<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--

-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue10/menu_issue10.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue10/lina_meruane/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">Razor Blades <span class="texto2">by <a href="../../issue10/lina_meruane/bio.php" class="link3">Lina Meruane</a>, Translated by Lina Meruane in collaboration with <a href="../../issue10/ronald_christ/bio.php" class="link3">Ronald Christ</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           &nbsp;<br>
              <p>It&rsquo;s what guys used to do to  their faces. With foam and a thick, soft brush, standing in front of the  mirror, carefully watching their every move so&rsquo;s not to cut themselves. But so did we, we  also watched ourselves in the shaky mirror of our amazement, shaving each  other, on the first break of every Monday and the last of every Thursday. We  would wait until our skin felt stubbly again and then begin the slow ritual that  would strip us of our hair. We didn&rsquo;t leave a trace of soap in the armpits; it  was so exhilarating, more intense each time, that soon we started running the  razor blade along our arms, around our calves, and up our thighs. We would  shave on time, as punctually as our arrival every morning at the tall,  spiked-iron fence; we were as sharp as the Inspector&rsquo;s insistent finger on the  bell. Shaving was just as mathematical a procedure as cheating during algebra  exams, when equations were solved and passed on in a loud murmur before the  blind eyes and deaf ears of our old teacher. But not all teachers were as old  or as deaf. We had to proceed with covert signs, whispers, keeping the secret  to ourselves.</p>&nbsp;<br>
</div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <p>Our bodies were  beginning to swell, transformed by unexpected curves and shadows: tits rising  at the same pace as the hair we removed thoroughly from our nipples, pubis  turning into a dark skein of wool that sometimes dripped blood, without  warning&mdash;all in perfect synchrony. The metallic taste of blood excited us, just like the  murmur of our hoarse voices, like the labyrinth we were passionately  penetrating. Eagerly we would start to work on the fuzz of our toes: the  Gillette slipped over our naked instep like a stainless steel sock, sliding up our thighs like cold pantyhose, opening a wedge of  pale skin in the froth of bathroom soap; the sharp caress crept around our  groin and then glided down from the navel and underneath the elastic band,  below the soft cloth of the underwear that we finally removed, and open your  legs, a little more you idiot, keep still, and we would crack up when we saw  the shiny tongue sticking out, the nervous burst that made us tremble. We  watched the kiss that our razor blade pressed on those lips. </p>
            <p>One of us  would stay outside, by the bathroom&rsquo;s black door at the end of a long hallway,  just after a bed of prickly roses out in the quad. Our lookout muffled our  whispers by loudly singing the royal anthem: God save her, repeating the words  in a litany until she caught a glimpse of the Matron, nosing around at the end  of the hallway. Then switching to<strong> </strong>our  country&rsquo;s national anthem, to let us know, and to distract the slim Matron who  puffed up her chest whenever she heard that stirring patriotic hymn, sticking  out her lips, further accenting the dark line of fuzz that we hoped, one day,  to shave off against her will. And then, good morning Miss, our accomplice  would slyly say, while we, back inside there, hid the razor blades, and Good  morning, my dear, replied the staff sergeant, but please, do continue, go on  singing, she urged, standing there a while longer, her eyes shut, enjoying  herself. The inspector lingered there quite some time, carried away, like a  watchman sleepwalking through his rounds; the danger always passed us by: we  got off the toilet, retrieved the concealed razor blades, already warm inside  our underwear, pulled up our uniform once more, and went on shaving each other.  Behind us, white-tiled walls. </p>
            <p>The rest of  my classmates did not suspect it either, or maybe they did, just pretending not  to. Never did one of them come over to us; none dared to venture into our  bathroom. It&rsquo;s as if they perceived it as a forbidden territory, marked off,  fenced in&mdash;as if a dirty warning sign emanated from our eyes. We let them  admire, out of the corner of their eyes, our obvious physical  superiority, our shiny knees and our mid-calf socks; from a distance they&rsquo;d  watch us in one corner of the cemented yard, peeling quinces. Because that&rsquo;s  what we did when we weren&rsquo;t in the bathroom: peel and peel quinces with our  little jackknives. We practiced our manual skills by skinning that sour fruit.  We competed in paring the longest peel, but the thick, opaque curl we were  stripping off always broke. We consoled ourselves for the failure by licking  the pulp, our tongues smarting as we burst into laughter. We were still  laughing when the bell rang and we had to fold up the metal blade and go back  to class. We kept the broken peel in a plastic bag: it was a precious  disinfectant for accidental slashes. </p>
            <p>Wednesday, and we were already anxious. In the last row,  sitting side by side, we scratched each other. Such intense itching when our  hair started to grow out; and after we had shaved, there was always more hair,  and thicker. Our nails left white tracks on our skin, but we refrained from any  expression of pleasure or pain, never for an instant taking our eyes away from  the blackboard where the old hag teaching Spanish explained subordinate clauses. We  had brand new razor blades, but recess was still fifteen minutes off and  Thursday a whole day away. Our impatience to get back to the bathroom was  beginning to make us feel weak: our will power was diminishing and then, right  in the middle of a copulative sentence, at the height of our most exasperated  scratching, the door opened and the headmistress came in with the new student.  The whole class stood up and repeated a greeting in English, in unison; then we  heard her name. But at that moment we didn&rsquo;t fix on the tough features of  Pilar&rsquo;s face, nor her penetrating gaze; our attention was not caught by her  astonishing height nor by that stranger&rsquo;s scrawny body tucked like death in the  dark polyester of her uniform. No, we were taken aback only by her bony calves covered  with hair. We saw nothing but that thrilling tangle, that mop of virgin hair  made our skin bristle in disgust and joy.</p>
            <p>A chill breeze  sliced through the wintry windows, our last winter, and there was Pilar,  defiant as a bonfire in a windy yard. There was only one seat left, in the  corner, at the end of the first row, and she took her place there, at the  wooden desk: took off the navy blue coat, her blue  sweater vest, and rolled up the sleeves to  shamelessly exhibit thick hair on her arms. Before sitting, she turned toward  the back of the room and, beneath thick, bushy eyebrows, her eyes slowly swung  back and forth among us, as though surrendering herself, as though letting us  lick her with our gaze. She freed her pony tail and began writing while we  hurried our pencils under the desks: doesn&rsquo;t look like a woman, read the first  line on the notebook sheet we circulated; that&rsquo;s right, too hairy, too skinny  for that much hair, another of us wrote. Somebody among us was picking  furiously at her fingernail when finally the hands of time moved and the Inspector  depressed the bell beneath her ramrod finger. We all ran together down the  hallway, past the bed of roses, and  into the bathroom, leaving nobody to stand guard. Franticly, heedlessly, borne  along by the fit and our own grunts, we flashed our blades in futile carnage.  Some against the others. Striving to liberate ourselves from Pilar&rsquo;s flaming  hair, her infinite mop of hair only enveloped us more, entangled us.</p>
            <p>Pilar walked  back and forth before us in the yard while we peeled our quinces. We let the  fruit&rsquo;s sour juice run down our hands, we sucked our fingers, imagining her spread-eagled on the white bathroom tiles. Her  insidious gaze, that afternoon, pierced through us. Then we saw her venture  slowly down the hallway, stop at the black door and shake her mane. We followed  her. We heard when she locked herself in the stall, its relentless flush. Did  she want it or didn&rsquo;t she? As she was washing her hands, we took up our  positions around her and pronounced to her how fine she&rsquo;d look afterward. Pilar  did not move when we took out our razor blades, but she turned pale, and we  guessed she&rsquo;d scream. We had to grab her by the ankles and arms, hold her  firmly down on the floor, shove a handkerchief between her teeth to silence  her. She resisted, but we pulled up her uniform, rolled down her socks, tugged  off her black shoes. She even had hair on her insteps, and that further excited  our passion: she&rsquo;d be so naked when we finished with her. So soft, so fair. She  kept twisting with her eyes wide open, and me, who held the Gillette in my  hand, who never ceased whispering: stay still, you should lie still, for your  own good, so I won&rsquo;t hurt you, I started to shave, slashing the skin at every  twist. Instead of frightening us, the blood urged us on. Our saliva would numb  the painful skin.</p>
            <p>The floor was  covered with hair and blood. Only her pubis remained intact when Pilar finally  stopped wrestling. For an instant we were afraid she was suffocating, or that  maybe she was bleeding to death on us, so there was nothing else to do but take  the handkerchief out of her mouth. Just you try to move, stupid, and you won&rsquo;t  have eyeballs anymore. Pilar was  sweating, her eyelids pressed shut, but breathing quietly now, and we sighed  because we dreaded having to fulfill that promise and kill her. The razor blade  was slitting the hems of her panties and, scrupulously, still without  uncovering her completely, it began shaving the skin exposed above the elastic  band, then downward, delaying the appearance of Pilar&rsquo;s precious, desired pubis.  The mounded, dark pubis. An ambiguous expression crossed Pilar&rsquo;s face as we  drew back the soft cotton fabric and saw that enormous tongue<strong> </strong>poking out from between the lip-like  folds, a tongue growing thicker, leaving us with mouths agape, speechless,  astonished for a moment as that dark tongue continued thrusting up. We threw  our razor blades down on the floor and kissed that mouth and then each other  with our tongues, maddened by the ecstasy of the discovery.</p>
            <p>&nbsp;</p>
            <p><strong>Hojas  de afeitar</strong></p>
          <P>Era lo que hac&iacute;an ellos sobre sus  rostros, con espuma, con una gruesa brocha de cerdas suaves, y mir&aacute;ndose  atentamente al espejo para no cortarse. Pero tambi&eacute;n nosotras nos mir&aacute;bamos en  el tembloroso espejo del asombro, rasur&aacute;ndonos, las unas a las otras, durante  el primer recreo de los lunes y el &uacute;ltimo de los jueves. Esper&aacute;bamos a que se  sintiera la aspereza sobre la piel para recomenzar el lento ritual que nos  desnudaba de ese vello rasposo. No dej&aacute;bamos ni un rastro de jab&oacute;n en las  axilas; y era tan excitante hacerlo, cada vez m&aacute;s intensa la emoci&oacute;n, que  pronto fuimos extendiendo el filo de la gillette por los brazos, por las  pantorrillas y los muslos. Nos afeit&aacute;bamos puntualmente, tan en punto como las  llegadas por la ma&ntilde;ana a la reja de fierro coronada de puntas; exactas como el  timbre que tocaba sin dulzura el dedo duro e insistente de la inspectora.  Rasurar era un procedimiento tan matem&aacute;tico como el de copiarnos durante los  ex&aacute;menes de &aacute;lgebra; las ecuaciones iban siendo resueltas y repetidas en un  sonoro cuchicheo a o&iacute;dos sordos de la vieja de ciencias. Pero no todas nuestras  maestras eran tan ancianas ni o&iacute;an tan mal. Hab&iacute;a que proceder siempre entre  se&ntilde;as y susurros, guardar para nosotras el secreto.  </P>        
          <p>Nuestros cuerpos iban hinch&aacute;ndose de a poco,  llen&aacute;ndose de bultos sorprendentes. Simult&aacute;neamente nos crecieron las tetas, se  levantaron nuestros pezones con pelos alrededor que tambi&eacute;n elimin&aacute;bamos con  esmero. El pubis se nos hab&iacute;a vuelto una madeja oscura que derramaba sangre,  sin aviso, sincronizadamente; esa sangre ten&iacute;a un resabio met&aacute;lico que nos  excitaba, como el murmullo de nuestras voces roncas, como ese laberinto que  &iacute;bamos penetrando apasionadamente. Con entusiasmo sol&iacute;amos empezar la tarea por  el pelillo que se asomaba sobre los dedos de los pies; la gillette sub&iacute;a por  los empeines desnudos como un acerado calcet&iacute;n, desliz&aacute;ndose por los muslos  como una panty, dejando un surco de piel p&aacute;lida entre el espumoso jab&oacute;n del  ba&ntilde;o; la filosa caricia se arrastraba por la ingle y luego descend&iacute;a fr&iacute;a desde  el ombligo hacia abajo, y por debajo del el&aacute;stico, de la tela suave del calz&oacute;n  que por fin quit&aacute;bamos, y separa las piernas, abre un poco m&aacute;s, idiota, qu&eacute;date  quieta, y nos entraba la risa al descubrir la lengua asom&aacute;ndose por el pubis,  la carcajada nerviosa que nos hac&iacute;a temblar espiando el beso que imprim&iacute;a en  los labios la hoja de afeitar. </p>
          <p>Una de nosotras se quedaba vigilando la  entrada del ba&ntilde;o, esa puerta negra al final de un largo corredor, tras la  espinosa rosaleda. La vigilante cubr&iacute;a nuestro murmullo cantando en voz alta  nuestro himno a la reina de Inglaterra, lo repet&iacute;a en una letan&iacute;a hasta que  ve&iacute;a a la inspectora en el fondo del pasillo, y entonces entonaba la canci&oacute;n  nacional, para avisarnos, para distraer a la delgada inspectora que hinchaba el  pecho al escuchar esa arenga patri&oacute;tica, que deformaba hacia delante los labios  haciendo m&aacute;s visible la oscura l&iacute;nea de vello que alguna vez, so&ntilde;&aacute;bamos,  afeitar&iacute;amos a la fuerza, y entonces, buenos d&iacute;as se&ntilde;orita dec&iacute;a nuestra  c&oacute;mplice mientras nosotras, ah&iacute; dentro, ocult&aacute;bamos las hojas de afeitar, y  buenos d&iacute;as hija, contestaba la sargenta, pero no se interrumpa, siga cantando,  le recomendaba, y permanec&iacute;a ah&iacute; un momento m&aacute;s, con los ojos cerrados,  disfrutando. La inspectora se iba como un sereno caminando dormido en su ronda;  el peligro siempre pasaba de largo y nosotras nos baj&aacute;bamos del retrete,  recuper&aacute;bamos las hojas escondidas y entibiadas dentro de los calzones, nos  levant&aacute;bamos otra vez el jumper y continu&aacute;bamos rap&aacute;ndonos, las unas a las  otras. Detr&aacute;s, los muros de azulejos blancos. </p>
          <p>Tampoco las dem&aacute;s compa&ntilde;eras sospechaban, o  quiz&aacute; s&iacute;, pero disimulando. Nunca ninguna se nos acerc&oacute;; ninguna os&oacute;  aventurarse por nuestro ba&ntilde;o. Era como si percibieran que ese territorio estaba  marcado, cercado; como si de nuestras miradas emanara una sucia advertencia.  Las dej&aacute;bamos admirar de reojo nuestra evidente superioridad f&iacute;sica, nuestras  rodillas lustrosas y los calcetines a media pierna; observaban de lejos el modo  obsesivo en que nosotras, en la esquina del patio de cemento, pel&aacute;bamos  membrillos. Porque eso hac&iacute;amos cuando no est&aacute;bamos en el ba&ntilde;o, pelar y pelar  membrillos con nuestras peque&ntilde;as navajas de acero. Ejercit&aacute;bamos nuestra  habilidad manual despellejando esa fruta &aacute;cida, compet&iacute;amos por lograr la monda  m&aacute;s larga sin que se partiera, pero el grueso y opaco rizo que &iacute;bamos sac&aacute;ndole  siempre se romp&iacute;a. Nos consol&aacute;bamos de ese fracaso lamiendo la pulpa que nos  dejaba la lengua &aacute;spera y re&iacute;amos a carcajadas. Todav&iacute;a nos est&aacute;bamos riendo  cuando sonaba el timbre y deb&iacute;amos doblar la hoja met&aacute;lica para regresar a  clases. Guard&aacute;bamos tambi&eacute;n las c&aacute;scaras rotas en una bolsa pl&aacute;stica, era un  precioso desinfectante para las accidentales incisiones.</p>
          <p>Era mi&eacute;rcoles y ya est&aacute;bamos inquietas.  Sentadas en la &uacute;ltima fila, en l&iacute;nea, nos rasc&aacute;bamos mutuamente. Qu&eacute; picor cuando  empezaba a salir el pelo, y desde que nos afeit&aacute;bamos cada vez sal&iacute;a m&aacute;s, y m&aacute;s  grueso. Nos dej&aacute;bamos marcas blancas sobre la piel con las u&ntilde;as, pero evitando  hacer ninguna mueca de gusto o de dolor, sin dejar un instante de fijar los  ojos en el pizarr&oacute;n donde la vieja de castellano explicaba las cl&aacute;usulas  subordinadas. Ten&iacute;amos hojas nuevas y todav&iacute;a quedaban quince minutos para el  recreo, pero faltaba un d&iacute;a entero para el jueves. La impaciencia por regresar  al ba&ntilde;o empezaba a debilitarnos: se nos hab&iacute;a ido adelgazando la voluntad, y en  ese momento, en medio de una oraci&oacute;n copulativa, en el instante m&aacute;s exasperado  de nuestra picaz&oacute;n, se abri&oacute; la puerta y entr&oacute; nuestra directora con la nueva  estudiante. Toda la clase se puso de pie y repiti&oacute; un saludo un&iacute;sono en ingl&eacute;s,  y despu&eacute;s escuchamos su nombre. Para nada nos fijamos entonces en las duras  facciones de Pilar ni en sus ojos penetrantes; no nos llam&oacute; la atenci&oacute;n su  sorprendente estatura, la escualidez de esa desconocida agazapada como la  muerte en el oscuro uniforme de poli&eacute;ster. S&oacute;lo nos desconcertaron sus pantorrillas  tapadas de pelo. No vimos m&aacute;s que esa excitante mara&ntilde;a: toda una pelambrera  virgen que nos eriz&oacute; de asco y de alegr&iacute;a. </p>
          <p>La brisa fr&iacute;a se colaba por las ventanas del  invierno, nuestro &uacute;ltimo invierno, y Pilar estaba ah&iacute;, desafiante como una  hoguera en un patio de viento. S&oacute;lo quedaba un asiento libre, en la esquina de  la primera fila y ah&iacute; iba a apostarse, en ese pupitre de madera: se quit&oacute; el  abrigo azul marino, el chaleco azul, y se arremang&oacute; para exhibir imp&uacute;dicamente el  espeso vello de sus brazos. Antes de sentarse volte&oacute; hacia atr&aacute;s y bajo sus  gruesas cejas hirsutas su mirada oscil&oacute; lentamente entre nosotras, como si se  nos entregara, como si se dejaba lamer por nuestros ojos. Se solt&oacute; la cola de  caballo y empez&oacute; a escribir mientras nosotras apur&aacute;bamos los l&aacute;pices debajo de  las mesas. No parece una mujer, dec&iacute;a la primera l&iacute;nea de la hoja del cuaderno  que hicimos circular. Es cierto, es peluda, es demasiado flaca para tanto pelo,  escribi&oacute; otra de nosotras. Alguna se ensa&ntilde;aba en el borde de la u&ntilde;a cuando por fin  se movieron las manos del tiempo y la inspectora hundi&oacute; su dedo tieso en el  timbre. Corrimos todas juntas por el pasillo, cruzamos la rosaleda, entramos al  ba&ntilde;o sin dejar vigilante. Fren&eacute;ticamente, descuidadamente, dej&aacute;ndonos llevar  por el arrebato y los gru&ntilde;idos, estrenamos nuestras hojas en una carnicer&iacute;a  in&uacute;til. Las unas contra las otras. Intentando librarnos del pelo ardiente de Pilar  su pelambrera infinita nos arropaba m&aacute;s, se nos iba ensartando. </p>
          <p>Pilar se paseaba ante nosotras en el patio  mientras pel&aacute;bamos membrillos. Dej&aacute;bamos correr el jugo de la fruta por  nuestras manos, nos chup&aacute;bamos los dedos imagin&aacute;ndola desparramada en nuestro  ba&ntilde;o. Su mirada insidiosa, esa tarde, nos cortaba el aire. Despu&eacute;s la vimos  aventurarse lentamente por el pasillo, detenerse en la puerta negra y agitar la  melena. La seguimos. O&iacute;mos cuando se encerraba en el retrete, su chorro  interminable. &iquest;Quer&iacute;a o no quer&iacute;a? Se lavaba las manos cuando nos apostamos alrededor  y le anunciamos lo bien que iba a quedar. No se movi&oacute; mientras sac&aacute;bamos las hojas  pero se puso p&aacute;lida: supimos que gritar&iacute;a, tuvimos que agarrarla de pies y  manos, sujetarla firme sobre el suelo, meterle en la boca un pa&ntilde;uelo para silenciarla.  Se resist&iacute;a, pero le levantamos el uniforme, le bajamos los calcetines, le  quitamos los zapatos negros. Ten&iacute;a pelo incluso sobre el empeine, y eso excit&oacute;  a&uacute;n m&aacute;s nuestra pasi&oacute;n por ella: qu&eacute; desnuda iba a quedar cuando termin&aacute;ramos.  Qu&eacute; suave, que p&aacute;lida. Pero segu&iacute;a revolvi&eacute;ndose con los ojos muy abiertos y  yo, que ten&iacute;a la gillette en la mano, que no paraba de susurrarle que se  quedara quieta por su bien, para no hacerle da&ntilde;o, empec&eacute; a rasurarla. A  cortarla cada vez que se mov&iacute;a. La sangre en vez de asustarnos nos azuzaba, nos  instaba a seguir. Nuestra saliva anestesiar&iacute;a los ardores de su piel. </p>
          <p>El suelo estaba cubierto de pelos y de  sangre. S&oacute;lo faltaba el pubis y Pilar por fin dej&oacute; de moverse. Por un instante  pensamos que se nos ahogaba con el pa&ntilde;uelo o que se nos estaba desangrando, y  entonces no nos qued&oacute; m&aacute;s que desocuparle la boca. Como te muevas, idiota, te quedas  sin ojos. Pilar sudaba con los p&aacute;rpados cerrados, pero respiraba suavemente, y  nosotras suspiramos porque tem&iacute;amos tener que cumplir esa promesa y matarla. La  hoja fue cortando su calz&oacute;n por los lados y, con mucho cuidado, sin descubrirla  por completo todav&iacute;a, empez&oacute; a afeitar primero la piel que luc&iacute;a arriba del  el&aacute;stico y despu&eacute;s hacia abajo, retardando la aparici&oacute;n del precioso y ansiado  pubis de Pilar. Su pubis hinchado y negro. Sonri&oacute; ambiguamente cuando quitamos la  tela y vimos aparecer esa enorme lengua asomada por sus labios, una lengua que  al engordar nos dej&oacute; con la boca abierta, sin palabras, at&oacute;nitas un momento  mientras la lengua oscura se iba levantando. Entonces tiramos al suelo las  hojas de afeitar y le besamos la boca y nos besamos con la lengua, enloquecidas  por el &eacute;xtasis del descubrimiento.</p>         </td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
