<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">


</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue7/menu_issue7.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue7/jo_baker/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">An excerpt from <em>The Telling</em><span class="texto2"> by <a href="../../issue7/jo_baker/bio.php" class="link3">Jo Baker</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           
              <p style="text-indent:14.15pt;">The light was fading. I was pretty sure I was lost. The car wasn&rsquo;t used to that  kind of driving and had started making a nasty whining sound on the bends. I  hadn&rsquo;t reached the Hall yet, hadn&rsquo;t passed a house in miles. I pulled in at the  side of the road, bumped up on to the grass, switched off the engine. There was  a breeze, a bird singing; it was so quiet. </p>
            <p style="text-indent:14.15pt;">I rifled through the junk on the passenger seat for  the directions, snapped them straight and peered at Dad&rsquo;s crabbed handwriting.  The car ticked as it cooled. If I&rsquo;d gone wrong, I couldn&rsquo;t see where. I&rsquo;d come  off the motorway at the right exit, taken that turn, passed the lake and the  farm. The next landmark was listed as Storrs Hall, a grand old house with a  tower, in woodland, off to the right of the road. The village would be shortly  after that. </p>
          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <p style="text-indent:14.15pt;"> I slipped another chip of chewing gum into my mouth,  crossed my &#64257;ngers, and turned the key in the ignition. The engine started &#64257;rst  time. Another ten or &#64257;fteen minutes, I told myself, pulling out on to the empty  tarmac, bothered by the low-level whine from somewhere down and to the left.  After that, I&rsquo;d have to think of something else, &#64257;nd someone, ask for  directions. But that was easier said than done: I hadn&rsquo;t seen a soul, hadn&rsquo;t  even seen another car, since I left the motorway. </p>
            <p style="text-indent:14.15pt;"> The tarmac spun on between stone walls and patches of  hedge. Wide scrubby &#64257;elds sloped up towards the sky; trees stood torn and  twisted by the wind. A building blurred past. I glanced back in the mirror. A  square-fronted house, its windows blank, and a vast stone barn standing in the  blue twilight. It made me notice the dark. I &#64258;icked my headlights on. </p>
            <p style="text-indent:14.15pt;"> The road ahead became a tunnel, and I hurtled down it  far too fast. Any minute I would catch up with the sweep of my own headlights  and blunder on into the darkness beyond. The road dipped into woodland.  Branches broke the sky into a &#64258;ickering craze. I eased my foot off the  accelerator as the road swept in smooth bends downhill. Glimpsed in passing, a  crenellated tower stood against the evening sky. Then &#64258;ash of wrought-iron  gates, a curve of gravel. The Hall: it must be, at last. I felt as if I&rsquo;d been  driving for ever. Even so, I wasn&rsquo;t keen to arrive. </p>
            <p class="CM10" align="center" style="text-align:center;line-height:16.9pt;"> * </p>
            <p style="text-indent:14.15pt;"> A  terrace of stone cottages &#64257;rst, and then a crossroads. A shop, a pub, a school,  a parish hall, none of them open. According to the directions, it was half a  mile down the village street, towards the church. I made the turn, and drove on  about half a mile, slowed to a residential-area crawl. And there it was. </p>
            <p style="text-indent:14.15pt;"> The cottage stood elevated and set back from the  street, six stone steps leading up to the front door. I pulled in at the side  of the road. Whitewashed walls glowed in the twilight; four front windows  re&#64258;ected back the evening sky. It looked like a child&rsquo;s drawing of a cottage. I&rsquo;d  seen it in a photograph, but then it had stood &#64258;at against a blue-summer sky,  and Mum had been sitting on the top step in jeans and a print blouse. Now it  loomed solid, stony. I got out, took a lungful of clean, cold, wet air. Reading  Room Cottage. The place they chose to be. </p>
            <p style="text-indent:14.15pt;"> The front steps were worn into hollows and the  handrail was skin-smooth. The clutch of keys weighed heavy in my hand, the old  leather key fob pressing against my curved &#64257;ngers, folding back on itself. </p>
            <p style="text-indent:14.15pt;"> I turned the key until it clicked. </p>
            <p style="text-indent:14.15pt;"> The door opened into the living room. I saw the faded  blue sofa-bed, sagging in the middle, the arms worn shiny. Next to it, the  smoked-glass coffee table from when I was a kid. Stuff that could be spared  from home. Stuff that would do for summer holidays and Easter breaks, while  they did the place up. Stuff that would do until they retired, until they lived  here. </p>
            <p style="text-indent:14.15pt;"> I went in and dropped my holdall. The carpet was  &#64258;attened and tracked with grey. A breakfast bar corralled off a stark kitchen  extension. To the right of it there was a staircase, modern, with separate  planks whacked into the wall and a banister of cheap dowel and unsmoothed wood.  The smell of the place hit me: a smell like forgotten Sunday dinners, damp,  long emptiness. </p>
            <p  style="text-indent:14.15pt;"> I wanted  to be home, stepping over toys, the &#64258;at smelling of coffee and baby and drying  laundry. </p>
            <p style="text-indent:14.15pt;"> I headed straight back out to fetch the rest of my  stuff from the car; it seemed to have got much darker already, as if I&rsquo;d  blinked, and afterwards something of that internal darkness lingered. I opened  the boot, lifted out Sainsbury&rsquo;s bags, and glanced up the village street. </p>
            <p style="text-indent:14.15pt;"> The tarmac was slick as graphite in the moonlight;  windows caught a gleam here and there. There were no lights on in any of the  houses. And beyond the street, the darkness seemed deep, and somehow absolute.  I knew that out there, the M6 was streaming with light and fumes, strip-lit  service stations were selling coffee and cigarettes and travel sweets, that  there were towns and cities and hospitals and people, teeming people; but it  didn&rsquo;t quite seem possible, didn&rsquo;t quite seem real. Not beyond this blue-black  night, a tree&rsquo;s bones, the call of some bird or other. </p>
            <p style="text-indent:14.15pt;"> I shivered. I slammed the boot shut, scooped up the  bags and scrambled up the steps. When I &#64258;icked on the light, a latticework of  shadows scattered across the room. The lampshade was one that Mum had made in a  craft class, out of string and glue and a now long-burst balloon. It was way  off-centre. It gave the room an uneasy feeling, as if everything were slipping  sideways, as if it were sinking. </p>
            <p style="text-indent:14.15pt;"> I dumped my groceries and took my bag upstairs. Here  and there I could see traces of something real and beautiful in the building.  Smoke-stained stone, ancient wood. Clues to what they&rsquo;d seen here, what they&rsquo;d  wanted to realize. They must have thought they had years to peel all this away;  the stained carpets, the greyed woodchip, the varnished plywood. That they would  be able to uncover something. </p>
            <p style="text-indent:14.15pt;"> I glanced into one of the bedrooms. Two single beds  lay draped with white candlewick. The curtains were thin and drooping. A  dressing table, varnished thickly brown, stood underneath the window with a  primrose-yellow kitchen chair pulled up to it. None of it was familiar, it must  have belonged to the previous owner, and there was a smell, a faint lingering  sourness that I couldn&rsquo;t identify. I pushed open another door: a box room,  stacked full of boxes; shoeboxes, cardboard boxes, a tangle of wire coat  hangers on the &#64258;oor. An old brown suitcase trimmed with aluminium that I  remembered from childhood airport carousels. Laundry bags full of books,  carrier bags stuffed with objects wrapped in newspaper. I lifted out a papery bundle,  weighed it in my hands, instinctively knowing the cool heaviness of it. I  peeled back the paper: the pewter jug, for big bold &#64258;owers, for daffodils in  springtime, long-stemmed roses in summer, dahlias in autumn. The sleek curve of  the metal sucked the warmth from my hands. I could smell newsprint, and the  jug&rsquo;s metallic tang. The room felt cold; it was as if the shadows had taken a  step closer. </p>
            <p style="text-indent:14.15pt;"> I could just go. I&rsquo;d be home by midnight. The &#64258;at with  its night-time smells of baby bath and milk; I&rsquo;d sneak into Cate&rsquo;s room and  kiss her head, her hair curling into sweaty ringlets, and pull the covers up  over her shoulder, and slip down the corridor and out of my jeans and into bed  beside Mark. He&rsquo;d mutter something, not really wake; I&rsquo;d listen to him breathe.  The alarm would go at half past six, and we&rsquo;d lurch awake, and I&rsquo;d be there,  where I shouldn&rsquo;t be, and that would make him right. Right about me, and about  what should be done about me. </p>
            <p style="text-indent:14.15pt;"> I pushed the &#64257;nal door. </p>
            <p style="text-indent:14.15pt;"> As it swung slowly open my mobile rang. </p>
            <p style="text-indent:14.15pt;"> I remember that moment, the sense of pause. Even  though I was looking down into my bag, ri&#64258;ing for my phone, there was something  about the space in front of me that brought back a memory of my Mum&rsquo;s jewellery  box, with its interior padding of pink baize; a memory of picking through her  bits and scraps of jewellery, laying them out on her counterpane. The room felt  absorbent, somehow, containing, as if it would take in sound and light and  warmth and hold it. </p>
            <p style="text-indent:14.15pt;"> My hand closed around the phone. Mark calling. I &#64258;ipped  it open, stabbed at the buttons with a thumb, the other hand reaching around  the doorjamb to fumble for a light switch. The room seemed spacious and high, a  reservoir of dark. The call connected. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Hey there,&rsquo; I said. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Hey. How is it?&rsquo; </p>
            <p style="text-indent:14.15pt;"> My hand brushed the inner wall. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Y&rsquo;know,&rsquo; I said. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Oh.&rsquo; </p>
            <p style="text-indent:14.15pt;"> I could hear the shift in tone. I should have been  more careful. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Doesn&rsquo;t matter,&rsquo; I said. &lsquo;Get it sorted, get home.  That&rsquo;s what we said. I knew it wasn&rsquo;t going to be pretty.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;You&rsquo;re just tired after the drive, Rache. You&rsquo;ll feel  better in the morning.&rsquo; </p>
            <p style="text-indent:14.15pt;"> After sleeping here, in one of those sagging beds,  absorbing the sour smell and the damp into my clothes and hair, waking in the  morning to walk the worn grey tracks across the carpet? I could feel myself contract,  like a touched snail: I couldn&rsquo;t face it. At the same moment the back of my  hand brushed against a lightcord. I caught it, and tugged. The light came on. I  saw the bookcase. I went towards it. </p>
            <p style="text-indent:14.15pt;"> I was opening my mouth, and drawing a breath to tell Mark,  when the phone bleeped, and went dead. I glanced at it; connection failed. I  slipped it into the back pocket of my jeans. </p>
            <p style="text-indent:14.15pt;"> The bookcase was massive. Maybe eight feet tall and &#64257;ve  feet wide. It was completely empty. It stood in the middle of the gable wall,  the ceiling sloping away to either side; it was the only point in the room high  enough to accommodate its size. It must have been built to &#64257;t. In all her talk  of this place, she hadn&rsquo;t once mentioned the bookcase. She&rsquo;d been keen to  discuss her growing list of books for retirement-reading, the books she hadn&rsquo;t  had time for in her thirty years of teaching; the books she&rsquo;d worn to shreds in  rehearsing them for A levels. Living here, she&rsquo;d binge-read, she&rsquo;d gorge on  these books; that was why the place had seemed so &#64257;tting, with its unusual  name. She&rsquo;d talked about all that, and their plans for renovation and  refurbishment, but she never once mentioned the bookcase. The wood was dark and  old, and there was something about its crafting, the way its parts were shaped and  &#64257;nished and &#64257;tted together that gave it an almost archaeological feel. No lines  were ruler-straight, no edges precision-angled: it was as though the wood had  been split along its fault-lines, smoothed and considered and pieced together  in the only way the grain would naturally allow. I laid my hand on a shelf. It  was silky, ridged with veins, and my own pulse beat back at me. </p>
            <p style="text-indent:14.15pt;"> Behind the bookcase, I could see the gable wall was  bare unplastered stone. Underneath, the floor was uncarpeted. It must have stood  where it had been built. The whole house had morphed and changed around it,  covered itself in woodchip and magnolia and varnish, but this had remained  here, darkening with the years. A kind of gentle heaviness descended on me,  like thick fog. It was as if I had been waiting to feel like this, as if I had  just been holding it off till I reached this moment, this room. I thought, I  can stay here, if I just stay here it will be all right. </p>
            <p style="text-indent:14.15pt;"> I noticed the rest of the room bit by bit, in a tired  way: the bare worn wood of the boards, the last blue evening light spilling in  through the window beside me, onto the varnished surface of a dressing table.  Over to the left, in the back wall of the house, a door stood open: the  bathroom, on the top &#64258;oor of the extension, directly above the kitchen. The  light was soft through the window that overlooked the street; it caught on the  dark blue satin quilt on the bed underneath, silvering the bulge of each pocket  of down. The wardrobe door stood open: clothes hung darkly inside. I walked  over to it and pushed the door shut; empty coat hangers chimed against each  other. </p>
            <p class="CM10" align="center" style="text-align:center;line-height:16.9pt;"> * </p>
            <p  style="text-indent:14.15pt;"> I lit  the &#64257;re and emptied out the bags of food that I&rsquo;d brought with me. I ate  straight from the packets; breadsticks, hummus. I swigged wine from  half-remembered petrol-station tumblers. I checked my phone. There was a  signal, so I phoned Mark. </p>
            <p style="text-indent:14.15pt;"> &lsquo;It just went completely dead,&rsquo; he said. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Yeah, the signal went.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;You didn&rsquo;t call me back.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;He-llo? Calling you back now?&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;It&rsquo;s been ages. I thought you&rsquo;d fallen through the &#64258;oorboards.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;You would have heard the crash.&rsquo; </p>
            <p style="text-indent:14.15pt;"> There was a smile in his voice. &lsquo;You over your  wobbles, then? You okay?&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;I&rsquo;m &#64257;ne. I&rsquo;m tired, like you said; it&rsquo;s a hell of a  drive. And I miss you both.&rsquo; </p>
            <p style="text-indent:14.15pt;"> The smell of woodsmoke, the taint of garlic and wine,  and a feeling that was like nostalgia, but not quite: it was all somehow  unexpectedly familiar. </p>
            <p style="text-indent:14.15pt;"> &lsquo;We&rsquo;ll be up to see you at the weekend, take back the  &#64257;rst load. Don&rsquo;t kill yourself over it, Rachel, you&rsquo;ve got plenty of time.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;A fortnight. There&rsquo;s not that much to do, really.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;You can always come home early. But take your time.  Don&rsquo;t overdo it.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;How&rsquo;s Cate?&rsquo; I asked. </p>
            <p style="text-indent:14.15pt;"> &lsquo;She&rsquo;s brilliant. She keeps telling me &ldquo;Mummy back  soon,&rdquo; like she&rsquo;s trying to reassure me. Mum bought her a new toy lion; she  keeps shaking it and pretending to growl and you have to be scared.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;That&rsquo;s great,&rsquo; I said, my throat thick. &lsquo;That&rsquo;s  really great.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;Yep,&rsquo; he said, &lsquo;Don&rsquo;t you worry. Just you get the  stuff sorted, and take care of yourself. We&rsquo;re doing &#64257;ne.&rsquo; </p>
            <p style="text-indent:14.15pt;"> I couldn&rsquo;t settle after that. I had one of Mum&rsquo;s  comfort reading books &ndash; <em>Pride and  Prejudice </em>&ndash; but even with that I couldn&rsquo;t get comfortable. The top of the  breakfast bar was only slightly wider than the base; my legs were twisted  around to one side. I &#64257;shed around for a toehold, glanced down, saw that the  bottom of the breakfast bar was formed out of the old back wall of the house;  where I was sitting had originally been the garden. The wall was a good  two-feet thick, made of great big undressed stones. It looked like a tree  stump; rooted in the earth, organic, cut abruptly off. </p>
            <p style="text-indent:14.15pt;"> I felt it for the &#64257;rst time then. A faint electrical  hum in the room. The fridge, perhaps. The cooker. The TV. </p>
            <p style="text-indent:14.15pt;"> I turned a page and took another sip of wine. It was  sour and dusty on the tongue. The hum continued, and I ignored it, but it soon  became intrusive, irritating. I slipped off the stool and crossed the kitchen  to check the fridge. I switched it off at the socket, and there was a kind of  wet, settling rattle, but the hum didn&rsquo;t change. I switched it back on again.  The cooker was off at the wall. The little portable TV was off, no standby  light glowing. I was puzzled. I stood a moment, breath held. The hum was still  there: if anything, it had grown. It wasn&rsquo;t even a noise as such; it was a  tingling, an agitation; it teased the hairs up on the backs of my arms. I  switched off the downstairs lights. In the sudden dark, my eyes swam with  coloured amoebic plaques. I stood and listened. The room seemed to soften in  the darkness. The &#64257;re&rsquo;s glow took on a new intensity, and I was aware again of  the old smell of the place; of damp and someone else&rsquo;s cooking and the faint  sour greenish smell. It was not a scent I associated with my parents. It must,  like the carpets, the wallpaper, and half the furniture, come from the time  before, from someone else. </p>
            <p style="text-indent:14.15pt;"> I brushed my hands down my arms, rubbed at them. </p>
            <p style="text-indent:14.15pt;"> The wiring must be dodgy. Or someone was vacuuming in  a nearby house. Or it was internal; post-motorway tinnitus. It could be  anything, really. The fridge clicked into gear; it hummed a slightly different  note, as if in con&#64257;rmation. </p>
            <p style="text-indent:14.15pt;"> The &#64257;re had crumbled down to glowing coals. I dropped  on another log and put the &#64257;reguard on. I left the lower &#64258;oor in darkness. It  felt quieter up in the Reading Room. Gentler somehow, more welcoming. </p>
            <p class="CM10" align="center" style="text-align:center;line-height:16.9pt;"> * </p>
            <p  style="text-indent:14.15pt;"> I wasn&rsquo;t  really asleep. I was conscious of the space beside me on the mattress, the dint  in the &#64258;ocking where my ankle pressed, the give of the springs beneath left hip  and shoulder. I was listening to the darkness. Amazing, just the distance of  it. Here and there, a splash of sound. A fox&rsquo;s bark &ndash; I recognized that &ndash; and a  bird&rsquo;s cry, and the sheep in the &#64257;eld behind the house calling back and forth  across the dark. And then just as I was drifting off to sleep, there was a  screech so loud and sudden that it startled me bolt awake, and I was staring  around the room in darkness, my heart going like a train. I reached for the  bedside lamp, but it wasn&rsquo;t there, of course; it was back at the &#64258;at. I lay in  the bed just looking into the black, and there was nothing: no movement, no  further sound, and my heart began to slow and settle. I got up out of bed and  went to switch on the light. The bookcase stood solid and dark and stacked full  of shadows. </p>
            <p style="text-indent:14.15pt;"> An owl, perhaps; or something killed by an owl, up in  the &#64257;elds behind the house. </p>
            <p class="CM10" align="center" style="text-align:center;line-height:16.9pt;"> * </p>
            <p  style="text-indent:14.15pt;"> Daylight.  There was a sense of weight beside me in the bed; if I just reached out a hand,  Mark would be there. Cate down the corridor in her little room: a mutter; she&rsquo;s  about to wake. The day teetering on its brink, ticking towards the shriek of  the alarm. The race of it all ahead of me; a battle with breakfast and with the  pushchair and bus, and Cate&rsquo;s clinging at the childminder&rsquo;s, and then work; and  the books dragged home from work, and lugging Cate on to the bus and she&rsquo;d be  tired and starting a cold, and holding me responsible. Feeding her, and bathing  her, and putting her to bed, and feeding us, and getting on with the marking or  reports or lesson plans, and an exhausted slump in front of the TV, watching  the news with the sound turned down, ice shearing into the waves, blood in the  dust. Hurtling, unstoppable change. Night, and bleached sleeplessness. Hours  staring into the dark. </p>
            <p style="text-indent:14.15pt;"> There was no alarm clock. The space in the bed was  cool and empty. The house was silent. I didn&rsquo;t have to be awake, not yet. </p>
            <p class="CM10" align="center" style="text-align:center;line-height:16.9pt;"> * </p>
            <p  style="text-indent:14.15pt;"> I spent  the morning wiping dead &#64258;ies from windowsills and &#64257;ngerprints from doors. I  dragged the old upright vacuum out of the kitchen broom-cupboard and did all  the carpets. I found a rusting cylinder of Vim under the sink and scoured the  baked-on meat juices from the inside of the cooker. I cleaned the bathroom. I  opened all the windows. The house smelt clean; of vacuuming and Vim and wet  spring air. It needed doing, it all needed doing. I wasn&rsquo;t wasting time. </p>
            <p style="text-indent:14.15pt;"> There was no means of making coffee in the house. No  cafeti&egrave;re, no percolator, not even one of those &#64257;lter efforts you balance on  top of a jug. So I made coffee in the teapot and brought it, with a cup and a  tea-strainer, back upstairs. I was going to go into the box room. I was going  to go in with my cup of coffee and start sorting through the stuff, unfurling  packages, assessing their contents, putting them in one of three piles,  destined for home, Oxfam, or the bin. But instead, I found myself standing at  the Reading Room window, looking out at the garden, at the nodding daffodils,  the bare branches of a tree trembling in the wind. At the end of the garden  stood an electricity substation; it was surrounded with green chain-link fence.  On its pebbledashed wall was a sign showing, in silhouette, a man falling over  backwards, a lightning bolt embedded in his chest. Beyond it was a farm, though  it didn&rsquo;t look as if it was still in use; there was no sign of animals. The  outbuildings were all painted pastel blue. </p>
            <p style="text-indent:14.15pt;"> All I could think was: this is an ending. The  beginning was lost; the &#64257;rst peeling of the helix from its twin, the &#64257;rst bulge  and split of cells: there is no way back to that from here. </p>
            <p class="CM10" align="center" style="text-align:center;line-height:16.9pt;">&nbsp;*</p>
            <p  style="text-indent:14.15pt;"> The  daffodils were bright yellow and the damson </span> tree was  in milky blossom. It was a fresh spring day and the sky was tumbling with  clouds. I&rsquo;d sat at the window in my Sunday dress, staring out across at Agnes&rsquo;s  house, nothing moving, till it seemed like everything &ndash; &#64258;owers, tree, Agnes&rsquo;s  four windows and brown front door &ndash; were all painted on the glass, and not real  at all. It was like looking at the windows in the church, of St Hilda and St  John, too deeply coloured, too neat, too calm to be anything like real. </p>
<p style="text-indent:14.15pt;"> My work lay beside me on the &#64258;ags, a book was  neglected in my lap. I had my shawl wrapped tightly around me; it was cold away  from the &#64257;re. No one came, and no one left, and I shivered in the draught, and  Mam scolded me for mooning about and wasting the day. The light began to fade. </p>
            <p style="text-indent:14.15pt;"> She left for the evening milking, and the boys were  playing out somewhere, and Sally was at the Forsters&rsquo; for her tea, and the house  was empty. </p>
            <p style="text-indent:14.15pt;"> I had wanted to stay with Agnes, but they wouldn&rsquo;t let  me. I&rsquo;d asked her mam to let me know when it was over, and she had said she  would send me word the &#64257;rst chance that she got. What good did I think I&rsquo;d do  anyway, my mam wanted to know. Hanging about, getting in the way? I&rsquo;d only  scare myself, and be put off ever marrying, and end up an old maid. But it  seemed to me that it would be better to be with her, to know how things went  with her, however badly they were going, than remain in ignorance for so long. </p>
            <p style="text-indent:14.15pt;"> Dad would be back soon. Once he was back, and given  his tea, I would just slip across the street and gently knock, and if someone  answered I&rsquo;d ask after Agnes, and if no one answered then I would just come  home, and no one need know I&rsquo;d been, and I&rsquo;d be no worse off than I was now. </p>
            <p style="text-indent:14.15pt;"> I had the kettle hot on the stove, the teapot standing  with the tea spooned in, the canister with its picture of a Chinaman and a lion  put back on the dresser. The bread and the cheese were cut, and a clean cloth  laid over them. There was nothing more to do. I leaned against the table,  chewed a &#64257;ngernail. Of my mam&rsquo;s con&#64257;nements that I could remember, none had  taken as long as this. </p>
            <p style="text-indent:14.15pt;"> My father&rsquo;s cap came bobbing slowly along the far side  of the garden wall. I poked up the &#64257;re, got the kettle steaming. He scraped his  way up the steps, and came in. His cheeks were &#64258;ushed: he brought a pool of  cool spring air with him, and the smell of his work, of horse and tobacco and  beer. He was in one of those slow, philosophical moods that he gets into when  he&rsquo;s had a drink or two. He saw the steaming kettle and the tea things set out  on the table, and shook his head, as if it were some fancy of mine to make him  his tea, but he was prepared to humour me and play along with it. Then he saw  my book lying on the windowsill, saw the work half done and lying on the &#64258;oor,  and his mood turned sharply. </p>
            <p style="text-indent:14.15pt;"> &lsquo;If you&rsquo;re going to waste your time reading that old  nonsense again,&rsquo; he said, his breath sweet with malt. </p>
            <p style="text-indent:14.15pt;"> &lsquo;It&rsquo;s Sunday, and it&rsquo;s <em>Pilgrim&rsquo;s Progress</em>, which is a &#64257;ne book for Sunday,&rsquo; I said  quickly. &lsquo;And it&rsquo;s better than many ways of spending the Lord&rsquo;s Day.&rsquo; </p>
            <p style="text-indent:14.15pt;"> He gave me a look, sat down in his chair, and kept  himself bolt upright in a poor imitation of sobriety. I made the tea and I gave  him his bread and cheese. I left him to pour his own cup and slipped out to  stand on our top step, and look over to Agnes&rsquo;s house. No candles lit there, as  yet. </p>
            <p style="text-indent:14.15pt;"> It was a lovely soft evening, a little way off dark.  The sheep were calling up in the back &#64257;eld, and someone was chopping logs up at  Goss House. A curlew &#64258;ew overhead, giving its shrill repeating cry. I went down  the front steps, crossed the road, the loose stones crunching loud underfoot. I  peered through the front window, but couldn&rsquo;t see anyone. I rested my ear to  the front door. I heard nothing but the beat of my own heart. I thought that  she had died. That she lay cold and dead upstairs. That they could not bring  themselves to tell me. I lifted the latch; the door creaked open, and I stepped  inside, on to Agnes&rsquo;s clean-sanded kitchen &#64258;oor. </p>
            <p style="text-indent:14.15pt;"> The room was stuffy; I could smell something sweet and  rich and spiced. There were &#64257;gures slumped at the kitchen table. I moved closer  in the gloom and saw that it was Mrs Skelton and Agnes&rsquo;s mam, and that they  were sleeping, their heads resting on folded arms. In the middle of the table  was a half-eaten batch-cake, the crumbs scattered like grain, whole raisins  lying plump on the scrubbed deal tabletop; the scent sweetened the air. Agnes  had made the cake for eating after the baby came, moving slowly, bending  red-faced at the stove, with her belly vast and in the way. Between then and  now was last night, and the walking up her garden, as far as the apple tree,  and back. She had paused when the pains came, her eyes screwing tight, and her  mouth opening. She whispered to me, so that the women wouldn&rsquo;t hear, &lsquo;I can&rsquo;t  do this, I can&rsquo;t do this,&rsquo; and I hissed back to her, &lsquo;Yes you can, of course  you can, it will be all right,&rsquo; because I was thinking, everybody that walks  the earth is born, it happens every day. Then her breathing changed, and her  eyes went distant and glossy, as if she were looking inward; she did not look  like Agnes any more, and the women had brought her upstairs and sent me home,  and I began to be afraid for her. But it was over now, because there were cake  crumbs and tea-stained cups. This was not a scene of mourning, these women  sleeping with their heads on their arms, the smell of spice, the huff and  whistle of their breath: she had lived through it. They had been too tired, too  exhausted by their labours, to think of telling me. </p>
            <p style="text-indent:14.15pt;"> I slipped past them and went up to Agnes&rsquo;s room; the  room she has had since she was married. Agnes was lying in the bed, sleeping,  the covers pulled tight over her. Her face had the same pulled-tight quality as  the sheets. Her hair lay in a thick dark braid over her shoulder and down over  the quilt. The room smelt of blood, but there was no blood to be seen. She  looked so completely done-in, so pale and wan. I came closer and saw the baby;  it was tucked in the crook of her arm. It was red, dry-looking, its eyes  pinched shut. Its head was a strange shape, bulged and squashed. It didn&rsquo;t look  like her. </p>
            <p style="text-indent:14.15pt;"> I wanted to touch her, but I couldn&rsquo;t bring myself to  do it. </p>
            <p style="text-indent:14.15pt;"> I heard the stairs creak and lifted my sleeve to my face  to blot away the wet. Her mam appeared and came over to me, moving quietly in  stockinged feet. She stood beside me. Her face was a maze of wrinkles; she  smelt of tobacco and bad teeth. </p>
            <p style="text-indent:14.15pt;"> &lsquo;A boy,&rsquo; she said. &lsquo;We&rsquo;re calling him William Stephen,  same as his father.&rsquo; </p>
            <p style="text-indent:14.15pt;"> The words whistled through the gaps in her teeth. She  went on talking, the sound hissing and wet, and there was a constriction in my  throat, and my nose felt raw inside. </p>
            <p style="text-indent:14.15pt;"> &lsquo;I said to her last night, it&rsquo;s taking that long it&rsquo;s  bound to be a boy,&rsquo; she said. &lsquo;Girls are that much easier, God grant her a girl  next time.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;I&rsquo;d best go.&rsquo; </p>
            <p style="text-indent:14.15pt;"> I turned to shift past her, and she was in front of me  a moment, her hair combed into a dry white parting, her shawl greasy and  threadbare, her skin creasing happily. She&rsquo;d seen it all before, of course,  seen how much worse it can be. She had ten children that I knew of, and she had  delivered all her six daughters&rsquo; babies. She turned to leave, and I followed  her out towards the landing. </p>
            <p style="text-indent:14.15pt;"> There was a pail tucked out of the way behind the  door. I&rsquo;d passed it unnoticed on the way in. It was full of blood-soaked rags.  The blood was crimson. On the &#64258;oor next to it was a folded blanket: it had been  folded to hide the worst, but I could see the corner of what must have been a huge  bloodstain. I looked back at Agnes lying white against the white sheets. I  could hear the stroke of the older woman&rsquo;s stockinged feet on the stair treads.  I turned again and went after her, the weave of her grey plaits pinned up like  a rush basket on the back of her head. Halfway down the stairs she stopped, and  looked up at me as if out of a hole. </p>
            <p style="text-indent:14.15pt;"> &lsquo;If you&rsquo;ve got any old linen spare, can you bring it  over, and any lye you&rsquo;ve got made up?&rsquo; </p>
            <p style="text-indent:14.15pt;"> I nodded, my face feeling cold and numb. Agnes and I  had shredded old sheets and shifts and shirts until we were covered in thread  and lint and Agnes had laughed and said it looked like it had snowed indoors. </p>
            <p style="text-indent:14.15pt;"> I managed to speak. &lsquo;Is it often this bad?&rsquo; </p>
            <p style="text-indent:14.15pt;"> Agnes&rsquo;s mam shrugged. &lsquo;Every time is different.&rsquo; </p>
            <p style="text-indent:14.15pt;"> She turned to go on down the stairs, as if this was my  question answered. I stood there, feeling cold. I had said that it would be all  right. </p>
            <p style="text-indent:14.15pt;"> I could hear the women moving around in the kitchen,  and low voices: Mrs Skelton was awake and they were talking softly. I heard the  clunk of stove-iron and clink of china as they made tea. I went down the stairs  and straight outdoors. I needed air. </p>
            <p style="text-indent:14.15pt;"> Outside a &#64257;ne soft rain was falling. I pushed my hair  back, tucked my shawl over my head and lifted my face to the clouded sky. I tried  to pray. I tried to thank God for her safe delivery, but my prayers melted in  the rain. I leaned there against the doorjamb and I cried sel&#64257;sh tears. I  couldn&rsquo;t do without her. </p>
            <p style="text-indent:14.15pt;"> I heard the racket of clogs on the wash-house lane,  voices; it could be my mam back with the other hands from Storrs Farm. I wiped  my palms across my cheeks and ran for home. </p>
            <p style="text-indent:14.15pt;"> I came in and started talking brightly to Dad, saying  how Agnes had had a boy, that they were calling it William Stephen and what was  the point giving a child the exact same name as its dad, he&rsquo;d only get pet  names all his life so you might as well think of something new to start with. I  had my shawl off and was marching over to the &#64257;re to get the kettle on again so  that it was hot for when Mam came in, and then I saw him. </p>
            <p style="text-indent:14.15pt;"> He&rsquo;d been sitting in Mam&rsquo;s chair. He was getting to  his feet. He was dark-clothed and tall; a good span taller than my father. Tall  as the Reverend, though lean, and his clothes seemed more like a working man&rsquo;s.  I don&rsquo;t know what it was about his features &ndash; the  dark eyes, the strong nose and heavy brows, the clean-shaven lip and chin &ndash; but  something just kept me looking at him. As if his face were a puzzle, and I couldn&rsquo;t  work it out. </p>
            <p style="text-indent:14.15pt;"> Then I realized what it was. I&rsquo;d never seen him  before. I couldn&rsquo;t remember the last time I&rsquo;d come across someone that I had  never seen before. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Ah Lizzy,&rsquo; my father said, &lsquo;this is Mr Moore.&rsquo; </p>
            <p style="text-indent:14.15pt;"> I nodded. &lsquo;Good evening.&rsquo; </p>
            <p style="text-indent:14.15pt;"> He dipped his head, returned the greeting. His voice  was  strangely  accented; he was not a local man. I reached up to smooth my hair and became  suddenly conscious of my hands, of how chapped and rough they were, calloused  as an old hedger&rsquo;s. I tucked them behind my back. I&rsquo;d never, not until that  moment, thought of my hands as anything but cold or sore or deft or fumbling. I  don&rsquo;t think I&rsquo;d ever thought about my hair at all. I couldn&rsquo;t think what to  say. My father leaned back in his seat, grinning. Mr Moore didn&rsquo;t say anything,  just looked at me, and didn&rsquo;t smile. The silence continued. I began to think he  was expecting something from me. He was in working clothes, but his stature and  carriage were that of a gentleman. Was he waiting for me to curtsey? I glanced  back at Dad. He nodded at me, his lips pursed. I turned to Mr Moore, looked him  in the eye, and curtseyed. He held my gaze, watching as I bent one knee,  wobbled, scraped my clog toe along the &#64258;ags and dipped my head stif&#64258;y. I have  never made a graceful curtsey in my life. For a moment, his face was sober, his  brows knotted. Then he laughed, his face breaking up into creases. </p>
            <p style="text-indent:14.15pt;"> &lsquo;You mistake me,&rsquo; he said. </p>
            <p style="text-indent:14.15pt;"> I felt my cheeks colour. &lsquo;So it seems.&rsquo; </p>
            <p style="text-indent:14.15pt;"> He stopped laughing then. My face burned. </p>
            <p style="text-indent:14.15pt;"> Dad made a clumsy joke about the re&#64257;nements of the  establishment, and I turned away, and went to tidy up my work, and clear the  leftovers of his tea, and all the time I was blushing, &#64257;ercely conscious of  myself, of how ungainly and uncouth I must seem. I slipped upstairs, and washed  my face in yesterday&rsquo;s water. I loosened my hair, gave it forty strokes,  plaited it and pinned it up again. I looked at my hands, the yellowed calluses  on the palms, the nails stained dark and rough. I soaked them in the water and  scrubbed at them. I heard Mam come in downstairs. I heard her greeting. She  called Mr Moore by name, which was a surprise to me. I looked at my hands.  Pinker, a little softer, still badly stained, the nails worn dull with work. I  went downstairs to help Mam get the supper. </p>
            <p style="text-indent:14.15pt;"> Mam and I were at the table. She was spooning tea from  the canister. One for each of us. One for the pot. One for Mr Moore. So he was  staying for supper. Over at the &#64257;reside, Dad was talking to him. Mam was  telling me what else needed to be done that evening and what was to be done  tomorrow when I rose. I nodded, trying to keep my attention on her, and not let  it drift towards the &#64257;reside. Every so often, Mr Moore glanced over. I kept my  attention on the loaf and the neat portioning of slices. One for each of us.  One for him. </p>
            <p style="text-indent:14.15pt;"> Then Mr Moore spoke, and Mam&rsquo;s words faded out of my  thoughts, and all I could do was listen to him. Dad must have asked him about  the towns and cities to the south, because he was giving an account of them.  Leeds, he said, was like a midden, &#64257;lthy, all of a fester, a summer&rsquo;s heat  would suf&#64257;ce to make it burst into &#64258;ames. Manchester was a tinderbox: any  reckless hand might strike the spark. People were arming themselves, he said;  in towns and villages all over the country, he&rsquo;d seen arms hanging over the  &#64257;replaces in the poorest houses. </p>
            <p style="text-indent:14.15pt;"> His voice, his manner and what he said: it reminded me  of something, but I couldn&rsquo;t quite remember what. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Everybody&rsquo;s spirits are down,&rsquo; Dad said. &lsquo;The bad  seasons and these unchristian taxes. People don&rsquo;t like going hungry.&rsquo; </p>
            <p style="text-indent:14.15pt;"> Mr Moore half shook his head. &lsquo;When an employer says  there is a slump in trade, and makes a reduction in wages, a man who already  works every hour he can to watch his wife and children starve must feel the  injustice of his circumstances as keenly as he feels brute hunger. What can he  do? He can&rsquo;t take his labour elsewhere, since if one employer makes a  reduction, the others follow. They are reducing wages now, all across the  region. And if there is a slump, then by God but the mill-owners are doing well  out of it. Oversby&rsquo;s building his new Hall on the strength of the current  crisis.&rsquo; </p>
            <p style="text-indent:14.15pt;"> I realized that I was staring at him. His words and  the manner of his speaking made me stare. </p>
            <p style="text-indent:14.15pt;"> &lsquo;They do well, the Oversbys,&rsquo; my father said, seeming  to think they were in complete agreement. &lsquo;That&rsquo;s a &#64257;ne new house they&rsquo;re  building up at Storrs. A man needs a little land, a little seed-money, if he&rsquo;s  to make anything of himself.&rsquo; </p>
            <p style="text-indent:14.15pt;"> Mr Moore said nothing for a moment. He inclined his  head, and when he spoke, it was quietly, almost too calmly. &lsquo;You know my  position, a joiner on the new hall, and you know I need the work as much as the  next man. But every peg I hammer home seems like a cof&#64257;n nail to me.&rsquo; </p>
            <p style="text-indent:14.15pt;"> He was still as a rock, the whole of his body, but for  his hands; they did not cease moving. He pressed his &#64257;ngertips together; his  &#64257;ngers slid and meshed and separated. These slight motions seemed to be  connected with what he said, as if he felt the distress in his own body and  could not be at ease; as if his hands were eager to be at other work. His thumb  rested for a moment between his lips, his teeth teasing at the skin beside the  nail. I noticed my own hand was at my mouth, my own knuckle resting in the wet  between my lips. I dropped my hand and looked away. </p>
            <p style="text-indent:14.15pt;"> &lsquo;I take the money that could be used to pay his  workers decent wages, and you will take it from me, and that is how we must  live, and so all our hands are stained with this guilt, however little we  intend it. We cannot be free of it.&rsquo; </p>
            <p style="text-indent:14.15pt;"> I knew what he reminded me of. Years ago, when we were  girls, a preacher had come to give witness to the Lord from a tree-stump on the  green. Our mams had forbidden us to go, so me and Agnes sneaked up through the  &#64257;eld behind the green, huddled down behind the wall among the buttercups and  wild carrot and long grass, and listened to the preacher&rsquo;s great strong voice,  his passionate words. We scared ourselves witless with what we heard about the  Elect and Grace and the Second Coming and the End of Days. I felt it again, the  same blend of fear and guilt, a sense of the coming apocalypse; and with it a  new feeling that I couldn&rsquo;t name. I was vexed at being laughed at, but there  was more to it than that. The kettle began to rattle and boil, and I remembered  the tea. I had to go to the stove, right between Mr Moore and my dad, and bend  to get the kettle. They paused in their talk a moment, and I was all too  conscious of myself and of the way my cheeks &#64258;ushed in the heat from the &#64257;re. </p>
            <p style="text-indent:14.15pt;"> Ted and John bundled in, red-cheeked and full of  buttoned-down laughter. Mam sent me to the larder for preserves, though it was  Lent, and there were only a half-dozen stone jars left on the shelves. Then  Sally came in, looking prim and pretty. She had been up at the schoolhouse  sewing with Mrs Forster. The younger ones took their supper to their stools and  sat to eat, and I kept company with Mam, standing at the table to eat our bread  and apple-jelly, while the men sat by the &#64257;re and ate theirs. Sally wanted to  know about the baby and wanted to tell me about the dress Mrs Forster was  making, but I didn&rsquo;t want to talk, didn&rsquo;t want to listen to her, didn&rsquo;t want to  think about the blood and the baby, and all the time she talked I couldn&rsquo;t hear  what Mr Moore was saying. My mam was now too tired for conversation, she just  leaned against the table, and sipped at her tea, and ate her bread and jelly as  if it were almost too much of a bother for her to do it. We cleaned up the  plates and put them away, and still Mr Moore lingered there, listening to my  father, who now was talking about the Enclosure. I didn&rsquo;t like it when Dad got  talking about the Enclosure. It seemed so long ago now, and there was nothing  to be done about it, and it made him nasty to re&#64258;ect on it, and I could not  imagine what kept Mr Moore there listening to him, when he could have been off  home hours before. He couldn&rsquo;t have known the trouble he was courting. </p>
            <p style="text-indent:14.15pt;"> I&rsquo;d go up to my room and read and get myself out of  the way. There was a little light left: I could get a few pages read at least  before Sally came up and started wittering about bonnet trimmings or the baby.  It didn&rsquo;t cross my mind that I&rsquo;d be remarked on, either in my going or my being  gone. I had my hand on the stair-rail, my foot on the &#64257;rst tread, and my new  chapbook about Robinson Crusoe under my arm, when Dad called out after me,  asking where I was off to. </p>
            <p style="text-indent:14.15pt;"> I turned and went back to him, bent to give him a kiss  on his cheek, and said goodnight. The hem of my skirt brushed against Mr Moore&rsquo;s  booted feet, and I caught his scent for the &#64257;rst time: the smell of cut wood.  There was wood dust in his hair. </p>
            <p style="text-indent:14.15pt;"> &lsquo;You&rsquo;re not up there any more,&rsquo; Dad said. </p>
            <p style="text-indent:14.15pt;"> I looked at him, not comprehending. </p>
            <p style="text-indent:14.15pt;"> &lsquo;You&rsquo;re down here. You and Sally. You&rsquo;ll be good and  warm with the &#64257;re.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;You mean sleeping?&rsquo; I asked. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Of course I mean sleeping.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;But &ndash;&rsquo; </p>
            <p style="text-indent:14.15pt;"> Ted laughed. Only then did it dawn on me what was  going on. Mr Moore was lodging with us. He was to have our room; mine and  Sally&rsquo;s room, and we were to sleep downstairs. There&rsquo;d been talk of a lodger  for a while, but nothing had been done, and I&rsquo;d thought the idea had been  forgotten. I looked down at the &#64258;oor, the rag rug, the ash on the hearthstone.  I will sleep like Cinderella tonight, I thought, and every night until he&rsquo;s  gone, and I will not have a moment&rsquo;s peace or solitude until he goes. In the  corner of my eye, I could see Mr Moore looking down at his hands, his right  index &#64257;nger bent and pressed down hard with the thumb of the same hand, so that  the &#64257;ngertip nearly touched his palm. The knuckle cracked, he looked up, and  our eyes met. His eyes were brown and clear as peat-water. He looked a little  ill at ease. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Go and get what you need down from your room, and put  it in the chest,&rsquo; Mam said, &lsquo;and then Mr Moore can go up when he wants to.&rsquo; </p>
            <p style="text-indent:14.15pt;"> My eyes left his. I turned away. I went up to our  room, and fetched bedding and clothes and brought them down and put them in the  chest, and then went back for the books I had up there, and rearranged the  crocks on the dresser to make space for them, and moved aside the Bible and the  prayer book, and pushed my <em>Pilgrim&rsquo;s  Progress </em>and my chapbooks in beside them, and all the while the pair of  them were sitting there at the &#64257;re, my father smiling and watching me as I made  the arrangements. Mr Moore didn&rsquo;t look around at me, which was good, because I  could not have easily met his eye. </p>
            <p style="text-indent:14.15pt;"> It was pitch dark by the time Sally and I had got the  bedding spread out and undressed and laid ourselves down to sleep. The &#64257;re was  a low smoulder. I was beginning to drift into sleep, thinking that another  night, when I was not so tired, I&rsquo;d stir up the &#64258;ames a bit, put a few sticks  on, and I&rsquo;d be able to read in the &#64257;relight, and it wouldn&rsquo;t be so bad. It was  good just to be lying down, and I didn&rsquo;t really feel the hardness of the &#64258;oor,  and my eyes were closing, and I was thinking how Agnes hadn&rsquo;t seen the new  chapbook yet, that I&rsquo;d take it over and read to her in bed tomorrow evening,  and when she was well enough, she&rsquo;d sit in her kitchen, and I&rsquo;d do her cleaning  or some baking for her. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Are you never going to get married?&rsquo; </p>
            <p style="text-indent:14.15pt;"> I opened my eyes. &lsquo;What?&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;You were nineteen last birthday,&rsquo; Sally said. </p>
            <p style="text-indent:14.15pt;"> &lsquo;I know how old I am.&rsquo; </p>
            <p style="text-indent:14.15pt;"> She took a noisy breath. &lsquo;I was thinking what with  Agnes having the baby now, you would be thinking of it, you could marry Thomas  and move out and have babies of your own.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;You&rsquo;ll wear yourself out, thinking like that.&rsquo; </p>
            <p style="text-indent:14.15pt;"> She rolled on to her side, pulling the blankets with  her. &lsquo;You could have your own room then too, though I suppose you&rsquo;d have to  share it with Thomas.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;Leave off, will you?&rsquo; </p>
            <p style="text-indent:14.15pt;"> She sniffed indignantly. &lsquo;It isn&rsquo;t just me.&rsquo; </p>
            <p style="text-indent:14.15pt;"> I leaned up on an elbow, looked over at her. &lsquo;What do  you mean?&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;Oh nothing.&rsquo; </p>
            <p style="text-indent:14.15pt;"> I prodded her. She yelped in protest. I said, &lsquo;Tell  me; you&rsquo;ll have no rest till you do.&rsquo; </p>
            <p style="text-indent:14.15pt;"> She rolled back over and looked me in the eye. I  remember her eyes, dark and glossy, catching the &#64257;relight, and her smooth young  skin glowing pale. &lsquo;Our mam was saying that we&rsquo;re too crowded here, I heard her  say it. And Dad agreed.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;They should have thought about that before they  invited that man in. There&rsquo;s just him taking up a whole room to himself while  us two have to sleep down here, and that&rsquo;s just daft, it makes no sense at  all.&rsquo; </p>
            <p style="text-indent:14.15pt;"> Sally shrugged and heaved herself over again; &lsquo;He  could hardly have the boys&rsquo; room, it&rsquo;s too small, and you wouldn&rsquo;t wish this on  our mam at her age.&rsquo; </p>
            <p style="text-indent:14.15pt;"> Just as I was about to ask whether she knew if he&rsquo;d be  stopping long, she said, her back still turned to me, &lsquo;I&rsquo;m to be apprenticed  soon, you know, Mrs Forster is arranging it for me.&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;Who to?&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;Mrs Forster&rsquo;s milliner at Settle; one of the girls is  leaving to set up for herself, and when she does, I&rsquo;m to be indentured in her  place.&rsquo; </p>
            <p style="text-indent:14.15pt;"> I rolled on to my back, lay there with the blanket  pulled up to my chin. &lsquo;What did our mam say?&rsquo; </p>
            <p style="text-indent:14.15pt;"> &lsquo;It&rsquo;s clean work, and I&rsquo;ll be mixing with a better  sort of people. She&rsquo;s glad.&rsquo; </p>
            <p style="text-indent:14.15pt;"> Time passed in silence, and the church clock chimed  ten. </p>
            <p style="text-indent:14.15pt;"> &lsquo;Good for you,&rsquo; I said. </p>
            <p style="text-indent:14.15pt;"> Sally muttered something, but her breath was  coming softer, and I knew that she was almost asleep. The blanket scratched  against my chin. I turned, tugged at the covers, and saw that there was light  overhead, sieved by the boards, slipping down between them, hair-thin, golden.  He was awake up there, up in our old room. He had a candle burning. He sat in  light.</p>
<p>&nbsp;</p><P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
