<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Book Antiqua";
}
p.MsoBodyText {
margin:0cm;
margin-bottom:.0001pt;
text-align:justify;
line-height:200%;
font-size:12.0pt;
font-family:"Book Antiqua";
}
p.MsoBodyTextIndent {
margin:0cm;
margin-bottom:.0001pt;
text-indent:36.0pt;
line-height:200%;
font-size:12.0pt;
font-family:"Book Antiqua";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="10%" align="right" valign="top">
      <?php include("../../issue3/menu_issue3.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr>
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr>
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2"><em>Three Beds </em><span class="texto2">by
            <a href="../../issue3/michael_blumenthal/bio.php" class="link3">Michael
            Blumenthal </a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr>
          <td height="219" colspan="2" valign="top" class="texto"> <div align="left" class="texto2">
              <br><p>The boy, hardly nineteen, was the son of the renowned  Israeli sculptor David Yogev and his beautiful, much younger, wife Sarah. He  was a beautiful young man as well, and, what&rsquo;s more, intelligent and athletic  into the bargain, possessed of the kind of calm and reticence even very few  adult men could pride themselves on. So it was no wonder that older  women&mdash;particularly those afflicted with unhappy marriages or sexually  uninterested husbands-- took an interest in him. </p>	
              <p>It was no wonder, too, that Daphna Feuerstein,  who had seduced his far shyer and less attractive older brother Etan several  months before, would begin to show an interest in him as well. The two boys&rsquo;  bedrooms in their parents&rsquo; Tel Aviv apartment on En Harod Street were only  inches apart and the temptation for an attractive woman of thirty-five to  parade around in various states of undress in front of two hardly  post-adolescent young men was simply too great to resist. </p>         </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr>
          <td colspan="4" rowspan="2" valign="top" class="texto2"> 
            <p>He had had girlfriends before&mdash;too many for a boy his age,  some family friends insisted&mdash;but his father had been a young man of notoriously  varied romantic experience, so it was no surprise that the branch hadn&rsquo;t fallen  far from the tree. His older brother, Etan, had also inherited a great deal  from his father. But in his case it was the sensitive and artistic (and,  insofar as the details of the quotidian life were concerned, mostly  dysfunctional) side. Already a published poet and accomplished watercolor  painter by his 20<sup>th</sup> birthday, Etan was possessed of a radically  otherworldly air, complete with a state of physical dishevelment and untidiness  that made him far less attractive to women than his popular and exceedingly  well-adjusted brother&mdash;skier and windsurfer <em>par excellence</em>, star  student, budding veterinarian, and already what Elvis Presley might have called <em>&lsquo;a hunk a hunk of burning love.&rsquo;</em></p>
		
            <p>Daphna Feuersten had been Etan&rsquo;s first lover, and it  rendered matters no less untidy within the Yogev family that, in addition to  being the mother of three young children, she was also the daughter of David  Yogev&rsquo;s best friend. Along with that, she was nearly fifteen years older than  the young virgin she had so eagerly taken to bed, and nearly seventeen years  older than his younger brother, to whom, she liked to think, she would have far  less to teach.</p>
            <p>Whatever it was she had, or didn&rsquo;t have, to teach young  Simon Yogev, she assumed, she would have plenty of time to find out. She  planned on this being a long relationship&mdash;far longer, at least, than the one  with his brother had been. As she saw it, it had more potential. She loved the  scent of Simon&rsquo;s body, the taste of his semen, she loved the soft furry hair on  his legs and his lithe, muscular chest, and, perhaps above all, she loved the  tight black curls on his head, loved running her fingers through them when they  made love, and loved, even, the silence with which he responded to her forceful  vocal demonstrations of ecstasy and pleasure.</p>
            <p>Her estranged husband, Hanan, was an artistic and  attractive man too&mdash;<em>and</em> had gradually become rich into the bargain.  When they first met at a Tel Aviv nightclub, he had been a struggling jazz  musician, a man who had an easy way with women and a difficult time paying the  bills. Then, once their first son was born, he had decided that the combined  life of a struggling artist and a family man wasn&rsquo;t for him, and, spotting a  void in Tel Aviv&rsquo;s heady economy, had opened bicycling messenger service  catering to the new boom in internet and high-tech companies. Soon there was  plenty of money to go with the music. </p>
            <p>Their other two children, a boy and a girl named Rami and  Timla, had been born in rapid succession, and soon thereupon there followed a  large house in Tel Aviv&rsquo;s airy and affluent Jaffa district. They seemed to have it all:  looks, money, three beautiful children. The kind of couple others&mdash;Simon and  Etan&rsquo;s mother among them&mdash; pointed to with a combination of adulation and envy.</p>
            <p>But, as was almost always the case, cracks and crevices  were beginning to form just beneath the smooth veneer of the enviable. Though  hardly inexperienced during her adolescence in Tel Aviv, Oslo  and Budapest  (her father was an Israeli-born Hungarian, her mother a Norwegian), Daphna  Flinker had married young&mdash;at hardly twenty&mdash;and had her first child just before  her twenty-second birthday. Two children and ten years later, with her husband  spending more and more of his time and energy emptying bills from the pockets  of bicycle messengers and less and less on her, she had begun to feel she was  missing something&mdash;sex above all&mdash;and she knew that, just below the portrait of  the loving, beautiful and happily married young mother she presented to the  world, another canvas was beginning to take shape: that of a embittered young  woman filled with unrequited hungers and unfulfilled cravings.</p>
            <p>She was also a painter, and not entirely without talent, so  that her small initial intimacies with Etan Yogev had often focused on their  shared artistic passion, as well as her comfortable, almost familial,  friendship with his parents. She saw him as a young Chagall, herself as Frieda  Kahlo (she even looked, a bit, the part-- a kind of Latino <em>sabra</em>); she  perceived him as a wild mop of hair that needed taming and felt herself a  temptress eager and willing to domesticate it.</p>
            <p>Etan Yogev had had no experience in bed&mdash;and hardly any  outside it&mdash;and it was not without a strong feeling of awkwardness and  insecurity that he had first allowed Daphna Flinker to guide his somewhat  ambivalent member into her own body, and his lips against her lips. She enjoyed  it&mdash;this teacherly role&mdash;it had been a long time since she had been able to  practice the art of sexual instruction, and there was something exciting and  alluring about this&mdash;all that innocence in a single place! Yes, he was unkempt,  disorderly, possessed of an air of distraction, but nonetheless there was  something-- how else could she put it?-- something <em>adorable</em> about him.  She imagined that he closely resembled his father as a young man&hellip; and just look  what had become of him!</p>
            <p>As for young Etan, he had found it confusing at first&mdash;so  much closeness to an actual human being! He had been reading about such  pleasures for so long&mdash;so many Madame Bovarys and Anna Kareninas, so many  lustful and tragic romantic heroines (even, from America, the occasional Edna  Pontellier, parrots urging her on from their cages)&mdash;that the actual  experiencing of them hardly seemed as novel, or exciting, as one might have  imagined for a young boy losing his innocence to an older, more experienced,  woman. What&rsquo;s more, his younger brother had always been the one the girls were  interested in, allowing his own romantic life to remain abstract and imaginary.  And that was just the way he might&mdash;had he reflected upon such matters at  all&mdash;have preferred it to remain.</p>
            <p>The day he had kissed Daphna for the first time they had  ridden their bikes to the Sea of Galilee for a  swim. It was late August&mdash;just at the height of Israeli summer before the High  Holy Days&mdash;and the air was crisp and clear, the water revivifying, even  shockingly, cold. Even he couldn&rsquo;t help notice how lovely she was&mdash;even lovelier  in a bathing suit where one could see, or imagine, all of her. She was small  and dark, with fiery, passionate eyes and a little-girl-like laugh that  suggested someone far younger than her years. And then there was her skin&mdash;dark,  well-oiled, beckoning. It seemed to him like the skin of the heroines of the  great romantic novels. It made him timid, but it also made something just below  his waist begin to tingle.</p>
            <p>When they lay together on the grassy shore of the Galilee after emerging from the water, she placed a hand  on his leg, stroking the thin hairs. Then she began kissing his neck, caressing  his feet with her own. It felt good&mdash;no, it felt <em>very</em> good.  And&mdash;awkwardly, timidly, ineptly at first&mdash;he responded, with her more than  willing to show the way.</p>
            <p>David and Sarah Yogev, like many members of the Israeli  artistic and intellectual elite, were libertines insofar as their children&rsquo;s  sexual experience was concerned. So it was not so much disturbing that their  almost twenty-one-year-old son was sleeping with their best friend&rsquo;s married  daughter in their house as it was bizarre&mdash;particularly for Sarah Yogev&mdash;to be  suddenly awoken to the pleasure-induced moans of a woman whose three young  children and their father she had fed at her table just weeks before. She  wasn&rsquo;t sure what she felt. Was it betrayal, jealousy, merely confusion? But one  thing she knew for certain: she didn&rsquo;t like it. Why couldn&rsquo;t her older son,  like his younger brother before him, simply choose an <em>appropriate </em>young  virgin with whom to first experience the pleasures of the flesh?</p>
            <p>But, then, she reasoned, nothing <em>else</em> about her  elder son had ever been appropriate&mdash;why should this be? She too had had her  share of wild times, after all. As a twenty-five-year-old girl, she had gone to  Paris for the  express purpose of seducing the twenty-five year-older artist who was to become  the boys&rsquo; father. And there had been plenty of amorous adventures prior to that  as well. So why deny her young sons theirs? So, after several months, urged on  by the obvious bemusement and vicarious pleasure her husband seemed to  experience at this turn of events, she had even begun to get used to the idea.</p>
            <p>&quot;<em>Elle a quand m&ecirc;me un beau cul</em>,&quot; David  Yogev would remark in French, suggesting that certain of the more admirable  portions of Daphna's anatomy had not entirely escaped his attention. <em>&quot;Non,  pas du tout,&quot;</em> his wife was forced to admit. Her husband, she  recalled, had always been particularly fond of nice asses. Before gravity had  begun to exact its inevitable toll, she had even been possessed of one of her  own.</p>
            <p>As a young couple in Paris--  or, rather, as a young woman and a significantly older man&mdash;she and David often  sat in caf&eacute;s and played what they affectionately called &quot;the three-bed  game.&quot; Each one would name an artist or intellectual in Tel Aviv whom they  knew (a man for him, a woman for her) and then-- by going through a list of the  lovers they each knew their selection to have had-- they could usually  determine that the two were <em>never</em> more than three beds apart! So incestuous  was the world of the Israeli intelligentsia! One had to admit that the story of  Daphna Flinker and Etan Yogev seemed to fit right in.</p>
            <p>The real trouble, however, only began when Daphna's  attentions and ministrations began to shift from Etan to his younger brother.  It had begun rather subtly-- with her often sitting beside Simon, rather than  Etan, at the dinner table, followed by what seemed longer and longer periods,  during her visits with the children to the Yogev&rsquo;s week-end home near Galilee,  when the two of them were absent from the house altogether. Then there were the  glances, the seemingly accidental touches, all the signs Sarah Yogev could so  well recognize.</p>
            <p>Daphna and Simon, of course, had done their best to make it  seem as if there had been a full stop, followed by a long ellipse (rather than  a mere segue), that separated her relationships with the two brothers. The  facts, however, belied such an explanation. Simon Yogev well remembered the  first night Daphna Flinker had come to his bed in his parents&rsquo; Tel Aviv  apartment. There had been a quiet dinner downstairs&mdash;his mother&rsquo;s famous  Hungarian goulash followed by her equally celebrated cheese-and-apricot strudel  (the Yogevs were confirmed atheists, and not at all kosher)&mdash;during which he  couldn&rsquo;t help notice that Daphna&rsquo;s gaze, rather than being directed at his  older brother, was perpetually fixed on him, and that, from across the table,  her feet brushed against his more frequently than mere chance might have  explained.</p>
            <p>That night, sleeping rather fitfully, he woke to the  rustling of his own sheets and the warm, not unfamiliar, feeling of a woman&rsquo;s  flesh beside him, and then of equally warm lips descending his chest,  accompanied by a feminine voice whispering sweetly in Hungarian, <em>&Eacute;des  Simon&hellip; &eacute;desem &eacute;desem &eacute;desem</em>. What had followed from that was the  inevitable&mdash;a night filled with such lubricated lust and <em>tendresse</em> that not even a glimmer of fraternal loyalty could  interfere with its pleasures. In the morning he would have to, as some writer  his father liked&mdash;was it the Frenchman Zola? -- had written, &quot;swallow his  large toad of nausea and regret&quot; in any event.</p>
            <p>There was now little question as to what Daphna Flinker&rsquo;s  real desires had been: Simon&rsquo;s brother had merely been a way station en route  to her actual goal. Now she had attained it. But, even before this, a certain  unspoken tension between the brothers had long been in the air&mdash;how could it <em>not</em> have been? It would be devastating to his older brother, from whom he had  already stolen most of the future family glory, Simon thought guiltily, to have  his first lover taken from him as well.</p>
            <p>Living in two almost entirely separate worlds&mdash;Etan in the  world of intellect and art, Simon in that of sports and women&mdash;whatever rivalry  might ever have existed between the brothers previously had been contained  mostly below the surface. At times, Etan had even ventured a foray into his  younger brother&rsquo;s territory&mdash;as, for example, several years earlier, when he had  taken up swimming and bicycling with a vengeance, managing to join the annual  summer swim all the way across the Galilee. In the process, he had also  developed a body far more muscular and sculpted than his disheveled, unkempt  coiffure and otherworldly gaze might have suggested.</p>
            <p>But each seemed dominant within his own spheres, into which  the other dared not tread, and Simon Yogev had always taken it for granted than  his older brother&mdash;if he could somehow survive the daily tasks of paying the  bills and doing his laundry&mdash;was heir apparent to their father&rsquo;s artistic gifts,  even if not to his capacities with women and soccer balls.</p>
            <p>Nonetheless, Etan Yogev&rsquo;s little romance with Daphna  Flinker, in addition to providing his mother a few sleepless nights, had created  a not entirely unwelcome realignment of the status quo, and <em>that</em>, if  nothing else, allowed Sarah Yogev a certain welcome relief: perhaps her older  son, after all, was not doomed to a life of being cared for by his mother, or  by some doughty, desperate young woman sufficiently enamored of his artistic  gifts to overlook the absence of most others. Perhaps he would still grow up to  be &ldquo;normal,&rdquo; whatever that meant.</p>
            <p>But now there was this.</p>
            <p>She would simply <em>break up</em> with Etan, Daphna promised  Simon, she would tell him what perhaps had become obvious to him already&mdash;that,  painting or no painting, they really didn&rsquo;t have very much in common, that she  didn&rsquo;t really feel the relationship was good for either of them in the long  run, and so on and so forth. (How then, Simon wondered, would she explain why  the relationship was good for the two of <em>them</em>?)</p>
            <p>Beneath Etan Yogev&rsquo;s veneer of otherworldliness, however,  there lay rather acute powers of intuition and observation. He had sensed  Daphna&rsquo;s impending flight from him even before it had actually taken place. He  may have looked like Heinrich Hoffmann&rsquo;s <em>Struwwelpeter</em>, but he was  possessed of his father&rsquo;s foresight and intuition. And he could feel, nightly,  the sense of Daphna&rsquo;s flesh, as well as her attentions, unwinding from his own.</p>
            <p>So, when the transition from the older brother&rsquo;s bed to the  younger&rsquo;s openly took place, the fault lines between fantasy and reality  suddenly split open as well, and, with them, the relative peace and contentment  that had for some months characterized the Yogev family&rsquo;s winter and early  spring, came to an end. Now it was not only Simon&rsquo;s potentially wrecked future  (Daphna Flinker, Sarah Yogev feared, was ripe for motherhood yet once again),  but his older brother&rsquo;s apparently fractured ego that needed tending to, not to  mention the Cold War-like mini-d&eacute;tente that had built a kind of psychological  Berlin Wall between the two brothers&rsquo; sleeping quarters and their day-to-day  relations. </p>
            <p>Etan, to put it simply, was heartbroken, his brother  guilt-ridden, their briefly shared concubine imperviously radiant.</p>
            <p>Like someone moving backwards through the seven stages of  grief, Sarah Yogev slowly moved from her initial state of shock and disbelief,  followed reluctantly by acceptance and hope, to profound depression, followed  by unmitigated anger at her younger son and his much older girlfriend, and then  by a profound sense of guilt towards her fragile and hyper-sensitive older son  for having allowed the liaison with a so much older&mdash;and still married!&mdash;woman to  go on to begin with. Now the bargaining stage was about to begin, but it was  not yet clear to her where on the table her chips lay, or whether, perhaps,  simple denial might be the wiser course.</p>
            <p>One thing she decidedly <em>didn&rsquo;t</em> want, she kept  reminding herself as she was again confronted&mdash;at an even higher volume-- with Daphna  Flinker nightly (and occasionally mid-afternoon) elocutions from upstairs, was  a grandchild at this point in her life, much less three step-grandchildren to  go with it. So she rather unsubtly placed a package of condoms beside Simon&rsquo;s  bed and another in the bathroom cabinet where he kept his toiletries. There  were no lengths, she reminded herself, a desperate woman wouldn&rsquo;t go to in  order to hold onto a man she loved&hellip;. particularly if that man happened to be a  boy.</p>
            <p>As for David Yogev, his sincere concern over his older  son&rsquo;s fragile and wounded ego was somewhat mitigated by the bemusement&mdash;indeed,  admiration&mdash;with which he observed his friend&rsquo;s daughter navigate, and escape  seemingly unscathed from, the various romantic minefields in her path. Having  long been one himself, he had always been intrigued by rebels and  anti-moralists&mdash;Raskalnikov had been his favorite literary character, along with  Julien Sorel. This girl was not merely, he thought (a small but undeniable  glimmer of paternal envy running through him) a marvelous conquest&hellip; she had <em>hutzpah</em> to boot. She knew what she wanted, and was determined to get it. How could a  man such as himself argue with that?</p>
            <p>Clearly, his younger son, guilt and all, was far from being  unhappy with these new amorous developments either. Hardly were his university  classes over for the summer, but that he and Daphna set off for two weeks in  Rome, the kind of &ldquo;in your face&rdquo; romantic interlude Sarah Yogev attempted to  mitigate the effects of upon her jilted and fragile older son by taking him,  along with her husband and their younger daughter, on a two-week vacation to  Provence. A friend of theirs, an Israeli politician of some note, had recently  purchased a marvelous mansion, on a cliff directly overlooking the Mediterranean. At the very least, Sarah thought, she  could offer her sensitive older son something &ldquo;poetic&rdquo; to offset the more  earthly pleasures his younger brother was so obliviously enjoying in Rome.</p>
            <p>As for Daphna Flinker, the weeks in Rome with her young  lover&mdash; and without the burden of her three children, whom she had left with  their grieving father&mdash;were a welcome reprieve from the life she had, it seemed,  so eagerly abandoned. They visited the Colosseum and the Pantheon; kissed in  front of the Trevi Fountain; strolled among the labyrinthine alleys within the  Jewish ghetto of Trastevere, amusing themselves at the rows upon rows of  washing strung out from the apartments in Mama-Leone tradition; picnicked in  the Roman Forum, and, after making a compulsory donation to the monks who  guarded it, discreetly made love in the Capuchin cemetery. It hardly bothered  them when their landlady, a former Benedictine nun who looked disapprovingly  upon what she had accurately perceived as their difference in age, finally  threw them out, finding the late-night sounds of their lovemaking a bit too  much for her and her ailing husband to take.</p>
            <p>Luckily for the young couple, there was a room available at  the Hungarian Academy  in Rome, in the  very precious <em>Palazzo Falconieri</em> at via Giulia 1, where a friend of  David Yogev&rsquo;s, a Hungarian-Israeli painter Sinai Sulzberger, had recently  become Director. This allowed the young lovers to roam the very same corridors  where such eminent Hungarians as the expert of Greek mythology, K&aacute;roly Ker&eacute;nyi,  the philosopher Gy&ouml;rgy Lukacs, the writer Antal Szerb, the poet S&aacute;ndor We&ouml;res,  and the composer Zolt&aacute;n Kod&aacute;ly&mdash;some of them even Jews!-- had once walked. So  their second week&mdash;with those around them seeming to revel in, rather than being  disconcerted by Daphna Flinker&rsquo;s late-night arias &mdash;passed even more happily  than the first.</p>
            <p>Simon&rsquo;s older brother, meanwhile, was enjoying the French  coast and its visual and culinary pleasures, and&mdash;surrounded by friends and  family&mdash;his thoughts returned only infrequently to his former girlfriend. There  were, after all, poems to be written, paintings to be made. The pleasures of  the flesh had been intense, but brief. Nonetheless, a wound had been opened  within him&mdash;perhaps more a wound of repudiation than of loss, more of wounded  pride than lost pleasure. For once, he had briefly triumphed over his younger  brother&mdash;and, what&rsquo;s more, on the amorous battlefield where his brother had  always reigned supreme! But now, that, too, was lost, and he was forced to  reassume his previous persona as the bedazzled genius little concerned with  earthly pleasures.</p>
            <p>The family returned from their Proven&ccedil;al journey and the  young lovers from their romantic two weeks in Rome at virtually the same time,  so that the Yogevs and what had by now become their &ldquo;extended&rdquo; family&mdash;including  not only Daphna, but her children, somewhat reluctantly re-possessed from their  depressed father&mdash;reconvened at Galilee for what had now unofficially become the  &ldquo;anniversary&rdquo; of Daphna Flinker&rsquo;s entry into the family circle&mdash;or, it might be  more accurately stated, the family&rsquo;s entry into her.</p>
            <p>Unlike the previous year, it had been a torridly hot  summer, even for the Middle East, the Galilee being no exception, and some of  the obvious tension that had by now more or less solidified between the two  brothers was slightly dissipated by periodic sojourns to the Lake for  refreshment&mdash;mostly in groups of two or three, with the two young lovers usually  choosing to bicycle on their own, leaving the children in the care of Sarah  Yogev or her young daughter Katya, who, at the age of just twelve, had already  developed something of a maternal instinct. Few, if any, words were exchanged  between the brothers, while their mother did her utmost to constantly extol the  enormous pleasures of their trip to France, thereby hoping to ensure  that the ever-turning wheels of jealousy and envy would be lubricated in the  other direction.</p>
            <p>On the eve of the holiday itself, ever hopeful of some  reconciliation between the brothers and of re-establishing an atmosphere of family  harmony, Sarah Yogev proposed that they all go to nearby Tiberias for a staged  Hebrew-language performance of <em>The Tragedy of Man</em>, the dramatic poem  by the famed l9th-century Hungarian Imre Madach that had often evoked  comparison&rsquo;s to Milton&rsquo;s <em>Paradise Lost</em>. With the exception of David  Yogev, who preferred to stay home and work on his newly-commissioned bust of  Yitzhak Rabin, and of Daphna, who felt uncomfortable about leaving the children  in the care of someone who, like David&rsquo;s elder son, entered all too easily into  a state of artistic trance, the others, albeit reluctantly, agreed. Neither of  the boys wanted to further disappoint their mother, who seemed more than a bit  edgy and depressed of late.</p>
            <p>Not that the Madach play&mdash; Etan, himself hardly in an elevated  mood, thought to himself&mdash; had been a particularly uplifting choice. Taking  place after Adam and Eve&rsquo;s banishment from the Garden of Eden, in it Adam  dreams the course of modern history, which only serves to fill him with  despair. He, Eve and Lucifer then take on different historical roles as they  pass through ancient Rome, the Crusades,  Kepler's Prague, revolutionary Paris and, finally, a post-historical time  when ecological disaster has nearly destroyed the world. As the play nears its  end, Adam, despairing of his race, tries to commit suicide. But, at the critical  moment Eve informs him she is about to be a mother, and the play ends with Adam  lying prostrate before God, who encourages him to hope and trust. </p>
            <p>Etan had read the work several times. Simon, in fact, (reluctantly&mdash;it  had been assigned in his Central European Literature class) had read it as  well, and looked upon the evening ahead with a dour countenance and a sagging  spirit. But, after all the pain he had caused his mother and brother, he  thought to himself, going along was the least he could do. What, after all, was  a mere wasted evening in the greater scheme of things?</p>
            <p>It was in this manner that, after Daphna had put the  children to bed, she and David Yogev, found themselves alone in the Yogev&rsquo;s  kitchen later that evening, enjoying a quiet supper of Norwegian salmon, potato <em>kugel</em> and green beans, expertly prepared in advance by Sarah, and a  fine bottle of <em>Gewurztraminer</em> from the nearby Golan Heights Winery,  owned by a friend of David&rsquo;s who had made his fortune in South African  diamonds. </p>
            <p>Daphna had always found David Yogev, even at seventy-two,  an intriguing figure. There was something terribly dignified about him, so  cavalier, so&mdash;how else could she put it?&mdash;<em>Old Worldly</em>. He seemed to her  like an aging Don Juan, a slightly pot-bellied Casanova, of times past. Lord  Byron, had he managed his Biblically ordained threescore and ten, might even  have come to resemble him.</p>
            <p><em>&ldquo;L&rsquo;chaim&rdquo;</em> the older man  toasted, clicking his glass against hers.</p>
            <p>&ldquo;<em>L&rsquo;chaim</em>&rdquo; she replied, smiling. He was certainly  still attractive&mdash;the kind of man who, no matter how advanced his age, still  adored women. But now, against the candlelight with his older son&rsquo;s paintings  everywhere around them, he seemed even more attractive, even more diabolically  cunning and wise. </p>
            <p>There was much a woman could learn from such older men,  Daphna had always been told, and he, no doubt, had already taught his share of  younger women a great deal. Suddenly, she could feel her feet moving against  his beneath the table. She could feel the pillows moving beneath her head once  more. He was gazing, paternally yet seductively, into her eyes from across the  table. Slowly but surely, she could feel her body begin to rise, slowly heading  towards yet another bed.</p>
            <p>Sarah Yogev hadn&rsquo;t really thought to reserve tickets for  the play in advance, as the small theatre in Tiberias was rarely, if ever, sold  out. She had underestimated, however, the number of Hungarians who lived and  vacationed near the Sea of Galilee, or who lived  on the various <em>kibbutzim</em> along its shores. So, when the Yogevs arrived  at the theatre just ten minutes before the play was scheduled to begin, she was  shocked&mdash; and Simon nearly ecstatic&mdash; to find that only a single pair of tickets  remained.</p>
            <p>There was little else to do but turn the car around and  head back home.</p>
            <p>Surprisingly enough, the house, aside from a single candle  still glowing on the kitchen table, was dark when the three of them arrived. As  she turned the key in the front door, Sarah could hear the faint sound of  Chopin&rsquo;s Nocturnes, played by Arthur Rubinstein&mdash;her and her husband&rsquo;s favorite  recording during their early courtship days in Paris&mdash;wafting as delicately as  Rubinstein&rsquo;s fingers themselves from her husband&rsquo;s darkened study.</p>
            <p>She also heard, coming from the same room, an  all-too-familiar sound, the same erotic song to which her own two sons had  already danced.</p>
            <p>Etan and Simon were right behind her as she entered the  kitchen. She could feel, somehow, her younger son&rsquo;s visage constricting into a  large synapse of pain, she could hear his breath, first letting out a slight  gasp, then inhaling deeply, as if trying to hold back some terrible inclemency.  She turned, as if looking right through him, just in time to see her elder  son&rsquo;s face break out into a wide and uncharacteristic smile, like a sly  adolescent who was somehow watching his own mischievous act bear fruit.</p>
            <p>He had of course known&mdash; that wise, silently introverted  boy, the poet and artist&mdash; how all this would eventually end. He could almost hear  the very words he had once read from the pen of the great Japanese writer,  Nobuhiro Watsuki. <em>Give me the sword of justice,</em> Watsuki had written,<em> show me the hate to put it through!</em> </p>
            <p>He felt his younger brother&rsquo;s entire body constrict and  grow taut as a wire before him. He saw their mother&rsquo;s large kitchen knife  gleaming up at them from the top of the pantry shelf. </p>
            <p><em>Animal sacrifices</em>, he  thought to himself as his brother&rsquo;s right hand tightened around the handle, had  been commanded by God everywhere in the Old Testament so that individuals might  experience forgiveness for their sins. The animal, his Hebrew School  teacher had told him, served as a substitute&mdash; that is, the animal died in place  of the sinner. And now here, in his very own home, the sinner herself <em>was</em> an animal. The sinner was a beast, a beast whose desire knew no limits, whose  seductive powers knew no ethical bounds. </p>
            <p>If ever a woman had been conceived in sin, surely it was  Daphna Flinker.</p>
            <p>Sometimes on this earth, his handsome and devastated younger  brother was also thinking to himself, humans had no choice but to behave like  surrogate gods. Sometimes, he had read somewhere, God appointed humans as  avengers of earthly sin.</p>
            <p>In Etan&rsquo;s eyes at that moment, as he watched his brother&rsquo;s  athletic body push past their mother and head for their father&rsquo;s study door,  the slightly uplifted knife suddenly became a symbol of righteousness, a  gleaming banner of faith, a bit like Abraham&rsquo;s knife rising over the body of  his own young son Isaac. </p>
            <p>It even began, in his ever-poetic mind, to resemble the  sword of justice.</p>          </td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr>
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
