<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <title>Michael Arditti &raquo; Interlitq</title>
  <meta http-equiv="Content-Type"
 content="text/html; charset=UTF-8">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
window.open(theURL,winName,features);
}
//-->
  </script>
  <link href="../../estilos.css" rel="stylesheet" type="text/css">
  </style>
</head>
<body>
<?php include("../../headernew.php"); ?>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr>
      <td align="right" valign="top" width="10%"><?php include("../menu_englishwriters3.php"); ?>
      <div align="right"></div>
      </td>
      <td valign="top" width="90%">
      <table bgcolor="#ffffff" border="0" cellpadding="0"
 cellspacing="0" width="679">
<!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tbody>
          <tr>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="10"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="192"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="17"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="205"></td>
            <td valign="top"><img src="/images/spacer.gif" alt=""
 border="0" height="1" width="239"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="16"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="1"></td>
          </tr>
          <tr>
            <td><img name="home_r1_c1" src="../../images/spacer.gif"
 alt="" border="0" height="59" width="10"></td>
            <td colspan="4"><img src="../../images/spacer.gif" alt=""
 name="home_r1_c2" class="link1" border="0" height="59" width="653"></td>
            <td>&nbsp;</td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="59" width="1"></td>
          </tr>
          <tr>
            <td rowspan="4"><img name="home_r2_c1"
 src="../../images/spacer.gif" alt="Click to enlarge picture"
 title="Click to enlarge picture" border="0" height="391" width="10"></td>
            <td rowspan="2" valign="top"><a href="#"
 onmouseup="MM_openBrWindow('artwork.html','','width=700,height=850')"><img
 src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2"
 border="0" height="167" width="250"></a></td>
            <td rowspan="2"><img name="home_r2_c3"
 src="../../images/home_img/home_r2_c3.gif" alt="" border="0"
 height="242" width="17"></td>
            <td colspan="2" class="titulo2" valign="top">Extract from Novel<span
 class="texto2">
 
 <br>by<br> <a href="bio.php"
 class="link3"> Michael Arditti</a><br><br><br>
</td>
            <td>&nbsp;</td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="23" width="1"></td>
          </tr>
          <tr>
            <td colspan="2" class="texto2" height="219" valign="top">
            <p>&nbsp;</p>
            </td>
            <td rowspan="3"><img name="home_r3_c6"
 src="../../images/spacer.gif" alt="" border="0" height="368" width="16"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="219" width="1"></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="2" class="texto2" valign="top">
           <p><br><br></p>
<p>The divine vengeance wreaked on Sodom is one of the most enduring and influential myths of all time.  <em>Of Men and Angels</em>, Michael Arditti’s new novel explores its creation, dissemination and application in five historical episodes.   The first depicts the codification of the myth by Jewish scribes in Nebuchadrezzar’s Babylon, and the second the performance of the mystery play of Lot’s Wife by guildsmen in medieval York.  The third depicts Botticelli painting panels of Lot and Sodom for the Office of the Night in Renaissance Florence and the fourth the alleged discovery by a Victorian rector of the ruins of Sodom on the Dead Sea shore.  The fifth depicts a Hollywood star, afflicted by AIDS, filming a biblical epic on the destruction of Sodom. </p>

<p><em>The following extract is the opening chapter of the second section of the novel and remains a work in progress. </em></p>

<p>Ralf clasped the angel’s crown and tapped the bronze wings on the door.  He was greeted by Walter’s steward with the mixture of disdain and deference due to one with so little sway in this world and so much in the next.  He walked through the great hall where, despite the warmth of the June morning and the absence of company, a fire blazed in the grate, doubtless to show off the chimney that was Marjorie’s latest indulgence.   </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;	He climbed the stairs, noting with wry dispassion the ache in his knees, and entered the gallery.  His hosts stood in the centre:  Walter in a samite tunic and purple robe trimmed with ermine;  Marjorie in a silver caul and the green-and-yellow gown she had worn at Candlemas.  Their guests were likewise resplendent, as though vying with the players in the pageants.  Only Edmund had eschewed such pomp and, despite his claim to scorn all displays of emotion, confined himself to the colour of his grief.  Ralf was surprised to see Frances Skirlaw after Marjorie’s forthright condemnation of her marriage to her dead husband’s apprentice full thirty years her junior, and dismayed to see Baldwin Louth, who had been convicted of riot last Fool’s Day in St Michael Le Belfry churchyard.  His penance had been to make a pilgrimage to five neighbouring abbeys, offering a fourpenny wax candle to each, but he had refused and remained excommunicate.   Ralf said a hasty prayer that the sight of the damned being pitched into hell at the Last Judgement would prompt his remorse. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;	For the third successive year, Walter had procured the right to have the Corpus Christi pageants presented outside his house.   His was the sixth station, midway along the route, immediately after the most parlous passage for the wagons where they turned sharply left from Ouse Bridge into Coney Street.  Despite the fee to the Corporation, the cost of scaffolding and the Chamberlain’s levy of every third penny from the lease of the seats for the common good, Walter had declared that he would make a fair profit, breaking off when he remembered that he was talking to a priest.   Ralf would have preferred to watch from the street where the air was cooler and the view less obscured, since he was obliged to stand back from the window in favour of more honoured guests, but he could not refuse an invitation from his patrons.  Besides, the well-furnished sideboard had its compensations.  Gazing at the venison, mutton, goose, stuffed carp, wheels of cheese, pies, honeyed fruits, custards and, at the centre, a candied merchant ship, which stirred his imagination far more than any seaworthy vessel, he prayed that he would not succumb to the sin to which he was most prone. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;	To his dismay, his gaze was met by Edmund.  It was Edmund who once informed the guests at his father’s table that, had he been aware of Ralf’s appetite, his grandfather would have waived the provision in the chantry ordinances for his chaplain to dine with himself and his heirs for three days every Christmas, Passion Week, Pentecost and Lammastide.  Although Marjorie had reproved her one surviving child with accustomed mildness, Walter had roared with laughter.  Ralf had known Edmund since birth.  He taught him at petty school and Edmund still resented the whipping he had dealt him for breaking his writing-board over another boy’s head.  Later, at Walter’s behest, he spent long hours disabusing him of the Lollard heresies he had affirmed as a youth.  But, despite having rescued him from that dangerous dalliance, he failed to sway him when, after his wife Constance died in childbirth, he rebelled against the Church, from which he too was now excommunicate.  Moreover, either to make mischief or worse, he directed his impiety at Ralf.  </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;	For the moment he was talking to two of his guests, whose unfamiliar caps and hoods marked them as merchants from Norway or Zeeland.   While Ralf objected to his using the pageants to further trade, he acknowledged that without trade there would be no pageants.  Walter himself had paid his silver for twenty years and, as he admitted to Ralf, his affairs were foundering.  Peace with France had favoured rivals such as Simon Muskham, who transported salt from Bourgneuf Bay, along with lucrative goods such as wine, woad, alum, silk and oil.  Walter and Edmund, however, dealt exclusively with the Hanse, where the mining and shipping costs were higher and the danger of piracy greater.   So they had to take every chance to persuade their associates to grant them more profitable terms. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;	Ralf’s relief that he did not belong to the merchantable world vanished when he was beckoned by Edmund.  Aware that he was not one of the chosen friends who would inspire the foreigners with a sense of their hosts’ renown, he suspected that he was to be the butt of mockery, affording them a brief distraction before the pageants began.   And so it proved. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Do not be misled by the gaunt cheeks and ragged gown,’ Edmund said.   ‘Sir Ralf is the most fortunate man in the room.  While the rest of us toil day and night, he prays.  Prayers he has repeated so often that they are like the humming of drone bees.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Was it not Alfred, the greatest of English kings, who said that a monarch had need of three kinds of subject?’ Ralf replied.  ‘Those who pray, those who fight and those who work.   Remember which he placed first.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘He was a king.  I am a merchant.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘But is a merchant not the king of his own realm?’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Well answered, Sir Ralf,’ said Walter, who, unlike his wife, liked to see his son chastened, provided that it was only with words. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘It is five thirty,’ Marjorie said loudly to Frances Skirlaw.   ‘The first wagon should be here soon.’ </p>
 <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Is it the same in your country?  Priests;  bishops;  chaplains;  clerks;  monks;  friars;  to say nothing of their children,’ Edmund said, the last clause piercing Ralf’s heart, ‘all robbing honest men.  Taking a tenth of our revenue in tithes while we live and a third of our estates in mortuaries when we die.’ </p>
 <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Please have some breakfast,’ Marjorie interposed.  ‘Do not leave it for the flies!’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘And as if one priest in a church is not enough, they have two… sometimes three or four, each with his own chapel, squinting past the pillars to the high altar to be sure that one of them is not raising Christ’s body at the same time as the other is eating it.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Not at all,’ Ralf said, addressing his remarks to the foreigners, who looked perplexed.  ‘Besides it is not my chapel;  it is your grandfather’s.  As you well know, he founded the chantry when his brother returned to him from purgatory in a dream.  With his face blackened and his body in flames, he recounted his pains for failing to do penance while he lived.   Your grandfather asked how he could help and he answered that the only way was through prayer.  So he built the chantry for the relief of his brother’s soul and his own and the souls of all his heirs, including you.’ Ralf forbore to add that one of those for whom he said a daily requiem was Constance, since Edmund had expressly forbidden it, arguing that if neither the kerchief that had been rubbed on the bones of St William Fitzherbert and pressed to her brow nor the prayer scroll wrapped around her belly had saved her life, no mass after her death could save her soul. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Much use will it do!   Just wasted spit.’ </p>
 <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Peace now,’ Walter said, gripping his son’s shoulder and turning to the merchants.  ‘Gentleman, please eat something.  Have you tried plover pie?   It is a dainty in these parts.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Walter led the men to the food, leaving Edmund scowling, until Agnes Muskham’s arrival transformed his mood as markedly as Martha’s and Mary’s in the cap-makers’ Raising of Lazarus.  Ralf wavered between gratitude that there was someone who could ease Edmund’s wounded spirit and sorrow that it was Agnes, who had not only been his wife’s dearest friend but was married to his adversary. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; After waiting for the steward, who wordlessly poured him a cup of ale rather than wine, he crept towards the window where he reflected on the altercation.  Edmund might scoff at his prayers, but he himself had no doubts of their virtue.  The most skillful physician could only relieve someone’s suffering for a mortal term, whereas he could do so for eternity.   But who would fulfill such an office for him?   Who would acquit him of the sins he had failed to confess and the penances he had failed to perform?  The few marks he might bequeath would barely suffice for an annual obit.   He envied the masons and tilers building the Minster choir who had the archbishop’s promise that any man who died at work would have not just a part but the whole of his term in purgatory annulled.  One of the vicars choral had jested that the greatest felons in York were seeking entry into the crafts and then throwing themselves from the scaffolds.  Ralf had failed to smile. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Crabbed voices rose up from the street.   With the first pageant setting off from Holy Trinity at daybreak, it should have reached Coney Street by now and, even if the wagon had yet to roll into view, the cries of Lucifer and his doomed companions should have been heard from the fifth station.  Any further delay, and the complaints from spectators at the final stations that the Coronation of the Virgin and the Last Judgement had taken place in the dark would this year be extended to the Resurrection itself.  </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘No doubt we are waiting on the king,’ Edmund said scornfully.  ‘Four o’clock is too early for one who retires at an hour when all honest men rise.’   </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘The King is the flower of courtesy!’  Marjorie chided her son more severely than was her wont.  ‘Master Underwood and I were presented to him at Easter.  He told me that the Queen herself did not have a kirtle so fine as mine.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘He told me that he would be content to hold his court permanently in York,’ Walter said. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘And drain our coffers dry within the year?’ Edmund asked, avoiding his mother’s eye. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; While presuming that a king so prone to flattery was apt to flatter in turn, Ralph did not doubt the affection in which he held the city.  He had visited it twice this year, first to grant it the dignity of a county and release it from the jurisdiction of the High Sheriff and then to attend the Passion Week masses in the Minster.  He had given a hundred marks from his privy purse for the rebuilding of the choir and paid for the renovation of his great grandfather, Edward II’s chantry.  But he had quarrelled with the Dean and Chapter, who refused to support his petition to have King Edward canonised, which was why he was watching the pageants at Holy Trinity rather than the Minster Gate.  </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘It must be very short,’ Edmund had said on hearing of the book of Edward’s miracles that the King had ordered to be sent to Rome, ‘or else very fantastic.  A bloody death does not make a man a saint.  Else why not sanctify every villain killed in a tavern brawl?’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ralf’s esteem for the King was a further cause of conflict with Edmund, who roundly condemned his refusal to lead an army into France to win back the territories lost after the Black Prince’s death.  Although he professed concern for England’s glory, Ralf suspected that his motives were more venal, since war with France would damage Mediterranean trade and favour merchants such as himself who dealt with the Baltic. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The tanners’ wagon approached to a roar of approval as loud as the one that had greeted the King at Micklegate Bar three days earlier.  The company in the gallery moved to the windows, which Marjorie declared safe to open since the streets had been newly cleansed and the seats at their station leased to the most wholesome persons.  Ralf held back, only to be summoned by Agnes to a place at her side.  He struggled to allay the suspicion that her kindness to him was intended to provoke Edmund.  The pageant bearers, their faces drenched in sweat although the sun was still low in the sky, set down the wagon, narrowly missing the jetties on the tenements opposite.  Musicians in craft livery played a measure on trumpet, shawm and regal.  The leaves of the wooden cloud atop the mansion ground open, and Ralf held his breath as at a stammering confession.  A burst of applause hailed Jack Sawyer, a master tanner from Barkergate, wearing the familiar golden mask and white robe of God.  Silence fell as he spoke the lines with which the whole play – indeed, the whole of creation – began:  <em>Ego sum alpa et O, Vita, Via, Veritas, Primus et Novissimus</em>.   They were among the few Latin words found in any of the pageants, which were written not in the language of the Church but that of the people.  Nevertheless, it was right that the Almighty’s first utterance should have a majesty that all would recognise if few comprehend.  </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The tanners’ God was attended by five angels, boys with flaxen tresses and peacock-feather wings, singing a canticle of praise.  Ralf remembered when he himself had been part of just such a celestial choir, in the Pageant of the Creed more than fifty years before, bursting into song on the phrase ‘he ascended into heaven’ in the sixth article.  He had been dressed much as the boys were now, although his wings had been made of swansdown and his mask only covered the top of his face.  He was paid four pence, a detail that he wished had not fixed so fast in his memory.   He had watched the priests who represented God and Christ and Mary, and even Satan and Herod, and imagined doing the like on his ordination.  Since then, however, clergy had been forbidden to take part.  Whereas laymen were held to be exalted by representing Christ, His Holy Mother and Apostles, and chastened by representing Satan, Cain and Herod, it was feared that priests, who dispensed the sacraments, would be defiled by unseemly emotion. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; He turned back to the pageant, where Lucifer’s baleful pride met with the usual hisses.  Undeterred, the soon-to-be devil was hoarsely bewailing his plight when four or five men (Ralf’s view was partially blocked by Agnes’s shoulder) beset the wagon.  The good and bad angels joined forces to repel them, while God retreated swiftly into the cloud.  Four wagon bearers and two stytelers entered the fray, buffeting the assailants, whom they dragged off as roughly as the damned in the Doomsday pageant.  Peace was restored to loud cheers, as the good angels, their feathers ruffled, and Lucifer, limping, gathered around God, his authority diminished by his flight. Ralf might have hoped that the Archbishop’s pledge of forty days remission from purgatory for all who attended the pageants would have assured good behaviour.  He had never known trouble to occur so early in the day, but then this had been prompted not by drunkenness or craft rivalry but rather by indignation on behalf of a young girl from the parish of St Peter-le-Willows, who had died of burns from the slaked lime that a negligent tannery had discharged into the street. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; God separated light from darkness and withdrew into the cloud with little of his wonted pomp.  Walter, ever jealous of his city’s honour, looked happy when his visitors not only commended the presentation but supposed that the disturbance was planned, a discord on earth to mirror that in the skies.  </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; There was less spectacle, licensed or otherwise, for them to laud in the second pageant.  Although six resplendently painted curtains were drawn across the mansion, one for each day of Creation, God, as was only fitting, stood alone.   Ned Foxholes, whose hoary beard required no added horse-hair, was no longer master of his speeches and had to be loudly prompted to bring forth the birds and fishes.  Ralf trusted that Sir Robert Palfrayman, in whose church his chantry was housed, had shown his disapproval of the pageants by staying away.  His objections to a common plasterer representing God would be multiplied by such infirmity. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The plasterers were succeeded by the cardmarkers with the Creation of Man, the fullers with Adam and Eve in Eden and the coopers with the Fall.  As Satan, scaled and tailed, rose from the trap to reveal his dark design, a palpable excitement filled the gallery.  Not only was the Fall a perpetual favourite, the vain excuses of Adam and Eve and crooked cunning of Satan relieving the horror of Original Sin, but the coopers’ arrival at the sixth station meant that the salters’ own pageant of Lot’s Wife would be starting at the first.   After the Fall came the Expulsion from Eden, which, to add to the banished couple’s distress, was arrayed in far more splendid colours on the armourers’ wagon than on the fullers’ and coopers’.  Marjorie, however, who had fought a long and bootless battle to oust a noisome forge from Davygate, refused to see any virtue in the offending craft.  No sooner had Gabriel stepped forward to proclaim God’s purposes for the pair than she abandoned the window and once again exhorted her guests to eat.  Disturbed by her rancour but loath to decline the request, Ralf took his platter to the sideboard, where she rewarded him with a slice of the sturgeon reserved for more favoured guests. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The armourers’ Adam and Eve were followed by the glovers’ Cain and Abel.  Thankful for any distraction from the pain of the first murder, Ralf observed the return of the scullion whom Walter had sent to Holy Trinity to report on the reception of Lot’s Wife.   Bounding up the stairs with a want of breath worthy of one of Herod’s messengers, he pronounced it a success.  ‘The King smiled.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘You were close enough to see, were you?’ Edmund asked. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘I saw his teeth,’ the boy replied pertly. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘And how do you know he wasn’t removing a piece of honey cake?’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Hurry along, Crispin.  Ask Sarah to give you some pie,’ Walter said.  ‘And I will thank you to keep your thoughts to yourself,’ he added sternly to his son.  </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Edmund bridled, no doubt adding paternal ingratitude to his list of grievances.   Mindful that, however blank his countenance, Edmund was sure to read it as a rebuke, Ralf turned back to the pageant where, having dispatched his brother, Cain was drinking himself into oblivion with his servant Brewbarret.  The respite proved to be brief, and the angel exiled him in his turn, after which the play moved forward hundreds of years to the two pageants about Noah:  the Building of the Ark and the Flood, presented by the shipwrights, and the fishers and mariners respectively.  They were among the most popular in the whole play, although last year the Flood had had to be abandoned at the third station, when two monkeys borrowed from the menagerie at Thornhill Hall tore down the painted canvas and menaced the other animals.   This year the animals were limited to two lions, two unicorns and two donkeys, represented by six boys from St Sampson’s song school, who were not only a delight in themselves but diverted attention from the unbridled antics of Noah’s wife.  Yet, as though the pageant were as doomed as the world it portrayed, the rainbow stuck at the last moment.  One of the mariners clambered up to the machine loft to release it, but only the lower half opened, reducing God’s covenant with mankind to three colours:  green, blue and violet. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Our pageant comes next,’ Walter informed the foreigners, as the fishers and mariners hauled off their wagon. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘I cannot watch,’ Edmund muttered to Agnes.  ‘Simon Muskham crowned in glory.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘He takes the wife’s part.  It is all he is fit for,’ she replied, in a whisper that Ralf wished he had not overheard. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The signs of affection between Edmund and Agnes made him uneasy.  While not their priest, he was by virtue of his chantry Edmund’s family chaplain and, having known Edmund and Simon since boyhood, he had a care for their earthly as well as their eternal welfare.  Moreover, he had heard both their confessions every Passiontide for almost twenty years and, unless either had confessed to Sir Robert on another occasion, he alone before God had a true understanding of their enmity. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; They had grown up together, when Simon served his apprenticehood in Walter’s shop and Walter kept Edmund at home rather than binding him to a fellow salter.  Ralf, who ever since their pilgrimage to Santiago had been privy to the secrets of Walter’s heart as well as his soul, knew that this was to please Marjorie who, having lost two children as infants and three more when the pestilence returned to York in 1378, was determined to keep him close. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The two boys had shared a schooling, in part at Ralf’s hand, and an instruction in the mysteries of their craft at Walter’s.  They had shared prayers and pastimes and friends and, at night, they had shared a bed – Ralf looked away from the street where the pageant bearers were securing the salters’ wagon and up to the ceiling, above which was the garret.  It was there one night, as Simon had hesitantly confessed, that Edmund stretched out his hand and stroked his belly.  Simon, the more timorous of the two although the elder by eighteen months, felt his body grow numb, except for the one part that quickened.  Thereafter they committed the sin every night, with one or other of them reaching out as if by chance.   Simon was in terror of punishment, both for the sin itself and the pleasure he took in it.  Assuring him that God forgave every contrite heart, Ralf sought to discover the nature of the offence:  whether it had been limited to the hands or extended to the mouth, thighs and fundament.  Simon swore that theirs was a solely manual transgression, horrified as much that such other practices existed as that Ralf knew of them.  But Ralf’s knowledge was drawn entirely from the penitentials.  He had never felt another’s hands on his privy flesh in all his sixty-four years. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; He had imposed a penance of fasting and prayers on Simon who, either because he was afraid of laying up punishment in the life to come or because he sought privation as much as pleasure, appeared disappointed by the mildness.  Despite giving him every intimation he could without betraying his office, he had failed to obtain a similar confession from Edmund.   Fearful for the boy’s eternal soul, he allowed himself to hope that his offence had been unwitting.  Given Simon’s assertion that no words had been spoken, he might even have been asleep. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ralf wondered at his eagerness to pardon – if only in his own mind – a man who did not trouble to conceal his contempt for him.  It was clear that, whatever else, the prospect of purgatory held fewer fears for Edmund than for his fellow miscreant.  Not two years after Simon’s confession, Marjorie’s young maidservant, Rose or Lily (he remembered only that it was a flower), found herself with child, naming the seventeen-year-old Edmund as the father.  The couple were arraigned for fornication in the archdeacon’s court.   Edmund was acquitted after purging himself before six neighbours.  The maid was less fortunate.  Unable to assemble the necessary compurgators, she was further accused of perjury and slander and sentenced to be whipped around the churchyard and driven from the parish.  Ralf was called upon to witness, although his vision was clouded by the memory of a whipping in another churchyard fifty years earlier and the woman who had died not of wounds but of shame.        </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The maid had been delivered three months before her time of a stillborn son who, according to report, had twelve fingers.  Having heard nothing more of her, Ralf doubted that she had long survived the child.  He wondered whether Edmund felt any remorse, either in the aftermath of her ordeal or on Constance’s death.  In the still of night might he have linked the two women’s fates in a way that his daylight mind eschewed?  He had been so anguished by the loss of his wife and child that no one, not Walter or Marjorie or any of his neighbours, least of all Ralf, could comfort him.  The one exception was Agnes.  She and Simon had married a few months before Constance and Edmund.  Walter, blind to how his favour towards his former apprentice had fuelled his son’s jealousy, prayed that the women’s friendship would extend to their husbands.  During Constance’s lifetime, they had maintained a semblance of courtesy.  In recent months, however, Walter had come to mistrust Edmund’s familiarity with Agnes and urged Ralf to counsel Simon in his duty to govern his wife.   Stuttering like Moses, he had done so, only for Simon to mock his concerns, although whether from belief in Agnes’s innocence or indifference to her guilt, Ralf could not say. </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; He turned back to the pageant just as Gabriel and Raphael descended the mansion by means of a jouncing winch.   Their fresh faces, golden locks and long white gowns drew lewd whistles from several of the more unruly spectators, who would no doubt shortly revile the Sodomites for similar wantonness.  Ralf wished that the angels had been presented as more manly, not only to accord with the biblical verse but to challenge the common misconception that the Sodomites’ sin was lust.  As a confessor, however, he knew that people oppressed by their own sins took comfort from the thought of others who had committed worse, not least a sin so grave that, according to St Augustine, it had led Christ to defer his Incarnation, a sin more deadly than murder since it threatened the very existence of mankind.  Yet, while echoing St Augustine’s revulsion, he could not forget the two scholars with whom he had shared a hostel at Michaelhouse, gentle souls whom he would never have suspected of such vice. Caught in rank lust, they were arraigned before the Chancellor, excommunicated, and handed to the city sergeants who had cut off their ears, branded and gelded them. </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Heart-sore, he forced his attention back to the pageant, where Lot’s wife, ignorant of the angels’ condition, chided her husband for harbouring more waifs and strays.  The crowd whooped as Simon rolled his eyes at Lot’s credulity, hid a pie beneath his apron, and swooned like a maid on descrying the strangers’ beauty.  While admitting that it would be unseemly – wicked even – for those representing God and the angels to invest their parts with emotion, Ralf was dismayed by how many of the players spoke their lines as though they were reciting their ABCs.  Simon, however, gleaned every shred of humanity from the Wife, augmenting certain womanly humours just as he had his bosom.   Ralf wondered whether he had borrowed any of them from Agnes, whose countenance was as inscrutable as the angels’ masks. </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As Lot’s newly humble wife prepared a meal of bacon and pottage, the Sodomites encircled the house, pressing Lot to yield up his guests, like drunken journeymen calling for whores outside a brothel-house.  Ralf was surprised that the clerk who penned the pageant in Walter’s father’s day had failed to draw on the legend that it was Lot’s wife herself who betrayed the angels’ presence by soliciting salt from her neighbours, which would have both presaged her transformation and given the craft a chance to display its wares.  Instead, he had dwelt on the men’s fleshly lusts with all the horror of one who lived in the shadow of the Great Pestilence, when such lewdness was blamed for inciting God’s wrath.  Thus Lot denounced his neighbours as:		 <br>
<blockquote>‘Saracens so hot and haught, <br>
		Who, glutted with all granted love,<br>
		For wanton lust do set at naught</br>
		The benison of God above.’</blockquote>
The men, in turn, scorned his reproofs, one beating the mansion curtain so hard that the door to Lot’s house shook like Abraham’s tent. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Sodomites’ assault was met by even louder hisses than Lucifer’s fall.  ‘I do not understand this,’ the Zeelander said.  ‘Are these also devils?’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Worse than devils,’ Marjorie said. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘The basest of men,’ Walter added. </p> 
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘It is hard for your players who must speak above the bruit.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Not at all,’ Walter said, with the assurance of one safely indoors.   ‘We are doing God’s work.  When the people shout, they are denouncing sin.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘A sin that is not of Master Underwood’s choosing,’ Marjorie said, lest there should be any doubt. </p>
 <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘We receive our charge from the Corporation,’ Walter explained to the Zeelander.  ‘Just as the shipwrights have the Building of the Ark and the vintners the Marriage at Cana, so we have Lot’s wife.’ </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘A peevish woman turned to salt is not the same as a pot of water turned to wine,’ Marjorie said sourly.  ‘I sometimes wish that God had transformed her into a sheaf of wheat and Christ made his sacrament of salt and wine.  Then we might trade pageants with the bakers.’   She laughed, as though to lessen the impiety. </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘How you women prate!’ Walter said, torn between silencing his wife and reassuring his guests.  ‘Would you sooner I were a girdler and my fellows slaughtered the Innocents or, worse, a butcher and they crucified the Lord?’ </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘At least those are daylight sins.   Whereas this is a sin so foul that it is found only among the black Mahometans.’ </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Not so, Mother,’ Edmund interposed.  ‘It is rooted in our native soil, rife in every abbey dormitory.  Am I not right, Sir Ralf?’ </p>
	 <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘That, as you well know, Edmund, is a Lollard slander.’  With a last look at the wagon where Raphael was commanding Lot to leave the city, Ralf moved to the centre of the room, determined not only to meet Edmund’s challenge but to correct the error on which the pageant itself was based.  ‘As a layman, you have not studied the sacred page like those of us who were at the university.’ </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Even those who were excluded?’ </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Edmund!’ Walter said, blushing as much at his own indiscretion as his son’s discourtesy. </p>
	 <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Stop taunting Sir Ralf, Edmund, and come here!’ Marjorie called from the window, where the mirth had reconciled her to the pageant.  ‘Simon is on the ground, refusing to stir.  You can see his great boots under his gown.  The sleeves are just like yours, Agnes dear.’ </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘They are mine,’ Agnes said quietly. </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘I knew I had seen them before.’ </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘We can start by abandoning the fable that, at Our Lord’s nativity, all the sodomites in the world fell down dead,’ Ralf said, reverting to his theme. </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘They are about to die again,’ Baldwin Louth interjected.  ‘We shall see how they accomplish the fire and brimstone this year.’ </p>
	<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘At Michaelhouse we were told never to breathe the word Sodom out of doors or the grass would wither.   But is that what we find in the Bible?’  Ralf left them no time to reply.  ‘Not at all.  If you read Ezekiel, you see that the sins of Sodom were arrogance and gluttony and contempt for those in need.  Would not the same be true in York today?’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Quick!’ Frances said, ‘or you will miss Master Muskham’s transformation.’  Returning to the window, Ralf gazed out at the wagon where, to a clap of thunder, a tower collapsed and four Sodomites rolled into a monstrous hell-mouth.  As neatly as if he were dancing a carole, Simon whirled round to look, emitting a piteous scream as he fell through a trap in the rushes-strewn floor.  Moments later, a pillar of salt – or, rather, wood covered with flour – rose up in his place. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘The very image of Master Muskham,’ Baldwin’s wife Janet said.  ‘Would you not say so, mistress?’ she asked Frances. </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Indeed,’ Frances replied, although both knew that it had been fashioned on old Giles Sweetmouth and the pageant master had resisted Simon’s pleas to replace it.  </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; On the wagon, Lot led his weeping daughters away from their transmuted mother with a haste that would have been unseemly in anyone not favoured by God.  They took refuge in a cave, where the pageant drew to a close, the clerk having wisely recoiled from what ensued.  Marjorie praised Simon’s representation to Agnes and exhorted her guests to replenish their platters before the sacrifice of Isaac.  ‘It is too doleful a tale to watch without victuals.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ralf, thankful to see both the Louths and the Skirlaws moving towards the sideboard, made to follow when Walter seized his arm.  </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘What you said about Ezekiel and the sin of Sodom:  was it just to provoke Edmund?’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘On the contrary.  I could have said much more if I had had the chance.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘You have it now.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Really?’ Ralf asked in surprise.  ‘Then look at the gospels.  Both St Matthew and St Luke make it clear that Our Lord condemned Sodom for its unkindness to strangers.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘What about St Mark and St John?’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Neither speaks of it.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Then it might not be the sin against nature?’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Not unless it be a sin against human nature, since hospitality was second nature to the ancient Israelites – ’ Ralf strove to attend to his argument rather than to the swiftly vanishing food – ‘Remember that when Joshua destroyed Jericho, the one person he saved was a whore – the least of women – because she had made his messengers welcome.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Is that in the Bible?’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Her name was Rahab.  Say nothing to Edmund – ’  Ralf immediately regretted naming him as he followed Walter’s gaze to the tapestry where he was huddled with Agnes – ‘but this is one occasion when I might wish to turn Lollard and make the Scriptures plain to all.’  Walter stared at him in wonder.   ‘I only said “might”.’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘So it would be possible to make a different pageant of Lot’s Wife, one that removes the stain from the Sodomites and, as Mistress Underwood sees it, from those who represent them?’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Certainly.  If your fellow salters are willing to open their purses.  But given how many of them carped at the raising of the pageant silver this year…’ </p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ‘Leave me to treat with them.  Thank you, Sir Ralf, you have given me much to think on.   But you must be hungry,’ he said with a laugh.  ‘Have some sweetmeats.  The bookmen will shortly be here with Abraham and Isaac.   And then it is but a twinkling till the birth of the Lord.’ </p>








            <p><br><br></p>
            </td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="46" width="1"></td>
          </tr>
          <tr>
            <td height="103"><img src="/images/spacer.gif" alt=""
 border="0" height="103" width="1"></td>
          </tr>
        </tbody>
      </table>
      </td>
    </tr>
  </tbody>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
