<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue8/menu_issue8.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue8/mary_caponegro/artwork.html','','width=580,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="292" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">Back to the Garden <span class="texto2">by <a href="../../issue8/mary_caponegro/bio.php" class="link3">Mary Caponegro</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           
              <p>&nbsp;</p>
          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Thousands and thousands of young  people blend into one body. This  malleable landscape of flesh raises thousands of hands, each index and middle  finger held high in a V--no longer the symbol of victory but of peace. From the  stage, Country Joe speaks the language of the middle finger <em>minus</em> its  neighboring forefinger--not to condemn or dismiss but to celebrate, eliciting  from the crowd a selective alphabet far more ecstatic than the call-and-response  one might hear during the Prayers of the People at Sunday mass, well before the  kiss of peace. That same weekend, in fact, Margaret Kinsella, Janie Salerno,  Dawn Krotowski, Vicki Corrigan, Virginia and Angela Postodellafuoco, and the  vast majority of the girls who attend St. Rose recite the <em>Nicene Creed,</em> the <em>Our Father</em>, the <em>Eucharistic Prayer</em>, as well as the  responsorial psalms. Whether in their respective parishes or a church they see  only in August, they will dutifully pray for the Pope, the President, the  bishop, the clergy, the army, and every civilian, including the poor and the  sick and the lonely, each congregation soliciting God&rsquo;s ear: <em>Lord Hear our  Prayer, Lord Hear our Prayer, Lord hear our Prayer</em>. The drone begins  Saturday evening at five and resumes Sunday at eight-thirty, ten,  eleven-thirty, twelve forty-five, and again at five. Just as banks  and grocery stores have extended their hours, so has the ever-more-flexible Vatican  II Catholic Church.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;But two and a half hours north in the  Catskills, the three-day-long festival has become, as if a temporal version of  the bodies crammed into it, a single contiguous entity, and its jubilant, mimicking din drowns out all the  distant, sotto voce incantations, matching them syllable for syllable, transforming  entreaty into command. <em>Gimme an f!&mdash;</em>shouts Country Joe into the crowd, and hundreds of thousands of  people reciprocate<em> &ldquo;F.&rdquo; </em>&nbsp;&ldquo;<em>Gimme  a u! Gimme a c!</em> <em>Gimme a k!</em> <em>What&rsquo;s that</em> <em>spell?,&rdquo; </em>Country Joe McDonaldasks  his electrified audience, and through their collaborative fervor, those four  infamous letters inscribe themselve into the mellow ambience of folk music, pot  smoke and anti-establishment good will.&nbsp; <strong></strong><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For whom, meanwhile, do the girls of  St. Rose most fervently pray, huddled in pews, safe under rooves, assembled not  in a single, vast open-air congregation but in scattered locations across the  island and beyond? For the poor, the sick, and those who are alone. (They know  they should not put themselves in this category; they&rsquo;re too young to have  boyfriends and besides, that is not how the Church defines alone.) Being a  member of the Catholic Church, Mrs. Postodellafuoco believes--and has  repeatedly told her daughters--means never having to be alone, even if poor,  even when sick. She would not likely acknowledge that one hundred twenty miles  away, at Yasgur&rsquo;s Farm, an alternate church has evolved overnight, in the form  of a thousand-armed Siva-like body. Nor would she likely perceive this unwieldy  but functional body as the picture of health. And yet this appears to be the  case. Excepting a lack of some basic supplies&mdash;sanitary napkins and aspirin and  soap--and of course the anomalous bad trip, there are no complaints; there is  certainly no loneliness. Money is irrelevant, as somewhere along the line, due  to its ever-expanding corpus (a benign version of the Postodellafuoco girls&rsquo;  favorite horror movie, <em>The Blob</em>), the festival has become free of  charge. Thus no one need pay for this delectable taste of the zeitgeist&rsquo;s  forbidden fruit, and no one need pray for the soon-to-be-legendary,  self-sufficient squatters of Yasgur&rsquo;s Farm.</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  ******************</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Like a  gameboard&rsquo;s spinner, the spun bottle&rsquo;s spout directs the placement of  tentative, perfunctory kisses. Who knows who you&rsquo;ll get to kiss?-- so you&rsquo;ve  got to be brave, you can&rsquo;t be picky. Submit to the beauty of randomness. With  so many fewer boys than girls, of course, the bottle sometimes has to spin more  than once in a single turn, if for instance, a girl landed on a girl. When the  children are finally dizzy from spinning, the class is promoted to  training-wheels strip-poker (Not to worry, each token removal is barely  perceptable to the naked eye, as if the subtle rotation of some distant planet.) Take off your glasses, unlace a shoe. You&rsquo;ve  got another few moves before having to tug off a sock. Unfasten a button, the  top one, just one. Then pull that leather snake from its fabric loops; unbuckle  it first, silly. There is so much peripheral forfeit before getting down to the  nitty-gritty. Sorry there, Dunlop, taking your handkerchief out of your pocket  is not a legitimate move. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Clearly no  one expects, or for that matter wants, any grand sweeping gesture; they&rsquo;re not  even thirteen, after all, and for this crowd it doesn&rsquo;t take much ammunition to  be provocative. One detail should not be left out, however: the context of this  forbidden game&mdash;much like its mechanism&mdash;is chance.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;While  serving ice cream and cake, Lorraine&rsquo;s mother  begins to act strangely, her head moving back and forth like a stuck wind-up  toy. Lorraine,  apparently having encountered this situation before, immediately takes charge,  saying, &ldquo;Let&rsquo;s get you upstairs, mom, let&rsquo;s get you some rest,&rdquo; and now the mysteriously  out-of-commission Mrs.Del Vecchio has been given equally mysterious medication  and been taken to her bed. A disorder, Lorraine calls it,  and Virginia Postodellafuoco tries to envision the messy state of her room  transported into a head or body. She has never before been in a situation where  a mother is incapacitated, and without question won&rsquo;t be coming down to provide  or to spy. No one refers to it but everyone is aware of it, and since it isn&rsquo;t  exactly an emergency, just a &ldquo;situation,&rdquo; this unseating of authority does not  merit phone calls to two dozen parents, all of whom promised to pick up their  children at five o&rsquo;clock<strong>, </strong>whereas now it is only three. A motherless party is a  party officially over. Unofficially, however, it&rsquo;s just begun. That is why on  this particular Saturday, at this particular party, there is a window of  freedom, which even in the physically windowless basement of the Del Vecchio house, opens just wide enough to see a  peripheral glimpse of the so-near-and-yet-far Yasgur&rsquo;s Farm. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This window of opportunity, from the soon-to-be  eighth-graders&rsquo; vantage, is a bit like the Red Sea parting to let the Israelites  across, because God preferred to work with the tools at hand: with nature, that  is--rather than crafting a miracle from scratch. Although Sister Cordelay and  Father Manley would dispute this interpretation, deem it self-serving and  possibly sinful. Do you know what the word sophistry means? Surely you see,  boys and girls, that this circumstance is just the opposite of the miracle of  the Red Sea, because the devil would be delighted to endorse any causal  arrangement whereby sickness and suffering make room for sin, even if only venial  sin.&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; And  the chastened pupils would hang their heads, ashamed of their unintended  wickedness, though during the latter five of the ten Hail Mary&rsquo;s of their  assigned penance, they would find themselves trying to gauge the relative  wrongness of one opened button or unbuckled belt. For it seems to them that  even cumulatively, their token disrobing or smooching gestures would register  less on a scale of indescretion than Len Whiting&rsquo;s indecent exposure as Romeo.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Less than the Coppertone Girl&rsquo;s,  for that matter&mdash;her pale buttock exposed by a mischievous dog who cleverly  tugged at her bathing suit bottom, thereby displaying the depth of her  product-assisted tan. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As they progress  through the years to come, some of the girls of St. Rose will decide that this  is precisely the problem with adults--with parents and nuns and parish priests.  So stuck on decency, they tended to miss the essence of things. Len Whiting  offered his flesh to the camera acting as Romeo, whose mortal sin wasn&rsquo;t making  love (since he made it in wedlock) but playing dead for real&mdash;<em>for</em> love, for love&rsquo;s sake. In exchange,  he gained the right to share eternity (and eternal damnation, presumably) with  his beloved. To any romantic girl, that was a dynamic, not static--even if  tragic--afterlife. Whereas the Coppertone Girl, emblem of innocence, sporting  youthful blonde pigtails and clueless expression, was doomed to be pestered  into eternity, never permitted to graduate from frisky dog to frisky man,  meaning frisky fianc&eacute;e of course&mdash;exposed on a million billboards as a classic case  of arrested development&mdash;thus frozen into the very definition of a young lady.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When, during these years, Sister  Catherine John introduces them to Sisyphus and his myth, some of the girls will  remember this: a girl trapped in cuteness via the jaws of a dog, locked in  position, unable ever to move forward.<br>
  <strong>&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;********************<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>On top of Spa-Ghe- ti! All covered with sauce! I lost  my poor meat-ball&hellip;</em><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Hush now,  says mom, we&rsquo;re about to say grace. <em>Bless  us O Lord for these thy gifts which</em> <em>we  are about to receive from thy bounty</em>&hellip;&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Strana, questa pasta,&rdquo; says Nonna, who prefers both the taste and  conceptual wit of a strangled priest&rsquo;s neck, i.e. <em>strozzapreti</em>, to this vulgar circle of macaroni, its interior  detailed with a series of radiating spokes, that might have fallen off a  nineteenth century covered wagon. Everyone knows macaroni should mimic a shell  or an ear or a feather or strand of hair, maybe a butterfly--something directly  from nature.&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;But Nonna, why don&rsquo;t you approve of the wagon wheels? Don&rsquo;t they make  this kind of spaghetti in Italy?&rdquo; One sister looks to the  other for moral support. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Dad says it&rsquo;s the best kind of noodle to make a spaghetti western! And Daddy likes the wild west; you can come  if we take a vacation there. He says we&rsquo;ll rent a big trailer and drive through  the whole U.S.&rdquo;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;That fantasy does not materialize, however, because when push comes to  shove, Sal&rsquo;s enthusiasm for a family roadtrip is not corroborated by daughters  or wife, let alone his own mother, who feels the east coast is already too much  of America. But that doesn&rsquo;t mean  there will be no excursions&mdash;modified versions of Salvatore&rsquo;s dream. For  instance, if the family happened  to be headed upstate in their wood-paneled, red Plymouth wagon, driving at  modest speed along the road that led--just by chance--to the road that itself  led to Yasgur&rsquo;s Farm, it would probably be for the purpose of visiting a  Catholic camp, to see if the girls might want to spend a summer there, like  their dad did when he was a kid--year after year, in fact. St. Boniface was a good Catholic camp, where you learned  to explore the outdoors, after going to mass every morning, of course, and  maybe in time become a counselor yourself, the way he did.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;But the girls decide that, for now anyhow,  it&rsquo;s a little too rustic up there: a bunch of bunk beds in a little cabin and  so many bugs&mdash;not a whole lot better than summer in southern Italy&mdash;especially if there were alternatives. Their  father assures them there are, and disguises his own disappointment on the way  home.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Collectively  seeking out certain state&rsquo;s license plates to win an all-too-familiar game,  then singing the equally familiar tune, <em>Ninety-nine  Bottles of Beer on the Wall</em>, one might have hoped&mdash;that is, Sal might have  hoped&mdash;that his daughters would not distract him further from driving by asking  him to identify a series of bungalows that formed scattered compounds on either  side of the two-lane highway. The lettering on the sign beside these structures  seemed even more foreign to them than the mind-boggling <em>tutti le direzioni</em> that they had often seen on windy rural Italian  roads during their past summer visits to Nonna and Nonno. But all the girls  could pry from their father was one disaffected sentence: &ldquo;Those are for Jewish  customers. Not for us.&rdquo;<br>
  &nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;*************************</p>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Let&rsquo;s  play a game,&rdquo; says a voice on the phone, without introducing itself. Ginny  assumes it&rsquo;s a prank call, the kind she&rsquo;s been taught to hang up on  immediately.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Wrist calling razor. Wrist calling razor.&rdquo; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Simon, is that you? What are you  talking about?&rdquo;<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;I  thought you liked to play <em>Simon Says</em>,&rdquo;  says the voice Ginny now recognizes as Simon Brown&rsquo;s. &ldquo;Take two cuts forward,  one cut back.&rdquo;<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Simon,  don&rsquo;t do this. I&rsquo;m worried about you.&rdquo;&nbsp;  Ginny is starting to cry and her mother is calling from downstairs,  &ldquo;We&rsquo;re late, hurry up,&rdquo; but she can&rsquo;t get herself to respond.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Then  the inevitable reckoning: her mother in front of her face, incensed. &ldquo;What is  the matter with you, Virginia? Who is making you cry on the phone? What could  possibly be so traumatic in the life of a well-off twelve year old?&rdquo;&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Andiamo,&rdquo;  shouts Dad from downstairs, completely oblivious.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Ginny!  Mom! We&rsquo;ll be late for the movie,&rdquo; calls Angie from the stairwell, no more  informed than her father.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;It&rsquo;s  that effeminate boy, isn&rsquo;t it?&rdquo; Mrs. P. prods Ginny. &ldquo;No wonder they&rsquo;re  thinking to send him away. He&rsquo;s a bad influence, that Simon.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Mom,  quiet. He&rsquo;ll hear you. That&rsquo;s rude.&rdquo;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Don&rsquo;t  you be lecturing me on manners, Virginia.&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; And  then even louder from downstairs: &ldquo;I said Andiamo!&rdquo;<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Simon says, take the knife. Mother, may I?&rdquo; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;No, you may not!&nbsp; Simon pleeaaaase!.&rdquo;<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;We&rsquo;re  going to curtail this soap opera right now.&rdquo; Mrs. Postodellafuoco pries the  receiver from her daughter&rsquo;s hand and hangs up the phone&mdash;the special <em>princess</em> phone that was bought for <em>her</em> room for <em>her</em> birthday and will now be restricted, if not confiscated. &ldquo;Wash  your face and come downstairs; we&rsquo;ll be in the car, and I&rsquo;m counting.&rdquo; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ginny  prays Simon&rsquo;s histrionics will not yield action, and considers quickly  redialing or making a two-second emergency call to Maggie or Vicki, one of whom  Simon is perhaps dialing this very moment. Oh, she hopes so. Please, God, let  him be lifting the receiver instead of the razor. But the time for intervention and prayer is  officially exhausted because her mother is making a final, non-negotiable  appearance, her forehead deeply creased, her mouth set in stone.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Five.  Six. Seven&hellip;Do you want me to have to tell Daddy?&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;***************************</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Rose  Postodellafuoco finds Grace Slick suspicious. It&rsquo;s not just the bangs falling  over those smoky eyes and the wild, psychedelic clothes. It&rsquo;s that she supplants  convenient, reliable platitudes with enigmas. Just when a growing girl is  starting to remember whether the saying goes &lsquo;feed a cold, starve a fever,&rsquo; or  &lsquo;starve a cold, feed a fever,&rsquo; this Slick woman bursts down the door and  absurdly insists, <em>feed your head</em>. Who knows what other absurd or illicit  instructions are being disseminated down there in the basement where the lyrics  are muffled by sheetrock and a closed door. It&rsquo;s a whole floor away, its own  universe. Sal had insisted on a finished basement, to keep up with the Joneses,  he&rsquo;d said, &ldquo;for the girls&rsquo; sake.&rdquo; Then he&rsquo;d winked, &ldquo;And for our sakes too.&rdquo; By now they had no doubt progressed to the  strident rasp of Janis Joplin, goading some random companion to shatter her  heart, piece by piece.&nbsp;&nbsp; &nbsp;&nbsp;<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; It was so  much easier when pop songs were wholesome and mindless--when they sat in the  car, all three Postodellafuoco females, and parroted the radio&rsquo;s wholesome,  cheerful sentiments, such as <em>She loves you yea yea yea</em>, or <em>I wanna  hold your hand</em> or even more blandly, <em>the</em> <em>morning&rsquo;s gonna shine  like red rubber ball</em>.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Angie and Ginny, on the other hand, prefer the  hypothetical to the nostalgic. They and their friends take up a collective  thought experiment, one that, were it to be formulated via Sister Catherine John&rsquo;s  metaphoric lexicon, might read as follows: What if Adam and Eve, having been expelled  into loneliness, manual labor and shame, somehow passed through the looking  glass, and landed in a strange, new world, on the order of Yasgur&rsquo;s Farm? Would  this mutation transform a seductive snake from a vessel of knowledge into a  vessel of pleasure? Would our reimagined Bibilical parents have thus  overreached in the name of lust per se versus lust for knowledge? In this  revised reading from Genesis, the first man and his mate would crave sensation  rather than information, invest more in the <em>body</em> of Christ than the  all-knowing mind of God.The former&rsquo;s sacred name and flesh, though so often  coupled with passion, was never, except illicitly, bonded to pleasure.</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**********************</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ginny will miss  Simon&rsquo;s company, even if he is sometimes too intense. How will he possibly manage in military  school, quarantined in some compound, distant in feel, though likely not in  literal miles, from Yasgur&rsquo;s Farm? He  will probably study all the same subjects as she and her friends at St. Rose  (and likely in greater depth&mdash;if the military school is anything like St. Regis),  but studying will probably be the easiest part, compared to rising at dawn and  making a bed as efficiently as any candy striper--because if it lacked crisp,  perfect hospital corners there would be consequences--and doing calisthenics  far more rigourous than those performed in gym class with Sr. Patrice. She  can&rsquo;t imagine what it would be like to do push-ups and jumping-jacks, not for  an overweight nun in a modern habit with whistle and sneakers, but a  muscle-bound man with a crew cut and boots, not to mention a gun. The whistle  that man blows would likely sound a thousand times more shrill than the one  animated by the sterterous breath of Sister Patrice, soon to be lumbering  toward her equally apathetic charges. The somber dance of her red Keds will  seem to the girls of St. Rose, every week of the years to come, like a parody of  the dripping blood of Christ.&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Into the domain of young ladies, a sissy had  evidently strayed, whatever a sissy technically was. But for that matter, what  was a young lady? A girl in arrested development? Miss Coppertone? And what was a bona-fide,  grown-up lady? Some elusive concoction of cleavage and nurture? Why couldn&rsquo;t  she be a long-haired woman in a flowing dress, standing innocent yet  self-possessed beside a nearly as long-haired man in jeans--a man with whom one  might substitute a perfectly harmonized, customized duet for some slavish  recitation of vows? A Guinevere<strong> </strong>with  green eyes, a Sweet Judy Blue Eyes? Why couldn&rsquo;t such visions be transported  from a Woodstock stage to suburban  streets? Might Ginny ever convince Sister Catherine John that her folk music  heroes and heroines were modern troubador poets? Just listen <em>please</em>,  Sister, she&rsquo;d say, please just give them a chance, as she began her  presentation with Crosby, Stills and Nash&rsquo;s rousing chorus before their  extended instrumental riff, crescendoing in harmony toward the irresistibly  romantic entreaty,<em> Be my lady</em>. If Sister C.J. would allow it, Ginny  would carefully raise the stylus needle from the groove, lift off the first  record, and place another on the turntable such that John Sebastian could  commence his sweet, intimate, melodic homage: <em>She&rsquo;s a lady</em>. Then Ginny  would repeat the same procedure, yielding Joni Mitchell&rsquo;s melancholy  declaration: <em>I would be his lady</em>, <em>all my life</em>, to her metaphoric father-child,  Willy. Meanwhile Tom Paxton&rsquo;s versatile lady was both wine and a wild flying  dove, each of which images had deep symbolic relevance to Christianity,  connoting Eucharist and Holy Spirit respectively&mdash;thus providing persuasive  closure for Ginny&rsquo;s hypothetical presentation. <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; And yet to  be anything&mdash;and especially a lover--<em>all  my life</em> was a tantalizing abstraction to Ginny, for whom eternity was a  separate endeavor, of spiritual rather than carnal measure. The dutiful,  suck-it-up aspect of <em>till death do us  part</em> wasn&rsquo;t present in lyrics like these, lyrics that seemed to address a  more urgent love than that which defined her parents&rsquo; marriage, but that had  seemed to shimmer that night, years ago, between Mr. And Mrs. McGillicuddy. How  could one measure such things? For  surely there was enough love in Romeo and Juliet&rsquo;s brief, intense passion to  equal a whole life&rsquo;s worth--which is perhaps just the sort of sentiment the  widowed Mrs. McGillicuddy entertained when she reached, half-asleep, for that  bottle of pills--if that was in fact what she&rsquo;d done. No one would ever know  for sure. Certainly Ginny wouldn&rsquo;t; she&rsquo;d be the last to know, because her  mother wouldn&rsquo;t ever consider her mature enough to be told any of the available  information--although years of speculation has brought Virginia to her own conclusion.  How far, in fact, was the Kingdom of Heaven from the  Valley of the Dolls? An unbridgeable distance?<strong> </strong>Separated by the mountain  ridge of mortal sin ? And to what end? The result was not Grace Slick&rsquo;s  Alice-in-Wonderland magic; not an eat-me or drink-me, expand-me or shrink-me  pill, nor the bland, ineffectual vitamin that mother <em>gives</em>, but on the  contrary, the all-too-effectual pill mother <em>takes</em> to be soothed and to  sleep, and perhaps to continue to sleep--indefinitely.</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;************************</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ironically  enough, it might have been easier to sneak into Woodstock had you chosen to rough it at the  aforementioned Catholic camp so dear to your dad, given its proximate upstate  location. But other than dreaming, you can&rsquo;t  go to Woodstock if you are out of state, just over the border in Pennsyvania to  be precise, living it up in the that Pocono Lodge, going to camp just a few  hours a day--nothing too strenuous--learning to fish while your parents played golf,  learning to trot on a horse around the perimeter of a fenced-in ring, then in  the afternoon swimming out to the floating raft halfway across the lake,  climbing the ladder up onto it and dangling your legs over the sides without a  care in the world, and then diving off and swimming back to shore where you  lazed in the sun on the sand. And on Sunday, only on Sunday, you go to church,  the whole family as usual, a little country church whose congregation swells  with strangers every July and August, and then come into the fancy dining room  where you can order griddle cakes drenched in butter and syrup with sausage on  the side and be served by a waiter or waitress who deftly slides an index  finger through a special opening to lift up the crown-shaped silver cover that  is keeping the food all steamy and warm, the smiling waitress displaying your sumptuous  breakfast for your approval as if you were a queen. &nbsp;<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; But between  the luxurious breakfasts, when all of the campers march single-file on the  trail to the lake for their overnight trip with their fishing rods, or when all  the girls twice a week parade single-file on their horses into the ring, Ginny  finds it hard to keep her eyes focused straight ahead. She keeps turning around,  keenly aware of the sharp hook held by some incautious peer swaying inches  behind her, ready to snag on her clothes or her hair or her skin, and later  aware of the horse&rsquo;s obscenely long head with its large set of teeth. She can&rsquo;t  wait to get back to the main lodge with its large, seductively dark recreation  room, where if you were lucky while playing ping pong or pinball or pool you  might even meet a boy. But if you were less lucky, you&rsquo;d get sucked into some  group activity involving both parents and children, in fact myriad guests of all  ages standing in formation, snaking through the ballroom, obligingly  shaking various parts of their anatomy in approximate synchrony, as the Pocono  lounge band provided the musical fuel for inhibition. In short, everybody and  his brother must join in this cheerful if awkward collaborative effort to  create wholesome family fun <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When the fun is concluded, and the families who  could afford to go in the first place return to their respective suburbs, Simon&rsquo;s  older sister, back from the spontaneously historic three days at Yasgur&rsquo;s Farm,  narrates for her spellbound younger brother, who in turn spreads the word to  all the incredulous, covetous Woodstock wannabees  in his class. Simon has always preferred the company of girls; they are nicer  and sweeter and easier to impress, and besides, there are only a handful of  boys in their grade.What&rsquo;s more, for the girls&rsquo; titillation, he can count on  his sister to share even unsavory details, which cause the intended effects on  his peers, yet make them yearn no less to have been there.&nbsp; &nbsp;<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ginny  imagines the Mountainview Lounge Band transposed to a Woodstock stage, but  the comic absurdity is small consolation. How might they alter their corny  sounds and still cornier lyrics? <em>You put  your right breast in, you put your right breast out. You put your right breast  in and you shake your ass about</em>---<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If only they were a few years older, they might have been part of it all.  Woodstock comprises their missed date with destiny, and that is  excruciating&mdash;to have it so tantalizingly close, so replete with <em>un</em>-Christian  mysteries. The concert writ large is as monumental to Ginny and her friends as the nearly  concurrent historic event of putting a man on the moon, the latter being an  occasion for unanimous national celebration, though curiously controversial  between Nonna and Dad. Some bizarre argument that Virginia and Angela  try to stay out of--something to do with Americas  putting a flag on the moon instead of a cross. Italy,  Nonna insisted, would <em>never</em> do such an ungodly thing. Imagine promoting  the fatherland rather than God the Father! &nbsp;&ldquo;Non farebbe mai.&rdquo;&nbsp;&nbsp;&nbsp; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Damn  straight,&rdquo; says dad, &ldquo;because Italy would  never produce the technology! La moda, va bene, disegno, va bene, ma  technologia! Forget it! Disastro!&nbsp; And don&rsquo;t  forget Mussolini,&rdquo; &nbsp;he adds.&nbsp; &ldquo;You got Dante, Da Vinci and all o&rsquo; those  geniuses but then Mussolini. Figure that out.&rdquo;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Then Mom interjects out of nowhere, &ldquo;But  didn&rsquo;t Buzz Aldrin receive the Eucarist on the moon?&rdquo; even though the  discussion is pretty much finished. &ldquo;That&rsquo;s as much of a statement as a cross  on the moon, in a way, Antonella. Christo sulla luna, capito?&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Did he dip  it in Tang?&rdquo; Ginny asks, and Mom gives her a withering look.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Senza  prete, non c&rsquo;e il sacremento. Il Corpo di Christo ha bisogno un prete.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;What is  she sayin&rsquo;, Mom?&rdquo; asks Angela.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;That it  isn&rsquo;t a sacrament without a priest present.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;I think it  would be kinda tough for NASA to find a  priest-astronaut to ride along and serve mass, Ma,&rdquo; says Sal. &ldquo;Go ask Lorenzo  if there are any aeronautics electives offered in seminary.&rdquo;<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Maybe a  priest performed mass just before the launch,&rdquo; Angie says, hoping to solve the  dispute, &ldquo;and then put all the left-over hosts into the shuttle.&rdquo; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Good  thinking, Ange.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Yea,  that&rsquo;s gotta be it,&rdquo; says Dad, &ldquo;case closed. &nbsp;The host had to have been pre-consecrated.&rdquo;<br>
  <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><br>
  <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  ************************</strong></p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The traffic  on Hillside Ave is heavy  as usual, as it advances toward the major intersection of Jericho Tpke., and  thus it is difficult to hear oneself. Virginia Postodellafuoco faces away from  the street noise, cradling the phone&rsquo;s receiver as she stands at an open kiosk&mdash;which,  if one were to fashion a PSAT analogy question, is to a bona fide phone booth  as a urinal is to a full toilet-stall. Not that a standardized test gets that risqu&eacute;;  not that Virginia is old enough to take that test yet, and not that she would  know much about urinals, except from some unsolicited descriptions offered by  Simon Brown, who often delights in mild forms of provocation, and who, at the  moment, is missing in action. Simon&rsquo;s absence makes Ginny nervous, fearful that  he might have <em>taken</em> the knife ( that is, razor), so as to avoid having  to take up a gun and do target practice, so as to avoid trading his plaid  blazer for a khaki or camouflage uniform, or whatever they make boys in  military school wear. Something dark blue with brass buttons maybe? Every day Simon seems more morose, waiting to  be shipped out to the military academy, and his only diversion from this  disconsolate state of mind is the occasional shopping excursion with Vicki and  Darcy and Maggie and Dawn and Ginny, despite the communal disapproval of all  the girls&rsquo; mothers: &ldquo;Boys don&rsquo;t go shopping. He should be out playing ball.  Does his mother know?&rdquo; Over these objections, and without exactly advertising  the fact to their mothers, the girls had invited Simon to come with them today,  but he&rsquo;d stood them up, making Ginny suspicious. Her worry increases by the  hour. Hence her presence now in the half-booth, this open-air phone-stand, on a  congested street lined with shops and cars on the way to those shops, cars  headed for vast parking lots: in short, a street not conducive to conversation. Hence her relief when she actually reaches  him, hears Simon&rsquo;s living, endearingly nasal voice. But his tone indicates that  the challenge has only begun.&nbsp; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Cheer <em>up</em>,  Simon,&rdquo; she says earnestly, desperately, into the receiver, her hand now cupped  over her other ear to block out the considerable ambient noise of the Hillside  Avenue intersection, &ldquo;I promise we&rsquo;ll all keep in touch through the summer&hellip; and  next year, and forever. Did you hear me, Simon, forever! I promise.&rdquo; This  shouting over traffic takes even more energy than the fraught conversation  they&rsquo;d had last night. The blue princess phone in her bedroom had felt much  more intimate&mdash;that is, until her mother intruded. (But her mother is nowhere  near now; she will not arrive to fetch Ginny from the shopping expedition for  another hour.) As she listens to Simon&rsquo;s now rather annoying voice, Virginia  Posto closes her eyes to facilitate concentration.&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;It&rsquo;s gonna  be living hell. I&rsquo;ll get beat up, I know it.&rdquo; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Before Ginny realizes it, something has  happened. Someone has touched her. A random hand has been placed on her  buttock, then removed just as quickly. It&rsquo;s the kind of joke Simon himself,  were he physically present and not just a plaintive voice in her ear, might  play on her.&nbsp; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Hold on a  second,&rdquo; she says, and whips her head around to see the benevolent face of a  tall black man, bearing an expression not the least sheepish or furtive. On the  contrary, he is smiling a mile wide, as if he had just exchanged how-do-you-do,  it&rsquo;s-a-lovely-day, isn&rsquo;t-it? Then he winks, as if letting her in on the joke,  waiting for her to get it, the sequence of smile and wink seeming to say, &lsquo;see  how womanly you are, and see how much I appreciate how womanly you are, and  isn&rsquo;t it time to enjoy life, young lady?<strong>&rsquo; </strong><br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Neither  mother, nun, nor priest have prepared her for a gesture this blunt: a stranger  touching her in a private place, not with a threatening look but a beatific  smile on his face--a contact intended perhaps as a compliment more than a  provocation. (Not entirely unlike the  Italian boys who had swarmed as she and her sister walked down the city streets  of Rome, their hands glancing ardently if over-zealously as they chanted, Ciao  bella! Those boys had been pests, yet behaved as if every girl were a gift from  God&mdash;not just glamourous, fashionable girls&mdash;as if not only Angie but Ginny too  were beautiful and desirable.) <strong></strong><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Simon, the  strangest thing just happened.&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;What?&rdquo;&nbsp; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;This guy  just touched me while we were talking.&rdquo;&nbsp; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Where?&rdquo;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Here. In  the phone booth.&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;No, dummy,  what part of you?&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;My bottom.&rdquo;&nbsp; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;You mean he goosed you?&rdquo;<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;No&hellip; I mean, I don&rsquo;t think he did&hellip;what exactly does  goose mean again?&rdquo;<br>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        Simon laughs raucously and offers no information.  When that episode is finished, he asks a yet more straightforward question. &ldquo;Is  he still there?&rdquo; <br>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    Ginny turns back to the street. The about-face  chesire smile is no longer visible.&nbsp; &ldquo;No,  he walked past.&rdquo;&nbsp;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Well, you  don&rsquo;t have to worry then. But you better tell your mother.&rdquo; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;You think  I should?&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Aren&rsquo;t  these the kind of things girls tell their mothers?&rdquo; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;I guess  so. But you know how my mother is. I mean, you heard her last night. She isn&rsquo;t  someone to, uh&hellip;share everything with.&rdquo;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Now, if a  man had touched <em>me</em>, I couldn&rsquo;t tell my father. If you get my  meaning.&rdquo;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;I&rsquo;m not  sure I ever&hellip; entirely get your meaning, Si.&rdquo;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;You girls  have it made. I&rsquo;m so jealous of you.&rdquo;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;Simon,  don&rsquo;t be ridiculous. It isn&rsquo;t so easy. My folks really wanted a boy, for  example.&rdquo; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;She gropes in her purse for another nickel or  dime as the automated operator&rsquo;s voice says, <em>Please</em> <em>deposit five cents for  the next five minutes</em>. &ldquo;Simon, Simon, are you still there?&rdquo; She inserts two  nickels, perhaps not in time. <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <em>Please deposit five cents.</em><br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;I  desposited it already, damn it.&rdquo; She is surprised by the volume of her own  voice.&nbsp; &ldquo;Simon&mdash;Jesus!&mdash;are you still there?  Can you hear me?&rdquo;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;I&rsquo;m not  the messiah, but thanks anyway. And of course I can hear you, you&rsquo;re yelling.&rdquo; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Not  at you, at the operator.&rdquo;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;I know,  Ginny. I know. But don&rsquo;t make stuff up just to make feel better. It won&rsquo;t  work.&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;I&rsquo;m not  making it up, Simon. They did want a boy, they still do. You should come live  with us.&rdquo; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &ldquo;Sure. Then  they&rsquo;d still want a boy and they&rsquo;d say so. I&rsquo;d feel even worse.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;That isn&rsquo;t  funny.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&ldquo;I&rsquo;m being  serious.&rdquo; <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Well, I  don&rsquo;t want you to feel any worse, Si, but you know I feel pretty crummy about  it now. You&rsquo;re not the only one with feelings, you know&hellip;Simon? Did you hear me?&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<em>Please  deposit ten cents</em>. And now she feels even more worried to lose him  while scolding instead of consoling and she can&rsquo;t believe it, she&rsquo;s completely  out of change. Ransacking her pockets and purse, Ginny finds only lint and  pennies and a couple of paper clips and the stupid button she couldn&rsquo;t be  bothered to sew on her school blouse, and then suddenly something lands on the  sidewalk beside her, like manna from heaven: a dime. She looks up to see the  same man, the same smile, sauntering past her now in the opposite direction,  and when they make eye contact, he tosses another dime toward her. Clutz that she is, she doesn&rsquo;t quite catch  it. But that doesn&rsquo;t seem to to perturb the hand-man, whose smile is even more  radiant as he watches her bend to pick up her prize, the receiver dangling from  the stall and Simon, she hopes, holding on, blind to the handman&rsquo;s final congratulatory  wink. <strong></strong><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;************************
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;One might think Woodstock had never occurred, even by proxy, even by  fantasy&mdash;as far as these girls are concerned, they who at the cusp of  adolescence have been forbidden to explore it first-hand. Just as violence,  according to Sr Catherine John, always occurred off-stage in Greek tragedy; its  inverse: frolic--or for the sake of hyperbole, Dionysian revel--was  intrinsically off-stage for Virginia, her sister, and the rest of the girls in  their respective grades at St Rose. For even three years after the infamous  pagan festival of upstate New York, the closest version of revel for these  girls is taking place here in the gym, where freshmen and sophomores and  juniors and seniors are gathered in clusters, arms at their sides, their faces  tramsmitting a spectrum of eagerness, panic, ambivalence, while their bodies  stand awkwardly or sway tentatively to the music. On no other occasion can one  find each girl dressed differently than her neighbor: in dresses, nice blouses,  dress pants, shoes with heels--not a loafer or plaid skirt in sight. This  creates a far more diverse composition than one would customarily see in this  vast, barren room generally used for assembly or mass or a basketball  game&mdash;rather than pleasure. But this night is not designated for to obedience or  worship or team sport. Tonight one cannot divide the females into their  customary fractions: one third shooting baskets, one third waving pom-poms for  the former third, and one third languishing in the bleechers. (This last set  would generally include Ginny and Darcy and Janie, as usual out of commission  and complaining as they loitered. &ldquo;What&rsquo;s the point of cheering for other <em>girls</em>?  Know what I mean? It&rsquo;s a little&hellip;peculiar.&rdquo;)&nbsp; <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Only last week this same auditorium was filled with row upon row of metal  folding chairs from which jutted a phalanx of bare female knees, each a knobby  oasis of flesh between cuff of knee-sock and hem of plaid skirt. The knees,  never crossed, perfectly parallel, like the eyes above them, formed a clean  line of sight to the male who solemnly held up a gold ciborium behind a  makeshift altar. By Thursday, the gym was commandeered for a special assembly  instead of a mass, the hand-made banners decorating the altar replaced by a  large screen mounted on the front wall. Sister Mary Moynihan sought to prepare  the girls for their future with a documentary film about birth, the sequel to  which was a film documenting the obstruction of birth, which their futures, of  course, precluded. Ginny was made  no less squeamish by one than the other,  though she understood as well as any girl sitting in her midst that the first  documented miracle; the second, mortal sin.  The image concluding the film was a dumpster outside the depicted  illicit facility. Janie, on the other hand, had to leave in the middle of the  film, so as to vomit in the relative privacy of the first-floor bathroom stall. <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  But neither birth nor obstruction of birth could occur  without certain conditions--rather elusive conditions--and while references  were often made to the highly mythologized opposite sex, seldom were they  visible ---let alone as a critical mass. Now a whole new population has invaded  the gym, a whole new gender of temporary squatters, who if sighted not Saturday  evening but Monday morning would virtually set off a fire alarm. Only one row  of chairs lines the wall. Most students are standing; the others attempting  some form of dancing. Virginia Postodellafuoco is one of the former and about  to become the latter, because someone is coming toward her. <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  So this is the body whose soul matches mine, thinks  the mortified, thoroughly disappointed girl. Last night she&rsquo;d felt hopeful and  fearless in their own basement, an intimate space much more congenial than the  gym, with its postered walls and familiar adolescent clutter. Sprawled across  orange vinyl, the girls, singing loudly, submitted eagerly to the Jefferson Airplane&rsquo;s  hypnotic sequence of rhetorical questions. Ginny responded in her heart with an  unequivocal yes (she <em>does</em> want, <em>does</em> need, she <em>would </em>love).  But where and by what means was a girl to go to carry out Miss--or Ms.--Slick&rsquo;s  interdiction, when she commanded as if with finger pointed straight at Ginny&rsquo;s  conspicuous Roman nose, <em>You better fnd</em> <em>somebody to love</em>, with an  authority more persuasive, certainly more seductive, than any nun&rsquo;s. Then a  light bulb went off inside Ginny&rsquo;s head just as bright as the sight of an angel  from heaven. The school dance, the school dance! Through scientific precision,  via the latest technology, she was <em>bound</em> to find someone to love. And Angie became her ally, as they prepared  themselves, ransacking the closet, sneaking makeup. &ldquo;Let&rsquo;s try to do something  with that hair.&rdquo; But what could one do really, except strategically insert a  pretty barette or two. And then the inevitable, excruciating delay--when Dad  told mom Ginny wasn&rsquo;t permitted to leave the house with a blouse that sheer,  even with both a brassiere and a camisole underneath. So then it got even  later, and Angie and Ginny and Mom went into emergency-wardrobe-mode, trying to  find anything that would go nearly as well with the powder blue velvet  bellbottoms, whose pretty butterfly appliqu&eacute;s Angela and mom had helped her sew  onto the hip pockets. No top would look as sophisticated with them as that  slightly sheer, puckered material had. Why couldn&rsquo;t anything go forward  uncensored? What a coup it was that a girl named Grace had grown up to initiate  thousands of teen-age listeners into the mysteries of pharmacology and the  ultimate falseness of alleged truth.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Once dropped off at the gym, things begin to  go further awry. Yes!, she has solemnly sworn to the sensuous voice of Grace  Slick, she does indeed need <em>somebody to  love</em>, but not <em>this</em> badly, this desperately. Love cannot possibly be  meant to take the form of this unctuous, slightly obese young man walking  toward her, computer print-out in his hand. There must be some mistake,  Virginia Postodellafuoco is about to say; she is certain there must be. And yet the numbers match precisely. On his  card: forty-three. On her card forty-three. How can it be? The short-cut  precision of technology--called in secular parlance miraculous--is not boosting  Virginia Fiorenza&rsquo;s self-image any. <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  He extends  his arm to shake her hand but the clumsy boy drops his card, and for a moment  he stands there nonplussed, too embarrassed to pick it up. Suddenly he squats  to the floor, leaving Ginny to gaze down at the top of his crew-cut head. Then  his pimply face is before her again, his glasses slightly askew from the abrupt  movement. With the card in his pocket now, he offers again his hand, which is  sweaty, and wouldn&rsquo;t you know, the band has just started a slow dance. How can  she refuse, having thrown her hat into the ring by participating in this  pathetic process in the first place? Nobody forced her to fill out the  questionnaire; she had wielded her number two pencil with at least as much  alacrity as the next girl, probably far more. At least initially. <br>
         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     Felicia and  Dawn, official facilitators of St. Rose&rsquo;s first-ever computer dating dance, had  helped Ginny interpret the ostensibly straightforward questions, such as, &ldquo;Are  you an introvert or extrovert?&rdquo; Depending on whether Ginny was home with her  parents or out with her friends, it was two different answers, but there was no  blank space in which to write &ldquo;both,&rdquo; or &ldquo;I alternate,&rdquo; let alone a long phrase  like &ldquo;depends on the situation.&rdquo;&nbsp; In  fact, the deeper she got, the more daunting Ginny found this compatiability  questionnaire, skipping over questions much more frequently than she would for  the PSAT. At the end, she went back to all the skipped ones, but only resolved  a few. Could it be some kind of trick question, Dawn? she had asked, absurdly  perplexed. Finally Felicia said, &ldquo;This is a dumb questionnaire, Gin, not a  Regents literature essay; and if you keep questioning questions, we&rsquo;ll have to  mark you down as an honorary extrovert!&rdquo; <strong></strong><br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And if only they had! Why, why, <em>wny</em> hadn&rsquo;t she marked the oval next to  extrovert instead? Her pencil had hovered there, wavering back and forth. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The  unctuous boy, who <em>had</em> obviously  blackened the introvert oval, holds her tighter and tighter as the song  progresses and Ginny is too self-conscious to make a scene or burst free of his  body&rsquo;s grip; there is something unsavory about his pressing against her like  that, suffocating, as if he were trying to strangle her, but much lower down  than her neck. She is too humiliated and stunned to know how to break free  without calling attention to this abortion of a fairy tale, this conceptual  prince turned actual toad that some objective technology cruelly matched her  to, as if to say, this is what you deserve, Ginny-Juliet. Say hello to your  customized Romeo--and by the way, might as well reach for that happy dagger  right now! <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Locked in  this unsavory vise, she does not have what Sr. Mary Constance called her <em>thinking-cap  on</em>, though obviously Dawn and Felicia had theirs snugly fitted when they  volunteered to do <em>all </em>of the distributing and then <em>all</em> of the collating  of <em>all</em> of the <em>other</em> girls&rsquo; questionnaires. Weren&rsquo;t those two savvy to exclude themselves  from this dubious<strong> </strong>sweepstakes? This  special treat the nuns provided via Student Council, this treat that was  supposed to be <em>her</em> ticket to romance. <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Who says  Catholic education is old-fashioned?&rdquo; Sister Constance will ask at next week&rsquo;s  assembly, smiling triumphantly, her modified, merely knee-length habit  providing a convenient prop for her rhetorical question. &ldquo;We offer our girls  innovation whenever feasible--and appropriate, of course.&rdquo; Then her expression  would change every so subtly as she folded her hands and stepped toward her  audience, pausing before continuing. &ldquo;More importantly, who says charity is no  longer prevalent in our society? May I present, girls,&rdquo;&mdash;and she would gesture  proudly toward the row in which the members of Student Council sat&mdash;&ldquo;the shining  example of Dawn and Felicia, excellent students and excellent citizens willing  to sacrifice their own enjoyment for the sake of their peers?&rdquo; <br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Ginny will  come to realize that making the  honor roll every semester is probably the least of what distinguishes this pair  as resourceful. One could easily enough infer from their twinned Mona Lisa  smiles that charity and common sense were, in fact, never more closely  affiliated.</p>            <P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
