<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue4/menu_issue4.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue4/edwin_williamson/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">Extract from &#8220;Borges: A Life&#8221; (2004) with a foreword (2008) and afterword (2008) <span class="texto2">by <a href="../../issue4/edwin_williamson/bio.php" class="link3">Edwin Williamson</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
              <br>
              <p><strong><em>Foreword. August, 2008</em></strong></p>
              <p>One Sunday in May 1961  Jorge Luis Borges was having lunch in Buenos Aires at the house of his friend  and occasional collaborator, Adolfo Bioy Casares, when he received a telephone  call informing him that he had won an international literary prize which he had  never heard of before. At first he thought it was a joke, but in fact it was a  prize which was being awarded for the first time that year. Six publishing  houses &#8212; &ldquo;Gallimard&rdquo; of France, &ldquo;Einaudi&rdquo; of Italy, &rdquo;Rowohlt&rdquo; of Germany, the  Spanish firm of &ldquo;Seix Barral&rdquo;, &ldquo;Weidenfeld and Nicolson&rdquo; of London and &ldquo;Grove  Press&rdquo; of New York &#8212; had created the International Publishers' Prize for an  author of any nationality whose existing body of work would have &ldquo;a lasting  influence on the development of modern literature&rdquo;. The winner was to receive $10,000 and have a  book translated and published by each of the sponsoring publishers.</p>
          </td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <br><p>The award of the prize had  been entrusted to six committees, each drawn from the countries represented by  the various publishing houses. In May, writers, critics and academics (among  them Iris Murdoch, Alberto Moravia, and Hans Magnus Enzensberger) convened at  the &ldquo;Hotel Formentor&rdquo; in Mallorca. Two names  eventually emerged &#8212; Samuel Beckett and Jorge Luis Borges. The French,  Hispanic and Italian committees argued in favour of Borges, but the British,  Americans and Germans preferred Beckett.&nbsp;  The organizers had planned to call on a seventh, Scandinavian committee,  which would have broken the deadlock, very likely by voting for Beckett with  the &ldquo;northern&rdquo; block, but there had not been time to put it together for that  year. The Americans at one point tried to break the deadlock by introducing the  candidacy of Henry Miller, but this late proposal was thrown out. Eventually,  it was resolved to bring the matter to an end by splitting the prize equally  between Beckett and Borges. </p>
            <p>&ldquo;As a consequence of that prize&rdquo;, Borges was to write, &ldquo;my  books mushroomed overnight throughout the Western world.&rdquo;&nbsp; Indeed, within a few years, he was being  acclaimed as one of the great writers of the twentieth century. Certainly, he  was to become the most influential writer in the Spanish language of modern  times. Not only did he have a seminal influence on Latin American literature,  he was subsequently to have a remarkable impact on a rising generation of  writers in Britain, the USA, Italy,  France  and many other countries. Borges&rsquo;s work encouraged writers to embrace fiction  as a self-conscious, rhetorical artefact, susceptible to unashamed fantasy and  to overtly intellectual, and even philosophical, concerns. Additionally, his  stories and essays were perceived to have anticipated some of the principal  topics of modern critical theory, from Russian formalism through to post-modernism.  His subtle reflections on time and the self, or on the dynamics of writing and  reading, generated texts which embodied ideas such as the arbitrariness of  personal identity, the de-centred subject, the &ldquo;death of the author&rdquo;, the  limitations of language and rationality, &ldquo;intertextuality&rdquo;, or the  historically-relative and &ldquo;constructed&rdquo; nature of human knowledge (viz.  Borges&rsquo;s elliptical &ldquo;histories&rdquo; of abstract concepts, such as infamy, eternity  or angels).&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            <p>This international  reputation, however, was based on a somewhat limited view of his actual output:  his fame rested almost exclusively on the stories collected in <em>Fictions</em> (1944) and <em>The Aleph</em> (1949), and the critical essays collected in <em>Other  Inquisitions</em> (1952); there was, for instance, very little interest in, or  indeed access to, his poetry, especially outside the Spanish-speaking world,  even though Borges had started his career as a poet and always regarded poetry  as his favourite medium. What&rsquo;s more, the pronounced metaphysical concerns of  Borges&rsquo;s fiction of the 1940s fostered the view among critics that his work  belonged in an ideal, timeless space, a kind of literary utopia in which  writing amounted to a self-referential game of quoting or re-writing earlier  texts. </p>
            <p>This radical decontextualization was,  of course, encouraged by certain strikingly original and revolutionary ideas in  Borges&rsquo;s own work. For example, in his &ldquo;Autobiographical Essay&rdquo;, he suggested  that &ldquo;Pierre Menard, Author of <em>Don Quixote&rdquo;</em> was the story which had  inaugurated the new style of writing he called &ldquo;ficciones&rdquo;, short stories or prose-texts  whose brevity allowed him to condense mental play into reverberating images and  situations. &nbsp;&ldquo;Pierre Menard&rdquo; is a  tongue-in-cheek account of the absurd enterprise of an early twentieth-century  French writer, who sets out to &ldquo;re-write&rdquo;  Cervantes&rsquo;s <em>Don Quixote</em> word for word, and it was to become one of Borges&rsquo;s  most famous texts because it calls into question the  unique authority of a literary classic, and insinuates that even the most  revered of writers, in this case Cervantes, the great iconic author of Hispanic  letters, may in the end be not much different from any other author, thereby  exemplifying one of Borges&rsquo;s favourite themes, the arbitrary or illusory nature  of personal identity. The questioning of an author&rsquo;s  status as the sole originator of meaning also entails a severing of the text  from its context, for if the author is no longer a privileged authority, then  the context in which the work was written cannot be privileged either and it  falls to the reader to provide the text with meaning according to his own  culture, history and circumstances.</p>
            <p>These ideas were a feature of Borges&rsquo;s writing some thirty  years before Roland Barthes declared the &ldquo;death of the author&rdquo; in his famous  essay of 1968. Nevertheless, they sit uneasily  alongside Borges&rsquo;s long-held belief that  writing, ultimately, is a form of autobiography. In 1926 he had declared in &ldquo;A  Profession of Literary Faith&rdquo;: &ldquo;All literature is autobiographical, in the last  instance. Everything is poetic inasmuch as it confesses a destiny, inasmuch as  it gives us a glimpse of one.&rdquo; And in 1967, when already famous for his &ldquo;ficciones&rdquo;,  he confessed to an interviewer: &ldquo;I have felt my stories so deeply that I have  told them, well, using strange symbols so that people might not find out that  they were all more or less autobiographical. The stories were about myself, my  personal experiences&rdquo; </p>
            <p>How can one reconcile  these seemingly contradictory conceptions of the nature of writing? The  inconsistency, I would say, sprang from a tension that is evident at the very  core of Borges&rsquo;s work between a desire to discover and affirm a destiny -- a  true self &ndash; through the process of writing, and a horror of what he called &ldquo;the  nothingness of personality&rdquo;. The fluctuations between self and non-self would  vary in intensity according to circumstances, but they were present throughout  his career, and, in fact, by looking into the context in which &ldquo;Pierre Menard&rdquo;  itself was written, one can appreciate the extent to which even this most  abstract of literary texts was a product of Borges&rsquo;s personal experience, for  it emerged from an acute crisis of faith in his own destiny as a writer,  stemming from deep-seated conflicts provoked by the final illness and death of  his father. </p>
            <p>&nbsp;</p>
            <p><strong>Extract  from &ldquo;Borges: A Life&rdquo; (2004)</strong></p>
            <p>Some  time in the latter months of 1937 Borges's father suffered a stroke which left  him paralysed down the left side of his body. At the age of sixty-four, Dr.  Borges was blind, debilitated by an aneurysm, and now immobilized. Borges would  give us a glimpse of his father's condition in his story &ldquo;The Other&rdquo;: &ldquo;His left  hand resting on his right hand was like the hand of a child lying on the hand  of a giant.&rdquo; The stroke destroyed what remained of Dr. Borges's will to live:  he wanted to die, he used to say, he wanted to die &ldquo;completely&rdquo;, by which he  meant dying in body and soul with no prospect of an afterlife. </p>
            <p>It was  very likely his father's plight that jolted Borges into seeking a full-time job  for the first time in his life.&nbsp; He was  thirty-eight and had no educational qualifications whatever, not even the  baccalaureate, which he had never got round to completing.&nbsp; Having previously worked only as a part-time  literary journalist at a number of short-lived, poorly-paid jobs, the best he  could manage by way of earning an independent living was a post as a library  assistant in the Municipal Library Service.&nbsp;  On 8 January 1938 he started work at the Miguel Can&eacute; Library in the working-class district of Almagro on the  southside of Buenos Aires,  effectively at the other end of the city from where he lived. His salary was a  measly 210 pesos a month, though some time later, through the influence of  friends, it was raised to 240 pesos, a miserable wage all the same. </p>
            <p>Life at  the Miguel Can&eacute; Library was pretty dire for a writer like Borges. None of his  colleagues showed any interest in books; they spent their time talking about  soccer and horse-racing, or telling each other smutty stories.&nbsp; The depths to which he had sunk were brought  home to him when a colleague came across a biographical note in an encyclopedia  on a certain Jorge Luis Borges, and pointed out the coincidence of their names  to Borges, not realizing that they were one and the same person. </p>
            <p>A  couple of upper-class lady-friends once came to visit him at the library and  were so horrified by what they saw that they rang him up and told him: &ldquo;You may  think it amusing to work in a place like that, but promise us you will find at  least a 900-peso job before the month is out.&rdquo; But working as a library  assistant was not one of Georgie's more perverse jokes, it was the position he  had attained by his own efforts as an independent adult in the world, and it  caused him unutterable distress:</p>
            <p>&ldquo;Now  and then during these years, we municipal workers were rewarded with gifts of a  two-pound package of <em>mate</em> to take  home. Sometimes in the evening, as I walked the ten blocks to the tramline, my  eyes would be filled with tears. These small gifts from above always underlined  my menial and dismal existence.&rdquo; </p>
            <p>Borges's  anguish was compounded by his awareness of his father's disappointment in him.  He would recall his father commenting on a well-known apothegm of the Liberator  General Jos&eacute; de San Mart&iacute;n, in which the founding-father of the nation extolled  a man's overriding duty to fulfil his destiny: <em>&ldquo;Ser&aacute;s lo que debes ser, y si no, no ser&aacute;s nada&rdquo;</em>&#8212;&ldquo;You must be  what you ought to be, and if not, you will be nothing at all&rdquo;, which, in Dr.  Borges's cynical gloss, became: </p>
            <p>&ldquo;You  must be what you ought to be &#8212; you must be a gentleman, a Catholic, an  Argentine, a member of the Jockey Club, an admirer of General Uriburu, an  admirer of the extensive landscape paintings of Quir&oacute;s, or you will be nothing  at all &#8212; you will be a Jew, a good-for-nothing, a first assistant in a  library; the Ministry of Culture shall ignore your books, and Dr. Rodr&iacute;guez  Larreta shall not send you any autographed copies of his own.&rdquo; </p>
            <p>The  reference to a &ldquo;first assistant&rdquo; indicates that this conversation took place  early in 1938, some time after Georgie had started work at the library. It  would have been painful enough for Borges to witness the depth of his father's  disillusionment, but the pain must have been exacerbated by the knowledge that  his father saw him as a failure too. Neither had found much success in the  world &#8212; the father had not fulfilled his aspirations as a writer and was now  blind and paralysed, while the son had betrayed his early promise as a poet and  risen to the giddy heights of &ldquo;first assistant&rdquo; at a municipal library in some  godforsaken corner of Buenos Aires. </p>
            <p>And  yet, as the reality of death drew closer, Dr. Borges could not reconcile  himself to literary failure. He confessed to being dissatisfied with his novel <em>El Caudillo</em>, and appears to have  placed some of the blame on Georgie: he was unhappy with the expressionist  metaphors his son had suggested to him in Mallorca.  He then asked his son &ldquo;to rewrite the novel in a straightforward way, with all  the fine writing and purple patches left out&rdquo;, and the two of them would  discuss ways of improving it. </p>
            <p>This  strange request to rewrite <em>El Caudillo</em> was itself an index of Dr. Borges's sense of failure: when Georgie had first  started writing poetry he was told by his father: &ldquo;Each of us must save himself  by his own efforts; you must never seek advice from anyone.&rdquo; At the end of his  life, however, the unfortunate Dr. Borges, having failed to save himself as a  writer by his own efforts, turned to his son for help. But it was a request  that put the son in a terrible predicament, for how could he &ldquo;save&rdquo; his father,  when his own failure to write a self-justifying novel had pushed him to the  brink of suicide four years earlier?&nbsp; <br>
  &nbsp;&nbsp; <br>
            On the  morning of 24th of February Borges received a telephone call from  his mother, who told him that the aneurysm had ruptured and his father would be  dead in a matter of hours. He left the library and made his way across the  city, arriving home in time to see his father pass away. Borges was profoundly  moved by the stoic dignity with which his father met his end, but admiration  was mixed also with a searing anguish, as is evident in a poem he wrote shortly  afterwards, an unpolished composition of thirty-two lines written on ruled  paper taken from an exercise book and clearly dated 1938. Next to the  handwritten text is a rough drawing of a large tree, an image of strength and  endurance which relates to the opening image of the poem:&nbsp; </p>
            <p>&ldquo;We  have seen you die on your feet,<br>
              bearing  fruit like brave men die;<br>
              we have  seen you die with the steadfast<br>
              spirit  of your father amidst the bullets ...&rdquo;</p>
            <p>Georgie  praised his father's courage in meeting his death by likening it to the heroic  death in battle of their ancestor, Colonel Borges. And yet, despite his brave  spirit, Dr. Borges died wishing that his son might somehow bring to fruition  the literary destiny that had eluded him. The grieving Georgie ended his  valedictory poem with a desperate <em>cri de  coeur</em>: </p>
            <p>&ldquo;Papa,  don't leave me, take me with you wherever it is that you are going!&rdquo;&nbsp;&nbsp; </p>
            <p>Borges's  poem posited a connection between himself, his father, and the spirit of the  latter's own father. As a boy, he had already adumbrated such a triangle in his  playlet about the Spanish knight Bernardo del Carpio, where the young hero pays  a ransom to release his captive father only to discover that he has been  tricked by the wicked king, whereupon he avenges his father's murder by killing  the king. However, the self-belief displayed by the adolescent Borges had quite  evaporated in the grown man &#8212; he now felt himself to be a mere reflection of  his father, since their respective attempts either to live up to the ideal of  the ancestral hero or to rebel against his oppressive memory had ended equally  in failure, and both father and son were mired in a paralysing condition of &ldquo;unreality&rdquo;  as a result.&nbsp; </p>
            <p>The  triangular relationship bonding father, son and the spirit of their ancestor,  exerted a horrible fascination. Borges saw an emblem of this triad in the  Christian notion of the Trinity. In his essay, &ldquo;A History of Eternity&rdquo;, he  described the Trinity as a monstrosity that &ldquo;only the horror of a nightmare  could have engendered&rdquo;; it was more terrifying even than the idea of Hell, for  &ldquo;Hell is mere physical violence, but the three inextricable Persons imply an  intellectual horror, an infinity which is suffocating, specious, as of contrary  mirrors&rdquo;. </p>
            <p>At the  time of his father's final illness, Borges was engaged in translating a  selection of Kafka's stories for the Editorial Losada, and it was Kafka who would provide him with the means of exploring  further the ambivalent relations with his father and the ghost of their  ancestral hero. In the prologue to his translations of Kafka, he would observe  that the Czech writer had been secretly &ldquo;despised&rdquo; and &ldquo;tyrannized&rdquo; by his own  father, and that Kafka himself had declared that his entire work was derived &ldquo;from  that conflict and from his tenacious meditations on the mysterious favours and  unlimited exigencies of patriarchal power&rdquo;. Two &ldquo;obsessions&rdquo; governed Kafka's  fiction &#8212; &ldquo;subordination&rdquo; and &ldquo;the infinite&rdquo;, which is why none of the three  novels he wrote was complete, for &ldquo;the pathos of these &lsquo;inconclusive&rsquo; novels  stems precisely from the infinite number of obstacles that detain his identical  heroes over and over again&rdquo;. </p>
            <p>Borges  must have had in mind the &ldquo;pathos&rdquo; of his own &ldquo;inconclusive&rdquo; novels &#8212; the two  attempts at the autobiographical <em>The Approach to Al-Mu'tasim</em>, or <em>April March</em>,  his equally &ldquo;inconclusive&rdquo; effort to render infinite time in narrative form.  Thanks to Kafka he attributed this failure to a mysterious inhibition deriving  from patriarchal power. In May, just a couple of months after his father's  death, he published a translation of&nbsp;  &ldquo;Before the Law&rdquo;, Kafka's brief tale about a man who is prevented by an  invisible obstacle from walking through an open door. Kafka's protagonist asks  to be admitted to the law but is refused entry by the doorkeeper who warns him that  there are other halls inside with other doorkeepers who are even more powerful  than he. The man waits for many years to receive permission to enter, and  finally, when he is on the point of dying, he asks the doorkeeper why no-one  else has asked to enter the law, only to be informed that this entrance was  reserved for him alone and now that he is about to die, it will be closed. In  the curious inability of Kafka's character to defy the doorkeeper's prohibition  Borges must have recognized an identical inhibition in himself &#8212; and in his  father too, no doubt &#8212; based on a fear of defying authority. <br>
  &nbsp;&nbsp; <br>
              The  period of his father's illness and death would constitute a decisive  turning-point in Borges's career as a writer. From the beginning, he had  conceived of writing as a means of expressing his true self, and, ultimately,  of transcending the self in a rapturous fusion with the essential reality of  the world. Even after losing his poetic voice in 1929, he had experimented with  fiction in order to define his unique artistic personality by transmuting his  unhappiness in love into aesthetic form. But his repeated failure to rebel  against the patriarchal sword of honour, and so dissolve the perverse, familial  trinity in which he was trapped, had caused him, time and again, to lose the  love of a woman. And without a woman's love, he believed, there could be no  hope of finding salvation by writing. In the aftermath of his father's death,  therefore, Borges would abandon his quest for the essence of the self and would  turn to writing as a means of exploring the nature of that abject failure.<br>
  &nbsp;&nbsp; <br>
            Father's  dying request that Borges rewrite <em>El Caudillo</em> epitomized the sheer impossibility of being saved by writing, for  such an enterprise would entail the sacrifice of his own creative identity to  his father's, while undermining his father's claim to be the novel's unique  author, which would defeat the point of having written it in the first place.  Re-writing, in short, entailed the destruction of true authorship, of originality,  of invention. By the middle of 1938, I reckon, Borges's reflections on the  implications of re-writing another man's work had led him to the rudiments of a  new story in which he would stand on its head the idea he had cherished for so  long, and portray its opposite &#8212; damnation by writing, or the death of the  author. </p>
            <p>We find  elements of the new story that was taking shape in Borges's imagination in his  review of Paul Val&eacute;ry's <em>Introduction &agrave;  la po&eacute;tique</em>, which appeared in <em>El Hogar</em> on 10 June 1938, only two weeks after his translation of Kafka's  &ldquo;Before the Law&rdquo; was published in the same magazine. Val&eacute;ry argued that the  history of literature was not to be found in an account of the life and works  of individual authors but in a transcendent &ldquo;History of the Mind&#8221; <em>(&#8220;Esprit&#8221;)</em>, which was both producer and  consumer of literature. And literary creation he regarded as the combination of  the potentialities of a particular language according to forms established for  all time. However, Borges found a contradiction between this view and a later  assertion by Val&eacute;ry that works of art only existed in the act of being  perceived by a reader or spectator, for the first assertion implied a large but  finite number of possible works, while the second &ldquo;admits that time and its  incomprehensions and distractions collaborate with the dead poet&rdquo;. The same  text, according to Borges, could mean different things to different readers in  different periods, and he quoted a line from a poem by Cervantes to show that a  reader in the twentieth century would derive a different sense from the very  same words: &ldquo;Time &#8212; a friend to Cervantes &#8212; has corrected the proofs for  him&rdquo;.&nbsp; </p>
            <p>Over  the following months Borges would work up the idea of time as a &ldquo;corrector of  proofs&rdquo; into a story he would call &ldquo;Pierre Menard, Author of <em>Don Quixote</em>&rdquo;, a  spoof review of the works of a fictional writer from N&icirc;mes, recently deceased.  In the character of Pierre Menard we have a Paul Val&eacute;ry who has woken up one  morning to find himself transformed into Franz Kafka, for the nihilism of  Menard was so absurdly perverse that it led him to &ldquo;anticipate the vanity that  awaits all human effort&rdquo; by undertaking &ldquo;an enterprise that was extremely complex  and futile from the start&rdquo; &#8212; he would rewrite Cervantes's <em>Don Quixote</em>. It was not a matter of  copying the novel but of &#8220;repeating&#8221; the book, that is to say, writing his own  text independently of Cervantes but with the aim of making it coincide &ldquo;line by  line and word for word&rdquo; with the original. &ldquo;Pierre Menard, Author of <em>Don  Quixote</em>&rdquo; thus presents us with an exact inversion of Borges's ideal of writing,  for this is a kind of writing that results in the complete annihilation of  personality. Had Menard succeeded in rewriting <em>Don Quixote</em>, he would have sacrificed his artistic individuality  to the task but, equally, he would have robbed Cervantes of his status as the  unique author of the great classic. Menard's success would thus have amounted  to the destruction of original invention, rendering authorship an arbitrary concept  &#8212; one author would be equivalent to any other &#8212; so that over a sufficiently  long period of time, any work could, in principle, be written by any author. </p>
            <p>In  addition to this death, so to speak, of the author, Borges elaborated the  related idea of time as the &ldquo;corrector of proofs&rdquo; which he had briefly  mentioned in his review of Val&eacute;ry's book. If time changed the meaning of texts  so that every reader derived a different meaning from the same set of words,  then a reader, in a sense, could be said to invent the meaning of any given  text. Accordingly, we learn that Pierre Menard had &ldquo;enriched&rdquo; the art of  reading by opening up the possibility of attributing a given text to any author  the reader might fancy, thereby filling &ldquo;with adventure the most placid of  books&rdquo;: &ldquo;To attribute <em>The Imitation of  Christ</em> to Louis-Ferdinand C&eacute;line or James Joyce, would this not be a  sufficient renovation of those mild spiritual counsels?&rdquo;</p>
            <p>A bitter,  self-mocking irony pervades &ldquo;Pierre Menard&rdquo;, for in this story Borges had drained  the act of writing of any vital purpose whatever.&nbsp; Menard's enterprise, in effect,&nbsp; converted the reader into an author, and the  author, in turn, into a glorified reader for whom writing had no connection  with individual experience or feeling, and indeed was no more original than the  work of a scribe &ldquo;repeating&rdquo; a pre-existing text. Moreover, as Borges realized,  such a conception of writing and reading led to the dissolution of objective  meaning. He cited as an example of Pierre Menard's &ldquo;enrichment&rdquo; of reading <em>Don Quixote,</em> Part I, chapter 9, in which history is called  the &ldquo;mother of truth&rdquo;, as an example of Pierre Menard's “enrichment” of reading. What was conventional rhetoric for a Baroque writer like  Cervantes becomes an &ldquo;amazing&rdquo; idea in a twentieth-century Frenchman &#8212; as  &ldquo;the mother of truth&rdquo;, history is regarded by Menard not &ldquo;as an investigation  of reality but as its origin&rdquo;: &ldquo;Historical truth, for him, is not what  happened; it is what we judge to have happened&rdquo;. And so, one might infer that  we invent the truths of history, we invent reality, in the way that readers  invent meanings for literary texts, with the result that reading, no less than  writing, becomes an exercise in solipsism.</p>
            <p>By one  of those strange ironies that seemed to manifest themselves periodically in  Borges's life, these reflections on the death of the author were interrupted by  a sudden brush with the reality of his own physical death in a strange accident  that occurred on Christmas Eve, 1938. Borges had gone to fetch a girl at her  apartment on Calle Ayacucho, some  five blocks from where he lived at Avenida  Pueyrred&oacute;n, in order to accompany her home for dinner with his mother. The  lift was out of order, so he decided to run up the stairs, but in the poor  light he knocked his head against a newly-painted casement window which had  been left open to dry.&nbsp; Despite receiving  first aid, the wound became poisoned, and for a week he lay in bed with a high  fever and suffering from insomnia and hallucinations. One evening he lost his  power of speech and had to be rushed to hospital for an emergency operation in  the middle of the night. He had developed septicaemia, and for a month he  hovered between life and death. When he recovered, he feared he might have been  left mentally impaired and might never write again. He decided to write  something he had never done before so that he would not feel so bad if he failed,  and this led him to write &ldquo;Pierre Menard, Author of <em>Don Quixote</em>&rdquo; while he was  convalescing from his illness in the summer months between January and April  1939. </p>
            <p>&ldquo;Pierre  Menard&rdquo; came out in <em>Sur</em> in May, and although it won plaudits from his friends,  this was not sufficient to dispel Borges's sense of failure.&nbsp; He was still oppressed by the concerns which  had preceded his accident on Christmas Eve, concerns which could only have been  aggravated when in July 1939 he lost his job as the editor of the fortnightly  books page for <em>El Hogar</em>.&nbsp; He had nothing left but his dreary post at  the Miguel Can&eacute; Library, and his  depression can be gauged from an essay, which he published in August, called &ldquo;The  Total Library&rdquo;, where he imagined the entire universe in the form of a library.</p>
            <p>&ldquo;The  Total Library&rdquo; was based on the idea that, given a sufficiently extensive  period of time, a limited number of letters or symbols would generate a finite  number of combinations and, consequently, of books. This library, therefore,  would contain all the books that could conceivably be written and would  describe everything that existed or could possibly exist in the universe. In  such a library all writers would be reduced to the condition of Pierre Menard,  for, as Lewis Carroll observed, they could only ask themselves not &ldquo;what book  shall I write?&rdquo; but &ldquo;which book shall I write?&rdquo; Dreadful as this idea was for  Borges, he went further still, imagining another kind of &ldquo;total library&rdquo;  immersed in the appalling immensity of infinite time, where for every  &ldquo;intelligible line&rdquo; of text there would be &ldquo;millions of senseless cacophonies,  verbal farragoes and incoherencies&rdquo;, where it was conceivable that &ldquo;the  generations of man might pass away altogether&rdquo; without the shelves of the  monstrous library yielding up &ldquo;a single tolerable page&rdquo;.&nbsp;&nbsp; </p>
            <p>The  nightmare of the Total Library put him in mind of a kindred nightmare, the  Trinity, and both nightmares he associated with the idea of Hell: </p>
            <p>&ldquo;One of  the mind's habits is the invention of horrible imaginings. It has invented  Hell, it has invented predestination to Hell, it has imagined the Platonic  ideas, the chimera, the sphinx, the abnormal transfinite numbers (in which the  part is no less copious than the whole), masks, mirrors, operas, the  teratological Trinity: the Father, the Son and the insoluble Ghost, articulated  in a single organism.&rdquo; </p>
            <p>The  Library &#8212; the Platonic form of Father's library in which he had spent his  childhood, or of the Miguel Can&eacute; Library in which he currently worked &#8212; would become the supreme metaphor of  solipsism for Borges, an idealist counter-world, a prison-house of &ldquo;unreality&rdquo;  so pervasive that it was as if the living universe itself had been transformed  into a Hell of endless books: </p>
            <p>&ldquo;I have endeavoured to rescue from oblivion a subaltern horror: the vast, contradictory  Library, whose vertical deserts of books run the unceasing risk of changing  into others, affirming everything, denying everything, and then confounding it  all like some deity gone raving mad.&rdquo; </p>
            <p>It was  in this solipsistic frame of mind that he conceived a new story, &ldquo;Tl&ouml;n, Uqbar,  Orbis Tertius&rdquo;, which would appear in <em>Sur</em> in May 1940. This was a parody of Bishop Berkeley's philosophical idealism, in  which the members of a secret society run by a millionaire called Ezra Buckley  invent an imaginary planet called Tl&ouml;n whose inhabitants lack any natural sense  of there being a physical reality external to their own consciousness. In a  series of brilliant comic manoeuvres, Borges sketched the consequences of such  congenital idealism for the languages, science, mathematics, literature and  religions of Tl&ouml;n. </p>
            <p>There  are, however, a number of autobiographical allusions lurking in the farther  reaches of the tale, among them the figure of Herbert Ashe, the taciturn  English engineer afflicted by &ldquo;unreality&rdquo;, who is said to have established with  Borges's father &ldquo;one of those English friendships which begin by excluding any  confidences and very soon omit conversation altogether&rdquo;, and who died of a  ruptured aneurysm like Borges <em>p&egrave;re</em> himself. The younger Borges recalls a conversation about Brazil he once  had with Ashe in which they spoke of &ldquo;cattle-ranching, of <em>capangas</em>, of the Brazilian etymology of the word <em>gaucho</em>&rdquo;. Herbert Ashe thus obliquely  connects father and son in a triadic relationship loosely associated with a  trip to the borderlands of Uruguay  and Brazil  that Borges made shortly after his suicide attempt in 1934. Finally, a touch of  paranoia creeps into the fable when Borges describes two incidents from his own  experience which suggest that Ezra Buckley and his conspirators may be  attempting to contaminate our world with the sinister idealism of the planet  Tl&ouml;n. The story, then, evinces Borges's fears of becoming as disengaged from  the world as the stricken Dr. Borges, a reflection of the father in the son  personified in the mysterious figure of the ghostly Ashe, and a condition from  which writing itself could no longer offer any salvation.</p>
            <p>&nbsp;</p>
            <p><strong><em>Afterword. August, 2008</em></strong></p>
            <p>The de-contextualization of Borges&rsquo;s work has obscured, if  not erased, a number of fundamental preoccupations that drove him to write, and  to persist in his writing, despite extremely adverse circumstances at times.  Borges himself contributed to this de-contextualization, not least through his  habit of appending additional texts to successive editions of his books, texts  which had often been written years before, or indeed after, those books had  first been published. &ldquo;Pierre Menard, Author of <em>Don Quixote</em>&rdquo;, for instance, now  forms part of <em>Fictions</em>, a book which has achieved canonical status in  Borges&rsquo;s <em>oeuvre</em>, but this collection came about in a manner that owed more to  the particular circumstances in which Borges&rsquo;s radically new fiction was received  in Buenos Aires at the time, than to any considered design of the author&rsquo;s. </p>
            <p>After its first appearance in <em>Sur</em> in May 1939, &ldquo;Pierre  Menard&rdquo; was published, along with &ldquo;Tl&ouml;n, Uqbar, Orbis Tertius&rdquo;, &ldquo;The Library of  Babel&rdquo; (a re-elaboration of &ldquo;The Total Library&rdquo;) and five other &ldquo;ficciones&rdquo; in  December 1941, in  a collection called <em>The Garden of Forking Paths</em>.&nbsp; Reviewing this collection in <em>Sur</em>, Bioy Casares claimed that  Borges had invented a new genre of fiction by discovering &ldquo;the literary  possibilities of metaphysics&rdquo; and combining these with the pursuit of the  &ldquo;ideal&rdquo; qualities inherent in detective stories, namely, &ldquo;inventiveness&rdquo;,  &ldquo;rigour&rdquo; and &ldquo;elegance&rdquo; in the structuring of a narrative. The book was entered for a &ldquo;National  Prize for Literature&rdquo; but failed to win an award. According to one of the  judges, it had been thought inappropriate to recommend  to the Argentine people &ldquo;an exotic and decadent work&rdquo; which followed &ldquo;certain  deviant tendencies of contemporary English literature&rdquo;, hovering as it did &ldquo;between  the tale of fantasy, a pretentious and recondite erudition, and detective  fiction&rdquo;; Borges&rsquo;s work  amounted to a &ldquo;dehumanized literature&rdquo;, &ldquo;an obscure and arbitrary cerebral  game&rdquo;.</p>
            <p>Borges&rsquo;s failure to win a &ldquo;National  Prize for Literature&rdquo; for <em>The Garden of Forking Paths</em> caused dismay, even outrage, among his friends, and two years later,  when he was preparing six new stories for publication under the title <em>Artificios</em>, his friend Enrique Amorim came  up with the idea of making amends to Borges by having &ldquo;The Society of Argentine  Writers&rdquo; create a prize of its own and award it to this new collection. Borges  seems to have been quite happy to go along with this manoeuvre, and it may well  have been Amorim&rsquo;s proposal that influenced his decision to re-issue <em>The Garden of Forking Paths</em>,  the object of the earlier controversy, under the same cover as <em>Artificios</em>. This double collection  was then called <em>Fictions</em> and,  when the book came out on 4 December 1944, it still bore the evidence of its  dual provenance by being divided into two sections, each with its own prologue  and title, <em>The Garden of Forking Paths</em>  and <em>Artificios</em>, respectively, a division that has been retained in all  subsequent editions. What&rsquo;s more, it was not until the second edition of <em>Fictions</em>  in 1956 that the collection would reach its present form, with the addition of  three new stories written in the early 1950s. Thus, the canonical edition of <em>Fictions</em>,  far from representing a well-defined period of Borges&rsquo;s writing, is a somewhat  haphazard accumulation of texts written between 1935 and 1953.</p>
            <p>The award of the &ldquo;Gran Premio  de Honor&rdquo;, which had been specially created by &ldquo;The Society of Argentine Writers&rsquo;&rdquo; for the 1944 edition of <em>Fictions</em>, was made at a dinner in July 1945,  and in his speech of thanks, Borges was to reveal something of the raw  suffering from which his &ldquo;ficciones&rdquo; had been distilled. Having been criticized  for the &ldquo;dehumanized&rdquo; quality of his work when he was denied a National Prize  in 1941, he spoke of the twenty years of &ldquo;obscurity&rdquo; which had preceded the  receipt of the present award. He had been &ldquo;nourished on dangerous poisons&rdquo;: he  had fed on &ldquo;darkness, bitterness, frustration, interminable useless evenings,  and neglect&rdquo;, but he rejoiced that the prize should have been given to a work  of fantasy because the literature of fantasy, far from being a&ldquo;marginal genre&rdquo;,  was in fact the most ancient of all: &ldquo;Dreams, symbols and images traverse our  lives; a welter of imaginary  worlds flows unceasingly through the world.&rdquo;&nbsp;  He concluded by observing that his life as a man had been &ldquo;an  unpardonable succession of miserable experiences&rdquo;, but he nevertheless hoped he  might achieve a greater dignity in his life as a writer. </p>
            <p>&nbsp;</p></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
