<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <title>The International Literary Quarterly</title>
  <meta http-equiv="Content-Type"
 content="text/html; charset=UTF-8">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
window.open(theURL,winName,features);
}
//-->
  </script>
  <link href="../../estilos.css" rel="stylesheet" type="text/css">
  </style>
</head>
<body>
<?php include("../../header.php"); ?>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr>
      <td align="right" valign="top" width="10%"><?php include("../../issue12/menu_issue12.php"); ?>
      <div align="right"></div>
      </td>
      <td valign="top" width="90%">
      <table bgcolor="#ffffff" border="0" cellpadding="0"
 cellspacing="0" width="679">
<!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tbody>
          <tr>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="10"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="192"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="17"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="205"></td>
            <td valign="top"><img src="/images/spacer.gif" alt=""
 border="0" height="1" width="239"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="16"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="1"></td>
          </tr>
          <tr>
            <td><img name="home_r1_c1" src="../../images/spacer.gif"
 alt="" border="0" height="59" width="10"></td>
            <td colspan="4"><img src="../../images/spacer.gif" alt=""
 name="home_r1_c2" class="link1" border="0" height="59" width="653"></td>
            <td>&nbsp;</td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="59" width="1"></td>
          </tr>
          <tr>
            <td rowspan="4"><img name="home_r2_c1"
 src="../../images/spacer.gif" alt="Click to enlarge picture"
 title="Click to enlarge picture" border="0" height="391" width="10"></td>
            <td rowspan="2" valign="top"><a href="#"
 onmouseup="MM_openBrWindow('../../issue12/peter-wells/artwork.html','','width=360,height=500')"><img
 src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2"
 border="0" height="242" width="192"></a></td>
            <td rowspan="2"><img name="home_r2_c3"
 src="../../images/home_img/home_r2_c3.gif" alt="" border="0"
 height="242" width="17"></td>
            <td colspan="2" class="titulo2" valign="top">Interview  <span
 class="texto2">of <a href="../../issue12/peter-wells/bio.php"
 class="link3">Peter Wells</a> by <a href="http://interlitq.org/issue10/siobhan_harvey/bio.php"
 class="link3">Siobhan Harvey</a>, from "Words Chosen Carefully: New Zealand Writers in Discussion"</span></td>
            <td>&nbsp;</td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="23" width="1"></td>
          </tr>
          <tr>
            <td colspan="2" class="texto2" height="219" valign="top">
            &nbsp;<br>
            <p align="right">&quot;To me, the greatest pleasure of writing is not what it's about, but the inner music the words make.&quot;<br>
              – Truman Capote</p>
               
              
              <p>This interview initially took place at Siobhan Harvey's home in Glendowie, Auckland, in June 2009. The engagement with landscape Wells enjoys as a writer was evident in his immediate curiosity about the panoramic views of the Tamaki River and Half Moon Bay from Harvey's house, which he declared reminiscent of the 1950s' Point Chevalier of his boyhood.</p>
            </td>
            <td rowspan="3"><img name="home_r3_c6"
 src="../../images/spacer.gif" alt="" border="0" height="368" width="16"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="219" width="1"></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="2" class="texto2" valign="top">
           
               
         &nbsp;<br>
              <p><strong>Siobhan Harvey:</strong> <em>Peter, let's begin with a quote. You once said, 'I like the past. The past fascinates me. If there was a door on a wall and I could walk through it to the past, I would.'
              Let's imagine that there is such a door. You walk through it. Which part of your childhood would you most like to be returned to?</em></p><p>
              <strong>Peter Wells:</strong> Full moon, high tide, Point Chevalier, round about 9pm.</p><p>
              <strong>SH:</strong> <em>Your mother's family, the Northes, were originally from Napier and before that, Cornwall. Growing up, you spent a lot of time in Napier. What's your most resonant memory of the Napier of your childhood?</em></p><p>
              <strong>PW:</strong> Being alone in my grandmother's house. She and my mother are out visiting. The house is quiet. The wallpaper seems to sigh, and I start opening a drawer.</p><p>
              <strong>SH:</strong> <em>Historical Auckland, Point Chevalier and Napier are places you often return to in your writings. Less so Mount Albert, where you attended grammar school, I believe.</em></p><p>
              <strong>PW:</strong> Yes. It's odd you mention that. I was sorting through books housed at my mother's place yesterday. I found a copy of <em>The Albertian</em>, which was the school magazine. I felt this utter gust of sexual longing when I looked at the boys in the sports photos – I could still remember every one of them. The handsome ones, that is. They still appeared ... almost impossibly attractive.</p><p>
              When I was in Australia recently I was talking to William Yang, the photographer. He said high school had been the unhappiest time of his life because he wanted to fit in most and yet couldn't. And he had no control over his own life. So it was utter misery. It was the same for me. I went to an all-boys, military-type, sports-mad school, which I went into loving and came out hating.</p><p>
              William also said that he thought that because gay men couldn't experience a lot of things in an ordinary sequence – socialising, sexual experimentation and that sort of thing – during their teenage years, quite often they were delayed and happened later in life, with a special intensity and velocity. I thought it was a very interesting insight. You could say that was the whole experience of a generation of gay men who came of age at the same time – in the 1970s.</p><p>
              <strong>SH:</strong> <em>And then on to Auckland University. Was that a comfortable environment?</em></p><p>
              <strong>PW:</strong> Yes, but it took time to find friends. I kept my friends from school for a long time. Recently, when I went back to university to teach, I could observe that happening with my students – people being bored with the friendships from school but not feeling capable of taking that great leap into the unknown.</p><p>
              <strong>SH:</strong> <em>What was Auckland University like in the early 1970s?</em></p>
              <p>
              <strong>PW:</strong> Well, I'm writing this memoir at the moment which is about a couple of years – 1972-74 – I spent at Auckland University. 1972 was quite a volatile year in New Zealand. Auckland was at its epicentre. It was an exciting, highly molten moment in which sexuality, race, gender floated free for a few glorious seconds. So for me this period is always something very special – a sense of walking out into thin air – and not falling. Yet it's a period hard to evoke without falling into lame, tired clichés. That's the challenge with my memoir.</p><p>
              <strong>SH:</strong> <em>After 1974, you attended Warwick University. Did you find England and Warwick in particular a contrast to the activism you'd found at Auckland?</em></p><p>
              <strong>PW:</strong> It was very different because I'd come from the tiny, overheated, narcissistic, exciting world of inner city Auckland, where there were a lot of drugs and a certain kind of madness – a beautiful madness, I'd call it. Then I was transported to a regional university on the other side of the world whose intake was quite strongly working class. It was an absolute shock for a long time. It was realist as against lyrical. In a way it was like fast forward detox. Hell. Then I found my feet and moved into establishing that what I really wanted to do in life ... which was writing. Up till that time I hadn't dare articulate it.</p><p>
              <strong>SH:</strong> <em>That was my next question – did you always want to be a writer?</em></p><p>
              <strong>PW:</strong> Yes, I did, but when family friends enquired jocularly, 'What do you want to do?' I could never say I wanted to be a writer because back then I'd have risked sounding absurdly pretentious. In New Zealand at that time there was a very small publishing industry and a handful of well- known writers, like Frank Sargeson, Janet Frame and Maurice Shadbolt. So the feasibility of being a writer seemed impossible.</p><p>
              <strong>SH:</strong> <em>Yet it dawns on you when you get to Warwick that there's some inner need to, if I can use the term, 'come out' as a writer?</em></p>
              <p>
              <strong>PW:</strong> I got a scholarship which allowed me to get out of New Zealand. I did well in my MA exams, and was asked what university in Britain I wanted to go to. So studying history was a sort of camouflage for a ticket out of New Zealand. It wasn't something I deeply wanted to do. Then when I got to Warwick I found myself in a high-pressure postgraduate situation in which I was being pushed into deciding what my specialty was going to be. It was a crisis point. Also I was also dreaming a lot, and I think it happens to all New Zealanders really – you don't realise how much you're imprinted as a New Zealander until you leave your homeland, then that imprinting becomes very vivid. But distance is a great thing. My subconscious was given a chance to untie certain knots which had been so tightly tied in New Zealand that I could never look at them. So I started to untie those knots. Indeed, when I looked through my papers recently, I came across scribblings and early drafts of things which showed that I was trying to write <em>Long Loop Home</em> and <em>boy overboard</em> in the late '70s.</p><p>
              <strong>SH:</strong> <em>The germ of wanting to be a writer must have been fed by prodigious amounts of reading?</em></p><p>
              <strong>PW:</strong> Oh yes, I was obsessive in my reading back then. The whole thing about being unhappy at high school was that I escaped reality by reading. When I look back now, I see that I was bullied – I was meant to have an effeminate voice. So by the time I was in the 5th form I never spoke, ever. I went inwards. So reading and immersing myself in words became hugely important because that was the only way I could survive.</p><p>
              <strong>SH:</strong><em> What were your literary tastes back then?</em></p><p>
              <strong>PW:</strong> Our local library at Point Chevalier, which was a place I used to haunt, held many books I adored. One book they had which I often read and which was a part of all of our childhoods at that time, was a book of the kings and queens of England which was all in rhyme. In the playground it was used as a memory test – if you could run right through all those Stephens, Matildas, Henrys and so forth. It was a form of English colonial whakapapa, the thread that tied you back to a rich, fantastical past.</p><p>
              Another book I loved and obsessed about was <em>The Little House on the Prairie</em> by Laura Ingalls Wilder. I felt that I was the little girl, Laura, in it. Back then, all boys in fiction were closet heterosexuals in training for manliness. I couldn't identify. It's a very confusing thing for a child when you look at the universe and you can't see a single pattern like your own. So I made my own connections to Laura, who was naughty and willful. Also, there were no narratives of colonial life in New Zealand at that time and because I was very interested in my family's past, I had nothing to relate that curiosity to, except tales about colonial life written by overseas authors like Ingalls Wilder. And as for taking on the role of a girl, Laura – well, there were no boys like me in fiction. You dream a lot and books become very important.</p><p>
              <strong>SH:</strong> <em>Which other books were important to you? </em></p>
              <p><strong>PW:</strong> At high school, I read Katherine Mansfield. D.H. Lawrence I loved
              madly, especially <em>The Rainbow</em> and <em>Women in Love</em>. Fantastic. There was a set, mainly English classics we were introduced to at school. Why I liked D.H. Lawrence, I don't know. His work is very vivid. I liked the river of prose and his awkwardness. He's very, very out of fashion now. But perhaps he also fitted into my life at that time because he was really a closeted man with very strong homosexual feelings. Maybe I identified with this pulse or vibe without being conscious of it.</p><p>
              <strong>SH:</strong> <em>You're a very visual person. When I read your work, I'm struck by the way in which you build precisely detailed architectures into it, architectures of place, space and environment. Why do place and space matter greatly to you?</em></p><p>
              <strong>PW:</strong> I suppose I always fear that I'm lost and want to be found. I like the tactile nature of what I see. To me, what you see is what you are.</p><p>
              <strong>SH:</strong> <em>What you are and where you a</em>re?</p><p>
              <strong>PW:</strong> I think we all, Maori and Pakeha, clue into something subconscious that lies in the land from an early age. In many senses, when I'm writing I'm returning to those memories, those visual imprints I have of location and environment. There's the myth that the childhood of my day was all flax and toi-toi, but New Zealand childhoods are rarely like that. You might have the sea, but you also have tarseal and tin roofs and the power lines. It's a whole suburban architecture which is as powerful as it is oppressive. Having experienced it, I continue to carry it inside me and return to it when I write about any environment.</p><p>
              <strong>SH:</strong> <em>Do you think then that though the focus on landscape isn't exclusive to New Zealand writers, it is in some way heightened in their work?</em></p><p>
              <strong>PW:</strong> It's an interesting question. I don't know whether the attempt to characterise New Zealand writers as focusing upon the land is based on the fact that we're trying to craft a New Zealand identity in our fiction. I can't quite answer that because I'm part of it, I'm afraid.</p><p>
              <strong>SH:</strong> <em>&quot;He was no longer Cary Grant. He was a teller in a bank,&quot; as you say in </em>Long Loop Home<em>.
              Often in your books, film and television are reference points.</em></p>
              <p>
              <strong>PW:</strong> Cinema remains such an important marker in New Zealand. I think this is because we all grew up with the movies. Our geographical isolation during the '40s and '50s also played a part. Hollywood movies presented powerful foreign worlds to us. We were so unsophisticated back then that we actually thought that overseas was Cary Grant. You got out of the airport and the world was all highly coloured and compressed and highly dramatic.</p>
              <p>
              <strong>SH:</strong> <em>You once said, &quot;I don't like looking back at my work.&quot; It's an intriguing statement, because it seems to me that what you as a writer and what your work so often does are to look back. The past is one of your widest inspirations. There's a dichotomy there, isn't there?</em></p><p>
              <strong>PW:</strong> Yes, probably. It kind of worries me now that I'm writing another memoir – I should sit down and quickly re-read <em>Long Loop Home</em> just to make sure that I'm not duplicating things because of course you do go over the same events repeatedly in your own mind. To me the dichotomy lies elsewhere. It's about the divergence between what I feel is true about my history versus the evidence of the times, as written in newspaper reports and official documents. To me, the '70s seem like the most marvellous time in my life, a wild opening up, if you like, after my long, claustral childhood. So part of the memoir is about questioning whether the 1970s were really like that. When I came to write the first draft of this new memoir, I sat down and wrote it in about a month which worried me enormously, but then the fact is I'd been thinking about it for decades. Now I'm going back to look at documents from the period, to question my own sometimes rhapsodic view of events.</p><p>
              <strong>SH:</strong> <em>Which reminds me of your discussion about crafting </em>Long Loop Home<em> which happened in an equally swift manner, if I recall. Did you look at that book with the same sort of scrutiny you're applying to your new memoir?</em></p><p>
              <strong>PW:</strong> With <em>Long Loop Home</em> I believe I relied more upon what I remembered, rather than my current preoccupation with memory versus evidential fact. Apart, that is, from the murder in <em>Long Loop Home</em>, which I did go back and look at in great evidential detail. I think I did that partly because it affected people outside the family.</p><p>
              <strong>SH:</strong> <em>I suppose what you're doing is charting that fraught territory that is memoir, between your perception of events and objectivity. It's what the writer of memoir inevitably comes up against.</em></p><p>
              <strong>PW:</strong> Yes. With the new memoir for instance, because it's about my contemporaries rather than solely about me and my family, I have a greater
              sense of trepidation and fear about what I'm writing because the subject matter concerns a wider group of people. Also the '70s were a wonderfully messy period so it's potentially much more libelous.</p><p>
              <strong>SH:</strong> <em>You're one of those writers who's always uncompromisingly discussed themselves. Is this a reflection of your personality or of your belief that it's the duty of the writer to be truthful to their craft?</em></p><p>
              <strong>PW:</strong> I think my interest in writing about the self started with a diary I kept as a young boy. It was a couple of inches thick with a plastic, gilt- edged cover, and was given away free by the whisky company, Dewars. I remember quite awkwardly forming words on the pages of the diary. That started me off on my lifelong diary-keeping in which I recreated parts of myself on the page. They haven't necessarily been real parts of my self. Sometimes, they've been whatever self I needed to detail on paper to survive. But throughout it's seemed an extraordinarily natural way for me to communicate.</p><p>
              <strong>SH:</strong> <em>Uncompromisingly discussing your self and your viewpoints on paper has also made you a political writer, of course. What dangers have prevailed for you and your family in writing about the self in this way?</em></p><p>
              <strong>PW:</strong> Well, I suppose I've done it with a false consciousness that my family, my mother particularly, wouldn't read what I've written. Whereas if I'd felt that my mother, my family or even my extended family were sitting on my shoulder reading what I've written I wouldn't be able to do it; yet, having said that, they all seem to have read my work. I was sitting with my mother last night watching the movie, <em>Miss Potter </em>[a film of Beatrix Potter]. The film got to a certain point where the mother regarded Potter's writings as an amateur silliness while the father was very supportive and told her how he was amazed by what she was doing. I realised that I've never had that. Though my mother is capable of saying how proud she is of my work in a larger sense, she's not capable of doing it in a specific sense, because I'm aware that whatever I do continually frightens her, especially the potential of what I write. That is, <em>the way</em> I write frightens her. Because it signals that it doesn't stop with the completion of the last work. It's a way of looking, talking, seeing. In essence it's who I am.</p><p>
              <strong>SH:</strong><em> Is such truth-telling ever offset for you by the need to be a compassionate writer?</em></p>
              <p>
              <strong>PW:</strong> Very much so. With <em>Long Loop Home</em>, I was always conscious of the need to be real about what had happened but I also had to have compassion. After all, I've acted horribly, stupidly, and have harmed people – that's part of being human. So I always try in memoir to have as much empathy as I can. I think when Mum read <em>Long Loop Home</em> – which she feared doing – she felt that there were elements of love and compassion in it. But that's what you have to strive for in writings, a sense of humanity, because writing after all is a profoundly human act. Words are what define us as humans.</p><p>
              <strong>SH:</strong> <em>That's very true, but being human is also defined by what we say. For instance, in striving for truthfulness, don't you inevitably venture into personally uncomfortable areas of your life, such as your sexuality?</em></p><p>
              <strong>PW:</strong> Yes, very much so. As someone who's homosexual, I naturally write about sexuality a lot, because, initially at any rate, it was a riddle handed down to me, a kind of impossible fate, a thing other people noticed about me, before I noticed it myself. So there's a huge amount of material there, material which wasn't especially looked at closely before the advent of 'gay liberation'. There are areas of disjunction, disinformation, humour – it's a potentially rich turf. I don't find writing about it personally uncomfortable, I find it entirely natural.</p><p>
              <strong>SH:</strong> <em>If it's natural to write about, how comfortable are you with the unavoidable authorial label which results, 'the gay writer'?</em></p><p>
              <strong>PW:</strong> I think the descriptor has passed its use-by date. I envy writers like Annamarie Jagose and Stevan Eldred-Grigg because they've found it easier to shed that tag and simply be a writer. It gives people a much bigger area in which to talk about their work, whereas if you're labeled 'a gay writer' you're somehow in a corner, boxing out of it. Having said that, there was a particular era in which it was very important to be out and visible publicly.</p><p>
              <strong>SH:</strong> <em>Of course, there are always gay characters in your fiction. Does your response to the previous question mean that you can envisage a time when you write a piece of work in which there are no gay characters?</em></p><p>
              <strong>PW:</strong> Yes, I could. But I don't see why I should. I see my characters, straight and gay, as peopling the world.</p>
              <p>
              <strong>SH:</strong> Dangerous Desires <em>and</em> The Duration of a Kiss – <em>Chekov said that the short story should be like a shot of vodka. What was it about the short story form which first attracted you to it?</em></p>
              <p>
              <strong>PW:</strong> Looking back now, I thought that was how you started as a writer. Now I've written more books I understand that short stories are an incredibly complex genre. Also I'd loved short stories for a long time: Katherine Mansfield's New Zealand stories, but also the Southern writers from the United States. Eudora Welty whom I love. And I think stories by her really inspired me to write my own.</p><p>
              <strong>SH:</strong> <em>Did you perceive at the time or with hindsight, do you now perceive, a link between the concision of language, the paring down of image, and concentrated authorial direction of the story, and the shared territory of this with your life back then as a short-film maker?</em></p><p>
              <strong>PW:</strong> Yes, I like small. I like small things. I love the detail of detail. But these days I feel far more at home in writing novellas. I find writing short stories really difficult to write now.</p><p>
              <strong>SH:</strong> <em>Difficult?</em></p><p>
              <strong>PW:</strong> These days, I think their concision taxes me. I don't think 'short story' so much. Also, apart from the stories which appear in The New Yorker which I read assiduously and find each issue stunning, I don't read a lot of short stories now. And I think you have to read to write. You get inspired. You want to try it out.</p><p>
              <strong>SH:</strong> <em>So why the comfort felt in the novella form?</em></p><p>
              <strong>PW:</strong> It's such a strange form, of course. Quite loose. But it has a slight shagginess and a larger parameter than the short story which appeals to me. Funnily enough I do think that the novella is a distinctly New Zealand form. <em>At the Bay</em> and <em>Prelude</em> for instance, seem to me the high points of Katherine Mansfield's art form. <em>That Summer</em> by Frank Sargeson equally so. Janet Frame's early novels were very much novella-like. The novella is a long lyric.</p><p>
              <strong>SH:</strong> Dangerous Desires – <em>did the thematic sense of it come to you from the outset of writing the collection, or did you have a few constituent parts and then the collection evolved thematically afterwards?</em></p>
              <p>
              <strong>PW:</strong> That collection is so closely related to the death of my brother Russell, and the mood I was in afterwards, a strangely expansive and explosive mood rather than a traditional mourning mood. I started writing it one day when I was up in Auckland University library doing research on the film, <em>The Mighty Civic</em>. I had a completely lateral moment and wrote the story, 'Outing', instead. Suddenly something clicked into place, something which all my adult life I'd wanted and had never been able to find, until then. I think once you find that as a writer, your voice, you can't go wrong.</p><p>
              <strong>SH:</strong><em> Once 'Outing' was written, did the rest of the collection fall into place?</em></p><p>
              <strong>PW:</strong> Yes, it seemed to. I felt a sense of sudden confidence. As a writer I felt a unified sense of being. I was also helped by my agent at the time, Michael Gifkins. He was really quite wise in suggesting the characters in 'Outing' could be threaded through the collection. But that book is sustained by a single mood, I think. It relates closely to the sense of freedom I felt when my brother died, whereas before I'd always been a deeply conflicted, uncertain person trying to navigate through an unnamed territory.</p><p>
              <strong>SH:</strong> <em>As a title, </em>Dangerous Desires<em> is suited to your whole work, which it seems to me explores the dangers of desire.</em></p><p>
              <strong>PW:</strong> And the excitements of desire hopefully. The success of the collection frightened me actually. And, when writing my next book, <em>The Duration of a Kiss</em>, I set out to try and lose a whole readership. Deliberately attempting to lose your readership still seems like a perverse thing to do as a writer, though perhaps a lot of authors do this subconsciously [laughs].</p><p>
              <strong>SH:</strong> <em>Did </em>The Duration of a Kiss<em> successfully lose you that readership?</em></p><p>
              <strong>PW:</strong> I think <em>The Duration of a Kiss</em> was more homosexual, and I think that freaked some readers out. I remember a friend commenting at the time <em>Long Loop Home</em> came out that she'd gone round to people urging them to read the book and the response had often been, oh no, he's become too homosexual for me. That's a product of what I thought I was doing with the readership of <em>The Duration of a Kiss</em>.</p><p>
              <strong>SH:</strong> <em>Your stories are very character-focused. Were characters the entry point for you when crafting the stories in your first two collections?</em></p>
              <p>
              <strong>PW:</strong> When I was crafting <em>Dangerous Desires</em> and <em>The Duration of a Kiss</em>, often the starting point to a story was a sentence, something which niggled away at me with its wild imperative to tell the whole tale. The characters follow from that first sentence. Like all writers, of course, I find human behaviour astounding and bizarre. I write letters to two special friends, both writers, and if I've had a good day out socially I enjoy constructing wildly malicious character assassinations of a slightly comic sort. Of course I'm tragic – I love Dickens.</p><p>
              <strong>SH:</strong> <em>Your next book was the novel, </em>boy overboard<em>. Did you find it hard to make the literary shift from the short story to the novel?</em></p><p>
              <strong>PW:</strong> I found it tremendously difficult. Once I got hold of the idea of what a novel is, I felt quite at home within its expansive world. That doesn't mean that I still don't find it hard to write novels, I do. But to start with I didn't understand structure and the subject matter meant it was difficult psychologically for me to craft the longer piece of fiction. With hindsight, for a first novel, I probably should have avoided the literary territory of that novel because it's such a difficult subject to pull off. But at the time I clearly thought that this is what I needed to write about. I must say, I was very lucky to have the encouragement and support of my editor, Harriet Allen, throughout.</p><p>
              <strong>SH:</strong> <em>In terms of the subject matter of </em>boy overboard<em>, class plays a significant role. You're a writer who is very conscious of class in their work, but in boy overboard class is central, crucial. Why?</em></p><p>
              <strong>PW:</strong> Issues of class have been a constant in my life, and so I guess that it's natural for me to reflect them in my work. I come from an ambiguous class background, an ambitious lower middle-class family who is upwardly mobilised. So subconsciously I was aware of that transition and the inherent possibility of falling downwards in the social scale while my family always retained the aspiration to keep moving upwards. I also think that the whole thing of upward mobility is a huge gravitational thing in New Zealand culture which people just refuse to talk about. The belief that class doesn't exist in New Zealand is nonsense.</p><p>
              <strong>SH:</strong> <em>It's become clichéd perhaps, but there's a prevalent idea that first novels borrow heavily from the writer's personal experience. Is that true of boy overboard?</em></p>
              <p>
              <strong>PW:</strong> Interestingly enough, in the writing of <em>boy overboard</em> it never occurred to me that I was fictionalising aspects of my own experience. I thought I was describing an objective reality, a map of common existence which had always existed. Looking back, though, I think one of the problems I had with writing the novel was that I was drawing so deeply on subconscious and subjective areas of my life which deeply disturbed me. I mean Jamie, the central character, acts out a sexual trauma without any self- consciousness. I suppose, if I can look back now, I was trying to supply the consciousness in writing the novel, and that was why it was so personally taxing, exhausting, nightmarish, like walking in a perpetual fog but knowing you just had to keep walking for survival's sake. Yet it was also a novel which I had to write for my sanity. I had to somehow transcribe that consciousness, which was immensely challenging personally, but also, I have to say, on the level of craft.</p><p>
              <strong>SH:</strong><em> And in terms of trying to articulate the difficult mindset of boy overboard's protagonist, Jamie, someone who's on the cusp between childhood and adulthood, was it an extensive task?</em></p><p>
              <strong>PW:</strong> I discovered Jamie's strangely clotted, slightly trashy, hyper-poetic voice when writing the novella 'One of Them!' in <em>Dangerous Desires</em>. It's a tale about Jamie at a slightly later age in life. He's still one fucked-up kid but he's got another fucked-up kid, and not his brother, to play around with. Back then, it seemed like a good voice. One of the problems with <em>boy overboard</em> was extending that voice out from a novella into the novel. I hadn't quite understood how difficult that would be.</p><p>
              <strong>SH:</strong> boy overboard<em> is the most linguistically experimental of your books.</em></p><p>
              <strong>PW:</strong> Yes, I enjoyed writing that aspect of the book though I imagine it proved difficult for readers. It's not a traditional postmodern narrative style but I feel it suited a kind of character such as Jamie, someone who is inarticulate, who hasn't learned to talk in conventional ways. At Jamie's age everything is primary, painted and vivid. That's what childhood is, a vivid reality, an over-reality. Jamie's voice also reveals my influences at that time – Patrick McCabe, Janet Frame and William Faulkner. I thought Faulkner particularly wonderful, though recently I went back to <em>The Sound and the Fury</em>, a book which changed my life, and I thought, 'Oh, my God, I just can't read this. The language is too much.'</p><p>
              <strong>SH:</strong><em> Early on in the novel, Jamie says, &quot;I don't trust words here&quot;. Trust, self-reliance and deceit. How significant were these as themes for the novel when you were writing it?</em></p>
              <p>
              <strong>PW:</strong> Very, because I was trying to make a personal language in contrast to an official, structured language. So it was part of trying to craft a character like Jamie who doesn't fit in with the official New Zealand world at that time. Back then, Jamie's statement also reflected something of me as a writer. I was an author who was in love with words but uncertain about the imperative of the sentence. Now I feel different as a writer. I trust words implicitly.</p><p>
              <strong>SH:</strong><em> I imagine one of the difficulties with the novel was the way in which it straddles the gender divide. Although its world is that of a boy caught between childhood and manhood, it's also a narrative which actively embraces sides of life which have cultural and literary ascriptions as feminine. Jamie's nature is very sentient, emotional and bitchy, for instance. Was this gendered subject matter consciously layered into the book?</em></p><p>
              <strong>PW:</strong> I can't say whether it was conscious or subconscious, but it's the real landscape of the book. As real as creeks and reefs and roads and school.</p><p>
              <strong>SH:</strong> Long Loop Home<em> has become a seminal memoir in the New Zealand literary canon. It's a memoir about objectivity. Can you be objective and see why that book struck a chord with, and continues to strike a chord with, readers?</em></p><p>
              <strong>PW:</strong> Yes, I can. In <em>Long Loop Home</em> I was trying to delineate something which preoccupies much of my work and that's the particularity of Pakeha experience. From the '80s onwards, the push towards the creation of a bi-cultural or multicultural society has been so strong that the world in which I grew up, which was a Pakeha-dominated world – has essentially sunk, like a stone, to the bottom of the tide. I think evoking that provoked a lot of responses in readers because many of us grew up with that kind of past. I also think the territory of family, of fraught interaction with one's relatives, is also a world readers recognised. I think the level of emotional debate contained something which is alarming and daring yet doing that in public meant that people felt empathy with the work.</p>
              <p>
              <strong>SH:</strong> <em>&quot;This is a story – one written, moreover, by a writer of fiction – and a writer of fiction is only a born liar who has found some use for his talents&quot;, from the Prologue, </em>Long Loop Home<em>. Did being a fiction writer, a born liar who has found some use for his talents, make the writing of </em>Long Loop Home<em> easier or harder?</em></p>
              <p>
              <strong>PW:</strong> I think the question is broader. There's this stupid notion that fiction is somehow better than writing non-fiction, that writing a novel is somehow much more difficult and dangerous, and writing non-fiction is somehow easier and less valued. I think we live in a world in which that dichotomy is rapidly reversing. This said, writing fiction had prepared me well for writing my first memoir in that it up-skilled me. It's taught me pace, structure, to feel very capable when crafting a sentence and, probably most importantly of all, to trust myself. Trust is one of the hardest things for a writer to learn.</p>
              <p>
              <strong>SH:</strong> <em>In </em>My Lives: An Autobiography<em>, Edmund White said, &quot;At every moment, I convinced myself that I was gathering material for the novel of my life – all experienced from the philosophical distance of the author... Life was a field-trip.&quot; When you wrote </em>Long Loop Home<em>, was there a difficulty in deciding what to include and what to discard?</em></p>
              <p>
              <strong>PW:</strong> I got into the rhythm of that book very quickly. Each time I started a new piece, something would come up in my mind which was a riddle. It was like when you run your hand over a piece of fabric and find a crease. I ran my hand back over that crease and thought, 'Why does that crease echo in my mind so much?' Sometimes it was something tiny, but just by looking at it, it opened up a broader landscape and exposed the reason why something seemingly unimportant is remembered. The thing is that as a young man I thought I had no memory of my childhood. I thought my past was sealed like an urn which I couldn't access and filch. But when I acknowledged my gayness, in a sense I became another character. I assumed another identity and part of doing so was to reject things which didn't fit within my 'new' personality. Writing the memoir was a healing process that enabled me to glue parts of my past together again and allowed me to remember things which before I'd chosen to reject.</p><p>
              <strong>SH:</strong> <em>Another quote for you by Edmund White. &quot;The most important things in our intimate lives can't be discussed with strangers except in books.&quot; Do you agree?</em></p><p>
              <strong>PW:</strong> Yes, I do. When <em>Long Loop Home</em> was broadcast on the radio, I found it un-listener-able. It wasn't the strangeness of hearing someone read out work that belonged to and was written by me. Rather the public nature of the work seemed unbearable. I felt also – have always felt – that the nature of reading is a contract, one in which, while the reader reads about your life they're also thinking about their own past and existence – so it's a private relationship to do with silence, the whiteness of the page, meditation and so forth. Whereas to have such private things read out in public made me feel extremely uncomfortable because it opened the work
              up to anyone who was casually listening to the radio at the time.</p><p>
              <strong>SH:</strong> <em>The keeping of secrets and the reason for the keeping are important motifs in the memoir. What does </em>Long Loop Home<em> say to us about the human need to keep secrets?</em></p><p>
              <strong>PW:</strong> As a writer, my work is motivated a lot by the nature of secrets. <em>Iridescence</em> and <em>Lucky Bastard</em>, for instance, both turn upon secrets kept privately which are revealed publicly. In terms of <em>Long Loop Home</em>, it's about the need to keep secrets in order to survive and the long-term damage wrought upon the keeper and those close to them by that keeping. Interestingly enough, as time goes by, the secrets which are extremely powerful to us end up having nothing more than a curiosity value for others. That's the tragedy.</p><p>
              <strong>SH:</strong> <em>The tragedy of keeping secrets, yes I can see that, and yet equally it feels like there was a liberation, a catharsis to your writing of </em>Long Loop Home<em>.</em></p><p>
              <strong>PW:</strong> Absolutely. I slept better after that book. Certain things which tormented me in nightmare form, night after night, vanished.</p>
              <p>
              <strong>SH:</strong> <em>Your next book, the novel </em>Iridescence<em>, returns us to the past once more. David Lodge said, &quot;Twentieth century perspective brought to bear on 19th century behaviour reveals things about the Victorians that they didn't know or preferred to suppress or simply took for granted.&quot; What does </em>Iridescence<em> reveal about the Victorians that they didn't know, or preferred to suppress or simply took for granted?</em></p>
              <p>
              <strong>PW:</strong> The elasticity of gender. What interested me in writing the novel was that things about sexuality that we take for granted, such as homosexuality, they regarded as far more shadowy. In a sense that allowed Victorian gay men a certain amount of homosexual freedom to move around unnoticed. Having said that, our standard view of the period is that it was heavily moralising, but one of the things I discovered when writing the novel was that their sexual world was so chaotic, so lacking in order as to be exploding out in every direction that they felt they needed a sense of a higher moral order to maintain an ethical cohesion.</p>
              <p>
              <strong>SH:</strong> <em>As a historical literary novel, </em>Iridescence<em> is an exemplar of its genre. It meets all those modalities laid down for the historical novel by David Lodge when he affirmed that this type of fiction must perceptively and accurately envisage the faults and fortes of our ancestors and in so doing draw out parallels between us and them. Were you very aware of such genre descriptors when writing the book?</em></p><p>
              <strong>PW:</strong> Writing <em>Iridescence</em> was as much an adventure as an act of genre- writing. In completing <em>Long Loop Home</em>, I felt like I'd exorcised things which had haunted me all my life. So when I came to <em>Iridescence</em> I felt tremendously and uniquely freed into writing a 'classic' literary historical novel.</p><p>
              <strong>SH:</strong> Iridescence<em> is one of those books where, as a reader, one is very aware of the research undertaken by the author. How much do you enjoy the act of research?</em></p><p>
              <strong>PW:</strong> Oh I love it. What I enjoyed so much about studying history was the digging up of the past. The evidence and traces of the past fascinate me. The wonderful thing about getting the Randell Cottage Residency while writing <em>Iridescence</em> was that I was right next to the Alexander Turnbull Library. Also, I think it's true of all authors who write historical novels, the research has its own momentum and you have to be incredibly assertive to cut it off at a certain point and start to write.</p><p>
              <strong>SH:</strong> <em>How long did the research take you?</em></p><p>
              <strong>PW:</strong> The central event in the novel, the Boulton and Park incident, was one I'd studied for my PhD at Warwick, so all the information related to that remained very clear in my mind. I didn't need to research it. It was the New Zealand elements to the story – the migration, the arrival in New Zealand, the life of the early settlers.</p><p>
              <strong>SH:</strong> <em>Like Jamie in </em>boy overboard<em>, Samuel in </em>Iridescence<em> is a person on the cusp. For him, he's caught in a liminal point between geographical divides – England and New Zealand, and cultural divides. What attracted you to Samuel?</em></p><p>
              <strong>PW:</strong> Napier has always been an imaginative landscape in my life, and so I was fascinated with trying to enter the world of 19th century Napier from an outsider's viewpoint like that of Samuel's, one who's such a misfit. Yet even as a misfit he has to fit in. The entire novel is really about someone learning to live in the landscape, psychological as well as actual. I felt at the end of the novel a great sense of sadness that I was leaving him.</p><p>
              <strong>SH:</strong> Lucky Bastard<em> is another historical novel, though its terrain is recent history. What are the dangers and delights of writing about an era – such as the aftermath of Word War II, which is still retained within our collective memory, particularly by those who lived through this period in time?</em></p><p>
              <strong>PW:</strong> I've very complex feelings about this novel. I decided, too late, I'd written a novel which the core of my readership would not relate to. That is, my readership is largely made up of women – in fact women make up 80 per cent of all readers, apparently – with a smaller proportion of gay men. But I was dealing with war crimes which I hadn't realised was inalienably heterosexual 'male' subject matter, like war itself. There's a romance in the novel but it's between two men. I'd written a novel which wouldn't reach people who 'read' me.</p><p>
              Set in Japan, it also had the added difficulty of being about a part of the war which was largely outside most New Zealanders' experience. So perhaps I didn't actually connect with the 'collective memory'. It's one of those decisions which happen right at the beginning of a novel. A fork in the path. Sometimes you head off on the path and it's only at the end you feel that perhaps it was a wrong direction.</p><p>
              <strong>SH:</strong> <em>Your books often examine sibling relationships, </em>boy overboard<em> and </em>Long Loop Home<em>, for instance, </em>Lucky Bastard<em> too. What attracts you as a writer to scrutinise such relationships?</em></p><p>
              <strong>PW:</strong> <em>Lucky Bastard</em> almost unwittingly became a novel about sibling rivalry, its complications and death-like struggle. That sort of primitive battle between children for the love of a parent is as old as Greek drama. It can be very harmful. I know this from my own life. It interests me, partly because it's so largely unconscious, or arises from the subconscious and is so powerful that it's hard to control. There's not enough love but there's too much love. It's a piquant paradox and a great theme for any writer. Could one say world peace as such is threatened by an eternal form of sibling rivalry – Russia versus America – or the Moslem world versus the 'Crusaders'? Or is that too beauty queenish?</p><p>
              <strong>SH:</strong> Lucky Bastard<em> also symbolises your ongoing literary analysis of the origins and effects of mental and/or physical cruelty visited upon your protagonists. Wouldn't you agree?</em></p>
              <p>
              <strong>PW:</strong> Sadism and masochism seem ingrained in a lot of human relationships. In a war, they become dramatised and a space opens up for humans to act out in the most extreme way. It's a dynamic which is also true sometimes in families or in erotic and love relationships – the captive and the capturer, the prisoner and the guard. There's also a cruelty in kindness.</p><p>
              <strong>SH:</strong> <em>Like many of your books, </em>Lucky Bastard<em> is a mosaic of points of view, first person, third person, etcetera. Is this your natural style of writing or do you prefer one point of view over another, and if so which and why?</em></p><p>
              <strong>PW:</strong> I struggled with the importance of retaining a single point of view or at least a first person voice for the characters. But somehow the third person leapt into the mix and I decided that there were no rules on this in the contemporary novel. The third person voice can see round corners, whereas first person is always special case pleading, 'Listen to me, listen to my story.' The instability of multiple points of view attracts me.</p><p>
              <strong>SH:</strong><em> Fact versus fiction, truth versus media distortion, how to discern what's real amidst a melee of blurred meanings – is </em>Lucky Bastard<em>, in part, an attempt to discuss how much of what we understand about our past is a battle between truth and fable-making?</em></p><p>
              <strong>PW:</strong> The difficulty with the area of Japanese, and Allied, war crimes generally is that they haven't been talked through or acknowledged. The speed with which Japan went from enemy to needed ally in the Cold War meant that certain things were never really investigated. I was attracted to the murkiness of that arena. As a visual field, it seemed to me very like the film <em>The Third Man</em>, a murky black and white world with a lot of desperate characters whose idealism had been snatched from them. I still like the novella at the beginning of the novel, which in fact I wrote first and as a stand alone thing when I first went to the Randell Cottage Residency. That is, the novella preceded <em>Iridescence</em>. I always struggled with how to continue it, whether it needed to continue. Then I got stuck into the boy- father relationship compared with the daughter-father relationship which seemed to me especially poignant. The father prefers the daughter, and the son always suffers from a fatal lack of self-esteem because he knows he can never 'measure up' to his sister in his father's eyes. Suddenly it seemed I had a theme I knew and could talk about. That and war-damaged fathers. Once one places these dilemmas in a media circus that looks into war secrets and war crimes, the unreality of the situation jumps up exponentially.</p><p>
              <strong>SH:</strong> <em>Eric in </em>Lucky Bastard<em> is the archetypal male New Zealand protagonist, the man alone. Is this how you conceived of Eric as you wrote the novel?</em></p><p>
              <strong>PW:</strong> I saw him as a tortured soul, a man who snatched at erotic response 104</p><p>
              as a way of staying alive. Yes, I suppose he was a man alone, I've never thought of that but now you mention it he's a lineal descendant of Jack Lovelock who suicided and that mayor of Wanganui who was caught in a homosexual affair and went off to Berlin in the 1930s and got shot. These are men with a predicament they can't solve and can't even articulate. This is what makes them men alone – they're like that painting of the lovers kissing with sacks on their heads, lost, confined yet passionately and inarticulately searching. That part of the novel was attacked as being pornographic. I love writing erotically. I love writing about sex, and by this I mean not only the mechanics, which require a degree of skill in such a clichéd area but I also love the anthropological search, in a way, for the various meanings of sexual acts.</p><p>
              <strong>SH:</strong> <em>The mechanics and anthropology of sex ... You sound, if you don't mind me saying so, as if you're engrossed with the topic.</em></p><p>
              <strong>PW:</strong> Well, I think partly it goes back to what I said at the beginning, when William Yang said gay men of a certain vintage had never experienced things in a normal heterosexual order. You come to things later in your life and you naturally question them a lot more, see the oddity in them, have a lot of thought about things which to other people might be uncomfortable to look at. I'm fascinated by the emotions that go with sex. They're so discrete, infinite, shaded, urgent, awful, necessary, painful and tender. In my private diaries I write a lot about sex, my thoughts on it, its bizarre banality and poetry. It's the freedom which comes from being a vintage queer, maybe.</p><p>
              <strong>SH:</strong> <em>Or the freedom which comes from being an experienced writer, perhaps. The notion of freedom brings me onto another aspect of your oeuvre, the anthologiser because there's a great deal of autonomy in compiling an anthology. What is it about the work of anthologising that you most enjoy?</em></p>
              <p>
              <strong>PW:</strong> Walking round an obsession. Gathering it into a basket. </p>
              <p><strong>SH:</strong> <em>What makes a good anthologiser?</em></p>
              <p><strong>PW:</strong> An iron will, a little courtesy and probably a restricted palette. </p>
              <p><strong>SH:</strong> The Cat's Whiskers – <em>why cats?</em></p>
              <p><strong>PW:</strong> Cats have always been my friends. I like their silences, moods, inscrutability, fur and warmth.</p>
              <p>
              <strong>SH:</strong> <em>Was it a relief to compile an anthology rather than, say, write a book about your past?</em></p><p>
              <strong>PW:</strong> It was a huge relief for me to talk and write and gather something which wasn't, like, ripping open an artery in full public view and then dipping my pen into the blood and making something out of it. I'm actually an incredibly private person. I hate people observing me accidentally. It makes me most uncomfortable. So the book on cats was a bowl of cream from beginning to end.</p><p>
              <strong>SH:</strong> Best Mates: Gay Writing in Aotearoa New Zealand<em> – did it surprise or delight you to discover how much 'gay' literature exists in the New Zealand literary canon?</em></p><p>
              <strong>PW:</strong> Yes, I was moved by it but also disappointed by the executors of the estates of Charles Brasch, James Courage and even Eric McCormick as they didn't seem to get it that we were attempting to expand their readership base. It was seen as a challenge, as a kind of besmirching. It made me angry and uncomfortable. But some of those people, like Eric McCormick, are like my imaginary uncles. They look over my shoulder, and hopefully, very occasionally, smile.</p><p>
              <strong>SH:</strong> <em>An imaginary uncle – would you like to be remembered by a future writer or future writers as their imaginary uncle?</em></p><p>
              <strong>PW:</strong> Oh yes, definitely. The kind who invites you to afternoon tea, which is followed by a strong cocktail with a hint of scurrilous laughter.</p>
            <p></p>
            </td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="46" width="1"></td>
          </tr>
          <tr>
            <td height="103"><img src="/images/spacer.gif" alt=""
 border="0" height="103" width="1"></td>
          </tr>
        </tbody>
      </table>
      </td>
    </tr>
  </tbody>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
