<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue8/menu_issue8.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue8/john_stauffer/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">The Politics of Self-Making

and the 2008 Presidential Campaign
 <span class="texto2"><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;by <a href="../../issue8/john_stauffer/bio.php" class="link3">John Stauffer</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           &nbsp;<br>&nbsp;<br>
              &ldquo;I am the child of Fortune,&rdquo; declares Oedipus, one of the  great self-made men in ancient Greece.&nbsp;  Abandoned as an infant and left to die, he rises up to become the  benevolent king of Thebes, only to discover that he has unwittingly killed his  father and married his mother.&nbsp; Horrified  by this discovery, he blinds himself, is banished from Thebes, and dies  penniless.&nbsp; In the classical world,  social mobility was not an ideal, and self-made men typically came to an  ignoble end.<br>
&nbsp;&nbsp;&nbsp;&nbsp; American self-made statesmen have fared  much better.&nbsp; Indeed, throughout most of  American history, the image of the self-made man has been invaluable to  presidential candidates.&nbsp; Self-made men  (and now women) appeal to voters particularly during times of national crisis  and the perceived need for change.&nbsp; It is  at these unstable moments that Americans have chosen for president the image of  the self-made man who can remake the nation.
          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            &nbsp;&nbsp;&nbsp;&nbsp; During the  sectional crisis of 1860, for example, Republicans promoted Abraham Lincoln as  &ldquo;the railsplitter,&rdquo; the self-made man who sought to remake the nation by  prohibiting the spread of slavery. Twenty years later, amid Southern terrorism and Northern corruption,  Republicans declared that their candidate James A. Garfield was &ldquo;the ideal  candidate because he is the ideal self-made man.&rdquo; Voters agreed and elected him. More recently, in the wake of a presidential  sex scandal and impeachment proceedings, Republicans trumpeted George W. Bush  as a self-made man who had &ldquo;battled and defeated his own inner demons&rdquo; by  discovering Jesus and being born again.      <br>      
            &nbsp;&nbsp;&nbsp;&nbsp; It is thus no  accident that last November, Barack Obama and Joe Biden, as well as John McCain  and Sarah Palin, were championed by supporters as different versions of the  self-made man or woman and decried by opponents as being falsely or  insufficiently self-made. Amid the worst  economic crisis since 1929, Obama, Biden, and Palin continually emphasized  their rise from modest roots, while McCain drew attention to his struggle up  from POW to a politician who put &ldquo;country first.&rdquo; A central theme of the 2008 campaign was that  bringing &ldquo;the change our country needs&rdquo; would require a self-made person at the  helm.<br>
            <p align="center">******</p>
            &nbsp;&nbsp;&nbsp;&nbsp; The original  meaning of a &ldquo;self-made man,&rdquo; coined in 1832 by Henry Clay, the leader of the  reform-minded Whig Party, denoted someone who had risen up from lowly origins  and sought to improve his world. In  remaking themselves, self-made men also reformed society. <br>
            &nbsp;&nbsp;&nbsp;&nbsp; Lincoln and  Frederick Douglass, the two preeminent self-made men in American history, both  emphasized this point. As Douglass put  it, true self-made men waged war on evil and injustice; they served their  &ldquo;fellow men on earth&rdquo; and &ldquo;God in Heaven.&rdquo;  Lincoln&rsquo;s goal of self-making also began with the self and extended into  society: &ldquo;I want every man to have the  chance&mdash;and I believe a black man is entitled to it&mdash;in which he can better his  condition.&rdquo; For Lincoln (the archetypal  self-made president) and Douglass (the former slave who became the most famous  black man in the western world), the very existence of slavery precluded the  possibility of self-making and a reformed nation.<br>
            &nbsp;&nbsp;&nbsp;&nbsp; Southerners  articulated a different version of self-making, one that was defined by wealthy  and slave owning. In many respects,  Lincoln&rsquo;s Southern counterpart was Nathan Bedford Forrest. Like Lincoln, Forrest was born dirt poor in a  log cabin in a border slave state, had no formal education, and earned money as  a rail splitter. But he became a  successful slave trader, and by the eve of the Civil War was a  multi-millionaire. He spent the rest of  his life trying to preserve the old order of white supremacy in the South,  first by fighting as a Confederate cavalry general, and then by founding the Ku  Klux Klan. <br>
            &nbsp;&nbsp;&nbsp;&nbsp; During the Gilded  Age, as growing inequalities of wealth and the rise of big business made it  increasingly difficult to struggle up from poverty, the concept of self-making  expanded. Now <em>anyone</em> (no matter how elite in origin) could become a self-made man  as long as he <em>remade</em> himself by  overcoming adversity and rising high enough.  In eulogies to J.P. Morgan, journalists declared that &ldquo;in him were the  qualities of the self-made man,&rdquo; because he overcame his ugliness and the  &ldquo;ambition-destroying handicap of having been born rich&rdquo; and ascended &ldquo;as many rounds  of the ladder as did many other financiers who began with nothing.&rdquo; Self-making also expanded to include the  &ldquo;self-made woman.&rdquo; The first book by that  title appeared in 1873, urging women to struggle up and persevere until they  were the equals of men.&nbsp;&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; These two versions  of the self-made man&mdash;-the one born of lowly origins who rises up, the other who  remakes himself through adversity&mdash;have persisted from the nineteenth-century&rsquo;s  Gilded Age through the one that just ended, sometimes competing. During these years, almost half the nation&rsquo;s  presidents&mdash;Garfield, both Roosevelts, Kennedy, Nixon, Reagan, Clinton, the  younger Bush, and Obama&mdash;campaigned on reform platforms and portrayed  themselves as self-made (or remade) men. <br>
            &nbsp;&nbsp;&nbsp;&nbsp; If Lincoln is the  ultimate self-made man, then Theodore and Franklin Roosevelt are exemplars of  remade men. Distant cousins, they came  from families of enormous New York wealth. As a boy, Theodore was called a &ldquo;sissy,&rdquo; as  one scholar noted. Physically weak and  timid, he suffered from asthma and other illnesses. But by championing the &ldquo;strenuous life&rdquo; of  boxing, weight-lifting, hunting, and combat, he remade himself to such a degree  that a Harvard classmate called him &ldquo;the most self-made man in America.&rdquo; His political success stemmed partly from his  ability to turn remaking into an authentic image of self-making.&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; When Franklin  Roosevelt ran for president in the depths of the Great Depression in 1932, he  faced a genuine self-made man in Herbert Hoover, who had been born into  poverty. But most Americans viewed  Roosevelt as the superior self-made man because he had struggled up from the crippling  effects of polio to become governor of New York. Americans saw in his withered legs something  of their own blighted condition, and his tone of confidence gave them hope that  they too, could overcome. According to  the historian Michael Parrish, &ldquo;crutches became FDR&rsquo;s log cabin.&rdquo;&nbsp;&nbsp;<br>
            &nbsp;&nbsp;&nbsp;&nbsp; Kennedy had more  difficulty than the Roosevelts convincing voters of his self-made or remade  status, largely because his father was famously wealthy and had groomed him  from youth to be president. This  difficulty almost cost Kennedy the election.  In 1960, with communism and economic stagnation perceived as major  threats, self-making was a key campaign theme, and most of Kennedy&rsquo;s opponents  regaled voters with stories of their childhood poverty. His Republican opponent, vice-president  Richard Nixon, was well-known as a self-made man, having come from humble  Quaker roots. But he weakened his  ticket&rsquo;s image by choosing for his running mate the Boston Brahmin Henry Cabot  Lodge. Kennedy&rsquo;s campaign slogan, &ldquo;The  New Frontier,&rdquo; linked him with the image of the cowboy, often seen as a  self-made man. Kennedy also emphasized  that his father was self-made. And he  selected as his running mate Lyndon Johnson, a Texan who embodied the rags-to-riches  odyssey. &ldquo;When I was young, poverty was  so common we didn&rsquo;t know it had a name,&rdquo; Johnson frequently said. He bolstered the ticket&rsquo;s image and helped  Kennedy win Southern votes. Had Kennedy  been more effective in portraying himself as a self-made or remade man, by  drawing attention to (rather than ignoring) his ability to persevere through  debilitating ailments, the election probably would not have been so close. As it was, he won by only 100,000 of 69  million votes.&nbsp;<br>
            &nbsp;&nbsp;&nbsp;&nbsp; Historically,  voters more easily forgive the silver spoon in Democrats than in  Republicans. This is because Republicans  have been more deeply committed to the image of the self-made man, frequently  coupling it with the ideology of laissez-faire capitalism. Yet during the Republican ascendancy from  1980-2006, with Democrats increasingly demanding change at the polls, they have  also come to appreciate the power of the self-made image. Indeed, during the past thirty years, the  only Democratic president before Obama, Bill Clinton, was a quintessential  self-made man, having grown up poor in small-town Arkansas. This leveling out of the concept reflected  the fervor with which the 2008 presidential candidates from both parties sold  themselves as self-made men or women.&nbsp;&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; This brings me to  the 2008 campaign. Obama and McCain each  cast himself as a self-made or remade man, ran on a platform of change, and  sought to claim his version of self-making as the most &ldquo;authentic.&rdquo; Obama, the son of a poor white mother who at  times resorted to food stamps, and an African father who abandoned her,  attended private schools on scholarship and became the first black editor of  the <em>Harvard Law Review</em> and the third  black senator since Reconstruction. Like  Frederick Douglass, he became world-famous before the age of forty on the  strength of a bestselling autobiography. And he identifies deeply with Lincoln&rsquo;s story of self-making. In launching his presidential bid, he  declared that &ldquo;the life of a tall, gangly, self-made Springfield lawyer tells  us that a different future is possible.&rdquo;&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; By choosing Joe  Biden as his running mate, Obama teamed up with another self-made man in the  original sense of the term. A child of  working-class parents, Biden overcame a severe stutter before entering public  service. Obama&rsquo;s and Biden&rsquo;s self-made  image, coupled with their platform of change, was a keynote of the Democratic  convention; and they emphasized their rags-to-riches stories on the campaign  trail. The 2008 Democratic ticket was  unusual in having a genuine, double self-made billing.&nbsp;&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; Some Republican  tried to portray McCain as &ldquo;a self-made common man&rdquo; while calling Obama &ldquo;an  elitist,&rdquo; in the hopes of convincing voters that their candidate more closely  followed in the tradition of Lincoln.  But this was a hard sell, since McCain is the son and grandson of  decorated four-star admirals, attended a prestigious prep school before  entering the Naval Academy, and is married to one of the wealthiest women in  America.&nbsp;&nbsp;<br>
            &nbsp;&nbsp;&nbsp;&nbsp; McCain has been  much more effective at crafting the image of a <em>remade</em> man in the tradition of TR and FDR. Retelling his prisoner-of-war story at the  Republican convention, he described how he was reborn through adversity: &ldquo;They worked me over harder than they ever  had before. For a long time. And they broke me. . . . I was never the same  again. I wasn&rsquo;t my own man anymore. I was my country&rsquo;s.&rdquo; In remaking himself, McCain became newly  self-made.&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; McCain&rsquo;s wife  Cindy linked him to her family&rsquo;s own self-made story. On the campaign trail she followed Kennedy by  emphasizing that her father was a classic rags-to-riches guy: he &ldquo;had nothing,&rdquo; she told ABC News last  August. &ldquo;I&rsquo;m proud of what my dad and my  mother did and what they built and left me.&rdquo;&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; Sarah Palin  briefly energized the Republican ticket in much the same way that Johnson had  helped legitimate Kennedy&rsquo;s vision of a New Frontier. Female voters in particular were hungry for a  compelling image of the self-made woman, and the tough-talking Palin, who comes  from a modest, small-town family, was &ldquo;the living definition of a self-made  woman,&rdquo; according to the journalist Michael Hayutin. When Palin became his running mate, McCain  began competing with Obama in the realm of self-making, and thus over a vision  of reform, which was the central issue of the election. But after Palin betrayed her stunning  ignorance of politics, geography, and history, Democrats vigorously and  successfully attacked her self-made image: she had not transformed herself, they argued, but rather was the same,  stupid country girl she had always been.<br>
            &nbsp;&nbsp;&nbsp;&nbsp; Democrats also  tried to undermine McCain&rsquo;s remade image. In a long <em>Rolling Stone</em> article published a month before the election, Tim Dickinson argued that  McCain&rsquo;s Vietnam experience did not change him, other than to make him even  more ambitious:&nbsp; &ldquo;he&rsquo;s still the  undisciplined, spoiled brat that he was when he went&rdquo; to Vietnam, he quoted a  former POW as saying. But Dickinson&rsquo;s  prickly tone disabused few people of McCain&rsquo;s remade image. Besides, it&rsquo;s hard to imagine anyone not  being transformed after spending five years in a POW camp and being tortured  repeatedly.&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; Republicans  similarly (and less successfully) tried to chip away at the authenticity of  Obama&rsquo;s self-made image. To some  critics, Obama came across as too polished, too articulate, too disciplined. They exploited the popular belief, especially  among Republicans, that Americans want to see <em>themselves</em> in a candidate. They want their candidates to be amateur or &ldquo;imperfect servants,&rdquo; as  McCain says of himself (he plays the role well), rather than a supremely  gifted, professional and disciplined campaigner and orator like Obama, who  actually writes some of his own speeches.&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; In this respect,  Obama resembles a professional athlete.  For many Americans, professional athletes are &ldquo;our culture&rsquo;s holy men,&rdquo;  as David Foster Wallace shrewdly noted; &ldquo;they give themselves over to a  pursuit, endure great privation and pain to actualize themselves at it, and  enjoy a relationship to perfection that we admire and reward. . . . They do it  &lsquo;for&rsquo; us, sacrifice themselves for our (we imagine) redemption.&rdquo;&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; But Republicans,  who see government as the problem, would never equate professional athletes  with politicians. If athletes are their  holy men, politicians are their policemen. And the police deal with problems, which are always messy. One Republican ad cast Obama as a &ldquo;self-made  messiah.&rdquo; To a star athlete, this would  be a term of endearment; but it was meant to be a put-down, connoting arrogance  and elitism.&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; In another  critique of Obama&rsquo;s self-making, detractors compared him to F. Scott  Fitzgerald&rsquo;s Jay Gatsby. He was, like  Gatsby, mysterious and unknowable, a stranger, a &ldquo;romantic but insubstantial  figure,&rdquo; and &ldquo;a man of false dreams&rdquo; who was not who he seems. <br>
            &nbsp;&nbsp;&nbsp;&nbsp; But critics who  liken Obama to Gatsby ignore two crucial points. First, despite his flaws, Gatsby is, with  Lincoln, one of the great self-made men in the American imagination. Indeed, in one of the most important lines in  the novel, the narrator Nick Carraway tells Gatsby: &ldquo;You&rsquo;re worth the whole damn bunch put  together.&rdquo; In a society of cheaters and  cynics and careless people who &ldquo;smashed things up&rdquo; and then &ldquo;retreated back  into their money,&rdquo; Gatsby stands apart through his &ldquo;incorruptible dream&rdquo; and  his willingness to realize it. He is,  like Obama, audaciously hopeful.<br>
            &nbsp;&nbsp;&nbsp;&nbsp; Moreover, by  invoking Gatsby critics inadvertently played the race card. Gatsby&rsquo;s mysteriousness and strangeness stems  more from his identity as an ethnic outsider who passes for a WASP than from  his self-making. His given name, Jay  Gatz, is probably Jewish. Even more  significant is the fact that Fitzgerald first conceived him as a light-skinned  black who passed. Thus, critics who  linked Obama to Gatsby, and dwelled on his strangeness and mysteriousness,  unconsciously echoed white characterizations of ethnic and racial outsiders  during an era (the 1920s) of virulent racism and anti-Semitism.&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; The concept of  self-making was as important in the 2008 election as it has ever been. While Americans generally prefer image over  issues, the two were closely linked last November: after all, they were voting for the self-made  man who they hoped would remake a nation reeling from domestic and foreign  crises.&nbsp; <br>
          &nbsp;&nbsp;&nbsp;&nbsp; Most political  analysts have concluded that Obama won last November owing to economic  free-fall in the months leading up to election.  But they are wrong, for they ignore the power of genuine  self-making. What actually happened was  that Obama persuaded voters that he was more like Lincoln than Gatsby, and that  his doubly self-made ticket was authentic.  Indeed, his self-made persona not only defeated McCain; it trumped the  racism that continues to plague America.  As Frederick Douglass noted long ago, the art of self-transformation can  break down racial barriers.&nbsp;        </td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
