<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--

-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue10/menu_issue10.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue10/zhimin-li/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">New Chinese Poetry: The Origin and the Development
&#8212; From the Perspective of Cultural Exchanges between China and the West
 <span class="texto2">by <a href="../../issue10/zhimin-li/bio.php" class="link3">Zhimin Li</a>, a transcription of a presentation given at The  Kelly Writers House, University of Pennsylvania, Philadelphia, USA </span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           &nbsp;<br>
              <p><strong>&nbsp;</strong>In this &ldquo;globalization age&rdquo;, no nation can survive,  not to say develop, without learning from the achievements, either of natural  science or of social science, of other nations. &ldquo;Nations must serve as guides  for one another.&rdquo; In every country one should &ldquo;welcome foreign ideas, for  hospitality in this way makes the fortune of those who receive it.&rdquo;<a href="#_ftn1" name="_ftnref1" title=""><sup>1</sup></a> China is becoming more  &ldquo;universal&rdquo; by receiving influences from the West who had received influences  from China in previous ages.</p>
          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2"><p>&nbsp;</p>
<p><strong>I. Influence  of </strong><strong>China</strong><strong> on the West</strong></p>
            <p>Joseph  Needham once said: &ldquo;The more you know of Chinese technology in the medieval  period, the more you realize that, not only in the case of certain things very  well known, such as the invention of gunpowder, the invention of paper,  printing, and the magnetic compass, but in many other cases, inventions and  technological discoveries were made in China which changed the course of  Western civilization, and indeed that of the whole world.&rdquo;<a href="#_ftn2" name="_ftnref2" title=""><sup>2</sup></a> Joseph Needham offers many concrete examples to support his argument. Natural  science is itself an embodiment of a certain philosophy. The acceptance of  science and technology from another culture is in fact accepting a certain  philosophy as well. Hugh Kenner offers some direct traces of Chinese  philosophic influence on Western philosophy.<a href="#_ftn3" name="_ftnref3" title=""><sup>3</sup></a> In  the field of politics, some basic institutions, including the &ldquo;Civil Service  Examination System&rdquo;, in China were imitated by Europe. Literature was also  introduced from China into the West and carried  much influence on Western literary circles. Johann Wolfgang <em>Goethe</em> once highly praised a novel from China, i.e., <em>Haoqiu Zhuan</em> (&#12298;&#22909;&#36881;&#20256;&#12299;, <em>The Fortunate Union</em>). <br>
  &nbsp; In the field of poetry, China also  carried much influence on the West, the most well-known example is Ezra Pound  who published <em>Cathay</em>, a  book of all Chinese poems with only one exception. &ldquo;The River-Merchant&rsquo;s  Wife&rsquo;s: a Letter&rdquo; in <em>Cathay</em> is a  good example that well demonstrates the charm of Chinese poetry that attracted  Ezra Pound. The whole poem is full of fresh, concrete, energetic images, which  are created by the technique of &ldquo;Look-Back Strikes&rdquo;. For example, in the lines  from the second to the fourth, a <em>Genteel </em>poet  might just writes: &ldquo;I played about the front gate/  You came by on bamboo stilts/ You walked about my seat&rdquo;, in which it seems that  the story is also made clear. However, the poetic beauty of the images is  terribly undermined, as the images are much less concrete. The three phrases &ldquo;pulling  flowers&rdquo;, &ldquo;playing horse&rdquo;, &ldquo;playing with blue plum&rdquo; serve as &ldquo;Back Strikes&rdquo;,  hammering once more on the images preceded and guaranteed the finalization of  beautiful images. By the way, the three phrases together produce a marvelous  poetic rhythm and a wonderful poetic sound image as well. In the image of &ldquo;By  the gate now, the moss is grown, the different mosses,/ Too deep to clear them  away&rdquo;, two &ldquo;Back Strikes&rdquo; are applied, and, therefore, a very vivid image is  produced. <br>
  &nbsp; However, the most marvelous poetic  achievement is the unprecedented, and probably subconscious as well,  application of &ldquo;Sound-Linked Images Flow&rdquo; in English. This poetic technique is  very frequently applied in traditional Chinese poetry, especially obviously in  Chinese Couplets. This technique can greatly free images from the bondage of  grammar and, therefore, produce wonderful bondage of poetic image; and at the  same time, readers do not feel the lines are loosened because of lack of good  grammar, as the sound of words closely knit them into a beautiful acoustic  unit. In &ldquo;The River-Merchant&rsquo;s Wife&rsquo;s: a Letter&rdquo;, &ldquo;pulling  flowers&rdquo;, the phrase-images &ldquo;playing horse&rdquo;, &ldquo;playing with blue plum&rdquo;, though  not a typical example, have more or less achieved this effect. <br>
              In fact, <em>Cathay</em> was such a success that, when it came out in 1915, &ldquo;almost all the major  Modernists&mdash;Yeats, Ford, Lewis, Eliot, and Williams&mdash;applauded its freshness,  elegance, and simplicity. Ford, in particular, remarked, &lsquo;If these were  original verses, then Pound was the greatest poet of the day&rsquo;, which should  indicate that the English Modernist writer and critic had perceived affinities  between his own and Far Eastern sensibilities.&rdquo;<a href="#_ftn4" name="_ftnref4" title=""><sup>4</sup></a> After Ezra Pound&rsquo;s successful introduction of Chinese poetry into the West,  Western poets started to learn more and more from Chinese poetry, most of whom  are not disappointed. For example, William Carlos Williams learned &ldquo;the  technique of achieving wholeness by means of uniting opposing elements&rdquo; from  Bai Juyi, a fellow poet of Li Bai in Tang Dynasty in Ancient China.<a href="#_ftn5" name="_ftnref5" title=""><sup>5</sup></a> <br>
  &nbsp; <br>
  <strong>II. New Chinese  Poetry being Fermented under Influence from the West</strong></p>
            <p>It  should be surprising to readers if they are told New Chinese Poetry was born  with the introduction of Western Poetry. In order to make it clear, we need to  examine the social, cultural and literary backgrounds in China in which New Chinese Poetry  was conceived and finally was born. <strong></strong><br>
              China had not known much of the West until the year of 1840  when England waged a war against the Qing Dynasty government, thus  commencing the Modern Age in China. China had remained a powerful  nation for a long time. Even at the time when Columbus discovered America in 1492, China  was still the most powerful nation in the world. &ldquo;The most powerful empire the  world over was in Asia----she was China  in Ming Dynasty. From 1405 to 1423, Chinese fleets which contained hundreds of  warships dwarfed Columbus&rsquo;s  sailboats and brought the fame of the Chinese Empire further into South Asia, East Asia and the  Indonesian islands.&rdquo;<a href="#_ftn6" name="_ftnref6" title=""><sup>6</sup></a> It  is no wonder that many European people, especially the upper class people,  should have so fancied Chinese products as well as the Chinese way of living  during the sixteenth and seventeenth century, just as many Chinese people very  much fancy the Western way of living nowadays. <br>
              China failed in the war with England in 1840, a failure followed  with a series of misfortunes she had never experienced in the past. Finally,  &ldquo;the Chinese began to doubt anything of their traditional culture and this  gradually caused the May-fourth movement that was to overthrow all traditional  Chinese cultures and rebuild their culture by learning everything from the West  civilizations. &hellip;&rdquo; <a href="#_ftn7" name="_ftnref7" title=""><sup>7</sup></a> China had been learning from  other nations and had always been accepting foreign cultural nourishment during  its whole historical course.<a href="#_ftn8" name="_ftnref8" title=""><sup>8</sup></a> Yet the process of China learning from the West  after 1840 is very special. Before 1840, China had learned from other  civilizations and had assimilated the elements of other civilizations into here  own culture that is basically of Confucianism. However, it is all different in  the modern age. &ldquo;When China  was confronting the challenge of the West in the modern era, Confucianism could  no more absorb it as it once had done with Buddhism. It finally became the  negative force in the development of Chinese society, causing the Chinese to  fall into a severe ideological peril.&rdquo;<a href="#_ftn9" name="_ftnref9" title=""><sup>9</sup></a> Confucianism, once the main foundation of Chinese culture, was revealed of many  of its defects and was radically criticized by some Chinese vanguards,  especially those who had won a chance to study in the West for some time.  Chinese culture then experienced a collapse from within, resulting in an  unselected influx of Western ideologies. Chinese literature as a main carrier  of Chinese culture was first and foremost challenged and subsequently  thoroughly reformed on the basis of modeling itself on the West. Even the  Chinese ideographic characters that were established thousands of years ago and  had been creating many literary wonders, were seriously questioned and  challenged.<a href="#_ftn10" name="_ftnref10" title=""><sup>10</sup></a> It was a crazy age, in which Chinese cultural values were all questions,  re-examined and often criticized even without sound arguments. At the same  time, Western models were introduced to replace the vacuum of many cultural  practices. <br>
  &nbsp;&nbsp; The learning  from the West was well demonstrated by the translation of books. At the very  beginning, &ldquo;the books such as literary books and philosophic books were ignored  in those days. It was natural for Chinese then to think that Western art and  philosophy would certainly be lagging behind China, with its 5,000 years&rsquo;  history, though they had very powerful guns&hellip;&rdquo;<a href="#_ftn11" name="_ftnref11" title=""><sup>11</sup></a> However, the failure of the Reform Movement of 1898 demonstrated the  impossibility for the Chinese culture to reform from within, and so many  scholars started a large-scale importing of Western ideas and methods. Since  there were very few Chinese who had learned any Western language or culture,  most Chinese scholars chose to introduce Western ideology into China by translating  Western-origin works in Japanese. &ldquo;During the three hundred years before the  Sino-Japanese War of 1894-95, the Chinese translated only 12 Japanese books.  But within the 15 years after it, the Chinese translated 958 Japanese books,  most of which were originally Western or written about the West&hellip;&rdquo;<a href="#_ftn12" name="_ftnref12" title=""><sup>12</sup></a> The influx of Western works into China on this unprecedented scale then  formally began the Westernization of Chinese culture that had been up to then  so well established that only an internal upheaval could possibly shake and  change it. <br>
              Poetry,  as the most sensitive element of Chinese culture, responded very fast to the  dramatic changes in China after 1840. Very soon after  the Opium War of 1840, some reformation of Chinese poetry had already occurred.  Gong Zizhen&#65288;&#40858;&#33258;&#29645;&#65289;and Wei Yuan&#65288;&#39759;&#28304;&#65289;, two famous patriots, claimed that there was an  urgent need to change Traditional Chinese Poetry to serve their nation. <a href="#_ftn13" name="_ftnref13" title=""><sup>13</sup></a> They did some initial work in this respect and, later on, Huang Zunxian&#65288;&#40644;&#36981;&#23466;&#65289; and Liang Qichao&#65288;&#26753;&#21551;&#36229;&#65289; made a true beginning at rendering classical Chinese  poetry into a much freer form by accepting Western poetics. <br>
              The  most well known resulting poetic reformation during this period was Huang&rsquo;s  &ldquo;New Style&rdquo;, whose core is &ldquo;to write as you speak.&rdquo; Liang, however, cultivated  a much grander aim to reform traditional Chinese literature as a whole by  challenging the traditional literary language----Wenyan. Later on, people took  Liang Qichao as the initiator of Baihua Literature (literature in vernacular Chinese),  and many important literary figures, including Hu Shi&#65288;&#32993;&#36866;&#65289;, Chen Duxiu&#65288;&#38472;&#29420;&#31168;&#65289; and Li Dazhao&#65288;&#26446;&#22823;&#38026;&#65289;, were deeply influenced by  Liang before the May Fourth Movement.&nbsp;&nbsp; <strong></strong><br>
  &nbsp; Changes in the  field of poetry only serve as an example. In fact, changes happened in all the  literary fields after the Opium War, with the basic belief of reforming Chinese  culture for survival.<a href="#_ftn14" name="_ftnref14" title=""><sup>14</sup></a> The movements of reforming Chinese culture grew and finally in 1919 it  exploded, resulting in the changed climate of the May Fourth Movement, which  was basically characterized by the Western ideologies of Democracy and Science.  Its fundamental significance was its acceptance of the need to learn from  Western culture in reforming Chinese traditional culture and literature. Hu  Shi&rsquo;s &ldquo;Some Suggestions for Reforming Chinese Literature&rdquo;<a href="#_ftn15" name="_ftnref15" title=""><sup>15</sup></a>,  which was composed in the United States and posted back to China to be  published by Chen Duxiu in <em>New Youth </em>(&#12298;&#26032;&#38738;&#24180;&#12299;), the vanguard of the May  Fourth Movement, was the most significant literary advance and was  enthusiastically hailed and followed. The core of Hu Shi&rsquo;s advocacy was to  establish New Chinese Literature by overthrowing the traditional one, the  traditional literary language Wenyan as well.<br>
  &nbsp; To overthrow  Chinese traditional poetics, Hu Shi argued that vernacular Chinese is the true  carrier of poetry and, thus that vernacular poetry should take the place of  traditional Chinese poetry. &ldquo;It is very clear that the vernacular could be  applied to writing poems. The vernacular poems of Du  Fu &#65288;&#26460;&#29995;&#65289;,  Bai Juyi &#65288;&#30333;&#23621;&#26131;&#65289;,  Hanshan &#65288;&#23506;&#23665;&#65289;,  Shi De &#65288;&#25342;&#24471;&#65289;,  Shao Yong &#65288;&#37045;&#38605;&#65289;,  Wang Anshi&nbsp; &#65288;&#29579;&#23433;&#30707;&#65289;and Lu You &#65288;&#38470;&#28216;&#65289; can all be cited as proofs. There are even more  proofs in Ci &#65288;&#35789;&#65289; and Qu &#65288;&#26354;&#65289;.&rdquo;<a href="#_ftn16" name="_ftnref16" title=""><sup>16</sup></a> He even exaggerated that &ldquo;in short, all valuable literary works in China since <em>The Book of Poetry</em> (&#12298;&#35799;&#32463;&#12299;)are in the vernacular or very close to the vernacular.&rdquo;<a href="#_ftn17" name="_ftnref17" title=""><sup>17</sup></a>&nbsp; Hu Shi&rsquo;s criteria were very partial.  Nevertheless, his standpoint was supported by many of his followers, who agreed  to simplify traditional Chinese literature, with Wenyan that appeals only to  the educated class, so that the ordinary public can be well educated to do  something on behalf of the nation. It is ironical to note that Hu Shi and his  colleagues worked hard to simplify Chinese poetry, however, after almost one  century&rsquo;s development, contemporary Chinese poetry is becoming more and more  difficult again, being mostly too difficult for ordinary readers to understand.  Hu Shi could have been more convincing if he had not sought too exclusively poetical  reasons rather than social ones. Hu Shi and his fellow Cultural Reformers did  succeed in establishing vernacular Chinese as an officially accepted written  language. However, if it had not been for the particular historical background,  Hu Shi would never have succeeded so easily in establishing the vernacular,  instead of Wenyan, as the solely right tool for poetry, because his arguments  would never have been strong enough to do so in any other historical situation. <br>
              Many  scholars admit that the creation of New Chinese Literature came about mainly  because of the need to call on all Chinese to come together to save their  nation. I. A. Richards said: &ldquo;The intellectual movement in Modern China is  primarily a consequence of the political movement. The traditional Chinese  outlook is being remade&mdash;not because it was felt to be unsatisfactory in <em>itself</em> but because it plainly put China at a disadvantage in the  world-struggle.&rdquo;<a href="#_ftn18" name="_ftnref18" title=""><sup>18</sup></a> Since traditional Chinese poetry appealed only to a small number of  well-educated people, it was criticized and replaced by easily understandable  New Chinese Poetry. Naturally, that did not mean that traditional Chinese  literature had not been beautiful and nourishing to the spirit, since literary  beauty does not necessarily go together with popularity among all members of a  society. Actually, many beautiful literary works are very demanding and appeal  only to a very small number of readers. But, again, that does not necessarily  mean that a good literary work has to be difficult, as there are also many  beautiful yet simple works. In short, literary beauty and literary popularity  are not identical; some times they coincide with each other while on other  occasions not so.<br>
              Traditional  Chinese Poetry had undergone several large-scale changes in its history before  the Modern Age in China. &ldquo;After Four-word poetry  declined, there appeared <em>Songs from the  South</em>&#65288;&#26970;&#35789;&#65289;; after <em>Songs from the South</em> declined, there appeared Five-word poetry;  after Five-word poetry was Seven-word poetry; after the ancient-style poetry  was Lu &#65288;&#24459;&#65289;and Jue&#65288;&#32477;&#65289;, followed by Ci&#65288;&#35789;&#65289;.&rdquo;<a href="#_ftn19" name="_ftnref19" title=""><sup>19</sup></a> Wang Guowei &#65288;&#29579;&#22269;&#32500;&#65289; gave a more academically  reasoned explanation for this phenomenon: &ldquo;&hellip;all those changes happened because  after a certain literary form got into circulation, more people would utilize  it and then a rigid pattern would take shape, which would prevent even the  well-educated people from making attractive literature. Therefore people  abdicated the old forms and created new ones. This is the reason that all  prosperous literary forms finally declined.&rdquo;<a href="#_ftn20" name="_ftnref20" title=""><sup>20</sup></a> However, Wang&rsquo;s explanation can not be applied to explain the formation of New  Chinese Poetry because New Chinese Poetry had been established and widely  accepted even before any literary wonders were created in this literary genre.  And during all the twentieth century, many people, including poet Chairman Mao  Zedong (although he supported New Chinese Poetry politically), repeatedly  questioned the success of New Chinese Poetry as a literary genre. </p>
            <p><strong>III. The Formation Period of New Chinese Poetry from the 1910s to the  1940s</strong></p>
            <p>&nbsp; A desperate  person can easily be driven into madness, so can a people. Since Chinese  culture seemed too weak to hold its own against the violence of internal  warfare and external modernizing upheavals, it was subsequently madly  challenged by its own people. Chinese classical literature, being a part of  Chinese culture and with Chinese classical poetry as a central component, being  generally considered as no less wonderful than that of any other culture on  earth, was supplanted by a so-called commonplace people&rsquo;s literature, whose  main aim was to penetrate into the minds of the ordinary Chinese, calling upon  them to stand up for the rescue of their nation as well as themselves. <br>
              During  those years, many persons that had the best advantage in interpreting Western  culture and literature, usually being those who had actually spent significant  periods abroad, acquired a considerable measure of fame. Hu Shi, who had stayed  for eight years in the United States and finally earned a Ph.D.  at Columbia University in New York, was one of the few  important persons that &ldquo;ignited&rdquo; the New Chinese Literary Movements. Hu Shi  said: &ldquo;This movement [the May Fourth Movement]&mdash;&mdash;which is generally called a  literary revolution, I myself prefer to address it as the Chinese  Renaissance---- was initiated by my friends and I in an American university  dormitory in 1915, 1916 and 1917.&rdquo;<a href="#_ftn21" name="_ftnref21" title=""><sup>21</sup></a> Hu Shi&rsquo;s Doctorate was not in literature but in ancient Chinese philosophy,  though he claimed that he read a considerable number of Western literary books  while in the United States. Scholars often seriously  doubt Hu truly knew about Western literature and its cultural background. <br>
              His <em>Attempting Poems</em> (&#12298;&#23581;&#35797;&#38598;&#12299;), the first poem-collection  in Vernacular Chinese, which was widely distributed and imitated, formally  starting the New Chinese Poetry history, is actually of quite limited literary  quality. Its most significant value seems to consist in the very fact that it  is in vernacular Chinese----like &ldquo;a small foot that has just been released&rdquo; as  Hu Shi himself later on apologized. <br>
  &nbsp; It is almost  certain that Hu Shi indeed learned or copied some models from Western  literature for constructing his famous &ldquo;Eight Nos&rdquo;, a prescription which he  drew up for reforming Chinese literature, and which became highly esteemed  during subsequent literary movements in China.<a href="#_ftn22" name="_ftnref22" title=""><sup>22</sup></a> In fact, while Hu Shi was studying in New York from 1910 to 1917, the  Imagism that had been proposed by Ezra Pound was quite influential there and Hu  copied the proposals of the American Imagist Amy Lowell in his notebook.<a href="#_ftn23" name="_ftnref23" title=""><sup>23</sup></a> The Imagists proposed to create free verse in new-rhythm and new-form using  daily language rather than old-style poetic vocabulary. There can hardly be any  doubt that Hu borrowed some ideas from the Imagists who learned from Traditional  Chinese Poetry themselves.<a href="#_ftn24" name="_ftnref24" title=""><sup>24</sup></a><br>
  &nbsp; Hu Shi, in a  sense, is one of the few persons who set the literary direction for the May  Fourth Movement. His Western background and Western literary characteristics  thus strongly promoted the Western poetical characteristics of New Chinese  Poetry. Soon after Hu&rsquo;s <em>Attempting Poems</em>,  there emerged many poem-collections that more or less based themselves on some  imported Western poetics, among which Guo Moruo (&#37101;&#27819;&#33509;)&rsquo;s <em>The Goddesses </em>(&#12298;&#22899;&#31070;&#12299;&#65292;1921) and Li Jinfa&#65288;&#26446;&#37329;&#21457;&#65289;&rsquo;s <em>Light Rain</em>(&#12298;&#24494;&#38632;&#12299;&#65292;1925)<em>,</em> correspondingly importing Western Romanticism and Symbolism  into New Chinese Poetry, were among the few works that generated the most  immediate and widely-spread attention in the Chinese literary circles of those  days. <br>
  &nbsp;<strong>&nbsp;</strong>Guo  Moruo&rsquo;s poem T<em>he Goddesses,</em> which is  generally considered as the very beginning of Chinese Modern Romanticism that  created the first climax of New Chinese Poetry<em>, </em>is of very obvious Western characteristics.<a href="#_ftn25" name="_ftnref25" title=""><sup>25</sup></a> The title image &ldquo;goddess&rdquo; is from Western mythology. &ldquo;The Western images in <em>The Goddess </em>are much more prevalent than  the Chinese ones, such Western mythic images as Apollo, Venus, Cupid, Bacchus,  Prometheus, Hygeia&hellip; There are also many Western historical terms. And there are  even many words in English in this Chinese poem.&rdquo;<a href="#_ftn26" name="_ftnref26" title=""><sup>26</sup></a>&nbsp; To directly apply Western sentences in a poem  did never happen in traditional Chinese poetry, and it is rather ridiculous  that a poem supposedly for the commonplace people should apply some sentences  that only very few well-educated people could possibly understand. The same  problem applies to the Western images in <em>The  Goddesses</em> too, as fulfilling the supposed target of New Chinese  Literature to serve the ordinary people, since the conveyed meanings  of such Western images could not possibly have appealed to any but specially  trained ears. Later on, up to the present, new Chinese poetry has been going  further and further towards Western poetical development as well as away from  its commonplace native readers. <strong></strong><br>
  &nbsp; As soon as <em>The Goddesses</em> was published, it quickly  became popular within Chinese literary circles and thus firmly established  Guo&rsquo;s position as a leading figure in the literary world in China. However, the overall most  important factor in <em>The Goddesses</em> that appealed to Chinese readers was not so much its literary quality, but  rather its patriotic theme as it enthusiastically hailed China as a phoenix coming to a  rebirth by burning herself painfully, most forcibly evidenced by the poem  &ldquo;Rebirth of the Goddesses&rdquo;: &ldquo;&hellip; Ladies and Gentlemen, you have become tired of  living in the foetid gloom of this dark world. You surely thirst for light.  Your poet, having dramatized so far, writes no more. He has, in fact, fled  beyond the sea to create new light and heat. Ladies and gentlemen, do you await  the appearance of a new sun? You are bid to create it for yourselves. We will  meet again under the new sun.&rdquo;<a href="#_ftn27" name="_ftnref27" title=""><sup>27</sup></a> Besides, Guo&rsquo;s <em>The Goddesses</em> is  heavily laden with strong optimism that was very precious for China in a dark  age: most poems in <em>The Goddesses </em>are  happy and energetic, such as &ldquo;Sunrise&rdquo;, &ldquo;The Good Morning&rdquo;, &ldquo;Shouting on the  Rim of the World, Oh Earth, My Mother&rdquo;, &ldquo;Sea of Light&rdquo;, &ldquo;Hymn to the Sun&rdquo; and  &ldquo;Stirring of Spring&rdquo;, etc.<br>
              More  often than not, the popularity of a piece of literary work does not necessarily  go together with a high level of literary merit. In <em>The Goddesses</em> there are so many superfluous words and unqualified  sentences that a well-trained eye could clearly see Guo&rsquo;s lack of precise  control over either diction or emotion, such as in the poem &ldquo;Good Morning&rdquo;:<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Ah,  Ah! Alas the Pacific Ocean!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Good  morning!&nbsp;&nbsp; Alas the Pacific Ocean!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Good  morning! Alas the New Continent beside the Pacific Ocean!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Good  morning! Alas the grave of Washington! Alas the grave of Lincoln!&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Alas the grave of Whitman! <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ah, Ah!  Alas Whitman! Alas Whitman! Alas the Pacific-like Whitman!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ah, Ah!  Alas the Pacific Ocean!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Good  morning! Alas the Pacific Ocean!&rdquo;<a href="#_ftn28" name="_ftnref28" title=""><sup>28</sup></a></p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (&#21834;&#21834;! &#22823;&#35199;&#27915;&#21568;!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#26216;&#23433;! &#22823;&#35199;&#27915;&#21568;!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#26216;&#23433;! &#22823;&#35199;&#27915;&#30036;&#30340;&#26032;&#22823;&#38470;&#21568;!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#26216;&#23433;! &#21326;&#30427;&#39039;&#30340;&#22675;&#21568;! &#26519;&#32943;&#30340;&#22675;&#21568;! &#24800;&#29305;&#26364;&#30340;&#22675;&#21568;!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#21834;&#21834;! &#24800;&#29305;&#26364;&#21568;! &#24800;&#29305;&#26364;&#21568;! &#22826;&#24179;&#27915;&#19968;&#26679;&#30340;&#24800;&#29305;&#26364;&#21568;!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#21834;&#21834;! &#22826;&#24179;&#27915;&#21568;!<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#26216;&#23433;! &#22826;&#24179;&#27915;&#21568;!)</p>
            <p>Any  emotion, not to say unqualified diction, that goes beyond control in a poem  should be considered as superfluous and shallow, which would only offend an ear  instead of offering any ordered beauty of expression. There is no wonder that  there should have been so many superfluous and shallow poems to &ldquo;serve&rdquo; the  commonplace, being produced during the Cultural Revolution Years while Guo held  the official leadership of literary circles in China. Guo might have understood  his own poetic limitations later on since he said frankly that &ldquo;Viewed as  literature, these poems may disappoint the reader. Let them rather be taken as  recordings of the age in which they were written.&rdquo;<a href="#_ftn29" name="_ftnref29" title=""><sup>29</sup></a>&nbsp; It should also be remembered here that to  point out the few drawbacks in <em>The  Goddesses</em> is by no means to deny its being a literary milestone in the  history of New Chinese Poetry, not to say to denigrate Guo the poet as one of  the greatest literary figures in the history of New Chinese Literature; since  Guo also wrote quite a few remarkable novels that should be  worth much more  recommendation than his poetic creation.<br>
              Li  Jinfa, who introduced Western Symbolism into New Chinese Poetry, might be one  of the few exceptions who became a famous new Chinese poet without a good  mastery of either Chinese or any foreign language. Li Jinfa, who was  concentrating on studying sculpture in France, occasionally scratched a  few lines in the manner of French Symbolism and got his poems published in China, which immediately brought  him an unexpected success.<a href="#_ftn30" name="_ftnref30" title=""><sup>30</sup></a> Li&rsquo;s introduction of French  Symbolism into China attracted the attention of  many poets such as Dai Wangshu, Wang Duqing, Bian Zhilin and others, many of  them now considered better writers than Li himself <br>
  &nbsp; Li is commonly  referred as a &ldquo;Shi Guai&rdquo; (&#35799;&#24618;,  a bizarre poet)  because of his &ldquo;bizarre&rdquo; disposition of images, the bizarre images themselves  and the bizarrely awkward diction that made his poems appear to be very fresh  and imaginative. Readers of Li&rsquo;s works can often see very bizarre and  incoherent pictures and to obtain a wonderful poetical experience; it  nevertheless demands of a reader a strong imaginative power. To mention that Li  did bring some poetical merits is in no way to guarantee that Li was a master  of the Chinese language. Li Jinfa had only a very poor opportunity to improve  his Chinese while young.<a href="#_ftn31" name="_ftnref31" title=""><sup>31</sup></a> Li&rsquo;s linguistic limitation in Chinese is clearly seen in all his three poem  collections, <em>Light Rain </em>(1925), <em>I Sang for Happiness</em> (&#12298;&#20026;&#24184;&#31119;&#32780;&#27468;&#12299;&#65292;1926), <em>The  Long-Term Visitor and Hard Times </em>(&#12298;&#39135;&#23458;&#19982;&#20982;&#24180;&#12299;&#65292;1927), where poor diction is  everywhere. Zhu Ziqing said: &ldquo;There is no want of imagination in Li&rsquo;s poem; but  his sentence structures are too Europeanized, with some classical Chinese preps  and conjunctions, making one feel rather like reading a piece of translation  work than an original; this might be owing to Li&rsquo;s too anxious intention of  creating a new language, or because his mother tongue is too limited.&rdquo;<a href="#_ftn32" name="_ftnref32" title=""><sup>32</sup></a> <br>
  &nbsp; Li never  published another line in the way of poetry after <em>The Long-Term Visitor and Hard Times</em>. Many famous writers, such as  Lu Xun and Zhou Zuoren, did exactly the same: they wrote New Chinese Poetry in  order to help have it established, and not to write one single line afterwards.  Even Hu Shi, the very initiator of New Chinese Poetry is more or less of the  same like.&nbsp;&nbsp; <br>
  &nbsp; <br>
  <strong>IV. The Misty  Poetry Period from 1978 to 1989 and the Individual Creation Period after 1990s</strong></p>
            <p>New  Chinese Poetry during the period from 1949 to 1978 is to be only briefly  discussed, for New Chinese Literature as a whole did not make any significant  progress, if any, during this period, especially during the ten-year Cultural  Revolution from 1966 to 1976. The problem was caused by the wish to make  literature serve as a subordinate instrument for politics, which resulted in  the extreme formalization and generalization of all literary creation in China: The &ldquo;revolutionary&rdquo;  personages in most &ldquo;revolutionary&rdquo; writings are perfect in all respects, the  former chapters of such works informing readers about the latter ones.  Therefore, &ldquo;during all the ten years of the Cultural Revolution, there occurred  only eight Model Plays and one Author, as people said in joking tones during  those days.&rdquo;<a href="#_ftn33" name="_ftnref33" title=""><sup>33</sup></a> Literary Circles, including that of poetry, were depressed as a whole. However,  the slogan of &ldquo;literature serving as a subordinate instrument for politics&rdquo; was  officially abolished in the late 1970s, liberating literature from its  prolonged chains. <br>
  &nbsp; After the  removal of the chains of Literature Serving Politics, &ldquo;Misty Poetry&rdquo; gradually  grew and finally bloomed. It is conventional wisdom to say that Misty Poetry is  made up of the sighs, complaints and songs of the long depressed, and then  newly released intellectual spirits. Therefore, it is not strange that Misty  Poetry was mainly concerned with political themes, and was addressed as  Political Poetry by some critics. More than politics, Misty poetry was also  concerned with humanity, cultural tradition and intellectual existence, being  much more advanced in comparison with the poetry in the previous age, which can  be viewed as a partial return to and a further development of the May Fourth  Literature.<br>
  &nbsp; Misty Poetry  as a whole is quite a misty term. The Misty poet Gu Cheng said: &ldquo;Some of my  fellow poets and I have always considered the term &lsquo;Misty&rsquo; itself to be rather  misty.&rdquo;<a href="#_ftn34" name="_ftnref34" title=""><sup>34</sup></a> Misty Poetry was perhaps considered as misty just because most readers,  especially some officially important critics, had long accustomed themselves to  easy, slogan-like poems. The misty quality of Misty Poetry results in profound  poetic beauty, establishing an embryo of a new Chinese literary language that  is independent of both Wenyan, the classical poetical language and Baihua, the  Vernacular Chinese that had been more or less formalized by the previous  literary works, where poetic imagination is at ease, and often at its best. A  person without a literary appreciative capability would always feel confused  and troubled confronting a &ldquo;misty&rdquo; poem, while one with it would only feel  inspired and gratified. <br>
  &nbsp; Although most  Misty poets had seldom been abroad before winning themselves the title as a  poet, their works are found to be very Westernized. &ldquo;The best example to  indicate the similarity between New Chinese Poetry and Western poetry is Misty  Poetry, which appeared in China during the 1970s.&rdquo;<a href="#_ftn35" name="_ftnref35" title=""><sup>35</sup></a> Shu Ting, who was found to be following Western poetics to a great extent, is  one of the most popular Misty Poets. &ldquo;The majority of critical discussions that  Shu Ting&rsquo;s poems are mainly influenced by the West&hellip; Some papers state that the  poetical techniques of modern European Romanticism, Symbolism and Imagism can  be found in Shu Ting&rsquo;s most excellent works&hellip; Other papers declare that,  concerning the matters of Form, Theme and Methods of Expression, Shu Ting  deliberately imitated the Western Poets&hellip;&rdquo;<a href="#_ftn36" name="_ftnref36" title=""><sup>36</sup></a> In fact misty poetry is found to be characterized by the use of Western writing  skills and poetics that were and are extremely diverse and various. <br>
  &nbsp; Compared with  their predecessors in the first half of the twentieth century who had  personally stayed in the West for a fairly long period of time, many misty  poets based their acceptance of Western poetics on the basis of Chinese  language through their reading experience in Chinese, mainly through  translations. The major disadvantage of this is that they had unavoidably  missed a lot of poetic beauty of the original works, and the major advantage is  the they accepted Western influence in an inwardly digested way, in other  words, they would accept whatever was beneficial for their poetical practice,  even to the extent of intuitive acquisition, which prevented them from adopting  something that is not consistent with the Chinese language, such as directly  applying Western languages into their poems. <br>
              The  years around 1990 are generally considered as the end of the poetical period of  Misty Poetry as well as the beginning of the new period of the1990s----&ldquo;a new  age of Individual Creation<em>.</em>&rdquo;<a href="#_ftn37" name="_ftnref37" title=""><sup>37</sup></a> The so-called Individual Creation tendency, which appeared in embryo during the  Poetry Exhibition in Shenshen in 1986, refers to the fact that every single  poet is seen as writing in his or her own particular way. <br>
  &nbsp; It might be on  account of the freer social atmosphere and the great success of the Misty Poets  (millions of copies of their works were sold out), that there came an age of  profuse production of poetry as well as multiplying poetical schools around the  turn of 1990, which was topped by the exhibition held by the Shenzhen Youth  Newspaper and Poetry Newspaper in 1986. Around eighty different poets&rsquo; schools  and poetical dogmas were presented during this exhibition, and the total  schools in China are believed to have been  more than double that number. As the so many &ndash;isms and schools were making many  experiments, radical or moderate, of which some were failures, others  successes, the poetical characteristic of the era of the1990s, an age of no  poetical authority, gradually took its form. The many schools and &ndash;isms made  the pro-classification critics feel very confused, dizzy and desperate.  &ldquo;Post-Misty poetry is a kind of blend of New Classicism, New Romanticism,  Modernism, etc. None of them can be classified into any certain school.&rdquo;<a href="#_ftn38" name="_ftnref38" title=""><sup>38</sup></a>&nbsp; <br>
  &nbsp; The date that  Haizi (&#28023;&#23376;), a prominent new Chinese  poet, who committed suicide on the Shanhai Guan railway over Easter in 1989,  chose for his self-termination is a further sign of the Western features within  the New Chinese poets of the 1990s. In a book entitled as <em>The Selections of the Jottings of Contemporary Chinese Poets</em>,<a href="#_ftn39" name="_ftnref39" title=""><sup>39</sup></a> all the thirty-five poets frequently quote foreign poets, critics, philosophers  or experts while few mention any Chinese poet or critic, either classical or  modern. And in another poem-collection, <em>A  Poem-Selection of the Most Popular Chinese Poets in the 1990s,</em><a href="#_ftn40" name="_ftnref40" title=""><sup>40</sup></a> poets such as Xi Chuan &#65288;&#35199;&#24029;&#65289;, Bai Hua &#65288;&#26575;&#26726;&#65289;, Yi Hai &#65288;&#20041;&#28023;&#65289;, Lin Dongwei &#65288;&#26519;&#19996;&#23041;&#65289;, Mo Yaping &#65288;&#33707;&#38597;&#24179;&#65289;, BC-1 and others graduated  from Foreign Language Departments in Universities in China; other poets also  have a specific relationship with the West, for example: Wang Jiaxin &#65288;&#29579;&#23478;&#26032;&#65289; stayed in England for two  years and travelled in Europe widely; Lu De&ndash;an &#65288;&#21525;&#24503;&#23433;&#65289; stayed in the United States from 1991 to 1994; Liang  Xiaoming (&#26753;&#26195;&#26126;) claimed to have  begun writing  poems after he had been greatly moved by reading Walt Whitman&rsquo;s <em>Leaves of Grass</em>; Hei Dachun&rsquo;s &#65288;&#40657;&#22823;&#26149;&#65289; most favorite works are R. Tagore&rsquo;s <em>Stray Birds </em>and the lyrics of George Gordon Byron and Alexander Pushkin; Ma Li&rsquo;s &#65288;&#39532;&#33673;&#65289; literary creeds are Aestheticism and Mysticism; Nie  Pei &#65288;&#32834;&#27803;&#65289;said the first book he read  was Ernest Hemingway&rsquo;s <em>The Old Man and the Sea</em> and the first poet he became familiar with  was William Shakespeare.<br>
  &nbsp; One particular  poetry group, the Chinese Language-Poetry Group that has recently obtained some  attention at home and abroad, at the very beginning of their manifesto,  declared: &ldquo;We object to localist and ethnocentric----in a word, to  nationalistic writings. Our writings are of the world (an open box): through  writing, we hold conversation with contemporary art of global significance and with  modern Western art in particular.&rdquo;<a href="#_ftn41" name="_ftnref41" title=""><sup>41</sup></a> This manifesto was publicized in 1988, ten years after Bruce Andrews and  Charles Bernstein initiated their journal L-A-N-G-U-A-G-E in February 1978.  However, according to Zhang Ziqing (&#24352;&#23376;&#28165;), a leading figure who  specializes in American Literature in China, American Language Poetry was not  introduced into China until the summer of 1990.<a href="#_ftn42" name="_ftnref42" title=""><sup>42</sup></a> It is not important whether the Chinese Language-Poetry Group was shaped under  the influence of their American counterpart or not; the fact that they are so  eager to &ldquo;hold conversation with the West&rdquo; speaks for itself. The following  poem &ldquo;Flowers of Two Persons&rdquo;, written by the leading figure of the small Chinese  Language-Poetry Group Che Qianzi (&#36710;&#21069;&#23376;), might shed more light on  this issue:&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Flowers in two lips, grow,<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Some red words, like two roses.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Two roses, <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  One is taller than the other, above blue light,<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  The slightly shorter one leans<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Against its lover&rsquo;s shoulders, murmuring;</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  China pink, golden;</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Flowers blooming in eyes, for rooms at night,<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Pave carpet, purple meridian and parallel lines;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  The planet suspended between two bodies,<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Blooming more violets than sea water. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  One warship of violet, <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Another warship of violet, gold-spot-jumping<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Sunlight, the flower centre of violets, the intersects in <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  The carpet, like two persons with hands crossed<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Embracing for the past. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  The gold timepieces in the tender wool of the purple carpet,<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  As if having China pink at hand, she seizes  time.</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Two persons, having relationship with flowers,<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Having been years. At the intersects of<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Growing and blooming: embracing for brains.<a href="#_ftn43" name="_ftnref43" title=""><sup>43</sup></a><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  (&#20004;&#20010;&#20154;&#30340;&#33457; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#33457;&#22312;&#20004;&#29255;&#22068;&#21767;&#38388;&#65292;&#25104;&#38271; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#19968;&#20123;&#32418;&#33394;&#30340;&#35805;&#65292;&#20687;&#20004;&#26525;&#29611;&#29808;&#12290; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#20004;&#26525;&#29611;&#29808;&#65292; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#19968;&#26525;&#39640;&#36807;&#19968;&#26525;&#65292; &#22312;&#32511;&#20809;&#19978;&#38754;&#65292; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#37027;&#31245;&#30702;&#30340;&#19968;&#26525;&#36276;&#22312; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#29233;&#20154;&#32937;&#22836;&#31363;&#31363;&#31169;&#35821;&#65307; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#30707;&#31481;&#65292;&#37329;&#40644;&#65307; </p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#33457;&#22312;&#30524;&#30555;&#20013;&#24320;&#25918;&#65292;&#20026;&#22812;&#26202;&#30340;&#25151;&#38388;&#65292; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#38138;&#19978;&#22320;&#27631;&#65292;&#32043;&#33394;&#30340;&#32463;&#32447;&#32428;&#32447;&#65307; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#20004;&#20010;&#20154;&#36523;&#20307;&#38388;&#24748;&#28014;&#30340;&#26143;&#29699;&#19978;&#65292; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#24320;&#25918;&#20986;&#27604;&#28023;&#27700;&#26356;&#22810;&#30340;&#32043;&#32599;&#20848;&#12290; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#19968;&#33368;&#32043;&#32599;&#20848;&#30340;&#33328;&#33337;&#65292;&#37329;&#28857;&#23376;&#36339;&#36291;&#30340; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#38451;&#20809;&#65292;&#32043;&#32599;&#20848;&#30340;&#33457;&#24515;&#65292;&#22320;&#27631;&#19978;&#30340; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#20132;&#21449;&#28857;&#65292;&#20223;&#20315;&#20004;&#20010;&#20154;&#20132;&#21449;&#30528;&#25163; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#20026;&#36807;&#21435;&#32780;&#25317;&#25265;&#12290; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#32043;&#22320;&#27631;&#19978;&#28201;&#26580;&#30340;&#32650;&#27611;&#37324;&#30340;&#37329;&#40644;&#30340;&#38047;&#34920;&#65292; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&#22914;&#30707;&#31481;&#22312;&#25163;&#65292;&#22905;&#25235;&#20303;&#20102;&#26102;&#38388;&#12290; <br>
  &nbsp;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#20004;&#20010;&#20154;&#65292;&#19982;&#33457;&#26377;&#20851;&#65292; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#23601;&#26377;&#20102;&#24180;&#22836;&#12290;&#25104;&#38271;&#19982;&#24320;&#25918;&#30340; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &#20132;&#21449;&#28857;&#19978;&#65306;&#20026;&#22836;&#33041;&#32780;&#25317;&#25265;&#12290;) <br>
  &nbsp;<br>
  &nbsp; To the  majority of Chinese readers, this poem is of no reasonable sense, more foreign  than foreign (some Chinese readers have in some way developed a habit of  describing anything difficult to understand as foreign), even though there  indeed exists a magic beauty that can be appreciated only by a few, whose power  of imagination can rise to the challenge beyond the definition of Samuel Taylor  Coleridge (1772-1834), to recognize and appreciate a poetic beauty created from  seemingly unrelated and incoherent images, without declining into the work of  mere low-grade fancy (to borrow Coleridge&rsquo;s term).<a href="#_ftn44" name="_ftnref44" title=""><sup>44</sup></a><br>
  &nbsp; <br>
  <strong>V. New Chinese  Poetry: A Melting Pot for Traditional Chinese Poetry and Western Poetry</strong></p>
            <p>In  traditional China, poetry enjoyed an  extremely high social status. Almost all emperors in China&rsquo;s history would accept  training in reading, appreciating and actually composing poetry. And some of  them were good poets; one outstanding example is Li Yu (&#26446;&#29020;, 937-978), who composed many  wonderful poems. Mao Zedong, the leader of China in the twentieth century  should certainly be considered as one of the best poets in China throughout the twentieth  century. In China, especially in traditional China, people all pay high  respect to a person who could write good poems. Poetry is actually the heart of  Chinese culture, or to say, the spirit of Chinese culture. <br>
  &nbsp; In the West,  poetry seems to have belonged more to the people than to the noble class who  comparatively were more interested in wealth and the military field. In Europe,  there had been endless warfare throughout its written history, much more than  that of China before the middle of the  nineteenth century. The unification of China as a large nation at a very  early stage was perhaps the most important reason why the Chinese could enjoy  more peace than their European counterparts in history. And the rich tradition  of poetry in China undoubtedly helped to stabilize traditional Chinese  societies, reinforcing their stability to a great extent, until the ruling  class became so thoroughly decayed that it would be defeated or replaced within  a couple of months or years. <br>
  &nbsp; The difference  of the cultural and social backgrounds between Chinese and Western poetry  granted them very different spirits in tradition. In China, poetry was generally of  the ruling classes and most poets were a part of them, and Western poetry was  more of the people and more poets were plain persons; thus Chinese poetry was  mostly for the ruling class, having an aristocratic tendency while Western  poetry was more of the people, having a very strong rebellious tradition. John  Milton in England should be a very good representative of the rebellious  poetical spirit, while in China, beginning from Qu Yuan, a poet who would at  most complain, not to hate, never to rebel in his poems. However, the spirit of  Chinese poetical tradition suddenly changed to be very rebellious at the  beginning of the twentieth century when New Chinese Poetry took form under the  direct influence of the West. Contemporary Chinese poets should be among the  most rebellious spirits in China, probably throughout the  world as well. <br>
  &nbsp; Because of the  social difference of Chinese and Western poetry, Chinese poetry was concerned  more with aesthetics and Western poetry more with ideologies. But this  difference is not very obvious, as there were some opposite evidences on both  sides; it can only be viewed as a difference of degree. However, after the  introduction of Western poetry into China, New Chinese Poetry  suddenly became very ideological, concerned very much with social and political  issues. In fact, the famous Misty Poetry Movement was so political that some  critics would even address Misty Poetry as Political Poetry. <br>
  &nbsp; But the strong  appetite for beauty is exactly the same in both Chinese and Western poetics;  this is probably why a beautiful Chinese poem can always find readers in the  West and the same in the other way around. &ldquo;Inasmuch as we are all members of one  human race, Chinese culture is our culture. Poetry is the heart of Chinese  culture. The heart of Chinese poetry beats in us, too.&rdquo;<a href="#_ftn45" name="_ftnref45" title=""><sup>45</sup></a> This convincingly demonstrates that Chinese poetry and Western  poetry can indeed learn and benefit from each other. In fact, foreign culture  has long been a rich source for Chinese poetry. &ldquo;The only other force that has had as much effect on  Chinese poetry as the folk song is foreign literature. As far back as the Han  Dynasty (202 B.C.&mdash;A.D. 220), military tunes from the non-Chinese tribes in the  north and Northwest enriched Chinese poetry. And throughout the centuries,  foreign verse forms and influences, like the indigenous folk song, have  repeatedly brought fresh blood into the main artery of Chinese poetry.&rdquo;<a href="#_ftn46" name="_ftnref46" title=""><sup>46</sup></a>&nbsp; Nevertheless, this does not guarantee that  the application of a blind learning approach would not do considerable harm. It  is thus clear that attempts at importing Western poetics themselves are certainly highly  recommendable if only much of them had not been carried out by some  self-belittled minds with a method of taking-without-digesting and  creating-just-for-show. Learning is good, but only by digestion and followed  with a reasonable creation. Qi Baishi (&#40784;&#30333;&#30707;), a famous Chinese painter,  once said to his admirers: &ldquo;It is good to learn from me, yet it is fatal to copy me.&rdquo;<a href="#_ftn47" name="_ftnref47" title=""><sup>47</sup></a> &ldquo;Never to copy&rdquo; is probably the first rule in any trans-cultural learning. <br>
  &nbsp; Throughout  Chinese history, there was no lack of successful experiences of learning from  foreign cultures. The acceptance of foreign influence can always contribute to  the development of Chinese literature and language. Even the Four Tones of  Chinese language was shaped under foreign influence. Chen Yinke (&#38472;&#23493;&#24682;) in his &ldquo;Four Questions  about the Four Tones&rdquo; said that &ldquo;the Four Tones were created by some Chinese  monks and scholars who knew music well in Qi and Liang of Nan Dynasty, being  inspired by Xiyu [it refers to Ancient India and the nations around it in those  days] monks&rsquo; ways of reading Jing [the Buddhist books].&rdquo;<a href="#_ftn48" name="_ftnref48" title=""><sup>48</sup></a> There has been a very strong voice in the poet&rsquo;s circle insisting that the best  way to prosper Chinese poetry is to &ldquo;blend Chinese and Western Culture  together&rdquo;, even as early as in the late nineteenth century. &ldquo;The giant of  Poetic Revolution, Huang Zunxuan, had much the same views as Liang Qichao,  i.e., they both considered that the way out for Chinese poetry is to blend  Chinese and Western culture together.&rdquo;<a href="#_ftn49" name="_ftnref49" title=""><sup>49</sup></a> However, before any blending, the following few points should at least be done:  a) a good understanding of oneself; b) a good understanding of the other; c) a  good understanding of their differences and similarities; d) a good  understanding of the positive and negative consequences of their exchanges.  Besides, the most desirable is that the person himself should be an ingenious  POET! <br>
  &nbsp; There does  exist a chance for New Chinese Poets to bring their works into great success,  if they would choose to learn form both Traditional Chinese Poetry and Western  poetry in appropriate ways. &ldquo;In June of 1923, in the paper of &lsquo;The Local Colour of <em>The Goddess</em>&rsquo;, Wen Yiduo said: &lsquo;I am  always thinking that New Chinese Poetry should be different from not only  Traditional Chinese Poetry, but also from Western  poetry. That is to say: New Chinese Poetry should not remain purely local, yet  it should keep its local character; it should not be totally Western, yet it  should absorb Western poetic advantages. New Chinese Poetry should be the son  produced by a marriage of Chinese and Western poetics.&rsquo;&rdquo;<a href="#_ftn50" name="_ftnref50" title=""><sup><sup>50</sup></sup></a> And some famous Western scholars have also stated their expectation of  combining the advantages of Chinese and Western cultures together. &ldquo;We have not yet realised  that the quality of the world-life that our children are to inherit depends quite  as much upon the character of the new China as upon any other one factor we can  think of. If we were wiser we would make incomparably greater efforts to see  that the values we most believe in came to the Chinese as freely and by as good  channels as we could devise. &hellip; Only those who have had the opportunity of  working with Chinese students know how great their powers and how needlessly  entangling and frustrating their difficulties are. A new age is being created  in this wedding of East and West. Those to whom history gives some faith in  humanity will envy the Chinese the richness of the joint heritage which will be  theirs.&rdquo;<a href="#_ftn51" name="_ftnref51" title=""><sup>51</sup></a> I.A. Richards was a very famous British scholar who had worked in China. It is not likely that he  should say anything without a profound meditation. <br>
  &nbsp; However, no  matter how strongly would people like to blend Chinese and Western cultures  with poetry as the beating heart, this marriage is certainly not like one  between two lovely persons in a warm church.</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <div>
              <div id="ftn1">
                <p><a href="#_ftnref1" name="_ftn1" title="">1.</a> Ren&eacute; Wellek, <em>A History of Modern  Criticism</em><em>: 1750-1950</em> (Cambridge: Cambridge University Press, 1981, 4 Volumes), Vol. 2, p. 230. </p>
              </div>
              <div id="ftn2">
                <p><a href="#_ftnref2" name="_ftn2" title="">2.</a> Joseph Needham: <em>The <em>Grand Titration</em>: Science and Society in East and West </em>(<em>London</em>: <em>George Allen &amp; Unwin</em>,<em>1969),</em> pp. 149-154.</p>
              </div>
              <div id="ftn3">
                <p><a href="#_ftnref3" name="_ftn3" title="">3.</a> Hugh Kenner, <em>The Pound Era</em> (London: Faber and Faber, 1972), p.231.</p>
              </div>
              <div id="ftn4">
                <p><a href="#_ftnref4" name="_ftn4" title="">4.</a> Zhaoming Qian, <em>Orientalism  and Modernism: The Legacy of </em><em>China</em><em> in Pound and  Williams</em>. (Durham: Duke University  Press, 1995), pp. 3-4 (Prologue).</p>
              </div>
              <div id="ftn5">
                <p><a href="#_ftnref5" name="_ftn5" title="">5.</a> Zhaoming Qian, <em>Orientalism  and Modernism: The Legacy of </em><em>China</em><em> in Pound and Williams</em>. (Durham: Duke University Press, 1995), p. 137.</p>
              </div>
              <div id="ftn6">
                <p><a href="#_ftnref6" name="_ftn6" title="">6.</a> Howard Chua-eoan, &ldquo;Empires on the Wane&rdquo;, <em>The Times</em>, October 21, 1991, p.7. </p>
              </div>
              <div id="ftn7">
                <p><a href="#_ftnref7" name="_ftn7" title="">7.</a> <em>The Legacy of </em><em>China</em>, ed. Raymond Dawson (Oxford: Clarendon Press, 1964), pp. 80-81<em>.</em></p>
              </div>
              <div id="ftn8">
                <p><a href="#_ftnref8" name="_ftn8" title="">8.</a> Jacques Gernet, <em>A  History of Chinese Civilization</em>, trans. J. R. Foster (Cambridge: Cambridge  University Press, 1982), p. 20.</p>
              </div>
              <div id="ftn9">
                <p><a href="#_ftnref9" name="_ftn9" title="">9.</a> Qing Mansu, <em>Emerson and </em><em>China</em><em>: A Retrospect of  Individualism</em> (Beijing: Joint Publishing Company  Limited, 1996), p. 3.</p>
              </div>
              <div id="ftn10">
                <p><a href="#_ftnref10" name="_ftn10" title="">10.</a> Hushi, <em>Hu Shi&rsquo;s Talks on Literary Changes</em> (Shanghai: Shanghai Classic  Publishing House,1999), p. 60.</p>
              </div>
              <div id="ftn11">
                <p><a href="#_ftnref11" name="_ftn11" title="">11.</a> Hushi, <em>Hu Shi&rsquo;s Talks on Literary Changes</em> (Shanghai: Shanghai Classic  Publishing House,1999), p. 93. </p>
              </div>
              <div id="ftn12">
                <p><a href="#_ftnref12" name="_ftn12" title="">12.</a> <em>The Historical Trace of Chinese Modern  Literature</em>, ed. Shanghai  Bookshop Publishing House (Shanghai: Shanghai Bookshop Publishing House, 1999),  p. 312.</p>
              </div>
              <div id="ftn13">
                <p><a href="#_ftnref13" name="_ftn13" title="">13.</a> <em>The Historical Trace of  Chinese Modern Literature</em>, ed. Shanghai Bookshop  Publishing House (Shanghai: Shanghai Bookshop Publishing House, 1999), p. 61.</p>
              </div>
              <div id="ftn14">
                <p><a href="#_ftnref14" name="_ftn14" title="">14.</a><em> The Historical Trace of Chinese Modern  Literature</em>, ed. Shanghai Bookshop  Publishing House (Shanghai: Shanghai Bookshop Publishing House, 1999), pp. 4-5.</p>
              </div>
              <div id="ftn15">
                <p><a href="#_ftnref15" name="_ftn15" title="">15.</a> Hu Shi, <em>Hu Shi&rsquo;s Works</em> (Shanghai:  Shanghai East Asia Bookshop, 1929), p. 7. Hu Shi&rsquo;s eight points for reforming  Chinese literature are: 1. whatever  said should mean; 2. not to  imitate the ancient; 3. pay  attention to grammar; 4. no false  emotion; 5. no clich&eacute;; 6 .no idioms; 7. no antithesis; 8. not to  avoid the vulgar language. </p>
              </div>
              <div id="ftn16">
                <p><a href="#_ftnref16" name="_ftn16" title="">16.</a> Hushi, <em>Hu Shi&rsquo;s Talks on Literary Changes</em> (Shanghai: Shanghai Classic  Publishing House,1999), p. 205.</p>
              </div>
              <div id="ftn17">
                <p><a href="#_ftnref17" name="_ftn17" title="">17.</a> Hushi, <em>Hu Shi&rsquo;s Talks on Literary Changes</em> (Shanghai: Shanghai Classic  Publishing House,1999), p. 45.</p>
              </div>
              <div id="ftn18">
                <p><a href="#_ftnref18" name="_ftn18" title="">18.</a> I. A. Richards &ldquo;The Chinese Renaissance&rdquo;, <em>Scrutiny</em> (a quarterly review), edited by  L.C. Knights and Donald Culver, London. Vol. I., No. 2., September/1932. p. 102. </p>
              </div>
              <div id="ftn19">
                <p><a href="#_ftnref19" name="_ftn19" title="">19.</a> Wang Guowei, <em>Comments on Human Poetry</em>,  trans. and annot. by Teng Xianhui. (Changchun: Jilin Literary History  Publishing House, 1999), p. 86.</p>
              </div>
              <div id="ftn20">
                <p><a href="#_ftnref20" name="_ftn20" title="">20.</a> Wang Guowei, <em>Comments on Human Poetry</em>,  trans. and annot. by Teng Xianhui. (Changchun: Jilin Literary History  Publishing House, 1999), p. 86.</p>
              </div>
              <div id="ftn21">
                <p><a href="#_ftnref21" name="_ftn21" title="">21.</a> Hushi, <em>Hushi&rsquo;s Talks on  Literary Changes</em>. (Shanghai: Shanghai Classic Publishing House, 1999),<br>
                  &nbsp;p. 259.</p>
              </div>
              <div id="ftn22">
                <p><a href="#_ftnref22" name="_ftn22" title="">22.</a>&nbsp; Hushi, &ldquo;Discussion  on Literary Reformation&rdquo;, <em>Hu  Shi&rsquo;s Work Collec</em><em>tions </em>(Volume 1)  (Shanghai: Shanghai East Asia Library, 1921), p. 7.</p>
              </div>
              <div id="ftn23">
                <p><a href="#_ftnref23" name="_ftn23" title="">23.</a> Pan  Songde, <em>Forty Poetical Schools in Modern  Chinese Poetry</em>, (Chongqing: Chongqing Publishing House,  1991&nbsp; ) p. 29.</p>
              </div>
              <div id="ftn24">
                <p><a href="#_ftnref24" name="_ftn24" title="">24.</a> Zhang Tongdao, <em>An  Exploration: On </em><em>Modern</em><em>Chinese</em><em>Poetry</em><em>Schools</em><em> in the Twentieth Century</em> (Hefei: Anhui Education Publishing House, 1998), pp.  105-106. [To compare: Ezra Pound, &ldquo;A Retrospect&rdquo;<em>,  Literary Essays of Ezra Pound</em>, ed. by T.  S. Eliot (London: Faber and Faber Limited, mcmliv ),  pp. 2-14.]&nbsp; </p>
              </div>
              <div id="ftn25">
                <p><a href="#_ftnref25" name="_ftn25" title="">25.</a> Huang Xiuji, <em>The History of  the development of Modern Chinese Literature</em> (Beijing: Chinese Youth  Publishing House, 1997), pp. 81-94.</p>
              </div>
              <div id="ftn26">
                <p><a href="#_ftnref26" name="_ftn26" title="">26.</a> Wen Yiduo, &ldquo;The Local Colors of Goddess.&rdquo; Wen Yiduo,<em> Wen Yiduo&rsquo;s Poems</em>, ed. by Lan Dizhi.  (Hangzhou: Zhejiang Literature and Art Publishing House, 1995), pp. 406-407.</p>
              </div>
              <div id="ftn27">
                <p><a href="#_ftnref27" name="_ftn27" title="">27.</a> Guo Mo-Jo [Guo  Moruo], <em>Selected  Poems from The Goddesses</em>, trans. by John Lester and A.C. Barnes (Peking:  Foreign Languages Press, 1978), p. 7.</p>
              </div>
              <div id="ftn28">
                <p><a href="#_ftnref28" name="_ftn28" title="">28.</a> Guo Moruo, <em>The Goddesses </em>(Beijing:  People&rsquo;s Literature Publishing House, 1998), p. 66 </p>
              </div>
              <div id="ftn29">
                <p><a href="#_ftnref29" name="_ftn29" title="">29.</a> Guo Mo-Jo, trans. by John Lester and A. C.  Barnes, <em>Selected Poems from The Goddesses</em>.  (Peking: Foreign Languages Press, 1978), p. 1  (Foreword).</p>
              </div>
              <div id="ftn30">
                <p><a href="#_ftnref30" name="_ftn30" title="">30.</a> Cheng Houcheng, <em>A  Memorization of Li Jinfa</em> (Shanghai: East Publishing Centre, 1998), pp.  53-56.</p>
              </div>
              <div id="ftn31">
                <p><a href="#_ftnref31" name="_ftn31" title="">31.</a> Cheng Houcheng, <em>A  Memorization of Li Jinfa</em> (Shanghai: East Publishing Centre, 1998), pp.  29-148.</p>
              </div>
              <div id="ftn32">
                <p><a href="#_ftnref32" name="_ftn32" title="">32.</a> Zhu Ziqing, <em>The Prefaces and  Comments Written by Zhu Ziqing</em> (Beijing: Joint Publishing Company Limited, 1983), p. 99.</p>
              </div>
              <div id="ftn33">
                <p><a href="#_ftnref33" name="_ftn33" title="">33.</a> Zhang Dexiang, <em>The History of the Changes  of Realism in Modern Times </em>(Beijing: Academic Social Science Publishing  House, 1997), p. 189.</p>
              </div>
              <div id="ftn34">
                <p><a href="#_ftnref34" name="_ftn34" title="">34.</a> <em>Selected Poems by Gu Cheng</em>, ed. by Sean  Golden and Chu   Chiyu, trans. by John Cayley and  others. (Hong Kong: The Chinese University of Hong Kong, 1990), p. 168.</p>
              </div>
              <div id="ftn35">
                <p><a href="#_ftnref35" name="_ftn35" title="">35.</a> Lu Jin, <em>Chinese Modern Poetics</em> (Chongqing: Chongqing Publishing House, 1991), p. 7.</p>
              </div>
              <div id="ftn36">
                <p><a href="#_ftnref36" name="_ftn36" title="">36.</a> Hai Bing, &ldquo;A Summary of the discussions on Shu Ting&rsquo;s Creation held by Fujian  Literature and Art&rdquo;, <em>A Selection of the  Contending Poems Published&nbsp; in the New  Era of China</em><em>,</em> ed. by Ding  Guocheng (Changchun: Era Publishing House, 1996), p. 64.</p>
              </div>
              <div id="ftn37">
                <p><a href="#_ftnref37" name="_ftn37" title="">37.</a> Yang Ke,<em> Selected Poems of the Most Popular Poets in 1990s</em>, ed., (Guilin:  Lijiang Publishing House, 1999), p. 3 (Preface).</p>
              </div>
              <div id="ftn38">
                <p><a href="#_ftnref38" name="_ftn38" title="">38.</a> Zhang Tongdao, <em>An Exploration: On </em><em>Modern</em><em>Chinese</em><em>Poetry</em><em>Schools</em><em> in the 20th Century</em> (Hefei: Anhui Education Publishing House, 1998), p. 571.</p>
              </div>
              <div id="ftn39">
                <p><a href="#_ftnref39" name="_ftn39" title="">39.</a> Wang Jianzhao, <em>The Jottings of  Contemporary Chinese Poets</em> (Beijing: Chinese Social Science Publishing  House, 1998).</p>
              </div>
              <div id="ftn40">
                <p><a href="#_ftnref40" name="_ftn40" title="">40.</a> Yang Ke, A Poems-Selection of the  Most Popular Chinese Poets in the 1990s, ed. (Guilin: Lijinag Publishing House,  1999). </p>
              </div>
              <div id="ftn41">
                <p><a href="#_ftnref41" name="_ftn41" title="">41.</a> <em>Original: Chinese language-Poetry Group</em>,  trans. by Jeff Twitchell (Brighton: Parataxis Editions, 1994), p. 98.</p>
              </div>
              <div id="ftn42">
                <p><a href="#_ftnref42" name="_ftn42" title="">42.</a> Zhang Ziqing and Yunte Hung,<em> Selected Language Poems by Charles Bernstein, Hank Lazer, James Sherry</em>,  trans., (Chengdu: Sichuan Literature and Art Publishing House, 1993), p. 4  (Preface).</p>
              </div>
              <div id="ftn43">
                <p><a href="#_ftnref43" name="_ftn43" title="">43.</a> <em>Poetry Journal</em>, July, 2000.</p>
              </div>
              <div id="ftn44">
                <p><a href="#_ftnref44" name="_ftn44" title="">44.</a> &ldquo;Chapter 13. On the imagination, or esemplastic power&rdquo;, <em>The Collected Works of Samual Taylor  Coleridge. 7. Biographia Literaria</em>, ed. by James Engell  and W. Jackson Bate (Princeton [New Jersey]: Princeton University Press, 1983), pp. 295-306.</p>
              </div>
              <div id="ftn45">
                <p><a href="#_ftnref45" name="_ftn45" title="">45.</a> Greg Whincup, <em>The  Heart of Chinese Poetry</em> (New York: Anchor Press, 1987) p. vii (Preface).</p>
              </div>
              <div id="ftn46">
                <p><a href="#_ftnref46" name="_ftn46" title="">46.</a> Kai-yu Hsu,<em> Twentieth Century Chinese Poetry</em>, trans. and ed., (New York: Anchor Books  Doubleday &amp; Company, Inc., 1963), p. xii.</p>
              </div>
              <div id="ftn47">
                <p><a href="#_ftnref47" name="_ftn47" title="">47.</a> Lu Jin, <em>Chinese Modern  Poetics</em> (Chongqing: Chongqing Publishing House, 1991), p. 371.</p>
              </div>
              <div id="ftn48">
                <p><a href="#_ftnref48" name="_ftn48" title="">48.</a> Hu Yingjian, <em>Alone in a </em><em>High</em><em>Building</em><em>: Chen Yinge</em> (Jinan: Shangdong Painting Newspaper Publishing  House, 1998) pp. 39-40. </p>
              </div>
              <div id="ftn49">
                <p><a href="#_ftnref49" name="_ftn49" title="">49.</a> <em>The Historical Trace of  Chinese Modern Literature</em>, ed. Shanghai Bookshop  Publishing House (Shanghai: Shanghai Bookshop Publishing House, 1999), p. 16.</p>
              </div>
              <div id="ftn50">
                <p><a href="#_ftnref50" name="_ftn50" title="">50.</a> Tang Hongdi, <em>The World of the Poet Wen  Yiduo</em>. (Shanghai: Xuelin Publishing House, 1996), p. 194.</p>
              </div>
              <div id="ftn51">
                <p><a href="#_ftnref51" name="_ftn51" title="">51.</a> I. A. Richards, &ldquo;The  Chinese Renaissance&rdquo;, in <em>Scrutiny</em>: a  quarterly review, edited by L.C. Knights and Donald Culver, September/1932,  Vol. I. No. 2. London, p. 103.</p>
              </div>
            </div>
<p>&nbsp;</p><P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
