<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue7/menu_issue7.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue7/aleksandar_petrov/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">The Blue Butterfly Effect <span class="texto2">by <a href="../../issue7/aleksandar_petrov/bio.php" class="link3">Aleksandar Petrov</a></span><br>Translated by <a href="../../issue7/vera_radojevic/bio.php" class="link3">Vera V. Radojevi&#263;</a></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           &nbsp;<br>
             <p>In the  mid-eighties, at the site of the Nazi massacre on the outskirts of Kragujevac  in Serbia, a blue  butterfly settled on the left hand of the English poet Richard Berengarten,  then known as Burns.<a href="#_ftn1" name="_ftnref1" title=""><sup>1</sup></a> A quarter of a century  earlier, Edward Lorenz, an American scientist and meteorologist living in Boston, had discovered a phenomenon that he termed &lsquo;the butterfly effect&rsquo;. Lorenz showed how changes of small proportions in one set of circumstances or conditions are capable of  influencing phenomena elsewhere on a much larger scale. Modern chaos theory is  based on this observation, because what is conventionally called chaos originates in minute changes that turn out to have unforeseen  consequences. Lorenz illustrated his theory with a picturesque example: a  butterfly fluttering its wings in Brazil can influence a  hurricane in Texas (Lorenz 1963  &amp; 1965). &nbsp;</p>
          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <p>Of course, the concept of  chaos in physics is rather different from the usage of the same word, and the  notions that go with it, in everyday language. For one thing, the scientific  concept highlights how the relationship between cause and effect is  considerably more complex than classical physicists believed. For another, it  interrogates long-term predictions based on simplistic understandings of the  cause-effect relationship. </p>
            <p>The  fact that, according to the theory, a chaotic system may develop in a manner  which is by no means &ldquo;chaotic&rdquo; in any conventional sense but, rather, appears  to be &ldquo;smooth and harmonious&rdquo;, is outstandingly confirmed by &lsquo;the butterfly&rsquo;  effect in the case of Richard Berengarten. The landing of the blue butterfly on  the poet&rsquo;s finger brought about unpredictable and far-reaching changes in his  own life and work. Readers of the short autobiographical essay &ldquo;Arijana&rsquo;s  Thread&rdquo; (ITD 73-77) &ndash; a piece that might almost be said to have been speckled  by the powder of a blue butterfly&rsquo;s wings &ndash; will know that this momentary  occurrence was the first in a string of events that eventually led to his  spending three years in a turbulent Yugoslavia, between July 1987 and June  1990. During that time, he married a Yugoslav woman, Jasna Mi&scaron;i&#263;, and fathered  a daughter, Arijana, his third child. In the early years of the 21st  century, Berengarten also published two volumes of poems on Serbian, Yugoslav  and Balkan themes, under the name Richard Burns. These are <em>In a Time of Drought</em> published in Serbian in 2004, two years before  its English publication, and <em>The Blue  Butterfly</em>, also published in 2006, followed by its Serbian version (<em>Plavi leptir</em>) in 2007. These two books not only confirm Berengarten&rsquo;s  reputation as a significant European writer but, in their handling of universal  themes, herald his status as a great poet.&nbsp; </p>
            <p>So,  on a sunny day in May 1985 &ndash; &ldquo;out of the blue&rdquo; as the English would say, or  &ldquo;like a lightning bolt out of a cloudless sky&rdquo;, as the Serbs would have it &ndash; a  blue butterfly, unexpectedly and unpredictably entered Berengarten&rsquo;s life,  occupied a central role in it and became an integral image and symbol for much  of his subsequent poetry. Berengarten and his first daughter, Lara, who at that  time was seventeen years old, caught the butterfly&rsquo;s image for posterity via a  camera lens, as the creature perched on the forefinger of the poet&rsquo;s left hand.  As soon as he returned to Cambridge, Berengarten wrote a  short poem, quickly followed by another. The focus of the first of these, &ldquo;The  blue butterfly&rdquo;, was this left &lsquo;writing hand&rsquo; of his &lsquo;now of a sudden stretched  before me in Serbian spring sunlight&rsquo; &ndash; which he suddenly saw in an entirely  new light: &lsquo;my Jew&rsquo;s hand, born out of ghettos and shtetls [&hellip;], my proud firm  hand, / miraculously blessed by [&hellip;] two thousand eight hundred / martyred men,  women and children&rsquo; (BB 8). The second poem, &ldquo;Nada: hope or nothing&rdquo;, explores  how that winged being of indeterminate gender actually landed on his hand (BB  9).</p>
            <p>In Serbian, the gender of  that tiny airborne guest needed to be made explicit. There was a choice between  the masculine<em> leptir</em> and the feminine<em> leptirica</em>, which is also a  diminutive. Early co-translators of the first of these pieces were the  exceptional poet, Ivan V. Lali&#263;, and Danilo Ki&scaron;, a novelist ranking among the  finest in Europe. In their version, they opted for the  masculine variant.<a href="#_ftn2" name="_ftnref2" title=""><sup>2</sup></a> Actually, when they did so, they could scarcely have envisaged the sheer force  of that blue butterfly&rsquo;s impact &ndash; almost that of a blow, I would suggest &ndash; let  alone how far-reaching its repercussions would be. Still, it is worth  mentioning to English-speaking readers that the word for &lsquo;soul&rsquo; or &lsquo;psyche&rsquo; in  Serbian [<em>du&scaron;a</em>] is feminine, as are those for &lsquo;colour&rsquo; [<em>boja</em>] and  &lsquo;death&rsquo; [<em>smrt</em>].</p>
            <p>The &ldquo;arrival&rdquo; of these two  &ldquo;core&rdquo; poems prompted Berengarten to build up a fuller context for them that  involved historical, cultural, literary and even entomological information; so  that, gradually, an entire superstructure was built up around them. The poet  started by studying historical material on the massacre of October 1941 itself.  He focused on establishing reliable figures for the number of victims which, he  discovered, was just under 2,800, rather than 7,000.<a href="#_ftn3" name="_ftnref3" title=""><sup>3</sup></a>&nbsp; He also set out to find out more details  about those killed, in terms of age, ethnicity and social background. They  included Serbs, Jews and Roma; members of the intelligentsia, workers and  peasants; and a large group of schoolboys of high school age (BB&nbsp; 133-134). Berengarten also explored  information about the perpetrators of the massacre and their own subsequent  trials and sentences at Nuremburg, which turned out to be disproportionately  lenient (BB 128-133 and 141-142). He took pains to find out more about the  poets who had already written about the massacre, especially Desanka Maksimovi&#263;  (BB 135); and he worked tirelessly to establish the exact species of the  fleeting visitant itself (BB 124-5). Inevitably, out of this research, new  poems emerged, and these resulted in a sequence of seven poems that included  the first two. Six further sequences were developed, each also containing seven  poems.</p>
            <p>The result of this  undertaking is <em>The Blue Butterfly</em>,  first published in Cambridge in 2006 under the name Burns. In addition  to its forty-nine poems, the book contains poignant photographs, plus several  of the victims&rsquo; last messages (BB 114-121), followed by a &ldquo;Postscript&rdquo; and  notes which, together, amount to a genuinely scholarly study of the Kragujevac massacre (BB 123-139). The book  also incorporates a good deal of valuable information about the making of the  poems themselves and their historical and biographical backgrounds (BB  141-148).</p>
            <p>This is an exceptionally  complex book in a number of ways. The first section is built around the &ldquo;core&rdquo;  of the first two poems mentioned above &ndash; &ldquo;The Blue Butterfly&rdquo; and &ldquo;Nada: hope  or nothing&rdquo; &ndash; which are still the best known of Berengarten&rsquo;s &ldquo;Kragujevac  poems&rdquo;. This part also contains two pieces directly based on documentary  material: &ldquo;Two documents&rdquo; (BB 4-5) and  &ldquo;Don&rsquo;t send bread tomorrow&rdquo; (BB 6-7). Even at the slightest assessment, it has  to be acknowledged that the long making of this book took considerable poetic  stamina, and, as the highest endorsement, it resonates with love for justice  and for humanity. The butterfly, in the guise  of <em>psyche</em>, crowns the whole endeavour as a symbol of rebirth &ndash;  since the butterfly emerges from its cocoon as from a grave.</p>
            <p>In 2007, <em>The Blue Butterfly</em> appeared in Serbian in an outstanding  translation by Vera V. Radojevi&#263;. This edition benefited from a pair of essays  that served as commentaries and epilogues, by the distinguished poets and  essayists Slobodan Rakiti&#263; and Srba Ignjatovi&#263;: the former a one-time President  of the Serbian Writers&rsquo; Association and the latter its incumbent at that time.  Both writers praise the book for its high quality and rank Berengarten&rsquo;s work  as among the finest in contemporary European poetry. They focus, too, on his  other &ldquo;Balkan&rdquo; book, <em>In a Time of</em> <em>Drought</em> (2006), into which the poet adds  detailed commentaries on folklore and mythology. As far as symbolic  interpretations are concerned, however &ndash; of the butterfly itself, the colour  blue, the number seven and aspects such as &ldquo;the forefinger&rdquo; in the culture of  the Serbs and other peoples &ndash; the poet seems to have left these matters to his  critics<em>. </em>This challenge has been  taken up most effectively by Slobodan Rakiti&#263; (Burns 2007: 151-156). </p>
            <p>Among other things, Rakiti&#263; points to a key &ldquo;butterfly&rdquo; connection  between the two books, partly because one of the names for the girls who take  part in the Balkan rainmaking ceremonies is &ldquo;butterflies&rdquo;. This leads him to  conclude that, &lsquo;[i]n a way [&hellip;] the blue butterfly configures the true meaning&rsquo;  of both books and also that &lsquo;[i]t is as if the poet&rsquo;s own identity had merged  with that of the blue butterfly&rsquo;; that is to say, the poet &lsquo;invoked his  butterfly and &ldquo;fell into&rdquo; its power&rsquo;. Significantly, Rakiti&#263; also notes that  their material involves &lsquo;a whole range of associations, objects, meanings,  references, denotations, sounds, quotations and documentary details&rsquo;, and that  in the handling of this material, the poet &lsquo;display[s] a veritably  encyclopaedic command of poetic forms&rsquo; (ibid.: 151). Critics should also be  grateful to Rakiti&#263; for comparing <em>The  Blue Butterfly</em> to the &lsquo;once famous&rsquo; symbolist drama, Maeterlinck&rsquo;s<em> The Blue Bird</em>, which &lsquo;points not  only to the mythical and religious meanings of the colour blue but also to its  poetic and philosophical ones&rsquo; (ibid.: 155).</p>
            <p>It is helpful, too, to  compare these books with other literary works. Srba Ignjatovi&#263; calls <em>The Blue</em> <em>Butterfly </em>a &lsquo;canto&rsquo; [<em>spev</em>] (ibid.: 157) and &lsquo;a great and  impressive memorial&rsquo; (ibid.: 159); George Szirtes calls it &lsquo;epic&rsquo;: &lsquo;Epic poems  are rare. This is one.&rsquo; (BB back cover, first edition). </p>
            <p>Among the makers of such  contemporary cantos and poems, a special place belongs to the great Serbian  poet Vasko Popa. The vast majority of Popa&rsquo;s <em>oeuvre</em> has been translated  into English (see, for example, 1998); and the epic scope of his books has been  extensively explored, especially vis-&agrave;-vis their cyclic structure, by critics  and commentators such as Miodrag Pavlovi&#263; (1964: 139-140), Ivan V. Lali&#263; (1971:  7-28), Aleksandar Petrov (2000: 403-417) and Ronelle Alexander (1985: 26-169). Moreover, two of Popa&rsquo;s best  known books in this genre, <em>Sporedno nebo</em> (<em>Secondary Heaven</em>) and <em>Vu&#269;ja so</em> (<em>Wolf Salt</em>) have a cyclic structure  identical to <em>In a Time of Drought</em> and <em>The Blue Butterfly</em>: seven cycles of  seven poems. Of course, there are both similarities and differences between  these two works of Popa&rsquo;s, just as there are between the two by Berengarten;  but comparison of all four books would certainly provide a fascinating and  worthwhile study. Berengarten himself mentions Popa, who was his personal  friend, among the authors who influenced <em>The  Blue Butterfly</em> (BB &ldquo;Acknowledgements&rdquo;). The second cycle of poems of <em>In  a Time of Drought</em>, &ldquo;For the Green Rider&rdquo;, is dedicated to Popa (ITD 13-19).</p>
            <p>Here, I should like to explore a particular detail in  Popa relating to the number seven, that is, the number both of sets of poems  and of poems in each set. Between 1962 and 1968, while Popa was working on <em>Sporedno nebo</em>, he also compiled an  anthology of medieval Serbian poetry, entitled <em>Jutro misleno</em> [Spiritual Morning, 2008].<strong> </strong>In 1963, he also published a selection of the writings  of Domentijan, an important  Serbian poet of the 13th century. In Popa&rsquo;s afterword to Domentijan,  I noticed an interesting parallel between his own writing and the  &lsquo;unsilenceable poetry of the medieval Serbian &ldquo;goldwinged hymn-writers&rdquo;&lsquo;, as he  called his distant predecessors (Domentijan 1963: 139). As noted by &#272;or&#273;e Trifunovi&#263; in his preface to a book of  Domentijan&rsquo;s writing, one of this Serbian writer&rsquo;s favourite readings  was &ldquo;&Scaron;estodnev&rdquo; [The Six Days], compiled by the eleventh century Bulgarian scholar  John Exarch (ibid. 1963: 17). This text tells us not only that there are seven  heavens in the sky but that these are like &lsquo;seven circles, over each of which  seven stars are distributed [&hellip;] conjoined in such a way that one [circle] leans  against the other&rsquo; (ibid.1963: 25). Popa&rsquo;s <em>Wayside  Heaven</em> is an absurd comedy, because it depicts the cosmos being devoid of  divine presence, despite the fact that, even in our &ldquo;secondary&rdquo; condition,  there exists a yearning for the  &ldquo;primal&rdquo; paradise, that is to say, for an earthly version of paradise that is  anterior to the Fall &ndash; or, as it is described  in Serbian, &ldquo;primal flaw&rdquo; or &ldquo;primal mistake&rdquo;. And in this version of his own  Creation myth, Popa writes that this &ldquo;mistake&rdquo; was rather small in the  beginning &ndash; comparable almost to the light strokes of a butterfly&rsquo;s wings:  &quot;Once upon a time there was a mistake / So silly so small / That no one  would even have noticed it&quot; (Popa 1977: 68). </p>
            <p>Apart from Popa&rsquo;s modern (and  hence absurd) vision of the underworld and upper world, contextual and  structural comparisons of Berengarten&rsquo;s <em>The  Blue Butterfly</em> can be pursued in other directions too, especially vis-&agrave;-vis  Dante. One of Berengarten&rsquo;s poems, &ldquo;Diagonal&rsquo; (BB 70-72), adapts  the <em>terza rima</em> form of the <em>Divine Comedy</em>. In this poem, a female  figure appears who is comparable to Beatrice. It should also be borne in mind  that, besides the numbers three and nine, the number seven is quite significant  in Dante&rsquo;s work, particularly in the <em>Purgatory</em> &ndash; with its seven terraces, and the Angelic guardian at the gate, who writes  the letter <em>P </em>(standing for <em>Peccati</em>, &lsquo;Sins&rsquo;) seven times on the  poet&rsquo;s forehead, with the point of a sword.<a href="#_ftn4" name="_ftnref4" title=""><sup>4</sup></a> Furthermore, one of the many symbolic configurations of the butterfly in  Berengarten&rsquo;s long poem is that the creature appears as guardian to &lsquo;one of the  entrances to the Underworld&rsquo; (BB 89-98). Thus, at this point the butterfly  takes on the role both of interpreter of the language of the dead and of the  Dantesque and Berengartenian &lsquo;Beyonds&rsquo; (BB 93), that lie on &lsquo;the Far Side&rsquo; of  silence (BB 79).</p>
            <p>Of course, the vision of the  other world in the work of a modern poet like Richard Berengarten is very  different from that of Dante&rsquo;s <em>Divine  Comedy</em> &ndash; in both &ldquo;positive&rdquo; and &ldquo;negative&rdquo; senses. Berengarten&rsquo;s vision  never attains paradise; but neither do we find the warning &lsquo;Abandon hope all ye  who enter here&rsquo;<a href="#_ftn5" name="_ftnref5" title=""><sup>5</sup></a> inscribed over the gates of the hell-on-earth that he explores. Furthermore,  Berengarten&rsquo;s blue butterfly is as much the angel and harbinger of death and  nothingness as<strong> </strong>herald of hope and forerunner of love.  Berengarten&rsquo;s poetic world is framed within space-time between <em>hope</em> and <em>nothing</em>. The blue butterfly is a being that inhabits both poles of  this world, because, in the poet&rsquo;s hand, it paints the most horrifying  landscapes of death; but it also takes that hand and &lsquo;writes / in invisible ink  across its page of air / <em>Nada</em>, <em>Elphida</em>, <em>Nadezhda</em>, <em>Esperanza</em>, <em>Hoffnung</em>&rsquo; (&ldquo;Nada: hope or nothing&rdquo;, BB  9). These words all spell/signify/mean <em>Hope</em> &ndash; in Serbian and Croatian,  Greek, Russian, Spanish and last, and perhaps most significantly of all,  German.</p>
            <p>&nbsp;</p>
            <p align="center">* * *<strong><u></u></strong></p>
            <p>I would like to see a future edition of <em>The Blue Butterfly </em>published with illustrations from  Peter Lubarda&rsquo;s cycle of paintings entitled <em>Kragujevac  1941</em>. One of the greatest, if not the greatest of all Yugoslav painters in  the second half of the 20th century, Lubarda commenced work on this  cycle of twenty-six paintings in 1966 and completed them for his 1968  exhibition in Kragujevac. At that time he had already received several  international awards, and distinguished artists, art critics and historians had  written in praise of his work. When he  donated these paintings to the Memorial Park in Kragujevac, he wrote:</p>
            <blockquote>These paintings are done in  various techniques and represent <em>a single  unique</em> <em>set</em> and <em>a single indivisible entity</em>, as can be seen from their titles,  starting with <em>Se&#263;anja na 1941</em> [Remembering 1941] and ending with <em>&Scaron;uplji  &scaron;lem</em> [Hollow Helmet]. Altogether, they represent a sort of novel in paint,  whose subject is the inconceivable suffering caused to a town and its proud  citizens.<a href="#_ftn6" name="_ftnref6" title=""><sup>6</sup></a></blockquote>
            <p>And in the catalogue for that exhibition, Miodrag B. Proti&#263; writes of this  set of paintings by Lubarda: </p>
            <blockquote>The 1941 massacre in  Kragujevac is a tragic subject that has generated innumerable treatments, both  poetic and metaphysical. By confronting a real event, Lubarda pronounces his  clear verdict on the gigantic destructive power that evil and terror have  wrought throughout history. However, in addition to this verdict, within each  painting and throughout the exhibition as a whole we trace secondary and  tertiary dimensions; and through these, we are offered the chance to think  about even broader and deeper themes: the meaning of life, the peculiar marks  that life tracks across eternity, the  inevitability of all processes, and cosmic movements and transformations. In  this way, his treatment of an event of national significance takes on layers of  poetic meaning that are both transcendental and universal. (Proti&#263; 1968: 1)<strong> </strong></blockquote>
           
            <p>Taken together with the words the great  painter himself wrote about <em>Kragujevac  1941</em>, this commentary on Lubarda&rsquo;s paintings is highly applicable to  Berengarten&rsquo;s poetic treatment of the enormity of evil in the world and  condemnation of atrocities throughout history in<em> The Blue Butterfly</em>.  Indeed, Berengarten submits the multiple layerings and variations of evil and  atrocity to identical treatment &ndash; in the precise sense that the work&rsquo;s  multi-dimensional poetic and metaphysical themes ramify and overarch the poem&rsquo;s  primary &ldquo;trunk&rdquo;. And although obviously Berengarten&rsquo;s poems have a good deal to  tell us about the poet himself, they at once also involve a &lsquo;telling&rsquo; (see BB  10-15) of human destiny &ndash; and of the sense that humans <em>make</em> of destiny  within the transformations of earthly and cosmic processes. Moreover, like  Lubarda, Berengarten deploys various techniques &ndash; poetic ones, in his case, of  course &ndash; not only in the book&rsquo;s overall design but also within the framework of  each of its particular cycles or, rather, circles. The complexity of these  techniques and the masterly skill with which they are applied and put into  practice deserves a separate study in itself. One almost has the impression  that there is no verse or stanza form, whether classical or modern, that  Berengarten does not deploy in <em>The Blue  Butterfly</em>. All the same, his book works as a unique, indivisible,  unrepeatable unity. Its themes  widen and intermingle in concentric rings; and, all the while, the blue  butterfly seems to flutter over the various <em>fleurs du mal</em> sown by human hand across the twentieth century, perching here  and there for an instant, not only in Kragujevac, Srebrenica or Kosovo, but in  the concentration camp of Mauthausen, in the pit dug out of Manhattan on 9/11,  and on the gallows of Rwanda &ndash; as well as<strong> </strong>in places where &ldquo;accidents happen&rdquo;, for example, in the Paris tunnel where  the &ldquo;authors&rdquo; of one such particular &ldquo;accident&rdquo; were a bunch of paparazzi and a  drugged driver (see BB 78). Into the air that floats above such sites of  accident and evil, the blue butterfly carves words of condemnation and disgust,  inscribes question marks and exclamation marks, utters lamentations for victims  and intones elegies among those who have somehow,  miraculously, survived. The blue butterfly enters into dialogue with those who  are dead and those who are sentenced to death; and <em>that</em> means with us  all in general and each and every one of us in particular. The winged creature  weaves metaphorical wreaths above individual  graves and mass graves; but it also heralds the mercy of blessing and awakens  the hope of resurrection.</p>
            <p>The final lines of the  book are genuinely symbolic and embed a multitude of meanings: &lsquo;Red tulip  petals / scatter. A blue / butterfly hovers&rsquo; (BB 111). Red and blue. A dead  tulip and a blue butterfly hovering above it. Neither hell without hope, nor  paradise without suffering and doubt. </p>
            <p align="right">&nbsp;</p>
            <p>&nbsp;</p>
            <p><strong>BIBLIOGRAPHY</strong></p>
            <p><strong>&nbsp;</strong></p>
            <p><strong>References with Abbreviations</strong></p>
            <p>&nbsp;</p>
            <p>BB &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Richard Berengarten,  2008. <em>The Blue Butterfly</em>. Second edition, Cambridge: Salt  Publishing, edition. References in this essay are to this second edition. The  first edition was published under the name Richard Burns. 2004. Cambridge: Salt  Publishing.</p>
            <p>&nbsp;</p>
            <p>ITD &nbsp;&nbsp;&nbsp; Richard Burns, 2008. <em>In  a Time of Drought</em>. Cambridge: Salt  Publishing. References in this essay are to this second edition. Page  references in the text are to this first edition. The first edition was  published under the name Richard Burns. 2006. Nottingham: Shoestring  Press.</p>
            <p><strong>&nbsp;</strong></p>
            <h2>Other Works Cited </h2>
            <p>&nbsp;</p>
            <p>Alexander, Ronelle.  1985. <em>The Structure of Vasko Popa&rsquo;s  Poetry</em>. Columbus, Slavica.</p>
            <p>Burns Richard. 2004. <em>U vreme su&scaron;e</em> (tr. Vera V. Radojevi&#263;). Belgrade: RAD. </p>
            <p>- - . 2007. <em>Plavi  leptir</em> (tr. Vera V. Radojevi&#263;, with two poems translated by Ivan V. Lali&#263; and  Danilo Ki&scaron;). Belgrade and Kragujevac:  Plava ta&#269;ka and Spomen-Park, Kragujeva&#269;ki  oktobar [Kragujevac October Memorial Park].</p>
            <p>Brki&#263;, Stani&scaron;a. 2007. <em>Ime i broj: Kragujeva&#269;ka tragedija 1941</em> [Name and Number: the Kragujevac Tragedy 1941]. Kragujevac: Spomen-Park,  Kragujeva&#269;ki oktobar [Kragujevac October Memorial Park].</p>
            <p>Domentijan. 1963. <em>Domentijan</em> (ed. &#272;or&#273;e Trifunovi&#263;). Belgrade:&nbsp; Nolit.</p>
            <p>Ibler, Reinhard (ed). 2000. <em>Zyklusdichtung  in den slavischen Literaturen.</em> Frankfurt am Main: Peter Lang.</p>
            <p>Ignjatovi&#263;, Srba. 2007. &ldquo;Neuni&scaron;tivi spomenik&rdquo; [Indestructible Monument] in Burns 2007: 157-159. </p>
            <p>Lali&#263;, Ivan V. 1971. &ldquo;Poezija Vaska Pope&rdquo; [The  Poetry of Vasko Popa] in Popa: 1971; 7&ndash;28.&nbsp; &nbsp; </p>
            <p>Lorenz, Edward. 1963. &ldquo;Deterministic  Nonperiodic Flow&rdquo; in <em>Journal of Atmospheric Science</em> 20: 131&ndash;40.</p>
            <p>__. 1965. &ldquo;A Study of the  Predictability of a 28-Variable Atmospheric Model&rdquo; in <em>Tellus</em> 17: 321&ndash;33. </p>
            <p>Pavlovi&#263;, Miodrag. 1964. <em>Osam pesnika</em> [Eight Poets], Belgrade: Prosveta.</p>
            <p>Petrov,  Aleksandar. 2000. &ldquo;Cycles in the Po&shy;e&shy;try of  Vas&shy;ko Po&shy;pa&rdquo; in Reinhard Ibler (ed.): 403&ndash;417. </p>
            <p>Popa, Vasko. 1968.<em> Sporedno nebo</em> (<em>Secondary  Heaven</em>). Belgrade: Nolit.</p>
            <p>__. 1971. <em>Pesme</em> [Poems]. Novi Sad &amp; Belgrade: Matica Srpska,  Srpska  knji&#382;evna zadruga [Serbian Literary Association].</p>
            <p>__. 1975. <em>Vu&#269;ja so </em>(<em>Wolf Salt</em>)<em>. </em>Belgrade: Nolit.</p>
            <p>__.&nbsp;&nbsp; 1977. <em>Collected Poems  1943 &ndash; 1976</em> (tr. Anne Pennington, with an introduction by Ted Hughes).  Carcanet: Manchester. </p>
            <p>__. 1998.&nbsp; <em>Collected Poems</em> (tr. Anne Pennington and Francis R. Jones). London: Anvil Press  Poetry.</p>
            <p>__ (ed.). 2008. <em>Jutro misleno</em> [Spiritual Morning]. Novi Sad: Akademska  knjiga [Academic Book]. </p>
            <p>Proti&#263;, Miodrag B. 1968. <em>Petar Lubarda </em>(catalogue for the exhibition &ldquo;Petar Lubarda,<em> Kragujevac 1941</em>&rdquo;). Kragujevac: Spomen-Park, Kragujeva&#269;ki oktobar [Kragujevac October Memorial Park].</p>
            <p>Rakiti&#263;, Slobodan. 2007. &ldquo;Pesnik u vlasti leptira&rdquo;  in Burns 2007: 151-156. </p>
            <p><strong>&nbsp;</strong></p>
            <h3>&nbsp;</h3>
            <p>&nbsp;</p>
            <div>
              <div id="ftn1">
                <p><a href="#_ftnref1" name="_ftn1" title="">1.</a> The poet reverted to his ancestral name Berengarten in June  2008.&nbsp; Henceforward in this essay, the  name Berengarten is used retrospectively, except in specific reference to books  published under the name Burns.</p>
              </div>
              <div id="ftn2">
                <p><a href="#_ftnref2" name="_ftn2" title="">2.</a> <em>Translator&rsquo;s note</em>: the very first translators of &lsquo;The blue butterfly&rsquo; into Serbian  were Moma Dimi&#263; and Ivan Gadjanski.</p>
              </div>
              <div id="ftn3">
                <p><a href="#_ftnref3" name="_ftn3" title="">3.</a> <em>Translator&rsquo;s note</em>:&nbsp;  Burns came to realise that there had been considerable controversy  concerning the number of victims. His major acknowledged source was the  historian Stani&scaron;a Brki&#263;, head of the 21st October Memorial Museum in  &Scaron;umarice.&nbsp; See BB 125-137 and Brkic 2007. </p>
              </div>
              <div id="ftn4">
                <p><a href="#_ftnref4" name="_ftn4" title="">4.</a> &lsquo;Sette <em>P</em> nella fronte mi descrisse / col punton della spada&rsquo;  (<em>Purgatory</em>: IX, 111-2).</p>
              </div>
              <div id="ftn5">
                <p><a href="#_ftnref5" name="_ftn5" title="">5.</a> &lsquo;Lasciate ogni speranza, voi ch&rsquo;intrate&rsquo; (<em>Inferno</em>: III, 9).</p>
              </div>
              <div id="ftn6">
                <p><a href="#_ftnref6" name="_ftn6" title="">6.</a> Lubarda&rsquo;s &ldquo;Letter to The Executive Board  of the Kragujevac Memorial Park&rdquo; was not published, but was included in  the exhibition <em>Lubarda 1907 &ndash; 2007</em>,  held at the Museum   of Yugoslav    History,&nbsp; Belgrade, 2008.&nbsp; <strong><u></u></strong></p>
                <p>&nbsp;</p>
              </div>
          </div>            <P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
