<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue4/menu_issue4.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue4/michael_schmidt/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2"><p align="center"><strong>Before Irony: John Bunyan</strong> 
            <span class="texto2">by <a href="../../issue4/michael_schmidt/bio.php" class="link3">Michael Schmidt</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2"> 
              <p align="left"><br></p>
              <p>&#8220;Outwardly the  extreme puritan appears narrow, crabbed, fanatical, gloomy and dull; but from  the inside &ndash; what a series of dramatic climaxes his life is, what a fascinating  casuistry beguiles him, how he is bemused by the comedies of duplicity,  sharpened by the ingenious puzzles of the conscience, and carried away by the  eloquence of hypocrisy. He lives like a soldier, now in the flash of battle, now in the wangling of camp and billet. However much he may bore others, he  never suffers from boredom himself.&#8221;<br>
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;V.S.  Pritchett <em>The Living Novel</em> </p>
          </td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <p>&#8220;If you will go  with us you must go against wind and tide&hellip;&#8221; John Bunyan is, or seems to be, a  man of dogged sincerity and meticulous accuracy. If he describes the engines of  war, each detail is correct. This factual correctness gives weight to the  allegorical and moral truths that he tells. &#8220;I have used similitudes,&#8221; says the  epigraph on the title page of <em>The</em> <em>Pilgrim's Progress</em><a href="#footnote">&sup1;</a>. The words are taken  from the Old Testament book of Hosea (xii.10). &#8220;The father of the novel,  salvation's first Defoe,&#8221; Rudyard Kipling called him. We believe Bunyan more  readily than we do Defoe, despite the realism with which Defoe portrays the  contingent world. This is because Bunyan at his best is not only telling a  story but building a marvellous structure, in which all the parts relate to one  another. Defoe tells us a series of stories while Bunyan has a plot. Defoe describes  others while Bunyan confronts us, figuratively, with a version of ourselves.  Melville, his greatest literary beneficiary, invokes him: &#8220;Bear  me out in it, thou great democratic God who didst not refuse to the swart  convict, Bunyan, the pale, poetic pearl&hellip;&#8221; And Bunyan has a gentle and generous  sense of humour. Ford Madox Ford says, &#8220;The difference between Bunyan and his  predecessors is one more than anything of whole-heartedness...&#8221; A more real  difference, separating him from many of his successors as well, is his formal  instinct. Bunyan is at once more mediaeval (allegorical) and more modern  (synthetic) than most.</p>
            <p>It is customary for critics to  condescend to him. Henry James deals with him obliquely, applauding Edgar Allan  Poe for having the &#8220;courage to remark&#8221; that <em>Pilgrim's  Progress</em> is a &#8220;ludicrously overrated book&#8221;. And Ford: &#8220;So let us say that  it was to the homespun illustrations, the simple imagery and the stern diction  of the Bible that we owe Bunyan &ndash; for obviously Bunyan read the Scriptures,  year in and year out, during a lifetime of Bedford Gaol, of persecution and  turmoil...&#8221; Bunyan is less homespun than Defoe, his imagery rather more complex  and resonant than Richardson's.  It is Bunyan's manifest didactic, spiritual purpose that seems out of place in  the world of fiction. Novels exist to test ideas, not to affirm them. But here  is an exception: <em>The Pilgrim's Progress</em> is for use, the characters are figures, their clarity is complex. The critic condescends, but ends up  marvelling: &#8220;He just told on in simple language, using such simple images that  the reader, astonished and charmed to find <em>the  circumstances of his own life typified </em>[my italics] in word and glorified  by print, is seized by the homely narrative and carried clean out of himself  into the world of that singular and glorious tinker.&#8221; </p>
            <p>&lsquo;Tinker&rsquo; because his father Thomas  was a tinsmith and brazier. In <em>Grace  Abounding</em>, Bunyan declared: &#8220;my descent [...] was, as is well known by  many, of a low and unconsiderable generation; my Father's house being of that  rank that is meanest and most despised of all the families in the land.&#8221; This  over-states the case: his father owned land, his own house and workshop, and  was by later account a Royalist and Anglican. Bunyan exaggerates his humble origins  in order to include as wide a constituency as possible in his embrace.  &#8220;Wherefore I have not here, as others, to boast of noble Blood, or of a  high-born State according to the Flesh; though, all things considered, I  magnify the heavenly Majesty, for that by the door he brought me into the  world, to partake of the Grace and Life that is in Christ by the Gospel.&#8221; And  why is his style so simple? The reasons are moral, even though the aesthetic  demands might have elicited a different mode of address, as he says in the  Preface to <em>Grace Abounding</em>:</p>
            <blockquote>I could have  enlarged much in this my Discourse of my Temptations and Troubles for Sin; as  also, of the merciful Kindness, and Working of God with my Soul: I could also  have stepped into a Style much higher than this, in which I have here  discoursed, and could have adorned all things more than here I have seemed to  do; but I dare not: God did not play in tempting of me; neither did I play,  when I sunk as into a bottomless Pit, when <em>the  Pangs of Hell caught hold upon me</em>; wherefore I may not play in relating of  them, but be plain and simple, and lay down the thing as it was: He that liketh  it, let him receive it; and he that does not, let him produce a better. <em>Farewell</em>.</blockquote>
            <p>This is strong  stuff. In such Puritan writing we marvel at the spiritual hubris implied in the  excessive humility, and in the absolute assurance that God actually cares so  directly and <em>so much</em>. </p>
 <p>Bunyan identifies his patron in the  Preface of <em>Grace Abounding</em>. The  author's dedication is &#8220;to those whom God hath counted him worthy to beget to  Faith, by his Ministry in the Word.&#8221; In other words, the book is dedicated to  those he has converted or brought back to church, and through their witness to  God himself. Imprisoned (&#8220;I being taken from you in presence, and so tied up,  that I cannot perform that duty, that from God doth lie upon me, to you-ward,  for your further edifying and building up...&#8221;), he provides an alternative  presence, a witness. The clauses follow one another with absolute, unaffected  clarity, building long, limpid sentences, unambiguous and reassuring in tone.</p>
 <p>John Bunyan was born in 1628 to his  father's second wife in Harrowden, near Elstow, Bedfordshire. The cottage where  he was born vanished long ago, but the spot is marked by a commemorative stone  placed there during the Festival of Britain. He attended the thirteenth-century  abbey church of St Helena and St Mary where he was  baptised in the font still in use today; and the communion table, too, is from  his time. The church overlooks the Green and the Moot Hall. His parents and  sisters are buried in the churchyard. This is the village where he spent his  youth, rang bells and played tip-cat on the green, nineholes and perhaps  stoolball (an early form of cricket). He was reportedly a strong, lusty lad  with a commanding voice. The commanding voice of God spoke to him as a boy  playing tip-cat on the Sabbath: &#8220;Wilt thou leave thy sins, and go to heaven? Or  have thy sins and go to hell?&#8221; Some years later he took heed.</p>
  <p>He may have attended Bedford's Grammar School, or perhaps the Free School  in Houghton Conquest. But he was, by his own account, unmarked by formal  education, picking up at best a few words of Latin and Greek. He was  apprenticed in the smithy with his father, soon learned the trade and travelled  the countryside with him or on his behalf. Later he lay claim to a blasphemous,  wayward childhood and a troubled adolescence, racked with terrible, involuntary  thoughts, visions and dreams that drove him close to suicide. This may have  been dramatic exaggeration, intended to emphasise how great an effort of divine  Grace was required to hoist him out of the mire.</p>
  <p>He was in his early teens when the  First Civil War began (1642-6). It is uncertain why he joined, whether he  actually fought, whether he joined for Parliament, and if he did whether he  stayed on that side throughout the war. Bedford  was a broadly Parliamentarian district though Charles I recruited here as he  passed through en route to his climactic defeat at Naseby,  1645. Did he see action there? In <em>Grace  Abounding</em> he relates, &#8220;when I was a soldier, I, with others, were drawn out  to go to such a place to besiege it; but when I was just ready to go, one of  the company desired to go in my room; to which, when I had consented, he took  my place; and coming to the siege, as he stood sentinel, he was shot into the  head with a musket bullet, and died.&#8221;</p>
 <p>Whatever the truth of the matter, he  was demobbed in 1647 and entered his father's business, working away, in Bedford and elsewhere, as  an itinerant. Though not yet directly involved or even deeply interested in  political or religious controversies, the roots of his spiritual reformation  are in this time of his life. He began attending church, reading Scripture. He  gave up swearing, gaming and dancing. In 1648 he married his first wife, an  orphan: &#8220;I changed my condition into a married state, and my mercy was to light  upon a wife whose father was counted godly. This woman and I, though we came  together as poor as poor might be, not having so much household stuff as a dish  or spoon betwixt us both, yet this she had for her part, <em>The Plain Man's Pathway to Heaven</em>, and <em>The Practice of Piety</em>, which her father had left her when he died.&#8221;  He married, then: a woman, and two edifying books to add to his Bible. The next  year, Charles I was executed.</p>
   <p>Bunyan was now a family man. His  daughter Mary was born in 1650, blind from birth and the apple of his eye. Two  sons followed, and another daughter. It was Mary who brought him a jug of soup  each evening during his imprisonment. He made a violin out of tin and a flute  from a chair leg. Music was integral to his Puritanism.</p>
 <p>1653 was the turning point in his  spiritual life. He befriended the Puritan pastor of St   John's Church, Bedford, Mr Gifford, who  became his mentor, baptising him a second time in the Ouse, somewhere between  what is now Duck Mill Lane  car park and the weir bridge. In the same year he fell from a boat into the  Ouse and was narrowly saved from drowning. &#8220;I fell out of a boat into Bedford river, but mercy  yet preserved me alive,&#8221; he reports in <em>Grace  Abounding</em>. He moved permanently to Bedford  and became deacon at St John's.  He was invited to begin preaching, at first privately, then in public. He was  good at it, quickly gained a following, and became insistently devout, a  &#8220;soldier of Christ&#8221; in the words of Ebenezer Chandler. Then his wife died,  followed shortly by Mr Gifford. </p>
 <p>Bunyan had the bit between his  teeth. In 1656 began his fierce attack on the Quaker preacher Edward Burrough,  and on Quakerism generally, in <em>Some Gospel Truths Opened</em>, his first published pamphlet. Thus he entered into  the tradition of &#8220;Martin Marprelate&#8221;, Nashe and Greene, a controversialist, but  a consistent fighter, not a pen for hire. The next year <em>Vindication of Gospel Truths</em> followed. He was formally recognised  as a preacher and was soon in trouble with the law for preaching outside his  area. In 1658 he published <em>A Few Sighs  From Hell</em>. </p>
 <p>His concerns deepened as his life  settled into a more coherent routine. He married a second time and published <em>The Doctrine of the Law and Grace Unfolded</em>.  The larger, visible structure of his faith was beginning to take shape. Then in  1660 came the Restoration. Charles II may have undertaken to tolerate religious  dissenters with the Declaration of Breda, but the politic intention and the  political will were at odds. The wind no longer blew the Puritan way. In  October the magistrates of Bedfordshire ordered the reinstatement of Anglican  liturgy. On 12 November Bunyan was scheduled to preach at Lower   Samsell. Upon arrival he was advised that a warrant had been  issued for his arrest by the judge Francis Wingate. Wingate and his  brother-in-law William Foster tried to persuade Bunyan to offer certain  concessions in exchange for his freedom. But, he insisted, he had broken no new  law. Bunyan was imprisoned at Bedford,  in a gaol on the old bridge over the Ouse. He spent a third of his adult life  incarcerated, and it is in large part to this restraint that we owe his  writings.</p>
 <p>In January he appeared before Sir  John Keeling ('Lord Hate-Good' in<em> Pilgrim's Progress</em>) at the Assizes, charged with &#8220;devilishly and  perniciously abstaining from coming to Church to hear Divine Service, and for  being a common upholder of several unlawful meetings and conventicles, to the  great disturbance and distraction of the good subjects of this kingdom,  contrary to the laws of our sovereign lord and king.&#8221; When Bunyan tried to  outline his objections to Anglican ritual, a voice exclaims &#8220;let him speak no  further; he will do harm!&#8221; Keeling replied: &#8220;No, no, never fear him... he can  do no harm; we know the Common Prayer Book hath been ever since the Apostles'  time.&#8221; He was sentenced to three months with the added threat of banishment if  no recantation was forthcoming. Bunyan retorted: &#8220;if I were out of prison  today, I would preach the gospel again tomorrow, by the help of God.&#8221; </p>
 <p>After twelve weeks, Bunyan was  visited in prison by Cobb, a clerk of the peace. Cobb urged that a loyal  subject of the King was bound by St. Paul to obey the King's laws. Although St Paul respected the  authorities, Bunyan said, he spent time in prison nonetheless. His own loyalty  to Charles II did not override what his conscience told him was his duty.  Wycliff had declared that he who discontinues preaching and hearing the word of  God for fear of the excommunication of man was already excommunicated of God.  Bunyan's imprisonment continued despite the amnesty marking the coronation. </p>
 <p>The Act of Uniformity of 1662  institutionalised the episcopalian (Catholic) character of the English church,  depriving thousands of pastors of their right to preach while restoring others  to their parishes. Bunyan's hitherto fairly relaxed regime was tightened; the  conditions of his imprisonment remained poor until 1668, though he was allowed  a 'library' &ndash; &#8220;the least and yet the best that ever I saw&#8221;: his Bible. &#8220;I was  never out of the Bible either by reading or meditation.&#8221; To support his family  he spent his days making shoelaces, reading, writing, preaching to and  counselling fellow inmates. As more acts hostile to the Puritan cause were  passed, so Bunyan's polemical and reflective work continued. In 1666 he  published his autobiography, <em>Grace  Abounding to the Chief of Sinners</em>. After a very brief period of freedom, he  was rearrested after unauthorised preaching. After 1668 he was allowed limited  access to visit his congregations outside gaol. and four years later, in 1672,  he was elected pastor. Charles II's Declaration of Indulgence led to his  release from Bedford Prison after twelve years. He became pastor of the  Independent Congregation, composed largely of burghers and tradesmen, and was  now a famous man. He began to preach widely, as far afield as Reading  and London. One  account says that in London  he drew a crowd twelve hundred strong even though he preached at seven in the  morning on a working winter's day. On Sundays he drew three thousand and more.  Enemies dubbed him 'Bishop Bunyan'. Libels were spread alleging immorality, Jesuitism, even witchcraft. </p>
 <p>It was too good to last. The  Declaration of Indulgence was overturned in 1673: elements in Parliament  thought it favoured the Catholics. In 1674 Bunyan was accused of keeping Agnes  Beaumont (herself accused of poisoning her father because of his disapproval)  as his mistress. In 1675 Bunyan's license to preach was revoked and he went  back to prison. He began work on <em>The  Pilgrim's Progress</em>. He was briefly released, then re-arrested. He may even  have been grateful this time for the opportunity to return to his imaginary  adventures.</p>
 <p>In 1677 <em>The Pilgrim's Progress </em>was published, the first of an unprecedented  twelve editions within Bunyan's remaining lifetime. By 1792 it had gone through  one hundred and sixty editions and was, by most polite authors, regarded with  derision. Whatever the English intellectual classes thought, the book was a  popular success throughout the Protestant world and was translated into French  and Dutch within a decade. His already prolific output quickened, but apart  from the cautionary tale <em>The Life and  Death of Mr. Badman</em> (1680) nothing quite lived up to <em>Grace Abounding</em> and <em>The  Pilgrim's Progress</em>. <em>Mr Badman</em> is  an allegory in dialogue form in which Mr Wiseman recounts the life of Mr  Badman, recently deceased, and Mr Attentive comments upon it. Mr Badman drank  too much, duped a maid and married for money and, upon her death, remarried a  wicked woman. He died of a cocktail of diseases. Morally uplifting, the story  is also funny. Despite the solemnity of his themes, Bunyan is never a severe or  po-faced writer.</p>
  <p>In 1687, acknowledging his influence  and power, James II offered him a &#8220;place of public trust&#8221;; Bunyan declined, but  gained concessions for his friends. His health was in decline and the next year  he caught a fever from having travelled to London in bad weather to try to settle a  conflict between a young man and his father. He preached a final sermon and 31  August brought 'the Death of deare Brother Bunyan'. He was buried at Bunhill  Fields, where Defoe, Blake and other radical spirits would eventually join him.  Due to Victorian restoration, his is by far the most elaborate tomb there, with  an imposing marble effigy and bas-relief depictions of scenes from <em>The Pilgrim's Progress</em>. In Bedford  himself he stands nine feet tall and green with corrosion at the top of the  High Street.</p>
            <p align="center">*</p>
              <p>In <em>The Pilgrim's Progress</em> the narrator,  weary from walking &#8220;through the Wilderness of this World&#8221;, finds a den, falls  asleep and starts to dream, all within the opening sentence. We are immediately  in the mediaeval world of allegory. William Langland is not far away, though  Bunyan's sense of structure is far more certain than Langland's, and his  translation of the terms of moral argument into a consistent fiction more  assured. This has much to do with his style. &#8220;<em>The Pilgrim's Progress</em>,&#8221; writes Coleridge with measured respect,  because from Bunyan he had learned some of the lessons that went into the  making of his balladic <em>Rime of the  Ancient Mariner</em>, &#8220;is composed in the lowest style of English, without slang  or false grammar. If you were to polish it, you would at once destroy the  reality of the vision. For works of imagination should be written in very plain  language; the more purely imaginative they are the more necessary it is to be  plain.&#8221; His success also has to do with consistency. The unfolding of the  allegory, David Lodge reminds us, is controlled completely by correspondences,  usually quite specific, to the meanings implied or declared in the given names.  But we may feel inclined to disagree with Lodge when he declares that Bunyan lacks  what Henry James called &#8220;the sense of felt life&#8221;. Here we find fear,  friendship, tenderness, doubt, joy, grief. There are feelings and there are  textures, scents and savours. All that is lacking are literal contingencies  which, Bunyan might have said, are rather overvalued in the fictions of this  world. </p>
			  <p>The sleeper spots Christian, bearing  a burden on his back and reading from a book in which he learns that the city  in which he and his family dwell will be burned with fire. On advice from the  Evangelist, Christian flees from the City of Destruction,  a kind of Gomorrah,  having failed to persuade his wife and children to accompany him. Salvation is  a painfully lonely exercise, and the path leads through various perils,  temptations and places of recuperation. In Part One the ten chief stopping  places are familiar to us, some from the Psalms, others from Blake, Thackeray  or elsewhere. </p>
            <p><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Slough  of Despond</em><br>
                <em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The  Interpreter's House</em><br>
                <em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Palace Beautiful</em><br>
                <em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Valley of Humiliation</em><br>
                <em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The  Valley of the Shadow of Death</em><br>
                <em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Vanity  Fair</em><br>
                <em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Doubting Castle</em><br>
                <em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The Delectable Mountains</em><br>
                <em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The  Country of Beulah</em><br>
                <em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The  Celestial City</em></p>
            <p>On the way he  encounters a variety of faces and voices: Mr Worldly Wise-man, Faithful (who  goes with him but is killed in Vanity Fair), Hopeful (who also joins him),  Giant Despair, the foul fiend Apollyon, and many others. This is a world that  in its lineaments reminds us now of Spenser's <em>Faerie Queene</em>, except there is little decoration; now of Dante's <em>Inferno</em>, but there is more hope and  forgiveness at hand, and Christian is supported from within and urges his way  forward with hope rather than fear.</p>
			<p>Bunyan himself in imaging the places  of trial and temptation may have had specific places in mind: the wicket gate  at Elstow church, Squitch Fen, St. John's Rectory, the Chilterns and so on. Some of the  allegorical figures were based on human models, for example Evangelist is John Gifford, who brought him to faith. These personal occasions are lost to us:  they were part of the process of composition and visualisation, making the  pilgrimage real to the author and therefore to us. </p>
 <p>Part Two brings the family along.  Christian's wife Christiana and children set out on the same hard pilgrimage,  accompanied by neighbour Mercy (Christiana's gossip) and over-ruling the  objections of Mrs Timorous. Their escort Great Heart overwhelms Giant Despair  and they too come to their destination. First man, then woman, first husband,  then wife, make their way to salvation. </p>
 <p>What makes this story, predictable  in its outcome, passage by passage derivative of the Bible, so compelling, so <em>durable</em>, is the reality of its  allegorical figuration, and its humour. It is the best fruits of Puritan  culture, setting out to include every person among its readers. &#8220;I could not  have believed beforehand that Calvinism could be painted in such exquisitely  delightful colours,&#8221; said Coleridge. Bunyan is a most uncommon common man, a  man of the people and of a demanding, democratic, accountable faith. Into his  novel of practical faith he works dramatic dialogue or interrogation, for  example when the Porter cross-examines Christian, or Greatheart elicits from  Valiant, like an attorney, an account of his adventures and heroisms; verse,  including Bunyan's famous hymn, &#8220;Who would true valour see&#8221; and runs of  homespun couplets for invocations and conclusions; regular marginal rubrics, as  in the case of published sermons, summarising action or speech, indicating  Biblical allusions; and other formal features, making for a rich impurity and  variety of effect. The author avails himself of the elements he feels will make  his work direct and &#8220;understanded&#8221;. Writing in the provinces, he rejects the  new urban and the pastoral mode; he knows what literature is and he avoids it  because it tends to falsify. No University has infected him with a witty  brilliance. His book does not limit itself to a scholarly or cultured class,  nor to the rich and powerful. Yet it is figurative, it plays constantly between  the Bible and allegory, it is more complex in conception and consistent in  execution than any English prose work tat precedes it. It is original without  meaning to be; it entertains even the pagan heart. Bunyan's direct legacy is to  his faith; his oblique and lasting legacy is to writers including Defoe, Swift and  Smollett; Blake and Thackeray (<em>Vanity Fair</em>) and Coleridge; Hawthorne (<em>The  Celestial Railway</em>, 1843), and Louisa May Alcott; to Joyce and Wyndham Lewis  and Gore Vidal (<em>Burr</em> abundantly  alludes to him), to all the makers and re-makers both of plain and of figurative  styles.</p>
            <div>
              <div id="ftn1">
                <p><a name="footnote"></a><small>1. Or to give it its full title, <em>The  Pilgrim's Progress from This World to That which is to Come: Delivered under  the Similitude of a Dream, Wherein is Discovered The Manner of his setting out,  His dangerous Journey , and Safe Arrival at the Desired Country.</em></small></p>
              </div>
            </div></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
