<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue8/menu_issue8.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue8/aamer_hussein/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">The Grammar of Grief<span class="texto2"> by <a href="../../issue2/aamer_hussein/bio.php" class="link3">Aamer Hussein</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           
              <p>&nbsp;</p>
          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <br><p><strong>1.</strong></p>
            <p>It was happenstance, of course. Lady L and her old adversary Reza Shah  fell in the same year. He from his  throne, she from her bicycle. A broken limb meant that, given the battle of  succession that followed, she never did reclaim her role as High Priestess of  Persian in our department.&nbsp;&nbsp; </strong><br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Lady Jane would have  been more appropriate a title: she was born into the minor nobility but had  never married, and would not have been addressed as Lady Lambert. In the  hallowed halls of Middle Eastern Studies she was known as The Professor.  Reputed to be a martinet, or, at her less than benign best, an academic Mary  Poppins. She was tall, thin and  hollow-cheeked; she scraped back her steel-wire hair into a little bun. She  wore masculine tweed jackets over severely-tailored skirts. But she had a soft  accent when she spoke Persian, and sometimes she wore an agate brooch  coquettishly pinned above a breast.&nbsp;&nbsp;&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Marco, my Italian  classmate who&rsquo;d dubbed her Lady L, would tell me I was her &lsquo;fiore  all&rsquo;occhiello&rsquo;, because I usually got my verbs right and elicited her  approval.&nbsp; Marco was a bit of&nbsp; a lad: spry and bespectacled, he looked  weedily serious at first glance until you saw the wry grin on his thin lips. He  loved good films, the theatre, food, lots of sex (he said), smoking dope and  (very occasionally) getting drunk on beer, red wine or grappa. Sometimes, on a  Sunday, he attended Mass at Brompton Oratory. He'd travelled all over Asia in  his teens, worked in Catholic convents and Buddhist monasteries, and had joined  University a year before me: he was studying Urdu and History, and had taken  Persian as a minor in his second year. He'd wanted to leave Italy because, he said,  classes there went so slowly that it was difficult to finish your studies  before you were thirty. One advantage of being with Marco was that we spoke  either Italian or Urdu to each other and didn't need English at all, which gave  us a special kind of intimacy.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; There was a rumour in  the corridor, repeated to me, as usual, by Marco, that once Lady L had loved an  Iranian, to whom she'd almost certainly been secretly married; he was almost  certainly of lesser breed than she was. She'd left him, chosen never to go back  to Iran (or Persia, as she called it), but&nbsp;  kept her faith with the foreign land she knew in her youth by teaching  verbs, clauses and nouns to one generation after another in the language she  might have learned for her lover who knew no English. And he - how knows? - he  may have given her the agate, which was the kind of stone people often wore,  set in rings and lockets, with prayers in Arabic letters carved into its deep  orange. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I thought my moment of  disgrace had come when Lady L summoned me to her office one afternoon after  class. What had I done wrong? My knees trembled, my shoulders quaked.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;Mr Malik,&rsquo; she said,  &lsquo;are you a sporting man?&rsquo;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (So I&rsquo;d&nbsp; been accused of gambling? But wait.)<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;I mean, do you play  cricket, football, tennis&rsquo;&hellip;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;No, Professor.&rsquo;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;I was merely asking in  case you wanted Wednesday afternoons off in order to play.&rsquo;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (She made some  reference to my being young, energetic, and in need of constant exercise. But  if I could ever get away early from classes, I&rsquo;d rush to an office a mile&rsquo;s  walk away to file papers for a small sum that kept me in Jacques Brel LPs,  cigarettes, paperbacks and cinema tickets for the month: I didn&rsquo;t have a  student grant. Although the time off to work would actually have helped, my  studies, too, were important that first year. I was twenty-three, had dropped  out of another degree to fulfill an ambition to study Persian, and I wasn't  going to take risks.)<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;I wouldn&rsquo;t want to  miss a class.&rsquo;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;Oh, good man. But if  someday you&rsquo;d like a game of badminton, I play on Thursdays.&rsquo;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I didn&rsquo;t play  badminton, and, as a consequence, perhaps I fell from grace. </p>
            <p><strong>&nbsp;</strong></p>
            <p><strong>2.</strong></p>
            <p>Or perhaps I never did lose her favour in the few months - was it even  six? - I spent under her tutelage. I don&rsquo;t remember. Life has a way of taking  over from memory. I recall the hours spent over verbs and tenses and  subjunctives, and the fall of the Shah, and the hanging of Bhutto, and the  gentle middle-aged Persian native who took me over from Lady L when she went on  protracted sick leave. Marco laughed at me (he dropped Persian in his third  year to switch to Hindi) - &lsquo;Trust you to choose to study Persian, Mehran,&nbsp; just as Iran&rsquo;s star is falling and  the stock of Arabic rises.'&nbsp; And Thatcher  won the elections at some point. I remember thinking that after Pakistan had  let me down by letting Bhutto be hanged and ogre-faced Zia come in with his  henchmen, Iran, which seemed to offer me some sort of alternative, was now  becoming some kind of dictatorship too. I remember breaking up with Tina the  Venetian, my fashion buyer girlfriend who spent more time in Venice and Milan than  in London and was too absent a partner for a twenty-four year old; hanging  around University bars with Marco and others, and going to midweek socials in  the evenings in the idle hope of meeting someone new; rushing between work and  classes when I took on more of the former and attended fewer of the latter; and  often spending Saturdays alone at the cinema, a concert, or with a record or a  book.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; And I recall, in the first year of a new  decade, sitting my finals in Persian, doing quite well, and leaving it behind  as an academic subject for ever. Lady L had come back by then, her hair cropped  close, but now she was a shadowy figure among the library shelves, and it was  too late for me to learn any more from her.&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As for me, I abandoned  the rhetorical delights of the book of Persian grammar for the joys of my  mother tongue, which I'd only discovered in my early twenties. It was so easy.  In my first two years at University, Urdu was in a way my default subject, and  I&rsquo;d only had to attend one seminar a week in which a student deconstructed an  Urdu poem; in my second year, we discussed classic lyrics, Wali and Quli and  Sauda and Ghalib, for two hours on a Tuesday. My spelling was atrocious, but I  discovered a gift I&rsquo;d never suspected I had for unravelling elaborate similes  and undoing the multiple knots of a metaphor. Much of the time, I just had to  pick up xeroxed copies of Urdu texts like Bagh-o-bahar (The Tale of Four  Dervishes), read them alone without supervision, and deliver a scribbled exegesis,  report, or translation now and then. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In the third year, we  read long romantic poems by Mir and Shauq and Anis's laments for the martyrs of Karbala, all eloquently  expressed in the simplest words. If there was any excess at all it was not of verbiage  but of emotion, which didn&rsquo;t disturb me: it reminded me of a more intense and  somehow purified version of the sentiments in the film songs on the radio I'd  grown up listening to and still hummed. I didn&rsquo;t have to think much, or prepare  much; just prise open the text so it would reveal its mysteries, or read the  words out loud and let the poems talk to me, their rhythms sing in my ears. Now  I realised that the rolling cadences of Keats and Tennyson had always been a  music as distant to me as the assonances of Mir or Ghalib or Faiz were close.  Once, in class, Marco was reading out the lines 'dekh lo aaj ham ko ji bar  ke/koi aata nahin hai phir mar ke' from&nbsp;  'Zehr-i-Ishq', the mid-nineteenth century set text we were looking at,  and listening to his voice which sounded like the leafy afternoon outside I  could just hear the silk-wrapped arpeggios of Tahira Syed who'd recently  recorded a musical arrangement of that section of the poem echo in my head.  Suddenly our lecturer - an Englishman, as they all were in South Asian Studies  - guffawed: 'Oh, like so much Urdu literature this is at the level of Victorian  penny dreadfuls.'&nbsp; And I, who'd never  even heard of Edward Said or his emerging theories, exploded: 'But that sort of  comparison is facile! I don't see why you're making it.'&nbsp;&nbsp;&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 'Zehri-Ishq' or 'The  Poison of Love' was the story of two youths who fell in love at first sight and  had an affair in a society which secluded its women and didn't allow romance.  Its heroine spent a long, long time dying. Why couldn't the hero, I'd ask  myself, simply have asked his parents to bring her to their home as his bride?  Even in my childhood I'd heard accounts of unfortunate love affairs that had  ended in family reconciliations. But her death-throes gave the language one of  its most stirring romantic ballads.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I must have been  disappointed, even shocked, on hearing that Lady L wouldn&rsquo;t be teaching me  again. But I soon adjusted to the newer, gentler rhythm of poring over texts,  without companions or classmates, in the company of my new teachers. Now there  were close readings and discussions of poems by Iqbal or Faiz. I&rsquo;m sure, when I  look back now, that learning Persian had helped me to navigate the maze of my  own language, but I can&rsquo;t remember studying Persian poetry at all, with Lady L  or any of my other teachers. Rumi I&rsquo;d read with my mother as a teenager; Hafez  I would strugggle with later, on my own. What the joys of Persian literature  contributed to making me the dreamer I was becoming I can&rsquo;t say. Persian  studies for me meant the subtle disciplines of word order and subjunctives and  parsing, and then of translation, which - I was too often reprimanded by my  sandy new teacher, an Englishman who didn't quite seem to know what he was  doing with the Persian canon - I practiced too freely or too literally. Or  hunching over the homiletic verses of Sa&rsquo;adi, or Qabus&rsquo;s advice to his son in which  all manner of conduct from letter-writing to personal hygiene was strictly  codified.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
            <p><strong>3.</strong></p>
            <p>But if Persian taught me the discipline of grammar and translation, and  Urdu the joy of lyricism, I was also acquiring new vocabularies of emotion. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I&rsquo;d met Riccarda -  another Italian - in my Persian class. She had cat eyes and a tigress&rsquo;s body  and her allure crept up on you like a feline&rsquo;s, too.&nbsp; Like Marco, she spoke to me in&nbsp; Italian. We&rsquo;d study together some evenings at  her kitchen table with another classmate; sometimes we'd go to watch Persian  films with titles like 'The Bicycle' and 'The Cow'. Then she left University to  take photographs in Turkey and India. With her departure  and Marco&rsquo;s defection I was left entirely alone in the Persian class, and  didn&rsquo;t really have friends in Urdu or History (except, again, Marco, whom I  always seemed to be helping with vocabulary, syntax and pronunciation) . <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I don&rsquo;t know when it  was, precisely, but in one of those post-adolescent moments of crisis that men  in their twenties go through, I turned to Riccarda instead of Marco for advice  and knew she&rsquo;d always been there for me, even while we conjugated Persian verbs  together. (She didn't like Marco; she found his Roman accent grating, his tastes  philistine, and couldn't understand why he was doing South Asian Studies.) I  must have known her about a year, then. I posed for her camera in the park. The  photographs she took of me in the summer of '80 show a youth more rough and  rugged than I imagined myself to be. 'How happy we look,' she said about a  photograph a passerby (incidentally, a PhD student who'd taught us basic Arabic  broken plurals in Lady L's absence) had taken of us against the sunlit backdrop  of the Serpentine. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; But all too often she  wasn&rsquo;t there. And again it was Marco's presence that filled my narrow room; his  surprisingly deep voice intoning planned trajectories, dreams, activities,  always navigating the future, while my map was scaled very small. Occasionally  he'd fall asleep with his head against the wall and I'd pull him, grunting,  down to my carpeted&nbsp; floor, cover him  with a quilt or a sheet and let him sleep on till it was time for him to rise,  make coffee and heat up whatever he could find - pasta, lentils, rice, cold  meats - then shower (or not) before leaving for classes. Once I woke from a  deep sleep to find him recumbent next to me, fully clothed, on my narrow bed,  snoring softly with his head on my shoulder. I didn't move, but at some point  he rose and, half-asleep, I watched him rise, stretch, look around him, strip  down to his briefs and lie down on the floor again. ('You drop me when she  beckons,' he complained. I'd try to take them out together, but they'd argue  about everything - the pronunciation of the word&nbsp; 'cotolette', the architectural merit of the  Hayward Gallery, the films of the Tavianis or Wajda. Then he'd find an excuse  to turn on me and say: 'You're only an anglophone, all your&nbsp; knowledge of Urdu poetry comes from listening  to recordings of ghazals by pop stars and pretty female singers - it's the  music and the easy lyricism you love, not the underlying metaphysics.')&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When Riccarda was here  she'd take me on a tour of my own city to discover a London I hadn&rsquo;t charted at  all. My first taste of sushi and raw fish in a wooden bar in Covent Garden. Sian Phillips singing in  'Pal Joey' in the West End,&nbsp; Bob Hoskins in 'Guys and Dolls' at the  National. Pasolini&rsquo;s 'Medea' at the art house cinema in Brunswick Square. The Impressionists at  the Tate, the Contemporary Dance Theatre at the Place in Euston. (I&rsquo;ve  forgotten to say that Riccarda was, I think, forty-seven when we met.&nbsp; She&rsquo;d been a singer and a dancer once, and  though she&rsquo;d been caged in glamorous seclusion by her Austrian husband in a  Ligurian town by the sea for years, her yearning to spread her wings had never  left her.) <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; On my twenty-fifth  birthday, I told her over candles and champagne that I'd fallen in&nbsp; love with her, had loved her for a long time  without even knowing that I did. (I have a photograph of that evening; she's  dressed in a blue outfit, a long, clinging shirt over narrow trousers, she'd  bought in India; her blue eyes smile at the camera, while I grin into my  glass.) <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A narrative of love,  Riccarda&rsquo;s and mine, that was to remain unfinished. I won&rsquo;t attempt to give it  closure here.&nbsp;&nbsp;&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; </p>
            <p><strong>4.</strong></p>
            <p>My university days came to an end as the new decade and my travels  began. The year I&nbsp; graduated I spent a  summer fortnight in Rome with Marco, then  travelled with him to his parent's house in the country near a lake. I had a  few very happy days alone with Riccarda back in Rome. Later that year I  went to India and wandered round a  country I hadn&rsquo;t seen for a decade. During that trip, when I met him in Delhi  where he was living in a hostel for local students and spending a lot of time  listening to music at Sufi shrines, I fell out with Marco - over our differing  attitudes to India or to the rich, or over his disapproval of my relationship  with Riccarda, I've forgotten exactly why. I just remember anger (his),  coldness (mine), hurt.&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I returned unwillingly  to London and I told Riccarda  we&rsquo;d only be friends from now on as I had a life to live that didn&rsquo;t include a  secretive love. She had a son of seventeen and a husband from whom she was  emotionally separated, but for the son's sake they were still a couple. Either,  or both, of the males in her life could turn up, or demand her presence, at any  time, except when she was hiding away in the pied a terre she'd inherited from  her mother in Rome.&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; And I had plans. I  wanted to travel, to write essays or poems, to live in an Asian country, to  make a film, perhaps. Then, I thought, I'd like to settle down and have a  child, or adopt one, while I was still young. It was that no man's tract  between late summer and autumn and we walked up and down on the bridge over the Thames after a showing of La Femme de Boulanger. I talked  and then fell silent. 'Talk to me, tell me,' she said, and I responded: 'But I  thought I had.'&nbsp; (For a few months, she  was silent; two years later, she left to live in Rome.)&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; But life didn&rsquo;t work  out the way I&rsquo;d planned. I didn&rsquo;t go back to my university to complete my PhD,  though in my early thirties I began to work there, in the extramural division  of languages, teaching Urdu to foreign students. From time to time I'd be  reminded I belonged to the enchanted confraternity of the Students of Lady L;  I'd smile, and never say I'd only studied with her for a few months and away  from our class her interest lay in the economic demography of Qajar Iran, not in prosody. My  knowledge of Persian poetry was self-acquired. Legend was turning Lady L into a  Hafez-quoting mystic:but there were other stories too, about how she'd been a  spy of some sort and the brains behind the fall of Mossadegh in '53. It's easy  enough, though, to live with a legend. I wasn't being deceitful when I didn't  correct such impressions. I think I'd just forgotten how short my time with her  had been, and just how much - or little - she'd taught me. I'd forgotten a  lot.&nbsp;&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Someone else came into  my life when I was thirty-two. I was invited to a birthday party by an old  friend and it happened to be at Nina&rsquo;s house. (Tina, then Nina! But it's true.  And there were a few others in between. One had been important, a long  engagement, which had been interrupted by, and survived another sudden,  unwritten passion.) Nina was an unusual Pakistani; tall and quite dark-skinned,  with light brown eyes and cropped black hair, and the body language of a  European in the very short black dress she had on. She'd come to London as a teenager. She was an  economist; a migrant from Karachi like me, she was four  years younger. The mother of two but unhappily married, I found out. Living in London meant living away from  her husband.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We spent evening after  evening listening to music, singing, drinking wine and talking. Sometimes I  would be filled with yearning when I felt the sense of belonging she clung to  by going back, every year and sometimes more often, to Karachi, to Lahore, to  the small feudal town in Sind where she'd spent childhood summers with her  grandparents. She'd struggled with her family as a teenager when she'd run away  from a Hampshire college with a vagabond actor, but when she'd married and then  gone back to complete her studies at LSE she'd laid fresh claim to her father's  love. 'I spend my life longing for the place I'm not in but when I go back I  never fit,' she lamented; I knew what she meant, though I'd been back to India  just twice and never returned to the place of my birth. I preferred to wonder  outwards: home, if there was any longer such a place, was where I was with the  people who loved me.&nbsp; And that, at the  time I met Nina, was Rome, where Riccarda was.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp; I'd only known Nina a month when, during a  to Riccarda at summer's end,&nbsp; I heard  she'd had an accident on a skiing holiday in Austria. She was  semi-paralysed, and she had to abandon a promising academic career. My other  relationship ended, the long engagement which had become friendly make-believe  when Samar left for Harvard on a fellowship, but I didn't, and  don't, connect its end directly with Nina.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; For the next four years, I watched Nina undo  herself with cocktails of painkillers (she injected herself with pethidine) and  vodka. And though I tried to help, I wasn&rsquo;t strong enough; by being with her I  felt I was undoing myself, too.&nbsp; Yet when  I tried to escape her I'd feel drained and empty and it would take me days to  refill myself. But more often I'd succumb to her calls and go back because I  was too tired for anything, anyone else. Except Riccarda, who was my refuge  during those years, in which, for a while, I could pretend to forget Nina. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Riccarda had had a sudden, rapacious cancer  five years after moving back to Italy, but was in remission.  Ironically, it had been diagnosed just after her son found a job in a  prestigious New York law firm, and she'd  finally left the mysterious husband for ever. The first time I spoke to her on  the phone after her operation she was under sedation and said: 'Ti voglio molto  bene, amore.' Later, she didn't remember the call, or what she'd said. I  travelled to meet her in Rome, and she came to London too. Disease had made  her thin but also incandescent.&nbsp; She  looked so beautiful people would stop and stare at her in the street and  children wanted to touch her.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Nina and I had almost ceased to touch each  other by then but from time time she'd still reach out to me for warmth.  I'd&nbsp; hold her thin body with its fragile  bones in my arms for hours, or kiss her skin all over, until my own body would  rebel against the constraints of hers and then she'd cry and say she knew I had  to go elsewhere for the pleasure that she could no longer give me, and one day  I'd leave for a saner, stronger woman.&nbsp;  And at other times she'd say I was obsessed with Riccarda's cancer, it  was separating me from my friends and those who loved me: 'I know I'm crazy. But  you're a fucking ghost.'&nbsp; At thirty-six, I did feel ghostly, as if I'd died in some  other era. I'd become used to being unfulfilled, and even if I did find myself  in other beds it didn't matter, I was still Nina's and still alone. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; But things had also  changed in the world, some for the better: Benazir Bhutto had come into power  and even the disappointments that dogged&nbsp;  her supporters during her first term didn't succeed in vanquishing hopes  for a new era in Pakistan. In response, I'd started reading contemporary Urdu  writing, and my interest had turned to that. I wanted to teach it and translate  it and write about it, at least for the next ten years.&nbsp; I spent hours in the University library,  searching out unread, uncut fiction and poems freshly arrived from Pakistan. In the early evenings  I'd sometimes meet a colleague for a drink in the Senior Common Room or a bar  nearby, and wouldn't go back to the empty flat I'd moved into till 10 or  11.&nbsp;&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Marco suddenly rung me  up after eight or nine years of absence to say he was attending a conference on  Iqbal and the Concept of the Self at SOAS and wanted to come and stay. I didn't  think he'd changed much, but something about his air made me try to understand  why people had once called him plain and now called him handsome. His spare  frame had filled out, he wore contact lenses, and his longish hair was streaked  with grey; his once-edgy manner was expansive and tactile. He dressed baggy,  elegant clothes and had travelled to places- the Seychelles, Bali, Kenya -&nbsp; that seemed to have little to do with the  academic pursuits to which he was still dedicated. He'd moved to Venice, married a Tamilian  he'd once introduced me to in Rome where she was living  with a musician friend of his; they'd had a daughter, but seemed to be involved  in a rather acrimonious battle. 'I live like a hermit now,' he said. 'No money,  no home, and half a job. How are you?' But still he had a city he'd lived in  all his life, faces he'd known since his childhood around him,&nbsp; places - lakes, beaches, cemeteries, streets  - he went back to for solace, a native language he inhabited and that lived in  him.&nbsp; 'Well,' I said, 'you know, quite well,  all said and done. Work's steady, that helps.'&nbsp;  I was like a phantom on the streets I'd known for twenty years. From  time to time I'd be possessed with a longing for something I'd never known,  that would turn me restless at times and at others listless; some nights my  blankets weighed heavy on my skin and when I laid my head down on a pillow it  felt like a stone resting on a stone. I could tell Nina about it all, and she  understood though it hurt her and she used it against me in her rages, but I  couldn't tell Marco these things.&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;In the three days he spent with me Marco acted  as if we'd never been apart for eight years, but instead of regaining my trust  he had some sort of drunken interlude with Nina. During one of his tipsy  late-night calls after he went back in Rome I told him I'd walked out on her in  anger some months after his visit - not because she or I had found someone  else, but because of her drugs and her drinking, because she'd lied to me once  too often, because it was all dead. He told me he had something to confess.  'About Nina and me.' 'She told me all that,' I said; I was willing to forget,  but he was obviously embarrassed and wanted to put things right. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I heard his version  about a year later, in the EUR flat he'd borrowed from his parents with whom,  until recently, he'd been living in Frascati after his marriage fell apart. He  sat there as the night wore out, drinking wine and smoking Marlboros, shirtless  and in shorts, his eyes threaded with red, his large hands with their short fingers  resting palm-upwards on his bare knees, and he told me, in a hot torrent of  broken phrases, how Nina had&nbsp; sat beside  him and kissed him on the mouth, in her sitting room one evening when I'd left  him alone with my key and with her, kissed him and touched him till he was on  fire, and when I came back slightly earlier than expected from the evening  class I taught he'd heard the bell ring and pushed her away, hard, so she'd  tripped and twisted her wrist. He was helping her up when I'd come in and&nbsp; they said she'd fallen. 'She told me you were  the one who made the overtures,' I said. 'But it hardly matters.'&nbsp; I knew the games she played to make me feel  something but I'd ceased to care. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As we talked,&nbsp; I must have told him something about my new  routines -'reading around in search of textual satisfaction', I used to say -  thinking he'd be pleased I'd found a direction. But really I wanted to talk  about Riccarda: about the trip I'd taken with her the winter before, in a car  we'd hired, to San Francesco's tomb in Assisi, where I'd lit a candle for her  and prayed by that Catholic shrine that she'd live a few years longer, though I  was lazily mystic rather than religious and a Muslim, not a Catholic. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (It was the last time  I'd seen Riccarda. One April morning, four months after that pilgrimage, our  friend Lilla had phoned at dawn to tell me: 'Be strong. She's dead.' I'd been  wondering why Riccarda hadn't called on my birthday a few days before, as she  always did. She would have been sixty-one in May. She lived like a warrior,  someone said: she didn't give up fighting, even at the end. Neither Lilla nor I  had gone to her funeral. I'd spent some weeks in silence. And then Lilla had  called again. 'Come over to Rome. Take the next flight  you can get. We need to grieve a little together.' I'd hesitated. She'd said:  'I'll drive you to Assisi. She'd like  that.'&nbsp; I booked a flight and flew out  two days later. When I&nbsp; reached Rome, I'd called Marco - on  impulse, or from a sense of duty to the past, I don't remember why - and he'd  driven over immediately to pick me up. 'I'm sorry. I don't really know what to  say. I know how much she meant to you.' Somewhere, I thought, he held a part of  the young man I'd been who'd fallen so briefly&nbsp;  in love, and a memory of the woman I'd loved then, though he'd never  liked her.)&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I may have been quiet,  or seemed uncaring, as Marco spilled out his stories about Nina over red wine,  because when I tried to tell him about my conversation with Riccarda he began  to shout. 'You're the coldest and most narcissistic man I've ever known. And  you're dull and lazy. You&nbsp; haven't even  written a book or made a film or done anything else with your life. I'm  disappointed in you . You used to be fun, Mehran. You've lost all sense of poetry  and your love of it: you're teaching foreigners the dullest details of your  language to turn them into spies. You can never have a real relationship, you  aren't capable of that, you've been attached for years to the apron strings of  a sick woman who summoned you to entertain her when she was bored and always  took advantage of you, and now you're obsessed with her ghost. Very convenient.  And what you've played at all these years with Nina, who is also a walking - or  should I say limping - disaster, is a vicarious, virtual game. I'm not shocked  that she walked out on you; even her betrayals were only attempts to bring down  your walls of ice.' <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 'You're paralytic.' I  got up to leave, feeling unsteady myself. (I'd always&nbsp; hated red wine.)&nbsp; He didn't offer to drive me back, which was  as well because he'd been drinking so much and smoking hashish, too. I should  have been drunk as well, but only felt cold in the mild night weather and my  eyes were stinging from lack of sleep. I took a couple of buses to get back to  Lilla's place in Trastevere at dawn. We were leaving early for Assisi.&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I wished I'd reminded  Marco that I was the one who'd walked out on Nina in cold anger; that even when  she'd given me an ultimatum I had never turned back. Marco seemed to be  discontent; along with the Tantric philosophy he'd been endlessly researching,  he was studying psychosynthesis or some such arcane discipline that was  shadowing the oddest angles of his life, including the fragile corner that was  our friendship. I hadn't really wanted to see him; I was too preoccupied with  Riccarda's death. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 'What's with that man?'  Lilla asked on the road from Rome to Assisi. Years before, they'd  had a long argument, over plates of gnocchi and glasses of white wine at Riccarda's  table, about the architectural politics of the South Bank and the Hayward  Gallery where Lilla was exhibiting her sculptures. He'd called it a  concrete rabbit hutch, the living prison of culture; at one point, I'd thought  she was going to throw her glass of wine in his face. Then she'd seen him the  night before when he came to pick me up from the cafe at the corner near her  flat. 'He seems tormented.&nbsp; So much  anger. And envy. Or jealousy. Something left unsaid between you? He looked  so...confrontational.'<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;Guilt, I thought on the slow drive out of Rome, often makes the  guilty offend the innocent.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; He'd&nbsp; been so close to me that Roman summer ten  years before that I'd been able to let my joy in my passion for Riccarda spill  over into our friendship, and reliving that joy in words, or in his silent  company, had nearly doubled the pleasure of my yearning. He'd taken me to Como and Bracciano and  Frascati and we'd talked and talked and sometimes we hadn't; we'd climbed  hills, and played games in ancient Etruscan cemeteries or in the Ostian sea.  Then, at some uncertain moment, we'd let it all slip away, the companionship  and the conversations and the unvoiced tenderness. Or maybe I had. At some  point restlessness had become my real companion, closer to me than anyone I'd  ever known. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I remembered how we'd  struggled once, on a hot Roman evening by the river bank in the shadow of  Sant'Angelo, to translate those words of Shauq that ended 'The Poison of Love':<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 'Ishq men hamne ye kamaai  ki<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; dil diya gham se  aashnai ki'<br>
              I'd come up with something like this: 'For love's labour, this is what I  earned/My heart I traded/and the craft of grief I learned'. And Marco had  laughed and said, 'But all it means is this: ''Questi sono i miei&nbsp; guadagni dell'amor/Ho dato il cuore e  conosciuto il dolor. So much easier in Italian!'' It really was much closer to  the bareness and musicality of the original.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Driving in the pale  sunshine past Umbrian fields on that trip to Assisi, I told Lilla, as I'd tried  to tell Marco the night before, how I'd recounted, on another drive, in another  season,&nbsp; another chapter of my story and  Nina's to Riccarda, and I must have shuddered then because Riccarda had said:  &lsquo;Don&rsquo;t do that. Have you ever thought that in some way you might have hurt her  - might still be hurting her - as badly as you feel she hurt you? Let go,  Mehran, let go.&rsquo;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;</p>
            <p><strong>5.</strong></p>
            <p>Three years after Riccarda died I visited Karachi for the first time in  twenty-seven years. Somehow I wasn't surprised when Nina rang me from the caf&eacute;  below the apartment block I was visiting in Zamzama, as if it hadn&rsquo;t been  nearly seven years since we'd parted. We talked all day until she dropped me  off, too late for dinner, at the Defence house of the aunt I was staying with. She&rsquo;d  almost given up drinking but was still depending on painkillers to see her  through everything. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; She moved back to a  flat across the road from me in London that autumn. I was  over forty, taught long hours at the University (I'd been appointed a lecturer)  and spent a lot of time alone, reading or listening to music, and most winters  I'd travel away from the sting of winter, to India or Bangladesh or Java,  because I could afford to now. But often in the evenings I would&nbsp; walk over to Nina's place and, sitting  shoulder to shoulder holding hands with all attraction spent, we'd listen to  the songs of Noor Jehan or sing or recite verses we remembered by heart;  sometimes we'd read to each other from books of poems we'd brought back from  Pakistan, that jagged free verse our contemporaries were writing and I'd learnt  to understand. She'd say she liked their work, but it was the old masters she  loved best.&nbsp; Not even Faiz could make her  thrill like Ghalib, or Daagh, or Meer. But then we discovered Parveen Shakir:  I'd dismissed her for years as a lyricist who could only write about the malady  of love, but when she died in a freak automobile accident the obituaries forced  me to look at her work again. Thought it was the discipline of her syntax and  the almost Persian grace of her complex vocabulary that drew me to her verses,  I could hear something in her voice - a yearning, vulnerable intimacy, born of  our time and our generation - that spoke to Nina.&nbsp; (And there were verses that could have been  about our relationship .'We ought to have met/in a kinder age/in the hope of a  dream/in another sky/or another land.') We planned for a while to translate her  into English.&nbsp; But it was Parveen's broken  marriage, her life as a single mother, and most of all her early death Nina was  obsessed by. 'She'd done so much at that young age. She didn't reach her  forty-second birthday. Look at me, I've done nothing yet, and I'm not even  going to live to see forty.'<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; At thirty-eight, Nina  was shrunken and skeletal, her eyes huge and leaf-brown in her little  wax-lantern skull. 'I look like Morticia Adams,' she'd groan when she caught  casual sight of herself in a mirror. She was almost always in a wheelchair: if  she took too many steps without a stick, she'd fall. The rumour was that during  the years she lived in Karachi she was taking heroin.  She'd come back to London to escape from the  habit into the relative ease of prescription drugs.&nbsp; I'd learnt not to ask more than she told me.  But she'd been a part of me I'd torn out long ago, a part I'd never understood,  or even admitted to losing, and now that I had ceased to feel the pain of  amputation I could care for her from a distance. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; At imes she'd kiss the  tips of my fingers and tell me that if she did live on a year or two I'd have  to stay with her, and other times she'd turn her head and say we never would  have made it, she and I, even if she had been well. 'We met too late. Or too  early'. (In another sky.Or another land.)<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; One summer evening she  said: &lsquo;I&rsquo;ve become a liar: I lie all the time to doctors to get my painkillers.  I make my children lie. I feel like a thief. If it weren&rsquo;t for my kids I&rsquo;d just  jump out of the window. I can&rsquo;t live like this any more&rsquo;.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; On the last evening of  '98, she rang to ask what I was doing: she was on her way to dinner at a  friend's. 'I've got bronchitis,' I said. 'I'm in my dressing gown. I've  cancelled an outing. These years that come and go don't seem to matter much,  any more.' 'Well, maybe see you...tomorrow, then?' I settled down with a book  of wonder tales in Urdu and switched the TV on to a cable channel that was  playing mellow jazz. At 9, the doorbell rang, and there she was, wrapped up in  a great beige cape in a wheelchair pushed by her Javanese carer. Her eyes were  lined with kohl, her lips blood-red; her face, nestling in a hood, had some of  its prior glamour. She'd brought me two brown paper bags full of my favourite  Persian food, grilled lamb and buttery rice and yoghurt with dill and hot bread  fresh from the oven, and she sat and watched me eat before she went off in her  wheelchair to see the old year out with her friends.&nbsp; 'I'm moving to Brighton this month,' she said  at the door. 'I'm happiest by the sea. It takes me back to Karachi.' I left the curtains  undrawn and watched fireworks light up the London sky. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A few days before her  birthday in April, she rang me up to invite me to celebrate with her in Brighton. When, a day or so  before the party, her cousin rang to say: 'Come over immediately, she&rsquo;s been  run over, she's in and out of a coma, she asked for you this morning.' I  thought she was&nbsp; joking, but it was true:  she&rsquo;d kept her word, about not living to see forty. A hit-and-run truck-driver  had smashed into the car her cousin was driving. The drivers survived, she  didn't.&nbsp;&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Among the cassettes I'd  left with her when we parted years before was Tahira's recording of the lover's  lament from 'Zehr-i-Ishq':<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dekh lo aaj ham ko ji bhar ke<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; koi aata nahin hai phir  mar ke<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; khatm  hoti hai zindagani aaj<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; khaak  men milti hai javani aaj<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; chup  raho kyun abas bhi rote ho<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; muft  kahe ko jaan khote ho<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; samjho is shab ko shab  baraat ki raat<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ham hain mehmaan  tumhare raat ki raat<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; chain dil ko na aayega  tujh bin<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ab ke bicchre  milenge hashr ke din...'<br>
              Nina died six years to the month (and almost to the day) after Riccarda.  Two days before the fortieth birthday she'd always said she wouldn't live to  see. I saw her face one, final time, almost free of pain, at the mosque in  Whitechapel where we read funeral prayers before they flew her coffin to Sind, to bury her in the  cemetery by the shrine where her ancestors lay.&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nina, Riccarda. My  night-guests, my dream-visitors who died at dawn, interred in the twentieth  century.&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I left for my first  trip ever to New York a day or two after  Nina's funeral. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
              <p><strong>6.</strong></p>
              <p>Lady L, on the other hand,&nbsp; lived  to be ninety-six. I came upon the notice of her death by accident last winter,  when my sister was trying to remember the name of an aristocratic bounder who  had murdered his nanny. 'Wasn't he Lady L's nephew?' 'It's Langdon you mean,'  I said. 'Her nephew was Lambert, the Tory politician.' I looked her up on the  web and discovered she'd been dead a few months, since the summer of 2008.When  she retired she'd returned to the Northern town where she was born, and had a  late flowering as a fire-breathing Evangelist in the local parish church.&nbsp; The obituaries confirmed the rumours about  her activities in the world of espionage and political skullduggery. But unlike  the shock of some many death notices - when you discover someone you once knew  or cared for as been gone a while without your knowing - the only surprise this  time was her late-blooming religious mission, and that she'd lasted so long.  I'd thought she'd been dead many years.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We  are born, we die, and sometimes, for a while, we do something in between.  Sometimes we live as though we were dead, or we die while we're living. Most  often, though, our lives are just afterthoughts, bookends, epilogues.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>
            <p><strong>7. </strong></p>
            <p>I&rsquo;m in Rome again, for a  conference and a book launch. It&rsquo;s April. I haven&rsquo;t been back since Riccarda&rsquo;s  funeral sixteen years ago. I&rsquo;m having dinner in that Trastevere flat I I first  visited twenty-nine years ago with Riccarda; Lilla and her long-time companion  Flavio have invited me over with a group of his academic colleagues. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Of all of us, Lilla has  possibly traversed time best. Her once-spare body is imposing now, her long  blonde hair a grey rain-cloud. She has her grandchild, her garden, the wounded  animals that come to her for shelter. At sixty-nine, she only carves in  driftwood; she says time's too short for working with stone. She lives in the  country and only comes to Rome for moments of what  she calls digression. But she writes poetry, too, and translates verses from  the east: Kabir, Meera, Roopmati. (Years ago, she guided Riccarda into Lady L's  classes, though I never really understood why.) <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Lilla, I reflect, lives  life like a continuous prelude.&nbsp;&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; An archaelogist friend  of hers is talking about a man called Marco, who spends six months of the year  leading workshops on spiritual self-development in Delhi,&nbsp; where he lives in a flat beside Humayun&rsquo;s  tomb, and&nbsp; the other six in an Umbrian  farm, from which he emerges occasionally to teach a seminar at some Institute  in Rome. He's apparently had a succession of partners, and a couple of children  with different mothers. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;Marco who?' <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;Marco  Messina&hellip;&lsquo;.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (Yes, it&rsquo;s him.)<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;I told him to join us  tonight, said he'd be here, rang to say he was on has way, but hasn&rsquo;t showed  up. Your name seemed to register with him, though. Do you know him? He was in London - oh, years ago, says  he studied with Professor Lambert too, graduated around the same time&hellip;'<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;Only vaguely. We  weren't in the same year.&rsquo;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;(Apparently he&rsquo;s made a lot of successful  documentaries about Sufi shrines all over the world, and is now translating  Rumi into Italian; he's seen as something of a Sufi philosopher in certain  circles, not a convert to Islam, but an advocate of Schuon and Burckhardt and  their theories of the essential oneness of all faith and of eternal knowledge.  He must, at some point, have resurrected his Persian. Or, knowing him, acquired  a willing apprentice to do the hard work for him. I wonder whether he ever  forgave me for whatever it was that made him so angry with me, though I've long  forgotten exactly what it was.)&nbsp; <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The after-dinner  conversation turns to metaphysical poetry, to the relative merit of the Indian  and the Persian mystics, and Lilla, whose new translation of The Poison of Love  I've introduced and am here to launch, says: &lsquo;Ask Mehran, he studied Persian  Classics with Lady L. He must be something of an expert on Rumi and  Hafez.&rsquo;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;Lady L? She only  taught us grammar and translation.' I pause, pour myself some water, light a  cigarette. 'We learnt the austerity of Persian's rules, not the glory of its  excesses.&rsquo;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </p>            <P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
