<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--

}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue8/menu_issue8.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue8/leslie_woodard/artwork.html','','width=600,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="292" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">The Tale of the Pegasus <span class="texto2">by <a href="../../issue8/leslie_woodard/bio.php" class="link3">Leslie Woodard</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           &nbsp;<br>
                      &nbsp;<br>

              In the last minutes of the last hour of the day of the summer solstice  as Miss Plinx Stillwell was lounging in her backyard, a herd of pegasus flew  over. Miss Plinx never doubted for a moment that they were real, for she heard  the sound of their wings roll in on the summer breeze like the coming of a  storm. She saw their silhouettes pass before the moon, and she watched their  shadows sweep the dead brown grass. <br>
              No trace of shock or surprise elaborated the movements with which she  gathered herself from the chaise and returned the bottle of Coca Cola she&rsquo;d  been sipping to the iron table. She took time even to notice the cherry red  print of her lips like a kiss on the bottle&rsquo;s rim. And then, leaning on the  pearl handle of her cane she crossed the yard, following the path of the  shadows to the end of her property. There they passed out of the moonlight and  vanished.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            &nbsp;&nbsp;&nbsp;&nbsp; She stood at the fence line which separated  her from the rest of the town and continued to stare at the sky. The cane was  poised against the gate, and the wisp of silver gray hair which had come loose  from her braid was the only thing that moved. And then she sensed someone.<br>
&nbsp;&nbsp;&nbsp;&nbsp; His coming penetrated the deepest layers of  her skin even before she heard the crunch of gravel beneath the heels of Jackson  Baker&rsquo;s boots. He was on his way home from the town meeting, hurrying like a  criminal from the scene of a crime. But when he saw her he stopped. <br>
&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;How now, Miss Plinx, still haunting the  night?&rdquo; He drew a tobacco pouch from his pocket and rolled a cigarette. As he  lit up, he asked from between his teeth, &ldquo;And what might you be staring  at?&rdquo;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp; She did not need to look at him to know he  was standing on the road with the broad brim of his hat cocked down, his feet  apart, and his heels dug in - standing on the road despising her. He had ever  since the death of his father for which she was blamed. And since his rage was  so particular, so personal in nature, he had become the mouthpiece for the  grudge of the entire town. Even so, she could not return his hatred.<br>
&nbsp;&nbsp;&nbsp;&nbsp; If she answered him, he would pounce on  each of her words, shoving them into his pockets like the marbles of a child&rsquo;s  game. Then he would run off to set them into motion. By morning, they would  have ricocheted all over town. That idea suited her fancy very well so she  decided not only to answer him, but to answer him truthfully. &ldquo;I am waiting for  the pegasus to come back.&rdquo;<br>
&nbsp;&nbsp;&nbsp;&nbsp; Jackson Baker prided himself on his  heritage as a black, southern gentleman. So in deference to a &ldquo;lady,&rdquo; even a  crazy woman not deserving of the term, he looked where she was looking before  he said, &ldquo;Now, Miss Plinx, you know there&rsquo;s no such thing as a pegasus.&rdquo;<br>
&nbsp;&nbsp;&nbsp;&nbsp; She had expected as much and there was no  need to offer anymore. <br>
&nbsp;&nbsp;&nbsp;&nbsp; Jackson Baker glared at the pearl-handled  cane, turned and headed back toward town. At the crest of the hill, just before  he disappeared, it seemed the words he had spoken at the town meeting, that  they had seconded, echoed so loudly in his thoughts that she heard them: <br>
&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Something must be done about Miss Plinx.&rdquo;<br>
&nbsp;&nbsp;&nbsp;&nbsp; She knew how he felt. She knew how they all  felt but it didn&rsquo;t matter. The pegasus would be back, and so she would not be  there if they came to carry out their machinations. She took up her cane and  returned slowly to her chaise. Miss Plinx had just passed her 71st birthday and  she considered it her right to be comfortable while she waited.<br>
&nbsp;&nbsp;&nbsp;&nbsp; She lay down, took hold of her braid and  pulled it in front of her, letting it wrap round her neck. &ldquo;Remember,&rdquo; she  said, gathering the strands together and caressing their ends, &ldquo;when you were  shiny and so black.&rdquo;<br>
&nbsp;&nbsp;&nbsp;&nbsp; She thought of the astronomy book that had  belonged to her father, of the ragged and dog-eared page she had smudged with  her fingertips because it had never been enough to read the words. She needed always  to touch them, to make herself a part of their meaning. <br>
<em>&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Some stars are so  distant, and it takes so long for their light to reach us that by the time we  see it, we are actually seeing yesterday.&rdquo;</em> <br>
&nbsp;&nbsp;&nbsp;&nbsp; She looked at the smallest speck of silver  blue light in the sky and said, &ldquo;Somewhere in the universe I am young and Nick  Baker is still alive.&rdquo;<br>
&nbsp;&nbsp;&nbsp;&nbsp; She was caressing her braid when she fell  asleep. <br>
&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp; The town to which her father had brought  her and towards which Jackson Baker was hightailing himself, was surrounded by  four hills - the feet of the Appalachians with toenails painted red by the  valley&rsquo;s clay. The name of the town didn&rsquo;t matter much to anyone but itself,  and it hid quietly in the shadows, believing that if it spoke softly and  correctly no one would bother it. A little town it was of plain folks who  earned their livelihood at the sawmill up the road, and who kept their windows  open, their doors unlocked, and the lids of their garbage cans tight. <br>
&nbsp;&nbsp;&nbsp;&nbsp; The cow paths had laid the map for the  narrow curving streets, along which old houses with big porches sat close  together like fat cats on a fence. Only Main Street was straight. There, the  General Store, the doctor&rsquo;s office, the school, the stables, the undertaker,  and the church monitored the movements of passers-by. The speakeasy lurked on  the corner, just out of sight. The gas lamps would eventually be replaced by  electric lights, horses and buggies by automobiles, and after the stables  burned to the ground, a fire house would be built on the gutted lot. But the  town itself would change little from the time Plinx first knew it. <br>
&nbsp;&nbsp;&nbsp;&nbsp; The Stillwells had arrived at high noon on  the Silver Crescent, Plinx perched on her father&rsquo;s arm like a small parrot. She wore  a blue double-breasted coat with brass buttons that glistened in the sun like  plumage. The pair appeared against the backdrop of the town like exotic figures  cut onto the glass of an old and undeveloped photograph. The porter stood  beside the train, watched Plinx and her father quizzically, and wondered,  despite the destination on their tickets, whether this town was where they had  intended to debark.<br>
&nbsp;&nbsp;&nbsp;&nbsp; They moved into the large house at the top  of the smallest hill. There were other houses of other families built into  other hills as the town had begun to outgrow the valley in between, but Plinx&rsquo;s  father chose the weather-beaten one with the large open porch and creaky swing,  its property bordered by a split-rail fence and dotted with Georgia pine. He  liked that the house was so weather-beaten that painting was impossible. He  liked the melody the swing sang at night and the pine needles which covered the  ground and killed the grass so he didn&rsquo;t have to tend the lawn. But most of all  he liked the hill, which provided the perfect place to use his telescope. He  valued it and his baby daughter over all things in the world, because he&rsquo;d  built them both himself.<br>
&nbsp;&nbsp;&nbsp;&nbsp; His wife had come from a well-to-do family,  and, when she died, she left him enough money to spoil both himself and his  Plinx. So Jeremy Stillwell bought a pram, an elegant blue lace pram which he  ordered from the Sears and Roebuck catalog. Every afternoon they went down the  hill for a stroll.<br>
&nbsp;&nbsp;&nbsp;&nbsp; The town graciously allowed him such  indulgences because it believed him to be neither impressive nor elegant. The  hat he insisted on tipping had a hole in the brim. The chain of his watch fob  was rusted and he used a pocket knife threaded through his belt loop to hold it  in place. They believed such eccentricities came from over-education up north  but that he was still basically plain. They didn&rsquo;t even mind too much that when  they saw his daughter the word &ldquo;beautiful&rdquo; seemed to slip from their lips, even  when they didn&rsquo;t intend it. So for two years no one blamed Jeremy for parading  around, tipping his old hat and spoiling his Plinx. <br>
&nbsp;&nbsp;&nbsp;&nbsp; And then in one afternoon, one particularly  fine afternoon when everyone felt safe ignoring the old folks whose aching  bunions predicted a storm, everything was changed. <br>
&nbsp;&nbsp;&nbsp;&nbsp; Mavis Thompson was sweeping the red dust  off her porch. It was the third time that day that the flesh on the underside  of her arm had jiggled with the stroke of her broom. Her voice was loud, and  her neighbor, Blind Jacob Adams, heard her as she swept her greetings down on  the Stillwells.<br>
&nbsp;&nbsp;&nbsp;&nbsp; The pram and the broom were parked by the  side of the porch, and Jeremy brought Plinx up for some lemonade. How the  discussion of family lineage quite got started no one remembers, but as the  blue lace pram perambulated away, Mavis Thompson knew that Jeremy Stillwell&rsquo;s  grandfather was a captain in the old French armada, that his mother was the  granddaughter of Powatan, chief of the Algonquin Indians and that neither her  family nor the family of anyone else she knew had quite such a pedigree.&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp; Word that Jeremy had been bragging on his  family passed from Mavis to Blind Jacob, and by then Jeremy Stillwell was an  arrogant fool who thought his father was a duke. And then Blind Jacob told Fast  Black Rollins that he&rsquo;d seen Jeremy swell up when he told the story like the  melons in mid-July, and nobody ever questioned what Blind Jacob saw because  they all knew he saw the inside of things instead of the outside and the inside  always counted for more. And when Lucius Feldman got through with him, Jeremy  Stillwell believed he was descended from kings and thought he was too good to  associate with anybody whose people came from slaves. The preacher said it was  a sin sure because, &ldquo;pride goeth before the fall,&rdquo; and his wife heard him say  it and nodded her head all the way to the General Store where she told Rhanna  Lee Whitehead that if you asked Jeremy Stillwell, his yellow backside wasn&rsquo;t  even colored and that was why his family had to live up on that hill. <br>
&nbsp;&nbsp;&nbsp;&nbsp; By evening that same day, the town had the  distinct impression it had been watched, judged, and snubbed, and it didn&rsquo;t  like it one bit. A couple of folks noticed that just before the sun set behind  the hills, the sky looked a little green but nobody commented on that.<br>
&nbsp;&nbsp;&nbsp;&nbsp; Now Jeremy Stillwell had no idea what had  got started that day. He had mentioned the sea captain and Powatan&rsquo;s  granddaughter because he considered it his responsibility to provide everyone  with interesting conversation. He went home oblivious to the town&rsquo;s rumblings,  took up his telescope and counted the craters on the moon. The four year old  Plinx stood at his side, barefooted, burying her toes in the pine needles and  the dead brown grass. They didn&rsquo;t stay out for too long though, because it  rained. <br>
            &nbsp;&nbsp;&nbsp;&nbsp; As Miss Plinx was turning over on her  chaise, dreaming of the cool needles and the breeze on her bare young legs,  Jackson Baker was walking into the Speakeasy. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Prohibition was little more than a thing  the kids got tested on in history class. But folks in town discovered it just  wasn&rsquo;t a bit of fun to drink if you weren&rsquo;t always afraid the law was coming  after you at any moment. So Fat Sam Carver bought the bar, climbed up a ladder,  the third rung of which broke beneath his weight, stood on the tips of his fat  toes and boarded up the windows. He took a drill in his fat hands, made a hole  in the door and everyone just pretended.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Plinx Stillwell&rsquo;s gone round the bend,&rdquo;  Jackson announced as soon as Fat Sam had looked out of the peep hole and let  him in. He took off his broad brim hat, laid it on a table, sat down, and began  to poke at a cigarette burn in the red and white checkered cloth.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Now why you come in here acting like you  got some big news?&rdquo; Fat Sam wiped his hands on his apron. &ldquo;We just discussed  that down at the meeting.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Cause it&rsquo;s gone past the discussing  point.&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Jackson Baker was tall and lean as his  father, Nick, had been, but time had worn the leanness gaunt and the features  of his face hard. He had his father&rsquo;s wavy black hair, but the broad brim hat  had slicked it flat to his head, so he looked like a snake.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;What makes you say that?&rdquo; Fat Sam asked. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Give me a whiskey and I&rsquo;ll tell you.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Fat Sam poured a whiskey into a Coca-Cola  bottle out of respect for tradition, and brought it over. Sawdust crunched  under each of his steps. He sat down, lowered his head, which added a fourth  chin to the usual three, and looked Jackson directly in the eye. That was what  Fat Sam did when he wanted to see the seriousness of a thing. The other men,  who&rsquo;d stopped by Sam&rsquo;s for a nightcap, halted their conversations to listen. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Well, you know I have to go past her place  to get home,&rdquo; Jackson began.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Ain&rsquo;t it faster to go by the south road?&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;No. And that&rsquo;s not what&rsquo;s important  anyway.&rdquo; He took a long sip of his whiskey, so everyone had to wait and be  punished for the interruption. &ldquo;Like I was saying, I&rsquo;m going past her place and  I see that damn cane of hers leaned up against the fence, and then I see her  standing there like some kind of statue, staring up at the sky.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;My grandmamma said her daddy used to do  that.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Would you shut up.&rdquo; Another sip. &ldquo;So I  decide to be nice, smoke a cigarette, make a little conversation with the old  lady.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Thought you told me you hated her.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Shut up!&rdquo; Sip. &ldquo;So I ask her what she was  doing out so late, and she tells me she&rsquo;s waiting for a pegasus.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;A what?&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;A pegasus, it&rsquo;s a horse with wings.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Lord have mercy.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Yeah, now you&rsquo;re getting it. Anyway she  starts telling me she had this conversation with the thing and it told her it  would be right back and she should wait for it.&rdquo; He lighted a cigarette to give  the information time to sink in. &ldquo;Now I&rsquo;m not one to be telling tales out of  school, but it&rsquo;s starting to get a little chilly at night up where she is.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Oh come on now, it is not chilly.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Jackson threw the cigarette down and  crushed it beneath the heel of his boot. &ldquo;Maybe not chilly to you, fat man, but  for a little old lady...why she could catch her death of cold. Then folks from  the county would be over here talking about how we let her die.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; That silenced the bar. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Because the town was small and because  everyone in it (despite a plethora of skin tones) was of the same race,  segregation, like prohibition, stayed in its grave as long as the town&rsquo;s folk  stayed within the town&rsquo;s borders. They could have looked on this as a form of  segregation but since the town didn&rsquo;t want any more to do with its white  neighbors than they wanted to do with it, the local Klan took time out to wash  its sheets and there was a relative if imperfect peace. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Maggie Wheatlock once nailed two planks  together and burned a cross in her own backyard. She wanted to scare her son so  he wouldn&rsquo;t stay out so late, but the boy found out and it didn&rsquo;t work. But  even so the town remembered times when borders were less defined and things  were not so peaceful. Everyone knew the family names that had been erased from  the registry after the last male heir had come home, shackled to the back of a  horse, blood-soaked and without his genitals. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; So the one thing the town did not want was  a visit from the county sheriff who, friendly as he might seem, was still  white.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;What do you think we ought to do?&rdquo; Fat Sam  asked.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Jackson Baker took a moment to bask in the  fact that the entire bar was looking to him for direction, and as he did an  idea was struck like a match in his mind. He had come there planning to content  himself with a couple of whiskeys and the stirring of some vicious but  basically idle gossip. But the intent faces around him, suggested the means to  finally do much more. &ldquo;Seems like we have a responsibility to get her to  someplace where she can be properly looked after.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Fat Sam shook his fat head. &ldquo;That&rsquo;s not  going to be easy. My Grandmamma told me, Miss Plinx got a violent streak.&rdquo; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; But anyone passing by the fence which  separated Plinx from the rest of town would never have known it. The wind on  the hill had picked up slightly, and the pine trees and the porch swing were  singing. Miss Plinx was still lounging on her chaise, harmlessly dreaming of  roller skates. <br>
            &nbsp;&nbsp;&nbsp;&nbsp; The town had begun finding fault with Plinx  almost immediately after its perceived snubbing. She was Jeremy&rsquo;s pride and  joy, so what better way to get at him than through the shortcomings of his  daughter. It was also about this time that folks began noticing that the  Stillwells did not attend church. While everyone was dressed in their  Sunday-go-to-meeting clothes, walking reverently through town, Plinx was on her  window seat, her knees hugged to her chest and a book in her hands. If the town  had known the title, it would have been even more appalled. But the advent of  the &ldquo;violent streak&rdquo; did not occur until Plinx was thirteen. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; The other girls her age were all struggling  to negotiate legs and arms which seemed to grow longer every night while they  slept. But Plinx remained remarkably graceful and coordinated and although she  was little more than eyes, knees, feet and hair. It was a source of irritation.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; She had long outgrown the blue lace pram,  and so on her thirteenth birthday, Jeremy presented her with a magnificent pair  of roller skates. They had a cunning silver key which allowed Plinx to adjust  the fit exactly, and bright red calves leather straps.&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Plinx put them on nearly every afternoon  and sailed down the hill, the breeze whipping her dress up behind. The ladies  in town, who noticed their church-going sons smiling in Plinx&rsquo;s wake, said it  was indecent for a girl-child to go around like that with her dress flying. But  Plinx never heard them. Their words were drowned by the &ldquo;whoosh&rdquo; of her skates.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; One afternoon, as Plinx was sitting on the  steps of the general store making an adjustment, one knee up and her panties  showing, Nick Baker came by on his bicycle. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Nick was generally considered the finest  plum the town had ever produced. An easy-going, charming boy, tall, lean, his  hair black and wavy and his skin smooth and dark as an oil slick. The town  watched him, smiled to itself and said, &ldquo;That boy will amount to something  someday.&rdquo; And no daughter&rsquo;s mother ever fell asleep without praying he would  someday be her son-in-law. But that afternoon as the sixteen-year-old muscles  in his legs, buttocks, even his forearms undulated with the pumping of the  pedals, Plinx noticed him. She gave the first smile she had ever given to a boy  and Nick Baker smiled back.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; He was so busy smiling that he didn&rsquo;t  notice Greezly Smith, or Smiff as most folks said it, coming towards him.  Greezly was the town bully who lived in a shack at the base of the hill  opposite the one on which the Stillwells had taken up residence. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; His mother ran off with a Snake Oil  salesman when Greezly was five. After that his daddy took to drink and Greezly  was left to drag himself up as best he could, for there was no one around to  raise him. He was a large, angry boy who devoted himself to the cultivation of  meanness. He went to school sporadically, but was expelled after he set fire to  his desk. Folks knew something ought to be done about Greezly, but they were  all just a little bit afraid of him. So he lurked around town, knocking the  other children down in the dirt and stealing their lunches whenever he could  catch them. And when he couldn&rsquo;t, he went out in the woods, put homemade  firecrackers in frog&rsquo;s mouths and watched them explode.&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Greezly came towards Nick Baker that  afternoon, his teeth bared like a rabid dog and his sights set on Nick&rsquo;s bike. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Nick rode right into Greezly&rsquo;s grip, too  engrossed in Plinx to avoid it. Greezly caught hold of the handlebars and gave  the bike a crack the way the ladies cracked freshly washed sheets before  putting them on the line. Nick fell off, Greezly jumped on, turned the bike  around, and rode away laughing. Nick was too stunned to even try to go after  him but Plinx wasn&rsquo;t. She had her skates in her hand and as Greezly passed, she  let fly into the spokes. The pedals jammed and Nick Baker&rsquo;s bicycle, like an  obstinate horse, threw Greezly forward into the dirt. He skinned his knees,  elbows and face from his chin to his forehead. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; It was the first time anyone, let alone a  girl, had ever bested Greezly and he couldn&rsquo;t bear the shame. He ran off  towards home, bleeding and embarrassed. Plinx doubled over with a laugh too  deep and too round for any thirteen-year-old girl as Nick picked up the bike,  which was undamaged, and rode away. But not without offering a smile and a last  look of appreciation for all that was Plinx. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Now anyone else would have been a national  heroine by morning, but because it was Plinx the town saw it as an act of  wanton violence. Why she might have killed poor Greezly and after all, it  wasn&rsquo;t his fault he came up so hard. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Mavis Thompson led a delegation up the hill  to speak to Jeremy. He needed to be told what his daughter had been up to. And  tell him they did, with a particular emphasis on the fact that her panties had  been showing when she threw the skates. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Jeremy was aware of the town&rsquo;s general  loathing for Greezly, so he couldn&rsquo;t understand the problem. He gave the  delegation the look a cricket would give you if you tried to explain to it why  it shouldn&rsquo;t be sitting on your porch singing while you were trying to sleep.  But he did promise them he would speak to Plinx.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; He went up to her room, digging his  fingernails through his hair, trying to scratch some wisdom out of his scalp,  and told her something about the appropriate behavior for young ladies. She  gave him the same look he had given the delegation, so he shrugged his  shoulders, went back downstairs, got out his telescope and counted  craters.&nbsp; <br>
            &nbsp;&nbsp;&nbsp;&nbsp; Fifty-eight years from that moment, Miss  Plinx was lounging on her chaise, asleep, laughing the same deep round laugh  she had smothered with her pillow when her father had gone.<br>
            &nbsp;&nbsp;&nbsp;&nbsp; It was decided that some help must be  enlisted if Jackson Baker was serious about them getting Miss Plinx &ldquo;to  someplace where she could be properly looked after.&rdquo; And as he watched them  take hold of the idea it was all Jackson Baker could do to keep his joy in  check. After they took her away, he would go to the Speakeasy, sit at the table  with her cane between his knees, and he would have a drink. He would smile  because his whiskey would taste even sweeter sipped from her Coca-Cola bottle,  after he&rsquo;d wiped the cherry red print of her lips away from its rim forever. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Hiram Shepherd, who had also been sipping  whiskey from a Coca-Cola bottle that evening, suggested his wife might be of  some assistance. So as Fat Sam locked the Speakeasy, Hiram and Jackson kicked  the sawdust off their boots, munched breath mints, and walked over to Hiram&rsquo;s  house. His wife, Mary, was sitting on the porch tatting lace when they came up.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; She made several mistakes and finally  pricked her finger as she listened to Jackson&rsquo;s story of how Miss  Plinx had talked to the pegasus that kissed her cheek and promised to return  after she gave it a lump of sugar. Mary&rsquo;s mother had been one of Miss Plinx&rsquo;s  contemporaries, one of the gawky girls the boys were not smiling at while they  were smiling at Plinx. So Mary had been raised on the stories of Plinx&rsquo;s  transgressions the way other children were raised on pablum. She was therefore  all too willing to help Miss Plinx get &ldquo;to someplace where she could be  properly looked after.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; It was at her suggestion that they went to  see the preacher&rsquo;s wife who, after hearing Jackson say with many apologies for  the frankness of his words, that Miss Plinx had gone so far as to tell him that  she had fondled the pegasus, agreed they must speak to her husband at once. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Jackson had sewed the fabric of his story  like a tailor who knows exactly what type of clothing will excite his client.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The preacher&rsquo;s wife chose to tell her  husband the story herself, especially the part about the fondling. She also  added that a court appointed guardian might see fit to reward the church for  its service, by donating whatever money might be left after Miss Plinx&rsquo;s care  was arranged. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; The preacher&rsquo;s father had been the preacher  of the &ldquo;pride goeth&rdquo; sentiment. And so having also been raised on large and  bitter doses of Plinx, he felt righteously comfortable pronouncing, &ldquo;It&rsquo;s all  that wild living come home to roost. That&rsquo;s what&rsquo;s made her crazy.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; And  his wife nodded saying, &ldquo;Bet she had on that lipstick even tonight didn&rsquo;t she,  Jackson.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; And Jackson confirmed that she did.<br>
            &nbsp;&nbsp;&nbsp;&nbsp; Initially, it was only cherry candy. Plinx  had a weakness for the cherry flavored hardballs which stained her lips as red  as the straps on her skates. She never lost interest in the candy, but shortly  after Nick Baker rode away on his bicycle she lost interest in the skates. By  the time she was sixteen, her attention had turned to the cherry red lipstick  she cajoled Jeremy into buying for her. She began wearing her hair in one long  thick braid which reached down to her waist, and she found that she loved to  run. Her legs unfurled beneath her in long, graceful strides, the braid came  loose, and everyone knew why it was called a pony&rsquo;s tail.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Now rumors to the contrary not withstanding,  Plinx Stillwell never went a day in her life without her panties. But the ease  with which she moved belied the fact that there was anything between her skin  and the thin cotton of her dress.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Jeremy was down at the General Store, which  also served as a post office, picking up a book he had ordered. Plinx ran by,  flashed a wave at her father, and galloped off. Jubee Whitehead, Rhanna Lee&rsquo;s  husband, watched her go. &ldquo;I&rsquo;m glad she&rsquo;s not my daughter,&rdquo; he said. And for the  first time Jeremy looked worried. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; That night when he looked through the  telescope he lost count of his craters and found he was missing his wife. He  had never missed her before. She was so much a part of him, like the beard that  grew on his chin every night, and after he shaved it off every morning was  still there under his skin. He sat down on the creaky porch swing, thought  about his Plinx and wondered what he ought to do.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; But Plinx wasn&rsquo;t worried. She was sitting  on her window seat replaying the moment Nick Baker had asked her to the church  social. She had been running up the hill towards home when she heard his voice  behind her. She could still feel the tickle of the sweat that had rolled down  the center of her back when she stopped, and the touch of his hand on her skin.  She smiled, and her mouth opened wide as if to devour what had pleased her. It  was the same smile she had given to Nick when she accepted his invitation,  without so much as a thought for her father&rsquo;s permission.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The gesture seemed unnecessary for Jeremy  never refused her anything. She told him about the invitation the next morning  at breakfast as proudly as she told him about the &ldquo;A&rsquo;s&rdquo; she earned at school.  He didn&rsquo;t say anything for few moments, and Plinx noticed a wrinkle on her  father&rsquo;s face she&rsquo;d not seen before. She didn&rsquo;t know what to make of it. But it  passed quickly as he said, &ldquo;Best that boy have you back early.&rdquo; She threw her  arms around his neck, hugged him, and ran out of the kitchen. After she had  gone, the wrinkle in his face returned.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Plinx climbed the stairs to the attic where  most of her mother&rsquo;s things were stored. She made her way through the dust and  cobwebs, past the dressmaker&rsquo;s mannequin, the sewing box, the bolt of royal  blue silk, and the stacks of letters tied with ribbon. She looked at her  mother&rsquo;s script and smiled because her own handwriting matched it exactly. She  took a few of the letters, blew away the dust, pressed them against her nose,  and tried to catch a whiff of her mother&rsquo;s perfume. She stepped carefully over  the boxes of china, and the porcelain figurines her mother had bought when her  father had taken her to Paris after their wedding. &nbsp; She touched one of the delicate figures with her finger and  imagined Paris with Nick. Jeremy had told her of the places he and her mother had  visited, and the things they had said to one another. Her parents&rsquo; marriage had  become a fairy tale to Plinx, and her marriage to Nick would be one as well.  She opened her mother&rsquo;s trunk and dug through the clothes. She found her  mother&rsquo;s wedding gown, but that would have to wait. And then she found the  crinoline party dress her mother was wearing in the photograph Plinx kept by  her bed. She snatched the dress out of the trunk, held it up in front of her,  and swirled around the attic.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The town watched with envy as the long  thick braid, decorated with a sprig of pink azalea, swirled past, for Nick  Baker would have no other partner. They had to hear the crunch of the crinoline  as Plinx pressed close to him, ignoring their edict that six inches of space be  maintained between boys and girls. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; It rained that night as Nick escorted Plinx  home, and by the time they reached the top of the hill, both of them were wet  to the skin. He stood on one side of the gate, she on the other, he leaned  across, put his hands on her bare shoulders, and kissed her. The rest of the  world melted in the rain like colored chalk until there was nothing left but  Nick. He stood before her soaking wet, with his father&rsquo;s frock coat hanging off  his shoulders, and she was sure she saw the cherry red print of her lips on his  before he walked away. <br>
            &nbsp;&nbsp;&nbsp;&nbsp; Six months after the church social, the  Japanese bombed Pearl Harbor. The newspapers allowed the town its share of the  nation&rsquo;s outrage, but except for the fact that folks had a harder time getting  tires for their trucks, the war was a very faraway thing. And then a letter  came with a photograph of Sergeant Gerald Lee Smith of the 81st Airborne  Division. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; The town hadn&rsquo;t seen old Greezly for quite  awhile. His daddy had finally pickled himself and was buried in the cemetery.  After that Greezly disappeared, and nobody thought much of him until his photo  arrived. It kind of set folks back a couple of paces. Everyone had assumed  Greezly would wind up like his father one way or another, and they felt just a  twinge of guilt about the way he&rsquo;d been treated. But they quickly forgot about  it; after all, Greezly had sent his letter to the town collectively, (he had no  one else to write to) and if Greezly was willing to let bygones be bygones the  town could certainly do the same.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Only Nick Baker seemed to begrudge Greezly  his success. Jubee Whitehead framed the picture and hung it in the window of  the General Store, and no one ever picked up their mail or bought supplies  without paying their respects. But every time Nick saw it, it fouled his humor.  Fact was, since the town held a deep resentment towards him for his romance  with the arrogant Jeremy Stillwell&rsquo;s infamous daughter, the story of Plinx&rsquo;s  skates was never told unless Nick was in earshot, and never without a mention  that Greezly had knocked him into the dirt. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Nick was working in the sawmill just a few  miles from town, trying to save enough money for college. But the sawdust that  fell from the logs seemed to pile onto his shoulders like weights. His number  must have been lost somewhere in the drum of the draft lottery because it had  never come up. But the newspaper was filled with stories of men and boys going  off to enlist. While they won battle after battle, Nick was still lying in the  dirt where Greezly had thrown him. He grew restless even with Plinx. But to  tell her what he was feeling would have been to admit himself a failure. He  wanted to go to college but he didn&rsquo;t know what he&rsquo;d do there, and he saw  himself, degree in hand, going back to work at the sawmill while Greezly was  the town&rsquo;s greatest hero. The idea soon became more than he could bear. So  without a word of goodbye to anyone, not even to Plinx, Nick Baker enlisted in  the Marines. <br>
            &nbsp;&nbsp;&nbsp;&nbsp; The wind blew the pearl-handled cane Miss  Plinx had leaned against the chaise down onto the pine needles. She wrapped her  arms around herself as she had when she was a girl, to keep her body from  shaking apart.<br>
  &nbsp;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; For a long time, nobody saw Plinx. When  Jeremy came to town and they asked, out of a desire for gossip rather than  genuine concern, how she was doing, all he said was, &ldquo;She&rsquo;s getting on.&rdquo; And  then the astronomy book came with the passage she was to commit to memory.  Jeremy left it out where she&rsquo;d be likely to see it, just as he had the roadside  flowers he gathered from time to time, the bags of cherry hardballs, even a  stray kitten he once found on his way home - anything to bring Plinx back to  life. But although she had changed the water to keep the flowers fresh, eaten  the candy and given the cat milk, most of her time had been spent on her window  seat staring at the stars.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The silence that hung between them at meals  wasn&rsquo;t born out of any resentment for her father; she just couldn&rsquo;t find  anything to say. So at dinner, on the evening that he left the astronomy book  beside her plate, she picked it up and leafed through the pages. She didn&rsquo;t  touch her food, but after a while she got up and went outside. She was still  there, reading by the full moon, bare-footed, her feet tucked under her and her  shoes abandoned beneath her chaise when Jeremy went to bed. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; She never told her father about the passage  she had read, but when he was greeted for the first time in weeks with a  breakfast of Smithfield ham, eggs, biscuits and coffee, he asked no questions.  He merely thanked The Maker that his Plinx was back, and gave her privacy each  night when she went out in the yard with the book hugged to her chest. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; It consoled her to know that she and Nick  were seeing the same moon. And as she read the passage, running her fingers  over and over it and the constellation of Pegasus pictured underneath, she felt  sure that if &ldquo;some stars were so distant&rdquo; that by the time their light reached  her she was actually seeing yesterday, the reverse must also be true. Somewhere  in the universe everything that had ever happened was still going on, and she  and Nick Baker were still dancing.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The town was not pleased at her resurgence.  When it saw her hair flying behind her as she once again ran its streets, it  lowered its chin, raised its eyebrow, and put its hands on its hips. It found a  new word as it watched her and mumbled &ldquo;hussy&rdquo; beneath its breath. It felt  certain her amorous gestures towards Nick Baker had been false. Why she didn&rsquo;t  even care that the boy was at war, and it was likely a broken heart which had  driven him to enlist in the first place.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The town sought every opportunity to  conjure the worry wrinkle between that cocky Jeremy Stillwell&rsquo;s brows. Every  time he was at the General Store someone managed to tell him what a beautiful  girl Plinx had become, always adding how difficult it was to keep a pretty  woman safe. Folks stopped him on the street to say they&rsquo;d just seen his lovely  child run by, and oh by the way, had he heard about such and such a pretty  innocent girl from the next county who wasn&rsquo;t so innocent anymore. And Jeremy  who had always enjoyed his solitude on the hill, suddenly had visitors two and  three times a week. Folks just dropping in to be neighborly. They sat with him  on the porch, watched Plinx take the coffee tray into the kitchen, and just  couldn&rsquo;t resist remarking on her graceful figure and all that gorgeous hair.  And as they left, they patted his hand and said how hard it must be for him,  raising a pretty girl-child like that all alone.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Plinx began to notice a nervousness in  Jeremy she hadn&rsquo;t seen before. Their time spent separately had always made  their time together more pleasurable. They would just run into each other at  meals and Jeremy would describe some new crater he&rsquo;d discovered and Plinx the plot  of a book or the color of a field she&rsquo;d run through that day. But now he seemed  always to be looking for her, inside the house and out. He asked her lots of  questions like where she was going, where she had been, and whom had she been  there with. He&rsquo;d always been content to wait for her to tell him things before.  But since she never kept anything from him because he never minded anything she  did, his asking didn&rsquo;t bother her exactly - it just seemed odd.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Then Gilford Stanton pulled his automobile  into town. He was standing on his running board just at the moment Plinx  galloped by. He had never seen anything quite like her before.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Gill&rsquo;s family owned the sawmill where Nick  Baker had worked and were generally considered the richest folks around. They  had sent Gill to school up north, and when he finished he had started his own  business in Atlanta. The fabric of his suit, the shine on his shoes, and the  quality of the leather in his car, told folks he&rsquo;d done quite well for himself.  He had been married but his wife had died leaving him with four children, the  oldest of whom was just a year younger than Plinx. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Now when the town found out she had sparked  Gill&rsquo;s fancy, it felt its usual irritation. Gill had a reputation for being  determined, so if he wanted Plinx he would have her, and Jeremy would be  impossible to live with after he had married his daughter to a rich man. But on  the other hand, the Stantons lived in a place where folks owned the sawmills,  not worked them. And if Plinx married Gilford, the town could lay claim to the  mill owner&rsquo;s daughter-in-law and therefore lay claim to the mill. It could be  as grand a town as the one where the Stantons lived, a town of masters not  slaves. So it rushed to embrace the girl it hated, to take pride in the creature  it despised. And as it watched her, really watched the way she ran, it smiled,  because it was sure the last thing Plinx would want was to be harnessed to a  husband, particularly not one 35 years her senior. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; It informed Gill that he and Plinx&rsquo;s father  might have a good deal in common, both being widowers with children. And after  it made certain that he knew how much Jeremy adored his child, how worried he  was about her and the exact directions to the Stillwells&rsquo; home, it sat back to  wait. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; It didn&rsquo;t have to wait long. Plinx was  perfectly charming and friendly to the man she assumed had come to see her  father. She offered him coffee and sherry on the porch and sat on the steps to  entertain him. He came often and she was glad. He was good company for Jeremy,  who seemed less nervous when he was around. And she liked talking to him  because he was interested in everything she had to say. She told him all about  her special places, this field or that brook, all the places she&rsquo;d sat with  Nick, whom she never mentioned directly. She preferred keeping him to herself,  but she relished the chance to relive the moments she&rsquo;d spent with him. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Now men like Gilford Stanton observe the  graying of their hair with desperation, because they believe it signals the  coming of the time when they can no longer excite passion in any woman save the  one they&rsquo;ve been married to for years, and with whom they have built a  reputation. But a young woman like Plinx, with a musical voice, a bright and  inquisitive manner, and a comfortable confidence in her movements, like she&rsquo;s  been in possession of her body for much longer than anyone can imagine, appears  to him like a gift. But most of all it is her hair. The shiny braid wrapping  around her neck like a thick black rope as she fidgets with her ends, chases  all sense from the mind of a man like Gilford Stanton, until all he can think  of is how that braid will feel when it wraps around him. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Gilford asked for Plinx&rsquo;s hand a month  later, and Jeremy readily agreed. He slept well that night for the first time  in ages, confident he had at last done right by his child. Gilford seemed to  genuinely adore Plinx, and he had the money to spoil her the way Jeremy always  had. So when she met him with a look of absolute horror on hearing of her &ldquo;good  fortune,&rdquo; he was totally unprepared. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Plinx grabbed the bag of cherry hardballs  Gill had brought her and hurled them to the floor. She accused her father of  giving him bait to trap her like an animal. Jeremy slammed his fist down on the  table for the first time in his life, and the vase of roadside flowers toppled  over and shattered. How dare she say such a thing and what did she expect him  to do anyway, with her running the town like somebody&rsquo;s wild horse. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; It had never occurred to her that she  wasn&rsquo;t exactly the way he wished her to be. She had always assumed she was just  like her mother. Plinx slumped into her chair in tears. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Jeremy had never made his daughter cry  before, and he was certain there was no worse feeling in the world. He listened  to the desperate rush of words with which she told him about Nick Baker, and he  was sorry. But that boy had picked up and gone without so much as telling her  goodbye. And did she think there weren&rsquo;t any women in Europe? And didn&rsquo;t she  know that no matter who a person was when they left, they weren&rsquo;t the same when  they got back? No, he had done the right thing and she would see it in time.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; So Plinx made her first trip to church. She  refused to wear her mother&rsquo;s wedding gown. That was meant only for Nick and if  she wasn&rsquo;t like her mother anyway, it didn&rsquo;t matter. She wore a plain ivory  dress, carried no flowers and clung to her father&rsquo;s arm for support as he  walked her down the aisle. The hardwood of the country church closed around her  like a coffin. And the eyes, the eyes of the town she had never noticed stared  from the pews, disliking her but terribly proud.&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Gill drove her to a hotel in the next  county for their wedding night, but several of the town&rsquo;s men got tipsy,  sniffed out the hotel, stood outside, and howled like dogs when a bitch is in  heat. But it wasn&rsquo;t until Gilford had locked their door that her last hope  died. Nick was not coming to save her, and all Plinx felt on her wedding night  was injured. <br>
  &nbsp;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Clouds covered the full moon as Miss Plinx  lay on her chaise, crying in her sleep.<br>
            &nbsp;&nbsp;&nbsp;&nbsp; The preacher said it would be best to have  the doctor with them when they went to get Miss Plinx. She might not take to  the idea of leaving too readily, and some sedation might be in order.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Jackson Baker had little trouble convincing  the doctor, whose son had received a half-a-behind full of buckshot at Miss  Plinx&rsquo;s hand. The fact that the boy had accepted a dare to come onto her  property and steal the pearl-handled cane was always eliminated whenever the  matter was discussed. Miss Plinx was an excellent markswoman and if she&rsquo;d  wanted to really shoot that boy she certainly could have, but no one ever  mentioned that either.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Someone did bring up the problem of a  competency hearing. What if Miss Plinx managed to convince some idiot she was  sane? But Jackson Baker reminded them of the &ldquo;violent streak&rdquo; which would  surely surface when they tried to take her, even though it was for her own  good, and that the county hospital would immediately administer appropriate  drugs when presented with a screaming, raving old lady. By the time any hearing  occurred she wouldn&rsquo;t be able to convince anyone of anything. He also added the  complete story of the pegasus incident with all the appropriate elaborations  until everyone was sure that this was not only the right thing, but the only  thing to be done.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; News of the plan swept up the steps and  into the houses like the red dust Mavis Thompson had swept from her porch so  many years before. And it was with the support of the entire town behind them  that Jackson Baker, the doctor, and the preacher climbed into the preacher&rsquo;s  car.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; As they were doing so, Miss Plinx reached  out in her sleep, found the pearl handled cane and pressed it between her  breasts.<br>
            &nbsp;&nbsp;&nbsp;&nbsp; Mrs. Plinx Stanton was sixteen years old  when Gilford pulled his car to a halt in front of his house. It was on the  outside edge of Atlanta in the black section, where the streets looked much  like the streets she had left behind. Except for the fact that the furnishings  were more lavish, she might have been in anyone&rsquo;s house back in town. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Now the one thing she had learned on her  wedding night was that it was something she was not going to let happen again.  So the first thing she located was the ornate mahogany liquor cabinet. Nick  Baker had once told her that with enough moonshine, you could convince a man  he&rsquo;d done anything the night before. Plinx discovered sherry worked just as  well. She managed to maintain her sanctity, while keeping her new husband  bursting with pride. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; The children looked at her as if their  father had just brought a chicken into the house and told them it was their new  mother. Then they went on blithely doing whatever they pleased. Plinx didn&rsquo;t  care. She had no desire to be a mother to anyone. But the one thing she had  never had was a sister, and she found that in Gilford&rsquo;s oldest daughter, May. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; May was small and compact with wild fuzzy  hair. Her body was that of pin-up jailbait, and she had the sparkle of the  devil in her eyes. She never stood still. She percolated like a coffee pot.  Plinx had been wild, but May was fast. She was home from an exclusive girls  school for the summer and delightedly told Plinx all about how she&rsquo;d climbed  out of her dorm window to meet a boy in the woods. How far she had let him  slide his hand beneath her skirt, how sweaty his palms had been, and how hard  he had kissed her mouth. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Nick had never been so forward with Plinx.  He&rsquo;d only touched her shoulders, or maybe held her hand. His skin was always  cool and his kiss light. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; May also told her how one night she got  scared, because she couldn&rsquo;t push the boy&rsquo;s hand away, and that she&rsquo;d had to  bite his lip to escape. Plinx had never been afraid with Nick, whom she chose  once again to keep for herself. She liked May very much, but since she was  married to her father, she couldn&rsquo;t be sure how May would react.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; It wasn&rsquo;t long before Plinx was running the  streets of a new town, flanked by May. And since Atlanta had bigger things on  its mind than the antics of two young girls, no one bothered to notice. Gilford  traveled a good deal, and when he was home was content to let Plinx be a girl  by day, as long as she convinced him that he was a man by night.&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Plinx passed four years in that manner. She  kept largely to herself in the fall and winter, remaining very much the same  person she had been. But in the spring, she looked forward to May&rsquo;s coming, the  way she looked forward to the warm weather.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; One summer afternoon as they were sitting  on soda stools, sipping cherry cokes and making sure their skirts were hiked up  just a little too high, they saw a man nailing a sign to an abandoned building.  It announced the coming of the new black USO. Everyday they stopped to watch  the construction until the workmen knew them by name. They saw the lumber  carried in, and the stones for the new facade, and they were there when the  last bit of white paint was put on the stairs. May had a hankering to marry a  soldier, so one Friday night when Gilford was to be gone for the weekend, they  paid a visit.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; It was the day of the summer solstice. The  air was hot and humid, the moon was full, and their thin cotton dresses were  sticking to their bodies by the time they went inside.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The sound of an enormous Philco radio  filled the room with big band, and the dance floor was covered with uniformed  men and women in bright dresses popping through the steps of the Big Apple.  There were three pool tables, their felt covering still shiny and green, and  just above them hung lamps and a haze of smoke. On the right was a wooden bar  with a shiny glass top and a mirror behind. The mirror ran the length of the  wall and reflected the entire room. It was at the far end of the bar that the  girls ensconced themselves.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; They conned the bartender, who was much  thinner than Fat Sam, into giving them rum with their cherry cokes. They both  thought it was the nastiest thing they&rsquo;d ever tasted, but they drank it just  the same. Two stools away, a soldier with his elbow on the bar and his chin in  his hand, watched them and shook his head. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; May&rsquo;s devilish eyes met his in the mirror  and she begged a cigarette. He handed it to her with a book of matches. May was  a little indignant. She had never smoked before but she&rsquo;d seen people do it in  movies, and she had been counting on the fact that a gentlemen always lit a  lady&rsquo;s cigarette, particularly since she wasn&rsquo;t sure how to do it herself. She  held the matches in her right hand, the cigarette in her left and tried, but  the thing wouldn&rsquo;t catch. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Finally the soldier leaned over and said,  &ldquo;Put it in your mouth.&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp; May sat straight up, the remark was so  rude. But the soldier drew another cigarette from his pack, put it in his  mouth, lit it, and made smoke rings. Plinx was delighted. Jeremy used to make  smoke rings for her from his pipe. The soldier took the matches and struck one  as May lipped the cigarette. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;When I put the match to it, you suck in,&rdquo;  he said.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Plinx thought poor May would choke to  death. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; The soldier whooped. &ldquo;Dolls, little girl.  You still need some dolls.&rdquo; He got up and headed to the pool table. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; But despite the fact that he&rsquo;d insulted  her, May liked him. &ldquo;I always wanted to learn how to play pool,&rdquo; she said. And  Plinx watched her narrow fanny wiggling back and forth as the soldier tried to  keep from laughing long enough to teach her to shoot.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; May didn&rsquo;t think Plinx would mind being  left alone. There was the music to listen to and the dancers to watch and after  all Plinx was married. But when the bartender noticed her, he came over, patted  her hand and said, &ldquo;You want something else?&rdquo; Then he noticed her wedding ring  and drew back. &ldquo;You&rsquo;re married?&rdquo; he said.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Sort of,&rdquo; and Plinx put her hand in her  lap.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The bartender had very old eyes. And after  he had stared at Plinx for a few seconds, he smiled and said, &ldquo;I bet I got  something you&rsquo;ll like.&rdquo; <br>
  &nbsp;&nbsp;&nbsp;&nbsp; He opened a big silver freezer, pulled out  a cardboard drum with &ldquo;Cherry&rdquo; written on the side and made Plinx the most  magnificent cherry soda she had ever had. She felt the cold, sweet taste in her  mouth and thought of the ice cream Nick had bought for her at the General Store  one hot August day. She was sucking hard on her straw when she looked in the  mirror. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Nick  Baker was standing at the door.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; For a few seconds, she forgot to breathe.  She shut her eyes. He wasn&rsquo;t there, she had made him up. But when she opened  them, he was coming towards her. She couldn&rsquo;t move. She sat frozen to the bar  stool until his hand touched the skin on her shoulder. It was the same touch  she had felt in the rain, at the gate, on the night of the church social. He  was real.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; She turned around and saw that he was  leaning on a pearl handled cane. She reached down and put her hand on his.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Can&rsquo;t dance no more,&rdquo; was all he said.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; She cried when he touched her wedding band,  but she cried even harder when he showed her his.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;They told me you got married,&rdquo; he said.  And she felt he had&nbsp; whispered it because  he could not bear to say it aloud.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;I didn&rsquo;t get married. I never got married.  I just was married. And that was all. I didn&rsquo;t know you got married.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;I didn&rsquo;t get married either,&rdquo; he said. &ldquo;I  just married someone.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Plinx closed her eyes, remembering him  until he was the only real thing in her world and everything else was gone.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The bartender had been watching them with  his old eyes.&nbsp; &ldquo;There&rsquo;s a door back  there, leads to the alley,&rdquo; he said. &ldquo;Person could get a little quiet if he  wanted,&rdquo; and the bartender walked away.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Nick took her hand and led her outside.  Plinx didn&rsquo;t notice where May was.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; They sat close to each other on the back  steps. The faint laughter and music of the big band faded as the door closed,  and the pearl handled cane was balanced between Nick&rsquo;s knees. He drove the tip  of the cane hard into the dirt. &ldquo;Can&rsquo;t dance no more,&rdquo; he said. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; She stood up, took the cane and laid it in  the dirt. She drew his body to her and put her hand in his. Then the music of  the church social filled the air, and she let him lean against her as they  danced. When the music ended, Nick picked up his cane. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; The old livery stables stood empty at the  end of the alley and as they entered Plinx imagined the horses that had stamped  and whinnied and rustled in their stalls. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; There was no more crinoline to keep her  from him, not even the thin fabric of her dress. She felt his fingers caress  her body, his skin press against hers, his mouth taste of her neck and throat,  and the scar on his leg brush her calf. She touched his hair and pulled his  face to hers. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Then a sound cracked the quiet. It echoed  through the stables like an explosion. Her hands trembled before her as Plinx  watched them go red with his blood.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Gilford was standing at the door with a 12  gauge. He had come home from his business trip early and found May on the steps  in tears. She had seen Plinx with Nick, and she had told her father everything. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; He grabbed Plinx&rsquo;s arm, pulled her up,  jerked her dress down over her head and dragged her away. But not before she  had the pearl handled cane in her hands. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; Gilford dragged her through the streets so  hard and so fast that she fell. Her whole body shook as she crouched, pressing  the cane to her breasts and whispering over and over, &ldquo;Some stars are so  distant by the time their light reaches us we&rsquo;re seeing yesterday. Some stars  are so distant by the time their light reaches us we&rsquo;re seeing yesterday....&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;You trying to make me think you&rsquo;re crazy,  girl?&rdquo; and Gilford raised his hand to strike her.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; &ldquo;No.&rdquo; She looked dead into his eyes, and  her gaze froze his hand in midair. She got up slowly, pulling her arm away when  he tried to grab it. Gilford spit and stormed off. He was trying to make her  follow him but she would not. She held the cane tight, keeping pace with  Gilford no matter how fast he walked. And she made up her mind that neither he  nor anyone else would see her cry.</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp; Jubee Whitehead&rsquo;s second cousin lived in  Atlanta, so the news of Plinx&rsquo;s homecoming preceded her. The wind whipped the  red dust as&nbsp; the entire town poured into  the streets and stood on the road, hating her. It was ready when Gilford  Stanton&rsquo;s car raced through, to watch her in the passenger seat, with her head  bowed and her shoulders hunched forward. It wanted to see her finally made  sorry for herself, sorry for Nick Baker&rsquo;s murder, sorry for the disgrace she  had caused. But she was sitting perfectly straight in the car as if balancing a  crown on her head. She was still perfectly straight when she stood behind the  fence that separated her from the rest of the town and locked the gate, even  after Gilford had left her there like so much damaged goods. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; The town did not expect to see her when  Nick Baker was buried. Wind stirred the tall grass like waves on the ocean as  Plinx made her way up the hill. Her black hair shone in stark contrast to the  grave stones bleached white by the sun. The town drew its breath in rage,  turned away from her with clenched fists and closed its ranks around a woman  and a small boy.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Plinx had not known that Nick Baker had a  child until she saw his face in Jackson&rsquo;s. But Jackson Baker stared through her  with a look that penetrated the deepest layers of her skin. He was so small,  yet he hated her so completely. And then his eyes fell on the cane. She hadn&rsquo;t  made a conscious decision to bring it. It was only that her hands felt empty  when it wasn&rsquo;t there. The boy broke from his mother, charged at her, grabbed  the cane, and tried to jerk it away. And as she was standing there struggling  with this boy who sobbed and screamed, Plinx realized he was the only person  who had loved Nick as she had, and she would never be able to return his  hatred. But neither could she give him that cane. She pulled it to her, and the  boy fell back in the grass.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; As she turned to go, the town hissed, &ldquo;Mrs.  Stanton is finally leaving.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; She did not break stride nor did she look  back, only said clearly over her shoulder, &ldquo;You may address me as Miss Plinx.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The town did not want to call her that, but  it did.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; Miss Plinx never came into town again. Even  when Jeremy finally died she called an undertaker from the next county. She  paid a considerable sum to see that a circuitous route was taken to the  cemetery and that Jeremy was buried under the full moon he had loved. Folks  claimed they heard her wailing, but no one saw her. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; She had no visitors whatsoever. Even when  her groceries were delivered, they were left outside the gate. But Jackson  Baker was always there. As soon as he was old enough, he started climbing out  of his window at night. He would use any excuse to go up the hill, dig his  heels in, stand on the road, and despise her. He watched her lounging on her  chaise, sipping Coca-Cola from a glass bottle, leaving the cherry red print of  her lips like a kiss on its rim, and all the while she held his father&rsquo;s pearl  handled cane. But the night he saw her lean on that cane, lean on his father  for support, he wanted to destroy her. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; That was how the town knew her hip had gone  bad. The doctor said from the way Jackson described it, that it was like as not  tubercular and would eventually kill her. But Jackson Baker would never see her  slip away from him like that. He swore that no matter what Nick Baker had felt  for her, nothing would protect her from his son. The town said the lame hip was  her punishment. It imagined her at last in pain and felt vindicated. But Miss  Plinx never saw it that way. At last she had a reason to use Nick Baker&rsquo;s cane,  and she considered it a gift.<br>
  &nbsp;&nbsp;&nbsp;&nbsp; The preacher&rsquo;s car pulled to a stop in  front of the fence that had separated Plinx from the rest of the town. Jackson  Baker, the doctor, and the preacher got out. The only sound was the creaking of  the porch swing and crunch of the pine needles beneath their boots. They walked  quietly to the house. There were no lights on anywhere and the front door was  locked. They knocked, they called, and then they banged but Miss Plinx did not  come.&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp; And then they heard the sound of wings roll  in on the summer breeze like the coming of a storm. They saw silhouettes pass  before the moon, and they watched shadows sweep the dead brown grass. But when  they reached the backyard they did not find Miss Plinx. Only a half-empty  bottle of Coca-Cola with the cherry red print of lips like a kiss on its rim, a  pearl-handled cane, an old woman&rsquo;s body, and feathers and hoof prints around a  chaise.</p>           </td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
