<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue7/menu_issue7.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue7/christine_simon/artwork.html','','width=575,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="292" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">Culture and barbarism: <em>Doctor Faustus</em>, modernism and the rise of fascism <span class="texto2">by <a href="../../issue7/christine_simon/bio.php" class="link3">Christine Simon</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           &nbsp;<br>
<p>Few writers of  historical fiction can have been as ambitious as Thomas Mann, whose stated aim  in his novel <em>Doctor Faustus</em> was &lsquo;to  write nothing less than the novel of my era, disguised as the story of an  artist&rsquo;s life&rsquo;.<a href="#_ftn1" name="_ftnref1" title=""><sup>1</sup></a> His &lsquo;biography&rsquo; of the fictional composer Adrian Leverk&uuml;hn represents the  situation of the artist at a particular juncture of history and stands  allegorically for the plight of Mann&rsquo;s Germany. Although  the original conception for the story of &lsquo;the syphilitic artist: as Doctor  Faust who has sold himself to the Devil&rsquo; dates from 1905,<a href="#_ftn2" name="_ftnref2" title=""><sup>2</sup></a> by the time Mann came to take up the idea for <em>Doctor Faustus</em>, both his outlook and the world around him had  changed. The original idea, overlaid with historical and political concerns,  came to incorporate an exploration of the rise of Nazism while retaining the  theme of the artist&rsquo;s predicament in the modern period.&nbsp; Either of these subjects could form the basis  of a substantial novel; the result is a work which defies categorisation,  containing interwoven elements of history, social realism, biography and  autobiography, allegory and myth.</p>          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
          &nbsp;<br>
            <p>Mann&rsquo;s interposition between himself and his subject of an  intermediate narrator, the inexperienced biographer Serenus Zeitblom, does not  preclude the use of some carefully-selected narrative techniques which enable  the seamless interweaving of history with the other elements of the novel.&nbsp; </p>
            <p>The use of the Faust myth, as well as enabling the symbolic pairing  of Faust with Germany and with Leverk&uuml;hn, creates a link between three  significant points in German cultural history<a href="#_ftn3" name="_ftnref3" title=""><sup>3</sup></a>,  spanning the era labelled by Zeitblom as &lsquo;the epoch of bourgeois humanism&rsquo;.<a href="#_ftn4" name="_ftnref4" title=""><sup>4</sup></a> The original Faust of the 1587 chapbook can be seen as a Renaissance man whose  pact with the devil signals the  increasing power of rational, secular enquiry over the control of the church.  The culmination of post-Renaissance culture is represented by Goethe&rsquo;s Faust (Part I,  1808; Part II, 1832), who also stands for its main  branches of learning<a href="#_ftn5" name="_ftnref5" title=""><sup>5</sup></a>.  Mann&rsquo;s own version of the bedevilled magus, Adrian Leverk&uuml;hn, is located in  what his creator saw as the nadir of Western civilisation: a decadent age which  has bred all manner of foul ideologies<em>.</em> This structure is reinforced by Adrian Leverk&uuml;hn&rsquo;s conscious modelling of his  life on that of the chapbook <em>Faust</em> and by subtle references to Goethe in the  text. The devil situates Leverk&uuml;hn&rsquo;s pact within this historical context when  he compares the artistic possibilities of past and present: &lsquo;What he in his  classical decades could have without us, certainly, that, nowadays, we alone  have to offer&rsquo; (p. 241).</p>
            <p>Much of the representation of history in <em>Doctor Faustus</em> turns on Mann&rsquo;s handling  of time. The use of Zeitblom enabled a narration on two time planes, which Mann  called &lsquo;double time&rsquo; (<em>Genesis</em>, p.  119). This is now a common device in historical fiction; it was less so in the  1940s when Mann was writing. Zeitblom&rsquo;s biography of his friend Leverk&uuml;hn spans  the period from 1885 to 1940, but this life story is interspersed with reports  and comments on the events of World War II during the period in which Zeitblom  is writing: from May 1943 to April 1945. In chapter 33, the biographical  narrative has reached the fall of Germany  at the end of World War I, but Zeitblom begins his chapter with an account of  the impending fall of Germany in 1944: </p>
            <blockquote>The time of which I write  was for us Germans an era of national collapse, of capitulation, of uprisings  due to exhaustion, of helpless surrender into the hands of strangers. The time  in which I write, which must serve me to set down these recollections here in  my silence and solitude, this time has a horribly swollen belly, it carries in  its womb a national catastrophe compared with which the defeat of those earlier  days seems a moderate misfortune, the sensible liquidation of an unsuccessful  enterprise. (<em>Doctor Faustus</em>, p. 343)</blockquote>
            <p>This counterpoint between writer and subject, between time depicted  and time of depiction, which echoes the nature of history itself, allows not  only the interpolation into the novel of Zetiblom&rsquo;s outraged and despairing  comments on fascism and the Second World War (with a vehemence and a simplicity  which would have been difficult for Mann the sophisticated man of letters) but,  more subtly, a comparison by juxtaposition of his present time with the events  of the period narrated in the biography, allowing the one to comment on and  enlighten the other. The Nazi Germany of Zeitblom&rsquo;s present is the product of  those years of the Second Reich and the Weimar Republic which  form the subject of his biography; but this is implied rather than stated,  shown rather than explained. It is, in fact, though Mann does not define it as  such, an instance of montage.</p>
            <p>At the same time, this device &ndash; the interweaving of Leverk&uuml;hn&rsquo;s life  and times and those of his biographer &ndash; underpins Leverk&uuml;hn&rsquo;s symbolic  function.&nbsp; Chapter 33 continues with a  discussion of the humiliation of Germany following the end of World War I,  after which the narrative swings back to Leverk&uuml;hn in 1918: &lsquo;Leverk&uuml;hn &hellip; was  unusually ailing at this time, in a way that had something humiliating in its  torments&rsquo; (p. 343). This parallel runs through the novel; Leverk&uuml;hn&rsquo;s mental  and physical health mirrored by and mirroring the condition of Germany,  till the final end of both: the defeat of Germany,  the collapse, insanity and death of Leverk&uuml;hn.</p>
            <p>Earlier,  in chapter 26, the ingenuous Zeitblom comments on this layering of time:</p>
            <blockquote>I do not know why this  double time-reckoning arrests my attention or why I am at pains to point out  both the personal and the objective, the time in which the narrator moves and  that in which the narrative does so. This is a quite extraordinary interweaving  of time-units, destined, moreover, to include even a third: namely, the time  which one day the courteous reader will take for the reading of what has been  written; at which point he will be dealing with a threefold ordering of time:  his own, that of the chronicler, and historic time. (p. 256)</blockquote>
            <p>This  passage could be read as a paradigm of the historical novel in general, to  which each generation of readers brings the shifting interpretations of its own  time, and of those novels written in a dual time-frame in particular.&nbsp; In fact, the &lsquo;historic time&rsquo; in <em>Doctor Faustus</em> is not limited to the  period from 1885 to 1940, but includes also a panorama of German history,  stretching back to the late Middle Ages, sketched out and alluded to throughout  the novel. This is Zeitblom&rsquo;s &lsquo;epoch of bourgeois humanism&rsquo;, the decline of which  is described and discussed throughout the novel:</p>
            <blockquote>I  felt that an epoch was ending, which had not only included the nineteenth  century, but gone far back to the end of the Middle Ages, to the loosening of  scholastic ties, the emancipation of the individual, the birth of freedom. (p.  359)</blockquote>
            <p>One of the  ways in which this sense of &lsquo;historic time&rsquo; is established is through the loci  of the novel. Halle, Leipzig and Munich, cities in which Adrian Leverk&uuml;hn lives, are significant in Germany&rsquo;s  theological, musical and political history. Kaisersaschern, the fictitious  little town where Zeitblom and Leverk&uuml;hn were born and from whose influence Leverk&uuml;hn  can, significantly, never quite escape, functions as a symbol of Germanness. A  historic town which &lsquo;had kept a distinctively mediaeval air&rsquo;, in Zeitblom&rsquo;s  childhood it was &lsquo;practical, rational, modern&rsquo; (p. 34), its mediaeval  characteristics superseded by modern enlightened virtues. But the past here  prefigures later developments, just as the &lsquo;crude instruments of torture&rsquo; (p.  33) in the town&rsquo;s museum are not only vestiges of a less enlightened age, but a  reminder that beneath the surface lurks an older, unenlightened, psychology  which predates Zeitblom&rsquo;s humanism. It is precisely, implies Zeitblom, this <em>v&ouml;lkisch</em> (folkish) and archaic layer of  the German psyche, easily roused to &lsquo;deeds of sinister significance&rsquo; (p. 35),  which has aided the rise of fascism. It is significant also that the devil,  appearing to Leverk&uuml;hn in 1911 or 1912,<a href="#_ftn6" name="_ftnref6" title=""><sup>6</sup></a> characterises their shared world as &lsquo;pure Kaisersaschern, good old German air,  from anno MD or thereabouts&rsquo; (p. 235). &nbsp;It  is no coincidence, either, that this meeting with the devil takes place in a  sixteenth-century house in the ancient town of Palestrina, birthplace of the  eponymous composer whose work forms part of the heyday of counterpoint, that  technique which characterises western music from the late Middle Ages and which  Leverk&uuml;hn is about to abolish. </p>
            <p>Mann is  adept at throwing into his narrative subtle and complex references which serve  to reinforce the novel&rsquo;s sense of history. In the description of Adrian  Leverk&uuml;hn&rsquo;s work room at Pfeiffering, mention is made of a Savonarola chair  which stands at his work table (p. 261). Though deceptively simple, this reference  is nonetheless highly significant. The Savonarola chair is an antique form and  thus stands for the past. But of the various names by which it can be known  (X-chair, scissors-chair, Dante chair, Luther chair, Savonarola chair) Mann  chose &lsquo;Savonarola&rsquo;, thus conjuring an array of historical references. Savonarola,  notorious for his religious and political zeal, his anti-humanist stance, his book  burnings and destruction of what he saw as immoral art, carries sinister  resonances for an opponent of Hitler who had witnessed the Nazi book burnings  of 1933 and the <em>Entartete Kunst</em> (Degenerate Art) exhibitions of 1937. &nbsp;The  reference, however, is equivocal, since it is underlaid with the notion of Savonarola&rsquo;s  opposition to what he saw as a corrupt regime. Subtle references of this sort abound,  but they are not laboured; Mann expects much of his reader. </p>
            <p>Music in <em>Doctor Faustus </em>is &lsquo;only a paradigm for something more general, only a means to express  the situation of art in general, of culture, even of man and the intellect  itself in our so critical era&rsquo; (<em>Genesis</em>,  p. 37); nonetheless, the history of western music is treated in detail, and runs  through <em>Doctor Faustus </em>like the  history of Germany. In the lectures of Kretschmar and the conversations between  Zeitblom and Leverk&uuml;hn, the reader is presented with the development from  monody (monophony) to polyphony, the seminal innovations of Beethoven and the  consequent difficulty of creating anything new, the development of chromaticism  and the problematic nature of Wagner&rsquo;s music<em>.</em> This leads on to Leverk&uuml;hn&rsquo;s development of the twelve-tone system, and to a  body of work which, though it reflects the <em>Zeitgeist</em>,  also encapsulates the history of western music, of which it is both the  culmination and the overturning<em>.</em></p>
            <p><em>Doctor Faustus</em> is  &lsquo;embedded &hellip; in the pressure and tumult of outward events&rsquo; (<em>Genesis</em>, p. 9-10). Characteristically, this statement describes  both the narrative itself and the process of writing it. Zeitblom puts pen to  paper to begin the biography of Adrian Leverk&uuml;hn on 23 May 1943, the same day on which Mann started to write <em>Doctor Faustus</em>. <a href="#_ftn7" name="_ftnref7" title=""><sup>7</sup></a> The events which formed a backdrop to Mann&rsquo;s writing of the novel become  Serenus Zeitblom&rsquo;s &lsquo;time in which I write&rsquo;. This is typical of what Mann called  his &lsquo;montage technique&rsquo; (<em>Genesis</em>, p.  29), by which he means the mixing of real events and characters into the  fictional narrative. &lsquo;I was constantly amazed,&rsquo; he wrote, &lsquo;by the way its [the  novel&rsquo;s] fantastic mechanisms drew upon factual, historical, personal, and even  literary data. As in the &ldquo;panoramas&rdquo; shown in my childhood, palpable reality  was for ever indistinguishably merging into painted perspectives and illusion&rsquo;  (<em>Genesis</em>, p. 29). To some extent this  process is inherent in the writing of fiction, although Mann does seem to have  taken the borrowing from reality &ndash;  and other sources &ndash; &nbsp;to extremes. His  research for the novel, detailed in <em>Genesis,</em> was vast, wide-ranging and eclectic. It covered both written and human sources  (he relied heavily on Theodor Adorno, a fellow German exile and at that time a  neighbour of Mann&rsquo;s in California, to advise on musical matters) and was both  planned and circumstantial; he asked questions, wrote letters, read books, but  also made use of chance findings. The project &lsquo;arrogated for its own purposes  all that reality brought my way&rsquo; (<em>Genesis</em>,  p. 25). </p>
            <p>What Mann calls montage includes the covert use of historically  attested characters. Adrian Leverk&uuml;hn is so closely connected with Nietzsche,  in terms both of life events (the brothel incident and subsequent syphilitic  infection, the manic-depressive moods) and of ideology (the problem of the  modern artist, burdened with an excess of knowledge, no longer able to follow  traditional paths and thus forced to create works which exploit the primitive)  that Nietzsche cannot appear in the novel as an autonomous historical character  (<em>Genesis</em>, p. 30). The same is true of Sch&ouml;nberg, since Leverk&uuml;hn &lsquo;invents&rsquo;  Sch&ouml;nberg&rsquo;s twelve-tone system. Such borrowings, or &lsquo;theft from reality&rsquo; (<em>Genesis</em>, p. 32), as Mann called them,  are historically accurate but take on meanings of their own in the novel.  Leverk&uuml;hn&rsquo;s knowing infection with syphilis &ndash; he disregards Esmeralda&rsquo;s  warnings about her infected state (p. 157) &ndash; is drawn from Nietzsche&rsquo;s life<a href="#_ftn8" name="_ftnref8" title=""><sup>8</sup></a>,  but it becomes part of Leverk&uuml;hn&rsquo;s self-modelling on Faust and is seen as the  vehicle for both his creative success and his final collapse. The twelve-tone  system, a way out of the paradoxical restrictions of post-Romantic individual  freedom, becomes a solution to the artist&rsquo;s dilemma, but one which, in its  leaning towards the over-ordered, fascistic and barbaric, echoes Germany&rsquo;s  political solution.</p>
            <p>Mann incorporated into <em>Doctor  Faustus</em> significant elements of his own experience, thus creating an  overlap between personal and political history. The depiction of German society  in the first half of the twentieth century owes some of its cogency to the fact that Adrian Leverk&uuml;hn&rsquo;s  formative period was Mann&rsquo;s own. The semi-bohemian circles of Munich, the  problems of artistic creation, the experience of life during the Second Reich  and the Weimar Republic, are all mined from his own past. Clarissa Rodde&rsquo;s suicide is drawn  from that of one of Mann&rsquo;s sisters, the angelic child Echo is closely (and  courageously) based on the author&rsquo;s favourite grandson. This borrowing from  reality, which underpins the conventional realism of the novel and contributes  to its verisimilitude, also provides a detailed picture of the cultural roots  of Nazism amongst the middle classes. </p>
            <p>Mann&rsquo;s use of a narrator allows the life-story of Adrian Leverk&uuml;hn  to be filtered through the pen of the mild, earnest and sometimes  unintentionally comic humanist scholar Serenus Zeitblom. The themes of the  novel &ndash; the Faust myth and the pact with the devil, the rise of Nazism, music  and the predicament of the artist in the modern age &ndash; are all played out  through Leverk&uuml;hn; Zeitblom is the powerless onlooker to both his friend&rsquo;s tragedy and that of Germany. This narrative  dichotomy is symbolic of Germany:  the old-style rational, cultured humanism versus the new, tortured national  psychology which has made a pact with its own devil, Hitler. But at the same  time it represents the author&rsquo;s divided self.<a href="#_ftn9" name="_ftnref9" title=""><sup>9</sup></a> Mann does not stand aloof from his country&rsquo;s historical catastrophe; on the  contrary, he recognises that it was something in which he had himself  participated. <em>Doctor Faustus</em> is in  part an exploration of his own complicity, bound up with the artistic problems  of the early years of the twentieth century. Mann had noted in 1938 that he  himself possessed the &lsquo;tendencies of the time, in the air long before the word  &ldquo;Fascist&rdquo; existed&rsquo; and that they &lsquo;served its moral preparation. I had them in  me as much as anyone&rsquo;.<a href="#_ftn10" name="_ftnref10" title=""><sup>10</sup></a> It was ideas such as these, expressed by Mann in his <em>Reflections of a Nonpolitical Man</em>, written during the First World  War, which led to the dispute with his brother Heinrich; a reconciliation took  place only after Thomas had abandoned the possibility of being non-political.</p>
            <p>For Mann, the cultural had become political; there is an implication  that the social decline and the disaster of Germany&rsquo;s  descent into Nazism are not only inevitable and parallel, but causally  connected. &lsquo;Certainly in Germany, so he [Mann] would write after the German  catastrophe, &hellip; [the] spiritual, cultural, emotional impulse &ndash; was the prime  moving force, and political action only came after, as its expression and  instrument.&rsquo;<a href="#_ftn11" name="_ftnref11" title=""><sup>11</sup></a>&nbsp; Mann concentrates not on the big &lsquo;forward step which  history has taken&rsquo;, but on its &lsquo;reflexes in everyday life&rsquo;<a href="#_ftn12" name="_ftnref12" title=""><sup>12</sup></a>.  He places less emphasis on a textbook analysis of Hitler&rsquo;s rise to power &ndash; we  are not presented with the Beer Hall Putsch or jackboots goose-stepping through  Berlin<em> &ndash; </em>than on its  underlying cultural, psychological and intellectual roots. The personal stories  of the Rodde daughters and of Rudi Schwerdtfeger are tragic endings symptomatic  of &lsquo;the final stage of a society&rsquo; (<em>Genesis </em>p. 107) and are prefigured by Zeitblom&rsquo;s liberal use of prolepsis, lending  the narrative a sense of inevitable doom and imbuing both personal and  political events with the same relentless fatality. </p>
            <p>But Mann&rsquo;s historical analysis is always, however loosely, a  function of his characters and their situations; from the student discussions  at Halle to the&nbsp; conversations of the  Kridwiss circle, it is knitted into the narrative. A telling example is  provided early in the novel, when Zeitblom muses on the relationship between  the intellectual and the daemonic. He was first struck by the daemonic as a  necessary element of culture during his youthful travels in Greece:</p>
            <blockquote>When from the Acropolis I  looked down upon the Sacred Way on which the initiates marched, adorned with  the saffron band, with the name of Iacchus on their lips; again, when I stood  at the place of initiation itself, &hellip; I experienced by divination the rich  feeling of life which expresses itself in the initiate veneration of Olympic  Greece for the deities of the depths; often, later on, I explained to my pupils  that culture is in very truth the pious and regulating, I might say  propitiatory entrance of the dark and uncanny into the service of the gods.  (pp. 7-8)</blockquote>
            <p>Though there is much of importance here, it is understated, slipped  in amongst the apparently rambling memories of an old man. The uneasy  relationship between the rational and the daemonic is seen to be historically rooted  in the western mind. This reference is central to the novel: in Zeitblom&rsquo;s  view, one of the significant problems of modern Germany  is that it has let in too much of the &lsquo;dark and uncanny&rsquo;, at the expense of the  reasoned and intellectual; but it is a typically oblique reference.&nbsp; </p>
            <p>Zeitblom&rsquo;s &lsquo;uncanny&rsquo; in this quotation is undoubtedly a reference to  Freud&rsquo;s concept of the uncanny (<em>das  Unheimliche)</em>. The uncanny is that which arouses fear or unease because it  contains elements which are both known and unknown. Freud notes, through the  development of the word <em>heimlich</em> from  &lsquo;homely&rsquo; to &lsquo;concealed&rsquo;, the semantic shift by which <em>heimlich</em> (&lsquo;familiar&rsquo; or &lsquo;homely&rsquo;) comes to mean its opposite  (unfamiliar, uncanny); it &lsquo;becomes increasingly ambivalent, until it finally  merges with its antonym <em>unheimlich&rsquo;</em>.<a href="#_ftn13" name="_ftnref13" title=""><sup>13</sup></a> Freud suggests that the sense of the uncanny derives from the resurgence of  repressed impressions or ideas: either childhood complexes (in the individual)  or primitive beliefs long since superseded by reason (in a society or a  culture).<a href="#_ftn14" name="_ftnref14" title=""><sup>14</sup></a> We may see here a parallel with Adrian Leverk&uuml;hn&rsquo;s ambiguous music, in which a  primitive and barbaric element resurfaces despite its highly rational nature;  and with the Nazis&rsquo; deliberate exploitation of archaic, <em>v&ouml;lkisch</em> beliefs.</p>
            <p>Zeitblom, now an old man facing the destruction of Germany,  makes a further reference to the ancient world, in a bitterly ironic comment on  the short duration of Hitler&rsquo;s Reich: </p>
            <blockquote>Our  &lsquo;thousand-year&rsquo; history, refuted, reduced <em>ad  absurdum</em>, weighed in the balance and found unblest, turns out to be a road  leading nowhere, or rather into despair, an unexampled bankruptcy, a <em>descensus Averno</em> lighted by the dance of  roaring flames. (p. 462)</blockquote>
            <p>Aeneas&rsquo; &lsquo;descensus Averno&rsquo;<a href="#_ftn15" name="_ftnref15" title=""><sup>15</sup></a> was a journey back into the past &ndash; to consult his dead father, Anchises &ndash; and  into the future: Anchises would enlighten his son on the nature of his destiny.  This connection of past and future is part of the overall substance of <em>Doctor Faustus</em>, but also interesting  here is the layering of concepts: the juxtaposition of the classical underworld  &ndash; a place in which good and evil are mixed &ndash; with the flames of the Christian  hell &ndash; an unequivocal place of punishment for the wicked. We might connect this  juxtaposition and progression of ideas with Zeitblom&rsquo;s concept of the  &lsquo;daemonic&rsquo;, quoted above. Although there is no distinction in <em>Doctor Faustus</em> between the &lsquo;daemonic&rsquo;  and the &lsquo;demonic&rsquo;, there exists in the use of the word &lsquo;daemonic&rsquo; an implied  degeneration, from the &lsquo;daemonic&rsquo; as a dangerous but necessary component of the  intellectual life, artistic genius included (one thinks of Socrates&rsquo; guiding  spirit), to the &lsquo;demonic&rsquo; evil of fascism. However unavoidable or necessary the  &lsquo;daemonic&rsquo; may be, both Leverk&uuml;hn and Germany,  in their combination of the primitive and the radically modern, have slipped  into the &lsquo;demonic&rsquo;. </p>
            <p>Fascism, however, was not the only system in the first half of the  twentieth century to exploit the &lsquo;dark and uncanny&rsquo;, the primitive and the  equivocal. The artist&rsquo;s life as exemplified by Adrian Leverk&uuml;hn may on one  level be a vehicle for Mann&rsquo;s socio-political analysis, but it is nonetheless a  major constituent of the novel in its own right. For, in addition to  investigating Germany&rsquo;s political crisis and her descent into Nazism, <em>Doctor Faustus</em> is an exploration of the  era&rsquo;s particular artistic problems, which can be summed up in the word  &lsquo;modernism&rsquo;. The juncture of history at which Mann&rsquo;s Faustus finds himself was  critical not just for politics but for the arts too. &lsquo;Why does almost everything  seem to me like its own parody?&rsquo; Leverk&uuml;hn asks of his mentor Kretschmar at the  decisive point in his career, when he is about to abandon theology (which he  had taken up in an attempt to escape the need for parody) for musical  composition. &lsquo;Why must I think that almost all, no, all the methods and  conventions of art today <em>are good for  parody only?</em>&rsquo; (p. 135). This expression of the difficulty of making art in  1905 is met, in Kretschmar&rsquo;s reply paraphrased by Zeitblom, with an even  clearer statement of the problems: </p>
            <blockquote>Art needed just his sort  today [...] [Leverk&uuml;hn&rsquo;s temperament]  belonged only in part to the private personality; for the rest it was of an  extra-individual nature, the expression of a collective feeling for the  historical exhaustion and vitiation of the means and appliances of art, the  boredom with them and the search for new ways. (p. 136) </blockquote>
            <p>It is against this background, then, that Leverk&uuml;hn&rsquo;s musical career  and his pact with the devil are played out<em>. </em>Living during the period of what may be called &lsquo;high modernism&rsquo;, Leverk&uuml;hn  faces, broadly speaking, the same artistic problems as Joyce and Kafka,  Mondrian and Duchamp. With the  exhaustion and consequent unacceptability of traditional forms, few choices are  left: parody, which is equally unacceptable; the destructive abolition of  traditional forms, as in Dada; or the creation of radically new ones. Adrian Leverk&uuml;hn&rsquo;s breakthrough, the twelve-tone  system, is just such a radically new form.  This highly rational and intellectual method, which removes from the  process of composition a great deal of problematic subjectivity as well as the  traditional need for tonality, places its creator firmly within the modernist  camp. </p>
            <p>But Leverk&uuml;hn&rsquo;s position as an exemplar of extreme modernism is at  odds with his allegorical function. His career runs parallel to the recent  history of Germany;  his pact with the devil, period of creativity and subsequent madness are also  hers; but this is no one-sided correspondence. Paradoxically, Leverk&uuml;hn&rsquo;s music  would doubtless have met the same fate as that of its actual creator,  Sch&ouml;nberg; in Nazi Germany atonal compositions were classed as <em>entartete</em> <em>Musik</em> (degenerate music) and their performance banned. Indeed, one  of the reasons that Zeitblom gives for desiring German defeat in the war is  that this is the only way his friend&rsquo;s music will be able to see the light of  day (p. 28). </p>
            <p>The opposition between these two readings of Leverk&uuml;hn is nowhere  more apparent than in Zeitblom&rsquo;s  discussion of his friend&rsquo;s <em>Apocalypsis  cum figuris. </em>This masterpiece is  specifically connected, through the intertwining narratives which comprise the  three sections of chapter 34, with the proto-fascist ideas of the Kridwiss  circle meeting in Munich in the 1920s: the need, enforced by the decline of bourgeois  humanism, for an alternative ideology, one which sees itself as ultra-modern  and which combines an element of Social Darwinism with the control of the  masses by barbarism and primitive &lsquo;mythical fictions&rsquo; (p. 373). Yet, though it  epitomises those ideas, the <em>Apocalypsis </em>&nbsp;is a complex avant-garde work, such as would  have been vilified by the members of the Kridwiss circle.&nbsp; It is in fact largely misunderstood, and  incurs &lsquo;the reproach both of blood-boltered barbarism and of bloodless  intellectuality!&rsquo; (p. 381).&nbsp;&nbsp;&nbsp;&nbsp; </p>
            <p>This complex linkage and opposition of ideas is underscored by a  simile used by Zeitblom in describing both the new ideology and the <em>Apocalypsis cum figuris</em>. In this work,  musical conventions have moved full circle, so that dissonance stands for  spirituality and pure harmony for hell. (Similarly, the buildings of Auschwitz made  use of classical symmetry; a fact used by the artist Kitaj, in whose &lsquo;If Not,  Not&rsquo; the Auschwitz gatehouse in the  background forms a startling contrast with what Kitaj called the &lsquo;scattered  fragments&rsquo; in the rest of the picture.<a href="#_ftn16" name="_ftnref16" title=""><sup>16</sup></a>)  Zeitblom uses this idea of &lsquo;full circle&rsquo; to connect the <em>Apocalypsis</em> with the ideas which form its backdrop. First, to flag  up the simultaneously progressive and regressive nature of this ideology: </p>
            <blockquote>It was an old-new  world of revolutionary reaction, in which the values bound up with the idea of  the individual [...] were entirely rejected and shorn of power [...] &ndash; not, let  me say, in a reactionary, anachronistic way as of yesterday or the day before,  but so that it was like the most novel setting back of humanity into medi&aelig;vally theocratic  conditions and situations. That was as little reactionary as though one were to  describe as regression the track round a sphere, which of course leads back to  where it started. (p. 375-376) </blockquote>
            <p>And later, to justify in the <em>Apocalypse</em> the combination of old and new, on which the charge of  barbarism rests:</p>
            <blockquote>but surely this is  by no means an arbitrary combination; rather it lies in the nature of things:  it rests, I might say, on the curvature of the world, which makes the last  return unto the first. (p. 383)</blockquote>
            <p>&nbsp;(Music tending  to rediscover ancient forms, as the twelve-tone system is prefigured in the  music of Johann Conrad Beissel). </p>
            <p>The unresolved  tension between these two uses of the simile pinpoints the uncomfortable  consonance between modernism and fascism, forms which, however different they  appear on the surface, both contain a &lsquo;combination of very new and very old&rsquo;  (p. 383). Fascism, itself a manifestation of modernity,  had common ground with modernism in the arts. Like Futurism, it exalted modern  technological phenomena &ndash; the railway system, speed, the radio and film &ndash; while  at the same time making use of primitive folk-motifs. Radical in its break with  the past and with traditional forms, it was consciously experimental, a new  form of government for a new age. The fact that some modernists embraced fascism  &ndash; Ezra Pound, for example &ndash; serves only to reinforce the connection. </p>
            <p>For Mann, the connection between fascism and modernism would appear  to be barbarism. While we might expect  an old-fashioned liberal bourgeois like Zeitblom to be disturbed by any  non-traditional music, it has to be noted that Mann found in Sch&ouml;nberg&rsquo;s music  an element of barbarism. Mann agreed with Adorno that the &lsquo;rigorous rational  analysis&rsquo; of Sch&ouml;nberg&rsquo;s approach nonetheless resulted in &lsquo;just the converse of  rationality. Over the head of the artist, as it were, the art is cast back into  a dark, mythological realm&rsquo; (<em>Genesis</em>,  p. 40).</p>
            <p>The concept of barbarism features in the wider discussion  surrounding the effects of technology on modern art and culture during the  1930s and 1940s. To many intellectuals of this period, the popularisation of  culture and the control of the masses through mass media were a cause for  concern<em>. </em>Walter Benjamin noted the  fascists&rsquo; use of film to make politics into a spectacle for the masses: &lsquo;The  logical result of Fascism is the introduction of aesthetics into political  life&rsquo;.<a href="#_ftn17" name="_ftnref17" title=""><sup>17</sup></a>Yet such effects were also apparent in  the free United States; Adorno and Horkheimer wished to explain &lsquo;why mankind,  instead of entering into a truly human condition, is sinking into a new kind of  barbarism&rsquo;<a href="#_ftn18" name="_ftnref18" title=""><sup>18</sup></a> &ndash; a  barbarism that had as much to do with Hollywood and the commodification of  culture as with mass rallies and Hitler&rsquo;s voice over the radio.<a href="#_ftn19" name="_ftnref19" title=""><sup>19</sup></a> The personal tragedy of Adrian Leverk&uuml;hn is that his attempt to resolve the  problem of artistic sterility<em> &ndash; </em>what  Mann called &lsquo;the desperate situation of art: the most vital factor&rsquo; (<em>Genesis</em>, p. 38) &ndash; results in an art  which, though refined and cerebral, shares elements with a system he would  despise. </p>
            <p>The question remains whether <em>Doctor  Faustus</em> is a modernist novel. Though it discusses the problems of  modernism, it lacks the experimental techniques of novels such as <em>Ulysses</em> or <em>The Waves. </em>The conceit of the simple schoolmaster writing the  biography of his beloved friend &ndash; a device which goes back to the early days of  the novel and which Mann found beneficial to the writing process &ndash; not only  produces a discontinuity between author and reader but allows an outward form  which, superficially at least, relies on traditional techniques. Serenus Zeitblom, out-and-out traditionalist  that he is, would never think of using anything but the conventional, realist modes. Yet Mann, discussing his work in relation to  that of Joyce, was at pains to identify himself with the modernists, while at  the same time acknowledging the greater accessibility and popularity of  traditional forms (<em>Genesis</em>, pp.  75-76). </p>
      
<p>Georg Luk&aacute;cs praised <em>Doctor Faustus</em> precisely for the fact that it is not a modernist  work: though its two time sequences lend it a superficial resemblance to some modernist  novels, the fact that both time frames are &lsquo;objective realities&rsquo; forming &lsquo;one  unified time sequence&rsquo; makes it a conventional realist novel. Deploring the  &lsquo;wildest orgies&rsquo; of the modernist treatment of time, with its &lsquo;extreme  subjective distortion of reality&rsquo;, Luk&aacute;cs finds the fracturing of form in  modernism unacceptable; however ironized, it is only conventional realist  forms, treating time as a &lsquo;social and historical unity&rsquo;, which permit the  disclosure of reality. In Luk&aacute;cs&rsquo;s view, <em>Doctor  Faustus</em> is a supreme example of this socially responsible realist novel.<a href="#_ftn20" name="_ftnref20" title=""><sup>20</sup></a></p>
<p>However, if we scratch beneath the surface  of <em>Doctor Faustus</em>, we find a more  intricate fabric. It was Bakhtin who said that the novel absorbs all forms and  is a supremely effective vehicle for expressing the complex nature of truth; a  dictum exemplified in the elaborate polyphonic structure of <em>Doctor Faustus</em>. Its hybrid nature has  already been noted; in fact, what we have in <em>Doctor Faustus</em> is an amalgam of several forms and styles. Like many  another Bildungsroman, it recounts the life of its subject in detail from  childhood, but this authentic and accurate social realism is only one strand of  the novel. Allegory forms a major element: Adrian Leverk&uuml;hn is paralleled with  Faust and with Germany. The Faust myth forms a template for the novel; the language of  myth and fairy tale is used to imbue seemingly ordinary elements of the  narrative with mythical significance: Leverk&uuml;hn&rsquo;s life is &lsquo;marked by fate&rsquo; (p.  151); his seeking out of the prostitute Esmeralda a year after his visit to the  Leipzig brothel is described by Zeitblom as a &lsquo;fateful event&rsquo; (p. 155);  prefigured, at the end of the preceding chapter, by the comment, &lsquo;Adrian was to  return to the place whither the betrayer had led him&rsquo; (p. 150). The tragedies  of the Rodde daughters and of Rudi Schwerdtfeger are moved forward by  traditional (and melodramatic) plot-driven dramas characteristic of the realist  novel. There are Kretschmar&rsquo;s lectures on the history of music (that on  Beethoven is taken from Adorno&rsquo;s essay &lsquo;Beethoven&rsquo;s Late Style&rsquo;<a href="#_ftn21" name="_ftnref21" title=""><sup>21</sup></a>) and much of Zeitblom&rsquo;s narrative consists of reportage: for  example, the accounts of the Roddes&rsquo; semi-bohemian salon and the theological  lectures of professors Schlepfuss and Kumpf at Halle university. Though he did  not define it as such, Mann&rsquo;s use of these different representational modes &ndash; a  collage of novelistic and essayistic forms &ndash; nonetheless constitutes an  instance of montage, one more akin to that used by Eisenstein in his films and  by Brecht in his <em>episches Theater</em>.  Like the use of &lsquo;double time&rsquo;, Mann&rsquo;s montage and juxtaposition create a  layering effect, akin to that fragmentation of narrative which is a distinctive  feature of the modernist work.<a href="#_ftn22" name="_ftnref22" title=""><sup>22</sup></a></p>
<p>Categories, however, are not always useful,  and <em>Doctor Faustus</em> is in any case too  complex and heterogeneous a work to be easily pigeon<em>-</em>holed. Whether or  not it is relevant to the problem of fascism in the modern world,<a href="#_ftn23" name="_ftnref23" title=""><sup>23</sup></a> and though it makes heavy demands of its reader (one could be  forgiven for wondering if it would be accepted for publication these days), as  the novel of an era it is an extraordinary engagement with history.</p>
&nbsp;<br>
&nbsp;<br>

&nbsp;<br>

&nbsp;<br>

<div>
              <div id="ftn1">
                <p><a href="#_ftnref1" name="_ftn1" title="">1.</a> Thomas Mann, <em>The Genesis of a  Novel</em>, trans. by Richard and Clara Winston (London: Secker &amp; Warburg, 1961), p. 34.&nbsp; Further references are given after quotations  in the text.</p>
              </div>
              <div id="ftn2">
                <p><a href="#_ftnref2" name="_ftn2" title="">2.</a> Mann&rsquo;s notebook entry, 1905, quoted in T. J. Reed, Introduction to <em>Doctor Faustus</em>, p. xiii.</p>
              </div>
              <div id="ftn3">
                <p><a href="#_ftnref3" name="_ftn3" title="">3.</a> See Michael Beddow, <em>Thomas  Mann: Doctor Faustus</em> (Cambridge: Cambridge University Press, 1994), pp.  11-14.</p>
              </div>
              <div id="ftn4">
                <p><a href="#_ftnref4" name="_ftn4" title="">4.</a> Thomas Mann, <em>Doctor Faustus:  The Life of the German Composer Adrian Leverk&uuml;hn as Told by a Friend</em>,  trans. by Helen Lowe-Porter (London: Everyman&rsquo;s Library, 1992), p. 359. Further  references are given after quotations in the text.</p>
              </div>
              <div id="ftn5">
                <p><a href="#_ftnref5" name="_ftn5" title="">5.</a> Jaroslav Pelikan, <em>Faust the  Theologian</em> (New Haven: Yale University Press, 1995), p. 7. </p>
              </div>
              <div id="ftn6">
                <p><a href="#_ftnref6" name="_ftn6" title="">6.</a> The uncertainty is Zeitblom&rsquo;s.</p>
              </div>
              <div id="ftn7">
                <p><a href="#_ftnref7" name="_ftn7" title="">7.</a> <em>Genesis,</em> p. 29 and <em>Doctor Faustus, </em>p.  1. The Everyman edition of Lowe-Porter&rsquo;s English translation has May 27, but  this is a misprint; the German text has May 23: Thomas Mann, <em>Doktor Faustus: Das Leben des deutschen  Tonsetzers Adrian Leverk&uuml;hn, erz</em><em>&auml;hlt von  einem Freunde</em> (Frankfurt am Main: Fischer Taschenbuch Verlag, 2008). </p>
              </div>
              <div id="ftn8">
                <p><a href="#_ftnref8" name="_ftn8" title="">8.</a> Mann apparently believed, from his reading of certain biographies,  that Nietzsche had knowingly contracted syphilis. (Beddow, p. 34.)</p>
              </div>
              <div id="ftn9">
                <p><a href="#_ftnref9" name="_ftn9" title="">9.</a> T. J. Reed, Introduction to <em>Doctor  Faustus, </em>p. xv</p>
              </div>
              <div id="ftn10">
                <p><a href="#_ftnref10" name="_ftn10" title="">10.</a> Letter from Mann to Agnes. E. Meyer, 30 May 1938, quoted in T. J. Reed, Introduction to <em>Doctor Faustus</em>, p. xv.</p>
              </div>
              <div id="ftn11">
                <p><a href="#_ftnref11" name="_ftn11" title="">11.</a> T. J. Reed, &lsquo;Mann and history&rsquo;, in <em>The Cambridge Companion to Thomas Mann</em>, ed. by Ritchie Robertson (Cambridge:  Cambridge University Press, 2002), pp. 1-21 (p. 5).</p>
              </div>
              <div id="ftn12">
                <p><a href="#_ftnref12" name="_ftn12" title="">12.</a> Georg Luk&aacute;cs, &lsquo;In Search of Bourgeois Man&rsquo;, in <em>Essays on Thomas Mann</em> (London: Merlin Press, 1964), pp. 13-46 (p.  15). </p>
              </div>
              <div id="ftn13">
                <p><a href="#_ftnref13" name="_ftn13" title="">13.</a> Sigmund Freud, &lsquo;The Uncanny&rsquo;, in <em>The Uncanny</em>, trans. by David McLintock (London: Penguin  Books, 2003), pp. 121-162, (p. 134).</p>
              </div>
              <div id="ftn14">
                <p><a href="#_ftnref14" name="_ftn14" title="">14.</a> Ibid., passim.</p>
              </div>
              <div id="ftn15">
                <p><a href="#_ftnref15" name="_ftn15" title="">15.</a> In Book VI of the <em>Aeneid.</em> Virgil, <em>Eclogues, Georgics, Aeneid I-VI</em>,  with English translation by H. Rushton Fairclough, revised by G. P. Gould, The  Loeb Classical Library (Cambridge, MA: Harvard University Press, 1999), pp.  520-521.</p>
              </div>
              <div id="ftn16">
                <p><a href="#_ftnref16" name="_ftn16" title="">16.</a> R. B. Kitaj, catalogue note on &lsquo;If Not, Not&rsquo; for the retrospective  exhibition of his work in 1994-1995; in Morphet, Richard (ed.), <em>R. B. Kitaj</em> (New York: Rizzoli, 1994),  p. 120.</p>
              </div>
              <div id="ftn17">
                <p><a href="#_ftnref17" name="_ftn17" title="">17.</a> Walter Benjamin, &lsquo;The Work of Art in the Age of Mechanical  Reproduction&rsquo;, in Lawrence Rainey (ed.), <em>Modernism: An  Anthology</em> (Oxford: Blackwell Publishing, 2005), pp. 1095-1113 (p. 1108).</p>
              </div>
              <div id="ftn18">
                <p><a href="#_ftnref18" name="_ftn18" title="">18.</a> Theodor W. Adorno and Max Horkheimer, <em>Dialectic of Enlightenment</em>, trans. by John Cumming (London: Verso,  1997), p. xi. </p>
              </div>
              <div id="ftn19">
                <p><a href="#_ftnref19" name="_ftn19" title="">19.</a> Theodor W. Adorno and Max Horkheimer, &lsquo;The Culture Industry:  Enlightenment as Mass Deception&rsquo;, in <em>Dialectic  of Enlightenment</em>, trans. by John Cumming (London: Verso, 1997), pp.  120-167.</p>
              </div>
              <div id="ftn20">
                <p><a href="#_ftnref20" name="_ftn20" title="">20.</a> Luk&aacute;cs, &lsquo;The Tragedy of Modern Art&rsquo;, in <em>Essays on Thomas Mann</em> (London: Merlin Press, 1964), pp. 78-84 (pp.  78, 80, 84). </p>
              </div>
              <div id="ftn21">
                <p><a href="#_ftnref21" name="_ftn21" title="">21.</a> Fredric Jameson, &lsquo;Allegory and History: On Rereading <em>Doktor Faustus</em>&rsquo;, in <em>The Modernist Papers</em> (London: Verso, 2007), pp. 113-133 (p. 116).</p>
              </div>
              <div id="ftn22">
                <p><a href="#_ftnref22" name="_ftn22" title="">22.</a> Alan Wall, &lsquo;Demotic Ritual: The Primacy of Form in Modern Art and  Physics&rsquo;, p. 11. </p>
              </div>
              <div id="ftn23">
                <p><a href="#_ftnref23" name="_ftn23" title="">23.</a> For a discussion of fascism in modern India,  for example, see Jairus Banaji, &lsquo;The Political Culture of Fascism&rsquo; (2002) &lt;<a href="http://www.sacw.net/new/BanajiSept02.html">http://www.sacw.net/new/BanajiSept02.html</a>&gt;  [accessed 14/02/08]. It is interesting that Banaji shares Mann&rsquo;s view of fascism as an  ideology nurtured not only by political conditions but by widespread cultural  and psychological tendencies. </p>
              </div>
          </div>            <P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
