<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--

-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue10/menu_issue10.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue10/bina_shah/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">The Believers  <span class="texto2">by <a href="../../issue10/bina_shah/bio.php" class="link3">Bina Shah</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           &nbsp;<br>
              <p>Yusuf kept  Mrs. Colewyn&rsquo;s secrets long after she died, like a faithful lover.&nbsp; He  never told his family anything about her &ndash; not the fact that she was adopted;  nor that her adoptive parents were Jews who had left their homeland because of  the pogroms in Russia, where they&rsquo;d been burnt out of house and farm before  making the long, arduous journey to England. They&rsquo;d settled in Luton and opened  a tailor&rsquo;s shop, making fine lace clothes for English ladies who couldn&rsquo;t  pronounce their last name properly. Mrs. Colewyn herself had never moved far;  she&rsquo;d ended her days in Yusuf&rsquo;s own neighborhood, in Bury Park, living and  dying in a tiny flat above his parents' halaal butcher-shop on the  corner.&nbsp; </p>
</div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <p>&ldquo;I&rsquo;m an  orphan, and my parents were refugees,&rdquo; she told him, not long after they'd  first met. &ldquo;A daughter of a poor Irish girl got &lsquo;into trouble&rsquo;, adopted by  Orthodox Jews who had nothing left, not even a pin to call their own, but they  felt sorry for her. What do you think of that, Yusuf?&rdquo; </p> 
            <p>He smiled  back, liking the feeling he got in his heart when his eyes met hers, amazed  that she'd tell him a secret like this, but even in those first few days, their  friendship had gone beyond simple pleasantries and everyday cliches. &ldquo;They  sound like very compassionate people.&rdquo;&nbsp; </p> 
            <p>He knew  instinctively to bite his tongue on the words that wanted to follow, about how  compassion was one of the Prophet&rsquo;s best qualities, peace be upon him. Whenever  Yusuf talked about religion, about Islam, Mrs. Colewyn's eyes would take on a  faraway gaze, and she&rsquo;d fiddle around with her hands in her lap, and the  silence between them would grow large and awkward, like a dog jumping up for  attention. </p> 
            <p>Mrs.  Colewyn came down from her flat every Thursday to buy a little meat for  herself. She was the only English person to ever shop at the Madina Meat  Market; unlike the others, she held no objection to the fact that the cows and  sheep and lambs were slaughtered in the Muslim way - a quick knife to the  carotid artery without electric shock or sedation. Nor did she mind that there  was no pork sold in the shop. &quot;I don't miss it. My parents kept kosher  when I was a girl,&quot; she explained once, while Yusuf was sitting in a  corner, doing his homework. He listened to her tell his mother how her parents  spent a small fortune keeping a kosher kitchen - separate dishes for meat and  dairy, separate pots to cook them in, the oven used at different times of the  day for preparing <em>chalav </em>and <em>basar</em>.&nbsp; </p> 
            <p>Yusuf's  mother nodded in a bewildered way, the dupatta falling down over her head to  expose her dark, luxuriant hair. &quot;So will you be wanting your lamb chops  like last time?&quot; </p> 
            <p>&quot;Yes,  dear. They were delicious! With a little onion sauce and some peas and carrots.  Though I suppose you don't eat them that way, with all your lovely spices and  chillies.&quot; </p> 
            <p>When she  had left, Yusuf's mother said to him, &quot;Is she a Jew?&quot; </p> 
            <p>&quot;I  don't know,&quot; said Yusuf. &quot;Maybe.&quot; </p> 
            <p>She sniffed  and pulled up her dupatta on her head. Yusuf wondered why she bothered with it;  it fell down a hundred times a day and defeated the purpose of wearing a hijab.  But he kept his opinion to himself. His mother went to the door of the shop and  turned the Open sign around, then leaned against the door and crossed her arms  over her chest. &quot;I don't like her.&quot;&nbsp; </p> 
            <p>The imam at  the mosque had warned them all to stay away from infidels. The boys in his  school filled their notebooks with drawings of Kalashnikovs and shouted  &quot;Allah hu Akbar!&quot; in the hallways, fists pumping the air like the  cheap gangsters that populated their streets. There had been a problem in Year  8, when one of the teachers had tried to take away a bleeping mobile phone from  one of the kids, and the kid had screamed out, &quot;Don't touch me! You're  English!&quot; Thus followed a furore, letters and complaints from the parents,  both English and Asian. articles written about it in the newspapers about  tolerance, diversity, assimilation. Big words bandied about by small-minded  people. Yusuf would never tell anyone that he was friends with an old lady who  was both a Christian <em>and </em>a Jew.  Neither his parents nor his friends nor the imam at the mosque would  understand.&nbsp; </p> 
            <p>Mrs.  Colewyn came faithfully to the shop every Thursday for two years, and then one  day she stopped coming. One week went by, then two. His mother didn't really  care. His father was too devout to look women in the face when they bought his  wares. Only Yusuf noticed that the old lady with the kind, weathered face and  piercing blue eyes wasn't coming in for her provisions. He started worrying  about her. What was she eating if she didn't do her shopping? Was she all  right? Had she gotten offended by something she'd overheard his mother saying  about her?&nbsp; </p> 
            <p>And then,  in the third week, a note turned up on the doormat. Yusuf found it when he was  going out on his way to school. <em>I have  not been well, so I have not been able to come for my shopping. Mrs. Alice  Colewyn. </em>The handwriting was flowery, what they called round hand, and he  stared at it for a good long while, wondering where on earth anyone had learned  to write so beautifully.&nbsp; </p> 
            <p>After  school, he came back to the shop, as he always did. Mother was taking a nap -  she got tired from being up late at night with the baby, who was now three  years old, but still referred to as &quot;the baby&quot;. Yusuf's father was  standing behind the counter, in his usual skullcap and butcher's apron,  arranging the fresh meat on trays - mince, for qorma and samosas, some of it  shaped into round patties, shami kebabs for ladies' parties; chicken, also  ground into mince, for the more health conscious; chops of lamb and mutton, and  even goat meat for the Jamaicans who cooked a spicy curry that Yusuf had heard  of but never tasted.&nbsp; </p> 
            <p>&quot;Abu,&quot;  said Yusuf, trying to inject his wobbling adolescent voice with a tone of sweet  innocence, &quot;can I take two lamb chops?&quot; </p> 
            <p>&quot;What  do you want them for?&quot; his father said, hardly looking up from his  work.&nbsp; </p> 
            <p>&quot;It's  Suleiman's mother's birthday but he doesn't have anything to give her so I  thought I could give him some chops to give to her.&quot;&nbsp; He waited for  Father to laugh and tell him to stop wasting time, that the shop needed  sweeping and the broom was in the corner. </p> 
            <p>But without  hesitation Yusuf's father took out a small bag of qeema and handed it to Yusuf.  &quot;I can't spare the chops but you can have some of this mince. That's a nice  thing you're doing for your friend. Shabash.&quot; </p> 
            <p>Yusuf ran  out of the shop, hoping that he'd be forgiven for the lie. When he was young he  thought his father knew everything and could tell whenever he was not telling  the truth. It was only now that he was older that he realized he'd confused his  father with God.</p>  
<p>He bounded up the stairs to Mrs. Colewyn's flat, stopping short only when he  reached her doorstep. He put his hand experimentally to the door. It felt warm  to his touch, as if it were alive, and breathing. He took it as a good sign and  tapped politely with only the tips of his fingers.</p> 
<p>&quot;Who's that?&quot; The voice was faint, quavering.</p> 
<p>&quot;It's Yusuf, from downstairs. The butcher shop.&quot; Yusuf tried to see  if anyone was peering through the porthole in the door. The light coming  through the porthole, like the pinhole of a box camera, blocked out for a  moment, then the door swung open, and a blast of warm air and the smell of  lemons washed over him.</p> 
 <p>He walked in, the plastic packet held out in front of him. &quot;Er... I've  brought your meat. I mean, I've brought you some meat. It's not what you  usually like, but...&quot; His words trailed away when he realized he was  speaking to the air. Mrs. Colewyn had retreated to her bedroom, and she called  out to him, as if from a great distance. &quot;Come in, lad, come closer.&quot;</p>  
<p>Yusuf felt the way Gulliver must have done when he landed in Lilliput: the flat  was so tiny that he, with his newly-lanky limbs and enormous feet (he'd woken  one morning to find they'd grown two sizes overnight, and at night tossed and  turned with growing pains in his legs that sometimes made him cry), could reach  his hands up and touch the ceiling, or out to the sides and brush his  fingertips against both walls of the tiny front room.&nbsp; The walls were  covered in an old-fashioned print, large stripes that repeated in patterns of  dove blue and dove grey, but the carpet on the floor was of an indiscriminate  color.</p>  
<p>He stood there and cleared his throat, not sure whether he should just leave  the meat on the counter and go, or whether she'd want to check it and ask for  something different. A minute or two went by, and then the voice, papery-thin,  called out again, &quot;Why did you say...&quot;</p> 
<p>Yusuf's voice boomed out in the flat, shaking the dust off the old photographs  in their brass frames. He hated how it did that all the time now, going up and  down like a Swiss yodeler's. &quot;I've brought you some meat, Mrs. Colewyn. I  heard you were feeling ill so I brought it for you... since you couldn't come  down to the shop...&quot; At that moment it occurred to him that she'd been  well enough to leave the note under the door, so she couldn't really be that  ill, could she? He blushed, feeling embarrassed that he'd been fooled into  coming upstairs by a lazy old woman. A lazy old Jew.</p> 
<p>&quot;Oh, that is so thoughtful of you. Won't you come in here a little closer,  young man?&quot; He did as he was told. She was lying in the bed, a very  different figure from the one that smiled her way into the shop, clutching a  straw basket in one wiry arm. Lying down, she looked smaller, flatter, her  strong blue eyes faded and rimmed with red. Her hair, usually done in a neat  bun, stood up wildly all around her face, and Yusuf fought a strange urge to  find a brush and neaten it, to restore her to that neat, prim figure that he  remebered.</p> <p>
</p> 
<p>In Mrs. Colewyn's overheated flat, beads of condensation gathered on one of the  small windows above an old dresser, blocking out the view of the brick wall  beyond. Yusuf was reminded of the school trip to the Triangle Garden, where they'd  been shown organic vegetables and multicolored wildflowers in sub-tropical  heat, while a cold grey sleet fell outside. &quot;Would you like me to turn  down the heat?&quot; he said.</p> 
<p>Mrs. Colewyn was perspiring heavily; the sheets underneath her had grown damp  patches, and there was a sheen above her lip. &quot;Oh, thank you dear, but  it's stuck. I think the radiator is broken, actually.&quot;</p>  
<p>Yusuf held out the packet of meat to her. &quot;It's for you.&quot;</p> 
<p>Mrs. Colewyn's face broke into a smile, the wrinkles around her mouth and on  her forehead creasing into a dozen small riverbeds across her dusty skin.  &quot;You <em>are</em> kind. What's your  name?&quot;</p> 
<p>&quot;Yusuf.&quot;</p>
<p>&quot;I shall settle with your mother when I'm on my feet again, Yusuf.&quot;</p>
<p>&quot;You don't have to do that. It's a gift. I hope you feel well soon.&quot;</p> 
<p>He turned to go, feeling the blush spread to the roots of his hair, but a  strange sound made him glance back. It was the sound of Mrs. Colewyn crying.  Alarmed, he stepped close to the bed. &quot;Are you all right?&quot;</p> 
<p>She couldn't speak, and he realized that she wasn't crying; a prolonged  coughing fit had started out small and muffled in the bottom of her lungs. Soon  a mighty war to force the air into her uncooperative lungs was underway. Yusuf  shuffled his feet, watching to see if her lips turned blue, the way he'd been  taught in his First Aid class. He spied a glass of water on a small table next  to the bed, reached for it and offered it to Mrs. Colewyn.</p>
<p>At first she could hardly speak, but then her panting and groaning gradually  turned into half-formed words. &quot;Oh, thank you, thank you my dear.&quot;</p> <p>Yusuf took the glass from her shaking hand, and watched as the color came back  into her cheeks. She smiled weakly. &quot;Yes, this happens to me quite a lot.  You mustn't be afraid. They told me I could have oxygen if it becomes  unbearable, but not yet, not yet...&quot;</p>
<p>&quot;But what's wrong with you...&quot;</p> 
<p>&quot;They call it COPD. Chronic...something or other, pulmonary... Disease. My  lungs aren't working very well. It's a bother, but what can you do?&quot;</p>  <p>&quot;Is it cancer?&quot; The question burst out of him before he could apply  his mind towards its appropriateness. Lately the question of death had begun to  bother him, especially after listening to the imam at the mosque  enthusiastically informing them would happen to them after they died. <em>Seventy-two virgins! Beds of pearls... wine  that won't make you drunk</em>... Yusuf, who had not yet developed an interest  in girls or in alcohol, and preferred a duvet to sleep on at night, felt that  if these gifts were supposed to make him more inclined to die sooner rather  than later, they were woefully inadequate.&nbsp;</p> 
<p>Mrs. Colewyn must have seen the alarm on his face, because she pulled herself  up with thin but wiry arms, as if an upright position would reassure Yusuf of  her hardiness. &quot;Oh, my dear, no, no! In my day we would simply have called  it 'having a weak chest'. But these doctors, my goodness, they have to find  fancy names for everything under the sun, don't they?&quot;</p>
<p>&quot;Not just doctors,&quot; said Yusuf, thinking about how what would have  once been called devout or simply Muslim was now called fundamentalist and  extremist.</p>
<p>He surprised even himself by telling Mrs. Colewyn he'd be back to see how she  was doing, and, skipping down the stairs two at a time, resolving to visit her  every day until she was well again.</p>
<p>-- </p> 
<p>Another day in  school, and the trial of the radical preacher Abu Hamza was all over the news.  An English boy in Year 7 had gotten a kicking on the playground because some of  the Muslim boys thought he'd been making a hook with his hand. They took him to  a picnic table at the far side of the ground and wedged him underneath it, then  kicked him until a teacher saw what they were doing and ran at them, scattering  the boys like dry leaves in a winter's wind. &nbsp;When the teacher fished the  boy out from underneath the table, he'd been beaten so badly that he had to go  to the hospital and be treated for a concussion, a perforated ear drum, and  three broken ribs.&nbsp; </p> 
<p>Now the  assailants were facing expulsion and the parents in Yusuf's neighborhood were  furious. Some of the fathers had gathered in the butcher shop, considering  whether or not to organize a protest. The mothers were in the back room,  drinking cups of hot mixed tea and gossiping about the boys who were going to  be expelled. They never sat and talked together, the mothers and fathers, and  Yusuf wondered if they had even wanted to be included. </p> 
<p>At this time of  day the freezer cabinets were almost empty; only a desultory pack of mince or  giblets lay on the shelves, and Yusuf walked carefully behind the men, hoping  to be able to take a last packet without being noticed.</p>
<p>He listened to  the cacophony of male voices, speaking quickly in Mirpuri, feeling like a  rudderless boat stuck in a sea with too many currents. He'd been there, he'd  seen the boys that did it. They were all Muslim boys, it was true. But it was  also true that the white boy had held up his left hand in the shape of a  deformed claw and shook it at the Muslims, while his friends, both black and  white, had sniggered and mouthed obscenities. The Bangladeshi boys who wore  bandanas and roamed around the streets in gangs after school had leapt at the  boy like nimble panthers and pinned him down while his friends watched,  open-mouthed at the swift administration of their form of justice.&nbsp; It had  reminded him of that book that he'd read a few years ago, with the boys who  were abandoned on an island, and had quickly turned violent and dangerous in  order to survive. He shuddered at the memory of the screaming and hollering,  the sound of their shoes striking the white boy's body, as if sacks of potatoes  were being dropped on the ground.</p> 
<p>&quot;What proof  do they have?&quot; said Ramiz's father, clutching the sheet of paper that had  come from the school in his son's bag. &quot;They always blame the Muslims.  Always!&quot; </p> 
<p>&quot;It's  nothing new!&quot;&nbsp; </p> 
<p>&quot;Always our  fault.&quot; </p> 
<p>&quot;They won't  be happy until they've kicked us all out.&quot; </p> 
<p>&quot;It's a Zionist conspiracy.&quot; This was Yusuf's father, who was still  wearing his butcher's apron, the uniform giving him a feeling of added  importance, to which the other men happily deferred.&nbsp;</p> 
<p>Just as he made  this pronouncement, a deep clang rang out from the empty freezer behind all of  them, making them all jump. Yusuf's father apologized - something must have  fallen off a shelf, or perhaps a block of ice had come loose and crashed onto  the floor. He got up to check, shaking his head as if this, too, was a  conspiracy on the part of the Zionists. </p> 
<p>Yusuf's blood  seemed to prickle inside his veins. He'd heard the words they'd used many times  before, shouted in the mosque, whispered, spoken in Urdu in front of someone's  face, muttered every time the television showed what was happening in  Palestine. He didn't even know what it really meant - everyone nodded sagely  when it was spoken, as if it was code for something you just knew if you were  born Muslim in Britain.&nbsp; </p>
 <p>And yet, there  were provocations: the mosque's windows shattered by drunken yobs throwing  stones; Muslim graves spraypainted with swastikas; women spat upon or their  veils pulled off their heads in the streets. Yusuf had seen the anger, the rage  in his elders' faces, coupled with the immutable knowledge that they would  never be respected or accepted the way the English were. In those moments he  could understand why they blamed the English; there was simply nowhere else for  their feelings to go.</p> 
 <p>But he hated it when the kids in school said it to each other, especially about  their teachers, and most often when they'd gotten a low grade on an exam.  &quot;Bastard!&quot; they'd spit. &quot;Always trying to keep us down.&quot;</p> 
 <p>Ramiz added &quot;Yahudi&quot; to the litany of insults aimed at Mr. Fakan, the  science teacher, as he passed them in the halls, the day after a mock exam,  when Ramiz had gotten the worst grade in the entire class.</p> 
 <p>&quot;You know, he can probably understand that word,&quot; said Aisha, a serious,  bespectacled girl from their year. It was rumored that she was going to take  ten AS levels and that she had aspirations of going to university, although  girls from around here either went to work as shop assistants or got married to  their cousins from Pakistan.</p> 
 <p>&quot;Get out! How would he know that? It's Arabic?&quot;</p> 
 <p>&quot;Yeah, but it's the same word in Hebrew. If he's Jewish, he'll know that  for sure.&quot; Aisha was calm in her confidence, and Yusuf found himself  admiring the way she stood with her neck straight and shoulders thrown back,  not hunched over to hide her chest the way the other girls scuttled around in  the halls.&nbsp;</p> 
 <p>Ramiz glanced at the other boys darkly, shamed at having been caught out by a  girl. Then he scowled at Aisha. &quot;Was we talking to you anyway?&quot;</p> 
 <p>She shrugged and walked away.&nbsp; </p> 
 <p>&quot;Stupid  cow!&quot; Ramiz sent the insult after her like a well-aimed cricket ball,  looking to his cohorts for appreciation.&nbsp; </p> 
 <p>But Aisha never  turned around or looked back at them, and they all felt a few inches smaller  because of that.</p> 
 <p>&quot;Hey, don't call her names,&quot; said Mohsin, one of the few boys in Year  8 who refused to be one of Ramiz's sycophants. Yusuf couldn't help but wonder  whether this, too, was to be admired, or whether it was a dangerous assertion  of Mohsin's independence. Too dangerous to be emulated, certainly, by Yusuf,  who lacked Mohsin's musculature or his four elder brothers.&nbsp;</p> 
 <p>&quot;Why not?&quot;</p> 
 <p>&quot;She's a sister. One of us, yeah?&quot;</p> 
 <p>&quot;She ain't <em>my</em> sister.&quot;</p>
 <p>Yusuf had, from that day onwards, tried to erase the word <em>yahudi</em> from his vocabulary. It was easy to let it slip out like a  curse when something went wrong: when the bus driver wouldn't stop for you, or  you didn't have enough money to pay for the snacks you wanted in the corner  shop. But if all Jews knew what it meant, the word lost its power, and became  something different: no longer a weapon, but a weakness. He was good in maths,  anyway, and Mr. Fakan had never given him a bad grade that he didn't deserve.</p> 
 <p>And now that he and Mrs. Colewyn were friends, it was best to forget that he'd  ever known the word. Who knew when it would come out from his mouth like a  cobra, ever ready to deliver its poison with an unexpected blow?&nbsp; </p> 
 <p>The men's meeting  died out hardly half an hour later, when it was time for the evening prayer. It  was always like this: a lot of anger, a few stock phrases about the injustice  of the English, the immorality of British society in general. Never once had  Yusuf seen his father or uncles or neighbors actually <em>do </em>anything about what was wrong. They met their councilor to  complain about pork sold in the school canteen, or someone making fun of a  woman's niqab, but as far as organizing, voting, signing a petition - they were  strangely impotent. They did not believe in the system, Yusuf realized, even  though they found the system vastly superior to anything they'd encountered in  the countries they or their fathers and mothers had left behind.&nbsp; </p> 
 <p>Yusuf raced up  the stairs to Mrs. Colewyn's flat, a packet of biscuits accompanying the  giblets that he knew she'd like boiled up in soup for her tea. He knocked, then  let himself in; she'd told him she'd leave the door open for him at four  o'clock, and he tried to be prompt, worried that some day a drug-crazed thief  would find the unlocked door and rob her.&nbsp; </p> 
 <p>This had fast  become his favorite time of the day; he brought his schoolbooks to her flat,  and worked on his homework, or read a book for one of his classes, while she  sat at the table opposite him, cutting vegetables for her evening meal.  Sometimes she asked him to help her thread a needle or read something out to  her because her eyesight was weak. She'd recovered from her illness, and they  sat companionably together, in silence, while the rain fell outside in steady,  cold sheets, and the television flickered with blue ghosts in the far corner of  the room.</p> 
 <p>Today, as they sat together and peeled potatoes for a shepherds pie that she  wanted to make, Mrs. Colewyn talked and Yusuf listened. He'd been raised not to  interrupt his elders, but he'd had no grandparents to practice his respect with  - they were far away in Mirpur, and also dead, since he was small. And Mrs.  Colewyn, unlike his elders, didn't mind when he asked questions.&nbsp; </p> 
 <p>It was an  unfamiliar warmth that he felt, as Mrs. Colewyn told him stories about her parents  who had struggled to establish their tailor's shop at first but found  prosperity after the first few hard years. He wasn't used to this openness,  this level of honesty. He'd been raised to keep quiet about personal history,  in order to avoid giving gossips more fuel for the fires they loved to set in  the neighborhood. But Mrs. Colewyn talked and talked, revealing more and more  secrets as if she couldn't give them away fast enough. Her parents had been  unable to have children of their own; then she had come into their lives, a  sudden gift from an arbitrary God who had seen fit to take her mother away  after three days of hard labor in her childbirth bed. It was her punishment,  the parish priest who'd buried her had said, for having committed the sin of fornication  and having the misfortune to fall pregnant from it.&nbsp; </p> 
 <p>&quot;But my  parents felt so sorry for my mother, who had worked for them as a maid, of  course until she couldn't hide her pregnancy any longer, that they adopted me.  The priest threw a fit, but the home she'd gone to wasn't a religious one; it  was run by the Quakers, and there were already too many orphans, so they  allowed my parents to bring me home with them. And they raised me as if I were  a daughter to them, although I always knew I wasn't - I didn't look anything  like them!&quot;</p> 
 <p>&quot;So which do you feel more of,&quot; asked Yusuf, &quot;Christian or  Jewish?&quot; He could hardly believe that they shared this intimacy, but she  seemed to welcome it, treat it as something normal, even appreciated. People  stopped listening to the elderly, so that they grew full with the weight of  their own stories, until they found someone willing to listen to them - like  Yusuf.&nbsp;</p> 
 <p>&quot;I suppose...&quot; She drew her eyebrows down in concentration, as if  considering the question for the very first time in her life, although Yusuf  knew that she'd had to think about it all her life. &quot;I suppose both,  really. Legally, you know, technically, I can't be Jewish, because it's passed  through bloodlines. Through your mother, and my mother was Catholic.. But I've  always felt comfortable with both, you know. Half and half, then, that's what I  must be!&quot;</p> 
 <p>Yusuf said, &quot;In Islam, if your father is Muslim, then you're Muslim  too.&quot;</p> 
 <p>&quot;What if your mother were Christian, or Jewish? Would you be half?&quot;</p> 
 <p>&quot;I don't think so... I don't know. I'll ask.&quot;</p> 
 <p>Every day, talking with Mrs. Colewyn created more and more ideas in his mind,  stored up and woven carefully into non-incriminating questions he longed to  pose the imam at the mosque. He imagined the conversation that would ensure,  though:</p>  
 <p>&#8212;Are all Jews and Christians infidels?</p> 
 <p>&#8212;Of course.</p>
 <p>&#8212;Do they all go to hell if they don't accept Islam, even the good ones?</p> 
 <p>&#8212;Inevitably. Once they hear the message, either they accept it or they perish.</p> 
 <p>&#8212;Then why are they called Believers in the Quran?</p> 
 <p>&#8212;There are some things that God knows better than we do, and it is best not  to question.</p> 
 <p>In the mosque, they were told that all Christians and Jews and Hindus and  non-Muslims of every creed and ilk and skin color were their enemies; but they  were living amongst them, going to school with them; some people even fell in  love with them and married and had babies that were, like Mrs. Colewyn, half  and half. What were they, then? And were their worlds really so far apart, or  were they all thrown together to live on one earth, with only their ideas  separating them? Which was God's will - war, or peace; friendship or enmity?  But he knew he could ask these questions of the imam, a sturdy, velvet-skinned  man with caterpillars for eyebrows crouched over hazel eyes, who had been  imported from Mirpur to address the spiritual matters of the migrant Kashmiri  population in the language they could best understand (a softly-spoken dialect  of Punjabi that burbled and tripped on the tongue like water in a gentle  mountain brook, weighed down with thoughts and conventions that were older than  time).</p> 
 <p>Mrs. Colewyn was telling him about her husband now. &quot;Their name was  Coleman, but they changed it to Colewyn to make it sound more English.&quot;</p> 
 <p>&quot;When?&quot;</p> 
 <p>&quot;Oh, I don't know, at least a hundred years ago. But there are many  Anglicized Jewish names, did you know that? Like Cowan - it's the English name  for Cohen. Or Greenfield for Gruenfelder.&quot;</p> 
 <p>&quot;I know people who do that with their first names, too. Sameer becomes Sam,  Bilal becomes Bill.&quot;</p> 
 <p>&quot;They do that to fit in. It's the same the world over.&quot;</p> 
 <p>&quot;I don't like it. They're beautiful Muslim names. We shouldn't be ashamed  of them.&quot;</p> 
 <p>&quot;What's in a name? A rose by any other name would smell as sweet...&quot;</p>
 <p>Yusuf laughed. &quot;I didn't know you liked Shakespeare!&quot;</p> 
 <p>&quot;Of course, and my husband adored him! We watched all the plays, Sir  Laurence Olivier, Richard Burton, Peter O'Toole...&quot; </p> 
 <p>&quot;What was  your favorite play?&quot; </p> 
 <p>&quot;Merchant of  Venice!&quot; she said without hesitation.&nbsp; </p> 
 <p>&quot;I know that  one. We studied it last year, in English.&quot; </p> 
 <p>She smiled.  &quot;Such drama! So much passion! I remember a wonderful actor, a German  fellow, named Rischstadt, I think he was, play Shylock. I nearly wept in the  trial scene - magnificent!&quot;</p> 
 <p>&quot;But... didn't it make you feel bad?&quot; </p> 
 <p>&quot;How do you  mean, love?&quot;&nbsp; </p> 
 <p>&quot;Well...  Shakespeare, I mean, he wasn't exactly sympathetic to the Jews in that one, was  he? He made Shylock a horrible person. He disowned his own daughter for  marrying someone who wasn't Jewish!&quot; But even as he said it, Yusuf  remembered the whispers about Muslim girls, from Bradford or Birmingham, who  married of their own choice: how their parents disowned them, their brothers  beat them, their communities shunned them. &nbsp;And the others, the Turkish  girl who'd been murdered by her own father for running away with her English  boyfriend. The Arab girl who... He tried to push the memories out of his mind,  the headlines, that screamed at him from the front pages of red tops and made  him feel ashamed to be alive.&nbsp; </p>
   <p>Mrs. Colewyn said, &quot;There is that. I can't say it isn't true. Still, they  learned their lesson at the end, didn't they?&quot; For a minute, her eyes  dropped away, and Yusuf wondered what memories were coming to her right now.  Was she thinking of her parents? Was there some man that had come along before  Mr. Colewyn, to steal her heart away, that her parents hadn't approved of?  &nbsp; </p> 
   <p>Yusuf dearly  wanted to tell her that real life was not a Shakespearean play. That life in  Walthamstowe was not about tragedy or drama, but the small heartbreaks that  occurred day by day, a constant drip of rainwater to weaken the strongest  foundations of anyone's sense of security. That his parents, the boys in  school, everyone around him, walked as if on a rope stretched between two countries,  that could one day break and send them tumbling into a hell that nobody on  either side could understand. But he lacked the vocabulary to tell her of his  pain. </p> 
   <p>&quot;Careful,  dear,&quot; said Mrs. Colewyn. &quot;You're getting a bit careless with that  knife.&quot; </p> 
   <p>Yusuf steadied  his hand, tired of peeling the potatoes. He put down the basin, stretching his  fingers out to relieve the pain in his wrists. &quot;You have enough for three  pies!&quot; </p> 
   <p>But Mrs. Colewyn  went on as if she hadn't heard him. &quot;You might cut yourself, and then you  might bleed... Shakespeare would have to write another play...&quot; </p> 
   <p>He thought at  first that she was laughing at him. But her smile was gentle; it contained a  thousand other stories he was afraid he might never get the chance to  hear.&nbsp; </p> 
   <p>-- </p> 
   <p>Aisha and Yusuf  had been made partners in the biology lab. Yusuf had to endure his friends'  ribbing (&quot;a girl! why don't you just go to Domestic Skills and learn how  to knit a cardigan together?&quot;); he suspected some of them were secretly  envious he'd gotten her as his partner. She never put her hand up in the air to  attract the teacher's attention more than necessary, but when called upon, knew  all the answers, spouting off her knowledge with an ease that impressed  teachers and infuriated fellow students. Yusuf had formulated a plan to let  Aisha do the hard work and he'd just write down everything she said. Biology  was not his strongest subject, and she was too nice to stop him anyway.</p> 
   <p>Mr. Fakan, the biology teacher, walked around the lab, setting down a  dissection pan in front of each pair of students. &quot;No, don't remove the  covers until I tell you. Just wait until everyone has got one.&quot;</p> 
   <p>&quot;Ugh, it stinks, sir,&quot; moaned Ramiz, holding his nose with his finger  and thumb and rolling his eyes.</p>
    <p>&quot;That's the formaldehyde. Preserves everything beautifully. Be very  careful not to get that in your eyes, keep your safety goggles on throughout.  And your gloves, because this can irritate your skin. Let's take a look at the  dissection kit, everyone.&quot;</p> 
    <p>Yusuf opened the kit and examined its contents: a scalpel, pair of scissors,  metal probes, forceps. Aisha picked up the scalpel in her hand delicately, as  if it were a feather quill. &quot;I'd love to be a surgeon.&quot;</p> 
    <p>&quot;Could you stand all the blood?&quot;</p> 
    <p>&quot;Huh! I'm much tougher than you think. The sight of blood doesn't bother  me one bit.&quot;</p> 
    <p>She made a few practice swipes with the scalpel, then gave him a cheeky,  uncharacteristic wink. Yusuf bent his head and examined her closely out of his  peripheral vision. Despite a few blemishes on her cheeks and the tight hijab  that pulled her hair out of sight, emphasizing her prominent nose, she wasn't  terribly ugly. She didn't deserve those gagging noises the boys made when she  walked down the hall. She had soft brown eyes and dimples. In fact...she was  quite pretty.</p> 
    <p>Yusuf felt an unfamiliar tightening in his stomach and a sudden dryness in his  throat. But before he could make any sense of his feelings, Riffat, at the next  table, turned to page 173 and screamed out in horror:</p> 
    <p>&quot;Is you serious? We gonna be dissecting a <em>pig</em>?!&quot;</p> 
    <p>Twenty pairs of eyes stared up at Fakan. &quot;Not an entire pig, just its  kidney. Many aspects of its internal and external anatomy are identical to  humans, so that's why we're studying them. Much more complex systems than frogs  or earthworms, which we've already done.&quot;</p> 
    <p>&quot;You <em>what</em>?&quot;</p> 
    <p>&quot;Did he say that pigs are identical to humans?&quot; </p> 
    <p>&quot;Is he  having us on?&quot;</p> 
    <p>&quot;He never...&quot;</p> 
    <p>Fakan ignored the outburst and held up his hands with authority. &quot;I know  some of you are squeamish about dissection, so we aren't doing a full animal,  but I've got a special video for you from the US: you can see the dissection of  a full fetal pig on the screen here.&quot; He turned to the television set  behind him and switched it on; the screen was filled with the image of a small  pale creature in a dissection pan, wrinkled and shrunken, a rubber doll's  floppy body with a cartoon snout and closed, delicately lashed eyes. &quot;All  right, students, you may remove the covers off your pans now.&quot;</p> 
    <p>Yusuf and Aisha stared at each other in disbelief. &quot;Do you want  to...&quot; began Yusuf.</p> 
    <p>&quot;No... no. You go ahead.&quot; Aisha let the scalpel fall from her fingers  with a clatter. She pushed the tray towards Yusuf. &quot;I am of the weaker  sex, you know.&quot;</p> 
    <p>Yusuf peeled the plastic cover away from the tray with the tips of his fingers.  Immediately the chemical stink assailed his nostrils, and Aisha took two  startled steps back. They held their breaths and peered into the pan, blinking  at the small lump that lay there, a large bean that seemed to quiver, drawing  in breath and letting it out again, even though they both knew it was  inanimate, unmoving.</p> 
    <p>&quot;Now you don't have to worry that any pigs were killed unnecessarily for  this,&quot; said Fakan.&nbsp; &quot;These kidneys were taken from animals which  were already being slaughtered for food. But of course I understand that some  of you may be disturbed by the death of a living creature, and I don't take it  lightly, so I want you to be serious about your work today. We're dissecting  because this is the best way to learn the structure of the kidney. Otherwise  I'd just have you look at diagrams, but well, for concrete thinkers and visual  learners, nothing replaces the experience of dissection. So let's now look at  the external anatomy of the specimen in front of you.&quot;</p> 
    <p>Yusuf touched the kidney with his eyes half-closed. It felt cold and rubbery,  and the wrenching stench of formaldehyde made him want to choke. On screen, two  American students were working on the fetal pig: its neck was stretched back,  its forelegs raised high in a frozen stretch. It was a strange color, not pink  as he'd always seen piglets on television or in picturebooks, but a waxy  indeterminate hue that wavered between yellow and ash. The sights on the  television and the kidney in the pan in front of him both made him want to  vomit.&nbsp; </p> 
    <p>&quot;I think you  have to cut in... well it says, dorsal and ventral,&quot; said Aisha, her eyes  glued to the lab manual. Yusuf wished he could switch places with her, but she  clutched the book tight enough to tell him that he was stuck with the job of cutting.  &nbsp;His mother and father harbored dreams of him becoming a surgeon, but  after today, he knew he'd never be able to make them come true.&nbsp; </p> 
    <p>&quot;Now be  careful with the scalpels,&quot; Fakan was intoning at the head of the  classroom. &quot;The veins are injected with blue latex dye, and the arteries  with red latex, so you can distinguish them from each other.&quot;&nbsp; </p> 
    <p>Yusuf watched as  the American students finished tying back the pig's limbs, spread-eagling the  creature in the pan. He cocked his head to the side to survey their handiwork,  wincing. &quot;Don't they need to tie its mouth shut?&quot;&nbsp; </p> 
    <p>&quot;Why would  they?&quot; Aisha asked. </p> 
    <p>&quot;I dunno...  don't they do that when someone dies? Tie their jaw with a handkerchief so  their mouth doesn't flop open?&quot; </p> 
    <p>&quot;That's for  a funeral, not a science class!&quot; Her face had turned a peculiar color,  too, the usual sandalwood brown of her smooth cheeks giving way to a bilious  green. All around them the other students displayed the various symptoms of  disgust: making retching noises, rolling their eyes and holding the pans as far  away from them as possible. Some were gamely making an attempt to begin the  dissection, and Yusuf picked up the scalpel and saw in the text where he was  supposed to look for renal pyramids, for the ureters, the arteries and veins marked  on the diagram like the fine lines on a roadmap.&nbsp; </p> 
    <p>&quot;Which way  am I supposed to go? Up or down?&quot; </p> 
    <p>&quot;I don't  think it matters...&quot; </p> 
    <p>Yusuf was about  to make the first cut when a voice rang out in the classroom: &quot;I ain't  doing this, it's bloody haram!&quot; </p> 
    <p>A collective gasp  went around the classroom. Yusuf didn't need to look up to know that it was  Ramiz who'd spoken. Ramiz, with his swagger, his rudeboy haircut, and (it was  whispered but never confirmed) a tattoo of the sword of Zulfiqar on his back,  who bragged about all the girls he had shagged, the alcohol he'd drunk, the  hash he'd smoked with his cousins in Pakistan, but said he'd been to Hajj five  times in his life and that Christians and Jews should be killed for refusing to  accept the message of Islam. He was all of fifteen years old.&nbsp; </p> 
    <p>Fakan said,  &quot;I beg your pardon, Ramiz?&quot; </p> 
    <p>Ramiz folded his  arms across his chest. &quot;Pigs. It's against my religion. Not permitted for  Muslims to touch pigs. They're dirty creatures. I ain't doing this class.&quot; </p> 
    <p>Now it was the  teacher's turn to roll his eyes. &quot;Ramiz, I know all about the rules for  halal consumption. It applies to the food you eat, not a pig's kidney in a  biology lab. Now would you please stop disrupting my class?&quot; </p> 
    <p>&quot;Nah, man,  you can't make me. It's against my human rights.&quot; </p> <p>
&quot;But...  nobody else seems to have a problem with the dissection. Isn't that right?  Mohsin, is this against Islam? You're not actually eating the animal, so it  can't be disallowed, can it?&quot; Fakan spread his hands out in a signal of  appeal that Yusuf thought made him look weak in front of all the students. If  he were the teacher, he'd tell Ramiz to shut up and do the lesson or leave the  room, not argue with him. Ramiz, for all his bluster and bullying, lacked  enough intelligence to understand the logic behind many of his own ideological  stances, and if argued with, would run out of reasons for why he'd taken the  stand in the first place.&nbsp; </p> 
<p>Mohsin glanced  down at his feet and mumbled, &quot;Dunno, sir.&quot;&nbsp; </p> 
<p>&quot;Yusuf?&quot; </p> 
<p>&quot;I'm not  sure, sir.&quot; Yusuf knew he'd get grief from Ramiz for calling Fakan  &quot;sir&quot; - Ramiz called Fakan &quot;man&quot; to his face and  &quot;yahudi&quot; behind his back. Showing deference to the infidels was  tantamount to betraying the entire Muslim ummah, according to Ramiz.&nbsp; </p> 
<p>Fakan's eyes  scanned the room and finally fell on Aisha, the only girl in the class wearing  a hijab. &quot;Aisha? Is it disallowed to do this dissection? You look like  you'd have a sensible answer for this dilemma.&quot; He nodded smugly; Aisha  could be trusted to give him the right answer.&nbsp; </p> 
<p>Aisha lifted her  chin. &quot;It's very wrong, Mr. Fakan. We're not allowed  to have anything to do with pigs. It's not just about eating them. We can't buy  them, we can't sell them. We can't serve them to anyone else. We can't sit at a  table if pork is being served. We can't go into a place where a pig is. We  can't even use a hairbrush if it's made of boar bristles.&quot; Yusuf's mouth  dropped open. Mohsin was goggling at her like a goldfish. Aisha continued  blithely on, her voice taking on a singsongy tone. &quot;The Prophet Muhammed,  peace be upon him, said that any man who touches a pig, his prayers are not  accepted for forty days. The angels will not come to his house, and he will be  questioned for it on the Day of Judgment.&quot; </p> 
<p>She smiled at him  sweetly. The students began to whisper to each other, but Yusuf could only  stare wide-eyed at her cunning.&nbsp; </p> 
<p>&quot;Besides,  Health and Safety regulations have banned dissections in most biology classes  in the UK. The instruments are too dangerous for students to handle.&quot; She  spoke out in a loud, clear voice, like the pealing of a church bell on a  wintery Sunday morning.&nbsp; </p> 
<p>Fakan opened his  mouth once or twice, but the only thing that came out was a dry wheeze.  Red-faced, he finally found his voice and mumbled, &quot;Well then.... well...  well I suppose... in that case... I suppose I've no choice but to... I didn't  know...&quot; </p> 
<p>&quot;Sorry,  sir?&quot; Aisha said.&nbsp; </p> 
<p>&quot;All right,  class cancelled, but next time I don't want to hear a word about... class  dismissed!&quot; </p> 
<p>An almighty cheer  went up in the classroom, and Ramiz punched the air a few times. Steel trays  were pushed away with a loud clatter, scalpels thrown down gleefully, and they  put their books away in their bags, grinning at one another. Ramiz gave  Churchill's V-for-Victory sign as he strutted out of the class; he quickly  turned his palm inwards and gestured towards Fakan's back as soon as he was in  the doorway.&nbsp; </p> 
<p>Yusuf dumped the  untouched kidney into the biological hazard waste bin, while Aisha packed up  the instruments into the dissection kit. As he gathered up his books and  shouldered his bag, he whispered to her, &quot;Why did you do that?&quot;&nbsp; </p> 
<p>&quot;I didn't  think you could handle all the blood,&quot; she whispered back. They both  rushed out of the classroom, giggling like children, avoiding Fakan's dark  scowl; Yusuf was dimly aware this was the second time in a row that a woman was  having a laugh at his expense, and he was bemused to discover that he didn't  mind in the slightest.&nbsp; </p> 
<p>--- </p> <p>
All the way home,  he thought of how he'd tell the tale of the disastrous lab to Mrs. Colewyn.  He'd have to explain to her Aisha's cleverness, Ramiz's obnoxious behaviour,  the defeated look on Fakan's face. He rehearsed his lines in his head,  imagining how Mrs. Colewyn would laugh until she cried, how she would chide him  for being so triumphant at their chicanery. But she'd sympathize with them,  she'd maybe even tease him about his obvious crush on Aisha. His imagined  protests tasted sweet in his mouth, even before he'd had the chance to deliver  them.</p> 
<p>But when he reached his lane, and saw the ambulance parked in front of the  house, he froze. His fingers tightened on the strap of his schoolbag and his  quick, energetic steps slowed down until he had to remind himself to put one  foot in front of the other.&nbsp; </p> 
<p>A police officer  at the corner, a stocky black woman with arms folded across her solid bosom.  Yusuf approached her, forgetting all about his day in school, trying not to let  his voice quaver with fear. &quot;What's happened? Is something wrong?&quot; </p> 
<p>The woman turned  around and regarded him with a cool, distant stare. &quot;Do you live  here?&quot; </p> 
<p>&quot;Yes, it's  my father's shop.&quot; He was praying harder than he'd ever prayed before.  Please let it not be his father. Let it not be his mother. No heart attack, no  sudden fire, no robbery with young kids desperate for drug money and a careless  gun. Please, let them be safe.&nbsp; </p> 
<p>&quot;The lady  that lives at the top of the building made a distress call. They're seeing to  her now.&quot; </p> 
<p>&quot;Yusuf?&quot;  It was his father, emerging from the bowels of the shop, blinking in the grey  sunlight.&nbsp; &quot;Yusuf, come inside, leave them, let them be.&quot; The  instructions were issued in swift, familiar Mirpuri. Yusuf should have been  relieved; he should have thanked God for answering his prayer before it had  even left his lips. But the fear had only heightened, turned into heavy dread  that seized his stomach and made him want to strike out at an invisible  predator.</p> 
<p>Then, out of the corner of his eye, he saw it: his father nodding at the  policewoman briefly, and she nodding back at him. Yusuf caught the looks  exchanged between his Pakistani father and the English woman: they were  conspiring together to send him inside, to shield him from what was going on  upstairs to Mrs. Colewyn. </p> 
<p>Weighing his  options, nostrils flaring, fists clenched, he suddenly pushed past his father  and dashed inside the house.&nbsp; </p> 
<p>&quot;You can't  go in there, sir! Stop!&quot;&nbsp; </p> 
<p>&quot;Yusuf! Come  back, for God's sake!&quot; </p> 
<p>He raced up the  stairs two at a time, dropping the heavy schoolbag as he went. It fell end over  end all the way down, crashing like a sack of rocks at the bottom of the  landing. He didn't care who it hit; he hoped it would wedge against the door of  his home and lock his mother inside there. She was like his father, like all of  them in his stifling little community, who wanted to keep him down, stop him  from making a commotion, from being troublesome. To keep him out of the way,  quiet and obedient, as they'd want him to stay all his life, never to make his  own decisions, always a wretched slave to their desires, always a boy, never a  man.</p> 
<p>The door to the  flat gaped open. Inside he could hear the paramedics talking to each other, the  crackle and hiss of a walkie-talkie, the tinny voice of a dispatcher issuing  instructions from an unseeable place. He clung to the doorway, feeling as if  all the air had been knocked out of his body. Where before he'd been able to  clear the space from the front door to the sitting room in three medium-sized  steps, now it took him an eternity to cross all the way to the bedroom, with  hesitant steps that betrayed the shaking of his legs.&nbsp; </p> 
<p>She lay on the  bed, two paramedics in green uniforms standing next to her inert body. Her  blouse had been ripped open; her thin, white arms stretched wide apart like the  joints of meat in his father's butcher shop, fingers curled as if trying to  grab onto the edges of the mattress, and her face was lifted, like she was  trying to stare at something above her head, just out of reach.&nbsp; </p> 
<p>But they were not  doing anything to save her. They just stood there and murmured things to each  other, mysterious incantations that Yusuf couldn't hear. One wrote down  something on a clipboard, while the other spoke into the walkie-talkie and  cocked his head, waiting for a response. For a moment, Yusuf didn't understand  what had happened, and then, in a moment of brilliant, cold illumination, he  knew: there was nothing more to be done. It would have been of no more use than  trying to hold on to a bird escaping from a cage, the summer's last flowers, a  child growing out of his old clothes or shoes.&nbsp; </p> 
<p>He didn't  remember how he made his way out of the house, back down the stairs, onto the  street where his father had already gone inside the shop and the policewoman  was still standing guard on the corner. He pushed past the curious crowd gathered  on the sidewalk: men in skullcaps, women with scarves over their heads,  children in school uniforms admiring the flashing lights of the patrol cars and  ambulances.&nbsp; </p> 
<p>He walked and  walked; soon he was at the high street, amongst the crowds of people out  shopping for their evening meals, looking to bring things home to their  children and families. The noise they made blurred into a wall of sound; he  flinched at anyone who grazed his arm as they walked by him. The ground was a  violent ocean under his feet, the sadness a physical pain that pulled at his  chest, made his vision blurry, sent waves of nausea from his stomach up to his  throat. He felt lost and frightened, like a child who has lost sight of his  parents in a crowded room.&nbsp; </p> 
<p>Finally, he made his way back home, to a nearly empty street at that time of  evening that was neither light nor dark. The early autumn air was crisp and  cool and tinged with the scent of burning leaves. A few children were still out  playing in the lane, crying out in protest when called in by their mothers. The  houses, in their sameness, the evening lights behind net curtains outlining the  familiar shapes of families just like his sitting down to their evening meals,  seemed to whisper to him that nothing on this street would ever change.&nbsp; </p> 
<p>In fact, for one  moment, when Yusuf set his feet to climb up the stairs of his house, his mind  played a trick on him, taking him back to an earlier time, before he knew what  death felt and tasted and looked like. In this innocent incarnation, he  wondered what Mrs. Colewyn might like for her tea, and how he would tell her  about the T. S. Eliot poem they were studying in English class: The Game of  Chess, from The Waste Land. He had read the conversation the two ladies, Lil  and Lou, and wondered if that was how people had really talked in the old days;  he wanted to read it out to Mrs. Colewyn and ask her if she had known people  who talked like that, funny and old-fashioned, blunt but not unkind.&nbsp;</p> 
<p>And then it all  came back to him, in the rush of a river swollen with flood: that Mrs. Colewyn  was gone, that she had died right in front of his eyes, and that he would never  see her again. Every morning, he would wake up and have to remember and relive  it all over again, until his mind had accepted the loss, and even that would be  a death of another kind.&nbsp; </p> 
<p>It was a good  thing that his feet were so familiar with the stairs, taking him smoothly over  the cracked third step and the little bump at the landing, because his eyes  were filled with tears, so much so that his vision was blurred and the hallway  grew dark and unfathomable. But because he was far too old to sink down to the  stairs and weep like a child, the tears remained trapped in his eyes, stinging  the back of his throat, the taste of them like bitter almonds, which he  remembered that his science teacher had once told them tasted the same as  arsenic.&nbsp; </p> 
<p>--</p> 
<p>Yusuf thought it would have been a bigger struggle to go to Mrs. Colewyn's  funeral than it turned out to be in the end. He told his mother and father that  the funeral was set for Saturday morning at the Luton Crematorium - it was not  quite asking for permission, not as bold as an announcement that he was going  to go. But his mother only looked at his father with frightened eyes, and his  father pretended not to have heard anything, and went back to reading his  newspaper. Yusuf took this to mean they would not protest, nor forbid him from  going. He went back to his room, unsure of what to do with his victory.</p> 
<p>He walked to the Luton town center early on the day of the funeral; as he  passed the War Memorial, he stopped for a second to crane his neck at the names  engraved on its white column. When he was younger, he'd played a game, trying  to find familiar names -- Peter, Robert, David -- names of boys he was friends  with at school, so he could go and make fun of them the next day. As he got  older, he scanned the list looking for any Muslim names, but never found any,  which filled him with a kind of sadness that he couldn't explain to anyone  else.</p> 
<p>The funeral, arranged by the council, had been set for 8:45 am, and would  hardly last twenty minutes. He'd called to find out the details, his voice for  once not cracking or wobbling out of control. He must have sounded much, much  older to the woman at the Crematorium - twenty or twenty-five at least. Maybe  she thought he was a relative coming from London to say goodbye. He hadn't  identified himself on the phone, afraid that giving his name would make them  suspicious, think that he was coming to cause some kind of trouble.</p> 
<p>The bus was, for once, on time; Yusuf climbed aboard and settled in the back,  the floor still clean, seats not yet filled with Saturday morning shoppers or  teenagers out on an expedition to one of the theme parks nearby. He was glad  for the peace and quiet, despite the loud rumbling of the heavy diesel engine  as they left the town centre and drove slowly through the streets filled with  rows upon rows of small terraced houses. He needed time to gather his thoughts:  he'd never been to a funeral before, Muslim or Christian, and the fear of what  he would have to see was like cold fingers reaching around his ribcage and  squeezing his heart.&nbsp; </p> 
<p>He found his mind  wandering back to thoughts of school, to Mr. Fakan and the ill-fated biology  lab. The science teacher had been suspended for an indefinite period by the  school head, after several parents had called to complain about the  &quot;forced&quot; dissection. Apparently Aisha had been right about the Health  and Safety regulations, although she had been bluffing in class that day. But  Fakan was supposed to give his students the choice to opt out of the  dissection, and now he was paying for his oversight. Yusuf felt a peculiar mix  of vindication and regret walking entering the classroom to find a substitute  teacher, who'd started them on plant biology and photosynthesis, which Yusuf  had already studied the year before. He had enjoyed Fakan's classes more than  any other at school, and had been hoping to do well on his Biology GCSE's next  year. But all that was now up in the air, just like everything else in his  life. </p> 
<p>Soon Luton  Airport came into view, to the east; it was as familiar a landmark to him as  the clock tower in the town center or the fireworks at Wardown Park. All the  things he'd known, growing up and living his entire life in Luton. As he  watched a plane dipping in for a landing, he thought about how he'd never been  to Pakistan: the country that ran his life and his parents' lives, and everyone  around him. He'd never seen it. His parents had never been able to afford going  back there after they'd left, even though they talked about it every day and  told him at least a hundred times a day that some aspect of his behavior would  never have been tolerated had they been living there. He realized with a start  that he didn't even want to go there. </p> 
<p>They drove by  Stopsley Common, and Yusuf got off the bus at the corner of Butterfield Green  Road, to walk the few hundred meters to the Vale. He rested his eyes on the  peaceful farmland beneath Warden Hill, the gently undulating carpet of gold,  red, and green. The air soothed his cheeks and caressed his hair; he found his  mind slowing down, turning over his thoughts with a detached calm that felt  completely natural. There was nothing to be afraid of: he was coming to say goodbye  to an old friend, to pay his respects. Nowhere seemed more fitting for this  duty than this place, this time.&nbsp; </p> 
<p>As he walked  along the road, he remembered how Mrs. Colewyn said that mornings were her  favorite time of day, when the rest of the day stretched out before you like a  road that you could run or walk down, depending on your mood. She would have  liked the feel of this morning: a gentle amble down a peaceful country road,  the birds calling to each other with the surprised greetings of long-lost friends.&nbsp; </p> 
<p>Finally he  reached the chapel at the Vale, a tiny red-brick building surrounded by oak and  plum trees, a round bed of riotous pink, white and purple flowers in a shady  circle at the entrance. Yusuf stopped to look at them; a lone lazy marbled  white butterfly sailed from one to another with careless luxury. But instead of  their perfume, he smelled the scent of lemon cologne, that she kept on her  bureau as a memento. It lingered just beyond the edges of memory as he took a  deep breath and squared his shoulders to step inside the chapel.&nbsp; </p> 
<p>He sat down quickly in the last row, and looked around: there was nobody else  there besides the funeral director and the coffin that contained Mrs. Colewyn  at the front of the room. Soft organ music was playing over the stereo system,  a lone flower arrangement graced the coffin, a small plywood box painted to  look like walnut. It was impossible to think of God in this setting, so bland  and nondescript: a cross on the front wall the only indicator that this was a  religious place. It was impossible to think of Mrs. Colewyn in that box.&nbsp; </p> 
<p>The minutes  passed. Nobody else came into the chapel. The room was very cold; Yusuf  shivered, and then mind began to wander to his schoolwork, to his friends. He  couldn't tell any of them he'd come here. What about Aisha, though? Would she  laugh at him, or would she understand? Would she think him odd for being  friends with an old lady, one who couldn't even say what religion she was, or  who her parents were? Or would she mock him, tell the others, so they could all  laugh at him? He felt so confused and embarrassed that he had to sink his face  into his palms, and block out the light with his fingers. </p> 
<p>Then he heard  Mrs. Colewyn's voice in his ear, saying something that he had heard her say  &nbsp;at least a hundred times while she had been alive: &quot;Well, go on,  talk to her.&quot; </p> 
<p>The corners of  his mouth lifted in a half-smile at the memory. Whenever he'd had an argument  with his father or mother; whenever he'd fallen out with someone at school;  that was what Mrs. Colewyn would say. First she'd worm it out of him: she'd  glance at him with those blue eyes that missed nothing, even though they were  surrounded by layers of wrinkles that almost obscured them from view. Then  she'd bribe him with a biscuit or a cake; and finally, she'd give him a kind  look that said &quot;tell me all about it&quot; and he was off, confessing his  day's pain or confusion to her as if she was his priest. And no matter what he  told her, big or small, trivial or of all the importance in the world, she  would nod and say, &quot;Well go on, talk to her.&quot;&nbsp; </p> 
<p>No religious  lectures, like the imam at the mosque. No censure about disrespect, about how  &quot;things aren't done like that in Pakistan&quot;, the way his parents would  lash him whenever he spoke out of turn or questioned their authority. Not even  the boring droning talks of his teachers at school, who went on and on about  responsibility and hard work. Even when he'd protested that they wouldn't  understand, or you couldn't talk to his mother because she was like a brick  wall, his father was stubborn as a donkey, Mrs. Colewyn would just smile and  say, &quot;Go on, talk to them. What do you have to lose?&quot; </p> 
<p>Yusuf longed to  hear the gentle words just one more time, spend just one more hour in that  simple place, high above the street, just the two of them, the old woman who  had no people and the boy trying so hard to become a man. Life held no  complications in those hours, no identity. They were just who they were, two  people who could talk to each other, about anything and everything, and that  was more than most people ever got in a lifetime. </p> 
<p>But then the  funeral director looked at his watch, and went to a screen, where he flicked a  button on the wall. The coffin began a slow, steady slide on electric rails  towards the far side of the chapel, where Yusuf saw a panel lifting up, ready  to receive it into the depths of the crematorium. There was nothing to stop  this slide, towards adulthood, towards old age, and eventually death.&nbsp; </p> 
<p>This time, when  the tears came, Yusuf didn't swallow them down. There was nobody to see him  anyway, just a funeral director who he didn't know and would never meet again.  He bent his head and bit his lip and cried his eyes out for the best friend he  would ever have.&nbsp; </p>            </td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
</p> <p>
<?php include("../../foot.php"); ?>
</body>
</html>
