<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue8/menu_issue8.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue8/karen_thornber/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">Ecocriticism and Japanese Literature of the Avant-Garde <span class="texto2"><br>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; by <a href="../../issue8/karen_thornber/bio.php" class="link3">Karen Thornber</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           &nbsp;<br>
              <p>This  article draws from my current book project &ndash; <em>Ecoambivalence, Ecoambiguity, and Ecodegradation: Changing Environments  of East Asian and World Literatures</em> &ndash; which analyzes Chinese, Japanese, Korean, and Taiwanese literary  negotiations of anthropogenic environmental degradation in the context of world  literature on environmental problems and crises. Here I will focus on human/nonhuman  dynamics in selected works of postwar Japanese avant-garde writing, integrating  ecocritical perspectives into discussions of modern Japanese literature, and incorporating  Japanese literature into ecocritical discourses.  </p>
          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ecocriticism can be broadly defined  as &ldquo;the study of nature writing by way of <em>any</em> scholarly approach or, conversely, the scrutiny of ecological implications and  human-nature [nonhuman] relationships in <em>any </em>literary text, even texts that seem (at first glance) oblivious of the  nonhuman world.&rdquo;<a href="#_edn1" name="_ednref1" title=""><sup>1</sup></a> Examining artistic negotiations of these interactions  in modern Japanese literature not only deepens our understanding of this corpus  but also expands the field of ecocriticism.  Since its launching in the 1990s, ecocriticism has contributed greatly  to a more nuanced understanding of American and European literary constructions  of human/nonhuman contacts.  But because  anthropogenic environmental degradation is well-nigh universal, it is  imperative to study human/nonhuman relationships in other literatures, and  those from East Asia in  particular.  Despite stereotypes of East  Asian &ldquo;love of nature,&rdquo; East Asia has been  home to some of the world&rsquo;s most daunting environmental problems and  crises.  As the historian Rhoads Murphey  argues concerning Asia, &ldquo;All Asian cultures in the areas east of Afghanistan  and south of the former Soviet Union have long been noted for their admiring  attitudes toward nature . . . All of this is contrasted with the Western view .  . . The Asian record, however, makes it clear that, despite the professed  values of the literate elite, people have altered or destroyed the Asian  environment for longer and on a greater scale than anywhere else in the world,  even in the twentieth-century West.&rdquo;<a href="#_edn2" name="_ednref2" title=""><sup>2</sup></a> Moreover, the historian Mark Elvin points out  that:
            <blockquote>
Through more than three thousand years, the Chinese  refashioned China.  They cleared the forests and the original  vegetation cover, terraced its hill-slopes, and partitioned its valley floors  into fields.  They diked, dammed, and  diverted its rivers and lakes.  They  hunted or domesticated its animals and birds; or else destroyed their habitats  as a by-product of the pursuit of economic improvements.  By late-imperial times there was little that  could be called &ldquo;natural&rdquo; left untouched by this process of exploitation and  adaptation.<a href="#_edn3" name="_ednref3" title=""><sup>3</sup></a>&nbsp; </blockquote>
Discussions of textual  constructions of relationships among human beings and the nonhuman in East  Asian literatures have focused on creative depictions of &ldquo;nature&rdquo; (i.e. the  nonhuman) as a refuge, often romanticized, from human society; the use of  &ldquo;nature&rdquo; (i.e. the nonhuman) as setting, inspiration, metaphor, and symbol; and  the Japanese &ldquo;discovery&rdquo; of landscape in the late nineteenth and early  twentieth centuries.  Yet not surprising considering the region&rsquo;s long  history of environmental degradation, East Asian literatures &ndash; although often  lauded for their &ldquo;celebrations of nature&rdquo; &ndash; have in fact for thousands of years  also been addressing interfaces among human civilizations and the nonhuman that  involve human degradation of the nonhuman.   Just to clarify, I use the term &ldquo;nonhuman&rdquo; to refer to both the biotic  (that is to say, nonhuman organisms) and the abiotic (that is to say, nonliving  physical elements such as air, water, and soil).  I use the term &ldquo;human&rdquo; to refer to human  beings and to human constructions both material and intellectual, including  technology.  Without question, the human  and the nonhuman are deeply intertwined, and borders between the two are often vague.  But the extent and preventability of the  environmental transformations instigated by human bodies (human beings and  their tools and technology) make it imperative, in ecocritical discourse, to distinguish  between human and nonhuman.  <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Artistic negotiations of the more complex interactions  among the human and the nonhuman are particularly intriguing in literature of  the avant-garde.  By &ldquo;avant-garde,&rdquo; I mean  what French literature scholar Susan Suleiman calls diverse projects that  &ldquo;linked artistic experimentation and a critique of outmoded artistic practices  with an ideological critique of bourgeois thought and a desire for social  change, so that the activity of writing could also be seen as a genuine  intervention in the social, cultural, and political arena.&rdquo;<a href="#_edn4" name="_ednref4" title=""><sup>4</sup></a> In addition, as Peter B&uuml;rger has argued, the  avant-garde artist attempts to reintroduce art into the praxis of life as well  as to transform the social institution of art.<a href="#_edn5" name="_ednref5" title=""><sup>5</sup></a> In Japan, like Europe and North   America, the hallmark of avant-gardes is &ldquo;their attempt  to effect radical change and innovation <em>both</em> in the symbolic field (including what has been called the aesthetic realm) <em>and</em> in the social and political field of  everyday life.&rdquo;<a href="#_edn6" name="_ednref6" title=""><sup>6</sup></a> It also is important to recognize that &ldquo;there  is no such thing as <em>the</em> avant-garde;  there are only specific avant-garde movements, situated in a particular time  and place.&rdquo;<a href="#_edn7" name="_ednref7" title=""><sup>7</sup></a>&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Avant-garde creative works have been discussed as  clusters of rapidly changing artistic perspectives and practices that embody  the ambiguous and conflicted interactions among human beings, materials, and  contexts of production.<a href="#_edn8" name="_ednref8" title=""><sup>8</sup></a> The focus here has been anthropocentric.  But in fact, a number of literary texts that  demonstrate aesthetic innovation <em>and</em> push for social change <em>also</em> address  human relationships with the nonhuman, pressing subtly or not so subtly for  both perceptual and practical transformations of these relationships.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I am particularly concerned with Japanese avant-garde creative  works that depict extreme human/nonhuman interactions: nonhuman entities overwhelming both other  nonhuman entities and human beings; and human beings or their creations  overwhelming both human beings and the nonhuman.  The first dynamic is highlighted in Ab&eacute;  K&#333;b&#333;&rsquo;s (1924-1993) famed novel <em>Suna no  onna </em>(Woman in the Dunes, 1962), which although revealing much that is  absurd with human existence, also sheds new light on some of the paradoxes of  human/nonhuman relationships.  Literature  of the atomic bomb, including the recent anthology <em>Genbakushi 181 ninsh&#363;</em> (1945-2007) (Collection of Atomic Bomb Poems  by 181 Writers [1945-2007], 2007) edited by Nagatsu K&#333;sabur&#333;, Suzuki Hisao, and  Yamamoto Toshio, foregrounds the second dynamic.  Atomic-bomb literature&rsquo;s articulations of  human-on-human violence have received considerable attention, but this corpus&rsquo;s  exposures of human-on-nonhuman violence are also significant.  Like most avant-garde writing, both <em>Woman in the Dunes </em>and <em>Collection of Atomic Bomb Poems </em>propose  radical change and innovation in the symbolic, artistic, social, and political  fields.  But these works &ndash; the former  implicitly and the latter explicitly &ndash; also call for change and innovation in  how human beings think about and interact with the nonhuman. &nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ab&eacute;&rsquo;s <em>Woman in the Dunes</em>, one of Japan&rsquo;s best  known avant-garde novels, introduces  Niki Junpei, a teacher and amateur entomologist who one August afternoon  travels to a remote section of Japan&rsquo;s  seacoast to look for insects.  Walking across  a desolate and increasingly sandy landscape, Niki finds himself in an  impoverished village where many houses are below sand level, some by  more than twenty meters: &ldquo;Before long,  all the houses seemed to be built in hollows dug out of the slope of the  sand.  The slope of the sand became  higher than the rooftops.  Each row of  houses sank deeper into the sand hollows.   The slope [of the road] suddenly got steeper.  It must have been at least twenty meters to  the roofs of the houses.  What kind of  life did they lead down there?&rdquo;<a href="#_edn9" name="_ednref9" title=""><sup>9</sup></a> Niki soon learns more than he had bargained  for about this village.  An elderly  resident arranges for him to spend the night at the home of a local widow,  located at the bottom of a sandpit; the following morning he discovers that the  ladder to the top of her sand hollow has been removed and that he has been imprisoned in  the dunes.  The remainder of the novel  consists of Niki&rsquo;s experiences in the hollow &ndash; his unsuccessful attempts at  escaping, the Sisyphean battle against sand that threatens to bury him alive,  his tumultuous relationship with the woman of the dunes, and his crow trap turned  water supply, which in the end gives him so much hope for the future  that he does not take advantage of the long-awaited rope ladder when it is  lowered into his hole.  The body of the  novel concludes: &ldquo;There was no need to  escape quickly.  On the round-trip ticket  he now held, destination and place of return were blanks for him to fill . . .  He might as well postpone his escape&rdquo;(144).   Seven years later, we are told, Niki has still not returned home. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong>A sensation since its  publication, translated into several dozen languages and adapted into a  prize-winning surrealistic film by Teshigahara Hiroshi (1927-2001) in 1964, <em>Woman in the Dunes </em>has garnered  considerable critical attention both in Japan and  abroad.  Niki has been discussed as &ldquo;the  very personification of the alienation of modern life,&rdquo;<a href="#_edn10" name="_ednref10" title=""><sup>10</sup></a> as a man who, &ldquo;recognizing that loneliness and impatience are nothing more than  confusion and ignorance, anticipates finally being able to stand at the  beginning of a new pathway of human relations&rdquo;<a href="#_edn11" name="_ednref11" title=""><sup>11</sup></a>;  the village he encounters has been interpreted as &ldquo;a critique of the fate  of the traditional rural village in modern, urban, capitalist Japan,&rdquo;<a href="#_edn12" name="_ednref12" title=""><sup>12</sup></a> the sand dunes as signifying the &ldquo;wasteland&rdquo; of twentieth-century Japan,<a href="#_edn13" name="_ednref13" title=""><sup>13</sup></a> and the novel itself as forcing the reader &ldquo;into an acute self-awareness of the  absurdity of the human condition.&rdquo;<a href="#_edn14" name="_ednref14" title=""><sup>14</sup></a>&nbsp;&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; And these assessments, explicitly promoted by passages in <em>Woman in the Dunes</em>, are  well-founded.  Even before  arriving in the dunes, Niki had likened the world and his students to sand,  noting, &ldquo;I brought up the example of sand [with my students] &hellip;&hellip;because  ultimately isn&rsquo;t the world like sand?&rdquo; (61).  In  addition, Niki&rsquo;s obsession with insects is interpreted by colleagues and  strangers as: 
<blockquote>
Proof  of mental flaws.  Even in children,  unusual fancy for insect collecting often indicates an Oedipus complex.  Children compensate for their unsatisfied  desires by eagerly sticking pins into the dead bodies of insects that they  never need fear will escape.  And not  giving this up once they become adults is a clear sign that the condition has  worsened.  So it is no accident that  entomologists often have a great appetite for possessions and that they are  extremely reclusive, kleptomaniacs, and gay.   So from this point it is but a step to pessimism and suicide . . .  Actually, that the man had never confided his hobby to anyone itself seemed to  prove that he was aware that there was something funny about it (7-8).<a href="#_edn15" name="_ednref15" title=""><sup>15</sup></a> </blockquote>
But the narrator  immediately debunks these assumptions, claiming them groundless because Niki&rsquo;s  body was never found.  Even more  significantly, he follows his comment that the authorities pronounced Niki dead  seven years after he went missing with a lengthy narrative on a Niki still very  much alive: the remainder of the novel &ndash; which tells Niki&rsquo;s story from his  appearance at &ldquo;S [train] station&rdquo; near the dunes to his decision to stay in the  dunes &ndash; partially discredits the authorities, and by extension the speculators.  Not all is metaphor.  Indeed, a closer look at the novel reveals much  at play concerning human interactions with the nonhuman.  What if instead of completely metaphorizing  the sand, and reading Niki&rsquo;s and the villagers&rsquo; struggles with the sand and  with each other only as symbolizing the absurdities of twentieth-century  existence, we also analyze the sand as emblematic of one aspect of the nonhuman? Encouraging such a reading are the novel&rsquo;s  many passages concerning the physical properties of sand &ndash; including the  diameter of its grains, its formation, its endless movement, as well as its  destructive properties.  Understanding  the sand as emblematic of one aspect of the nonhuman allows  not only for a more comprehensive appreciation of Ab&eacute;&rsquo;s novel, but also a better understanding  of human/nonhuman dynamics and possibilities. &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; On the one hand, <em>Woman  in the Dunes </em>depicts the nonhuman as completely overwhelming the human; in  this novel human beings are caught in a thankless struggle against a vicious nonhuman that  can be restrained only by ceaseless physical labor.  Niki speaks abstractly about the necessity of  adapting, the importance of moving with, rather than fighting against the  dunes: he wonders, &ldquo;Certainly, sand was  not suitable for existence.  Yet was a  fixed state utterly indispensable? . . . If we were to quit this fixed  existence and to give ourselves up to the fluidity of the sand, competition  would come to an end&rdquo; (13).  He even  hallucinates about moving with the flow.   But he quickly discovers that although possible, human survival is  precarious in this environment; struggles are many and comforts few.  And Niki observes that this has been true for  generations; the same sand currents that threaten his new home also destroyed  and devoured prosperous cities and great empires: &ldquo;The ancient cities, whose immobility not a  soul had doubted&hellip;&hellip;could not overcome the law of the flowing 1/8 mm. diameter  sand&rdquo; (29).  The sands also damage much  of the nonhuman.  As the narrator  remarks, &ldquo;The sands never rested.   Quietly, but reliably, they assaulted and destroyed the surface of the  earth&rdquo; (13).  Flies are one of the few  species able to survive such conditions:  &ldquo;they were okay even in environments where other insects could not live,  places like deserts, where all other living things perished&rdquo; (11).<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; But  on the other hand, <em>Woman in the Dunes </em>does  not depict human beings as completely helpless vis-&agrave;-vis all nonhuman bodies.  To be sure, Ab&eacute;&rsquo;s novel &ndash; in  sharp contrast with Nagatsu&rsquo;s <em>Collection  of Atomic Bomb Poems &ndash; </em>does not portray significant human abuse of the  nonhuman.  But several metaphors and  similes used to illustrate similarities between human beings and nonhuman  animals suggest parallels between the impact of sand on most everything it  encounters and the human impact on parts of the nonhuman.  Particularly pertinent in this regard is the  narrator&rsquo;s claim that, imprisoned in the dunes, Niki was &ldquo;an animal that finally realizes the gap in the  fence through which it was trying to escape in fact is nothing more than the  entrance to its cage&hellip;&hellip;a fish that, after striking its snout how many times,  finally sees that the glass of the goldfish bowl is a wall it cannot penetrate&rdquo;  (76).  The powerful metaphor of the  nonhuman animal caged by human beings draws attention to human confinement,  even mistreatment, not only of human beings but also of nonhuman animals. <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In  addition, Niki appears to take human mistreatment of nonhuman animals as a right,  and one of which he actively avails himself.   After all, he has enjoyed sticking pins into insects since childhood;  his aim in going to the dunes is to discover and bring back to the city a new  species that will grant him everlasting fame.   Moreover, although he compares his initial experiences in the dunes with  those of a beetle or mouse that has been lured to an inhospitable environment,  he quickly reassures himself that because he is not an animal, the village  leaders and their minions cannot force him to work.  But of course they do, just as they have  forced so many others.  Somewhat more  ironically, after binding and gagging the woman, Niki declares, &ldquo;I am a human  being and you can&rsquo;t simply chain me like a dog&rdquo; (65).  Yet he treats this woman like the very  nonhuman animal he declares he is not.  The  most obvious commentary here is on human-on-human abuse: the village leaders abuse Niki and the  villagers, and Niki abuses the woman in the dunes.  Just as the sand overwhelms most everything  in its path, powerful human beings, or at least those enjoying relatively more  strategic positions, overwhelm human beings in positions of lesser power.  <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; But  focusing exclusively on intra-human relationships, as does most scholarship on <em>Woman in the Dunes</em>, diverts attention  from the novel&rsquo;s references to human mistreatment of the nonhuman.  Most noteworthy in this regard is the novel&rsquo;s  brief yet suggestive discourse on flies.   As mentioned above, flies are depicted as remarkably adaptable, the only  organisms capable of surviving truly unforgiving desert environments (11).  But as invincible as they are vis-&agrave;-vis the  sand, they are to some extent at the mercy of human beings, some of whom imprison  if not kill them.  In fact, metaphorizing  Niki&rsquo;s incarceration in the dunes, the narrator comments that, frustrated that  he cannot leave his new prison to purchase his own cigarettes and sak&eacute;, Niki &ldquo;was  a big black fly that had believed it was assiduously flying, but that in fact  was simply rubbing its snout against the window pane&rdquo; (72). Human beings can be more threatening to insects  than are the dunes.  To be sure, Ab&eacute;&rsquo;s narrative  does not vigorously pursue this dynamic.   There is no explicit environmental message here, at least not in any  conventional sense.  In fact, the novel  concludes with Niki discovering, via his accidental pump, how to work with,  rather than against, the dunes (the nonhuman).   Yet this move too is ambiguous: Niki  has unearthed a relatively simple means of extracting water from the sand, but  taking advantage of this finding necessitates continuing, rather than  abandoning (as he originally had planned), his endless shoveling (i.e.  displacing) of the sand.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <em>Woman in the Dunes </em>opens space for reconceptualizing  relationships between human beings and the nonhuman.  By invoking human imprisonment and even destruction  of the nonhuman, the very discourse that highlights human abuse of the human in  fact calls attention to human abuse of both.   The sand &ndash; at once demonstrating the potential destructiveness of the  nonhuman (when read more literally) and the potential destructiveness of the  human (when read more figuratively) &ndash; complicates matters.  Its presence points to the destructiveness,  the endurance, and the vulnerability of both human beings and the nonhuman.  And it is these ambiguities that infiltrate, intervene,  and complicate political, social, and cultural behaviors.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
Like Ab&eacute; K&#333;b&#333;&rsquo;s novel <em>Woman in the Dunes</em>, Nagatsu K&#333;sabur&#333;&rsquo;s  edited <em>Collection of Atomic Bomb Poems </em>depicts  extreme human/nonhuman interfaces.  But  while <em>Woman in the Dunes </em>highlights a  nonhuman entity overwhelming and destroying both other nonhuman entities and  human beings, Nagatsu&rsquo;s <em>Collection of  Atomic Bomb Poems </em>reveals the devastating afterlives of the August 1945 nuclear  bombings of Hiroshima and Nagasaki.  Two of the most blatant examples of enacted  human desire, these bombings stand out from other atrocities not in terms of  numbers of people killed or square miles destroyed; more people were killed and  more square miles destroyed in the firebombings of Tokyo and other major  Japanese cities during the Second World War than in the attacks on Hiroshima  and Nagasaki.  Rather, as the first  tactical deployment of nuclear weapons, the strikes on these two targets revealed  more than anything the fragility of existence, demonstrating just how easily  people could annihilate both one another and the nonhuman.  More than six decades later, policy  specialists and activists continue to debate the future of nuclear weapons in the  face of persistent proliferation and ominous threats of use.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Japanese literature of the atomic bomb &ndash; a socially and  politically engaged corpus that rarely adheres to conventional literary forms  and often is extremely fragmented &ndash; is  an understudied segment of the Japanese avant-garde.  Its most obvious focus is the high human cost  of the bombings, both in their immediate aftermath and in following decades;  many texts expose the long-term consequences of exposure to radiation, which  invaded and indiscriminately damaged those human bodies it did not annihilate  outright.  Much literature of the atomic  bomb explicitly condemns continued nuclear proliferation, as well as the  world&rsquo;s growing dependence on nuclear power, because of the dangers such  activities pose to the future of human societies; the condition of the nonhuman  is depicted as a concern only if it threatens human beings.  But a number of creative texts, including  selections in Nagatsu&rsquo;s <em>Collection of  Atomic Bomb Poems</em>, also portray damage to the biotic and abiotic nonhuman as  itself deplorable.  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nagatsu&rsquo;s anthology features poems on the atomic bombings  and their aftermaths by 181 writers, most of whom are Japanese, produced in the  six decades following the attacks on Hiroshima and Nagasaki; it  also includes a handful of essays on topics similar to those addressed in the  poems.  This collection involves some of Japan&rsquo;s most  celebrated writers of the atomic bomb, including T&#333;ge Sankichi (1917-1953),  Kurihara Sadako (1912-2005), and Hara Tamiki (1905-1951), as well as a number  of lesser known writers; many poems were previously published elsewhere, but  some, solicited for this collection, appear here for the first time.  Poets are identified by their dates, places  of birth and residence, and principal publications; survivors and those who  visited Hiroshima/Nagasaki shortly after the bombings and were exposed to radiation  are recognized as such.  The anthology is  divided into six sections: poems written  between 1945 and 1959,   a section each for poems of the 1960s, 1970s,  1980s, and 1990s, and a final section of poems written after the turn of the  twenty-first century.  Interestingly,  this last section contains by far the most poets and poems; in fact, the total  numbers of twenty-first century poems and poets both exceed those of all the  other sections combined, pointing to increasing anxiety over Japan and the world&rsquo;s  future under the nuclear shadow, or at least to an effort to publish new  writing on nuclear concerns.  <br>
<em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Collection of Atomic Bomb Poems</em> offers  diverse typologies of human/nonhuman interactions.  As with most literature of the atomic bomb, the  anthology&rsquo;s principal focus is human suffering caused by the anthropogenically  affected nonhuman, particularly irradiated air, water, and soil, as well as irradiated  nonhuman organisms.  For instance  Kurihara Sunao&rsquo;s (1953&ndash;) straightforward &ldquo;Bakuhatsu wa m&#333; owatta&rdquo; (The  Explosion Is already Finished) reads simply: &ldquo;Irradiated/ air/ Irradiated/  water/ Irradiated/ milk/ Plentiful/ even in spinach . . ./ Popeye/ Cannot move/  Because he ate irradiated spinach . . ./ Every day/ Children drink 400 cc.&rsquo;s/  of irradiated/ milk./ I&rsquo;ve been drinking it for seven days now/ When/ will we  die?&rdquo;<a href="#_edn16" name="_ednref16" title=""><sup>16</sup></a> The explosion itself is &ldquo;over&rdquo; but the  poisons unleashed in this explosion still threaten human beings.  In contrast, a handful of poems focus on the  impact of the bombings on the nonhuman, while a number call attention to the  destruction of both the human and the nonhuman.   Most intriguing, however, are those selections that reveal the  paradoxical implications of seemingly unaffected or recovered nonhuman bodies (e.g.  freshly sprouting greenery): several  poems suggest that the greener the city, the more human and nonhuman  devastation is concealed, and the greater the potential for relaxed vigilance  and further destruction of both.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A handful of poems in <em>Collection of Atomic Bomb Poems </em>focus  primarily on nonhuman devastation.  For  instance, while Kat&#333; Sh&#333;&rsquo;s (1953&ndash;) &ldquo;Mururoa no shiroi nami&rdquo; (White Waves of the  Mururoa Atoll) describes the people of the Samoa and Cook   Islands as &ldquo;trembling in the sea and sky,&rdquo; it portrays  the biotic and abiotic nonhuman as severely damaged.  The poem speaks of &ldquo;corpses of thousands, no  tens of thousands of fish&rdquo; floating in the waters of the South Pacific and of a  loudly weeping ocean &ldquo;ruined by nuclear pollution&rdquo; (173).<a href="#_edn17" name="_ednref17" title=""><sup>17</sup></a> Similarly, Shimomura Kazuko&rsquo;s (1932&ndash;) poem  &ldquo;Bik&#333;&rdquo; (Faint Smell) reminds the reader that the bodies of human beings were  not the only bodies destroyed by the atomic blasts.  The poem begins, &ldquo;The atomic bomb that people  made didn&rsquo;t kill just people.  It also  killed trees/ The old camphor trees at Kokutaiji, natural treasures, were  blasted, and flattened at their roots&rdquo; (125).   Ibuse Masuji (1898-1993) likewise refers to the fate of the camphor  trees in <em>Kuroi ame </em>(Black Rain,  1965), Japan&rsquo;s most  famous novel of the atomic bomb: &ldquo;The camphor trees were said to be more than  one thousand years old, but today they had been brought to an end.&rdquo;<a href="#_edn18" name="_ednref18" title=""><sup>18</sup></a>&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Other poems in <em>Collection of Atomic Bomb Poems </em>focus on  the joint struggle of human beings and the nonhuman in the wake of the atomic  bombings.  While Nagase Kiyoko&rsquo;s  (1906-1995) &ldquo;Metsub&#333; kid&#333;&rdquo; (Orbit of Destruction) merges references to human with  those to nonhuman suffering, Makabe Jin&rsquo;s (1907-1984) &ldquo;Midori osanaku&rdquo; (Young  Green) moves from nonhuman to human suffering, and Kim Suson&rsquo;s (1939&ndash;) &ldquo;Kuroi  tsume (Hachigatsu muika ik&#333;: Hiroshima wa <em>Hiroshima </em>ni natta)&rdquo; (Black Nails [After August 6: Hiroshima became <em>Hiroshima</em>]) from human to nonhuman  suffering.  
<blockquote>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nagase writes in &ldquo;Orbit of Destruction&rdquo;:<br>
&nbsp;<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The earth became a victim . . .<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Beautiful bodies . . . into lumps<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Even surprised people into rags and rubbish. . .<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Since that time ashes minute like pollen<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; have been lightly wafting in space.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The fluttering of the poison is silently, silently  drawing the curtain on the<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; stratosphere.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In the middle of the purple green out in the open sea<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; voiceless plankton writhe in agony,<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; and they gradually flow over here . . . </p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Should our distress go unheard by people<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Like the distress of the plankton?<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Our mingled screams sucked into the whirlpool (36).  </blockquote>
              People and plankton here  are both in agony, but their screams risk going unheard.  <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Makabe Jin&rsquo;s &ldquo;Young Green,&rdquo; on the other hand, moves from  nonhuman to human suffering.  Although  the poem ties the latter closely with the former, the significance of damage to  the nonhuman transcends its impact on human beings. &ldquo;Young Green&rdquo; begins with observations on the condition  of the nonhuman in Hiroshima a  decade after the bombing, contrasting the material prosperity of the city with  its besieged vegetation; the poet, then turning primarily to human struggles, vows  to repair, and to prevent, what damage he can:
  <blockquote>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Did you see?<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; the prosperity of the city of deltas after ten years? . .  . &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Did you see?<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; that Hiroshima&rsquo;s  green is young?<br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Did you see that the earth does not nurture green and that the green<br>  
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;&nbsp;still does not cover the earth<br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Did you see the injured trees of Mt. Hiji? . . . </p>
            <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You probably saw.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The summer flowers of Hiroshima, red  crepe myrtle and oleanders.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; They look destitute, pale, like lost seasons,<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Trembling in the distress of the decayed earth.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Come back, come back, life of flowers!<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; My screamed desire is useless . . . </p>
            <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When poison has passed into the sky, into the ground,<br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; and the body is a living ruin that at any moment could melt  like thin ice<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; can we believe,<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; that the world is not a ruin? . . . </p>
            <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I will block the cloud, the ashes, the black rain,<br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; and the invitation to destruction<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; with the scab made by the fires.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; With this skin, I will testify to the merchants of death<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; so that no one will lose again<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; what I have lost (48-49).</blockquote>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Kim Suson&rsquo;s &ldquo;Black Nails&rdquo; moves in the opposite  direction, the poet focusing for most of the text on the extreme human  suffering that resulted from the atomic bombings, suffering experienced by both  Japanese and their colonial Korean subjects. But he ultimately acknowledges that this  suffering transcends the human:&nbsp; &nbsp;&nbsp;
  <blockquote>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Colonial Korea <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Forcibly taken away&nbsp;&nbsp;&nbsp;&nbsp;  atom-bombed<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Resentments piling up twofold, threefold<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Return home<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; newborns have a high count of white blood cells<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; and are left lying without treatment</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thanks to radiation,<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; there are people sprouting black nails<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; that grow longer and longer,&nbsp; curl up, and become strings.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I knit the strings into a hat . . .<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The hat looked like the earth.</p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; I <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; go to apologize to the earth (181-182).</blockquote>
              Concerned not just with  human suffering, &ldquo;White Waves of the Mururoa Atoll,&rdquo; &ldquo;Faint Smell,&rdquo; &ldquo;Orbit of  Destruction,&rdquo; &ldquo;Young Green,&rdquo; and &ldquo;Black Nails&rdquo; employ varying artistic  strategies to call attention to the devastation the atomic bombs have wreaked  on the nonhuman.  Unlike the majority of creative  writing on the atomic bombs, these poems depict damage to the nonhuman not only  as negatively impacting human beings, but also as something to be lamented, and  prevented, for its own sake.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Most  interesting, however, are those poems that call attention to the paradoxes  inherent in (apparent) recovery of the nonhuman.  As Chris Pearson notes in <em>Scarred Landscapes: War and Nature in Vichy  France</em>, the nonhuman can just as easily conceal as reveal atrocities: &ldquo;The  natural environment is not a reliable preserver of memory.  As well as being oblivious to human concerns  to remember the past, nature is an active force with the ability to cover up,  change or challenge sites of historical significance.&rdquo;<a href="#_edn19" name="_ednref19" title=""><sup>19</sup></a> For instance, as the poet asks in Makabe Jin&rsquo;s  &ldquo;Young Green&rdquo;:&nbsp; &ldquo;You likely saw./ The  seven rivers that run so clearly/ reflecting the image of every butterfly,  missing not a one,/ flowing into the ebbing tide of the sea./ Where do they  harbor the afterimages of the bloody river, the valley of corpses?&rdquo;(49).  Other poems in <em>Collection of Atomic Bomb Poems</em> suggest that although a (re)flourishing  nonhuman can give hope to people in despair, it also can camouflage very real  damage.  In so doing it can give people  near and far implicit license to continue their battles without deeper  consideration of the disparate consequences of their actions. The sentiments of a Japanese principal shortly  after World War II concerning the rapid recovery of some nonhuman species,  cited in Isakawa Masomi&rsquo;s (1930&ndash;) &ldquo;Kosumosu no hana&rdquo; (Cosmos Flower), echo  numerous voices in postwar Hiroshima and Nagasaki; ultimately, however, the recovery  (human and nonhuman) of the bombed city is linked to the failure to prevent the  outbreak of war in other sites:&nbsp; 
              <blockquote>
              For ten  years even grass won&rsquo;t grow at the epicenter of the blast<br>
              Despite  rumors like this<br>
              already  by autumn weeds had sprouted from the rubble<br>
              In a  corner of the desolate ruined school building<br>
              I saw a  cosmos flower . . . <br>
              All  right, [I thought], I&rsquo;ve somehow got to quickly rent a school building&nbsp; <br>
              and  start up classes again . . .<br>
              It&rsquo;s  already been thirty years [since that speech]<br>
              Hiroshima has  been remarkably restored<br>
              but  there always is a war going on, somewhere in the world (72). </blockquote>
              Seeing a blooming flower  a decade before he thought he would inspires the principal to resume educating  the city&rsquo;s children.  But the final lines  reveal the paradoxes and suggest potential unintended consequences of rapid  recovery: thirty years after the blast,  and in fact long before that, the city looks nearly &ldquo;normal.&rdquo; And so, it is implied, outsiders have little  incentive to resolve their own conflicts peacefully.<br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Nakaoka  Jun&rsquo;ichi&rsquo;s (1937&ndash;) &ldquo;Midori ga shitatari&rdquo; (Green Trickles) addresses this conundrum  more directly.  The poet criticizes the  makeshift measures to control radioactive waste that were implemented at Chernobyl  following its 1986 nuclear power-plant disaster.  He then remarks: &ldquo;The dripping green of &lsquo;Beautiful Japan&rsquo;/  Completely conceals this danger-filled scene&rdquo; (227).  &ldquo;Green Trickles&rdquo; reveals how by covering up  the past, the recovered landscape almost invites continued abuse, both of its  own and more distant bodies. &nbsp;&nbsp;Nakaoka&rsquo;s  reference to &ldquo;Beautiful Japan&rdquo; (<em>utsukushii  Nihon</em>) also mocks the Japanese writer Kawabata Yasunari&rsquo;s (1899-1972) Nobel  Prize acceptance speech &ldquo;Utsukushii Nihon no watakushi&rdquo; (Myself of  Beautiful Japan, 1968) and anticipates the irony both of former Japanese Prime Minister  Abe Shinz&#333;'s (1954&ndash;) remarks, upon assuming office in 2006, concerning Japan&rsquo;s  &ldquo;beautiful natural environment,&rdquo; and of the recent poetry anthology <em>Genbaku shish&#363; &ndash; hachigatsu </em>(Collection  of Atomic Bomb Poems, August, 2008), which juxtaposes poems on the horrors of  the atomic bombings with color photographs of a thriving nonhuman.<a href="#_edn20" name="_ednref20" title=""><sup>20</sup></a> The &ldquo;dripping green&rdquo; of many landscapes, both  physical and textual, conceals anthropogenic abuse and destruction of both  human beings and the nonhuman.  <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The full extent of the impacts of enacted human desires  on human beings and the nonhuman likely will never be known.  But one of the great challenges for  twenty-first century scholars is to attain a deeper understanding of  human/nonhuman interactions across time and space, including how societies have  perceived and constructed these interactions, an understanding without which we  will not be able to alleviate the pressing problems, much less crises, that  have faced both human beings and the nonhuman for generations and that are  becoming increasingly acute.  As I show  in <em>Ecoambivalence, Ecoambiguity, and Ecodegradation</em>,  literature provides few explicit solutions.   In fact, it often raises more questions than it answers.  But this is perhaps precisely the point.  Literature&rsquo;s deep engagement with the many  paradoxes of the experienced world, as well as with the diverse and often  conflicting scientific, social scientific, and humanistic narratives of this  world, offers multiple perspectives on human/nonhuman interactions, perspectives  that are vital to transforming consciousness, understanding, and ultimately  behavior. &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
            <div>
              <div id="edn1">
                <p><a href="#_ednref1" name="_edn1" title="">1. </a> Scott Slovic, <em>Going Away to Think: Engagement, Retreat,  and Ecocritical Responsibility </em>(Reno: University of Nevada Press, 2008), p. 27.</p>
              </div>
              <div id="edn2">
                <p><a href="#_ednref2" name="_edn2" title="">2. </a> Rhoads Murphey, &ldquo;Asian  Perspectives of and Behavior toward the Natural Environment,&rdquo; in <em>Landscapes and Communities on the </em><em>Pacific Rim</em><em>: Cultural  Perspectives from </em><em>Asia</em><em> to the </em><em>Pacific   Northwest</em>,ed. Karen K.  Gaul and Jackie Hiltz (Armonk, NY: M. E. Sharpe, 2000),  p. 36.  </p>
              </div>
              <div id="edn3">
                <p><a href="#_ednref3" name="_edn3" title="">3. </a> Mark  Elvin, <em>The Retreat of the Elephants: An  Environmental History of </em><em>China</em>(New    Haven: Yale University Press,  2004), p. 321.</p>
              </div>
              <div id="edn4">
                <p><a href="#_ednref4" name="_edn4" title="">4. </a> Susan Rubin Suleiman, <em>Subversive Intent: Gender, Politics, and the  Avant-Garde </em>(Cambridge: Harvard University Press, 1990), p. 12. </p>
              </div>
              <div id="edn5">
                <p><a href="#_ednref5" name="_edn5" title="">5. </a>Peter  B&uuml;rger, <em>Theory of the Avant-Garde</em> (Minneapolis: University of Minnesota Press, 1984), pp. 56-57. </p>
              </div>
              <div id="edn6">
                <p><a href="#_ednref6" name="_edn6" title="">6. </a> Suleiman, p. xv.</p>
              </div>
              <div id="edn7">
                <p><a href="#_ednref7" name="_edn7" title="">7. </a> Suleiman, p. 18. </p>
              </div>
              <div id="edn8">
                <p><a href="#_ednref8" name="_edn8" title="">8. </a> Tyrus Miller, <em>Singular Examples: Artistic Politics and the  Neo-Avant-Garde </em>(Evanston: Northwestern  University Press, 2009), p. 3.</p>
              </div>
              <div id="edn9">
                <p><a href="#_ednref9" name="_edn9" title="">9. </a> Abe  K&#333;b&#333;, <em>Suna no onna, </em>in <em>Abe K&#333;b&#333; zensh&#363; </em>6 (Tokyo: Shinch&#333;sha, 1972), p. 10. </p>
              </div>
              <div id="edn10">
                <p><a href="#_ednref10" name="_edn10" title="">10. </a> David  Pollack, <em>Reading</em><em> <u>against</u> Culture: Ideology and Narrative in the Japanese Novel </em>(Ithaca: Cornell University Press, 1992), p. 128.</p>
              </div>
              <div id="edn11">
                <p><a href="#_ednref11" name="_edn11" title="">11. </a> Sasaki  Kiichi, &ldquo;G&#363;wa ni shika kokuji dekinai:  Ningen kankei no atarashii katachi,&rdquo; in <em>Abe K&#333;b&#333; zensakuhin</em> 6 (Tokyo:  Shinch&#333;sha, 1972), p. 3.</p>
              </div>
              <div id="edn12">
                <p><a href="#_ednref12" name="_edn12" title="">12. </a> Pollack, p. 128.</p>
              </div>
              <div id="edn13">
                <p><a href="#_ednref13" name="_edn13" title="">13. </a> Susan  J. Napier, <em>Escape from the Wasteland:  Romanticism and Realism in the Fiction of Mishima Yukio and &#332;e Kenzabur&#333;</em> (Cambridge: Harvard University, Council on East Asian Studies, 1991), p. 13.</p>
              </div>
              <div id="edn14">
                <p><a href="#_ednref14" name="_edn14" title="">14. </a> J.  Thomas Rimer, <em>A Reader&rsquo;s Guide to  Japanese Literature: From the Eighth Century to the Present </em>(New York:  Kodansha International, 1988), p. 179.</p>
              </div>
              <div id="edn15">
                <p><a href="#_ednref15" name="_edn15" title="">15. </a> Much  scholarship on <em>Woman in the Dunes </em>addresses  Niki&rsquo;s interest in insects, but for the most part reads this connection  symbolically (as indicating, for instance, an obsession with details), rather  than as pointing to human/nonhuman interactions.  </p>
              </div>
              <div id="edn16">
                <p><a href="#_ednref16" name="_edn16" title="">16. </a> Nagatsu  K&#333;sabur&#333;, Suzuki Hisao, Yamamoto Toshio, eds., <em>Genbakushi 181 ninsh&#363;, 1945-2007 </em>(Tokyo: K&#333;ru  Sakkusha, 2007), pp. 190-91.</p>
              </div>
              <div id="edn17">
                <p><a href="#_ednref17" name="_edn17" title="">17. </a> The  Mururoa Atoll was only one of several sites where France  conducted nuclear tests from the 1960s through the 1990s.</p>
              </div>
              <div id="edn18">
                <p><a href="#_ednref18" name="_edn18" title="">18. </a> Ibuse  Masuji, <em>Kuroi ame, </em>in <em>Ibuse Masuji zensh&#363; </em>5(Tokyo: Chikuma Shob&#333;, 1975), p. 97.</p>
              </div>
              <div id="edn19">
                <p><a href="#_ednref19" name="_edn19" title="">19. </a> Chris  Pearson, <em>Scarred Landscapes: War and  Nature in </em><em>Vichy</em><em> France</em> (New    York: Palgrave Macmillan, 2008), p. 168.</p>
              </div>
              <div id="edn20">
                <p><a href="#_ednref20" name="_edn20" title="">20. </a> This anthology is divided into three parts: children&rsquo;s poems  on the atomic bombings, poems on the atomic bombings, and poems calling for  peace; the three parts are separated by several pages of background on the  bombing of Hiroshima, that of Nagasaki, and subsequent nuclear  testing and the antinuclear movement, respectively.  Interestingly, most of the poems are  accompanied by color photographs, almost all of which depict a thriving  nonhuman.  In contrast, the collection  contains only six photos of atomic ruin, all of which are in black and white;  these photographs are separated from the poems and appear in three sets of  facing pages: a burnt watch, a  schoolgirl&rsquo;s summer dress, human bone buried in melted tile, a student&rsquo;s  jacket, a second watch, and a cluster of half-melted bottles.  Sakai Izumi, ed., <em>Genbaku shish&#363; &ndash; hachigatsu </em>(Tokyo: G&#333;d&#333; Shuppan, 2008),  pp. 13-14, 42-43, 88-89.</p>
              </div>
          </div>            <P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
