<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue8/menu_issue8.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue8/edie_meidav/artwork.html','','width=600,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="292" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">Brown Ice <span class="texto2">by <a href="../../issue8/edie_meidav/bio.php" class="link3">Edie Meidav</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The ice thick around the branches,  beauty foretelling damage. Deceptive, because the cold doesn&rsquo;t bother needling  anyone&rsquo;s bones, not yet, it will sneak in at night. They all know the exact  timing of the storm, between six at night and four the next afternoon, eighteen  inches expected, roads impassable, lines down for days. They love the clarity,  the need to heed dire warnings, the gossip they exchange as late-night shoppers  for milk and eggs at one of the town&rsquo;s two markets. <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Once the storm hits and stops, finally, they will  take account, exhale by crowding to the diner to trade tales of plugged  plumbing, candlelit nights, unheated houses, sump pumps gone awry, flooded  basements and body scent; or will head to the school gym to glower at those who  gloat, who don&rsquo;t wait for the single shower, the people whose power stayed,  because once your power goes, life becomes dismal and the town takes forever to  get on the case. Even those whose power  stands strong against the weight of ice on electrical lines will go to the  diner just so disaster won&rsquo;t leave them alone. 
</div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2"><p>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Knowing a storm is coming, anyway, is different than  surviving.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Not just that a storm can knock down  power lines, it&rsquo;s that downed lines can set houses on fire, leave a widow with  five kids destitute, trap people in ice: these are the known stories. In a  house off the main road, the painter finishing his canvas pays not a jot of  attention to the storm, and not because his power usually stays and not because  his construction work made him finally give in and buy a generator he had  installed at his studio. And not because true tragedies happen infrequently. <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  He ignores because at most the whole thing is an  inconvenience. So you sleep in until they make the roads safe: big deal. You  still get to do what you want. He has never been the kind to shoulder up to  other people with a kind of hard-luck buddy zeal, never wanted to bond in  weakness, thinking, as he had explained to his new bride, that the idea of need  poisoned love.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  When he&rsquo;d been young, his father had cursed him many  times over, saying he was too damned independent and ornery for his own good,  and that one day he&rsquo;d learn that he&rsquo;d have to let someone else in. Well, more  or less he had followed his father&rsquo;s admonition, had let people in, and look  where it had left him.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Getting the exact shade of yellows in  a brown right. Because he is trying to finish up the last painting in a series  of brown on browns when the call comes in but still does his mightiest to  ignore it. There is a girlfriend, as there has long been, going on a  half-century at this point, this a girlfriend of many years, short-haired and  peppy, with dark glasses; this being the one for whom he ostensibly left his  wife Jo two weeks ago, because he just couldn&rsquo;t quit having a girlfriend,  having tried three times but probably full-on addicted. <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   Truth is that he doesn&rsquo;t know if it is the  girlfriend or the thrill of taboo. Harems, Mormons, bonobos &ndash; no argument he  ever martialed would have changed his wife&rsquo;s rage, practically forced to give  him marching orders and change the locks. At the same time, he cannot help  finding her rage resplendent. She is right. He had thought it kosher, as she  said, to bed the mother of one of their daughter&rsquo;s friends, someone in their  small community, someone who used to work in the convenience store down the  road, not even prettier, just a few years younger and unsaddled by kids.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; He cannot get the brown to adhere  correctly; figure has just swallowed ground; what did Mirandi know that he  doesn&rsquo;t? The tinny answering machine voice calls out, something about the party  tonight, a fancy affair at a neighbor&rsquo;s house, catered, a benefit for a  politician, he can see it already, the champagne handed you before you get your  coat off by college students who slum by aping an elegance their young lives  keep them from knowing. <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  If elegance depends on omission -- as one of his old  painting teachers used to say, the kind of teacher who used to sell a pint of  blood in order to buy tubes of paint, back before money hit the art world and  sprayed green over everything -- if it depends on omission, these kids have  suffered from the phenomenon of too much: too many parents involved, too many  yeses, excuses, dollar bills stuffed into pockets at airport departures. <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   Not that life is supposed to be hard. Those to be  patted down really should be these waiter kids; at least their parents or the  friends of their parents; but instead he, a humble carpenter not pretending to  any wisdom, not pretending to be anyone&rsquo;s latterday Jesus of the paint, is  supposed to go hear subtle pitches slide snakelike into his ears from people  doing better than he is, people who have glammed themselves just to shake you  down the better, with the fare-thee-well being the contributions you are meant  to leave in discreet envelopes in a wicker basket by the door, below a vanilla  candle on steroids. <br>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    This is not his world, he wants no part. And anyway,  what is he supposed to do, endure everyone&rsquo;s grins? They are all giant apes in  a cage, grimacing, picking fleas off. Only two weeks ago he left Jo, which  means he has already survived two weeks of seeing all shades of evil apery, the  way people love being polite to his face, knives dripping with honey just to  feel all the more righteous joy in later gossip, the gossip serving to define  the herd. Who understands the point of such gatherings? He can&rsquo;t help thinking  what his wife would call it. <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   In the last few days he has made the decision to  stop trying to excise her from his mind because how are you supposed to strip  someone from the neural layers when you share too much history, and he can&rsquo;t  really do anything about the way his heart has become like a crowded ship,  planks creaking, supporting the weight of her and his girlfriend and whatever  other exes he tries to forget. <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  You just have to submit sometimes, carry them all  inside you, there&rsquo;s no throwing a person overboard or cutting the strings. And  he knows his wife will be the hardest, not just the years they&rsquo;ve tripped  through but that she happens to be a person pungent from the first hello, what  with her 1950s stoop accent, the one she could never quit, the one in which she  mouths all her big words. In that accent she would have sized up the point of  this shake-down party and its evil gloaters by calling it <em>Schadenfreude, </em>only  having to tell him the first time that this means the sad-happiness of those  who like to see others fallen, because Briggs is one to never forget anything  that might make a difference to his idea of happiness.<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   He doesn&rsquo;t want their definitions, their sad  happiness, he is nobody&rsquo;s fallen guy. And so what if his girlfriend lacks much  accent beyond politics? Pungent in her own right, she bothers having a life  outside her concerns which is more than most people do and he has to respect  that. In their best moments, lying in bed in a moment stolen from whatever  grand ledger of morality someone somewhere inscribes with an invisible pen, his  girlfriend likes to get dreamy and compare the two lovers in grand terms, just as if  they were revolutionaries who could change the world, as if everyone were still  some narrow-ribbed twenty: he with his art, she with her politics so  relentlessly local. Though she never got to telling him what this big change  they could make would be, it is still a dreamy prospect. <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   Now that he thinks of it, such moments probably  don&rsquo;t happen so much anymore, moments from back when they used to shell out for  the hotel across the river, for muted greens and grays of drapery light on her  skin waiting for him, for he way she&rsquo;d laugh each time, saying: now tell me  we&rsquo;re not a clich&eacute;.<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   We&rsquo;re not, he&rsquo;d say, settling in to lie beside her,  his paint clothes still on as if he was Pygmalion finally getting his model.<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   And now she has started to be a bit too available. <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   Listing the good things about her: you would never  feel sorry for her, especially because she plays none of the strings of pity  his wife favors. Just look&nbsp; &ndash; he imagines  telling his father this, father underground for years breathing maggots, having  given up on bullying loyalty into Briggs right before some awful last breaths &ndash; just  look, she's practically a stoic! She earned her adultery rightfully! Her  two early marriages had made her endure enough miscarriages  before she&rsquo;d decided to just check out of the whole marriage-and-kids bag. <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   And because she noted injustices while clerking at  the town hall, her activist thing started, turning her at first into a quiet  rabble-rouser, activating or whatever you call it against this developer or  that bad idea for youth programming, and then it became part of who she is,  someone who makes the best of bad situations, being a non-complainer capable of  performing small magic everywhere, in bed and elsewhere, her pluck  breathtaking, her origins never far from her own memory, daughter of a highway  waitress who had gone cuckoo before abandoning her to a truck-driver father so  that she still suffers from some kind of post-traumatic disorder, shivering if  she gets so much as a paper cut. And still she had risen above. You should  admire her grit, he imagines shouting at his father, his father who, if he&rsquo;d  met his girlfriend -- but he&rsquo;d died at 61, only a few years older than Briggs is now -- would have harumphed and gone back to listening to loud news  radio, smoking up his devil-may-care storm.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  If Briggs ends up at the party, probably required by  his recent bold move, he will endure small talk. When what does anyone expect?  What is he supposed to do, answer back? Tell them that none of this would have  happened if Jo hadn&rsquo;t forced him into her bourgeois idea of life? His  particular parcel of genes had not been born for this. You only had to look at  his dad, preaching about loyalty from the safety of being someone whose wife  had died right after Briggs&rsquo; birth, his father with the halo of all his  discreet perfumed ladies never brought into the family circle. <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Clearly, Briggs had hardly been born to enter his ex-wife Jo&rsquo;s  idea of normal. <br>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    But he was a pleaser, and because of that, she had  ignored whatever he&rsquo;d been born for; easy to ignore too that he&rsquo;d never  suggested marriage to anyone, not a big house on acreage needing constant maintenance,  leaf-raking and snow-blowing and cutback, not even his daughter Mel, though of  course he wouldn&rsquo;t begrudge the best thing in his life, bar none. <br>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    And okay, so last year he had gotten desperate one  night, and had thought of drinking turpentine in his studio just to leave both  Mel and Jo the fifty thousand life policy his dad had taken out on him years  ago, but tipping the can, he hadn&rsquo;t forgotten Mel, not her huge brown eyes  peeking out under the head of ginger curls, how she could be so preternaturally  knowing within such unbruised white skin &ndash; the way she expected the best from everyone &ndash; and  if he could paint that, he&rsquo;d have been a millionaire five times over, the way that such a vision could keep someone from glugging down certain brain death. <br>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    A daughter could give a person reason to live, and  then a person has to live up to that kind of reason. Plus Mel is twelve, that  second before confusion hits hard, before all crazy ideas adults invented for  her were ready to set into her head like flies; he has to keep life steady if  just for her. <br>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;     So he can&rsquo;t go to the party and say any of this to  the honeyed knifers, out to slice up his choices. Because no one cares. Their  goal is mainly to feel smug about their own choices, the slicing of Briggs  being just another way to gather twigs for their own shelter.<br>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    Back when he had met the woman who would become his  wife, when Jo had just about pranced into the ski shop where he worked whenever  carpentry jobs slowed, he had mostly known who he was, just another local  roustabout, Briggs who loved to paint, secretly nourishing ideas of being a  bad-boy success in the big city, Briggs who could defy even his father&rsquo;s odds  against him, Briggs the bohemian painter with eyes too close and blue, as one  songwriter ex-girlfriend had sung through booze at him and also to her  miniscule audience at the town club. Briggs being just another Vermont bad boy, a boy good on skis  and with girls, having slid through school on charm and defiance, excellent at  making his teachers question their low judgment of his work. He had grown into  being Briggs, tall Briggs with calloused hands, someone who could run a line or  make apple wine, Briggs who would do any work to support his art habit,  secretly always thinking he was better than. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   Any smart-thinking city girl should have been able  to tell this guy was no one to link up with, but Jo had ignored the signs, spun  her high-ho urban version of a lariat, her appeal just enough to catch him in a  trap; and when the lariat had turned out to be a wooden engagement ring, that  was his joke, and he had liked the way she&rsquo;d laughed as he&rsquo;d struggled to fit  the wood ring on the wrong finger, the fuck-you finger. When later he had to  produce a real diamond ring, only then the idea started to dawn that maybe he&rsquo;d  found himself in a noose. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   And part of her appeal was that she was from the  city. He didn&rsquo;t like admitting it, but it was as if he&rsquo;d conquered the art  world by dragging a city girl, as she joked on the phone to a girlfriend, by her hair  to his caveman lair. To make up for all of that, he ribbed her in bed and out,  and if she ever got finicky about following his taste in all things, he&rsquo;d bust  her chops even more and call her my spoiled city girl.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Because back when they first moved in together,  before their date at City Hall, he thought he knew city girls, when really he  had no clue about the demands of the species. He used to see them get out of  their rental cars in black-cloaked clumps, a north-seeking gaggle of  peg-leggers with cleavage wrong for winter, as if winter were just something  you could toss around your neck like a scarf to abandon at will, women who had  come with mates to peep at leaves or snow or whatever people thought they  needed to  peep at just so they could run to the most overpriced  place in town to buy mementos and maple syrup in tins they&rsquo;d never reuse, doing  it all before Vermont soothed the up-and-down out of them, before they dared  nighttime driving just to rush back to the city with its all-night bodegas and  life support: what you get in the country is death support, and the people who  choose country life learn to stand up to death in a more stalwart way because  you always have to prep for the big one.<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  There was also that other kind, the  couples Briggs used to see driving up from the city, so unlike country people,  because the country either bonded people so together they couldn&rsquo;t look at each  other, both bearing snow shovels in grim tandem or it just tore them apart. But  then you had these inexplicably companionable city couples showing up, usually  older, sitting at the diner reading the paper, walking either  talkative or silent, a hand on the other&rsquo;s elbow because someone had a  knee that had failed. And these were the kinds who really turned his head,  making Briggs marvel: you could almost taste their respect, the way they bought  each other delicacies in the local market, happy because they had accomplished  some kind of feat against odds. They actually got along. They had overlooked  each others&rsquo; differences enough to make something work.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; So that Jo&rsquo;s car had broken down right before one of  the bigger storms in decades, well, call it luck, good or bad. And that fate  made her break down right in front of the ski shop, after they had already  sighted each other a few days earlier, broken down right after he had closed early  to head out to batten down his own pre-storm hatches &ndash; at first he had thought  she was fooling, the way she didn&rsquo;t even know how to pronounce carburetor. But  he helped, much as he could, scarcely enough to get an iced-up car going, his  talent in this department consisting of lots of blowing on his fingers while  she sat inside the car smiling back, both of them recognizing that they had stumbled into a  moment, and he promised there was no mechanic in town who wasn&rsquo;t going to say  call me in the morning, and because of the season, all hotels in town would be  full already, so it didn&rsquo;t take a genius to invite her in to stay the night on  the guest cot in front of the fire, and only a little brandy to get out the  story, that Jo wasn&rsquo;t just any city girl, being a school psychologist,  psychology the only field he would have gone into other than art, the only one  he respected other than, say, zoology or botany; and talking to her that night  with the silence of the storm wrapped so heavy around them, the ominous silence  broken only by the creak and snap of falling branches, exciting beyond words,  he found something in her accent that made him nostalgic for a past that could  not have been his, being from some fallen-to-the-side Mayflower line, knowing  nothing about sitting on stoops and playing stickball and shouting out to  neighborhood boys about matzo-ball soup or cannelloni or whatever people like  Jo might shout, some pastiche he knew from the movies, something you couldn't pinpoint too much, just liking the weirdness of her heap of curly  ginger hair and the accent that could slip someone up like a herring and the  way she confessed herself to be a total louse on skis and yet there she had  been on a solo venture, coming in to the shop, a single woman in her thirties  up in the backwoods of Vermont, seeming both older and younger, ill-equipped  for any storm, coming because she had self-diagnosed a need for adventure,  making it all inevitable that night that Briggs and the storm would become part  of her package. Only this: he hadn&rsquo;t known what a consumer a city girl could be, could  never have guessed how great might be her hunger to eat him whole.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Another call coming in: a couple of hours before the  storm was due to hit. Two storms ago he&rsquo;d relented by getting the generator;  the apartment was on town water; he had a pellet stove. I&rsquo;ll be okay, he says  loudly to no one, hand smeared brown, turning the volume way down on his  answering machine. Standing back from the painting, he sees more ochre should  be brought in, that ochre could make the naples yellow pop. The party would  be canceled and he&rsquo;d be better off. Who ever thought it a good idea to bother  communing with a bunch of people who form no one&rsquo;s idea of a community? He  would know all of them, because most people know him, Briggs that decent  carpenter who painted on the side, friendly but elusive but the guy to call if  you&rsquo;re trying to build something to last through the winters, plus he kept his  cost reasonable -- but for whatever repute he has and despite the way Jo always  tried dragging him to this concert or this benefit, he has managed to stay a  lone wolf. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   Having a kid helps you remember there are other  humans, Jo used to like telling him, one of five hundred coded accusations of  selfishness she used against him. She loved him best when he moved beyond himself and did  something like make an omelette for everyone or shopped for more than one roll  of toilet paper, all proof he remembered there were others in his sphere.<br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; And it was true he&rsquo;d had other girlfriends who sang  the same words, whatever their melodies. Some had called him arrogant or unfit  for human company or yelled at him -- find some other woman who&rsquo;ll put up with  you, but Jo hadn&rsquo;t given up, not for a long time, she had a savior complex and  had made him her cause, saying she saw most relationships as being like that  between two  rocks in a tumbler, saying the two of them could smooth out their rough edges:  all in her accent that could have been cut directly from broken Coney Island  glass.<br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Now another call comes in, someone really trying to  reach him. <br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  He turns up the volume to hear Jo&rsquo;s accent of the  stoops making it through: &ldquo;Briggs, don&rsquo;t mean to be a pest, just trying again,  maybe you can&rsquo;t hear, but our electricity is down and if I weren&rsquo;t scared about  Melanie, you know how she gets, no heat and all. And I&rsquo;d stay at Martha&rsquo;s but  she&rsquo;s gone, so say no if you need but just wondering if you think we could stay  at your place just the night?&rdquo;<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    His hand goes warm on the phone a crucial second  before picking up. Of course Jo is not surprised at the screening; her voice  goes flat, businesslike, as if she were the kind of woman who could find comfort in anything,  a low-maintenance woman who would think it  just fine if he answered in the  negative. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &ldquo;You sure it won&rsquo;t be a problem,&rdquo; she repeats  herself.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   The words voice him. &ldquo;Come on over. I hear there&rsquo;s  black ice.&rdquo; <br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; So now he has painted himself into a corner, has to  pick up the phone and swallow hard to cancel on his girlfriend. It will take wife  and daughter twenty minutes, give or take, even despite what a bad driver Jo is  in snow, a person not meant for country life, determined to give their  daughter permanence by staying in the backwoods, even if she always said women  prefer the bustle of the marketplace while men prefer the cave. That whole  package of her with her salty opinions and their solemn daughter is coming over  too soon and at his urging. He could have suggested she go somewhere else; he could have spoken her dialect and said something like <em>I have a  need for us to be in a different place before we start sharing a habitat in any  form even if it is out of necessity, </em>all that psychological parlance so  easy to mimic; but his tongue had swollen, he couldn&rsquo;t even speak a parody. His  self-understanding tends to have a slow backburner quantity, and this had been  their problem, that he couldn&rsquo;t stop being a pleaser, knows what people like,  all of which partly explains  why he is among the last still  making a living off carpentry in a boom-and-bust tourist town, and also why the  only way he found to really silence his city-girl wife was to have affairs  with this local woman and that one. If he hadn&rsquo;t been such a pleaser, way back he  could have just said no to marriage and the house and whatever banal package Jo  had sold him. <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    But she may as well be deaf; she never heard the  strangulated cry of the affairs, the call of a boy in a ditch rimmed with motel  lights, his dialect the charges on a credit card; because for all her  psychologist training she had to be one of the world&rsquo;s worst listeners and the only  person whom he'd trusted enough to say this to was that crazy bearded guy  Moyers who used to live in his studio, then in the apartment across the lot,  until finally Moyers left town on some half-baked entrepreneurial scheme, which was basically a  transparent cover over a misguided attempt to get his own ex back. <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   The problem with Jo, he&rsquo;d tell Moyers, is that she  has gotten too used to railroading everyone into following her wishes. If she  listened better &ndash; and he would never finish, never say  <em>I wouldn&rsquo;t have  had the affairs.</em> Moyers was companionable enough, didn&rsquo;t need any finished  sentences, would bump the beer can against his, grunt with brute  male sympathy.<br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Briggs&rsquo; fault, all of it -- and with guilt lumping  in his throat, now he calls his girlfriend, hoping for a machine and this time  in luck; she is probably on her way home, laden with pamphlets. &ldquo;Look, well,  that party&rsquo;s probably canceled anyway, right?&rdquo; he says, trying to sound tired  rather than hopped up on  speedballs of adrenaline. &ldquo;Going to call it an early  night but how about we catch up tomorrow?&rdquo;<br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  He thinks he should make Jo and Mel some minute  rice, eating being one way of keeping from people being too hostile, so starts  up a pot, only burning it once  he tries tidying up the bathroom. He meant to  give Jo one less thing to roll her eyes about, but before he can fix the   rice question the two are already knocking, standing at his door like  evangelists whose mission flickers, their god temporarily cloaked,  Jo not meeting his gaze, looking down at her own feet stamping on the welcome  mat she had given him the first day he had rented his studio. <br>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &ldquo;I tried calling ,&rdquo; she says, &ldquo;but &ndash;&rdquo;<br>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &ldquo;It&rsquo;s okay, I heard.&rdquo;<br>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      Melanie has already entered; during the fourteen  days of their separation, she has stepped foot into her dad&rsquo;s lair only for  eight hours, almost an entire day before beating a retreat back to her mom&rsquo;s  comforts, a real house with dishwasher and dryer. <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    After the initial waver, Jo enters, masking her own  discomfort with the tread of a real-estate broker, as if she were no one&rsquo;s  soon-to-be-ex-wife but rather a disinterested professional surveying mildew on   sills. Never mind that the last time they talked she had been twisting the  sleeve on his shirt as if she wanted to break his arm, bringing him close to  her to keep him from running, saying all she needed in her high tight way which  for the first time ever  almost stripped  the soot from her accent. He had hung  his head, understanding what that meant for the first time as well, just  letting blows rain upon his neck: his revenge lay in thinking that she had never  been good at apology, always expecting him to be the first.<br>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &ldquo;The truth is,&rdquo; she had said. &ldquo;You like the chase.  You and your slut will go sour. She betrayed me, trust me, she&rsquo;ll betray you.&rdquo;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; By this she chooses to ignore the idea that he has  been seeing his little slut for at least seven years. Seven years: the cells in  the body renew themselves every seven years, and hence the itch; a person has  to reencounter a new person. Of course Jo is right; he likes the chase; he  needs space; he loves novelty; hates the idea of mating in captivity; thinks  monogamy another bourgeois invention; has never been able to sleep touching a  person all night, had never met the girl or woman who could give him the exact  right amount of space. You cannot cut the books to fit the bookshelf, you have  to cut the bookshelf to fit the books, he always tells clients, while Jo had  tried to cut him to some prefab size with no relation to the wide-open range   needed by his breed.<br>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; And that Melanie takes after her father in this way  &ndash; a girl  loves her private time -- makes him tender, as if she were who he  might have been, soft and aware, had his father not been fist-happy, the cudgel  of those fists what Briggs had worked  to avoid most of his early life. <br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As Jo and Briggs talk, Mel does what she likes,  already having staked a hideout in the small room off the studio which he  called the living room. To her credit, about the affair that Jo had not kept  secret, Mel has shown no  acrimony, even though she knows who the  girlfriend is. The only flicker in her face makes it seem that her low  expectation of humanity has been fulfilled by her father&rsquo;s lapse, but she had  left after a few hours with him with no apology but with childish prerogative,  Mel delicate in her love of long showers and certain pillows: certainly she  would never have survived Briggs&rsquo; father. <br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  You have to love a daughter as deep and slow-talking  as Mel: you also have to worry about how she will survive adolescence. Back  when she&rsquo;d been younger, her favorite thing had been to sing loudly to herself  from the corners of rooms. Sometimes she helped him by handing him tools in his  woodshop so they could design a chair together; her huge playroom, one of Jo&rsquo;s  idea of necessities, quickly filled with all the animal chairs father and  daughter had built; and though both parents found her so companionable,  humorous, knowing, their daughter to be a girl easily disappointed in the slights  of others, one who gives up  quickly on people; she only ever had a couple  playmates come enjoy tea parties on those chairs.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;I could use a drink,&rdquo; Jo says after  her quick survey, though he hadn&rsquo;t asked.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;There&rsquo;s beer?&rdquo; He shrugs, trying not  to notice how she might as well be seeing through him, staring hard, eyes  glittering green and wide in the bare kitchenette, still the same eyes that  could make a person want to get behind them. That and Jo&rsquo;s secret little smile,  her sharp chin, all of it her arsenal, so that even when he has been angry at  her, he still wants to to find a sweet spot, wants her to soften. He leans  down hard on the butcher block nicked and stained by whatever other tenants had  cut before him. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;I&rsquo;ll take whatever you&rsquo;re offering.&rdquo;  She sits down too quickly in the white bean bag that had been left in the  studio. &ldquo;So long as it&rsquo;s not rock salt.&rdquo; This the tiniest gesture of  conciliation, a reference to an early pratfall from courtship. &ldquo;Your view&rsquo;s  nice here,&rdquo; she said. He isn&rsquo;t sure what she&rsquo;s talking about &ndash; all she could see  would be blackness, the black stretched down to the lake.  He has never let her in to his studio, preferring to  keep the expanse of snow in winter, down to the frozen lake, his own, in this  way selfish too: he has kept the special summer lavender that grows here away  from the fairy fancies of his daughter. This being the point he stuck to, that  he had to have his own place to make his art. Jo and Mel could know where it  was but for all those years they had never visited. Now they see it and he gets strangled up inside, watching them note the paintings  stacked in corners, some dusty, many left to finish, paintings that could get  sold and end up complementing someone&rsquo;s d&eacute;cor, some vacationer wanting to fix  up a timeshare; or paintings that could end up in storage, in the basement of  the one local gallery that had taken him on as a not quite lost cause. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; For a season, once, he had once kept a  log of his arguments with Jo, all about nothing. They all had the same  impossible question behind them. On her side, she was basically always asking  whether or not there would ever be enough flowing her way? Enough money, enough  love, enough worship, enough enough. And on his part he was always asking,  behind everything, am I doing it wrong? And this was their rut, her enoughness  colliding with his wrongness. So he had taken away her enough, while she had  dedicated herself to letting him know how wrong he could be. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In the next room, Melanie coolly  thumbs through videos and books left behind by the guy who used to live here,  Moyers being a bearded backwoods artifact who stuffed bearheads and collected  artifacts of the Indian variety. Before Moyers had left town, he had moved one  building over and it was during this epoch that he and Briggs would have   beery heart-to-hearts. Back in the days they&rsquo;d been neighbors, Moyers had  always lain in wait for Briggs, ready to give him advice, to pal around, to  dissipate everyone&rsquo;s birthright with small talk: Briggs had learned eventually  to take the back entry to his studio until Moyers moved away and the apartment  had been empty for at least a year.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;You have plans for the night?&rdquo; his  wife asks, questions pulsing behind her tone. One question might be, for one,  when either of them is supposed to go see a lawyer. Her tone told him that the  menu for tonight means they are putting all the bad stuff on hold, this is what her tone  declares, that they will be polite strangers with each other, just as if he  didn&rsquo;t know exactly the ripe scent of her neck under all that&nbsp; hair.&nbsp;&nbsp;   Her nails are stubby; she looks so tired and unkempt, not herself at all.<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;No big plans. Or I’m sure they'll be canceled.&rdquo; Come  to think of it, he doesn&rsquo;t know why he went so automatic in canceling the  outing with his girlfriend. It would have been more natural to have sucked it  up, to have gone to the honey knifers to be patted down, all of them  congratulating themselves on shouldering together despite the storm. Much  easier for everyone if Briggs had loaned his wife and daughter the studio so she could peek  through his nudes and studies of brown while he went to stay with his  girlfriend who also lived where power had never blown, at least not in anyone&rsquo;s  memory. <br>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &ldquo;Something I&rsquo;d rather not be at,&rdquo; he says, and she  looks at him surprised, the idea of <em>something</em> drifting uncomfortably over their heads when a knock comes at the door. <br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Their glance at each other is quick and sharp,  twelve years of marital habit dying hard, because he is guilty even as the  knock unites them. Who would be coming now? Surely not his girlfriend who was  so gung-ho about her event that she&rsquo;d be the last to show up at his door?<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; But of all people: Moyers the old tenant,  standing there stamping his feet, some story about ice and how he had been  passing through town to check out some old accounts but was no computer user  and his AM radio had been stolen out of his old Ford and so he&rsquo;d been clueless  about the weather, not like him at all, he used to be a ham radio operator who  could tell you weather patterns east of the Rockies day or night, it just goes  to show how stressed modern life is -- only in town had he gotten wind of the  double blizzard due to hit. &ldquo;You heard, eighteen inches predicted?&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;A double blizzard?&rdquo; Briggs&rsquo; daughter  leans by the darkened entry, tall and solemn, a beautiful pale light watching  her father. No one in town doesn&rsquo;t feel sorry for Moyers, or at least used to,  the guy a basket case caught in the past, holding out for some story about how  his girl had left and he&rsquo;d lost contact with his two sons, but still checked up  on the boys in a daily way, how one son had gone into the Navy while the other  was finishing up his GED, how they&rsquo;d gone to stay with her folks in West  Virginia and soon as his tour operator business took up &ndash; his latest venture  has something to do with promoting pack rides on llamas at yet another  desperate family farm &ndash; Moyers would have enough money to get himself a place  down in West Virginia, not that he loves it down there, but he&rsquo;d have some link  with his boys, because he didn&rsquo;t change poopy diapers and help out during the  worst howlers of nights just to lose contact at age 41, give or take.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Now Moyers is saying something about a  car starter, saying he wished he were better with these newfangled Japanese  machines. &ldquo;It&rsquo;s coming down fast too,&rdquo; he says, eyes hungry on the woman he  probably thinks is Briggs&rsquo; wife. Moyers is immune from gossip; when he had  evidently surrendered his apartment he had surrendered being of the town.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Briggs walked to the front window and  looked down. &ldquo;Too fast for us to go fussing with any car. Even if it is  American,&rdquo; this last a small joke at Moyers&rsquo; expense, because everyone within  ten feet of Moyers knows he&rsquo;s a Vietnam vet who would live and die  on the idea of why it is important to beat the Japanese by only using a thing if  it is made in America. <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The invitation sits heavy in the air, pressing down  on all of them so no one can breathe, for a second, then another, but Briggs  wants to be the one to voice it, otherwise his wife will beat him to it, she  the saint of lost causes, always trying to bring some teenage mom in, she the  first to hand random apples or kids&rsquo; snacks to beggars at freeway on-ramps, a  trait she&rsquo;d gotten from her own father, one Briggs both grudgingly respected  and loathed because it failed to recognize who really belonged to the tribe and  deserved charity and who was out. &ldquo;Hey, you could stay here. It&rsquo;s supposed to  stop by the morning.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; His wife startles but Moyers looks  around with real appreciation. &ldquo;You don&rsquo;t even have a bed.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;I have blankets. And the generator.  Got it installed. We&rsquo;ll be okay.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;I got someone supposed to call in  about my sons,&rdquo; he says. &ldquo;Can I give them your number here?&rdquo;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Why not,&rdquo; says Briggs, expansive --  let in the whole world, surprise Jo, let her think him a new man, why not?<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   Moyers makes his call, hunched over the phone as if  he were a substance addict arranging pick-up and then returns. &ldquo;My boys don&rsquo;t  know it but I got their back.&rdquo; Big smile at Mel. &ldquo;That&rsquo;s how fathers are. I  always got to know how they&rsquo;re doing. Call me Santa.&rdquo; <br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  And only Melanie, this is how well Jo has raised  her, half-smiles back at Moyers, who is determined to explain. <br>
  &ldquo;Someone&rsquo;s going to call here tonight and let me  know. A friend of mine in town. Cause I can&rsquo;t sleep without knowing what they&rsquo;re up to.  Sounds crazy but you never stop being someone&rsquo;s old man, right? You folks know  that.&rdquo;<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This would be their night then; Jo and Briggs  sidling around each other, taking turns serving Moyers soup &ndash; his appetite  prodigious and legendary while Melanie pretends to lose herself in Moyers&rsquo; old  books, polite whenever Moyers tries commenting on their various virtues. &ldquo;Now  that one, that&rsquo;ll tell you anything you ever wanted to know about bears in the Adirondacks,&rdquo; he says, &ldquo;different than  up here. Up here we got real bears. Down there, those bears are wusses.&rdquo;<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When it comes to the sleeping  situation, none of them make any bones about it: no one wants to be far from  the big fire. They are like kids settling down for the night, near one another,  as cozy as a sleepover, Briggs does what he can not to notice the way Jo is so  discreet, heading to the bathroom to borrow his sink, returning looking sleepy  and rumpled, huggable. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; It is as they are hunkering down, on  random throw cushions that Moyers and Melanie had left for them, side by side,  a married couple lying down for the first time, that Briggs&rsquo; hand wants to find  Jo&rsquo;s, pulling back before gripping it, her coolness in his as if he needs to  remind the hand of its basic humanity. &ldquo;This was a crazy idea,&rdquo; he says,  daring. All of it a dare. He is not telling himself what he wants. She is used  to his apologies and could recognize this as just one more. She  could go smart-ass and city girl on him,  throw up his hand, use one of her  diagnostic manual words on him. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   To her credit she does not. She just holds his hand  gently as if it were a specimen from another era. Does not squeeze back, does  nothing to encourage him. But still, she does not pull away. 
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Moyers lets out a deep rumble of appreciation on her  other side. It is as if Briggs has somewhere in his eyes a map out of difficult  snow country, as if he squinted, the solution could appear before them. Jo is  not going to give in so easily. He could try hooking her now, could try telling  her other stories from their past, but he will be more subtle.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; She could forgive. It is not  impossible. This is one of the stations on the map.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;We could leave here, you know,&rdquo; he  says, surprising even himself.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;There&rsquo;s a storm,&rdquo; and then she  understands.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;The city. Or somewhere else. You  could teach me stickball.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Don&rsquo;t try to charm.&rdquo; She pulls her  hand away.<br>
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &ldquo;I&rsquo;m not.&rdquo; He is. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   &ldquo;I don&rsquo;t know what you&rsquo;re talking about.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Now that he started, he won&rsquo;t give up  easily. &ldquo;Melanie could walk to school with a big group of kids.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;You&rsquo;ve got to be kidding,&rdquo; but she is  studying his face in the flicker of firelight. &ldquo;Don&rsquo;t you think that&rsquo;s too  easy?&rdquo; she says finally. &ldquo;What happens to you and the chase?&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Maybe the city would cure it.&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;That&rsquo;s a cognitive error. You think  geography is ever a cure?&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Why not?&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;And when it fails?&rdquo;<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &ldquo;Not when, if. It won&rsquo;t.&rdquo;<br>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       And it is as he takes her hand again, with Moyers  shifting in his sleep, mumbling something about the teeth on an animal, how  they grip, that he thinks maybe he has sealed a better future on a dare, that  he had always been opposed to the city, to its grays and crowds, but that these  colors could become his. His father might have been right: he could surrender  ice just like that. &ldquo;You won&rsquo;t know how good it could get,&rdquo; his dad had said  enigmatically, not long before he passed. <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; When years later Briggs will be walking to the  corner park holding the small butter-warm hand of Melanie&rsquo;s little toddler, a  curious, happy boy Melanie and her man had in a quirk decided to call Moyers in  honor of the stranger now dead at least a decade, the odd man who had united  Mel&rsquo;s family in some late-in-life unexpected boon of happiness &ndash; <br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    -- the moment comes back to him, the way Moyers had  talked animals in his sleep, his passion never enough to ever win over sons or  a wife but which nonetheless had leaked out like some kind of radioactive  blessing, charging up everyone with the determination to do something right  by  at least an idea of love. <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   And only the next morning, Moyers complimenting them  on how well he had slept, best sleep in years, that he notices how discreetly  Briggs had made no big deal about unhooking the phone. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  &ldquo;Hey that was smart,&rdquo; guffaws Moyers. &ldquo;What's bigger than that, hey? What's bigger?&rdquo; And to Jo's quizzical look, Moyers says: &ldquo;Nothing. You got it so no one could reach us. So all we had was ourselves, who says the world needs to be bigger than that?&rdquo; And it sounds credible, the pipe dream of people  together in a lost night, their trio plus the daughter entering the ranks of  those pouring maple syrup onto fluffy pancakes, a river of syrup uniting the  whole state, might as well be a union with the whole country, all the awake people  in window seats in front of drapery showing the sharp shadow of trees etched  like a fate you could make one crucial step to avoid.</p>
          <P><P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
