<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue9/menu_issue9.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue9/filippakopoulou/artwork.html','','width=570,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="292" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">Foreign in our own country<a href="#_edn1" name="_ednref1" title=""><sup>1</sup></a> <span class="texto2">by <a href="../../issue9/filippakopoulou/bio.php" class="link3">Maria Filippakopoulou</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           
              <p>&nbsp;</p>
          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <br>
            <p>Initially, what attracted me to <em>Black Light</em>, the  collection of<em> Poems in Memory of George Seferis</em>, in the bilingual  English and Greek edition that introduced me to  the work of Richard Berengarten,<a href="#_edn2" name="_ednref2" title=""><sup>2</sup></a> was, I suppose, what would attract any literary  academic to a work rich in dealings with foreign cultures and poetries. This  was a work which clearly entered into conversation  with canons and people from outwith its own native traditions, a work growing  by ceding its voice to that of others, from other places and times. Its ability  to acknowledge the poetic fruits of other sensibilities without cancelling them  out by appropriating them would be appealing to any student of literature,  especially this particular one, trained in literary translation and criticism,  keen on types of writing that surpass the national. A bilingual myself in Greek  and English, with French as my third language, academically primed to read  national literature through the lenses of its influence on or reception by  others, I eventually came to focus on translation as the means by which to best  explore and understand literature and poetry. I was particularly interested in  this collection because it seemed to be a prime  example of translation as creation, thriving in reflections of individual  affinities, and perceptions of each interlocutor&rsquo;s origins.</p>
            <p>In the context of Berengarten&rsquo;s oeuvre,<em> Black Light</em> was all the more intriguing for me not only because it was written in honour of  Greek poet laureate George Seferis, but also because it carried its own  afterlife in its translation by Ilias Layios and Nasos Vayenas &ndash; who by the very act of translating these poems were  themselves honouring both Berengarten and Seferis. This bilingual edition&rsquo;s main metaphor, <em>translation</em>, facilitated by the  ease of comparing versions on facing pages<strong>, </strong>made the entire project  endlessly fascinating. This<strong> </strong>book<strong> </strong>was,  surely, a striking record of a self-perpetuating  pleasure drawn from the poetry of the Other, a pleasure  so uncontainable that it had to go back to the original source of attraction  and address it, producing ripples and reflections in constantly changing  combinations.</p>
            <p>The writing of this present essay, from note-taking for  it, to further readings of it, and thence to alternate and/or cancelled drafts,  occurred between two deaths<a href="#_edn3" name="_ednref3" title=""><sup>3</sup></a> and the birth of my daughter. Death and birth, when  they concern you and your (extended) family, put you  irrevocably, and at one stroke, in the ranks of the grown-ups &ndash; ranks which until then you might have felt free to  join or leave at will. No matter how oblique or imperfect, the slant these  events gave to my reading of Berengarten&rsquo;s poetry was  inescapable. By that time, I had to admit to myself that  the largely unanticipated emotion that it burnt into me had more to do with  loss than with the celebratory effects of its tapestry of poetic voices. <em>Both</em> the theme of loss <em>and</em> the concomitant  elegiac motif are part of the core of <em>Black Light </em>itself, since the  thrust and intention of Berengarten&rsquo;s book  constitute memorial homage to Seferis.<a href="#_edn4" name="_ednref4" title=""><sup>4</sup></a><strong> </strong></p>
            <p>Admittedly, the excitement generated in this edition of <em>Black Light</em> for a  bilingual reader<em>, </em>by the multifaceted encounter with its facing  presences in both languages, gains body with every reading through its textual  layering. This effect results not only from the accumulated work of the men  who, in retrospect, can clearly be seen to have played a part in the making of  this volume &ndash; that is,  Berengarten and his Greek translators Layios and Vayenas; and Seferis and his  English translators Edmund Keeley and Philip Sherrard &ndash; but also the source of both Seferis&rsquo; and Berengarten&rsquo;s  attraction, the &lsquo;black light&rsquo; itself:</p>
            <blockquote>
              <p>[&hellip;] if the original of this book is not [only] Seferis&rsquo; poem  &lsquo;Kichli&rsquo; [Thrush], but the black light of the Greek landscape, whose experience  is shared with equal exaltation and dread by all those men [&hellip;], then it is an  original and originating/generative experience, fractured in the poetic  testimonies carried forth by all the texts, and textual fragments quoted,  glimpsed at, translated, back-translated, or glossed in this book: namely  prefaces, explicit and implicit quotations, translations of epigraphs, verbatim  quotation, and postscript. The interlingual translation by Vayenas and Layios  is only one of these convoluted chains of identification with, say, Seferis&rsquo;  &ldquo;Kichli&rdquo;. (Filippakopoulou 2005: 47-48)</p>
            </blockquote>
            <p>There is an unyielding power in the central metaphor of  the black light, whether in its linguistic,  referential, existential, or poetic guise. I believe that the source of  infatuation it represents to each one of these poets and translators as well  as, through their skilful mediation, to readers such as myself, is its power to <em>reflect</em>. Furthermore, what it reflects,  paradoxically, it reflects in <em>distortion</em> or, rather, in a series of  distortions: it is black, the opposite of  clarity and luminosity. That the coined phrase is a combination of two words<strong> </strong>which lend themselves easily to translation &ndash; <em>black</em>, <em>light</em> &ndash; does not  detract from the fact that this mesmerising,  twisted phrase acts upon Berengarten&rsquo;s poetry in ways not always foreseen:  perception of agency, poetic will in this case, is, therefore, changed in a  manner that I shall examine shortly. For the moment, let me simply say that to  accept this premise &ndash; &lsquo;black  light&rsquo; intimated by Seferis, reiterated in English by Berengarten,  back-translated by Layios and Vayenas &ndash; is to see Berengarten&rsquo;s poetry proposing and  experiencing a <em>wilful</em> alienation which merges with a process of  transformation affecting poet and reader(s). In the course of this discussion,  I aim to flesh out these abstract thoughts, for they have helped me reckon not  only with the lasting appeal of Berengarten&rsquo;s poetry but also with editorial  manifestations such as the bilingual edition of<em> Black Light</em>. I  also aim to show how the effects of <em>Black  Light</em>, the different types of distortion it allows (call it, if you will,  refraction, alienation, or transformation), can stand as an ethics for the  writing of poetry.</p>
            <p>In the context of this set  of aims and, more particularly, given the &lsquo;overarching&rsquo; perspective of a reader  responding to both English and Greek texts, I have come to view this bilingual  edition primarily as an exercise in <em>reflection</em>. A reflection, by  definition, on lost poets and their respective works, is more precisely an  effort to counteract the deadening of a  language &ndash; a deadening which has come to register the fact of death. To make such an attempt is to engage in an  open-ended dialogue with the foreign; and here  &lsquo;foreign&rsquo; is expanded to include the foreign within ourselves (Kristeva 1991),  in terms of identity, self-perception, and  (native) language. Its key element is the cross-lingual dialogue of poets,  whether or not through translation; hence the relevance of looking closely at  the bilingual rather than the original monolingual edition.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              The alienation brought on by death, whether remote or  intimate, makes visible the manner in which one&rsquo;s relation with one&rsquo;s mother  tongue has become stilted, blunt and merely &lsquo;communicative&rsquo;. In this respect,  the loss of childhood that I hinted at earlier is  simultaneously the inability to keep language alive by speaking it with those  one loves; as Seferis himself put it, &ldquo;as the years go by and you converse with  fewer voices, / you see the sun with different eyes&rdquo; (Seferis 1982: 168).  What is lost by growing old(er), by accepting changes, by continuing to live  after loved ones are gone, amounts to a  withering away of language, especially &lsquo;the native tongue&rsquo;. Hugo von Hofmannsthal in <em>The Lord Chandos Letter</em> spoke eloquently about this deadened language and the ensuing  self-estrangement, the reduction in the sharpness with which the world used to  present itself when language seemed to be organically linked to the sensations  conveyed by the world (Hofmannsthal 1995: 19, 20).</p>
  <p align="center"><strong>* * *</strong></p>
            <p>I can recollect with some effort the roughness of the  grey woolly blanket my brother and sister and I used to cover ourselves with,  when we slept outside on the veranda on hot summer nights, how pleasant its  warmth became when we finally fell asleep in the gathering dark, and how oppressive when dawn finally came, bringing with  it the growing heat of the morning. Is the recollection of the peach juices  running down my chin as I lay on warm pebbles after a long swim, as the light  was fading, imagined? Real or constructed memories, the sensuality of the  images, their very <em>presentness, </em>all stand, nonetheless, for a reality  that language now can neither hold nor capture any longer; and recollections  such as all of these point to a clarity of emotion inseparable from a language  quick to catch at the core of emotions that surfaced at the time, but have now become evasive.  It is a mixed blessing that Berengarten has come up with the very  definition of the kind of language-as-lost-happiness that I have in mind. It is found in the poem called &lsquo;Salt&rsquo;:</p>
            <blockquote>
              <p>[&hellip;] for here desire and fulfilment  are stitched in one weft of light,<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cross-woven, stilled and impossible  to unravel<br>
                from this seamless tide of days which  flow in one movement together <br>
                (Berengarten [1]: 164)<a href="#_edn5" name="_ednref5" title=""><sup>5</sup></a></p>
            </blockquote>
            <p>But it would be ill-advised to point too quickly to a  success, as there is nothing neat about what is  beneath this project. I would rather speak about the mechanics of how the  tribute to a lost poet is paid, how the act of preserving life in the face of  its cessation is carried out. For it is necessary for poetic composition to <em>enact</em> the alienation referred to, before it can bring back traces of the enchanted &lsquo;place&rsquo; where death was not yet a factual reality. I would like,  therefore, to structure this discussion on the basis of themes and tropes,  especially those found in <em>Black Light</em>. I will try to recover evidence of  the book&rsquo;s main  (emerging) themes: distortion, transformation, loss, sensuality, and  celebration. Simultaneously, I will be looking for the tropes which are largely  responsible for what I would call the <em>undeadening</em> effects of Richard  Berengarten&rsquo;s poetry. Foremost among them are immediacy, landscape, the undoing  of clich&eacute;s and, last but not least, translation.</p>
            <p align="center"><strong>* * *</strong></p>
            <p>&lsquo;Distortion&rsquo; leads the series of underlying themes in  Berengarten&rsquo;s poetry. The word itself has risen to my consciousness largely  thanks to the foreword by the two Greek poets/translators, in which they refer to the way in which Seferis&rsquo; voice is &ldquo;deflected&rdquo; in the voice of Richard  Berengarten. The distortion of <em>de</em>- makes one wonder why Berengarten&rsquo;s  voice should be <em>deflected</em> rather than <em>reflected</em>. Do we consider  it normal for voices to be deflected as they cross geo-linguistic borders? If  so, should we be at all concerned with or about this  change? Part of the change certainly involves the decontextualisation of, say,  Seferis&rsquo; poetry, seen  through the lenses of Berengarten&rsquo;s English. That alone brings out the  potential of a re-reading, whereby Seferis&rsquo; poetry is purged from the inevitable baggage of its  own historical genesis, and in particular his use of T.S. Eliot&rsquo;s high modernistic idiom to re-energise  Greek letters.<a href="#_edn6" name="_ednref6" title=""><sup>6</sup></a> Already, unexamined notions of native perception,  supposedly self-sufficient &ndash; what is commonly referred to as the &lsquo;self-same&rsquo; &ndash; are put into  question, as deflection is seen to have already  acted on the Greek original, which came into being by its very will to reflect  the foreign.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              To broaden the picture, the deflection at work can also  be seen in Berengarten&rsquo;s stated amazement at the way in which the new becomes  familiar while at the same time being an engine for productive self-distancing &ndash; i.e., self-alienation. Significant, in this respect,  is a compact note in his &lsquo;Postscript&rsquo; to<em> In a Time of Drought</em>, which, interestingly,  like <em>Black Light</em>, is another work by Berengarten that involves &lsquo;multiple  acts of translation&rsquo;, this time from south-Slavonic and other Balkan languages:</p>
            <blockquote>
              <p>When I started working on <em>In a  Time of Drought</em>, an idea had come to me, a hunch, a theme, accompanied by a  little (<em>too</em> little) knowledge. So, during the composition of the poem&rsquo;s first drafts, I set about finding as much as I could  about the rainmaking practices and songs. Their occurrence in cultures of which  I had shallow or scant experience, and their location in languages I understood  either imperfectly or not at all, added to their attraction. But as soon as I  started exploring, I found myself entering areas not only so new but also,  simultaneously, so wholly recognizable and so warmly hospitable that my set of  enquiries began to turn into an activity with its own separate direction and  momentum. More than once I was astonished to find that images which had been  cropping up spontaneously in my own mind during composition turned out to  belong to the sources themselves, and even to be part of their stuff or grain.  [&hellip;]</p>
              <p>Given the nature of the material that  has gone into the making of <em>In a Time of Drought</em> and my involvement in  it &ndash; whether as  fascinated guest, baffled foreigner, or both &ndash; I believe in retrospect that this plaiting or weaving  together was a necessary and inherent part of its composition. But as I began  to have inklings from my first notes and rough drafts of what was going on,  when it came to working on them, and at the same time taking the poem forward,  I found myself wanting to turn subliminal process into willed procedure, and so  gradually watched myself aiming to embed as complex a web of associations in  the writing as possible. And this self-watching got caught up in the poem's  making too, formulating itself, as I see now, as an attempt to eliminate any  remnants of my own voice. (Burns 2006: 33-34; Berengarten [4]: 77) </p>
            </blockquote>
            <p>As Berengarten proceeds from observing all things  foreign to manipulating them as poetic sources by following a willed procedure,  he clears his voice of what has been his own. Once again, as with the  &lsquo;deflection&rsquo; operating in this open dialogue, the poetic route seems to pass  through something of a distorting channel before the final composition is  offered.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              Similar unlikely pairs are found in &lsquo;Poem at the Autumn  Equinox&rsquo; in <em>Against Perfection</em>: </p>
            <blockquote>
              <p>[&hellip;]<br>
                and the one [dream] containing a word<br>
                clearly heard and recognised<br>
                from a language unknown,<br>
                which I can never pronounce. <br>
                &nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Burns 1999: 20;  Berengarten [5]: 35) </p>
            </blockquote>
            <p>The mystery of a word in a dream is conflated by sets  of unknown and unknowable elements: though mutually exclusive in normal usage,  the two adjectives, &ldquo;recognised&rdquo; and &ldquo;unknown&rdquo;, qualify the same noun, &ldquo;word&rdquo;. Equally significant, the  &ldquo;word&rdquo; is &ldquo;heard&rdquo; &ndash; and  therefore must have been spoken &ndash; but it is impossible for the poet to repeat it: he can &ldquo;never pronounce&rdquo; it. The realm in which the recognition of the &ldquo;unknown&rdquo; word occurs is, surely, very different from that of <em>logos</em>,  the Greek word that means &lsquo;rationality&rsquo; and &lsquo;speech&rsquo;. Rather, a process of  physical and imaginative dislocation is in process here. The scenario is one of  teasing or torment depending on where and how you look at it. It hints at  language as hindrance, even lack, thus presenting readers with two nearly  impossible puzzles: one is the source of seduction (a word), that is  unattainable; the other is the need to access it by language even when language is not forthcoming.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              One even wonders here whether English, or indeed any  other <em>single</em> language, is capable of fully illustrating the obvious  truth of the poet&rsquo;s insight.  Might then a cross-lingual dialogue not be more suited to the task? In &lsquo;Only  the Common Miracle&rsquo;, the realisation of failure takes a dramatic turn when, &ldquo;at passion&rsquo;s crest&rdquo;, one lover opens her<strong>/</strong>his<strong> </strong>eyes: the realisation becomes a material tear on the  page, when &ldquo;a gap opens  for a voice&rdquo; (Berengarten  [1]:161). The split is there for both lovers to be-hold, causing a nagging sensation  because this voice is one that &ldquo;isn&rsquo;t yours or mine, but we both hear quite clearly, and  recognise&rdquo;. The phrasing  here is very similar in lexical choice to &lsquo;Poem at the Autumn Equinox&rsquo;, thus  suggesting a deeper affinity between the two poems. But further on in &lsquo;Only the  Common Miracle&rsquo;, we read that this is a voice [which we both] &ldquo;understand, and adore, because you know as well as I  do, my love, that its your voice, not mine&rdquo; (ibid: 161). The gap seems to be bridged here, albeit  briefly, as the poet&rsquo;s persona  reaches over to her/his lover. However, the disconcerting spectre of alienation  even on one&rsquo;s own native  ground remains, and, with it, the threat of not mastering &ldquo;the language of love&rdquo;, as the next, and last, stanza illustrates:</p>
            <blockquote>
              <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[&hellip;]  but people like<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;you and me have been travelling<br>
                like this for years,  along the same dirt track through the<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;same city streets the same weary beds,<br>
                foreign in our own  country, <em>no longer recognising the<br> 
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;speech of men or women we know, of our  own flesh</em>,<br>
                so how then can we  be expected to converse with angels<br> 
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;or even <em>with old friends, long dead</em>,<br>
                let alone speak the  language of love, let alone the <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;language of love? (ibid 161; emphasis added, MF) </p>
            </blockquote>
            <p>&lsquo;Cicadas  (I)&rsquo; singles out, I believe, the moment in which &ldquo;a gap opens for a voice&rdquo;, and  enlarges that moment to a whole poem. The first stanza reads as follows:</p>
            <blockquote>
              <p>The men play <em>t&aacute;vli</em> and drink <em>ts&iacute;pouro</em> or coffee,<br>
                <em>sk&eacute;to</em>, <em>m&eacute;trio</em>, <em>glyk&iacute; vrast&oacute;</em>. Above our heads<br>
                the <em>nichter&iacute;dhes</em> flitter among  the plane trees<br>
                and every table but mine in the  square is full.<br>
                Through voices&rsquo; thrum, laughter, clatter of board<br>
                and counter, clink of glasses, and  fork against plate,<br>
                where the bald, bullied waiter runs,  scurrying, sweating,<br>
                tonight I sit alone, trying to write  a letter<br>
                home to my son and daughter: <em>Dearest  Children</em>&hellip; (ibid: 159) </p>
            </blockquote>
            <p>There is a cacophony of voices here, which could stand  for an attempt to alert us to the gap as discussed earlier, as a representation  of language&rsquo;s eventual  failure to communicate &ndash; or rather, failure  because language, a mundane instrument, <em>primarily</em> communicates. First,  there is a series of transcriptions of Greek words, which, although ordinary,  would mean very little to an English reader: <em>t&aacute;vli</em>, <em>ts&iacute;pouro</em>, <em>sk&eacute;to</em>, <em>m&eacute;trio</em>, <em>glyk&iacute; vrast&oacute;</em>, <em>nichter&iacute;dhes</em><strong>.</strong><a href="#_edn7" name="_ednref7" title=""><sup>7</sup></a><strong> </strong>Repetition of the &lsquo;t&rsquo; sound, which is probably the single  most overwhelming sound heard when a Briton overhears two Greek people  chatting, together with their sheer accumulation in the first three lines,  helps to impress the point of alienation by direct illustration. Then the level  of foreignness/estrangement drops from actual human (foreign) speech, through  &ldquo;voices&rsquo; thrum and laughter&rdquo;, to the inanimate noise in the caf&eacute;: &ldquo;clatter of  board and counter&rdquo;, &ldquo;clink of glasses&rdquo;, &ldquo;fork against plate&rdquo;. There are, of  course, human beings behind these noises, but crucially the imagery reduces  them to simple auditory effects. The non-human movement seems to have engulfed  even the emergence in the poem of the waiter in the form of two sets of  alliteration, &ldquo;bald, bullied&rdquo; and &ldquo;scurrying, sweating&rdquo; &ndash; to the extent that he  is entirely made up of sensory signals. Against this background, it would be  very difficult not to take the last sample of speech &ndash; the form of address in the narrator&rsquo;s letter to his  children, &ldquo;<em>Dearest Children</em>&hellip;&rdquo; &ndash; as yet another expression of inane human language,  blunt with overuse. Of note also is the corroborating caesura splitting  &ldquo;letter&rdquo; and &ldquo;home&rdquo;, exposing their uneasy cohabitation. Symmetry alone in the  stanza structure means that the italicisation of the Greek loan words mentioned  above, on the one hand, and the typographical relief of this standard phrase,  on the other, link them to each other as  illustrations of spoken language which has ceased to effectively signify, or  authentically affect. </p>
            <p align="center">* * *</p>
            <p>The next question should be whether the actual  translation, between English and Greek, is to be considered a mere aspect of  the project that the <em>Black</em> <em>Light</em> is, whose efficiency is mediated  on its very heterogeneity, its over-inscribed fabric. The brief answer is that,  if the volume&rsquo;s boldness consists in the fact that it actively complicates notions of belonging by  multiplying the available options of reading &ndash; that is, reading  in English, reading in Greek, and reading the  different originals of these metapoems and translations, not to mention all the <em>misreadings</em> that such readings entail &ndash; then there should be nothing straightforward about the  translation that forms the core of the work. And  sure enough, my reading of it has shown that its  impact exceeds notions of equivalence or accuracy, the usual angles of viewing  translations in print.</p>
            <p>Rather arbitrarily, I have chosen to focus on the  translations by Ilias Layios. My decision to discuss his translations has been  more a response to the particularly strong effect their language has had on me  than to any criteria of accuracy, maybe even despite such criteria. One  particular instance of translation has proven to offer an ideal and delightful  illustration: the &ldquo;fledgling [soul]&rdquo; in the poem &lsquo;Soulmonger&rsquo; (Berengarten [1]: 155) is  unexpectedly rendered by Layios with the Greek word <em>ksepetaro&uacute;di</em> (Burns<strong> </strong>2005: 19)<strong>.</strong>&nbsp; The unforeseen little word gave me a jolt of  happiness. I pondered for a while on the funny musicality of the noun, maybe  slightly shocked to find such a cockily improper choice written down. It is a  quirky, idiolectical choice that speaks conspiratorially into the ear of the  child in me, giving disproportionate pleasure with its shape, intonation, and  timbre. On a philological level, it is strikingly evocative of the diction of  Dionysius Solomos, who, as Seferis famously put it, was &ldquo;our other great poet  who did not speak good Greek&rdquo; (the other being Cavafy). What is splendid about  it is that the little word has enlarged its preordained spot on the page by  exceeding what the original requires semantically; thus, it creates a pocket of  meaning, emotions, images and memories that more or less bring the reading  process to a halt, all within the space of its four syllables. In the  indefinable period of time elapsed between the English and the Greek texts, the  English adjective has evolved to become, in the Greek translation, a fully  grown up, a syntactically independent noun.</p>
            <p>There is  something of a hijacking at work here, as the show is momentarily stolen by the  word <em>ksepetaro&uacute;di</em>, the cameo equivalent, which is equivalent to none,  because it belongs to the Greek poet-translator&rsquo;s own lived-in language, which  is intertextually linked &ndash; and, clearly, without any mediation from English &ndash;  to Greek literature. Which brings us, without fail, to Layios&rsquo;s unique  signature as a poet: his inability simply to translate, his lack, if you wish,  of a translation &lsquo;strategy&rsquo; unless there might be some way of appropriately  defining the manner in which he has breathed a soul into the words he chooses.  His is such a strong voice in Greek that it ends up straying from the  inevitable linearity of the translation process, cancelling even the factuality  of translation. His odd &lsquo;appropriation&rsquo; of the source poem is evident, in that  here, as elsewhere, he draws the attention of the reader <em>away</em> from the  original. I cannot imagine any bilingual reader of this collection who would  not be drawn to his translations to the detriment of the English poems. Having  said that, I would add that such is the fervour of his linguistic choices that  one has to go back to the original to make sure that one has read it  &lsquo;correctly&rsquo; the first time. So, in effect, Layios encourages the reader to  revisit the English poem, which has been brushed aside too quickly in the  previous readings, in the hope of finding in it some enlightening cues or clues  for a word, or a turn of phrase, in the Greek poem &ndash; which, thanks to its  authority and power, one can hardly call merely a &lsquo;version&rsquo;. In plain words,  Layios&rsquo;s translations have sharpened the reader&rsquo;s focus on the &lsquo;original&rsquo;  English poem&nbsp; &ndash; but in an oblique and  very unexpected manner.<a href="#_edn8" name="_ednref8" title=""><sup>8</sup></a> For in the reading experience I am describing, this &lsquo;original&rsquo; emerges  re-energised, transformed: and so much so that the &ldquo;fledgling [soul]&rdquo; of  Berengarten becomes in effect the &lsquo;translation&rsquo; of Layios&rsquo;s &ldquo;<em>ksepetaro&uacute;di</em>&rdquo;,  rather than vice-versa, because it is assumed, on the basis of their <em>de  facto</em> equivalence, that the English now illuminates the meaning of the <em>Greek</em>.  Whether or not this is actually the case, it certainly pushes the source poem  back to the centre stage, thanks to a newly discovered affinity &ndash; the result of  Layios&rsquo;s eccentric insistence on acting with the interests of the Greek language  close at heart.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              Other examples of this highly individual approach to  translating are Layios&rsquo;s transformations of existing words in accordance both  with their colloquial or dialectical pronunciation, and with his own preference  for longer particles and pronouns, as though he wished to augment their sensory effect. The  orality is unmistakable. Layios did speak like that himself, and probably it is  because now we will never get to hear his voice again that lexical features  such as these, minor but striking in their overall impact, become so  elementary. Deploringly for a language rendered orphan after his death, the  pacing and intonation of his lines betray something of the vibration, the pitch  (even drunkenness at times) of his own voice, that  moved his friends and audience when he recited verses by heart, or when he  merely told a story about a friend or foe. Nor is his vocabulary or choice of  register contained. From Biblical to demotic and then back to a purist Greek,  his poetic language does not miss a note: on the one hand, the mundane  crudeness of <em>mpisna</em> [business] (Burns 2005: 47) coexists with the  Socratic <em>en oida</em> [one thing I know] (ibid.: 41); and on the other, the  Palamas-inspired <em>skoteinagra</em> [gloom] joins the bowdlerised, and thus  more effective, <em>ntantella</em> [lace] (ibid.: 49). In the vernacular delicacy  of similar choices, vulgarity and mellowness are effectively juxtaposed and  counterpointed, in such a way that their depth of reach bestows a kind of  multilayered relief on the language of the translations. Nor are these choices  dictated solely by the wording of the original poems or by the rhyme scheme of  the translations. Although both these factors come into play, neither of them  serves even in the slightest way to exhaust the reading pleasure, simply  because the pleasure itself derives from the quirky illumination the Greek  &lsquo;versions&rsquo; throw onto the &lsquo;original&rsquo; English poems. That is to say, the feeling  of elation does not come from where you would normally expect it; it arises  from the novel relationship between source and target poems. <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              I have quite deliberately elaborated, and perhaps  downright exaggerated, my commentary on these rather flimsy instances of  translating. My purpose has been to illustrate how the predominant trope of  translation here accounts for an exhilarating reading process, in which  concepts of deflection and, by extension, self-identity, need to be rethought.  The logical consequences of comments such as the above are that, first, any  straying of criticism from trying to make sense of, say, cross-lingual dialogue  is unavoidable; secondly, following an essentially straying memory renders  systematicity, and even its desire, irrelevant; and, thirdly, the joy of  recognition from poetry of this kind is not to be retrieved by communication  between the two &lsquo;audiences&rsquo;, but by plainly, obstinately, going back to the  site of one&rsquo;s own origins. </p>
            <p>But the difficulty is: there are no roots.<a href="#_edn9" name="_ednref9" title=""><sup>9</sup></a> The only way to &lsquo;return&rsquo; to a place of origin is to recreate  the sensation that language gave us in a remote past or pasts, to pick out and  relish the particular flavours of the registers, dialects and idiolects  accreted by those pasts and heaped by them into presence, by reconstructing the  moment of untainted pleasure upon hearing that elusive word - trace of a language which can best be qualified  as a spent resource.</p>
            <p align="center">* * *</p>
            <p>Not everyone would agree with the slant I have given to  Berengarten&rsquo;s poetry, a hemmed-in reading that insists on the <em>dark</em> part  of the &lsquo;dark light&rsquo;. It is, however, a matter of emphasis; and emphasis is necessary if the existential reading  I am offering is to balance itself out. The fraught moments of realising what  is lost, of observing the Seferian moment that &lsquo;cuts through time&rsquo;, of  contemplating memories as mere fossils of bygone times, of desiring the faces  of &nbsp;&ldquo;our own flesh&rdquo; (i.e. our own kin) to the point of thinking we heard  their voices in an unlikely place &ndash; all these are moments that would eventually put an end  to all dialogue if no actual transformation were to follow. The climax of <em>Black  Light</em>, the proof, if you prefer, of its thorny fertility is, for me,  &lsquo;Volta&rsquo;, a poem about falling in love again, or being able to (Berengarten  [1]: 157-8). Transformation is required to achieve a language  defying loss, evident in this poem when the narrator becomes &ldquo;porous&rdquo;, to  receive the light of a radiant evening. The tone of the poem is rightly  elegiac, and its pivotal position in the collection is evident if we consider  that it is a comment on a very un-striking line by Seferis: <em>now that dusk  falls</em>&hellip; (ibid: 157).  I would like to risk the argument that a nondescript epigraph for, in effect, a  sublime poem should surely lead us to a moment of intense dialogue between  poets, which is also the moment when Berengarten&rsquo;s creativity is sharply  ignited by the Greek light &ndash; a light he  refers to in a filigree of images such as &ldquo;[k]ing sun&rdquo;, &ldquo;sweet evening  skyglow&rdquo;, &ldquo;shimmering light&rdquo;, &ldquo;darling evening&rdquo;, &ldquo;light thousands of years  old&rdquo;, &ldquo;clear throated singer&rdquo;,
  &ldquo;a mould that sculptures all it touches&rdquo;. The  understatement of the Greek epigraph &ndash; strategically designed to have this  effect<a href="#_edn10" name="_ednref10" title=""><sup>10</sup></a> - has led to an excess of emotion in Berengarten&rsquo;s response  to the light, a response in turn to the effects of light on people before him  and his time: the accumulative effect is such that the observer/recipient of  light becomes a web of exposed senses. His  realisation is expressed in the lucid, composed language of a well-rounded  citizen of the city in question, and one cannot help but think of another  famous citizen, no other than Constantine Cavafy, and Alexandria.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              The unashamed rawness of emotions &ndash; impacted and reflected &ndash; is on a par with the fundamental rawness of senses  rendered naked, their very functionality. Looking closer, one notices how the  internal rhyming through the repetition of the &lsquo;o&rsquo; sound, climaxing at &lsquo;the  pool of gold you pour&rsquo;, uncovers the porous quality of the poet&rsquo;s  transformation:</p>
            <blockquote>
              <p>King sun, rosy-cheeked, day&rsquo;s  sovereign coin,<br>
                you touch me, and my skin becomes a  cornea,<br>
                my spine an optic nerve, and my body  trembles<br>
                half dazzled by the pool of gold you  pour<br>
                over this sea and city, and I&rsquo;m  blinded. (Berengarten [1]: 157)</p>
            </blockquote>
            <p>In my initial reading of this poem, I considered it  significant that there was a semi-obscure female presence acting as a catalyst  on what women readers would undoubtedly perceive as &lsquo;an encounter of male  poets&rsquo; in the context of Greek history (Filippakopoulou 2005: 48). But now I am  convinced that, although this remains true,<a href="#_edn11" name="_ednref11" title=""><sup>11</sup></a> the sensuality of these stanzas far exceeds sexuality,  especially in terms of heterosexual desire and lust. In this respect, the  language of the poem is exuberant in its impact for it can bring both female  and male readers back to the way life used to be experienced, through the  senses, to the point that the senses themselves become a synonym for outer  reality. The narrator&rsquo;s ecstatic exclamation: &ldquo;I drink you, shimmering light&rdquo;  (ibid: 158) sums up the celebration of senses that is the poem;  it concludes a few lines further on: &ldquo;And, thirsting to drink you wholly, I  would fill / every pore with your radiance [&hellip;]&rdquo; (ibid: 158). It might  be that Berengarten has discovered, in this &ldquo;porous&rdquo; condition, the appropriate  state and a new means of honestly and creatively translating another culture  and literature, in the dual sense of both &ldquo;honouring&rdquo; and &ldquo;giving back&rdquo;.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              The theory of translation is historically grounded on a  discourse that sexualises the translating and translated sites in the image of  unequal sexual pairs. Metaphors in use, such as <em>les belles infid&egrave;les</em>, illustrate that &ldquo;western culture  enforces [the] secondariness [of translation] with a vengeance, insisting on  the feminized status of translation&rdquo; (Chamberlain 1988: 477). Understanding the  role of such metaphorics does not, however, mean that it can be easily  transgressed, especially in the case of a male author. But here we have an  instance of translating a trademark trope &ndash; Seferis&rsquo; &ldquo;black light&rdquo; &ndash; in such a way that there is neither invader nor  invaded. The transformation of Berengarten&rsquo;s narrator into a porous being who  has willed his body and senses to take in the universe cast by the  Mediterranean light, to become its &ldquo;slave, if not [its] citizen&rdquo;, is a valid,  robust proposition out of the deeply ingrained sexism found in translation practice  (Berengarten [1]: 158). <br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              The light that the narrator cannot help but adore is  what &ldquo;liquefies stone&rdquo; in &lsquo;Salt&rsquo;: it is &ldquo;as if the statue&rsquo;s marble body were  dancing&rdquo; (ibid: 162), an additional intimation of the miraculous capacity  of light to do and undo what death fixes forever, matter. The function of the statue in Berengarten&rsquo;s poetry is quite  strategic in that it suggests a notion of perfection in gestation. Statues &ndash; the effects of light &ndash; are simultaneously fixed and liquid, and in this  capacity they help avoid a clich&eacute; in their imagery in relation to the  representation of Greek literature and culture. In this he takes his cue from  Seferis himself, who famously undid the fixity of statues, that is to say, the  rigidity of the Greek ancient past, by giving statues human attributes, especially in  section II of the &lsquo;Thrush&rsquo; (Seferis 1982: 163).<a href="#_edn12" name="_ednref12" title=""><sup>12</sup></a> The entire landscape of &lsquo;Volta&rsquo;, both human and inanimate, is defined and signified by the effects of  light, and the poet&rsquo;s willingness fully to acknowledge these effects results in the poetic  expression of a perfect day on a fishing boat. &lsquo;Salt&rsquo; might commence and finish  with the phrase &ldquo;all I know&rdquo; (Berengarten [1]: 162, 164), but it embodies a  type of knowledge that is beyond cognition; it is rather the wisdom, imparted  by the senses, to receive the world rendered naked by light&rsquo;s miracle. Earlier,  I suggested that Berengarten offers nothing less than a definition of happiness  as experienced by a long-lost internalised child  of five, savouring a ripe fruit in front of the sea; we read in &lsquo;Salt&rsquo;:</p>
            <blockquote>
              <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[&hellip;] and all I know is, I&rsquo;m helplessly<br>
                &nbsp;&nbsp; &nbsp; &nbsp;in love with this mountain and this sea,<br>
                for here desire and fulfilment are stitched in one weft of <br>
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; light,  cross-woven, stilled and impossible to unravel<br>
                from this seamless tide of days which flow in one <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;movement together, its  whole fabric soaked and doubly<br> 
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;strengthened in salt,<br>
                and mine is  its crusted harvest with the perfect inner sheen,<br>
                &nbsp;although I have gnawed summer down to its  black core. <br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ibid: 164)</p>
            </blockquote>
            <p>Naivety aside, I would like to argue that Berengarten  forces his language to recreate the core of the world as uncovered by light in  a superb description &ndash; its fabric being not ethereal, but heavy with the crust of  salt, the lived-in experience, a tactile memory of summer. Because tactile,  virtually epidermal, it has to be talked about in the first person: the  narrator is obliged to exclaim, with a child-like reversal of the proper word  order, &ldquo;<em>mine</em> is its crusted harvest with the perfect inner sheen&rdquo; (ibid:  164, emphasis added, MF), transformed because transported to a near-orgasmic  state, recalling the wild joy of once savouring the moment while registering  the consuming desire to regain it. <br>
              <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><br>
              Paramount among such perspectives, <em>Black Light</em> is also a collection of poems that has <em>attracted</em> its translation by the two Greek poets. The series of moving mirrors, no matter  how &ldquo;tarnished&rdquo; they might be (&lsquo;Shell&rsquo;, ibid: 174), help to strengthen  Berengarten&rsquo;s essential virtue: of mastering a language enchanted enough by the  foreign and surrendering enough to the foreign to invite its own deflections.  The project has enabled difference &ndash; the mark of the foreign &ndash; to bring on a transformation, unexpected in its  results, that owes a lot to the multiplication of lines of attraction and  intersection between the native/self and the foreign. My argument has been that  the transformation depends on assuming a problematic affinity between childhood  (and the native tongue it is grounded upon) and the remote foreign landscape  (spatial and human): as suggested in my introductory comments, the alienation  that primarily marks adulthood can be accentuated by<strong> </strong>a plunge into a  foreign landscape &ndash; here &ldquo;black  light&rdquo; as a metaphor from/for Greek poetry. An ideal illustration of this is  the first stanza of &lsquo;Song, for Petro&rsquo;:</p>
            <blockquote>
              <p>What moves,  though still, yet sounds,<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;what, breathing, blows mysterious,<br>
                perfuming  this whole valley<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;channelling mountain waters<br>
                to race and  tumble, child-like,<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;down to your beach, through memory,<br>
                and plunge  into the sea &ndash; this gift,<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;old friend, is yours:<br>
                let nobody  take it from you. (ibid: 168)</p>
            </blockquote>
            <p>Every time the poem is read, its meticulous language  puts together an already existing landscape and seascape for the first time;  the quickening fluidity of the description helps keep at bay complacency, the  banality of a picturesque holiday destination<strong>. </strong>To turn the familiar into  the unfamiliar is a fine achievement. Here, senses co-operate with movement to  build a specific emotion in the brain and the heart, which would then recognise  the flow of the water as it comes down from secret mountains to reach you.  Readers are, at one stroke, transformed into small children who, wobbly feet  and all, run to join <em>flo&iacute;svos</em> [the sea&rsquo;s edge]. The encounter should be  child-like for a good reason: the ancient elements become recognisable only to  a sensitivity susceptible to enchantment and enamoured with the matter as it  finds it; this must be the metaphor <em>par excellence </em>of unadulterated  perception.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              Besides the invocation of the landscape, another aspect  of translation in its extended sense is the illuminating dialogue between poem  and epigram, of which &lsquo;Cicadas (I)&rsquo; and &lsquo;Cicadas (II)&rsquo; represent a case in point  (ibid: 159 &amp; 171-172). The figure of the cicada itself as an allegory is  rather ambiguous. In both &lsquo;Cicadas (I)&rsquo; and &lsquo;Cicadas (II)&rsquo;, the incessant,  inane singing of the cicadas can function either as a metaphor for the  annihilation of human language against which poetry struggles,<a href="#_edn13" name="_ednref13" title=""><sup>13</sup></a> or as the very essence of <em>poeisis</em> [creation].<a href="#_edn14" name="_ednref14" title=""><sup>14</sup></a> Although these are plausible interpretations, one  should, more importantly, account for the fact that the two poems offer a  commentary on Seferis&rsquo; line &ldquo;&hellip; <em>the way the cicadas stop suddenly and all  together</em>&rdquo; &ndash; the poem&rsquo;s epigraph (Seferis 1982: 338-339). The issue  here, then, is not the allegorical figure of the cicadas but the question of  what it is that the exploding silence, the momentary cessation of Nature&rsquo;s &lsquo;voice&rsquo;, means &ndash; and, most importantly of all, where this leaves the  poet. His is a miraculous position, to create on the basis of the exposed,  artificial silence as a site both vacant and full: vacant through the absence  of meaningful human language, and filled with what human language is not, be  that nature, musicality of sounds, or dreams. Berengarten gestures towards both  possibilities while at the same time illustating how the potential of  translation can be fruitfully, suggestively exploited here too. </p>
            <p align="center">* * *</p>
           <p>   In rare moments of physical and mental clarity, maybe  daydreaming or through intense concentration, one can half-imagine,  half-reconstruct<strong> </strong>the sensation of the &ldquo;seamless tide of days which flow  in one movement together&rdquo; (Berengarten [1]: 162, 164) &ndash; the connectedness  with nature and people through language encapsulated in these fortunate verses.  Trying to recapture this lost order is the constitutive war of adulthood. Since  the time of Sappho, armies of people have known that this war is lost, though  the manner of losing it makes all the difference. Poetic language partakes of  this crucial task, to wage war on <em>l&iacute;thi</em>, on forgetting. <em>Black Light</em>,  not to say Burns/Berengarten&rsquo;s poetry in its entirety, shows that managing this  Promethean task cannot be done through one language, no matter what that  language might be.<a href="#_edn15" name="_ednref15" title=""><sup>15</sup></a> If lyrical language is to have any success in bringing  about its undeadening effects, it needs a catalyst to rehearse the reality of  loss, to <em>enact </em>self-alienation.<strong> </strong>In the translation by Layios and Vayenas, the enterprise is played out in a  format which obliges bilingual readers, at any rate, to first look into the  face of the British poet turned towards the Greek poet laureate, before they  can contemplate the work of the Greek translators and be struck by its  manipulative energies.<a href="#_edn16" name="_ednref16" title=""><sup>16</sup></a> The multiple in effect, zigzag reading is truly  illuminating for it is responsible for the joy of recovering, partly at least,  native tongue in the very midst of estrangement<strong>. </strong><br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              The emotion stirred at the moment of empathy with the  poet&rsquo;s infatuation with light and light&rsquo;s inflections is not dissimilar to the  moment in which one encounters words unnoticeably forgotten in the course of  life, words that one will never speak again with people now perished, &ldquo;outside  of being, in that radiance&rdquo;.<a href="#_edn17" name="_ednref17" title=""><sup>17</sup></a> These spoken words are haunted, as Berengarten very  appropriately stresses again and again. Of all the themes and tropes I have  discussed here, translation proves to be the most revealing for bilingual  readers, a true key to Berengarten&rsquo;s poetry: in &lsquo;Cicadas&rsquo; and &lsquo;Volta&rsquo;, the  respective dialogue between the poems and their epigraphs was conducted across  a gaping difference. But it is precisely through the lack of equivalence that  an excess of meaning has been uncovered &ndash; the breaking of silence and the mystery of language in  &lsquo;Cicadas&rsquo;, understatement and ecstatic recognition in &lsquo;Volta&rsquo;. Berengarten&rsquo;s poetry invites readers to glimpse at the mechanics of  multivocal, multilingual poetry: its attraction works by bringing one closer  not simply to what is not one&rsquo;s own, but also to what is. It is not simply that  what is native &ndash; that which  belongs unthinkingly to a national literature and language &ndash; needs the foreign in order to enrich its traditions  and gain in originality. The ethics of this poetry is that a single  language/literature should work through another language/literature to let in  alienation, in order to chisel new life out of  death. Today poetic dialogue with the Other is not simply one literary option  or device among many others; it is a bare necessity.</p>
            <p><small>This essay is to be published, in slightly abbreviated form, in <em>Richard  Berengarten: A Critical Companion</em>, ed. Norman Jope, Paul S. Derrick and  Catherine E. Byfield&nbsp; (forthcoming, Salt  Publishing, Cambridge, 2010).</small></p>
            <p><strong>Bibliography</strong></p>
            <p>Beaton, Roderick. 1991. <em>George Seferis</em>. Bristol: Bristol Classical Press and New York: Aristide D. Caratzas.<br>
              Berengarten, Richard [1]. 2008. <em>For the Living. Selected Writings 1.  Longer Poems 1965-2000</em>. Cambridge: Salt<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Publishing.<br>
  &ndash; &ndash; .&nbsp;&nbsp;&nbsp;&nbsp; [2]. 2008. <em>The Manager</em>.<em> Selected Writings 2</em>. Cambridge: Salt Publishing<br>
  &ndash; &ndash; .&nbsp;&nbsp;&nbsp;&nbsp; [3]. 2008. <em>The Blue Butterfly</em>.<em> Selected Writings 3</em>. Cambridge: Salt Publishing<br>
  &ndash; &ndash;. &nbsp;&nbsp;&nbsp;&nbsp; [4]. 2008. <em>In a Time of  Drought</em>.<em> Selected Writings 4</em>. Cambridge: Salt Publishing<br>
  &ndash; &ndash;. &nbsp;&nbsp;&nbsp;&nbsp; [5]. 2008. <em>Under Balkan  Light</em>.<em> Selected Writings 5</em>. Cambridge: Salt Publishing<br>
              Burns, Richard. 1980. <em>Learning to Talk</em>. London: Enitharmon Press.<br>
  &ndash; &ndash;. &nbsp;&nbsp;&nbsp;&nbsp; 1983. <em>Black Light: Poems  in Memory of George Seferis</em>. Cambridge: Los Poetry Press. 1986, reprinted by the <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; same  publisher. 1995, reprinted, Norwich: The King of Hearts.<br>
  &ndash; &ndash;. &nbsp;&nbsp; 1999. <em>Against Perfection</em>.  Norwich: The King of Hearts.<br>
  &ndash; &ndash;.&nbsp; &nbsp; 2003. <em>Book With no Back Cover</em>. London: David Paul.<br>
  &ndash; &ndash;.&nbsp; &nbsp; 2005.<em> Mavro Fos. Poiimata eis mnimin George Seferis</em> (tr. N. Vayenas and Ilias Layios). Athens: Typothito &ndash;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Lalon Hydor.<br>
  &ndash; &ndash;.&nbsp; &nbsp; 2006. <em>In a Time of Drought</em>. Nottingham: Shoestring Press.<br>
  &ndash; &ndash;.&nbsp; &nbsp; Website: http://www.richardburns.eu/site/From-Notness.html <br>
              Chamberlain, Lori. 1988. &lsquo;Gender and the Metaphorics of Translation&rsquo; in <em>Signs</em>,  13: 464-72.<br>
              Filippakopoulou, Maria. 2005. &lsquo;Common miracle [in <em>In Other Words. The  Journal for Literary Translators</em>, 26: 46-51.<br>
              Hofmannsthal, Hugo von. 1995. <em>The Lord Chandos Letter</em> (tr. M.  Hofmann). London: Syrens.<br>
              Jakobson, Roman. 1992. &lsquo;On Linguistic Aspects of Translation&rsquo; in Schulte,  Rainer and John Biguenet (eds.)<em> Theories of<br> 
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Translation. An Anthology of  Essays from Dryden to Derrida</em>. Chicago and London: The University of Chicago<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Press: 144-51<br>
              Kristeva, Julia. 1991. <em>Strangers to Ourselves</em> (tr. L. S. Roudiez). New York and London: Harvester Wheatsheaf.<br>
              Seferis, George. 1982. <em>Complete Poems</em> (tr. E. Keeley and Philip Sherrard). London: Anvil Press Poetry.<br>
  &ndash; &ndash;. 1974. <em>A Poet&rsquo;s Journal. Days of 1945-1951</em> (tr. A.  Anagnostopoulos). Cambridge, Massachusetts: The Belknap<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Press of Harvard University Press.<br>
              Vayenas, Nasos. 1989. <em>Poiisi kai Metafrasi</em> [Poetry and  Translation]. Athens: Stigmi.</p>
            <p>&nbsp;</p>
            <div>
              <div id="edn1">
                <p><a href="#_ednref1" name="_edn1" title="">1.</a> The title of this essay is taken from &lsquo;Only the Common Miracle&rsquo;, a  poem in Richard Berengarten&rsquo;s sequence <em>Black Light</em>. For the most recent monolingual English  publication of this sequence, see Berengarten [1] 2008. For the first English  editions, see Burns: 1983. Some references in this essay are to the bilingual  Anglo-Greek edition of <em>Black Light</em>, (Burns 2005), entitled <em>Mavro Fos</em>,  translated by Nasos Vayenas and Ilias Layios, both poets in their own right.</p>
              </div>
              <div id="edn2">
                <p><a href="#_ednref2" name="_edn2" title="">2.</a>&nbsp; In June 2008, Richard Burns  changed his name to Richard Berengarten. This change was announced in notes in  the first five volumes of his <em>Selected Writings</em> (Salt, Cambridge, November 2008), such as the  following: &lsquo;Richard Berengarten used to be known as Richard Burns . . . [H]e now repossesses the family name of  his father, the cellist and saxophonist, Alexander Berengarten&rsquo; (Berengarten [1]: sleeve notes). &nbsp;Henceforward, in references to the poet  himself, this essay adheres to the name Berengarten. </p>
              </div>
              <div id="edn3">
                <p><a href="#_ednref3" name="_edn3" title="">3.</a>&nbsp; &nbsp;During the period that intervened between my  first and second readings of the bilingual edition of <em>Black Light</em>, Ilias Layios, one of the book&rsquo;s two translators, died  unexpectedly in Athens in  2005.&nbsp; In 2006, I also learned of the  death of my close personal family friend, Kyria Christoula.<strong> </strong></p>
              </div>
              <div id="edn4">
                <p><a href="#_ednref4" name="_edn4" title="">4.</a>&nbsp; &nbsp;This element in the text itself could, at  least partly, account for the affinity I felt with the book at my own time of  loss.<strong><u> </u></strong></p>
              </div>
              <div id="edn5">
                <p><a href="#_ednref5" name="_edn5" title="">5.</a>&nbsp; &nbsp; Hereafter all references to the original <em>Black Light</em> will be made in the format (Berengarten [1]: page number), and will be inserted  in the body of the text.</p>
              </div>
              <div id="edn6">
                <p><a href="#_ednref6" name="_edn6" title="">6.</a> &nbsp;&nbsp;In Greek criticism, Seferis&rsquo; &lsquo;Kichli&rsquo; [&lsquo;Thrush&rsquo;] is considered to be nothing  less than &ldquo;the Greek equivalent of <em>The Waste Land</em>&rdquo; (Vayenas 1989: 99).</p>
              </div>
              <div id="edn7">
                <p><a href="#_ednref7" name="_edn7" title="">7.</a>&nbsp;&nbsp;However, Berengarten is careful to add  the English meaning of these words in his notes to the poem: &lsquo;<em>t&aacute;vli</em>:backgammon; <em>ts&iacute;pouro</em>: an anis drink, like ouzo; <em>sk&eacute;to,  m&eacute;tno,  glyk&iacute;  vrast&oacute;</em>:  sugarless, medium, sweet-boiled (terms used for coffee): <em>nichter&iacute;dhes</em>:bats.&rsquo; (Berengarten [1]: 224)</p>
              </div>
              <div id="edn8">
                <p><a href="#_ednref8" name="_edn8" title="">8.</a> &nbsp;&nbsp;For further thoughts on the idea of the &lsquo;original&rsquo;, see Filippakopoulou 2005:  47-48, quoted above.</p>
              </div>
              <div id="edn9">
                <p><a href="#_ednref9" name="_edn9" title="">9.</a> &nbsp;&nbsp;Let us  remember that Seferis himself was effectively a Greek living on the mainland  after the forced exile from his childhood homeland, Asia Minor (Ionia), in 1922. His poetry is, in a way, a poetry of  exile; see the introductory point made by his editors (Seferis1982<em>:</em> xvii).</p>
              </div>
              <div id="edn10">
                <p><a href="#_ednref10" name="_edn10" title="">10.</a>&nbsp;&nbsp; In a personal response to  the author (April 3, 2008), Richard Berengarten has noted that if the epigraph taken from Seferis is  &ldquo;understated&rdquo;, it was chosen to be so, deliberately. And he continues as  follows: &ldquo;because, for my purposes, I needed to highlight the simplest elements  of Seferis&rsquo; line and so to remove them from their (from my point of view,  over-specified) surrounding context. So perhaps the part quoted does <em>appear</em> &lsquo;uninteresting&rsquo;. But I&rsquo;ve always thought the whole of this line to be among  Seferis&rsquo; most wonderful, most fabulous achievements, for its purity of music  (with the sibilant sounds of ships&rsquo; sirens) and its transparent simplicity, as  well as its centred, embodied love of the aural and visual [&hellip;] I suppose you  could even say that my poem, in some respects, attempts to retranslate back (i.e.  both &lsquo;honour&rsquo; and&nbsp; &lsquo;give back&rsquo;) the &lsquo;open  secret&rsquo; of physicality redolent in this epigraph.&rdquo; The entire line by Seferis  reads as follows: &ldquo;&Sigma;&phi;&upsilon;&rho;&#943;&zeta;&omicron;&upsilon;&nu; &tau;&alpha; &kappa;&alpha;&rho;&#940;&beta;&iota;&alpha; &tau;&#974;&rho;&alpha; &pi;&omicron;&upsilon; &beta;&rho;&alpha;&delta;&iota;&#940;&zeta;&epsilon;&iota; &sigma;&tau;&omicron;&nu; &Pi;&epsilon;&iota;&rho;&alpha;&iota;&#940;,&rdquo; which is  transliterated as &ldquo;Sfir&iacute;zoun ta kar&aacute;via t&oacute;ra pou vrathi&aacute;zei ston Pieirai&aacute;&rdquo;  &ndash;&ldquo;The ships hoot now that dusk falls on Piraeus.&rdquo; (&lsquo;In the manner of G.  S.&rsquo;,&nbsp; Seferis 1982: 110-111).</p>
              </div>
              <div id="edn11">
                <p><a href="#_ednref11" name="_edn11" title="">11.</a>&nbsp;&nbsp;This is  especially so in the translation, because in Greek all nouns are  gender-specific &ndash; most either masculine or feminine, with a smaller number that  are neuter. Thus, when one is translating out of English, gender  differentiation sometimes accounts for unexpected results in terms of meaning:  for example, the &ldquo;[k]ing sun&rdquo; is male, the city is female, and &ldquo;darling evening&rdquo;  is female. This means that the narrator&rsquo;s enamoured adoration of these elements  can unexpectedly vary hints of heterosexual or unidirectional attraction. Roman  Jakobson, among others, has commented on the poetic implications and  mythological connections bound to the gender of inanimate nouns (Jakobson 1992:  149-51).</p>
              </div>
              <div id="edn12">
                <p><a href="#_ednref12" name="_edn12" title="">12.</a>&nbsp;&nbsp;For a  discussion of statues in Seferis&rsquo; poetry, see Beaton 1991: 46-49.</p>
              </div>
              <div id="edn13">
                <p><a href="#_ednref13" name="_edn13" title="">13.</a>&nbsp;&nbsp;&lsquo;Cicadas  (I)&rsquo; finishes with the couplet &ldquo;[t]hey are hollowing a cave out of these night  covered hills/ and they will hole us up in it, until we drown in darkness&rdquo; (Berengarten [1]: 162).</p>
              </div>
              <div id="edn14">
                <p><a href="#_ednref14" name="_edn14" title="">14.</a>&nbsp;&nbsp;&lsquo;Cicadas&rsquo;  is the grammatical subject of a string of verbs: &ldquo;they groan like the dead&rdquo;,  &ldquo;they whine like the unborn outside my window&rdquo;, &ldquo;hover over the surrounding  hills&rdquo;, &ldquo;argue my destiny&rdquo;, [are] &ldquo;creaking under the snow&rdquo;, &ldquo;breaking up  glaciers&rdquo;, &ldquo;roped like slaves, heaving slabs of silence into pyramids of music  to celebrate a pharaoh across deserts on the ocean&rsquo;s chilly floor&rdquo; (ibid:  171-172).</p>
              </div>
              <div id="edn15">
                <p><a href="#_ednref15" name="_edn15" title="">15.</a>&nbsp;&nbsp;In an early poem, &lsquo;Guest&rsquo;, we read: &ldquo;He said he had opened himself to the  light, / that the light was a poem, was everywhere presence, / a silent  language with its grammar of waves and particles / of which our speeches were  dialects [&hellip;]&rdquo; (Burns 1980: 21).</p>
              </div>
              <div id="edn16">
                <p><a href="#_ednref16" name="_edn16" title="">16.</a>&nbsp;&nbsp;Elsewhere, I  have discussed the clear deviation of Nasos Vayenas,<strong> </strong>who reinstates  syntactical order by omitting the comma in the lines &ldquo;[a]ngelic and black,  light&hellip;/ Angelic and black, day&rdquo;, the epigraph of Berengarten&rsquo;s &lsquo;In Memory of  George Seferis (I)&rsquo; (Berengarten [1]: 153), as a mark of &ldquo;a predominantly <em>native</em> experience of the Greek light&rdquo;, perhaps even of&nbsp;  &ldquo;<em>Seferis&rsquo; verses</em>&rdquo;(Filippakopoulou 2005: 50).</p>
              </div>
              <div id="edn17">
                <p><a href="#_ednref17" name="_edn17" title="">17.</a>&nbsp;&nbsp;&lsquo;Radiance,  palpable. In memory of Ilias Layios&rsquo; (sic), <a href="http://www.richardburns.eu/site/From_Notness.html">http://www.richardburns.eu/site/From_Notness.html</a>.</p>
              </div>
          </div>            <P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
