<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <title>Marcelo Cohen, Extravio  &raquo; Interlitq</title>
  <meta http-equiv="Content-Type"
 content="text/html; charset=UTF-8">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
window.open(theURL,winName,features);
}
//-->
  </script>
  <link href="../../estilos.css" rel="stylesheet" type="text/css">
  </style>
</head>
<body>
<?php include("../../headernew.php"); ?>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr>
      <td align="right" valign="top" width="10%"><?php include("../../issue13-2/menu_issue13-2.php"); ?>
      <div align="right"></div>
      </td>
      <td valign="top" width="90%">
      <table bgcolor="#ffffff" border="0" cellpadding="0"
 cellspacing="0" width="679">
<!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tbody>
          <tr>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="10"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="192"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="17"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="205"></td>
            <td valign="top"><img src="/images/spacer.gif" alt=""
 border="0" height="1" width="239"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="16"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="1"></td>
          </tr>
          <tr>
            <td><img name="home_r1_c1" src="../../images/spacer.gif"
 alt="" border="0" height="59" width="10"></td>
            <td colspan="4"><img src="../../images/spacer.gif" alt=""
 name="home_r1_c2" class="link1" border="0" height="59" width="653"></td>
            <td>&nbsp;</td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="59" width="1"></td>
          </tr>
          <tr>
            <td rowspan="4"><img name="home_r2_c1"
 src="../../images/spacer.gif" alt="Click to enlarge picture"
 title="Click to enlarge picture" border="0" height="391" width="10"></td>
            <td rowspan="2" valign="top"><a href="#"
 onmouseup="MM_openBrWindow('artwork.html','','width=360,height=500')"><img
 src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2"
 border="0" height="242" width="192"></a></td>
            <td rowspan="2"><img name="home_r2_c3"
 src="../../images/home_img/home_r2_c3.gif" alt="" border="0"
 height="242" width="17"></td>
            <td colspan="2" class="titulo2" valign="top">Extravio <span
 class="texto2">by <a href="bio.php"
 class="link3">Marcelo Cohen</a></span></td>
            <td>&nbsp;</td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="23" width="1"></td>
          </tr>
          <tr>
            <td colspan="2" class="texto2" height="219" valign="top">
            &nbsp;<br>
            <p>- Una exploración de la lectura en los transportes públicos.</p>
            </td>
            <td rowspan="3"><img name="home_r3_c6"
 src="../../images/spacer.gif" alt="" border="0" height="368" width="16"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="219" width="1"></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="2" class="texto2" valign="top">
            <br>
            
             
           
            <p> Diez de la mañana de un subtropical enero porteño. En el barrio de Agronomía, cinco cabras pastan en el predio de la Facultad de Veterinaria; la fachada de la asociación <em>Bienestar</em> ofrece ayuda contra la bulimia, la anorexia, la depresión y las adicciones. Dentro del colectivo 113, mecidas por un rondó de amortiguadores, gentes de edad van a hacer trámites o llevar análisis al médico. Más adelante, afuera, el popurrí arquitectónico de la calle Bolivia aglomera épocas; en el colectivo sólo es el tiempo absorto de los mayores. Los viejos de esta época se han acostumbrado a aburrirse. Cuando en Plaza Flores bajo con la mayoría, en todo el viaje no he visto a nadie leyendo, ni un mínimo indicio de lo que buscaba. Aunque es cierto que principalmente buscaba mirar. </p>
            <p> Hace un mes el muchacho que fumiga mi casa me contó que en el 113 había visto a un hombre leyendo un libro mío, pero que estaba en francés. Lo veo muy difícil, dijo mi coqueto escepticismo, ¿vos  cómo…? Porque en la tapa usted figuraba como <em>Marcel Cohen</em>. Es otra persona, le expliqué. Él se encogió de hombros. </p>
            <p> En el 113 podría terminar ahora la excursión. Pero mi amigo A. N., pequeño empresario que lee mucho y usa con entusiasmo el transporte público, me ha dicho que él también vio <em>al hombre del libro de Cohen</em>, bajándose en la estación Agüero de la línea D de subterráneo y alcanzó a captar que el título tenía la palabra <em>Garde</em>. Por eso, aunque entre los dos datos no se adivina la menor pauta, unos días después salgo a explorar de todos modos, al tuntún, como ejercicio espiritual de capricho, para alentar la ilusión de averiguar quién lee hoy en los transportes, ridiculizar el supuesto de que los pasajeros no leen, purgar de patetismo la constatación de que casi no leen, encontrar que ya ni se divierten con el celular (porque los celulares con más aplicaciones son caros), y también como reparación. Pero pronto algo me desboca: el hombre que lee a MC se vuelve legendario, y enlaza con otras leyendas urbanas, y todos los viajes por el plano de la ciudad y los arrabales son un viaje en presente continuo. Es lo que pretendía. </p>
            <p> Porque yo sé quién es Marcel Cohen, y le debo una reverencia. No a Marcel Cohen el erudito en lenguas semíticas que murió en 1974, sino al escritor que nació en 1939 en un suburbio de París, hace periodismo con seudónimo y escribe poemas, novelas y unos conjuntos de relatos de argumento esencial y matices contenidos, a veces puras secuencias de gestos, diálogos breves o detalles materiales que delatan una ligazón íntima entre tragedia privada y aberraciones de la civilización. El último año del siglo XX, después de que José Angel Valente me desayunara con que Cohen existía y me recomendara sus conversaciones con Edmond Jabes, logré hacerme con tres títulos de él. De <em>Assasinat d&rsquo;un garde</em> tengo anotados los catorce cuentos; son narraciones   intempestivas, sin trama ni final, punzados por un atisbo de sentido que al instante se desvanece. Que Cohen hubiera publicado unas cartas al pintor Antonio Saura escritas en judeo-español ya podía considerarse una señal, siendo que parte de mi familia paterna era sefardita. Pero además la contratapa de la edición de Gallimard de la  novela <em>Faits, II</em>, decía que la narrativa de Cohen combina la autosupresión del autor y una avidez inhabitual por mirar las cosas del mundo. Eso era muy promisorio; podía ser el inicio de una conversación. <em>Monsieur Cohen, me llamo MC, soy un escritor argentino y, sin ánimo de molestar…</em> Incluso proyecté una crónica del encuentro con introspecciones sobre el egoismo literario, el miedo especular, la competencia, y la disolución de todo en la infinitud real del diálogo. Patrañas. En 2000 estuve en París y, a punto de discar, vergüenza y escrúpulos me hicieron retroceder, como si una bienvenida cortés de Cohen pudiese realzar mi insignificancia en el mundo de la literatura. Etcétera. Pero apurémonos a evitar recriminaciones sórdidas. La secuela que importa es esta excursión al mundo del transporte ciudadano. </p>
            <p> De modo que acá estoy, por ahí. En el 188 que va de Mataderos a Boedo una muchacha embarazada, maquilladísima y perpleja lee <em>Mujeres que aman demasiado </em>como preguntándose si una de las consecuencias del amor excesivo será el embarazo. </p>
            <p> Y ahora un vagón del ferrocarril Sarmiento. Carteles institucionales de tests de SIDA son la única publicidad. A muchos asientos de plástico les han arrancado los acolchados vinílicos; los expuestos mecanismos de las puertas muestran una roña fétida. Por rendijas perpetuas entra una humedad lamedora. El gentío experto ha desarrollado un bamboleo antisacudones que lo preserva de derrumbarse. Uno de los cien hombres del vagón lee el <em>Olé</em>, otro las páginas deportivas de <em>Crónica. </em>Doblada sobre fotocopias de geografía, una muchacha subraya con un afán de conocimiento que emociona. En los andenes de Paso del Rey, carteles de <em>Vossosparte. org</em> urgen a mandar los hijos a la escuela. Gorras de béisbol,  camisetas de fútbol, vestidos de taller clandestino, falsas zapatillas de marca. Más allá, en el furgón, nerviosos primitivos urbanos fuman sin pausa, pero entre los trabajadores, cuentapropistas y desposeídos del vagón, entre las caras andinas, guaraníes, bálticas bajo ondas estiradas por la planchita, cabelleras opulentas o jopitos oxigenados, lo común es una expresión exhausta de pensamientos, dura en una tierra de nada entre el interior y el afuera. Un matrimonio pulcro cambia los pañales de un bebé y acomoda tuppers, talco, biberón, cerealitas y fruta en bolsos forrados de diario viejo; la mamá ordena unos apuntes de decoración de repostería. La fotocopia es la gran candidata al trofeo a lo Unico Leído. Se venden combos de revistas <em>Pronto</em> y <em>Sopa de Letras </em>del año pasado. Cuando vuelvo al atardecer,  del Oeste suburbano hacia la capital viaja otra población: empleados de Bingo, vigilantes nocturnos, jóvenes de paseo, usuarios de espectáculos con descuento de miércoles. Una mujer de trenzas y bolso vintage salta de su melancolía para atender el celular, pone cara de Sos de no creer, corta y destroza los pronósticos sumergiéndose en <em>Los 101 inventos que cambiaron el mundo</em>. Una señorita de perfume alimonado lee <em>Para ti.</em> Hay un arco de ocho o nueve modelos de actitud. Cada actor se desempeña en su vida cotidiana como si fuera un show-realidad y el tedio sumara puntos para la final. Pero es curioso: un hombre con bigotes de luchador turco y un estuche de trompeta lee a Elmore Leonard, y de la cara concentrada una máscara resbala dejando a la vista otra, inclasificable. </p>
            <p> Maniáticamente yo cargo con mi lectura: <em>Vida y destino, </em>de Vasili Grossman, una novela monumental en varios sentidos. Voy por la página 357, donde un soldado antiestalinista –que morirá en la batalla de Stalingrado— reivindica el humanismo Chejov: &ldquo;Dejemos de lado las grandes ideas progresistas; seamos buenos y atentos para con el hombre, sea obispo, enterrador, magnate industrial, preso o camarero.&rdquo; Finjo leer. En la estación Medalla Milagrosa del subte E, un muchacho alto y desgarbado me otea con curiosidad. Brazos tatuados como telas del Bosco; pelo revuelto con esmero: este debería leer. Pero no: dirige toda la rebeldía contra el extendido vicio de clasificar por las apariencias. Y sin embargo, ¿en qué otra cosa consiste la individuación posible? Definirse. Distinguirse. Las superficies corporales hablan: dieta cárnica// yogures y ensaladas// pizza de Huggis con Fanta/ milanesa con chop. También la indumentaria:  bolso proletario de lona, maletín de escribanía, cartera con broches dorados, mochila Addidas, morral de bohemio. ¿Se deduce algo de esta diversidad? Mmm… Desde Constitución hasta Retiro en el subtre C, pasando por el obelisco, pocas apariencias sugieren certeramente qué se inclina a leer un individuo; y menos signos ofrecen de que se lea en absoluto, como si, igual que en las colas de los bancos o la sala de espera del urólogo, el desvelo excluyente fuese llegar, no distraerse del avance, y el viaje urbano la mera calamidad de trasladarse. ¿Y puede haber otro desvelo? </p>
            <p> Desde los paneles corredizos de la cultura parpadean las atracciones. Una de las sensaciones del verano es la fantasía de reformar nuestra humanidad desnaturalizada en las selvas 3D de <em>Avatar</em>. En la Web triunfa la nueva publicidad de Addidas, con aportes de Calle 13 y DJ Neil Armstrong. En Mar del Plata, ¡1500 personas! escuchan al  &ldquo;periodista&rdquo; Luis Majul disertar sobre su libro sobre Kirchner. Nimiedades. Un verdadero hit es el terremoto de Haití, visto por la tele, con su advertencia de que la naturaleza también puede bestializarnos. El otro hit es la muerte de Sandro, un recordatorio de nuestra condición real demasiado obvio ser atendido. En cambio el mismo mensaje es insoslayable si suena en el transporte público, porque se expresa en el cansancio. <em>Así </em>es la naturaleza humana: la acumulación despiadada de fatiga esclerosa el cerebro. Pero el viaje rutinario ¿no podría enseñarnos a asimilar dignamente el paso del tiempo? </p>
            <p> &ldquo;¡Esto es muy raro!&rdquo;, truena el electrizado dependiente del quiosco de prensa de la estación Pueyrredón del subte B, un medio muy pluriclasista. &ldquo;Vendo treinta <em>Olés</em> una mañana cualquiera, pero a lo mejor gana Boca y no vendo ninguno; y sin embargo acá vendo <em>Clío</em>, <em>Sudestada</em>, <em>National Geographic</em>, <em>Rolling Stone, Barcelona, </em>¡vendo revistas de arquitectura, de alimentación y de poesía! ¡Quién sabe lo que se le antoja leer a la gente!&rdquo; El quiosquero de la estación del Once informa que de las 650.000 personas que cruzan el vestíbulo cada día, unas 100 compran el <em>Clarín</em> (por los anuncios clasificados) y  30, Diario Popular. <em>Inrrockuptibles</em> por mes son su orgullo, y 20 <em>Muy Interesante</em>. A ras del suelo vuelan migas de pan de queso y hojas de los diarios que se regalan. </p>
            <p> Ferrocarril Urquiza. En el tren que va General Lemos un heladero manco y jovial pelea por el espacio con un vendedor de música pirateada (Dyango, Música Cristiana, Valeria Lynch), mientras al otro lado de la ventana, desde un cuidado muro de la estación F. Beiró, un misterioso retrato de Dante Alighieri frunce el ceño sobre un fondo azul de ochava porteña de 1930. El tiempo se descoyunta. Peones de construcción procuran no derrumbarse mientras mi compañera de asiento se cala unos lentes, en preparativo alentador, pero saca un móvil y no para de hacer llamados que redundan en información sobre su ruta. Un técnico con el overall azul  de Metrovías se debate por mantener desdoblada a una hoja de prensa con un artículo: &ldquo;La construcción de la historia&rdquo;. Colgado de una anilla, un hombre demacrado, de rasgos suaves y portafolios, le habla de <em>Un mundo feliz </em>a su hija adolescente; admite que lo leyó hace años, cuando tenía tiempo, lo que no consterna a la chica. En este padre se resume el folletín de una clase media desbarrancada, tensa hasta el agotamiento entre los deberes de no limitarse más, mantener una leyenda que alcanzó ribetes mundiales --la <em>cultura </em>de los argentinos, ¡su facilidad de palabra!— y seguir creyendo que ser culto es condición de humanismo. Lástima que ahora, obsesionados por las arritmias de la economía, ahogados en trabajo para sostener la mínima <em>posición</em> que les queda, estafados, incómodos con sus veleidades, su desinformación y su consumismo, los pequeños burgueses argentinos se rinden: mientras sus hijos atienden facebooks, ellos descansan en el volumen de  espíritu que acumularon cuando les iba mejor y lo administran como si fuera dólares. En toda la mente globalizada subsiste la noción filistea de que los males sólo se soportan duplicando el esfuerzo. Para esta moral los intervalos son abismos. </p>
            <p> Pero atención: <em>siempre alguien lee</em>. (Incluso tal vez a Marcel Cohen.) En el 109, por Villa del Parque, una bronceada pero ojerosa médica, con el estetoscopio por collar, ve que la miro cerrar un Murakami (<em>Mi chica sputnik</em>), me indaga la cara y dice: ¿Le gusta este autor?; yo de él ya me leí tres. Qué expresión fabulosa <em>Me leí Tal Libro</em>: indica posesión, ingestión (<em>Me lo tragué</em>). Orgullo heroico de mejoramiento. Acumulación: contabilidad, yendo a lo peor. Pero también expresa la calidez de leerse a uno mismo como a un compañero o un amante. La doctora, que viene de hacer guardia en un hospital y va a buscar a sus tres hijos a la escuela, acepta sestear unos minutos como parte del gusto de leer en el colectivo. Murakami se le mete en los sueños. Toca el libro: Acá hay una chica japonesa se va a pasear en una isla griega y se hace humo; no la encuentran nuun-ca más; lo que me encanta de este hombre es que de golpe cosas re-inexplicables y cosas reales son la misma realidad; pero yo igual termino durmiéndome.&rdquo; </p>
            <p> A las siete de la tarde varios duermen en el tren Roca que va a Glew. Vidrios sucios de sustancias pardas, tornasoladas. Suelo pringoso. La tos de un vendedor de calcetines salpica sin dar frescor. ¿Cómo no es inconcebible que tantos viajen todos los días hacinados en estos cascajos inmundos sin sublevarse más que a veces por una demora ultrajante? Maltrato, desdén: en la división de clases del transporte ciudadano se condensa una desigualdad monstruosa. Pero no es que haya dos Buenos Aires, una más o menos holgada, perseverante en el consumo cultural, y otra anonadada y rencorosa. No. Rencor, miseria y locura nos impregnan a todos en una sola ciudad donde el tono de la vida es chillón, un desvarío del cual sólo nos despabilamos en el umbral de la muerte.	La línea A, que pasa por varios barrios de comerciantes y profesionales de posición estándar, es la apoteosis de la renuncia a la religión de la cultura. En los vetustos vagones enmaderados se distinguen algunas netbooks, una revista <em>Noticias </em>y un ejemplar de <em>L&rsquo;étranger</em> (¡epa!) para la clase de francés. Nada más. Si no leen estos, uno se pregunta quién cuerno lee. </p>
            <p> También se pregunta si un lector es realmente una criatura tan peculiar. </p>
            <p> El enemigo no es Internet sino la ansiedad. Como leer implica estar quieto, se requiere cierta inclinación personal: quizá una facilidad para descubrir que la lectura constante da  un creciente plus de paciencia. El productor de paciencia de los libros es un placer que no todos indentifican pronto como tal. Pero hasta el lector ansioso termina desarrollando un tipo de paciencia que, si bien tiene muchas utilidades, básicamente es la paciencia necesaria para no desertar de un juego una vez se ha entrado por ganas de jugar. </p>
            <p> Jalonando grupos de moblocs, enclenques arcos de fútbol asoman ente matorrales. De un lado de la vía hay un cementerio; del otro, un convoy de camiones recolectores espera ante el predio de Coordinación Ecológica del Area Metropolitana. Esto es el Bajo Flores, que el tranvía del Premetro cruza rasgando un tul de olor basura, bordeando la Villa 1-11-14. Viajan varones de pelo oxigenado, muchachas de pollera de jean y zapatillas Sigma: el estilo básico del trabajador en negro. En el clima mental promedio que se obtendría desde esta escasez hasta el lujo de la Recoleta, ¿qué debería ser la cultura? ¿Solaz, conocimiento, agitación, vitamina para la sensibilidad? El chico que acaba de sentarse a mi lado, mochila Revvons y perla en el lóbulo, se centra en una fotocopia muy subrayada donde descuella la cara borrosa de Max Weber. Le pregunto si le entusiasma. Mmm, son apuntes de sociología pero él estudia económicas, informa de reojo, y no me mira más ni contesta las llamadas del celular aunque la cumbia del ring-tone suene y suene. </p>
            <p> Las nociones estatales de cultura son ciegas, aluvionales. Hoy en el diario se anuncia el estreno de <em>El principito</em> en el Planetario, la apertura de <em>Polo Circo</em> en Constitución, conciertos de Música Urbana en la Costanera Sur, lecturas de poesía en el Botánico, la pieza <em>Amores de tango</em> en la plazoleta San Martín de Tours, clases de murga y bailes africanos en el inefable Pabellón del Bicentenario y una ensañada de cientos de dádivas más con que el gobierno de la ciudad cumple estimula el desahogo sensible y el disfrute veraniego –<em>la cultura respira</em>—, pasa por caja electoral y se queda orondo. </p>
            <p> En el baño de la estación Haedo un gendarme le pide el diario al proveedor de jabón, que le advierte que no lo use para limpiarse. El gendarme se enterará de una denuncia que hacen hoy las tres grandes editoriales del país: en balnearias del país circulan copias piratas, no sólo de grandes ventas como <em>El combustible espiritual, </em>sino de títulos de Saramago y Cortázar. La noticia de que vale la pena embarcarse en una piratería que sólo abarca el cinco por ciento de las ediciones del país parece iluminar toda la realidad. En el tren Mitre que va a Tigre un señor de cabeza titánica abre una bolsa de Farmacity, saca un alfajor y se lo come y vuelve a abrir la bolsa para sacar <em>Lord Jim. </em>A cinco metros, contra una puerta, una mujer se mordisquea plácida y minuciosamente las uñas como para mitigar la comezón que le provoca <em>El amante</em> (la novela de Duras; no la revista). </p>
            <p> Hay un cuento de M. John Harrison, <em>El don</em>, en que un desconocido, en un andén repleto, le regala al protagonista Peter Ebert un libro; casi se lo impone. Es un libro sin  tapas, con páginas faltantes y letradas borradas en el título de portadilla, que demasiadas  manos ha manchado de té, aceite, tinta, semen. Desde el momento en que lo acepta, a Ebert le entra la certeza de que <em>puede haber otra vida</em>, y de hecho la vida se le volverá a él una peregrinación irrefrenable, ruinosa, enloquecedora y fantásticamente vana en busca de un ejemplar completo o un dato esclarecedor. Y efectivamente: un gran enigma de la representación ilimitada en que vivimos es si los libros pueden transformar realmente la vida. ¿Cómo pone en movimiento un libro, qué reinicia o desvía, cómo coagula el titubeo y sella el destino ? ¿Cómo surje en alguien la literatura?</p>
            <p> En la estación Retiro compro <em>Critica</em>. Es lunes 25 de enero. El diario trae un poema en que un preso recién liberado siente el olor del asfalto como <em>una sobredosis de alegría en las arterias. </em>Lo escribió César González, que tiene 20 años y hace una semana obtuvo la condicional después de dos años en institutos de menores, y dos en los penales de Ezeiza y Marcos Paz, por delitos que cometió con una bandita de la villa Carlos Gardel de El Palomar. González dice que en la cárcel <em>perfeccionó las ansias de otra vida</em>, no porque el sistema penal esté diseñado para eso, sino porque el horror lo llevó a desear con mucha fuerza la libertad; pero lo que hizo otra vida posible fueron los libros. </p>
            <p> Consigo un número y llamo a César González. Es seguro, pausado, gráfico, cuida las palabras pero sin reprimirse y agradece que se interesen por él. Cuenta cómo llegó a comprender, no en una revelación sino por aumentos, que la casualidad y la voluntad trabajaban en cooperación. También que antes ya le venía sucediendo algo menos palpable, que había en él como un llamado: los libros lo <em>intrigaban</em>. Un perspicaz abogado de oficio le insistió en que leyera; él empezó por Bioy, fue pasando a otros, y en el cuarto instituto de menores ya se ocupaba de actualizar la biblioteca. <em>Hay mucha mentira sobre qué es estar en la realidad y qué no</em>. <em>Yo descubrí que se podía usar la cabeza para otras cosas; la mente es muy poderosa; a mí me salvó de la opresión de la rejas. Un nudo que tenía adentro se rompió en ramificaciones, en cadenas. Me dieron ganas de hacer algo que no propagara el mal. Pero en la cárcel es difícil rescatarse, porque existe un molde prestablecido para que un pibe no se rescate.</em> Cuando un amigo le dio a leer a Walsh, lo admiró que hubiera existido gente que daba la vida por algo mejor. <em>En el barrio te hacen creer que si no tenés la Nike o una pistola en la cintura no sos nada, pero a los pibes hay que demostrarles que la cosa no se termina a los 25 con un plomo de la yuta. En la cárcel, en la charlas de noche, yo siempre tiraba algo que hiciera pensar.</em> <em>Lo grande fue que al final me pedían que les leyera mis poemas. Ahora en esta velocidad ando medio desacomodado; las cosas en la villa están peor y es jodido no tener un mango en el bolsillo, pero ahora discierno de otra manera. Voy a estudiar filosofía. </em></p>
            <p> Cadenas. Ramificaciones. ¿Los libros sacan la realidad de la cárcel ideológica del &ldquo;realismo&rdquo;? En mi cuenta virtual llevo un Douglas Preston (<em>Tiranosaurio</em>), un Sándor Marai, un Marcos Aguinis, dos Isabel Allendes, un Matilde Asensi, un Jung, un Bradbury y otros títutlos típicos de liberaría de viejo, un Dan Brown… Ningún otro best-seller, y <em>ningún libro de un narrador o un poeta argentino</em>. El operador sociológico que nos infiltra las conciencias no conseguirá que con esto arme una estadística. ¿Quién compra la friolera de libros que se publican? ¿Los que se mueven en coche? ¿Gente que se los llevan a la playa? Ahora, en un vagón del subte D entre Catedral y Palermo, veo como una muestra social uniforme pugna por encuadrarse en lo que se espera de ella. Desatildados, sudorosos administrativos, protobrokers y pasantes aguantan, y algunos se hacen espacio para la lectura, valor en sí. Una chica de ojos de menta lee a Kerouac. Una colérica trajeada <em>Nueve cuentos,</em> quizás porque<em> </em>esta semana murió Salinger. Carlos Fuentes. Laura Roberts. Banana Yashimoto. Literatura acá sólo leen mujeres, como si en efecto, según se estudió que ocurre desde hace siglos, las mujeres fueran la avanzada de la lectura, no como educación, no como alimento de fantasías, sino porque sí. </p>
            <p> Considerando la amplitud del desinterés por todo lo externo, el ideal de que todos los viajeros se ensimismen leyendo no es incuestionable; igual de bueno sería quizás que aprovecharan el viaje para charlar, escucharse, cambiar noticias, enriquecerse con las vidas de los demás. Sólo que, tal como estamos de expresión, todos los relatos se parecerían demasiado. En este punto regresa la abnegada doctora del 109: <em>Me leí tres libros de este autor. </em>No se trata de simple apropiación. Es como si el que <em>se lee un libro</em> se tragara un psicotrópico y, si <em>se lo lee </em>en un vehículo, el desplazamiento mental, sin dirección, se acoplara al momento de inercia del traslado; como si así se consumara la evasión de una realidad abusiva a lo imposible real, o a lo posible negado. </p>
            <p> Hace años ya que tengo <em>Galpa</em>, uno de mis tres libros de Marcel Cohen, colocado de frente en el anaquel correspondiente de la biblioteca: no sé si es un tributo supersticioso forzado por el remordimiento o un mal chiste. No hay una sola visita que lo haya notado.  Mañana voy a cortar la teatralidad y ponerlo de canto. </p>
            <p> Pero afuera la función no para. Ni a las dos de la tarde en el 42 que cruza Nueva Pompeya. Al lado mío, un criollo viejito, de leve camisa blanca, lee un Graham Greene, <em>El factor humano</em>. De pronto señala mi <em>Vida y destino</em>, y comenta que él leyó esta libro. Algo pesado para el colectivo, observo yo. Qué observación tonta, señor, sobre una novela tan lleno, no sé, de historia, guerra, familias, verdades, de sufrimiento; a ver ¿usted cómo lo describe? Yo me enderezo y declamo: Bueno, trata de la batalla de de Stalingrado, de los ecos en toda la Unión Soviética y de cómo Satlin aprovechó la victoria  sobre Hitler para liquidar el socialismo en la ideología mortífera del nacionalismo estatal. El se estira la barba canosa: Está muy bien; ¿y no le parece que el stalinismo es más misterioso que el nazismo? Me parece, sí; sobre todo si uno es de izquierda. Él golpea mi novela con un dedo; siento el temblor del cuerpo quebradizo. Murmura: Qué cosa, uno lee y ve cómo aumenta la montaña de lo que no supo. Una lección, digo. Ah, no, señor, no; yo con una novela no progreso; no me lleva a ningún lado. Sólo al rato le pregunto por qué lee. El deja pasar una cuadra, me toca el brazo y se tapa una risita: <em>Por eso</em>. </p>
            <p><BR>
            </p>
            <p><strong>Lecturas</strong></p>
            <p>Un callado acontecimiento del verano es la publicación de <em>La Biblioteca ideal </em>(La bestia equilátera) el libro en que Matías Serra Bradford hace una fenomenología narrativa de la pasión y la obsesiva ética lectora. Es una balada de la soberanía del lector, de su condición autárquica, recalcitrante, aguerridamente epicúrea; esta escandida en el infinito de detalles que hacen a esa forma de vida inflexible. Del libro de Serra Bradford se desprende que un lector solo es tal si es una excepción. </p>
            <p>El cuento de M. John Harrison está en <em>Preparativos de viaje</em>, Buenos Aires, Interzona, 2004, traducción de M. Cohen. Sobre figuras del lector (sobre todo la lectora) en la narrativa moderna, ver Nora Catelli, <em>Testimonios tangibles</em>, Barcelona, Anagrama, 2001. </p>
            <p><BR>
            </p>
            <p><BR>
            </p>
<p></p>
            </td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="46" width="1"></td>
          </tr>
          <tr>
            <td height="103"><img src="/images/spacer.gif" alt=""
 border="0" height="103" width="1"></td>
          </tr>
        </tbody>
      </table>
      </td>
    </tr>
  </tbody>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
