<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <title>The International
Literary Quarterly</title>
  <meta http-equiv="Content-Type" content="text/html;">
   <link href="../../estilos.css" rel="stylesheet" type="text/css">
</head>
<body style="background-color: rgb(255, 255, 255);">

<?php include("../../headernew.php"); ?>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody>
    <tr>
      <td align="right" valign="top" width="10%"><?php include("../../bio_menu_interviews.php"); ?>
      <div align="right"></div>
      </td>
      <td valign="top" width="90%">
      <table bgcolor="#ffffff" border="0" cellpadding="0"
 cellspacing="0" width="679">
<!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
<table border="0" cellpadding="0" cellspacing="0" width="100%">
 <tbody>
          <tr>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="10"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="192"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="17"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="205"></td>
            <td valign="top"><img src="/images/spacer.gif" alt=""
 border="0" height="1" width="239"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="16"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="1" width="1"></td>
          </tr>
          <tr>
            <td><img name="home_r1_c1" src="../../../../images/spacer.gif"
 alt="" border="0" height="59" width="10"></td>
            <td colspan="4"><img src="../../../../images/spacer.gif" alt=""
 name="home_r1_c2" class="link1" border="0" height="59" width="653"></td>
            <td>&nbsp;</td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="59" width="1"></td>
          </tr>
          
          
          <tr>
            
  <td rowspan="2" valign="top" width="240"><img
 src="daniel.jpg" name="home_r2_c2"
 border="0" height="212" width="200"><br>
 <small><br>Dan Gunn<br>
 <em>Photo by Louise Chester</em></small></td>
 
 
 
         
            
            <td colspan="2" class="titulo2" valign="top"><strong><em>Interlitq’s</em> “The Groves of Academe” series: </strong><br><br>

<strong>A Letter from <a href="http://interlitq.org/issue1/daniel_gunn/bio.php">Dan Gunn</a> to <a href="http://www.interlitq.org/staff/peter_robertson/bio.php">Peter Robertson</a>, Founder and President of <em>Interlitq</em></strong></td>

            <td>&nbsp;</td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="23" width="1"></td>
          </tr>
          <tr>
            <td colspan="2" class="texto2" height="219" valign="top">
            <p>&nbsp;</p>
            </td>
            <td rowspan="3"><img name="home_r3_c6"
 src="../../../../images/spacer.gif" alt="" border="0" height="368" width="16"></td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="219" width="1"></td>
          </tr>
          <tr>
            <td colspan="4" rowspan="2" class="texto2" valign="top">
           <p><br><br></p>



<br />
<p>Dear Peter,</p>

<p>You have asked us to point to the ideas that are “keys to our central intellectual concerns”. This being an eminently reasonable request, why do I find myself struggling to satisfy it in a properly direct and reasonable manner? </p>

<p>I believe the reason is that if I were to start out with a question such as “How to transmit the value of slow reading?” or “Who are the contemporary writers pushing the boundaries of the literary?” or even with a question a little more distant from my daily concerns such as “Why does Shakespeare turn towards the mythological in his late plays?” or “What are the continuities between a Dostoevsky, a Céline, a Louis-René des Forêts, and a Thomas Bernhard?” I would be distorting the way I work, which is rarely to begin with a question or idea. I wish I did have ideas! I’m fortunate to have clever colleagues who are brimming over with ideas whose richness and diversity never fail to impress me. I even think that I myself did once have some serviceable ones. But these days I seem more often to find myself in the position – the terms are barely adequate – of a <em>maker</em> than of a <em>thinker</em>. By this I mean that I rarely spend my days worrying over whether or not a concept is adequate. Usually, I am just trying to get something to work – a sentence (mine or another’s), a sequence (of texts, of images), an event, a book. Of course, for any of these to work, questions will have to be asked (and even answered), and ideas be mobilised; but for me this is usually secondary – and I think it is worth stating this at the outset. I suppose I could say that what interests and involves me are different sorts of <em>praxis</em>. But since that already sounds more abstract that I intended...</p>

<br />
<p><strong>1: IS ILLEGIBILITY PERMISSIBLE IN THE GROVES OF ACADEME?</strong></p>

<p>I have, for the past twenty-five years, been involved in preparing for publication the letters of Samuel Beckett, the fourth and final volume of which I am proofreading even now, and which will come out in September. As a part of this task, I have spent an inordinate amount of time staring at Samuel Beckett’s handwriting and trying, along with my co-editors and my friend Gérard Kahn (who has been giving us invaluable assistance), to decipher it. I could liken this process to meditation, in that it requires at one and the same time an acute attention to detail and a suspension of expectation. Attention to minutiae is required because Beckett’s handwriting is so wayward that one needs, in order to read a paragraph, to be drawing on every clue at one’s disposal (drawing on one’s experience too, of course). Much in the process of transcription is deduction: because the author has written these words up to this initially illegible word, and these other words after it, logic dictates that… As it happens, I’m currently learning to use my first smartphone, and because I am clumsy with the tiny keys, I find myself resorting to the predicted words that flash up as options. When one is transcribing, one tries to mimic the predictive function on a smartphone (only smarter). Yet even if necessary, to work this way with Beckett is fundamentally misguided, when what is required is a suspension of judgement that <em>prevents</em> one from leaping to what is expectable. Where the smartphone predicts the most likely word in any context, what Beckett often chooses is the <em>least</em> likely. And he does so in a language that is itself perilously unforeseeable. </p>

<p>On 24 March 1963, Beckett writes to his great friend the painter Avigdor Arikha, mentioning first a species of bird he has been observing on his lawn at Ussy-sur-Marne; in a new paragraph, he seeks to say something more general, beginning, “Oui, trop de main nuit, trop de tête aussi”– which is just about comprehensible when written to an artist who himself is in crisis about how to represent the world. Beckett goes on, less comprehensibly perhaps, but very much in his own vein: “trop de trop peu sans doute aussi, mais c’est par là la seule chance qui nous reste.” (In George Craig’s translation, this becomes: “Yes, too much hand does harm, too much head as well, no doubt too much too little does as well – but it’s our one remaining chance.”) In a further paragraph, Beckett continues: “Je ne fais rien. ….. ….., la tête à mille lieues. Ah si je pouvais ne plus jamais bouger.” (“I am doing nothing. ….. ….., my head miles away. Oh if only I could never make another move.”) If one knows French one can imagine pairs of words that could comfortably fit into the gaps I have represented by ellipses. We had several options and alternatives; but only, once the pressure was off and time slowed sufficiently, to discover that the missing words were “Drift about”. In English, in the middle of a sentence in the middle of a letter in French. </p>

<p>This brings me to what Beckett said to Harold Pinter, on 21 April 1969, having just read Pinter’s play <em>Silence</em>. “Dear Harold,” he writes, “Thank you for sending me <em>Silence</em>. I like it greatly, the writing so precarious and ….. .” What is on the page looks like “numbrous”, and has been transcribed by one Beckett scholar as “numerous”. But what on earth could it mean to say of Pinter’s writing that it is “numerous”. We thought of “umbrous”, which is a Beckett-like word but which doesn’t really fit the strokes on the page, then “cumbrous” – and so on. Only in the end to be defeated: here is one of the few places in the text of our Volume IV where we have been obliged to admit: “[illeg, 1 word]”. </p>

<p>Now, why does any of this matter, and what could it possibly have to do with whatever thoughts may, despite my initial asseverations to the contrary, be guiding my practice as an academic and writer? It matters because my inability to read this word hits against my awareness that there is a word present here: the promise of meaning has abruptly turned opaque, and is resisting me; rather than signification, I am forced to stare at ink-strokes on a page, almost as inscrutable as kanji. And this when it is the opacity of the world, the refusal of objects and others to be appropriated by meaning, that is at the heart of the project of the sort of writing that I am, in fiction at least, most drawn to. This starts, naturally, with Beckett’s own work, when so many of his protagonists are seeking sense in an obdurate or hermetically alien world, a world – and that includes their inner landscapes, of course, their “little worlds” – where words clearly matter (policemen use them to issue orders, as Molloy finds to his cost!) but where they refuse to yield up their riches in such as way as might generate any sense of a belonging-in-language. The failure of agency I am trying to describe here is one that is central to most of the fiction I return to and that I also choose to teach; indeed, again, I believe one of the roles of the literary is to remind us of the failure of human agency (which is not to say that I am drawn to anything approaching the “post-human”). </p>

<p>Even with a writer as prolix as Marcel Proust, whom Beckett read intensively and complainingly as a young man, and on whom he wrote his one sustained piece of literary criticism, it is the moments when words either betray a character or fail to achieve a purchase on the world, moments when intentionality fails, that are key to all the rest. The famous example of this is involuntary memory as illustrated in the episode with the <em>madeleine</em>. But this is just one example among legion that demonstrate how it is not in moments of conscious control or in the exercise of will (ambition, drive, ratiocination: traditional mainstays of plot in fiction) that something approaching the truth emerges. When teaching <em>A la recherche</em>, I linger over the way in which that great inveigher against snobbery, Monsieur Legrandin, is himself revealed to be the consummate snob. Proust releases the revelation subtly and incrementally, with a wonderful description of how something in Legrandin’s pupils gives away the fact of his snobbery – a snobbery of which he may himself be unaware. And then comes that hilarious description of how his undulating buttocks when he is in the presence of a member of the gentry reveal the incontrovertible fact that he is indeed a snob. Proust writes (in Lydia Davis’s translation):<br><Br>

<blockquote>he made a deep bow with a secondary recoil that brought his back sharply up past its starting position and that must have been taught him by the husband of his sister, Mme de Cambremer. This rapid straightening caused Legrandin’s bottom, which had not supposed was so fleshy, to flow back in a sort of ardent muscular wave; and I do not know why that undulation of pure matter, that quite fleshly billow, with no expression of spirituality and whipped into a storm by a fully contemptible alacrity, suddenly awakened in my mind the possibility of a Legrandin quite different from the one we knew.</blockquote>

I am lumping together too many elements here: my attempt to stay close to the twists and turns of Beckett’s (hand)writing and the particular sort of attention, both informed and free-floating, thoroughly trained and yet almost naïve, that reading his hand requires; the refusal of the material world to render itself up as meaning, and how literature may – if rather paradoxically, given that it functions in language – make a reader aware of this; the failure of human agency more generally, and the ways in which writing can reveal us not to be masters of our own destinies or worlds, not even of our own most intimate bodily motions; a notion of truth that is not reducible (or inflatable) to a concept, is relational, cannot be recycled, a notion that would lead the psychoanalyst Jacques Lacan to announce that “on ne peut pas dire le vrai sur le vrai” (“one cannot tell the truth about the truth”). And I am intimating that all of the above is to be lived not intellectually – or not only intellectually – but as daily practice; as, even, a <em>discipline</em> – and in the several senses of that word <em>discipline</em>.</p>

<p>None of which offers me any sort of reassurance or assistance when I am determined to keep illegibility out of my own personal academic grove by figuring out what Beckett wrote to Pinter. Knowing that I am in some sense within a Beckettian dilemma is scant consolation when I am aware that students and scholars for years to come will be reading Beckett’s letters in our transcriptions, and will be attempting to illuminate their understanding of Beckett through what we have deciphered. </p>

<p>Which leads me to:</p>

<br />
<p><strong>2: DOES FIDELITY HAVE A PLACE IN THE GROVES OF ACADEME?</strong> </p>

<p>In his entertaining book about translation and translation theory, <em>Is That a Fish in Your Ear</em>, David Bellos explores the history of the relationship between translation and betrayal, a history that has often been invoked in shorthand through the pair of cognate words, “traduttore/traditore”. His purpose in doing this is partly to show how this idea, that to be a translator is to risk becoming a traitor, if it once had currency, is now redundant or irrelevant; what he wishes to do, in keeping with the genial-Englishman tone of his book, is to remove the element of sacrifice, what I might call the “tragic dimension”, from the task of the translator. For me, this move is seriously wrong-headed – or wrong-<em>hearted</em> perhaps – because the element of sacrifice, of betrayal (or the potential for betrayal), is as relevant today as it ever has been. </p>

<p>(Even as I note this down, in the back of my mind I hear other words – other words written by Lydia Davis, from the opening story of her 2007 collection <em>Varieties of Disturbance</em>, in which the narrator visits her ninety-four-year-old mother in a nursing home and believes she has been flirting “with a man from her past who is not Father.” The story ends: “How can there be improper relations with a woman of ninety-four? Yet my confusion must be this: though her body is old, her capacity for betrayal is still young and fresh.”) </p>

<p>When I am faced with a Beckett word that is resisting transcription, I am ultra-aware of my capacity for betrayal, and this awareness extends from this most basic of “translations” (from the handwritten page to the type of a Cambridge University Press book which will come on with all the authority of institutional history and academic propriety) to my larger misgivings about what it is to “translate” the letters of a very private man into a series of books that casually interested readers may offer as a Christmas gift.</p>

<p>There are several steps or stages involved in producing a large edition such as ours: gathering, selecting, transcribing, translating, annotating, publishing, to name only the chief ones. In these, each of which I consider to involve or require a translation, there is embedded the possibility, indeed the very strong likelihood, of betrayal. One question I therefore need to ask myself, on a daily basis: Is the mourning I am doing for what I had imagined might be different (for “different” read “better”) truly necessary, or have I simply not been working hard or intelligently enough? This is a question which, in one form or another, most serious literary translators will ask themselves, even as they cajole themselves onwards with the most obvious answer – that they are not being paid sufficiently to break their heads over such fine distinctions. </p>

<p>My own way of thinking about these issues is oriented less by translation theory than by psychoanalysis; this will be no surprise to those who know my work, given that psychoanalysis has oriented my thinking – and not just my thinking – ever since I was an undergraduate. Though he comes at it from a rather different angle, Proust is often fascinated by precisely what fascinated Freud: the ways in which the unconscious erupts into everyday life, often to the great embarrassment of the person through whom it is making itself manifest. Any reader who has got that far in the novel will be likely to recollect that amazing moment when Albertine, attempting to assuage the jealousy of the obsessive narrator of the novel who has rendered her a virtual prisoner, catastrophically gives herself and her lesbian inclinations away by her use of the term “me faire casser…” (which the narrator completes with “le pot”) – words which escape from her rather as Legrandin’s buttocks ripple, emanations of a truth that will not be hidden – a <em>parapraxis</em> in Freud’s terms. When it comes to what I’ve been trying to say about translation, the <em>mourning</em> I have already mentioned relates, obviously, to <em>castration</em>. For me, to be a translator (as I consider myself to be when I am editing almost as much as when I am moving words from one language into another) means mourning a completeness that was not quite achieved; hoping that next time will be different; and learning from this and refusing to learn from this. I would not want it otherwise, would not want to inhabit the cheery world of David Bellos’s un-complexed translators for whom loss is merely an inevitability to be shrugged off along with life’s other vicissitudes. </p>

<p>In the very last year of his life, in 1989 – to give another little insight into our Volume IV – Beckett continues to devote his flagging energies to translation. “Trying half-brainedly to translate <em>Stirrings Still</em>,” he writes to his friend the actor and former convict Rick Cluchey: “Loss at every twitch.” He is eighty-two years old and has every entitlement to be considered one of the greatest translators of the twentieth century. He is, what is more, working on a text that he might be said to have authored. Yet this is how he experiences its passage into the language, French, in which he wrote most of his own major work: “Loss at every twitch”. Within which loss there is of course a betrayal (or a castration), and in the face of which loss there is the necessity of mourning – doubly so given that the work itself is, like so much of late Beckett, already wrapped around a core of mourning.</p>

<p>I have mentioned the “gathering” of the letters as an initial stage, by which term I might seem to be implying a process as neutral as the gathering of refuse or of leaves (analogies which, I realise, having noted them down, are less neutral than intended, both containing their own Beckettian echoes). The reality is that this process has been anything but neutral, and has required those who were in possession of letters written to them (or their children, since sometimes the letters had passed down to the next generation) to face the question head on of whether or not it is a betrayal of Samuel Beckett, to share his letters with editors who are seeking to publish them. The question is one posed most famously by Kafka’s injunction to Max Brod that he dispose of much of his literary remains without allowing public access to them. What is fidelity and what betrayal, if one is in Brod’s situation – a situation, as we discovered, much less rare than one might imagine? Exacerbating the issue for us editors was unquestionably the fact that Beckett, while a very sociable man – much more sociable than popular myth suggests, in no sense a hermit – was also a very private man, in that he tried hard to avoid having dealings with the media. He was, indeed, the antithesis of the sort of attention-seeking, celebrity-hounding individual so much on public view today, even in the literary world; knowing this, his friends, lovers, confidantes, had to decide if releasing his letters was an act of fidelity – usually they were aware of how remarkable these letters could be, and of how interesting they would surely be to enthusiasts and scholars of Beckett’s work – or an act of betrayal. Adding further to the complexity was the fact that Beckett’s own attitude changed over the course of his life: initially horrified at the idea of his private correspondence being made public, by the end of his life he had come to accept that this would happen one way or another, and preferred that it be done in a scrupulous manner. Not irrelevant also was an awareness, shared among those of Beckett’s inner circle, that Jérôme Lindon, his literary executor, was largely hostile to the project of publishing the letters of Les Editions de Minuit’s most important author. </p>

<p>Perhaps it is again by way of an anecdote that I can best illustrate how thoroughly un-abstract this issue of fidelity/betrayal has been for me. I recall with some trepidation being seated at the dining-room table of Avigdor Arikha and his wife Anne Atik, seven years ago, while I was being assessed, while the decision was being made of whether or not Beckett’s voluminous correspondence with the couple would be opened up to us. Decades earlier, my fellow editors had made an approach and been rebuffed. Through Anne I had managed, after several failed attempts, finally to be received by Avigdor. He was not one, to put it at its mildest, to suffer fools gladly; everyone I have met who knew him – and this includes preeminent art historians and museum curators – went in awe of the breadth of his knowledge, his strong views, his highly demanding intelligence. Samuel Beckett, he made it clear to me, had been the single most important influence in his life. He was not about to do anything that he thought would contravene Beckett’s wishes or be detrimental to his reputation as a writer….</p>

<p>We were conversing in French, and I was dimly aware that this was partly because my competence in that language was being assessed (it was one of the seven languages Avigdor spoke, as I later learned – he and Beckett chatted most commonly in German). After an hour or so, Avigdor invited me through to his study and placed before me a large folder, beautifully organised and presented, containing his more than 300 letters from Beckett. He invited me to look through it, which I duly and admiringly did. I then rose to leave, at which point he asked me when I would be coming to scan them. This took me by surprise, as I was sure I had failed the test and that he had decided not to share his collection. One year later, when we had got to know each other better, I returned to this moment, and asked him what had brought him to his decision. “It took me five minutes to decide I could trust you,” he told me – we were speaking English by then – “and when I decide something I do so fast and do not change my mind.”</p>

<p>This – <em>trust</em> – is the term I have been withholding, which ensures that not <em>all</em> need be betrayal and loss. When collecting copies of the letters from Beckett’s friends, what needed to be established were terms of trust which ensured that the unavoidable sense of betrayal – after all, these were letters written to this particular person, not to some larger public – became tolerable: trust that they would be put to good use, trust that the reputation of Samuel Beckett would only be enhanced by their circulation. This notion of trust, wonderfully explored by Gabriel Josipovici in his 1999 book entitled <em>On Trust: Art and the Temptations of Suspicion</em> – a book I much admire – is not one that has much currency in artistic or academic spheres today, where faith in tradition has withered, where originality is worshipped, and where scepticism, relativism, and suspicion have come to reign. Avigdor Arikha’s own artistic development exemplifies the virtues and dangers of suspicion, as he went through one crisis of faith in artistic representation after another (Duncan Thomson outlines these crises in his excellent book entitled simply <em>Arikha</em>). Beckett himself, in some ways the most trusting of men, was profoundly wary of any attempt to transfer his words or work from one medium to another – and this when that is precisely what we have been doing by taking his private handwritten letters and turning them into public print. </p>

<p>Of the other stages I have mentioned as integral to the preparation of our edition, let me focus briefly on just two: selecting and annotating. It is the natural wish of any student or scholar of Beckett to wish to have access to <em>all</em> of his letters. Our task as editors has been to make a selection, one guided by Beckett’s sketchy indication that there should be published letters (or passages from letters) “having bearing on my work”. This little phrase has, for want of a more explicit statement, been the albatross around the editors’ necks ever since Beckett’s death. For of course no two readers understand the instruction in the same way, particularly given that Beckett himself so vehemently refuses to see writing as any sort of a <em>career</em> or <em>profession</em>. What does fidelity mean, in view of his request/injunction, and how is it best achieved? </p>

<p>Our answer is of course (in) the volumes themselves. What I can add here is that on a daily basis I have found myself asking whether this letter is more worthy of inclusion than that letter, while trying all the time to monitor if my own personal preferences are being guided by my understanding of fidelity – fidelity to Beckett <em>the writer</em>. By this I mean that, when faced with a choice, as we have been continually, I have tried to go for words, sentences, whole letters sometimes, which indicate that Beckett, never a sloppy writer even when composing the most mundane or trivial business letter, was fully invested here <em>as a writer</em>, not merely as a conveyor of information (however interesting that information might be in itself). I have tried to bear in mind, practically to employ as a yardstick, one of his earliest published insights – an insight into James Joyce but which lays a foundation for what he would subsequently attempt in his own work, especially in what I consider his “mature” work (that published after World War II). In his essay “Dante . . . Bruno . Vico . . Joyce”, which appeared in 1929 in a collection of pieces on “Work in Progress” (<em>Finnegans Wake</em>), he wrote: <bR><br>

<blockquote>Here form <em>is</em> content, content is form. You complain that this stuff is not written in English. It is not written at all. It is not to be read – or rather it is not only to be read. It is to be looked at and listened to. His writing is not <em>about</em> something; <em>it is that something itself</em>.</blockquote>

The letters I have been most keen to publish are those that come closest not to “bearing on my work” but to <em>being that work itself</em>. However, were I to try to explain how I judge if or when this is the case, or why I rather than another should uphold this particular understanding of <em>fidelity</em>, I would be required to unpack my own literary formation and predilection, and in the process would no doubt reveal my limitations; reveal too how I have been moulded by my conviction that there has been – that there needs must be – “loss at every twitch”. </p>

<p>Four years ago I lectured at Tokyo University on the then recently published Volume II of our edition. I made a point of asking professors and graduate students present if they thought that footnotes would be helpful to explain what certain places or institutions were, from Le Dôme to the Ecole des beaux-arts. Not surprisingly, the response I received there was very different from what I received when I subsequently posed the same question to Beckett students and scholars at the Sorbonne Nouvelle. When annotating an edition such as ours, one feels forever on a tightrope: fall on one side and one infuriates readers by stating the obvious; fall on the other side and one leaves readers in the dark. As one attempts to keep one’s balance, one tries to avoid awareness of the fact that for every reader (and for every language and culture) what divides over- from under-statement will vary. What I am talking about here is of course another sort of <em>fidelity</em>: fidelity to one’s audience or readers. And it is not only across cultures that knowledge varies – what is familiar, what strange, within any linguistic, literary, or cultural reference – but over time as well, and this in at least two important senses. What is obvious to readers of a certain age may be far from obvious to those who are younger. What needed to be stated twenty years ago, when internet search engines were in their infancy, is much less essential now that most readers can be assumed to have access to Google. Over and over we have found ourselves adding a note, because one version of our readership is in our minds; then removing it, because a different version has since appeared; then adding it again… and so on. Any literary editor will have faced this issue, but there is something in the range of Beckett’s references and the ease with which he moves across languages and national cultures that makes the ideal of respecting one’s readers – neither taking them for fools nor taking them for versions of Avigdor Arikha, with his seven languages and his encyclopaedic knowledge of the history of art and literature – particularly challenging. </p>

<br />
<p>(Footnote to the above on <em>fidelity</em>. After jotting down these thoughts on my second “question”, I walked across Paris to a session of psychoanalysis, as I have been doing, on and off, for the past twenty-five years. Only when well into the session did I recollect a dream I had last night – as the French would have it, a dream I “made” last night, “un rêve que j’ai <em>fait</em>” – in which I was being flagrantly <em>unfaithful</em> – with a girl I knew when I was eighteen years old. The reasons behind the dream are less important here than my shocked realisation that everything I had written – above – earlier in the day had been a way of hovering around and trying to approach this dream: that, in analytic-speak, my ideas had been <em>overdetermined</em>. Does this make them less valid? <em>More</em> valid? And more generally – a question I shall return to after a brief inspection of the trees in our groves: is there a place in academic discourse for such sudden disruptive realisations?)</p>

<br />
<p><strong>3. ARE THE YOUNG TREES HEALTHY IN THE GROVES OF ACADEME?</strong></p>

<p>When I was a child, I attended a primary school situated on one of the most beautiful streets in my home town, Edinburgh, a street that passes through playing fields and lawns and parkland, running down the west side of the Botanical Gardens to the Water of Leith. Its name, Arboretum Road (which turns into Arboretum Place and then Arboretum Avenue), echoes through the present context. Could it be that my early experience of this delightful setting for learning has fostered in me an unhelpfully literal understanding of the relation between healthy well-tended trees and promising open-minded scholarship? What I can say with some certainty is that I feel a tension mounting between whatever points towards the natural in Horace’s metaphor of the “inter silvas academi” and the unnatural acts (or non-acts) taking place in contemporary academia (a tension already highlighted in Mary MacCarthy’s 1952 novel <em>The Groves of Academe</em> which popularised awareness of Horace’s words). Let me offer a single illustration. Trees use different ways of propagating themselves, but to ensure the continuity of their species is one of their lives’ purposes. While academics?</p>

<p>I shall try to answer this question, briefly, by returning to my notion of fidelity to my readers. When I write fiction, which I do when I can, I have a clear sense of my readership, made up of friends and those whose judgement I trust – some fine writers among them. If I am fortunate enough to find readers beyond this tight circle, then so much the better, but I consider this to be a bonus. By contrast, one of the pleasures of writing (or editing) for an academic audience was, in the past, that one could realistically expect to have a larger audience, so long as one was not working on too obscure a topic; finding the right register or degree of complexity might be challenging, as I have mentioned, but libraries would be likely to buy the books put out by the major presses, and interested students would be likely to borrow and read the books written by the professoriate. There was, in other words, a community, a system that followed a cycle, given that one’s student-readers themselves became professors, thereby ensuring the continuity of the profession (the reproduction of the species). </p>

<p>It seems to me that we live in a time where an academic readership, a succession of professor-to-student-to-professor-to-student, is no longer assured. Young scholars are required by their universities to publish books that the libraries of these same universities are far from certain to purchase. They are obliged to do this, often, long before they are ready; not simply in order to be promoted, or even to gain job security, but merely to obtain a job in the first place. Most academics and most academies – in the humanities at least – are failing to thrive and increase, barely able to maintain themselves at a level that ensures their survival. At my own university we do not have Ph.D. programmes, but of course I advise students who are considering graduate school; I need to think very hard, in a way I certainly would not have had to do twenty years ago, whether or not to advise even the brightest and most capable among them to continue into further years of study (and almost inevitably into further debt). In the past there existed the expectation that, after years of diligent and often isolating toil, the gifted but indebted scholar would find a job that would allow a modicum of freedom from the routine and tedium that commonly afflicts those working in better paid jobs. Now, with the prospect so diminished of even the smartest of Ph.D. recipients’ finding a job – someone told me recently of 734 applicants for a single Assistant Professor’s post in California… </p>

<br />
<p>And what of the rare individual who is fortunate enough to land an academic job? When I ask myself this question, I find my heart sinking all over again. It is not just the tightened faculty-development budgets that worry me, nor the fact that the newly appointed assistant professor (or lecturer or maître de conférences) is likely to be made to understand that s/he should be doing more (and more) administration – that, indeed, it is in administrators’ offices that the <em>real</em> work is going on. Nor is it even the amount that s/he will be required to teach. It took an observation offered to me two decades ago by one of my own students to pinpoint a different, additional source to my worry.</p>

<p>My university is small and eccentric enough – an American-accredited institution in France, with students from nearly one hundred countries – to help it avoid much of what strikes me as aberrant in university culture today. Yet even here I have felt a mounting consensus – the word <em>ideology</em> would imply something more conscious or explicit, yet the consensus is assuming something of ideology’s force – that appears today to be inflecting expectations of teachers and teaching. We faculty at AUP were recently encouraged to read, reflect on, and then discuss in open forum a book by one Ken Bain entitled <em>What the Best College Teachers Do</em>. Ten pages into this book I found myself rather reluctantly conceding that what Ken Bain was proposing seemed eminently rational. To summarise crudely: it is that the best teachers are those who put the student experience at the centre of their programmes, and who place learning – which includes the challenging of well-established methodologies and paradigms – above the acquisition of mere facts or rote knowledge. Throughout his book Bain’s eye is upon student expectations and how far these are fulfilled – an eminently reasonable focus, especially in a time in which student investment is liable to involve not merely time and intellectual energy but also money, lots of it. </p>

<p>So much was unexceptionable in Ken Bain’s book, as well as in my university’s approach to debating it, that I was surprised, almost embarrassed, by my own curmudgeonly resistance to what I was reading. Of course, there had re-emerged through his descriptions of university offerings my disquiet about a “shopping” attitude to studies, that might lead even a well-intentioned student to conceive of the selection of a course – of a major, even of a university – as a process akin to that of choosing any other commodity. Such a conversion, of student into <em>client</em> or <em>customer</em>, is very well analysed and critiqued in Stefan Collini’s book <em>What are Universities For</em>? Here, Collini demonstrates clearly the dangers implied by this shift, for those “purchasing” as much as for those “selling” education; and these dangers are exposed further by Marina Warner in her series of articles about her resignation from the University of Essex (published in <em>The London Review of Books</em>). Yet though these dangers are important and worth signalling, I knew there was more to my unease – or rather I knew that there was something that touched me more intimately. What could it be?</p>

<p>Suddenly, as I was trying once again to enjoy Ken Bain, I recollected a theory imparted to me by one of my brightest students from twenty years ago, who had joined the university in her early thirties after a fifteen-year career as a ballet dancer in several of the top companies in Europe. Let me sum up her argument – and then let me run with it, even to the point of caricature: she drew it from long experience of being being a student – in different languages, different techniques, different cultures. “There are two types of teacher,” she explained to me in a tone that would brook no dissent. “There are <em>gurus</em> and there are <em>pedagogues</em>.” </p>

<p>I asked her to elaborate. </p>

<p>Pedagogues, she explained, are those who obtain their satisfaction from sensing that they have transmitted their ideas, from seeing their students develop, from the glimmer of understanding in their students’ eyes (or their new élan when performing a leap or arabesque). Pedagogues need to know that they have a programme, that it is being followed, that the outcome is achievable and is (mostly) being attained. In other words – to take my own leap forward, twenty years, to the present – pedagogues are the <em>only</em> type of teacher who pass muster in Mr Bain’s book, the only ones who really qualify as teachers at all. In the university context, pedagogue-professors naturally embrace such notions as the “invitational syllabus”; are keen on student feedback and learn from it; are easy participants in a culture of assessment that in turn facilitates the task of administrators who themselves are under pressure from the accrediting bodies that seek to ensure that standards are being met and that the claims being made by institutions are empirically verifiable. </p>

<p>So much so simple and so sound. But what, I asked, of gurus?</p>

<p>Gurus, my dancer-student explained, are those whose attention (whose “narcissism” is what she in fact said) is invested not in the circuit between themselves and their students, for whom the very presence of these students is incidental. Gurus come to class with all their training and experience, but precisely in order to forget these; very possibly they have no clear plan, unless that plan is to try to interpret the work in question in a way that comes closer to it than ever before – gurus, she explained, try to surprise themselves, and a class in which what is uttered has been uttered before is a defeat. Gurus, she went on, are talking to themselves, or rather to some part of themselves that they wish yet to find; they talk to the work, at the work, round the work, and if there are students there to overhear then this is just an added plus. Gurus will not be displeased to see their students progress, but they will not judge their own success by that; they will be almost constitutionally incapable of participating sincerely in assessment exercises since what they are aiming for is not – hence the “guru” moniker – improvement or even excellence, but the <em>truth</em>. However often they fail to utter or instantiate it – gurus need not be mad or hubristic, and they somewhere know they are bound to fail – this does not stop their determination to get it right – get it righter – the next time.</p>

<p>I remember laughing when I heard my student’s theory: a binary simplification, an amusing one, but little more. Until, that is, I started to question myself as to what sort of teacher I had myself been drawn to. The more I thought about them, the more I realised that my own “best teachers”, the ones I had instinctively followed and who had left their stamp upon me – in the academic field but also in the other areas where I had sought out instruction – fell unmistakably and unvaryingly into the latter camp. It’s not that I did not encounter and respect teachers who were “pedagogues”; rather, while acknowledging their merits, I fled them like the plague. I did not want, I had never wanted, a teacher whose chief goal was to teach me, or one whose goal had anything to do, in fact, with <em>me</em>. Such teachers made me anxious, while also boring me from the outset, as if we were only ever going to perform a series of manoeuvres whose outcome was dreadfully foreseen. I was forever drawn to teachers who, when in class, made me feel that I was at most a witness, that what really mattered was not me, nor indeed themselves or our relation, but rather whatever was under discussion, which despite the teacher’s best endeavours remained almost always mysterious and at some level intractable. </p>

<p>Within the scheme laid out in Ken Bain’s book – a scheme that is so much the dominant one in academe today that it is practically heresy to question it – there is simply no place for the “guru”. To plead for the importance of such teachers would be a sort of wild impertinence, like pleading for incompetence or arrogance or unaccountability. When professors need to state what the seven chief outcomes are of the course they are about to teach, then of course the guru will be found wanting. What the guru seeks to teach cannot be corralled into a quick formulation, and even if it could be then from the moment that it was, it would have ceased to be a goal. I still remember how I chose my undergraduate courses at the University of Sussex, at the end of my first term there. I asked around among the teachers who had already taught me, seeking their advice. Three out of the four of them said something like: “People say George Craig who teaches French literature is very intelligent, though personally I don’t understand a word he says.” Instantly, I signed up for all George Craig’s classes. And I was not disappointed: I recall sitting in his cramped office with the pipe smoke thick, in those uncomfortably low bucket chairs that were a spine-twisting speciality of the 1970s, watching and listening as the one who purported to be “teaching” us spoke for twenty uninterrupted minutes at top speed about Baudelaire, while staring intently and undeviatingly at his shoes. Indeed, at one moment, to illustrate some point about a self-supporting verse structure, it occurred to him to slip his feet out of his shoes to see if they would stand on their heels alone, in an upside-down V. Amazingly, they did, and he gazed at them in as much astonishment as did I and my two fellow students.</p>

<p>Let me not turn this into <em>mere</em> caricature. I am not talking here about teachers who are sadists – I had enough of them as a schoolboy to know how to recognise and avoid them: those who wish to make their students feel small or vulnerable or insignificant. I have no wish to place myself in the masochist’s position with respect to any instructor. Nor am I implying that gurus will be any less disposed to be friendly or helpful to their students once the class is over. I got to know George Craig during my second term as an undergraduate, exactly forty years ago, and we have been friends ever since; it was I who invited him to join us as translator on our project to edit Beckett’s letters. Gurus need be neither more nor less human or humane – or available or engaged – when faced with the living reality of their students (though in my own experience they have almost invariably been <em>more</em> rather than <em>less</em> involved than their pedagogue counterparts). But for the duration of the teaching, such considerations fall away….</p>

<p>Naturally, gurus make very poor self-advocates, and most of them, amazed to realise that they fall into this category, would (rightly) repudiate any connotation of elevation or spiritual superiority that goes with the term. They also almost always make unsuccessful administrators. They find it inordinately difficult, when asked to provide the seven “student learning goals” of any given course, to state what these might be – a difficulty that will appear ridiculous, puerile even, to the pedagogue. As Ken Bain’s book made abundantly clear to me, gurus have absolutely no place in a contemporary university, least of all if they are junior; not when so much of their job will involve accounting for their activities and anticipating the outcomes of these activities. And – my dancer-student confirmed this for me when I asked – a guru can <em>never</em> convert to become a pedagogue, can only, if pressed, put on a poor imitation of one; which, she said, is even sadder than watching a pedagogue pretend to be a guru! </p>

<p>What I know for sure is that if I had entered a university filled with “pedagogues” I would have struggled from the start and probably not have completed my first four years. Not that pedagogues do not have a place in a university, a place all the more vital now that teachers are also supposed to double up as administrators and need to pretend to take seriously the language – the idiolect as it really is, but now so widely shared as to be virtually a language – of administrators. But for the student who is not drawn to the pedagogue, a university that offers only such “best teachers” promises a series of elaborate rituals, a dull procession of incremental achievements, a promise of endless imitation in the name of a goal that is, note least because it is named, already practically worthless.</p>

<p>When I consider the three academic systems with which I am closely familiar, the French, the British, and the American, I can see advantages and disadvantages to each, but in all I detect, if in different stages of dominance, the reign of the pedagogue (who also happens to be the administrator-in-waiting). What I fear I shall see when next I walk down the groves of academe is not the greenery that greeted me on Arboretum Road, not the confident risk-taking I encountered when I went to university and was encouraged to explore, expand, find the words for experiences I did not yet know I had had. What I fear I shall see is a line of blasted elderly trees, alongside some ragged-looking shrubs that are struggling to grow to maturity (but on which will be posted some very persuasive bulletins about how well they intend to flourish and how good that will be for life in the groves).</p>

<p><strong>4. IN SUCH GROVES, WHAT BEST?</strong></p>

<p>If I am in some measure right in my assessment of the health of the groves of academe, then where does this leave what I was trying to say about the role of the study of literature as being that of resisting orthodoxies and eschewing totalising explanations? As in any market that is shrinking, the temptation – both for the graduate seeking employment and for the institution seeking to make one of its increasingly rare hires – will be to go for the safe bet, rather than for the strange or idiosyncratic. </p>

<p>For a senior professor in a relatively secure job, such as myself, to say that I’d hope there would remain a place within what is conceived of as academic writing and criticism for that shocked and sudden awareness that struck me yesterday in the analyst’s consulting room – that’s all fine and well. But counselling attention to what is singular, unassimilable, or resistant to meaning can quickly come to sound like the indulgence of the privileged, when for example one is talking to graduate students whose hope for gainful employment in the field – one more pastoral metaphor – may well depend on their ability to produce the most easily recognisable forms of academic discourse. </p>

<p>Yet at the risk (unless it is the hope) of contradicting myself, let me hold out against my own pessimistic forecast, and suggest that it is precisely because the humanities are now in such difficulties that it is important to hold fast to what literature does best, which – for me – is to resist even this very <em>doxa</em> that I have myself here just expounded, that would have us overseeing the end of an era. How each individual – professor, graduate student, first-year undergraduate, writer, poet, painter – should resist is, naturally, as variable and unpredictable as the individuals themselves, and will be discovered only in the act of invention.</p>

<br />
<p><strong>5. IF LEAVES WERE TO GROW IN THE GROVES OF ACADEME DESPITE PREDICTIONS?</strong></p>

<p>The first missive – a telegram – in what is the fourth and final volume of Beckett’s letters is to Annette Giacometti who two days before had lost her husband, Alberto. The two men, Beckett and Giacometti, had been good friends, and when one reads in James Lord’s <em>A Giacometti Portrait</em> of how the artist was continually constructing and destroying, how he was in a perpetual state of never-quite-beginning and at the same time always-already-over, the resemblance between the two is certainly striking. Five years before, in 1961, they had collaborated on devising a tree for a re-staging of <em>En attendant Godot</em> at the Théâtre de l’Odéon. Photographs exist of them in the artist’s studio, with the plaster tree behind them. And this is just as well since the tree was destroyed by students who occupied the Odéon during the protests of May ’68 – quite why they thought this tree represented what was oppressing them has not been recorded.</p>

<p><em>En attendant Godot</em> (or<em> Waiting for Godot </em>as it became in translation) is a play where, it has been famously said, “nothing happens, twice”. The phrase is so memorable that the temptation is to accept it as true. The tree is there, not least, to remind us that it is not true. Something <em>does</em> happen, something that is not mere repetition, something that is not dependent on human volition, something that defeats prediction: the tree grows leaves between Acts I and II. How should one interpret this change? </p>

<p>This, I tell myself, is the sort of question an academic should probably ask. But is it the right question? May it not rather be that the tree has grown leaves precisely to remind us of the <em>limits</em> of interpretation? After all, Vladimir and Estragon will try to interpret the tree too, as unsuccessfully as they interrogate the rest of their surroundings; they will endeavour to render it redolent of meaning – the signal meaning that Godot will shortly appear – and will themselves be defeated. The leaves signal that our own grasp too is limited over the whys and wherefores of change. They remind us that nothing does <em>not</em> happen twice, and in so doing that what was once a fashionable view of Beckett’s world and work, as being replete with relentless repetition and “terminal despair” (the term was used by A. Alvarez, if I recollect correctly), is itself another consoling fantasy of consistency. Rather like the appellation “absurd” – as in “the Theatre of the Absurd” – it is a means by which we try to reassure ourselves that conditions of comprehensibility will prevail, that really we are not out of our hermeneutic depths.</p>

<p>Of course, there are many fine literary critics and philosophers who, since the heady days of “terminal despair”, since Adorno’s outstanding but grimly dark account of <em>Endgame</em>, have refined our notions – which includes our comic notions – of Beckett’s “intent of undoing” (the phrase is S. E. Gontarski’s). I recently read and reviewed Leland de la Durantaye’s new book that is making its contribution, entitled <em>Beckett and the Art of Mis-making</em>; several of our best critics have brought our attention to bear on what is aporetic in Beckett’s work. So why is it that I find myself still asking if there can be a place within academic criticism for those leaves? It may be for the same reason that I wonder if there is a place for yesterday’s apprehension of the forces behind my focus on the notion of <em>fidelity</em>. It may be for the same reason that I wish to drill a hole in my own pessimistic view of the current situation in university humanities departments. </p>

<p>If I may rephrase my question, borrowing terms from Roland Barthes (his essay on photography, <em>La Chambre Claire</em>): Is criticism, because of the requirements of the genre, because of the academy and what it considers highbrow and legitimate, because of the pressures of professional competitiveness and the dread within institutions of the unorthodox – is criticism condemned to deal with what Barthes calls the <em>studium</em>? (By <em>studium</em> Barthes intends all that is socially comprehensible, what can be sociologically deduced or be said to have generalisable truth-value.) Will criticism never be able to deal with the unruly, the idiosyncratic, the unassimilable, the ungovernable, what Barthes terms the <em>punctum</em>? “This second element which will disturb the <em>studium</em>,” Barthes writes, “I shall therefore call <em>punctum</em>; for <em>punctum</em> is also: sting, speck, cut, little hole – and also a cast of the dice. A photograph’s <em>punctum</em> is that accident which pricks me (but also bruises me, is poignant to me).”</p>

<p>However challenging it may be in the questions it poses, literary and art criticism tends to remain inviolate in its forms: the article, the commentary, the essay, the exhibition catalogue, the monograph… It is an awareness of the limits of such forms that contributes, I’m sure, to Beckett’s extreme reluctance to write criticism at all, and to the fact that when he does so, in later life, it is almost invariably to help out a friend. For it is certainly not the case that he is, as he regularly claims, a foolish critic or an inarticulate one; rather, he is a critic for whom the formal expectations inherited by critics are themselves inimical to the sort of criticism he might wish to offer. Something of this is apparent in what may be his most important artistic manifesto – by which I mean that it is about as close to a manifesto as this least manifesto-inclined writer stretches: his “Three Dialogues with Georges Duthuit”. Already the choice of a “dialogue” represents Beckett’s resistance to Duthuit’s urging (expressed repeatedly in his letters to him) that he write an article on contemporary artists. And then, within that dialogue, at key moments, Beckett plays with the genre, collapsing or sending it up to try to exemplify the limitations of what can be said even in a form in which no single voice or argument can be permitted to dominate. His final statement in the first of the dialogues, on Tal Coat, is “B.– ”; in other words, no words; no statement can rationally follow his extremist claim that the role of art today is “the expression that there is nothing to express, nothing with which to express, nothing from which to express, no power to express, no desire to express, together with the obligation to express”. The second dialogue, on André Masson, ends hardly more propitiously, with “B.– (Exit weeping.)”. And the third: “B.– (Remembering, warmly) Yes, yes, I am mistaken, I am mistaken.” What I am trying to articulate here is, I believe, my uncertainty as to the place in academic discourse, especially in a time of austerity when institutions are under severe pressures to produce what is instantly recognisable (and has “impact”), for Beckett’s statement “I am mistaken” (for the sprouting of those leaves). And yet without a place for such a statement, without those leaves, without the <em>punctum</em>, then the study and teaching of literature and the writing on it, must – if I am correct in thinking that literature’s role is not least to face us with the inchoate, the uninterpretable, the unassimilable in language – be working against rather than for or towards its object.</p>

<p>The problem, if I’m right in supposing that there is one, may have been exacerbated during the period when I myself was a student, during the 1970s and 1980s when theory – “high theory” as it came to be known – was gaining ascendancy. Not that theory was not able to “think” certain of the issues and limitations I have been pointing to, on the contrary. However, its dominance in certain quarters may have led to a widening of the gap between the theoreticians – employing specialised idiolects and often referring to “scientific” models or ideals (those structuralist graphs, those post-structuralist pyrotechnics) – and practitioners of writing, the very writers whose work was being analysed. I don’t wish to exaggerate this, nor do I wish to point a finger at practitioners of theory (I myself was one, in a minor way). But I do wish to suggest that, when added to the pressures produced by shrinking academic budgets and an increasing drive to specialisation on the one hand, and the populist drive to the production of demonstrable “outcomes” on the other, the move by which theory distanced itself from the languages and practitioners it was studying may indeed have contributed to a perception of the irrelevance or “elitism” of literature departments. </p>

<p>Fortunately, at least one remedy seems to have presented itself – and no doubt there are more. For this widening gap between the language of literature and the language of literary theory has provided, I presume, one of the stimuli to the rise in Creative Writing in universities over the past thirty years. The lure of the systemic or systematic, of abstraction and the abstruse, was not felt by every student, and surely not by those for whom the study of literature was intended to provide an entry to whatever it was inside him/herself that felt a need to <em>write</em>. Students interested in literature, hoping to try their own hands at writing, and who saw the study of literature as an apprenticeship into a craft – a mystery, even – must have experienced quite a shock when confronted by much of what passed as literary analysis in, say, the mid-1990s. </p>

<p>My own experience of thirty years of teaching students of literature tells me that they are a gifted but also volatile group, often psychologically vulnerable and confused – and yes, more so than students in other disciplines. Often they have been drawn to literature because that is where weirdness is permitted, where whatever they feel in themselves to be in search of expression may finally find an echo or even – such is the hope – recognition. When literature students read Beckett’s <em>The Unnamable</em> for the first time, or László Krasznahorkai’s <em>Satantango</em> (which I have also taught to enthused responses), they are likely to feel out of their depth; but in a sea of words whose storm is not being organised according to some principle that itself is alien or oppressive. Creative Writing may have allowed articulation of that remainder in self and world that academic discourse had occluded; I welcome its growth as in part an attempt to respond to whatever refuses to be absorbed into any sort of predictable system (including my own). </p>

<p><strong>6. WHAT SORT OF CONSISTENCY FOR THE GROVES OF ACADEME?</strong></p>

<p>No sooner do I make this claim, above, than I feel the need to qualify it. A graduate from one of the US’s top Creative Writing MFA programmes told me recently that the most important thing she had learned in her programme was to think her fictional characters in the round, from every angle, and to monitor them for consistency. What she said sounded to me rather like a transposition of Stanislavsky’s advice to actors. One of my own former students is soon to have her first novel published by a major US house; she asked if I would read it through before she sent it for its final edit. I was pleased to do so as the novel was exceptionally accomplished – and even if it hadn’t been, I was interested to see how she would develop the plot she had outlined to me. I came back to her with more than a thousand suggestions for minute changes – a tense here, a qualifying adjective there, the use of parenthetical commas, occasionally the tone of a dialogue. On one or two occasions I noticed what struck me a possible incoherence in plot or character, but as the book had already been sold for a handsome sum, I did not see it as my role to interfere, and in any case my own conception of character is far from being one I imagine to be universally shared. I was surprised to learn that when the novel returned from the experienced editor at the publishing house it did so with no line-corrections whatsoever but heaps of comments on character and motivation, mostly aimed at “tightening up consistency” – what sounded to me again like a literary version of the “Method School” of acting.</p>

<p>I have long been fascinated by a moment that has confounded critics, in what is sometimes described as Shakespeare’s most “toxic” play, <em>Troilus and Cressida</em>. Here is some of what I wrote about it in an essay on Shakespeare and Beckett (in Volume XII of the “Great Shakespeareans” series):<br><br> <blockquote>During the first great debate in the Trojan camp on the advisability of retaining Helen, cause of the war, after Troilus states ‘What’s aught but as ’tis valued?’ (II, 2, 52), Hector, who is as close in this play of unlikeable characters as we come to someone we can respect, launches into an attack upon relativism:<Br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;But value dwells not in particular will,<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It holds his estimate and dignity<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As well wherein ’tis precious of itself<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As is the prizer. (II, 2, 53-56)<br><br>

He expands into a cogent, virtually irrefutable argument in favour of nature and natural laws of matrimony, and against the shedding of more blood therefore: it is quite the most convincing speech in the Trojan chamber, even in the entire play, and this not despite but rather because of our disabused sense that the moral ambiance, the plot (such as it is), and the characterisation (with its self-doubling) are whelming him:<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Thus to persist<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In doing wrong extenuates not wrong,<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;But makes it much more heavy. Hector’s opinion<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;is this in way of truth. (II, 2, 186-189)<br>

Hector signs his own death warrant as, changing tack mid-line, he continues:<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;yet ne’er the less,<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My spritely brethren, I propend to you<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In resolution to keep Helen still,<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For ’tis a cause that hath no mean dependance<br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Upon our joint and several dignities. (II, 2, 198-193)<br>
<br>
Even as fine a critic as A. D. Nuttall (in Shakespeare the Thinker) throws his hands up in exasperation at Hector’s tergiversation, hazarding that “Shakespeare wrote the first, eloquent part of Hector’s speech, adjourned to the pub for a heavy lunch, and returned thinking ‘I have to turn the action round here’.” </blockquote>

<br />
I feel driven to ask myself: Why would Hector do this? Why would Shakespeare? When each has his respective audience eating out of his hand, why would he go and spoil it all, taking off in a direction that is destined to bring (for Hector) self-destruction and (for Shakespeare) bafflement? One can imagine what a contemporary trade-house fiction editor or certain Creative Writing instructors might make of such a moment. Yet it is, I want to say again, precisely for such moments – such “leaves”, such a “punctum” – that I turn to literature: for just this consistency, which is quite other than what is achievable through predictability or notions of psychological coherence.</p>

<p>What I go on to attempt in my essay is to read Hector’s turn through the lens offered by Beckett, comparing this moment to moments in <em>Waiting for Godot</em> when, for example, Pozzo appears to be unable to sit down, then, suddenly, for no accountable reason, finds himself indeed sitting down. Beckett himself would have had very little time for an approach to the literary that drew on psychological verisimilitude (which is almost always destined to be psychological reductionism). When quizzed in 1953 by Carlheinz Caspari, who is gearing up to stage the first German production of <em>Godot</em>, he responds:<br><Br>

<blockquote>The characters are living creatures, only just living perhaps, they are not emblems. I can readily understand your unease at their lack of characterisation. But I would urge you to see in them less the result of an attempt at abstraction, something I am almost incapable of, than a refusal to tone down all that is at one and the same time complex and amorphous in them.</blockquote>

<br />
The following year, after meeting the celebrated actor Ralph Richardson who was lining up to play in the London premiere of <em>Godot</em>, Beckett would report: “had a highly unsatisfactory interview with SIR Ralph Richardson who wanted the low-down on Pozzo, his home address and curriculum vitae, and seemed to make the forthcoming of this and similar information the condition of his condescending to illustrate the part of Vladimir”. Beckett refuses the hunt for any sort of “objective correlative” in a world where objective, like subjective, have ceased to be viable categories: “Too tired to give satisfaction I told him that all I knew about Pozzo was in the text, that if I had known more I would have put it in the text, and that this was true also of the other characters. Which I trust puts an end to that star”. The year after this, to his American director Alan Schneider, he is even more explicit about Pozzo, despite his habitual reluctance to be explicit:<bR><Br>

<blockquote>He is a hypomaniac and the only way to play him is to play him mad. The difficulty always experienced by actors with this role (apart from its mechanics which are merely complicated) results I think from their efforts to clarify it and to give it a unity and a continuity which it simply cannot receive. In other words they try to establish it from without. The result at the best is lifelessness and dullness. Pozzo’s sudden changes of tone, mood, behaviour, etc., may I suppose be related to what is going on about him, but their source is in the dark of his own inner upheavals and confusions. The temptation is to minimize an irresponsibility and discontinuity which should on the contrary be stressed.</blockquote>

<br />
And nearly twenty years on, Beckett is still mulling over the Richardson incident and reasserting his opposition to the actor’s presumptions. In 1972, when he is preparing to stage <em>Not I</em>, Schneider asks him, of the woman behind the mouth on stage: “We’re assuming she’s in some sort of limbo. Death? After-life? Whatever you want to call it. OK?” Beckett writes: <bR><br>
<blockquote>This is the old business of author’s supposed privileged information as when Richardson wanted the lowdown on Pozzo’s background before he could consider the part. I no more know where she is or why thus than she does. All I know is in the text. “She” is purely a stage entity, part of a stage image and purveyor of a stage text. The rest is Ibsen. </blockquote>
<br />
One can well imagine the reaction a young novelist – indeed a novelist of any age – might receive were s/he to send such an explanation to a fiction editor who was busy imposing psychological coherence upon the novelist’s characters… </p>

<p>So consistency, yes, but consistency of the sort Shakespeare’s Hector exemplifies, that a writer such as Dostoevsky (one of the young Beckett’s favourites) understood, or that Beckett himself insists upon. The challenge to criticism being, of course, that this is a much harder consistency to write about insightfully than that which Beckett seeks to sum up in his dismissive deployment of that proper name: “Ibsen”.</p>

<br />
<p><strong>7. WHAT DOES NOT GO DIGITAL IN THE GROVES OF ACADEME?</strong></p>

<p>At the start of each of the four volumes of the <em>Letters of Samuel Beckett</em>, we reproduce a single letter in facsimile in black and white. The first volume features a letter to Mary Manning, sent from Germany; the second a letter to Georges Duthuit; the third a letter to Avigdor Arikha. When it came to deciding which letter to reproduce in Volume IV, instinctively I knew which would receive my vote: the letter I have already discussed, to Harold Pinter. I wished for readers to share, if in a small way, the puzzlement I have felt, as well as my frustration at being unable to decipher that word – and perhaps some reader might indeed crack the puzzle. I wished to intimate how much work has been done in the transcription of the letters, but also to make clear the editors’ limitations; I wished readers to be aware, however fleetingly, of the physical nature of a letter, of the hand that drew these strokes across this page; of the violence, therefore, that has been done to Beckett’s <em>actions</em> as a letter-writer – I have already spoken of his <em>intentions</em> – in the conversion of these words into thousands of pages of type.</p>

<p>It was partly to offer readers a more intense impression of the physical nature of Beckett’s correspondence that I devoted pages of Cahier 16 in the Cahiers Series (by George Craig, entitled <em>Writing Beckett’s Letters</em>) to reproducing, in colour and high definition, letters and postcards that Beckett had written – envelopes too. For me, the material that is a letter, with its specific colour of paper, its weight, its creases and folds, and of course with its handwriting (or more rarely its type) – this too, this material, is what risks being forgotten in the groves of academe, focused as academe must almost inevitably be on type, on finished “objects”. Ideas, which are naturally the mainstay of academe, are of course not objects. But as I said at the outset, my ideas, these days…</p>

<p>When in 2007 I set up the Cahiers Series, with the designer Ornan Rotem of Sylph Editions, I did so with the purpose of making beautiful – and I hoped insightful – objects. From the outset we designed the cahiers to resist digital reproduction: the cahiers need to be held, their pages need to be turned by a living hand, they need to be smelled, even, in order for them to be fully appreciated. Digital media have opened the archive for many to whom it would otherwise have been closed; the fantastic work being done at Reading University on the Samuel Beckett Digital Manuscript Project is a good example of this. But by turning yet more objects into digital realities that can be viewed and considered on screen, digital media also run the risk of distancing us yet further from the material world. </p>

<p>With Daniel Medin, my colleague and companion at the Center for Writers and Translators at the American University of Paris, we recently went to print with Cahiers 27, 28, and 29. Each contains work by an author and work by an artist: Kirsty Gunn and her sister Merran Gunn (no. 27); Javier Marías and Wifredo Lam (no. 28); Georgi Gospdinov and Theodore Ushev (no. 29). The idea – an idea at last? – behind the series has not wavered: to encourage writers and artists to think about translation in new and interesting ways. I wished to narrow what I perceived as a gap – a gap once again between theoreticians and practitioner; I cannot be the only to have heard a translator say that s/he never reads translation theory, or who has heard a professor of translation studies be dismissive of this or that translator for not being versed in the latest theory. And of course the gap-reducing aspiration of the Cahiers Series became more acute and risky when a further pair of elements was added, with word being allied to image in a way that is highly unusual in academic publishing, in the hope that they should complement and comment on one another, without the image ever becoming “mere” illustration. As befits a venture in border-crossing, we have sought to be resolutely international too, and when no. 29 comes out we will have published writers and artists from Australia, Austria, Belgium, Bulgaria, Canada, China, Cuba, England, France, Germany, Greece, Hungary, Ireland, Israel, Italy, Japan, New Zealand, Poland, Russia, Scotland, South Africa, the US, and Vietnam…</p>

<p>But let me end where I started, with a statement not about ideas or principles but about practice: my own. I said at the outset that I consider myself to have been, for some time now, less of a <em>thinker</em> than a <em>maker</em>. I am aware that, even as I say this, my “consideration” is itself a <em>thought</em>; notwithstanding which, I wish again to assert that what I do, hour after hour, day after day, is to try to make things work – texts with images in the case of the Cahiers Series. And by <em>work</em> I mean something quite specific but rather hard to define, something I have no great wish to define for fear of becoming formulaic. I said above that literary and art criticism, even when it is posing challenging questions, tends to remain inviolate in its forms. The Cahiers Series seeks to violate these forms. Not being obliged to follow the publishers’ conventional conceptions of genre – that a book be a novel, a collection of stories, an essay, a monograph, or a set of poems – we combine elements that are commonly seen as inimical to one other. We assemble a cahier in the hope that its elements will produce something approaching a mosaic, where its many parts will become more than just parts. </p>

<br />
<p>If you’ve had the patience to follow me this far, Peter, you may be wondering: Does that hope to which I allude itself contains an “idea”? </p>

<p>Rather than try to answer that, let me get back to editing Cahier no. 30 - I just noticed that there is a comma missing on the colophon…</p>

<br />
<p><strong> Dan Gunn, Paris,  2016</strong></p>

<br /> 


<img name="home_r2_c1"
 src="../../images/spacer.gif" alt="Click to enlarge picture"
 title="Click to enlarge picture" border="0" height="391" width="10">
           <a href="artwork.html"
 onmouseup="MM_openBrWindow('artwork.html','','width=700,height=850')"><img
 src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2"
 border="0" height="234" width="250"></a>
 <br>
 <small>Secret Garden<br>
by <a href="http://www.interlitq.org/englishwriters3/lara-alcantara-lansberg/bio.php">Lara Alcantara-Lansberg</a></small>
 <br><br>



<p class="titulo2"><a href="http://www.interlitq.org/groves/groves-of-academe.php">The Groves of Academe</a></p>


            <p><br><br></p>
            </td>
            <td><img src="/images/spacer.gif" alt="" border="0"
 height="46" width="1"></td>
          </tr>
          <tr>
            <td height="103"><img src="/images/spacer.gif" alt=""
 border="0" height="103" width="1"></td>
          </tr>
        </tbody>
</table>
<?php include("../../foot.php"); ?>
</body>
</html>
