<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--

-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../glasgowvoices/menu_glasgowvoices.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../glasgowvoices/zoe_wicomb/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">The One That Got Away <span class="texto2">by <a href="bio.php" class="link3">Zo&euml; Wicomb</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           
              <p>&nbsp;</p>
          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <br><p>Drew has kept mum. Not a word, he had promised himself,  would he breathe to anyone, not even to his clever Janie, because cleverness  does not always come in handy with such projects. Janie is a no-nonsense  person, not given to flights of fancy, and that, he knows, is why he has fallen  for her. But he will not risk a discussion; there is the danger of her thinking  the work childish and, although he doesn&rsquo;t have a clear idea of what this  project is all about, he does know that secrecy is crucial to guarding plans  that are still in their infancy, to thinking things through.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Drew admits to a boyish sense of adventure that takes  him back to the drowsy afternoons at high school where Mr Wilton the history  teacher settled in his chair with legs wide apart to read aloud from the  textbook. Then the boy drummed his heels on the floor to quell the need to  escape, had to imagine a pair of strong hands pinning down his shoulders, for  the voice of the man ventriloquising Fowler &amp; Smit brought an irrepressible  urge to run. His pulse quickened at the thought of running, breathless, without  stopping, to the rim of the disk that was the real world where, looking down,  newness would lie sprawling before him in another disk, spinning like a  polished coin around the sun. Had he been an athlete he would have leapt and  landed in that alien landscape: mountain ranges with high snow-capped peaks,  trees burning in autumnal colours that he had seen only in pictures, colours so  distant and so subtle that they had never been named. He would have been the  one that got away. And all the time old Wilton was reading aloud in a dominee&rsquo;s  voice the sentences that had to be memorised for the examination, and that the  class had to underline in their Fowler &amp; Smit, now reduced to roughly half  the history. Stick to the facts, and underline neatly, with a ruler and in  pencil, Wilton said, as a mark of respect for the book, since pencil being  erasable, did not deface. All marks made in a book in ink was vandalism.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Drew used five colours of ballpoint pen and an HB  pencil, leaving none of the text unmarked, and as his ruler slid into angles  and verticals, the pages turned into dazzling works, every one of them  different. In the first row, almost under Wilton&rsquo;s nose, he bent industriously  over his book, and the project of turning every printed page of Fowler &amp;  Smit into something new was all the more exciting for being a secret act  performed so publicly.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fowler &amp; Smit is of course garish, but it could  be seen as Andrew Brown&rsquo;s first work of art, and as far as juvenilia goes, a  significant pointer to Brown&rsquo;s mature iconoclasm. Drew laughs aloud at this  foolishness that he dreams up in the name of Willem Stirling, the dreaded Cape  Town art critic. He had once met Stirling at the National Gallery where he had  just made the opening speech, and come to think of it, that was much like  listening to old Wilton. These formal events are killers. At his own grand  opening at Irma Stern, or why not the National Gallery itself, there will be no  pompous speeches, no, it will be a Cape Flats <em>djol</em>, or else he, the artist, will refuse to attend. Not  negotiable.<br>
Jane keeps her distance from his world, but she  worries when he larks about. They differ on whether it is healthy to fantasise.  Ambition unhealthy? he queries, but she says no, it&rsquo;s a matter of indecency,  this fantasising out loud. If he kept it under his hat as a dark brooding  secret, he would keep slim, she says, and then she lunges at him under the  covers, tries to grab handfuls of what she says are love handles. Which is of  course not possible since there is not an ounce of spare flesh.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Drew is pleased with himself for combining the  project he has in mind with their honeymoon. It could be said that the project  has brought about the marriage and honeymoon, for how else would he have  justified a trip to Glasgow? Janie was not keen on being married, why couldn&rsquo;t  they carry on as they were, and she poked fun at the idea of a honeymoon.  That&rsquo;s crap, she said; if it&rsquo;s a holiday let&rsquo;s call it that. Anyway it will be  more of a <em>wittebroodsreis</em> than a  honeymoon. That&rsquo;s all we&rsquo;ll be able to afford if we go to Scotland for our  white-bread-journey &ndash; pale, pre-sliced, flannelly white loaves from the  supermarket with Bride&rsquo;s Pride in blue logotype on the plastic wrapping. They  laughed at the translation, the paucity of down-to-earth, frugal Presbyterian  pleasure. Let&rsquo;s not bother with marrying, Jane said, wittebrood doesn&rsquo;t go with  a tiara. But, Drew said, Scotland, the home of Presbyterianism, is just the  place to go for an authentic wittebrood. Imagine, you&rsquo;ll give them sutz a  skrik, simmying in your Cape Flats  bling like the Queen of Seba. Please think of your mother, he said, of how  Grace can&rsquo;t hold her head up in Manenberg for the shame brought on her family by  a layabout artist. So in the din of mockery and laughter she said yes, alright  then, let&rsquo;s do it, at least marriage would please her mother. That is how their  own differences are resolved, the banding together against a world that seems  to them sentimental, thoughtless, conventional, and one in which they flaunt  their difference.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Drew was  over the moon. Yee-ha, he whooped, there was plenty of art he wanted to see in  Scotland, and he also wouldn&rsquo;t mind doing a spot of work in Glasgow. And so the  two things go hand in hand, which is another reason why his project must, for  the moment at least, be kept secret.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Glasgow, as they both knew beforehand, is hardly the  place for a Presbyterian wittebrood. Even bread is a designer item of many  variations housed in what looks like exclusive bread boutiques; bling is to be  found everywhere; and many a kirk has given up the holy ghost in order to  become fashionable bar caf&eacute;s. The opulence is awesome; their cents count for  nothing, and they have to keep track of each paper-thin pound note. Which is  why they&rsquo;ve moved to a cheap hotel-cum-boarding house in the scruffier east end  of the city.<br>
Jane is irritated with herself for expecting Drew to  behave as if they are on honeymoon. Even though the wedding was a hurried  registry office affair in their everyday clothes with only her mother carrying  an absurd posy of red roses and wearing a crazy hat, marriage has brought  nothing but complication. If they were not married, she would certainly have  expected them to do things together. Now, because it means nothing, because it  is no more than a convenience, she must put up with Drew rushing about the  place, leaving her to her own devices. It is as Jane thought: being a wife is  rubbish, precisely because you have to be careful not to behave like a wife, or  rather, not to be thought to behave like a wife. Which also sounds like rubbish  &hellip; Oh, it makes her head spin. She is sitting in an amazing space constructed  from the backs of grand old buildings now enclosed, galleried, and domed into a  modern square. The combination of old and new is piquant, and sitting in a caf&eacute;  on the top gallery, she looks down onto the modern floor mosaic where a jazz  pianist is absorbed in his playing, as if the place were not teeming with  people.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Yesterday turned out to be expensive so that now she  can only stare at the chocolate brownies, but there is a curious Presbyterian  pleasure to be had from the deprivation, and the coffee will taste all the  better. If Drew cannot be persuaded of the deliberate virtues of imposed daily  rationing &ndash; he would rather run out of rands &ndash; she finds that being in control  softens the blow.<br>
Jane is as comfortable as can be. The music seems to  encourage or at least legitimize loitering; after the coffee she will browse in  the shops, so that I have no compunction leaving her in Princess Square.  Besides, the rain has stopped and the glass cupola allows light to flood the  place. Should she get bored, I could wheel in a juggler or a clown since the  terraced space on the ground floor is large enough to accommodate a number of  municipal activities laid on for the season of tourists and children&rsquo;s outings.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And so back to Drew whose story this is: he is forced  into dissembling. He has in the last two days returned to the hotel to work on  the book. It would have been so much better if the work had been done at home,  but the truth is that until the very day they left, Drew was not sure what he  would do, what it entailed. Now he puts up the Do Not Disturb sign and pays no  attention to the cleaner who rattles the door in disbelief. Some monkey  business going on here &ndash; she has after all seen with her own eyes the couple  buttoning up their coats and leaving the place only an hour ago, but in  deference to the sign does not use her key.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The book  had been a green hardback without a dust jacket. Yesterday he scraped away at  the embossed title on the cover before painting it red. The title on the spine  is set into the fabric, with words arranged vertically, one by one: <em>The One  that Got Away by Helen McCloy</em>, and at the bottom, the name of the  publisher, <em>Gollancz</em>. Now painted, the letters are less clearly incised,  barely readable. It is on the front cover that he works today with a stencil to  print in large capitals an alternative title: GOLD  MINING IN SOUTH AFRICA. Drew feels a momentary twinge of unease: what would  Helen McCloy have thought of the alteration? He thinks of the author as dead,  as indeed he thinks of all authors, who, if not actually dead, are ancient and  chair-bound with long white beards. McCloy will of course not have a beard, or  at least not a long one. He thinks of Aunt Trudie&rsquo;s, of the half-hearted  migration from her thinning crown to the sparse crop of hair on her chin.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;It is unease about the author that makes him flick  through the pages, not for the first time, although he has no desire to read  the book. His eyes are drawn to a word in italics. This is the h our we call <em>forenicht</em>, he reads, when you can see  anything &ndash; ghosts of the dead and of the living, too, if you&rsquo;re a true  Highlander. For a second he shudders at the thought of seeing the ghostly  author with her wispy beard, but then takes comfort in the fact that he is not  a Highlander. He fills in the new title with black paint; tomorrow he will  alter the flyleaf and title-page. The book is placed carefully, open and face  down, in his briefcase, which, before they go to sleep, he will unlock and  leave slightly open for the drying of the paint. It is time for him to go; he  has promised to meet Jane in Princess Square for tea at four.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;But Jane is not there and her cellphone is switched  off. Jane has been driven out by a pack of hungry-looking teenage girls,  deathly pale in identical white sports outfits with hooded tops, who crowded  round her. Leaning against the railing, facing her, they jeered in demotic that  she could not understand, and as she bent down to secure her handbag, they  split their sides, pointed and shouted, seeming to demand answers. But how was  she to know what those questions were? The act of surreptitiously slipping her  handbag into safety had to be recast as getting ready to pay the bill, so that  she left for the safety of the till. The waiter thanked her effusively for the  large tip, but he did not follow her out to the gallery where the jeering girls  waited. Why on earth had she given a tip she couldn&rsquo;t afford? She stepped out  briskly, running the gauntlet of girls, and shook them off as she made for the  door. Outside it was pouring once again, and the girls did not follow her in  the rain. Sugar lumps, she muttered gratefully.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The rain is by no means summerish; it does not fall  gently like mercy from heaven. A vicious wind drives it in at an angle, so that  Jane all but doubles up clutching her coat. She will go back to the room, to  her bed, and snuggle down with a book. Drew will know where to find her.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The landlady, Mrs Buchanan, stops Jane on the  landing. She is what is known as motherly, which is to say soft-spoken, kindly,  full-bosomed, with rosy cheeks and fair hair fixed in the helmet style of  middle-aged women of this town, no, of the world over. Jane notes her hair  because she pats it compulsively, first with one hand, then with the other, and  at times with both hands.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;One or two days, the woman says, that&rsquo;s not a problem  &ndash; and Jane wonders if she has just returned from an incident with her  hairdresser, perhaps a new girl, an apprentice that she agreed to let loose on  her hair, and now the regret &ndash; but tomorrow, the coiffured landlady hopes, her  cleaner will have access to the room. Perhaps they could decide on a time that  is convenient to both parties? And now both hands slap insistently like  windscreen wipers at her temples.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jane&rsquo;s look of incomprehension confuses the woman,  who then remembers the cleaner muttering something about monkey business, so  that she says she has just baked chocolate brownies, still warm they are, and  wouldn&rsquo;t Jane join her for tea? Her kitchen is nice and toasty, just the ticket  for drying off with a nice cup of tea. Jane is ashamed of her anthropological  interest in the woman&rsquo;s kitchen and hairdo, for having scorned the motherly  look since it is precisely what is known as motherliness that admits her into  the warm sanctuary. Which brings a pang of homesickness for Grace&rsquo;s kitchen  with its bubbling pot of soup, even though Grace is anything but, and in any  case lacks the layer of plump that makes for motherliness. Puzzled as Jane is  by the story about access and cleaning, she notes the detail of chocolate  brownies, that which she had to forego in the caf&eacute;. The woman then is the  counterpart of the jeering girls in tracksuits, and so Jane must not resist the  pattern that presents itself, the story whose cast is growing, and which is  sure to throw light on the darkness that is Drew&rsquo;s role, for it occurs to her  as she bites into the sweetness of the chocolate brownie, that Drew must be up  to something.</p>
            <p>Drew had been researching the history of mining on the  Rand for a collaborative art project with his pal, Stan-the-Man. In the special  collection of the Cape Town City Library he pulled out the dusty volume, and  the novel literally fell off the shelf. He had not noticed it in the row of  mining books. Perhaps it had been wedged behind the one he removed? Drew could  not tell. The cloth binding was the exact green of the mining volumes, and the  book was only slightly slimmer than the others. The title on the spine, <em>The  One That Got Away</em>, suggested that it had nothing to do with mining, but  fascinated with his find, Drew leafed through it. On the flyleaf was pasted the  lending sheet of Glasgow City Libraries, and below, Dennistoun Public Library &ndash;<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Adult Department. The last date stamped in the final  column of the lending sheet was 16 JUN 1976. Pasted onto the bottom of the  gridded sheet was the standard information for lenders about the return and  renewal of books.<br>
              Only later, after the meeting with Stan, did Drew  wonder why he had, without thinking, tucked the book into his folder. It  couldn&rsquo;t be called theft; perhaps it was to test whether the library alarm  system would allow it, in other words, whether the book was a hoax of some  kind. He did not think at all of why he had kept the find a secret. Immersed in  the mining project, he gave little thought to the book, but kept it like  pornography &ndash; from the Adult Department &ndash; under wrap in a manila envelope. It  was a good two weeks before he had another look. He flicked through the book  and gathered that it was a mystery set in the Scottish Highlands. Not his kind  of thing, but it was the object and its history rather than the text that  interested him. What would he do with it? He didn&rsquo;t know, but there was also  the title that resonated, and the fiction that made him think of himself as a  character whose role would become clear in time. He too, after all, was the one  who got away, at least from the pin-stripe world of his brothers, the  businessmen, the hollow men, the invisible men &hellip;<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Occasionally, he took the book out of the envelope  and browsed through the pages. A mystery alright, although sections here and  there appeared to be excursions into Scottish history and traditions. The faded  pages were yellow around the edges, and Drew&rsquo;s nose twitched, as if foreign  Highland spores trapped for decades between the pages leapt out to attack his  sinuses. Thereafter he would turn the object this way and that, but try not to  open the book.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Then came the business of marriage and honeymoon, or  perhaps it was the other way round, since by then he knew with absolute clarity  why he had taken the book. The last sentence on the library&rsquo;s lending sheet  read: <em>A book must be returned to the library from which it was borrowed. </em>Such  an injunction has to be taken seriously. It is the imperative, the indefinite  article, and the mode of address that targets any reader, that at the same time  orders him, Drew, to carry out the task. The text speaks to him: responsibility  for returning the book does not remain with the one who borrowed it. Like any  traveller then, the book will return, showing the scars of its journey, the  markings of travel and adventure; it should return, flaunting its history and  its difference. But how? That he didn&rsquo;t know until the very day of their  arrival, so that he now has the task of transforming the object in a cheap  boarding-house room.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Drew arrives at the caf&eacute; ten minutes late and Jane  has gone. Her phone has been switched off, an infuriating habit that she  cannot, will not be cured of. Just as she predicted, he knows that she has gone  back to the room, knows that she has been driven back by the rain. He leaves a  message for her &ndash; that he&rsquo;ll wander about for a while, that she should call  him.<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Mrs Buchanan&rsquo;s kitchen is unremarkable. There are the  usual cupboards that hide mod cons like a refrigerator and who knows what else,  as well as a large double stove. An Aga, she says, that is what she&rsquo;d really  like, just imagine, a warm kitchen with stockpot bubbling and loads of wee  ovens to bake different things, over there a meringue in a cool oven, a  casserole in another, and perhaps a nice loaf of bread in the hot oven here,  all happening at the same time, and that, she says, is the beauty of it, the  many things going on simultaneously, which surely must save time.  Gesticulating, she loses the rhythm of patting her hair. Does Jane have an Aga?  Jane has no idea what an Aga is. And what do people eat in South Africa? Jane has  little interest in cooking, but she has a number of keywords at her  fingertips and so does not disappoint Mrs Buchanan. Biltong, bobotie,  boerewors, she recites, and then: frikkadel, sosatie &ndash; although she really has  no idea what sosatie is. She passes on a tip that Drew&rsquo;s mother offered, the  thing that makes Cape cooking so distinctive: a pinch of ground clove with all  red-meat dishes. Mrs Buchanan says she&rsquo;ll try it, she&rsquo;s game for all kinds of  culinary tricks, because if the truth be told, people here are fed up with  bland food. Did Jane know that curry was now the favourite British dish?<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The chocolate brownie is delicious. Jane eats two and  out of politeness asks for the recipe. Then she spills her tea on the tartan  tablecloth, but the woman says it doesn&rsquo;t matter. She giggles, It&rsquo;s a bit of a  laugh isn&rsquo;t it, the tartan, but the tourist board recommends a piece of tartan  here and there.<br>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   Before Jane goes she says, About the cleaning of the  room &hellip; But Mrs Buchanan brushes it aside. No need to worry dear; it really  isn&rsquo;t a problem, and she pats her hair vigorously before adding that the  forecast for tomorrow is dry and sunny, but cold, mind.<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Jane does not consciously search the room, but she  does wander in and out of the en-suite bathroom before settling into bed. What  could Drew be up to? Again, if they were not married she could have grabbed him  by the collar and shaken it out of him, but now she must be careful not to  behave like a wife. She remembers the phone, and calls Drew who is on his way  back.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ah, he sighs as he comes in, dripping with rain, just  the ticket, just what honeymooners are supposed to do, and he whips off his  clothes to snuggle into bed. 
              Jane recounts the events of her day, including tea with  Mrs Buchanan, but says nothing of the room that has not been cleaned. A funny  old thing hey, she says, this business of &lsquo;sharing&rsquo; your life with someone. And  she lifts her hands out of the covers to hook index fingers around the word.  What is it good for? she asks, this telling of the things you did, the things  that happened. Why do we do it? So the telling can tame the happening, the  strangeness of experience, and ease it into the order of your shared life? Like  writing the essay after reading the book: Discuss the role of chocolate  brownies in Jane&rsquo;s day, she mocks. Perhaps if you were to keep it to yourself,  undiluted, you&rsquo;d deal quite differently with the dangers that breed in the day.<br>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Drew looks into her eyes, smiling. He smooths back  her hair. You&rsquo;re crackers, he says. Take it easy man, things happen, or we make  things happen, and the talking is okay only if you feel like it. Listen, he  yawns, there&rsquo;s a whole hour left before we get ready for dinner, please can we  stop talking now, and hardly has he spoken before his breathing softens into  sleep. When he wakes he says, You must have understood what the hooded girls  were saying. No, she says, really, not a word. They just stopped in their  tracks at the sight of me and started laughing and shouting.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Say shibboleth, he says, and she says, Sibboleth.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The next day it is Drew who suggests they do the  Mackintosh architecture together. They visit the School of Art where she waits  patiently while he examines the building in tiring detail. But at the  Mackintosh House it is Jane who lingers, marvelling at the design of furniture  and fabric and the simple magic of white gauze. That&rsquo;s it, she says, I&rsquo;m going  to take down those curtains in the flat; it&rsquo;s going to be all white gauze and  diffused Cape light, and Drew laughs, Look who cares about d&eacute;cor all of a sudden.  Jane has always deferred to him in such matters.&nbsp; Watch me, she says, I&rsquo;m going shopping this  afternoon with my credit card.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; It is  that afternoon that Drew finishes the alteration of the book. There are now two  title pages: <em>The One That Got Away</em>, and another before it that reads in  the same typeface: <em>Gold Mining on the Rand: 1886 &ndash; 1899 by Gavin Wilton. </em>He  chuckles at the thought of old Wilton finding his name attached to a novel.  With the book in a plastic bag, Drew goes to Dennistoun library on the next  street, and has no difficulty slipping it into the fiction section between  Wickham and Witworth. There are only two people in the reading room and they  are stationed in front of computers. An attendant at the front desk is cleaning  his nails. Drew nods briefly, formally, at the row of books and leaves. There  is the satisfaction, but also the sense of loss that goes with finishing a  project. Done, he says. He must have said it out loud, since one of the people  at the computer looks up, and he leaves. The book has been returned to the  library from which it was borrowed. Nothing major, Drew thinks, just a modest  little project to go with a wittebrood. Before they go home he&rsquo;ll take Jane to  the library; he will have to think of something to ensure that she takes the  book from the shelf.</p>
            <p>&nbsp;</p>
            <p>We sit in the twilight, the hour of forenicht, on the  stoep looking out at Table Mountain on fire. Tonight&rsquo;s news says that a British  tourist has set it alight with his cigarette. When the others go in to get  drinks I ask Drew what he thinks. He fishes the typescript out of his bag and  hands it over. I had imagined that he would keep it.<br>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; It&rsquo;s okay, he says, even if it&rsquo;s hardly a subject for  a story. Really, it was just idle chat, just another event amongst things that  happened on the honeymoon. He didn&rsquo;t think that someone would weave an  elaborate story around it, hadn&rsquo;t imagined himself and Jane as characters in  someone&rsquo;s story.<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  It is difficult not to be offended, difficult not to  be defensive. Well, it&rsquo;s obviously not about you, or the two of you; it&rsquo;s just  that I used your project &ndash; as one does, I add lamely. I just thought you&rsquo;d find  it amusing to see what I came up with.<br>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Ja, it&rsquo;s okay, Drew repeats, shaking his head. Ag, I  don&rsquo;t know, can&rsquo;t put my finger on it; I&rsquo;ve always been rubbish with words.  Perhaps it&rsquo;s the casting into words that seems to make a song and a dance about  something that was not meant to be weighty. Now tamed further in the telling,  as <em>your </em>Jane would say. All Chinese boxes hey, where will it all end?<br>
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   There is a terrifying, cracking sound of fire, and a  flare from the mountain lights both our faces.</p>            <P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
