<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue9/menu_issue9.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue9/jorge_edwards/artwork.html','','width=575,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="292" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">A Reading of Things (1988) <span class="texto2">an essay by <a href="../../issue9/jorge_edwards/bio.php" class="link3">Jorge Edwards</a><br>Translated from the Spanish by <a href="http://interlitq.org/staff/peter_robertson/bio.php" class="link3">Peter Robertson</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
           &nbsp;<br>
              <p><em>In this essay, the Chilean  author, Jorge Edwards analyses the profound changes experienced by his literary  generation. These changes, reflected in narrative perspective, in its sources  and aspirations, underscore the fact that writers of his generation have  transcended the confines of&nbsp;&ldquo;Criollista&rdquo; and regional literature, the exponents&nbsp;of  which, in addition to their other characteristic features, were noteworthy for&nbsp;a  strange but unmistakable rift between their personal experience and their  literary style. This new generation, on the other hand, has chosen an  all-embracing&nbsp;surrealism to the detriment of social realism and has  elected to fashion its own creative language. Fallen heroes and anti-heroes now  people this new narrative that, with a nostalgic and almost utopian posture-in  drawing a clear demarcation between separate geographic environments and  disrupting the linear passage of time- aspires to metaphor, not being content  to be&nbsp;a mere transcription of the unbearable present. </em></p>
</div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <br><p>When I started writing in my adolescence, at the end of the 1940s, the  official literary world was dominated in Chile by the  so-called &quot;Criollista&quot; novel. Almost all of the authors who belonged  to this movement, each in their turn and without stealing one another's thunder  too much, had obtained the National Literature Prize. The most important &ldquo;Criollista&rdquo;&nbsp;texts  had been included in anthologies and State teaching programs. At&nbsp;literary  salons presided over by these authors, and even in routine urban settings, one  came up against characteristic figures such as Luis Durand,  Mariano&nbsp;Latorre or Eduardo Barrios. Augusto D'Halmar and  Joaquin&nbsp;Edwards Bello, who had experimented with&nbsp;somewhat different  narrative forms, were by now writing articles solely for newspapers,&nbsp;One  used to see them walking through the city streets resembling nothing so much as  human relics. The Manuel Rojas of that era, the creator of &quot;Lanchas en la  bahia&quot; (Boats&nbsp;in the Bay) and &quot;El Vaso de leche&quot; (The Glass  of Milk), anticipating&nbsp;&quot;Hijo de ladron&quot;&nbsp;(The Son of the  Thief), gave the impression of being a slightly updated manifestation--albeit a  pale imitation--of his predecessors.</p>
            <p>Nicomedes&nbsp;Guzm&aacute;n&nbsp;and  Juan Godoy, the leading novelists of the generation of 1938, who cultivated a  curious blend of populism and imagism, had succeeded in occupying a cult niche.  There&nbsp;was no escaping the achievements&nbsp;of the great poets but their  work&nbsp;received a more mixed&nbsp;reception, one of irritation and even  mockery. When Vicente Huidobro some years before, had published his review  &quot;Ombligo&quot; (Navel), Alone (also known as Hern&aacute;n D&iacute;az Arrieta) in an  article in &quot;El Mercurio&quot; derided the publication as an invisible and  insignificant organ that richly deserved the name that had been given to it. </p>
             <p> Seen from the  vantage point of that period, the work of the &ldquo;Criollista&rdquo;&nbsp;and regionalist  writers, whom I read more than anything chiefly&nbsp;because they were forced  on me at school, suffered from a kind of split personality. There was a gulf  between the personal experience of these novelists and the material that found  its way into&nbsp;their writing. And this was completely the opposite from the  artistic methods of&nbsp;a Proust, a Faulkner or a James Joyce. The  &quot;quality of experience&quot; that Joyce spoke about was conspicuous by its  virtual absence from the pages of our regional writers who happened to  be&nbsp;University lecturers, public civil servants, immersed&nbsp;in the life  and problems of the urban middle class who left at the weekend for the countryside,  armed with their notebooks and engaging in rather pedestrian literary efforts.&nbsp;Their  narratives provided a detailed portrayal of our rural customs, our  colloquialisms, our landscapes, our flora and fauna. The texts they produced  were slow and&nbsp;challenging documents, as all such laundry lists&nbsp;tend  to be, but their authors&nbsp;thought that they were carrying out a valuable  social function and they were granted fitting public recognition as a result. I  had long suspected that these authorial practices carried a deeper message for  young aspiring writers: being a writer and being a Chilean writer are two  different things. If the &ldquo;Criollista&rdquo;&nbsp;description of country villages,  instead of pointing us in the direction of a universal message, made us imagine  ourselves in the role of local village dignitaries, then we had to be resigned  to accept our fate with the proviso that our national literary agenda, our  cultural norms, obliged us to leave behind our real-life home village which  was, in fact, not a village at all but&nbsp;a district of the city of Santiago. </p>
            <p>  From the  beginning, and as a reaction against this environment, we rejected these older  Chilean novelists, proclaiming that we were completely indifferent to them, and  we pursued our own intensely personal odyssey that strayed far from the conventional:  Rimbaud and James Joyce, Aloysius Bertrand and Jules Laforgue, Kafka and Jorge  Luis Borges, the poetry of &quot;Residencia en la Tierra&quot;, &quot;Ecuatorial&quot; and  &quot;Altazor&quot;, part of the work of Gabriela Mistral, especially the early  poems of &quot;Tala&quot;, some texts by our avant-garde&nbsp;writers and the  novels of a notably unsung&nbsp;writer, Maria Luisa Bombai. Now, looking back,  I find&nbsp;that some examples of poetry by the young Neruda, sequences with  surrealist undertones, determined our attitude, left their stamp on us, marking  us because they seemed to us to be recognizable, far more so&nbsp;than the vast  geographical spaces&nbsp;of the &ldquo;Criollista&rdquo; novel. We were not especially  interested, for example,&nbsp;in geographical features that were a hallmark of &ldquo;Criollista&rdquo;  fiction, such as the&nbsp;mouth&nbsp;of the river&nbsp;Maule&nbsp;but these  other types of literature that I have just mentioned did indeed resonate&nbsp;with  us. I am talking, of course, about the hair-dressers and cinemas of  &quot;Walking Around&quot;, that &quot;terrible abandoned dining room with the  shattered olive oil jars&nbsp;and vinegar trickling&nbsp;under the chairs&quot;  of &quot;Melancolia en la familia&quot; (&quot;Melancholy in the family&quot;).  If the poet spoke to us about &quot;white water-closets awakening with wooden  eyes, like one-eyed pigeons&quot; we were plunged into the most sensitive and  most familiar part of our world, near the juxtaposition of&nbsp;a comfortable  Louis XV sofa and a quince mould in the shape of an elephant, of a dining room  leading into&nbsp;a back patio, where an old man would come to sell lemons,  where a child from the south would hang up clothes, where hens and even rabbits  were in plentiful supply. </p>
          <p>   We lived in  large houses deep in the shadows, among objects suffering from various degrees  of moth-eaten dilapidation, surrounded by people who were&nbsp;discreetly  eccentric and the vision of the deterioration of things, obscurely prophetic in  &quot;Residencia&quot; by Neruda, nostalgic in the work of&nbsp;Gabriela  Mistral, patently&nbsp;apocalyptic in &quot;Ecuatorial&quot; by Huidobro,&nbsp;was  of decisive importance&nbsp;in our formative literary years. It is not  surprising that the scenarios from our first tales disregarded&nbsp;the  countryside and nature in favor of cities and were, to some extent, artificial.  Artifice entered then into our narrative and developed later, not as a complete  rejection of realism but rather as a subversion of it: machines that were not  lifelike, waxworks, automata, literary characters who leave a sulphurous trail  in their wake. I suspect now that Neruda's shift  from&nbsp;&quot;Residencia&quot; to &quot;Canto General&quot; &nbsp;can be  interpreted, at least on&nbsp;some level, as an effort to flee from artifice, a  flight that was experienced in a state of&nbsp;anxiety and as&nbsp;a search for  nature. Strange as it may seem, this social and epic realism was a kind of  flash in the pan that did not really catch on among important writers in Chile </p>
            <p>The authors of the next generation tried, on the other hand, to build  unstoppable momentum for their literary movement. In terms of narrative, they  tended to practice what came to be referred to as &quot;articulated surrealism&quot;,  transcending prosaic literary output while building fantastic yet at the same  time rational settings, thereby attempting to unite delirium and logic. I am  thinking here, especially, about Braulio Arenas' narrative. The stories of the  young Eduardo Anguita were more dreamlike, less consciously constructed. <br>
              <br>
              Now, the change of landscape in prose, the abandonment of the natural and  ever-popular literary checklists associated with the &ldquo;Criollista&rdquo; style, the  relative indifference to the epic dimension of Neruda, implied a decisive  change with regard to language. It is a change that took place, before and  afterwards, in different contexts and with different shades of meaning, within  the totality of Latin American narrative and which indicated that this literature  held the potential to transcend boundaries. It opened up the possibility that  it would use its own language, one that was autonomous, creative. What  happened, as has often been said, is that the regional or &ldquo;Criollista&rdquo; novel,  in Chile and the rest of  America, operated on  two levels that were different and poorly unified from the writing perspective.  On the one hand, you had the&nbsp;language of the narrative voice, that  supposedly reflected the language of the Spanish homeland and the <em>real academia</em>; and, on the other hand,  you had the colloquialisms favored by popular figures, <em>huasos, afuerinos, pirquineros, gauchos</em>, determined by the Latin  American diversity, influenced by voices and in certain cases by&nbsp;indigenous  rhythms. </p>
            <p>Perhaps &quot;Don Segundo Sombra&quot;, written by the Argentine author,  Ricardo G&uuml;iraldes, is the novel that came the closest during this period to  achieving a modicum of verbal cohesion but it was tarnished by traces of the  excessively adorned&nbsp;prose bequeathed to us by&nbsp;modernism. The  overriding impression of this period, however, was that of a poorly thought-out  juxtaposition, an indigestible fusion of disparate elements where both extremes  were characterized by rigidity, by an alien tone of insincerity. For example,  if I flip open the pages of Mariano Latorre&rsquo;s &ldquo;Cuentos del Maule&rdquo;, my ears are  assailed by the monotonous and desultory voice of the boy who asks once again: <br>
  &quot;Where  might &lsquo;ister Lillo be going, &lsquo;issus&nbsp;Juana?&quot; <br>
              The omniscient  narrator, who himself uses&nbsp;the correct Spanish of the introductory phrase,  when seated at his desk endeavours ever so paternalistically to reproduce the &ldquo;mestizo&rdquo;  dialect spoken by his literary characters.</p>
              <p>In order to transcend this overly academic approach  tinged with populism, many authors of my generation, and the immediately  preceding one, in many different points of America, and with varying degrees of  awareness of the problem, tried to incorporate into their prose the most  original and creative form of&nbsp;writing closest to hand and&nbsp;that was  not, especially in the case of Chile, achieved&nbsp;by novelists but  by&nbsp;poets in their most experimental and innovative phase, from Ram&oacute;n L&oacute;pez Velarde up to C&eacute;sar Vallejo,  Huidobro and Neruda. To give a personal example, my descriptions of sordid  bureaucracy, in &quot;El Peso de la Noche&quot; (The Weight of the Night) had, of  course, some roots in Kafka, as well as in Jaime Laso's &quot;El Cepo&quot;  (The Trap) but also had some elements that could be found in the verses  &quot;Walking around&quot; and &quot;Desespediente&quot;, two central poems  of&nbsp;&quot;Residencia de la Tierra&quot;. For this narrative language,  images such as &quot;the shadow of the administrations&quot;, the  &quot;delicate pale color of the managers&nbsp;&quot;&nbsp;and those &quot;deep  tunnels like calendars&quot; in &quot;Desespediente&quot;, that pigeon with &ldquo;a  complexion resembling blotting paper&nbsp;whiter than a corpse and  panic-stricken inks befitting its color&quot; had a perfect sense that was  valid and that could be put to good literary use. Our initial experience of  things that have deteriorated, of crumbling&nbsp;walls, the mansions&nbsp;in  shadow, can be connected with a poetic antecedent that is very close to hand.  To incorporate this verbal landscape into&nbsp;narrative prose is to plunge  into modernity in the sense that the language of a novel demands autonomy, an  internal coherence, a rhythm, that bring it close to a poem-in-prose. By now we  had affinities with&nbsp;Flaubert, that great fount of inspiration, and his  literary family, with William Faulkner and James Joyce, among others. </p>
           <p>   When we talk  about transcending a two-dimensional belief system and moving toward a truly multidimensional  experience, about beating a hasty retreat from an awkward fusion of disparate  elements and embracing a true synthesis, we have gotten to the very heart of  the literary problems confronting my generation. I believe that the approach  that I have outlined here holds the greatest potential for clarifying the  trends toward greater convergence and concordance in modern-day Latin American  narrative.</p>
            <p>The search for a  language and its unity is necessarily the search for something greater, a more  far-reaching unity. In the case of the Chilean generation we talk at least  about a &quot;literature of decrepitude&quot; but now let us look at what this  term means. By definition,&nbsp;decrepitude is an &quot;impure&quot; concept  that invades territories extraneous to the purest verbal and aesthetic forms.  It implies a value judgment, an historical perspective, a position vis-&agrave;-vis  the past. Accordingly, it was quite possible to talk about&nbsp;&quot;a  literature of decrepitude&quot; in relation to the poetry in &quot;Residencia&nbsp;  en la Tierra&quot;  by&nbsp;Neruda, in &quot;Ecuatorial&quot;,&nbsp;by Vicente Huidobro, a poem  by&nbsp;an American that looks with innocent and haunted eyes at the spectacle  of the destruction of the world after the 1st world war. These were eyes  untouched by evil that were confronted with the Apocalypse.&nbsp;This was not  so far removed, after all, from the inspiration of a Kafka or of&nbsp;German  expressionist painters. That leitmotif, then, of the degradation  of&nbsp;things, of decrepitude as an obsessive theme,&nbsp;pointed to&nbsp;an  older phenomenon, more profound and more universal than it appeared at first  sight. Critics, not very imaginative at the best of times, typically inclined  toward the novel and the exotic, failed to grasp the sense of decay in Latin  America, of the new that was prematurely aged&mdash;a phenomenon that was nonetheless  captured with considerable acuity by a man who came from another intellectual  discipline, as is the case with&nbsp;Claude Levi-Strauss in &quot;Tristes  Tropicos&quot; (Sad Tropics). Moreover, that concept of the degradation of  things, so&nbsp;paradoxically fundamental in the literature of the New World,  by virtue of referring to the end of a process, drew the reader&rsquo;s attention to  a corrosive action that had occurred at a specific moment in time, to the idea  of a status quo ante, or pre-existing situation and the disruption of that  world view. In other words, it implied the mythical idea of a lost world and a  fall, the notion of Paradise Lost and that of Adam, the tragic hero <em>par excellence</em> of our whole Christian  culture. </p>
            <p>The heroes or  the anti-heroes of our narrative, bewildered children, old people who are cut  adrift, women who are gently eccentric, men incapable of joining the age of  enlightenment, tend to be unregenerate individuals, like Adam in the Garden of  Eden,&nbsp;who are more or less at sea, confused, nostalgic, belonging to an  idyllic age that is progressively fading from their memory, and perhaps the  truth is that they are not quite sure if it ever really existed. We have such  &quot;Adams&quot; in Buenos Aires, &quot;Adams&quot; in Santiago in the extreme  north of Chile&nbsp;and in Lima, that dreadful city,&nbsp;in the warm Colombian  lands and in the shimmering high-altitude regions The attitude of Adam, the  founder, initiator of history and of historic time, given that our notion of  time is in fact a reflection of our status as degraded beings, is a necessary  by-product of the original fall of man&nbsp;and&nbsp;is repeated in a quite  extraordinarily insistent fashion, in the poetry and novels of the Americas.  This attitude presupposes, together with the&nbsp;inevitable nostalgia, the rejection  of the present and the temptation, the giddy attraction of Utopia. The  hankering after a pre-lapsarian state is converted into efforts to imagine and  yearn for&nbsp;a future Paradise. What we cannot  abide is&nbsp;the present and the gateway to the future entails inevitably apocalyptic  consequences. We find ample confirmation of this realization&nbsp;in the vision  of Christopher Columbus revealed to us in &quot;Los Perros de Paradiso&quot;  (The Dogs of Paradise) by the Argentine author,&nbsp;Abel Posse. </p>
            <p>The anti-hero or, rather, the hero who has fallen into  disgrace, can leave an orderly and traditional world, put on a mask of  aggression, contorted into blind fury, end up in&nbsp;prison and in that  subterranean world, in that visit to hell, undergo an earth-shattering  conversion experience. After having served his sentence for a crime that is  essentially a reflection of class-based oppression, he will return to the light  of day transformed into a saintly revolutionary figure, an archetypal  communist, a radical in communion with nature and closely identifying&nbsp;with  beings that he had previously looked down upon from his class-based vantage  point: fishermen, country-dwellers, construction foremen. And this will  continue until the real revolution comes, or at least a pre-revolutionary  situation has arrived&nbsp;and this character puts on his more traditional  attire, his collar and tie, to take up a post in an agrarian reform  organization or, in other words, to collectivize the lands of his ancestors in  order to bring to a close, along with his own personal journey, the historical  cycle of the indentured servitude of the native peoples of Latin America. But  the crux&nbsp;of the novel, with the defeat of the Revolution, will have to  culminate in a further turn of the screw, another crisis of personality&mdash;a  personality that will at last be fully formed and which will accordingly reveal  its tragic dimension, the sudden twist of fate&nbsp;transformed into destiny.&nbsp; </p>
           <p>   I have allowed  myself to use&nbsp;the structural framework of one of the stories of my novel  &quot;Los convivados de piedra&quot; (&quot;Stone Guests&quot;).&nbsp;However,  this journey, this cycle, with its starting point, its descent into the regions  of Hades, its return, or should I say its re-emergence, in another landscape  and another story, reflecting the classical trajectories&nbsp;of Western literature&mdash;this  pattern which I have just described&nbsp;is to be found in many narrative Latin  American texts. If the writer, as Roland Barthes has said, is a public  experimenter who engages in an endless variations on a theme and who only knows  that one art and that alone, the same can be stated of the full range&nbsp;of  Latin American literature that, in its turn, is a variation &ndash;sometimes one that  is surprising and unexpected &ndash; on the central themes of European literature. </p>
            <p>
              We recreate  European literature in America but with subtle  variations upon a theme, and we in Latin America&nbsp;are, in  comparison with the way things are done in Europe, public and  inveterate experimenters and to a considerable extent we subvert the European  norm.&nbsp;The difference in geographical settings is complicated and deepened  by the superimposition of different historic timescales. The &quot;war of  time&quot;, to use a phrase and title employed by Alejo Carpentier, is  recreated in all our texts. The era&nbsp;of the Colony, of the stagnant Tradition,  of the Restoration, is insulated, captured in a time capsule, overshadowed by  the discombobulating menace of the revolutionary period. We flit back and forth  in a time warp between the Garden of Eden on the one hand, and historic time on  the other hand, and these gyrations for us are never something normal, rather  they are too slow or too quick for our taste, as they reflect an urge to  restore the past or impose an outcome on the future; I am talking about&nbsp;a  past which for&nbsp;the human&nbsp;imagination, for innermost personal  aspirations, has a tendency to&nbsp;invoke a bygone paradise, and I am  referring to a future that has comparable aspirations, albeit for the opposite  reasons. </p>
            <p>We rely on the  devices&nbsp;of our poetic avant-garde&nbsp;which is not as new as we would  like to believe and that includes that vision of pampas and of large estuaries  that had such a significant impact on the prose style&nbsp;of Isidore Ducasse,  the Count of Lautr&eacute;amont,. We do this in our effort to identify the creative  unity of our language but in using that language we enter, inevitably, into the  territory of dichotomy and conflict or,&nbsp;according to Sarmiento,  civilization and barbarism. The idea of the&nbsp;&quot;war of  time&quot;&nbsp;complemented by the notion of the primal vastness of our  wide-open spaces here in Latin America (&quot;Before the invention of the wig  and the frock coat there were the rivers, and waterways&hellip;&quot;) is more subtle  and more judicious especially as&nbsp;we do not know exactly where the  barbarians are&nbsp;or rather we suspect, all&nbsp;too often, that they are not  precisely where we suppose them to be, in the New World. </p>
             <p> This dualistic universe leads us to never-ending  twists and turns and optical illusions. Faced with these polar&nbsp;opposites  that haunt us obsessively (past and future), we can see looming before us a  present that is always unsatisfactory and often devastating, terrible to  behold. Because of this the novel, in Latin America, will never be  content with holding up a mirror to reality&mdash;the role foisted on it by the 19th  century realist movement. The novel is not and cannot be a mere checklist, as  our regionalist authors suppose. Conversely, the novels from our region aspire  to achieve the status of parables (which, you could argue, is simply another  way of holding up a mirror to reality) and to exorcise the demons that plague  us in the intolerable present moment; I am referring to the phantoms  that&nbsp;are inside us all&nbsp;and that are also disguised or deeply embedded  in our surrounding environment, poised to strike as in the ancient legends of  yore. </p>
<P><strong>Lección de cosas</strong></P>
<P><em>En este  ensayo, el autor analiza los profundos cambios que ha experimentado la  generaci&oacute;n literaria a la que &eacute;l pertenece. Variaciones reflejadas en la  perspectiva narrativa, en sus fuentes y finalidades, indican que los escritores  de su generaci&oacute;n han dejado de lado la novela criollista y regionalista, cuyos  representantes, adem&aacute;s de otras peculiaridades, denotaban cierta disociaci&oacute;n  entre experiencia personal y el estilo de sus obras. Esta nueva generaci&oacute;n, en  cambio, ha elegido el surrealismo articulado, en desmedro del realismo social.  Ha preferido un lenguaje m&aacute;s propio y creativo. H&eacute;roes ca&iacute;dos en desgracia o  antih&eacute;roes pueblan ahora esta narrativa que, con una actitud nost&aacute;lgica casi  ut&oacute;pica, diferenciando espacios geogr&aacute;ficos y dislocando tiempos hist&oacute;ricos,  aspira a convertirse en par&aacute;bola, y no ser, simplemente, mero reflejo del  intolerable presente. </em></P>
<p>Cuando comenc&eacute; a escribir en mi  adolescencia, a fines de la d&eacute;cada del cuarenta, el mundo literario oficial  estaba dominado en Chile por la llamada novela criollista. Casi todos sus  autores, en forma escalonada y sin excesivos tropiezos, hab&iacute;an obtenido el  Premio Nacional de Literatura. Sus principales textos se hab&iacute;an incorporado a  las antolog&iacute;as y a los programas estatales de ense&ntilde;anza. En las tertulias, y  hasta en el paisaje urbano, uno tropezaba con las figuras caracter&iacute;sticas de un  Luis Durand, un Mariano Latorre o un Eduardo Barrios. Augusto D&acute;Halmar y  Joaqu&iacute;n Edwards Bello, que hab&iacute;an ensayado formas narrativas algo diferentes,  ya s&oacute;lo escrib&iacute;an art&iacute;culos para los peri&oacute;dicos. Uno los ve&iacute;a pasar por la  calle en calidad de reliquias, de leyendas vivientes. El Manuel Rojas de  entonces, el de <strong>Lanchas en la bah&iacute;a</strong> y <strong>El vaso de leche</strong>, anterior  a <strong>Hijo de ladr&oacute;n</strong>, daba la impresi&oacute;n de un ep&iacute;gono un poco modernizado.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nicomedes Guzm&aacute;n y Juan Godoy, los  novelistas de la generaci&oacute;n del 38, que cultivaban una mezcla curiosa de  populismo e imaginismo, hab&iacute;an conseguido ocupar un espacio marginal, conocido  por minor&iacute;as. No se pod&iacute;a ignorar a los grandes poetas, pero su obra era objeto  de una recepci&oacute;n m&aacute;s bien dividida, irritada, burlona. Cuando Vicente Huidobro,  en a&ntilde;os anteriores, public&oacute; su revista <strong>Ombligo,</strong> Alone habl&oacute; en El  Mercurio del autor de una publicaci&oacute;n tan invisible y tan insignificante como  la parte del cuerpo que designaba con su nombre.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Desde mi perspectiva de esos a&ntilde;os, la  obra de los criollistas o regionalistas, que le&iacute; m&aacute;s que nada por obligaci&oacute;n  escolar, planteaba una dicotom&iacute;a curiosa, un fen&oacute;meno semejante a una  esquizofrenia. Hab&iacute;a una evidente disociaci&oacute;n entre la experiencia personal de  estos novelistas y su escritura. Todo lo contrario de lo que uno encontraba en  las p&aacute;ginas de un Proust, de un Faulkner, de un James Joyce. Esa &quot;cualidad  de la experiencia&quot;, de que hablaba Joyce, brillaba en las p&aacute;ginas de  nuestros regionalistas por su ausencia casi completa. Eran profesores  universitarios, funcionarios p&uacute;blicos, sumergidos en la vida y en los problemas  de la clase media urbana, que sal&iacute;an de fin de semana al campo, armados de un  cuaderno de apuntes y dedicados a cumplir con un trabajoso programa. En sus  narraciones aparecer&iacute;a un minucioso inventario de nuestras costumbres  campesinas, nuestras formas populares de hablar, nuestros paisajes, nuestra  flora y nuestra fauna. Eran textos lentos y opacos, como lo son,  inevitablemente, todos los inventarios, pero se pensaba que cumpl&iacute;an una  funci&oacute;n social y se les otorgaba el reconocimiento p&uacute;blico adecuado. Siempre  sospech&eacute; que hab&iacute;a en todo esto una advertencia impl&iacute;cita dirigida al joven  aspirante: no es lo mismo ser escritor que ser escritor chileno. Si la  descripci&oacute;n de la aldea, en lugar de conducimos a la universalidad, nos  convert&iacute;a en notables de la aldea, estaba bien y ten&iacute;amos que resignarnos. Con  la salvedad de que el programa, la norma, nos obligaba a salir de nuestra  verdadera aldea, que era, en realidad, un barrio de la ciudad de Santiago.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Desde los comienzos, por reacci&oacute;n  contra ese ambiente, renegamos de los novelistas chilenos mayores, proclamamos  nuestra perfecta indiferencia frente a ellos, y seguimos una l&iacute;nea de lecturas  personales, heterog&eacute;neas, m&aacute;s o menos exc&eacute;ntricas: Rimbaud y James Joyce,  Aloysius Bertrand y Jules Laforgue, Kafka y Jorge Luis Borges; la poes&iacute;a de <strong>Residencia  en la tierra</strong>, la de <strong>Ecuatorial</strong> y <strong>Altazor</strong>; parte de la obra de  Gabriela Mistral, sobre todo los poemas iniciales de <strong>Tala</strong>; algunos  textos de nuestros escritores de vanguardia, y las novelas de una ausente  notable, Mar&iacute;a Luisa Bombal. Ahora, en la reflexi&oacute;n retrospectiva, llego a la  conclusi&oacute;n de que algunos escenarios de la poes&iacute;a del joven Neruda, escenarios  ligados, de alg&uacute;n modo, al surrealismo, determinaron nuestra actitud, nos  marcaron, y nos marcaron porque nos parec&iacute;an reconocibles, mucho m&aacute;s  reconocibles que los espacios despoblados de la novela criollista. No nos  interesaba especialmente la desembocadura del r&iacute;o Maule, pero nos dec&iacute;an algo,  ten&iacute;an un significado para nosotros, esas peluquer&iacute;as y esos cines de <strong>Walking  around</strong>, ese &quot;terrible comedor abandonado, /con las alcuzas rotas/ y el  vinagre corriendo debajo de las sillas&quot;, de <strong>Melancol&iacute;a en la familia</strong>.  Si el poeta nos hablaba de &quot;waterclosets blancos despertando/ con ojos de  madera, como palomas tuertas&quot;, nos situ&aacute;bamos de inmediato en el centro  m&aacute;s sensible y m&aacute;s familiar de nuestro mundo, cerca del encuentro de una c&oacute;moda  Luis XV con un molde de dulce de membrillo en forma de elefante, de un comedor  normando con un patio trasero, donde llegaba un viejo a vender limones, donde  colgaba ropa una ni&ntilde;a del sur, donde hab&iacute;a gallinas y hasta conejos.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Viv&iacute;amos en caserones en penumbra,  entre objetos m&aacute;s o menos apolillados, rodeados de personas discretamente  extravagantes, y la visi&oacute;n del deterioro de las cosas, oscuramente prof&eacute;tica en  el Neruda de Residencia, nost&aacute;lgica en Gabriela Mistral, francamente  apocal&iacute;ptica en el Huidobro de Ecuatorial, fue determinante en nuestros a&ntilde;os de  formaci&oacute;n. No es sorprendente que los escenarios de nuestros primeros relatos  no hayan sido campestres y naturales sino urbanos y, en cierto modo,  artificiales. El artificio ingres&oacute;, entonces, a nuestra narrativa y se  desarroll&oacute; m&aacute;s tarde, no como un rechazo total del realismo, sino m&aacute;s bien como  una perversi&oacute;n suya: m&aacute;quinas inveros&iacute;miles, figuras de cera, aut&oacute;matas,  personajes que dejan tras de s&iacute; una estela inconfundible de azufre. Sospecho,  ahora, que el paso en Neruda de Residencia a Canto General puede interpretarse,  por lo menos en alg&uacute;n nivel, como una huida del artificio, una huida  experimentada con angustia, y una b&uacute;squeda de la naturaleza. Aunque parezca extra&ntilde;o,  ese realismo social y &eacute;pico fue una especie de culminaci&oacute;n aislada, que no tuvo  seguidores importantes en Chile.<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Los autores de la generaci&oacute;n siguiente  intentaron, por el contrario, consolidar la vanguardia. En la narrativa,  tendieron a practicar aquello que se ha denominado &quot;surrealismo  articulado&quot;, dejando de lado el dictado autom&aacute;tico y construyendo espacios  fant&aacute;sticos y a la vez racionales, intentando unir el delirio y la l&oacute;gica.  Pienso aqu&iacute;, sobre todo, en la obra narrativa de Braulio Arenas. Los cuentos de  juventud de Eduardo Anguita eran m&aacute;s on&iacute;ricos, menos construidos.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Ahora bien, el cambio de escenario en  la prosa, el abandono de los inventarios naturales y populares del criollismo,  la relativa indiferencia frente a la vertiente &eacute;pica de Neruda, implicaron un  cambio decisivo frente al lenguaje. Es un cambio que se produjo, antes o  despu&eacute;s, en diferentes contextos y con diferentes matices, en el conjunto de la  narraci&oacute;n latinoamericana, y que abri&oacute; la posibilidad de que esta literatura  saliera de las fronteras. Abri&oacute; la posibilidad de que utilizara un lenguaje  propio, aut&oacute;nomo, creativo. Lo que suced&iacute;a, como ya se ha dicho a menudo, es  que en la novela regionalista o criollista, en Chile y en el resto de Am&eacute;rica,  se daban dos niveles diferentes y mal unificados de escritura: el lenguaje de  la voz narrativa, que supuestamente correspond&iacute;a al castellano de Castilla y de  la Academia, y el de los personajes populares, huasos, afuerinos, pirquineros,  gauchos, determinado por la diferencia latinoamericana, influido por voces y  hasta por ritmos ind&iacute;genas. Quiz&aacute;s <strong>Don Segundo Sombra</strong>, del argentino  Ricardo G&uuml;iraldes, es la novela que m&aacute;s se acerc&oacute; en ese per&iacute;odo a una cierta  unidad verbal, pero estropeada por resabios de la prosa adornada que nos leg&oacute;  el modernismo. Lo que dominaba, era sin embargo, una yuxtaposici&oacute;n mal avenida,  un sincretismo donde no exist&iacute;a ni el asomo de una s&iacute;ntesis y donde ambos  extremos se caracterizaban por su rigidez, por su tono impostado, ajeno. Por  ejemplo, abro una p&aacute;gina cualquiera de <strong>Cuentos del Maule</strong>, de Mariano  Latorre:<br>
  La voz desganada y mon&oacute;tona del  muchacho volvi&oacute; a preguntar: <br>
  &ndash; Par&acute;onde ir&iacute;a don Lillo, o&ntilde;a Juana? <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  El narrador omnisciente, el que utilizaba el  castellano correcto de la frase introductoria, reproduc&iacute;a desde su escritorio,  con una sonrisa paternal, la lengua mestiza de sus personajes.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Para superar ese academismo doblado de  populismo, muchos autores de mi generaci&oacute;n o un poco anteriores, en diversos  puntos de Am&eacute;rica, con mayor o menor conciencia del problema, intentaron  incorporar a la prosa la escritura m&aacute;s original, m&aacute;s creativa, que se hac&iacute;a  entre nosotros, y que no era, sobre todo en el caso de Chile, la de los  novelistas, sino la de los poetas en su fase m&aacute;s experimental e innovadora,  desde Ram&oacute;n L&oacute;pez Velarde hasta C&eacute;sar Vallejo, Huidobro y Neruda. Para citar un  ejemplo personal, mis descripciones de la sordidez burocr&aacute;tica, en <strong>El peso  de la noche</strong>, llevaron, desde luego, alguna huella de Kafka, como las de  Jaime Laso en <strong>El cepo</strong>, pero tambi&eacute;n arrastraron elementos que se pod&iacute;an  encontrar en los versos de <strong>Walking around</strong> y <strong>Desespediente</strong>, dos  poemas centrales de <strong>Residencia en la tierra</strong>. Para ese lenguaje  narrativo, im&aacute;genes como &quot;la sombra de las administraciones&quot;, el  &quot;delicado color p&aacute;lido de los jefes&quot;, o esos &quot;t&uacute;neles profundos  como calendarios&quot; de Desespediente, esa paloma manchada por &quot;secantes  m&aacute;s blancos que un cad&aacute;ver, y tintas asustadas de su color siniestro&quot;,  ten&iacute;an un sentido perfectamente vigente y aprovechable. Nuestra experiencia  inicial de cosas deterioradas, de muros resquebrajados, de caserones en  penumbra, pod&iacute;a relacionarse con un antecedente po&eacute;tico muy cercano. Asimilar  ese mundo verbal en la prosa narrativa era una forma de insertarse en la  modernidad, en el concepto de que el lenguaje de la novela exige una autonom&iacute;a,  una coherencia interna, un ritmo, que lo acercan al del poema en prosa. Ya  est&aacute;bamos cerca de Flaubert, el gran precursor, y de su familia literaria, con  William Faulkner, con James Joyce, con tantos otros.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cuando hablamos de superar una  dicotom&iacute;a, de pasar de un sincretismo a una s&iacute;ntesis, entramos en la m&eacute;dula de  los problemas literarios de mi generaci&oacute;n. Creo que aqu&iacute; encontramos los puntos  de mayor convergencia y coincidencia de la narrativa latinoamericana reciente.  La b&uacute;squeda de un lenguaje y de su unidad es necesariamente la b&uacute;squeda de algo  m&aacute;s, de una unidad m&aacute;s amplia. Se habl&oacute;, por lo menos en el caso de mi  generaci&oacute;n chilena, de una &quot;literatura de la decrepitud&quot;, pero ya  vemos que ese concepto, por definici&oacute;n, es un concepto &quot;impuro&quot;, que  invade terrenos ajenos a la pura forma verbal y est&eacute;tica. Implica un juicio de  valor, una perspectiva hist&oacute;rica, una posici&oacute;n frente al pasado. Pues bien, era  perfectamente posible hablar de &quot;literatura de la decrepitud&quot; a  prop&oacute;sito de la poes&iacute;a de Residencia en la tierra, de Neruda, o de Ecuatorial,  de Vicente Huidobro, poema del americano que mira con ojos ingenuos y  espantados el espect&aacute;culo de la destrucci&oacute;n del mundo despu&eacute;s de la primera  guerra europea. Eran ojos ingenuos que contemplaban el Apocalipsis. No  est&aacute;bamos tan lejos, despu&eacute;s de todo, de la inspiraci&oacute;n de un Kafka o de los  pintores expresionistas alemanes. Esa famosa noci&oacute;n, entonces, de la  degradaci&oacute;n de las cosas, de la decrepitud como tema obsesivo, alud&iacute;a a un  fen&oacute;meno m&aacute;s antiguo, m&aacute;s profundo y m&aacute;s universal de lo que parec&iacute;a a primera  vista. La cr&iacute;tica, poco imaginativa en general, preocupada de la diferencia y  del exotismo, no comprendi&oacute; el sentido del deterioro en Am&eacute;rica Latina, de lo  nuevo prematuramente envejecido, cosa que capt&oacute;, en cambio, con gran agudeza,  un hombre que ven&iacute;a de otras disciplinas intelectuales, como es el caso de  Claude L&eacute;vi-Strauss en <strong>Tristes tr&oacute;picos</strong>. Adem&aacute;s, ese concepto de la  degradaci&oacute;n de las cosas, parad&oacute;jicamente fundamental en la literatura del  Nuevo Mundo, remit&iacute;a, por el hecho de referirse al final de un proceso, a una  acci&oacute;n de car&aacute;cter corrosivo verificada en el tiempo, a la idea de un estado  anterior, de un orden anterior y de su ruptura. Es decir, implicaba la idea  m&iacute;tica de un orden y de una ca&iacute;da, la noci&oacute;n del Para&iacute;so Perdido y la de Ad&aacute;n,  el h&eacute;roe tr&aacute;gico por excelencia en toda nuestra cultura de origen cristiano. <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Los h&eacute;roes o los antih&eacute;roes de nuestra  narrativa, ni&ntilde;os encandilados, ancianos a la deriva, mujeres suavemente  exc&eacute;ntricas, hombres que no saben ingresar bien a la edad de la raz&oacute;n, tienden  a ser Adanes m&aacute;s o menos extraviados, confusos, nost&aacute;lgicos de una edad  paradis&iacute;aca que ya no recuerdan muy bien, que quiz&aacute;s no saben si en verdad  existi&oacute; alguna vez. Tenemos Adanes Buenos Aires, Adanes de Santiago del Nuevo  Extremo y de Lima la Horrible, de las tierras calientes colombianas y de la regi&oacute;n  m&aacute;s transparente del aire. La actitud ad&aacute;nica, fundacional, iniciadora de la  historia y del tiempo hist&oacute;rico, puesto que nuestra noci&oacute;n del tiempo como  degradaci&oacute;n de las cosas es necesariamente consecuencia de la noci&oacute;n de la  ca&iacute;da original, se repite, en realidad, con extraordinaria insistencia, en la  poes&iacute;a y en la novela de Am&eacute;rica. Esta actitud supone, junto a la inevitable  nostalgia, el rechazo del presente y la tentaci&oacute;n, el v&eacute;rtigo, incluso, de la Utop&iacute;a. La nostalgia del Para&iacute;so Perdido se convierte en  imaginaci&oacute;n y aspiraci&oacute;n a un Para&iacute;so futuro. Lo intolerable es el presente y  la antesala del futuro es necesariamente apocal&iacute;ptica. Encontramos una mera  confirmaci&oacute;n de este sentimiento en la visi&oacute;n de Crist&oacute;bal Col&oacute;n que nos  entrega la &uacute;ltima novela de Abel Posse, <strong>Los perros del Para&iacute;so</strong>.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;El antih&eacute;roe, o m&aacute;s bien, el h&eacute;roe  ca&iacute;do en desgracia, puede salir de un mundo ordenado y tradicional, asumir una  m&aacute;scara de agresi&oacute;n, de furia ciega, caer a la c&aacute;rcel y experimentar en ese  subsuelo, en esa visita al infierno, una conversi&oacute;n fulminante. Despu&eacute;s de  haber cumplido condena por un delito esencialmente clasista, saldr&aacute; a la  superficie transformado en una especie de sant&oacute;n revolucionario, algo as&iacute; como  un comunista primitivo, comunista en comuni&oacute;n con la naturaleza y con los seres  que antes miraba desde su reducto de clase: pescadores, campesinos, dirigentes  obreros. Hasta que llegue la verdadera Revoluci&oacute;n, o por lo menos una situaci&oacute;n  prerrevolucionaria, y el personaje se ponga sus atuendos tradicionales, su  cuello y corbata, para ocupar un cargo en un organismo de la   Reforma Agraria,  es decir, para colectivizar las tierras de sus antepasados, para cerrar, junto  con su ciclo personal, el ciclo hist&oacute;rico de la encomienda de indios. Pero el  nudo de la novela, con la derrota de la Revoluci&oacute;n, tendr&aacute; que presentar otra vuelta de tuerca,  otra crisis del personaje, que ahora ser&aacute; definitiva y que revelar&aacute;, por eso,  su dimensi&oacute;n tr&aacute;gica, la peripecia transformada en destino.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Me he permitido utilizar la l&iacute;nea  estructural de una de las historias de mi novela <strong>Los convidados de piedra</strong>,  pero este periplo, este ciclo, con su partida, su crisis primera, su descenso a  los infiernos, su regreso, repetici&oacute;n de otra manera, en otro paisaje y otra  historia, de los periplos cl&aacute;sicos de la literatura occidental, se encuentra en  much&iacute;simos textos narrativos latinoamericanos. Si el escritor, como ha dicho  Roland Barthes, es un experimentador p&uacute;blico, que var&iacute;a lo que recomienza y que  s&oacute;lo conoce un arte, el del tema y sus variaciones, lo mismo puede afirmarse  del conjunto de la literatura latinoamericana, que, a su vez, es una variaci&oacute;n,  a menudo sorprendente, inesperada, de los temas centrales de la literatura  europea.<br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Recomenzamos la literatura europea en  Am&eacute;rica, pero variamos lo que recomenzamos, y somos, con respecto al orden de  Europa, experimentadores p&uacute;blicos y reincidentes, en buena medida  transgresores. La diferencia de los espacios geogr&aacute;ficos se complica y se  profundiza con la superposici&oacute;n de diferentes tiempos hist&oacute;ricos. La guerra del  tiempo, para emplear una frase y un t&iacute;tulo de Alejo Carpentier, se reanuda en  todos nuestros textos. El tiempo de la Colonia, de la Tradici&oacute;n estancada, de la   Restauraci&oacute;n,  se a&iacute;sla, se encierra en su c&aacute;psula, sometido a la amenaza vertiginosa del  tiempo de la Revoluci&oacute;n. Oscilamos entre la intemporalidad ed&eacute;nica y el tiempo  hist&oacute;rico, que entre nosotros nunca es normal, que es demasiado lento o  demasiado acelerado, ya que responde a la voluntad de restaurar el pasado o de  forzar el futuro: un pasado que para la imaginaci&oacute;n, para las ilusiones, suele  ser paradis&iacute;aco, y un futuro que tambi&eacute;n aspira a serlo, pero por razones  inversas. <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nos apoyamos en los modelos de nuestra  vanguardia po&eacute;tica, que no es tan nueva como solemos pensar, que incluye, por  ejemplo, esa visi&oacute;n de pampas y de grandes estuarios que alteraba la prosodia  francesa de Isidore Ducasse, el Conde de Lautr&eacute;amont, para encontrar la unidad  creativa de nuestro lenguaje, pero al utilizar ese lenguaje ingresamos,  inevitablemente, en terrenos de dualidad y de conflicto. Civilizaci&oacute;n y  barbarie, dijo Sarmiento. La idea de la guerra del tiempo, complementada por la  noci&oacute;n de la vastedad primigenia de nuestros espacios (&quot;Antes de la peluca  y la casaca /fueron los r&iacute;os, r&iacute;os arteriales...&quot;), es m&aacute;s sutil y m&aacute;s  justa, ya que no sabemos con exactitud d&oacute;nde est&aacute;n los b&aacute;rbaros, o m&aacute;s bien  sospechamos, demasiado a menudo, que no est&aacute;n precisamente donde se supone que  est&aacute;n, en el Mundo Nuevo. <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; La dualidad implica constantes  conversiones y juegos de espejos. Frente a esas ant&iacute;podas que nos obsesionan, pasado  y futuro, se alza un presente siempre insatisfactorio y a menudo devastador,  terrible. Es por eso que la novela, en Am&eacute;rica Latina, nunca puede reducirse a  ese papel de espejo que le asignaba el realismo decimon&oacute;nico. No es ni puede  ser inventario, como pensaban nuestros regionalistas. Aspira, en cambio, a  convertirse en par&aacute;bola (&iquest;espejismo?) y a exorcizar los demonios del  intolerable presente, esos demonios que est&aacute;n dentro de nosotros y que tambi&eacute;n  est&aacute;n disimulados e incrustados en las cosas que nos rodean, al acecho, como en  las viejas mitolog&iacute;as.</p>
<P></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
