<html>
<head>
<title>The International Literary Quarterly</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
<link href="../../estilos.css" rel="stylesheet" type="text/css">
<style type="text/css">
<!--
p.MsoNormal {
margin:0cm;
margin-bottom:.0001pt;
font-size:12.0pt;
font-family:"Times New Roman";
}
-->
</style>
</head>

<body>
<?php include("../../header.php"); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr> 
    <td width="10%" align="right" valign="top"> 
      <?php include("../../issue4/menu_issue4.php"); ?>
      <div align="right"></div></td>
    <td width="90%" valign="top">
<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="679">
        <!-- fwtable fwsrc="content.png" fwbase="home.gif" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="0" -->
        <tr> 
          <td><img src="/images/spacer.gif" width="10" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="192" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="17" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="205" height="1" border="0" alt=""></td>
          <td valign="top"><img src="/images/spacer.gif" width="239" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="16" height="1" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="1" border="0" alt=""></td>
        </tr>
        <tr> 
          <td><img name="home_r1_c1" src="../../images/spacer.gif" width="10" height="59" border="0" alt=""></td>
          <td colspan="4"><img src="../../images/spacer.gif" alt="" name="home_r1_c2" width="653" height="59" border="0" class="link1"></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="59" border="0" alt=""></td>
        </tr>
        <tr> 
          <td rowspan="4"><img name="home_r2_c1" src="../../images/spacer.gif" width="10" height="391" border="0" alt="Click to enlarge picture" title="Click to enlarge picture"></td>
          <td rowspan="2" valign="top"><a href="#" onMouseUp="MM_openBrWindow('../../issue4/alan_wall/artwork.html','','width=360,height=500')"><img src="art_small.jpg" alt="Click to enlarge picture." name="home_r2_c2" width="192" height="242" border="0"></a></td>
          <td rowspan="2"><img name="home_r2_c3" src="../../images/home_img/home_r2_c3.gif" width="17" height="242" border="0" alt=""></td>
          <td colspan="2" valign="top" class="titulo2">The Uses of Paranoia <span class="texto2">by <a href="../../issue4/alan_wall/bio.php" class="link3">Alan Wall</a></span></td>
          <td>&nbsp;</td>
          <td><img src="/images/spacer.gif" width="1" height="23" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="219" colspan="2" valign="top" class="texto2">  
              <p align="left"><br></p>
              <p>&lsquo;This  prophecy Merlin shall make, for I live before his time.&rsquo;</p>
              <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <em>King Lear</em></p>
              <p>In  Holbein&rsquo;s painting <em>The Ambassadors</em> in  the National Gallery in London  there is a distorted skull at the foot of the canvas. In one sense this is not  in the picture at all: it is an anamorphic projection and can only be seen if  the viewer moves over to one side of the picture and stares skewiff along it.  To see the skull you have to stop seeing the rest of the painting clearly; and  if you are seeing the rest of the painting clearly then you cannot see the  skull. You see either the living beings or the emblem of their forthcoming  death, but you cannot see both simultaneously. The ambassadors and the skull  are not viewable without a change of visionary angle. It is as though the  painting exemplifies Wittgenstein&rsquo;s observation that death is not an event  within life.</p>
          </div></td>
          <td rowspan="3"><img name="home_r3_c6" src="../../images/spacer.gif" width="16" height="368" border="0" alt=""></td>
          <td><img src="/images/spacer.gif" width="1" height="219" border="0" alt=""></td>
        </tr>
        <tr> 
          <td colspan="4" rowspan="2" valign="top" class="texto2">  
            <br><p>There  is an air of melancholy about the composition. The two figures are evidently  men of wealth and prestige, their heavy clothes and accoutrements bespeak  social status. The objects between them are instruments of power and control: a  celestial globe, a terrestrial globe, a quadrant, a polyhedral sundial, a  torquetum - these are means for mapping out the knowable universe, for  measuring heaven, earth and time. They are attributes of worldly control,  knowledge and trade, all except for the lute with its one broken string, insisting  tunelessly upon its solitary entropic message, and the crucifix which is tucked  away in a corner, out of the sway of stately power, containing its own theme of  sacrificial suffering. And of course the anamorphic skull, which requires a  change of perspective to come into focus at all.</p>
            <p>David  Gascoyne wrote in his <em>Short Survey of  Surrealism</em>: &lsquo;Dali claims that it is the paranoiac faculty that enables him  to discover a head where there was, until he looked at it, only an African  village.&rsquo; <em>Only</em> here is efficiently  employed; the paranoid vision often finds the unparanoid one curiously  impoverished. It seems to leave so much out. Dali could not have seen the shape  of the skull beneath the village, had it not been for the paranoia. And  according to T.S.Eliot:</p>
            <p>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Webster was much possessed by death<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; And saw the skull beneath the skin.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; And breastless creatures under  ground<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Leaned backward with a lipless  grin.<br>
  &nbsp;&nbsp; <br>
              To  be thus possessed by death is to be afflicted or blessed with that faculty for  anamorphosis which provides the alternative perspective in the Holbein  painting. And to view life so relentlessly skewiff is a paranoid propensity,  indeed a paranoid <em>sine qua non</em>. It  removes one from the realm of affability, with its four-square, full-frontal  progress from nativity to peripeteia. Such straightforward stories can perhaps  too often be told with the affability of self-serving cant which oils the  wheels of a rotten society, this being precisely the bone of contention between  Hamlet and his mother:</p>
            <p>&nbsp;&nbsp; <em>Queen</em>:  Do not for ever with thy vailed lids<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Seek for thy noble father in the  dust.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thou know&rsquo;st &rsquo;tis common: all that  lives must die, <br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Passing through nature to eternity.</p>
            <p>&nbsp;<em>&nbsp;Hamlet</em>: Ay, madam, it is common.</p>
            <p>Gertrude&rsquo;s  liturgy of days, her book of hours, has degenerated into a phrase-book of the  glib and trite. The common has coarsened into the commonplace. Her words have  lost their gravitas; they float too easily up and away in an atmosphere of self-absolution.  This is a world in which Hamlet will need to put an antic disposition on, in  order to defy the gravity-defying abrogation of tragedy all around him. To  bring the tragedy back into focus he&rsquo;ll have to become his own clown, for he  kills the only other candidate for the post in the shape of Polonius, though he  does subsequently stare into the blank sockets of another one&rsquo;s skull and finds  some hard, unwarming humour there:</p>
            <p>&nbsp;&nbsp; Alas, poor Yorick. I knew him, Horatio, a  fellow of<br>
  &nbsp;&nbsp; infinite jest, of most excellent fancy. He  hath bore<br>
  &nbsp;&nbsp; me on his back a thousand times, and now -  how abhorred<br>
  &nbsp;&nbsp; in my imagination it is. My gorge rises at  it. Here hung<br>
  &nbsp;&nbsp; those lips that I have kissed I know not how  oft. Where<br>
  &nbsp;&nbsp; be your gibes now, your gambols, your songs,  your flashes<br>
  &nbsp;&nbsp; of merriment, that were wont to set the  table on a roar?<br>
  &nbsp;&nbsp; Not one now to mock your own grinning? Quite  chop-fallen?<br>
  &nbsp;&nbsp; Now get you to my lady&rsquo;s chamber and tell  her, let her <br>
  &nbsp;&nbsp; paint an inch thick, to this favour she must  come. </p>
            <p>Was  Hamlet, with his emblem-book ribaldry, paranoid to see all humanity through the  optic of the skull, to read it backwards like this from posthumous silence to  natal squeal? By the same ironic reversal he sees through the lovely charms of  Ophelia to the unloving schemes of her manipulative father, then he kills him,  which in turn kills her. Whether his mind-set could be termed paranoid depends  on the facts, but not merely upon them, for it also depends on which  perspective we choose - from which stance we elect to focus the facts. It could  after all be the case that the Ghost has been providing Hamlet with spurious  information; could be that this is a malignant spirit of that superstitious  medievalism which reformed religion had seemingly purged away. Hamlet himself  considers this possibility, though not for long. Only by asking murderous  questions can he actually discover the truth. In dramatic and psychological  terms, he must behave like a paranoiac in order to prove that he isn&rsquo;t one.  Establishing the facts in such a theatre of battle can be lethal.</p>
            <p>The  survival strategies of what is clinically deemed to be paranoia and those of  the labouring imagination in the era of modernity would appear to have a great  deal in common. David Swanson in <em>The  Paranoid</em> characterised paranoia as being constituted by the following  characteristics. (1) A projection outwards on to the world of self-criticism.  (2) A conviction of the hostility of exterior reality towards the subject. (3)  A profound suspicion of the world and its intent, often resulting in the  discovery of elaborate schemes of esoteric malice. (4) A marked conviction of  the centrality of the subject. (5) Systematic, and frequently plausible,  delusions. (6) The great fear of having one&rsquo;s own autonomy constantly  undermined. (7) An inflated and deformed sense of self-worth, exacerbated by a  sense of imputed inferiority.</p>
            <p>All  seven of these characteristics could be ascribed to much of the work, and much  of the lives, of Baudelaire and Rimbaud. Does that then entail the inauguration  of modernist poetry being facilitated by paranoia? Is there a fundamental link,  in the era of modernity at any rate, between the paranoid and the poetic? </p>
            <p>Paranoiacs  make complete sense of their world, even if they are forced to do so by anamorphic projection. &lsquo;Only  connect&rsquo; <em>Howard&rsquo;s End</em> eirenically enjoins us, and the paranoiac and the poet  immediately nod in agreement, however far they may be from the liberal  declivities of Forster&rsquo;s Cambridge (Leavis&rsquo;s Cambridge, a spiritual laager against  both encroaching incivility and Bloomsbury insouciance, may be nearer the  paranoid mark). And if the only sense that can be made is one characterised by  hostility and suspicion, if the objective reality confronted by the writer is belittling in both its scorn and its enticements, then poiesis and paranoia  must share the same starting-point. Like Mandelstam&rsquo;s bees, they must both  weave the honey back to sunlight or be stuck in amber forever. Hamlet&rsquo;s  disproportionate consciousness in regard to the action of the play (which some  have found a fault, others a prophetic imbalance) starts to appear as the  herald of modernity. Paranoia in its strategies of defence and interpretation  already has something in common with certain modern literary strategies, and  that is before the conscious deployment of paranoia as a writing strategy. </p>
            <p>John  Gardner&rsquo;s <em>Grendel</em> might well turn out  to have been a far more influential text than is often acknowledged. It  achieved a particular tone which has been much imitated since, though seldom  matched by the same consistency of hostile estrangement, a lexicon and a syntax  of disenchantment. By grafting the human consciousness of isolation and  alienation on to the inhuman subjectivity of Grendel, an entirely cogent and  entirely belligerent view of humanity is facilitated. Grendel combines the  instinctive potency of a non-linguistic creature with all the world-weariness  of a highly sophisticated linguistic one. The effect is as if Jacques in <em>As You Like It</em> had been infused with the  demonic energy of Satan in the first books of <em>Paradise Lost</em>. Gone is the salty collective heroism of the Beowulf  poet, however elegiac; instead humanity is viewed dyspeptically, as by one  outside the magic ring of its myths and comforts, and yet knowingly, as though  by a cynical insider. This allows for a peculiarly effective purchase on the  human agents in the original poem. This optic provides an unblinking meditation  upon the self-serving, self-deceiving, self-mythologising ways of men. This  narrative need never be compromised by charity. We are always seeing the skull  here, but like a revenant from an emblem book, it howls.</p>
            <p>Grendel  is a philosopher in his flinty isolationism; he is a solipsist of bestiality  and a poet of natural vastation:</p>
            <p>&nbsp;&nbsp; I understood that, finally and absolutely, I  alone<br>
  &nbsp;&nbsp; exist. All the rest, I saw, is merely what  pushes me,<br>
  &nbsp;&nbsp; or what I push against, blindly - as blindly  as all<br>
  &nbsp;&nbsp; that is not myself pushes back. I create the  whole<br>
  &nbsp;&nbsp; universe, blink by blink.-An ugly god  pitifully dying <br>
  &nbsp;&nbsp; in a tree!&nbsp;&nbsp;&nbsp;&nbsp; </p>
            <p>There  is a sadness to the text, a melancholy tone that in fact conjures the elegiac  timbre of much Old English verse, with its <em>ubi  sunt</em> formulae, its sense of a world almost devoid of men, a world captured  in <em>The Wanderer</em> and <em>The Seafarer</em> and parts of <em>Beowulf </em>itself.</p>
            <p>The  allegorised paranoiac who is Grendel permits a high degree of what the Russian  Formalists called defamiliarization, that distancing and alienating optic which  Swift employed so startlingly in <em>Gulliver&rsquo;s  Travels</em>. Everything that might be seen in standard perspective is viewed  instead through the anamorphic projection. Many of Ted Hughes&rsquo; animal poems do  precisely the same thing.</p>
            <p>Thomas  Pynchon&rsquo;s <em>The Crying of Lot  49</em> is also an allegory of paranoia, but of a very different sort. Here the  picaresque narrative of modernity gradually reveals a secret society, held  together by codes and cryptic assignations, and through the gradual revelation  of this invisible fraternity and sorority the oppressive features of the  greater society are made manifest. Oedipa Maas, the book&rsquo;s heroine (though no  more heroic a heroine than Leopold Bloom was a hero) comes to assemble in her  mind the significance of the Tristero from the fragmentary clues she is given.  The Tristero provide the valency of the book&rsquo;s paranoia: they are either the  outlaw rebellion which a system of total control has engendered, or they are  the symptoms of Oedipa&rsquo;s increasingly frenetic mental collapse. The book&rsquo;s  ambiguity leaves open either reading. What the Tristero represent, assuming  that they have a reality outside Oedipa&rsquo;s mind, outside her obsessive making of  connections, is the need to win back the basic terms of communication from a  state which has seized the entire infrastructure of intercourse for its own  consolidation. The Tristero represent, even embody, a form of communication  outside the control of the state. They are epistolary bandits. In discovering  what they mean Oedipa comes to understand for the first time what the society  to which they are opposed means. She learns at last to read: she discovers  vernacular hermeneutics.</p>
            <p>Reading  itself, the battle between the authorised versus the unauthorised version, is  often a key thematic of the paranoid text. In Nabokov&rsquo;s <em>Pale Fire</em>, the strategy of reading itself is paranoid, though  paranoid in the manner of many Freudian readings, which is to say refusing to  allow for the possibility of the random or gratuitous. Contingency, that which  is neither impossible nor forbidden, has no place. There are no grace notes,  only symptomatic expressions of the deviously self-revealing subject. All  manifest expressions carry within them their own coded esoterica. The paranoid  text, like the paranoid world, is claustrophobic with meaning. It is  suffocatingly full of intention.</p>
            <p>In  Don De Lillo&rsquo;s <em>Running Dog,</em> the  sought-for pornographic film of Hitler operates thematically as emblematic of  the pornographic pull which the subject of Nazism exerts on our present day  media. It is as though the dark secret of history were here to be revealed, in  the demonstrably, nakedly human aspects of history&rsquo;s most sought-after demonic.  It is as though there is a secret interior to humanity&rsquo;s chronicle, a kernel of  esoterica, and an inverse grail quest might lead us at last to discover the  arcana of villainy, much as we enter into that realm with Shakespeare&rsquo;s Richard  III, though Richard himself is not paranoid: in that play we merely become  privy to the monstrous instrumentalism of a particular king&rsquo;s mind as it  applies itself to history.</p>
            <p>Shakespeare  himself would not of course have used the word paranoia, whose first usage is  listed in the OED as dating from 1857. But in the etymology of a mind beside  itself, even beyond itself, he would have entirely understood the condition,  even if he himself would have applied the terminology of passions to it. If  Hamlet is paranoid, he has contrived to be so, though the stance once adopted  takes on its own momentum. He had to be beyond (para) the <em>nous</em> of a society so resolutely minded to stick to its slothful  forgetfulness. He becomes paranoid in reaction to the cultural and moral  catatonia all around him, the prison that is Denmark. <br>
  &nbsp;&nbsp;&nbsp;&nbsp; <br>
              Is  Lear paranoid? His love-test might be seen as the confrontation of unmediated  absolutism - emotional as well as political - with newer, mediated and  negotiated forms just then coming into being. What is certain is that it is  impossible for Lear to come to know himself without being shorn of his power;  his self-knowledge is a catastrophic self-abasement, as catastrophic in its way  as Hamlet&rsquo;s action against the king, when it finally comes. What supervenes at  the end of <em>Hamlet</em> is the reign of  Fortinbras. Perhaps accommodation might have been a more sensible strategy - it  would certainly have been a less lethal one. And Ophelia might have been  married instead of buried. But then paranoia and trimming are incompatible.<br>
  &nbsp;&nbsp; <br>
              Returning  to DeLillo, he exemplifies a strand in American culture which might be  described less as post-war, post-Bomb or post-modernist, than as post-Dallas.  The killing of JFK, and the widespread incredulity at the conclusions of the  Warren Commission, have probably fuelled the paranoid element in American life  as much as the perception of the internecine politics of the Vietnam War. The  inheritance is there not only in films like Oliver Stone&rsquo;s <em>JFK</em>, which deals directly with the subject, but also in others like  Francis Ford Coppola&rsquo;s <em>The Conversation </em>which  feed upon the general sense of pervasive, state-organised deception. Paranoid  culture gorges on the notion that those in power are mired in mendacity, and  the greater their resources the more all-pervasive their lies are likely to be.  DeLillo himself tackled the theme in <em>Libra</em>,  a book which is simultaneously a study and a product of the paranoid strain in  modern writing. In <em>Mao II</em> the writer  portrayed is so bitterly estranged from the reality that is his subject, that  when he re-enters it, it promptly kills him. It was only his Howard  Hughes-style paranoid reclusiveness that had allowed him to go on living at  all.<br>
  &nbsp; <br>
              It  soon becomes apparent that in finding parallels between certain forms of  literary strategy and paranoia the problem is not so much searching for what to  include as deciding on what to leave out. Some texts are easy. <em>The Ordeal of Gilbert Pinfold</em>, for  example, is an entirely logical paranoid book in that it merely personifies and  apotheosizes the gallimaufry of prejudices that constituted Evelyn Waugh. His  own hatreds at last break free and gain a kind of autonomy. They turn on him  and he merely records their speeches. In <em>Hadrian  VII</em> Frederick Rolfe created an exemplum of sacerdotal paranoia which  permits him to revenge himself upon the church which terminated his clerical  ambitions, by re-fashioning it until it is fit to receive him as pope.<br>
  &nbsp; <br>
              Is  there an element of paranoia in Emily Dickinson, from her apocalyptic  punctuation to the questions that recur in her letters? How do they (i.e., her  neighbours) have the strength, she asks, to tie their shoes in the morning,  addressing that great eclipse they call God? And what about <em>Moby Dick</em>? For Ahab the world is a white  whale, it is the shape into which a single white whale has now riddled itself;  the world must be crossed and re-crossed until that shape, like the sculpture  hidden in Michelangelo&rsquo;s white marble, emerges. This obsessiveness, this  persecuted and persecutory spirit, redeems Ahab from the mere utility of  slaughter. The unanswerability of his passion makes him the whale&rsquo;s equal and  finally, as the great white shape descends into its formless habitat with its  one-legged captive, the whited monster&rsquo;s groom. Ahab&rsquo;s lethal romance with the  whale is a celebrated mourning for his wound; his fascination is with the world  as a hole into which the whale has disappeared. The ocean is a constantly  shifting hole, a hole forever filled in by tides and observation, and forever  capable of rendering forth the longed-for object of desire and loathing.</p>
            <p>Fascination  is still rooted through its etymology to enchantment and witchcraft.  Fascination implies the sinister for enchantment always implies danger and  powers beyond human control. And paranoia in fiction always involves a sense of  heroic isolation; the discovery of grave significance in every trivial  occurrence; a sense of the malice of surrounding reality; most relentlessly of  all, it involves suspicion. On this account it is worth remarking that the  history of Freudianism represents one of the greatest texts of paranoia of our  time, at its heart the embattled and persecuted figure of Freud himself in his  lonely confrontation with the sphinx and her mystery. Just as the history of  dialectical thought is the course of a particular trajectory of suspicion,  finding in all seemingly harmonious wholes hidden conflicts and warring  parties.</p>
            <p>At  its best, as in Hamlet&rsquo;s case, the paranoid stance becomes an aggressive  heuristic principle. It <em>will</em> get to  know the truth, as Oedipa Maas perhaps begins to discover it in <em>The Crying of Lot  49</em>, however great the odds are against the revelation. At stake ultimately  is the question whether or not there is something hidden, whether or not the  paranoid stance justifies the energy it must expend. In Hamlet&rsquo;s case there  was, so his grave suspicion was not merely a paranoid symptom but a justified  response, however &lsquo;paranoid&rsquo; his behaviour subsequently might have been.</p>
            <p>There  is a story by Borges called <em>Deutsches Requiem</em>, collected originally in <em>The  Aleph,</em> in which Otto Dietrich zur Linde recounts his Germanic lineage and  explains his history, including the fact that he is to be executed the  following day. He makes sense of his life and the lives of his forebears, of  the life of everyone in the world in fact, in terms of the Nazism to which he  subscribes. Its temporary failure, and the temporary success of the masters of Nuremburg,  is of no account: its truth is inextinguishable. <em>Deutsches Requiem</em> is in one  sense a classic paranoid text, not least in its powerful way of making sense of  everything. The anamorphic projection holds sway. Only connect.<br>
  &nbsp;&nbsp; <br>
            It  is disturbing in the way DeLillo&rsquo;s <em>Libra</em> is or Shakespeare&rsquo;s <em>Hamlet </em>might well  have been to its contemporaries. Did the Reformation really abolish purgatory  and its unquiet spirits? Did the Warren Commission really lay to rest the ghost of the  Kennedy assassination? The paranoid vision deliberately employed uses  anamorphic projection to discover what more conventional perspective cannot; it  uses indirections to find directions out, as Polonius, just as devious in his  own way, suggested. The best paranoid writing always raises a question about  history. Borges&rsquo; Otto Dietrich zur Linde was fictional, but Magda Goebbels  wasn&rsquo;t. She slaughtered her children, not in rage at her lover like Medea, but  in quiet protest at the very notion of a world without Hitler. So her final act  was to keep her little ones from a de-Nazified future unfit to inherit them. </p>
            <p>In <em>Totem and Taboo</em>, Freud writes: &lsquo;It  might be maintained&hellip;that a paranoid delusion is a caricature of a philosophical  system.&rsquo; The same urge exists in both to make sense of the world, to find  connections where others have found none. And a further similarity exists in  terms of modern philosophy, in that the starting-point of both is what Ricoeur  calls a hermeneutics of suspicion. Here Pynchon is astute in finding the  opposite of paranoia not in normality but in what he calls anti-paranoia: the  inability to find any connections at all. Eliot evoked this state, a species of  intellectual listlessness and separation, in <em>The Waste   Land:</em></p>
            <p>&nbsp;&nbsp; On Margate  Sands.<br>
  &nbsp;&nbsp; I can connect<br>
  &nbsp;&nbsp; Nothing with nothing.<br>
  &nbsp;&nbsp; The broken finger nails of dirty hands.<br>
  &nbsp;&nbsp; My people humble people who expect<br>
  &nbsp;&nbsp; Nothing.</p>
            <p>The  paranoiac expects everything; expects reality to be pleromatic. But then so  does the poet and the fiction writer and the religious ecstatic. Pynchon himself  began with a highly negative attitude towards paranoia, but has gradually come  to sympathise more with it. He seems to feel that given the nature of American  reality, paranoia is often the only intelligent response, since there are  tranches of hidden information to which the average citizen is denied access.  Reality often constructs its own elaborate devices, which might only allow a  paranoid interpretation. Some thirty years ago the rumour started to go around  that the CIA had attempted to kill Fidel Castro by poisoning his beard. This  was described as being at the furthest extremity of&nbsp; conspiracy theorising. Philip Agee and others  have now provided memoirs, and we tend to assume that the plots were hatched,  and sometimes acted upon. A similar shroud of sinister bafflement surrounds  Timothy McVeigh and the Oklahoma  bombing. In Elohim   City there was a paid  informer for the FBI, who warned them in advance of the plan. There may have  been another, Andy Strassmeir, who actively took part in engineering the attack,  but who has mysteriously never been interviewed (or never on record anyway) and  returned home safely to Germany. He had been a soldier in the German army, and  his father was a member of the German government. Faced with such information,  the mind resorts to strategies which are traditionally labelled paranoid. For  the fiction writer to portray such a reality, she or he must also portray a  state of mind which makes paranoid connections, because those are the only  connections open to it. The problem is the same as that with Hamlet: can you  put an antic disposition on without letting it become an integral part of your  personality? For how long can you portray the paranoid vision with shrewdness  and sympathy before paranoia starts to seep into your own psychic machinery?</p>
            <p>The  filament that separates the paranoiac from the writer of paranoid fictions is,  of course, irony. In David Foster Wallace&rsquo;s story <em>The Depressed Person</em>, the  narrator comes, adjectivally and adverbially, to identify herself as the depressed  person supposedly being clinically described. By her relentless view of the  world as a therapeutic theatre in which she is the central agent she comes to  alienate the reader, who looks on in horrified fascination at this monster of  self-pity and self-regard. Her therapist is bereaved and fatally ill, but this  is read by the depressed person merely as a further assault upon her rightful  demands for attention and succour. But where is the writer here? A trench of  irony evidently separates the paranoiac narrator from the supplier of words.</p>
            <p>Irony  is the <em>agent provacateur</em> of the  suspecting glance. The word contains within it the original Greek sense of  dissembling and dissembler. This is all very well as long as there is behind  the dissembling and untrustworthy voice an ultimate level voice which  vouchsafes reality. Irony is then a tactic contained within a larger strategy  which is unironic. This seems to have been Pynchon&rsquo;s earlier ironic mode. But  irony is not without its problems. The gap of credibility between the  information we are provided and our ability to accept it can widen with  vertiginous suddenness. This is what is referred to in philosophy as  infinitized irony. There is no ultimate reference which relativizes all the  ironic material and provides an ultimate, trustworthy version of reality. There  is no larger perspective within which the anamorphic projection can be  contextualized.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>
              The  paranoid vision, when it stops being merely a figural strategy in the writer&rsquo;s  terms of deployment, can find itself within the infinitized terms of ironic  suspicion, can feel as though, as one writer put it, American society is coming  up with more powerful fictions than American fiction. In what is sometimes  referred to as the condition of post-modernity, it seems to be reality itself  which has become ironic with its readers. Its readers, of course, have no  choice but to go on until the end of the text, because the text is their lives.  A crucial element of the paranoid vision is that one element of the interlinear  text that we call reality has been held back, is being hidden or disguised,  making it impossible to translate the data with accuracy. Tradition is being  imposed by state authority. But somewhere hidden in modernity&rsquo;s metropolis  there is the grail of the <em>editio princeps</em>,  or the hidden manuscript, or the extra layer of language, that will provide the  clue. All we have to do is find it.</p>
            <p>George  Smiley in <em>Tinker, Tailor, Soldier, Spy</em> behaves like the classic clinical paranoiac, distrusting everyone and everything  about him, suspecting plots and dissembling from every angle. One of his  recurring questions, the lack of an answer to which deepens his suspicion, is  who is the translator of Merlin, the new source of information regarding the  armed forces of the Soviet Union. All such  sources have to be translated, and without knowing who is doing the translating  you cannot know what your true source of information is. You have lost one  element of the interlinear text. Reality&rsquo;s mediation is hidden. Smiley isn&rsquo;t a  paranoiac, of course, because his suspicions are proved to be grounded in  reality. But then we did finally discover that the CIA had in fact attempted to  assassinate Castro by poisoning his beard, so that conviction wasn&rsquo;t paranoid  either, retrospectively. Whether a particular vision is or is not paranoid  depends ultimately, not upon all the characteristics ascribed to paranoiacs,  but to the facts of the situation to which they are responding. As long as  elements of the facts are missing, the interlinear text is incomplete. We need  the Rosetta Stone if we are ever to fathom the hieroglyphs.<br>
  &nbsp;<br>
              The  decipherment of hieroglyphs is in fact a classic paranoid trope. Pynchon is  quite explicit about it in <em>The Crying of Lot 49</em>. After Oedipa has driven to San Narciso we are  told: &lsquo;She looked down a slope, needing to squint for the sunlight, on to a  vast sprawl of houses which had grown up all together, like a well-tended crop,  from the dull brown earth; and she thought of the time she&rsquo;d opened a  transistor radio to replace a battery and seen her first printed circuit. The  ordered swirl of houses and streets, from this high angle, sprang at her now  with the same unexpected, astonishing clarity as the circuit had. Though she  knew even less about radios than about Southern   Californians, there were to both outward patterns a hieroglyphic  sense of concealed meaning, of an intent to communicate. There&rsquo;d seemed no  limit to what the printed circuit could have told her (if she had tried to find  out); in her first minute of San Narciso, a revelation also trembled just past  the threshold of her understanding. Smog hung all round the horizon, the sun on  the bright beige countryside was painful; she and the Chevy seemed parked at  the centre of an odd, religious instant. As if, on some other frequency, or out  of the eye of some whirlwind rotating too slow for her heated skin even to feel  the centrifugal coolness of, words were being spoken. She suspected that much.'  This is the beginning of a pattern recognition, an occult perception, which  must re-arrange reality in its entirety. All the information is there: one&rsquo;s  hermeneutic technique must be up to de-coding it. But that requires induction  to the society.</p>
            <p>In  the case of the Oklahoma bombing, the missing elements of the interlinear text  would be as follows: the identity of John Doe II, seen by many witnesses; the  involvement of the FBI in planting agents in Elohim City, who may even have  been <em>agents provocateurs</em>; the curious  role of Andy Strasmeir and the even more curious lack of interest in him on the  part of the FBI. Those who hold conspiracy theories about all this would only  be exhibiting paranoid tendencies if they are proved wrong; if they are proved  right, then the rest of us were suffering from Pynchon's&rsquo;anti-paranoia, connecting  nothing with nothing, insisting that the world is empty of meaning when it is  in fact full of unread meanings. We&rsquo;re on Eliot&rsquo;s Margate Sands, or in Hamlet&rsquo;s  Denmark.</p>
            <p>The  metaphoric reading of Oklahoma  might be as follows. In <em>Of Being Numerous</em> George Oppen wrote of America:</p>
            <p>&nbsp;&nbsp; Obsessed, bewildered</p>
            <p>&nbsp;&nbsp; By the shipwreck <br>
  &nbsp;&nbsp; Of the singular</p>
            <p>&nbsp;&nbsp; We have chosen the meaning<br>
            &nbsp;&nbsp; Of being numerous.</p>
            <p>In  the ancient tradition of rhetoric of Cicero (<em>De Inventione)</em> and Sextus Empiricus (<em>Against the Grammarians</em>), <em>fictio</em> was placed midway between <em>historia</em> and <em>fabula</em>. It wasn&rsquo;t tied to the  actual events in the way that history was, but it didn&rsquo;t have the freedom of  invention of fable and myth either: it needed to qualify to be taken seriously  by its verisimilitude. In some way it needed to be like life. Insofar as  paranoid fictions are compelling, it is because their narrative is in some  sense structurally homologous with some, or many, aspects of life as  experienced. They mimic the way we feel reality itself is mediated to us  through dissembling voices; they convey the sense that reality itself is  treating us ironically. But if reality has become ironic then where is the  unironic voicing of actuality that can vouchsafe the truth? It has fled to the  realm of secrets, the secrets of the heart and mind, or the inner chamber of  the secret society. The obverse of every paranoid vision of deceit and  manipulation is the secret world of truth. If <em>Moby Dick</em> can be classified as in some way a paranoid text, it is  at least in part because of that moment when the Pequod&rsquo;s crew take the vow  that Ahab offers them. In that evangelical scene of collective frenzy they  separate themselves from the rest of the world, from Starbuck&rsquo;s rational  urgings to hunt whales solely for profit. They enter the world of Ahab&rsquo;s  monomania. Within pages we hear of the white whale&rsquo;s intelligent malignity, and  at that point what is once more conjured forth is the world of demonology,  whose premise is that every inch of creation is claimed by God and his angels  and counterclaimed by Satan and his devils. Yet if Melville had merely written  of angels and devils he would have left the world of fiction and entered the  world of fable. The same is true of Dostoyevsky&rsquo;s <em>Demons</em>. Fiction requires verisimilitude. It must, as Hamlet put it,  hold the mirror up to nature. There has to be sufficient correspondence with  observable reality to provide the basis for transcending the empirical with  fiction. (Interestingly, the main attacks upon Pynchon&rsquo;s work tend to focus on his  lack of verisimilitude, even though that quality is evidently a highly  deliberated one. Sometimes his writing has more in common with the classic  strategy of surrealism: highly naturalistic detail within seemingly impossible  juxtapositions. Eustace in Arthur Hugh Clough&rsquo;s <em>Amours de Voyage</em> fears that what is called love is not love at all  but merely juxtaposition and facticity. The Surrealists acted as though this  were true not merely of love but of life itself in all its aspects.)</p>
            <p>Here  is a description of contemporary reality: &lsquo;All power is in the hands of  paranoiacs.&rsquo; This was heartfelt and came from the pen not of Pynchon or  DeLillo, but of that apparently most unparanoid literary strategist, George  Orwell. He wrote it in his Diary at the height of the war in 1942. We are  oppressed by reality. Pychon is more explicit in <em>V</em>: &lsquo;About the paranoia often noted under the drug, there is nothing  remarkable. Like other sorts of paranoia, it is nothing less than the onset,  the leading edge, of the discovery that everything is connected, everything in  the creation&hellip;&rsquo; Paranoia then is one way, a particularly defensive and offensive  one, of connecting everything up. The paranoiac is free from the irony which  the writer employs. The writer too sees connectedness everywhere, but the  summation at least of this connectedness must be ironized, even if much along  the way has not been. Poiesis can often be a species of non-psychotic paranoia.  In this it is responding to what Walter Benjamin called the decay of  experience. So much of the experience of modernity is fragmentary, fleeting,  disconnected. It cannot be incorporated into the labyrinth of memory traces;  the devices of consciousness merely dispose of it. Wisdom is replaced by  information. Much of contemporary paranoia is a response to information  overload. There is so much information provided that not only can it not be  transmuted into wisdom; it cannot even be digested for the purposes of utility.  Much information, while not untrue, is also provided to mislead or baffle. It  may be verifiable information but it is provided at the wrong time and in the  wrong place, often to prevent the acquisition of more pertinent  information.&nbsp; Information, to be  disinformation, does not have to be untrue, merely deliberately misplaced.</p>
            <p>One  of the greatest cultural responses to the paranoid vision, the paranoid  reality, is surely <em>Dr Strangelove</em>. In  a sense the film is a burlesque of paranoia, but it is no less paranoid for  that. The world it emblematises reciprocally emblematises itself in the warning  the Pentagon insisted must be inserted into the film, to the effect that the  film&rsquo;s events were impossible, and its protagonists unanchored in fact. But the  thread of paranoid dread underlying Kubrick&rsquo;s film treatment of the original  book by Peter George, was the information Kubrick uncovered that there were  many physicists who, prior to the explosion of the first hydrogen bomb, were  firmly of the opinion that such an explosion had a high potential to inaugurate  a chain-reaction that would wipe out the planet. The fact that the tests went  ahead anyway registered with Kubrick the extent of the globalised insanity  which is called the modern world. It was a world which prompted a paranoid  response, since a world so anchored in its own paranoia prompts a paranoid  reaction large enough to take its measure. The name of the insane officer  played by Sterling Hayden is Jack D.Ripper. The whole film is in fact a vast,  but very serious joke. It is a paranoid fantasy in a world that is just capable  of making it come true. The first half of the film is a desperate attempt to  establish the facts beneath the deceptions. This is the paranoid quest <em>sans pareil</em>, for the strength of  paranoia is also its greatest weakness: it makes sense of things with manic  investigative brio. In fact it often makes more sense of things than is there  to be made. But not always.</p>
            <p>If  the FBI and the AFT between them decide that the Branch Davidian sect at Waco don&rsquo;t fit the permitted rubric &lsquo;of being numerous&rsquo;  then the men, women and children of Waco  are incinerated. It was this specific event that impelled McVeigh, with or  without accomplices, to his own outrage. It is not that the events at Waco were under-reported.  If anything the opposite was the case. But in the mass of information that came  forth, the judgments were turned in the wrong direction: against the Branch  Davidian sect rather than against the murderous actions of the state  authorities. The information, in other words, ceased to be true information and  became instead what cyberneticists call &lsquo;noise&rsquo;. It is this noise which the  Tristero in <em>The Crying of Lot 49</em> are intent upon excluding from their  communications. They are said to be &lsquo;truly communicating whilst reserving their  lies, recitations of routine, arid betrayals of spiritual poverty, for the  official government delivery system.&rsquo; Adjusting the noise-to-signal ratio is an  act against the state. The lines of the official communications system are so  full of noise that true information is swamped, baffled, obscured. Information,  to become valid once more, must become unofficial, to the point of being  outlawed. It becomes an anamorphic projection which can only be detected if you  have the clue, the interlinear text, the <em>editio  princeps</em> which has been hidden for so long. This clue was once the word  clew, and it made up Ariadne&rsquo;s bobbin, the same one she handed to Theseus so  that he might enter the labyrinth and slaughter the beast that was eating the  island&rsquo;s children.</p>
            <p>The  Warren Report on the Kennedy assassination might be taken as one of the  founding texts of American paranoid fiction. It opened a gap between  information and credibility into which the fiction and the irony have never  ceased rushing ever since. The present status of the commissions and reports  into 9/11 doesn&rsquo;t give much hope that they will do more than fill a parallel  slot in the psyche. Here is a vision that might be of relevance: </p>
            <p>&nbsp;&nbsp; Falling towers<br>
  &nbsp;&nbsp; Jerusalem Athens Alexandria<br>
  &nbsp;&nbsp; Vienna London<br>
  &nbsp;&nbsp; Unreal</p>
            <p>This  is the end of the civilisation we have known, as envisaged by T.S.Eliot in  1922. And a video could be played of the twin towers falling, to two different  audiences, without any soundtrack or form of indication as to the required  response. One might be played in an auditorium somewhere in New   York and the other on an estate in a run-down part of Coventry&rsquo;s inner city.  The tears of the one audience could well be replaced by the cheers of the  other. Two perspectives so radically opposed are in a state of contradiction.  You can&rsquo;t see both the rectified vision and the anamorphic projection at the  same time. It&rsquo;s like the duck/rabbit image that so obsessed Wittgenstein all  his life. You can choose to set up the parameters of your mind thus or thus,  but you simply cannot combine the two options simultaneously. Such images are  liminal hieroglyphs. They point simultaneously in two directions, like Janus on  the demarcation line, and you cannot elect to go in both directions at once.</p>
              The  question then is this: is your version of reality the standard model, or is it  an anamorphic projection, encrypted so as to baffle the outsider? Is that  paranoia we are witnessing or a justified rage against injustice? The Pynchon  and the Kubrick versions remain fictions, which is another way of saying that  irony protects us there against too much actual damage. Fiction as  non-psychotic paranoia, then. But irony didn&rsquo;t protect Magda Goebbels&rsquo;  children. Which only goes to show that when history itself turns paranoid, it  outruns the imaginings of Euripides.</p>
            <p>Dissimilar  in many other respects, Emily Dickinson and Bob Dylan are both artists of the  anamorphic projection, the occulted glimpse. They both share the conviction  that something in the nature of modern reality defeats the artist if met head  on. Here is Dickinson:</p>
            <p>&nbsp;&nbsp;  Tell all the truth but tell it slant<br>
                &nbsp;&nbsp;  Success in circuit lies<br>
                &nbsp;&nbsp;  Too bright for our infirm delight<br>
                &nbsp;&nbsp;  The truth&rsquo;s superb surprise</p>
            <p>And here is Dylan:</p>
          
            <p>&nbsp;&nbsp;  The truth was obscure<br>
                &nbsp;&nbsp;  Too profound and too pure<br>
                &nbsp;&nbsp;  To live it you had to explode</p>
          <p>&nbsp;</p></td>
          <td><img src="/images/spacer.gif" width="1" height="46" border="0" alt=""></td>
        </tr>
        <tr> 
          <td height="103"><img src="/images/spacer.gif" width="1" height="103" border="0" alt=""></td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<?php include("../../foot.php"); ?>
</body>
</html>
